### ISSUE TITLE
add an ssh target

### ISSUE THREAD

**Issue by tshirtman** [kivy/buildozer#1]
Sometime using adb is not convenient, and with an ssh-server installed on the android device, it's possible to do everything adb can do, allowing to configure such things could be useful, one needs

an ssh server on the device (dropbear is great)
an ssh key added to the ssh server, so the connection is transparent (optional)
a dump of the adb shell "env" command, so everything happens correctly (i usually put this in /sdcard/adb_env)
the ip of the server

then, the apk can be copied other with a command like
`tar -c $apk |ssh root@device_ip 'cd /sdcard/ && tar -x'`

and the apk can be installed with

```
ssh root@device_ip "source /sdcard/adb_env &&\
pm uninstall $package_name &&\
pm install /sdcard/$apk"
```

and the activity started with
`am start -n $package_name/org.renpy.android.PythonActivity -a o    rg.renpy.android.PythonActivity"``

Assuming adb_env is loaded too.

If nobody does, i'll try to do that at some point in the future, if someone wants to do it before, i can help :)
##

**Comment by dessant** [comment]
Should be solved by https://github.com/kivy/kivy-remote-shell.
