### ISSUE TITLE
Kivy app Crashes while import openpyxl

### ISSUE THREAD

**Issue by anooprana985** [kivy/buildozer#1001]
I have been trying to import openpyxl in my main.py file.When i run buildozer android debug everything seems to be working fine.But when i open the app on my android it crashes.Can you help me with finding the solution.

Why can't i import openpyxl.?
When i don't use this module in my main file everthing works good but after importing it the app crashes.

**Comment by tshirtman** [comment]
did you add openpyxl to your requirements line in buildozer.spec ? can you share the buildozer.spec and look for the error in your logcat for the error and share it?

**Comment by anooprana985** [comment]
Yes i have added openpyxl in buildozer.spec file.I am attaching my .spec file.Note that the app runs fine on android when i remove openpyxl from both my main.py file and .spec file.But when i add import openpyxl it crashes on my android but during buildozer android debug process it does not give any errors.
Here is my .spec file :

`[app]

# (str) Title of your application
title = My Application

# (str) Package name
package.name = myapp

# (str) Package domain (needed for android/ios packaging)
package.domain = org.test

# (str) Source code where the main.py live
source.dir = .

# (list) Source files to include (let empty to include all the files)
source.include_exts = py,png,jpg,kv,atlas

# (list) List of inclusions using pattern matching
#source.include_patterns = assets/*,images/*.png

# (list) Source files to exclude (let empty to not exclude anything)
#source.exclude_exts = spec

# (list) List of directory to exclude (let empty to not exclude anything)
#source.exclude_dirs = tests, bin

# (list) List of exclusions using pattern matching
#source.exclude_patterns = license,images/*/*.jpg

# (str) Application versioning (method 1)
version = 1.2

# (str) Application versioning (method 2)
# version.regex = __version__ = ['"](.*)['"]
# version.filename = %(source.dir)s/main.py

# (list) Application requirements
# comma separated e.g. requirements = sqlite3,kivy
requirements = python3,kivy,xlrd,xlsxwriter

# (str) Custom source folders for requirements
# Sets custom source for any requirements with recipes
# requirements.source.kivy = ../../kivy

# (list) Garden requirements
#garden_requirements =

# (str) Presplash of the application
#presplash.filename = %(source.dir)s/data/presplash.png

# (str) Icon of the application
#icon.filename = %(source.dir)s/data/icon.png

# (str) Supported orientation (one of landscape, sensorLandscape, portrait or all)
orientation = portrait

# (list) List of service to declare
#services = NAME:ENTRYPOINT_TO_PY,NAME2:ENTRYPOINT2_TO_PY

#
# OSX Specific
#

#
# author = © Copyright Info

# change the major version of python used by the app
osx.python_version = 3

# Kivy version to use
osx.kivy_version = 1.9.1

#
# Android specific
#

# (bool) Indicate if the application should be fullscreen or not
fullscreen = 0

# (string) Presplash background color (for new android toolchain)
# Supported formats are: #RRGGBB #AARRGGBB or one of the following names:
# red, blue, green, black, white, gray, cyan, magenta, yellow, lightgray,
# darkgray, grey, lightgrey, darkgrey, aqua, fuchsia, lime, maroon, navy,
# olive, purple, silver, teal.
#android.presplash_color = #FFFFFF

# (list) Permissions
android.permissions = WRITE_EXTERNAL_STORAGE

# (int) Target Android API, should be as high as possible.
#android.api = 27

# (int) Minimum API your APK will support.
#android.minapi = 21

# (int) Android SDK version to use
#android.sdk = 20

# (str) Android NDK version to use
#android.ndk = 17c

# (int) Android NDK API to use. This is the minimum API your app will support, it should usually match android.minapi.
#android.ndk_api = 21

# (bool) Use --private data storage (True) or --dir public storage (False)
#android.private_storage = True

# (str) Android NDK directory (if empty, it will be automatically downloaded.)
#android.ndk_path =

# (str) Android SDK directory (if empty, it will be automatically downloaded.)
#android.sdk_path =

# (str) ANT directory (if empty, it will be automatically downloaded.)
#android.ant_path =

# (bool) If True, then skip trying to update the Android sdk
# This can be useful to avoid excess Internet downloads or save time
# when an update is due and you just want to test/build your package
# android.skip_update = False

# (bool) If True, then automatically accept SDK license
# agreements. This is intended for automation only. If set to False,
# the default, you will be shown the license when first running
# buildozer.
# android.accept_sdk_license = False

# (str) Android entry point, default is ok for Kivy-based app
#android.entrypoint = org.renpy.android.PythonActivity

# (list) Pattern to whitelist for the whole project
#android.whitelist =

# (str) Path to a custom whitelist file
#android.whitelist_src =

# (str) Path to a custom blacklist file
#android.blacklist_src =

# (list) List of Java .jar files to add to the libs so that pyjnius can access
# their classes. Don't add jars that you do not need, since extra jars can slow
# down the build process. Allows wildcards matching, for example:
# OUYA-ODK/libs/*.jar
#android.add_jars = foo.jar,bar.jar,path/to/more/*.jar

# (list) List of Java files to add to the android project (can be java or a
# directory containing the files)
#android.add_src =

# (list) Android AAR archives to add (currently works only with sdl2_gradle
# bootstrap)
#android.add_aars =

# (list) Gradle dependencies to add (currently works only with sdl2_gradle
# bootstrap)
#android.gradle_dependencies =

# (list) Java classes to add as activities to the manifest.
#android.add_activites = com.example.ExampleActivity

# (str) OUYA Console category. Should be one of GAME or APP
# If you leave this blank, OUYA support will not be enabled
#android.ouya.category = GAME

# (str) Filename of OUYA Console icon. It must be a 732x412 png image.
#android.ouya.icon.filename = %(source.dir)s/data/ouya_icon.png

# (str) XML file to include as an intent filters in <activity> tag
#android.manifest.intent_filters =

# (str) launchMode to set for the main activity
#android.manifest.launch_mode = standard

# (list) Android additional libraries to copy into libs/armeabi
#android.add_libs_armeabi = libs/android/*.so
#android.add_libs_armeabi_v7a = libs/android-v7/*.so
#android.add_libs_arm64_v8a = libs/android-v8/*.so
#android.add_libs_x86 = libs/android-x86/*.so
#android.add_libs_mips = libs/android-mips/*.so

# (bool) Indicate whether the screen should stay on
# Don't forget to add the WAKE_LOCK permission if you set this to True
#android.wakelock = False

# (list) Android application meta-data to set (key=value format)
#android.meta_data =

# (list) Android library project to add (will be added in the
# project.properties automatically.)
#android.library_references =

# (list) Android shared libraries which will be added to AndroidManifest.xml using <uses-library> tag
#android.uses_library =

# (str) Android logcat filters to use
#android.logcat_filters = *:S python:D

# (bool) Copy library instead of making a libpymodules.so
#android.copy_libs = 1

# (str) The Android arch to build for, choices: armeabi-v7a, arm64-v8a, x86, x86_64
android.arch = armeabi-v7a

#
# Python for android (p4a) specific
#

# (str) python-for-android fork to use, defaults to upstream (kivy)
#p4a.fork = kivy

# (str) python-for-android branch to use, defaults to master
#p4a.branch = master

# (str) python-for-android git clone directory (if empty, it will be automatically cloned from github)
#p4a.source_dir =

# (str) The directory in which python-for-android should look for your own build recipes (if any)
#p4a.local_recipes =

# (str) Filename to the hook for p4a
#p4a.hook =

# (str) Bootstrap to use for android builds
# p4a.bootstrap = sdl2

# (int) port number to specify an explicit --port= p4a argument (eg for bootstrap flask)
#p4a.port =


#
# iOS specific
#

# (str) Path to a custom kivy-ios folder
#ios.kivy_ios_dir = ../kivy-ios
# Alternately, specify the URL and branch of a git checkout:
ios.kivy_ios_url = https://github.com/kivy/kivy-ios
ios.kivy_ios_branch = master

# Another platform dependency: ios-deploy
# Uncomment to use a custom checkout
#ios.ios_deploy_dir = ../ios_deploy
# Or specify URL and branch
ios.ios_deploy_url = https://github.com/phonegap/ios-deploy
ios.ios_deploy_branch = 1.7.0

# (str) Name of the certificate to use for signing the debug version
# Get a list of available identities: buildozer ios list_identities
#ios.codesign.debug = "iPhone Developer: <lastname> <firstname> (<hexstring>)"

# (str) Name of the certificate to use for signing the release version
#ios.codesign.release = %(ios.codesign.debug)s


[buildozer]

# (int) Log level (0 = error only, 1 = info, 2 = debug (with command output))
log_level = 2

# (int) Display warning if buildozer is run as root (0 = False, 1 = True)
warn_on_root = 1

# (str) Path to build artifact storage, absolute or relative to spec file
# build_dir = ./.buildozer

# (str) Path to build output (i.e. .apk, .ipa) storage
# bin_dir = ./bin

#    -----------------------------------------------------------------------------
#    List as sections
#
#    You can define all the "list" as [section:key].
#    Each line will be considered as a option to the list.
#    Let's take [app] / source.exclude_patterns.
#    Instead of doing:
#
#[app]
#source.exclude_patterns = license,data/audio/*.wav,data/images/original/*
#
#    This can be translated into:
#
#[app:source.exclude_patterns]
#license
#data/audio/*.wav
#data/images/original/*
#


#    -----------------------------------------------------------------------------
#    Profiles
#
#    You can extend section / key with a profile
#    For example, you want to deploy a demo version of your application without
#    HD content. You could first change the title to add "(demo)" in the name
#    and extend the excluded directories to remove the HD content.
#
#[app@demo]
#title = My Application (demo)
#
#[app:source.exclude_patterns@demo]
#images/hd/*
#
#    Then, invoke the command line with the "demo" profile:
#
#buildozer --profile demo android debug`

**Comment by tshirtman** [comment]
`buildozer android logcat` will allow you to see the log of error and to see what happens when it crashes, please find the traceback that happens at that point and copy that part here.

**Comment by anooprana985** [comment]
8:16:34.918 29679 29715 V python  : extracting _python_bundle/site-packages/jnius_config.pyc
12-13 18:16:34.918 29679 29715 V python  : extracting _python_bundle/site-packages/openpyxl-3.0.2.dist-info/
12-13 18:16:34.919 29679 29715 V python  : extracting _python_bundle/site-packages/openpyxl-3.0.2.dist-info/INSTALLER
12-13 18:16:34.919 29679 29715 V python  : extracting _python_bundle/site-packages/openpyxl-3.0.2.dist-info/LICENCE.rst
12-13 18:16:34.920 29679 29715 V python  : extracting _python_bundle/site-packages/openpyxl-3.0.2.dist-info/top_level.txt
12-13 18:16:34.920 29679 29715 V python  : extracting _python_bundle/site-packages/openpyxl-3.0.2.dist-info/RECORD
12-13 18:16:34.922 29679 29715 V python  : extracting _python_bundle/site-packages/openpyxl-3.0.2.dist-info/METADATA
12-13 18:16:34.923 29679 29715 V python  : extracting _python_bundle/site-packages/openpyxl-3.0.2.dist-info/WHEEL
12-13 18:16:34.923 29679 29715 V python  : extracting _python_bundle/site-packages/XlsxWriter-1.2.6.dist-info/
12-13 18:16:34.924 29679 29715 V python  : extracting _python_bundle/site-packages/XlsxWriter-1.2.6.dist-info/INSTALLER
12-13 18:16:34.924 29679 29715 V python  : extracting _python_bundle/site-packages/XlsxWriter-1.2.6.dist-info/top_level.txt
12-13 18:16:34.924 29679 29715 V python  : extracting _python_bundle/site-packages/XlsxWriter-1.2.6.dist-info/RECORD
12-13 18:16:34.925 29679 29715 V python  : extracting _python_bundle/site-packages/XlsxWriter-1.2.6.dist-info/METADATA
12-13 18:16:34.926 29679 29715 V python  : extracting _python_bundle/site-packages/XlsxWriter-1.2.6.dist-info/WHEEL
12-13 18:16:34.926 29679 29715 V python  : extracting _python_bundle/site-packages/kivy/

12-13 18:16:36.019 29679 29679 V pythonutil: Library loading error: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/org.test.myapp-1/base.apk"],nativeLibraryDirectories=[/data/app/org.test.myapp-1/lib/arm, /data/app/org.test.myapp-1/base.apk!/lib/armeabi-v7a, /system/lib, /vendor/lib]]] couldn't find "libpython2.7.so"
12-13 18:16:36.019 29679 29679 V pythonutil: Loading library: python3.5m
12-13 18:16:36.020 29679 29679 V pythonutil: Library loading error: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/org.test.myapp-1/base.apk"],nativeLibraryDirectories=[/data/app/org.test.myapp-1/lib/arm, /data/app/org.test.myapp-1/base.apk!/lib/armeabi-v7a, /system/lib, /vendor/lib]]] couldn't find "libpython3.5m.so"
12-13 18:16:36.020 29679 29679 V pythonutil: Loading library: python3.6m
12-13 18:16:36.022 29679 29679 V pythonutil: Library loading error: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/org.test.myapp-1/base.apk"],nativeLibraryDirectories=[/data/app/org.test.myapp-1/lib/arm, /data/app/org.test.myapp-1/base.apk!/lib/armeabi-v7a, /system/lib, /vendor/lib]]] couldn't find "libpython3.6m.so"
2-13 18:16:36.022 29679 29679 V pythonutil: Loading library: python3.7m
12-13 18:16:36.029 29679 29679 V pythonutil: Loading library: main
12-13 18:16:36.031 29679 29679 V pythonutil: Failed to load _io.so or unicodedata.so...but that's okay.
12-13 18:16:36.032 29679 29679 V pythonutil: Unsatisfied linker when loading ctypes
12-13 18:16:36.032 29679 29679 V pythonutil: Loaded everything!
12-13 18:16:36.032 29679 29679 V SDL     : nativeSetupJNI()
python-installs/myapp/openpyxl/cell/cell.py", line 27, in <module>
12-13 18:16:39.203 29679 29730 I python  :    File "/home/physics/Desktop/test2/.buildozer/android/platform/build-armeabi-v7a/build/python-installs/myapp/openpyxl/styles/__init__.py", line 4, in <module>
12-13 18:16:39.204 29679 29730 I python  :    File "/home/physics/Desktop/test2/.buildozer/android/platform/build-armeabi-v7a/build/python-installs/myapp/openpyxl/styles/alignment.py", line 5, in <module>
12-13 18:16:39.204 29679 29730 I python  :    File "/home/physics/Desktop/test2/.buildozer/android/platform/build-armeabi-v7a/build/python-installs/myapp/openpyxl/descriptors/__init__.py", line 3, in <module>
12-13 18:16:39.205 29679 29730 I python  :    File "/home/physics/Desktop/test2/.buildozer/android/platform/build-armeabi-v7a/build/python-installs/myapp/openpyxl/descriptors/base.py", line 12, in <module>
12-13 18:16:39.206 29679 29730 I python  :    File "/home/physics/Desktop/test2/.buildozer/android/platform/build-armeabi-v7a/build/python-installs/myapp/openpyxl/utils/datetime.py", line 12, in <module>
12-13 18:16:39.206 29679 29730 I python  :  ModuleNotFoundError: No module named 'jdcal'
12-13 18:16:39.206 29679 29730 I python  : Python for android ended.
12-13 18:16:39.273  2276  2276 I NetworkController.WifiSignalController: Change in state to: connected=true,enabled=true,level=2,inetCondition=1,iconGroup=IconGroup(Default Wi-Fi Icons),activityIn=true,activityOut=true,rssi=-66,,ssid="Tech_D5972887",isGigaWiFi=false,isAttWifiCall=false
12-13 18:16:39.373  1911  2641 I WindowManager: WIN DEATH: Window{d4c34f3 u0 SurfaceView - org.test.myapp/org.kivy.android.PythonActivity}
12-13 18:16:39.374  1911  2641 I WindowManager: mPendingRelaunchCount: 0
12-13 18:16:39.374  1911  2641 D WindowManager: remove transit: 2
12-13 18:16:39.374  1911 10678 I ActivityManager: Process org.test.myapp (pid 29679) has died
12-13 18:16:39.375  1911 10678 D ActivityManager: cleanUpApplicationRecord -- 29679
12-13 18:16:39.376  1911 10678 W ActivityManager: Force removing ActivityRecord{c20e676 u0 org.test.myapp/org.kivy.android.PythonActivity t218}: app died, no saved state
12-13 18:16:39.380  1911  9649 I WindowManager: WIN DEATH: Window{4ce61b2 u0 org.test.myapp/org.kivy.android.PythonActivity}
12-13 18:16:39.380  1911  9649 I WindowManager: mPendingRelaunchCount: 0
12-13 18:16:39.380  1911  9649 D WindowManager: remove transit: 2
12-13 18:16:39.380  1911  9649 V SurfaceControlWithBlanks: destroy(), Window{4ce61b2 u0 org.test.myapp/org.kivy.android.PythonActivity}
12-13 18:16:39.383   846   846 I Zygote  : Process 29679 exited cleanly (255)
12-13 18:16:39.400   837   886 I PowerRM : System FW:1 SO:0 GT:0 CAPP:-1 APP:0
[CRASH_REPORT2.txt](https://github.com/kivy/buildozer/files/3960930/CRASH_REPORT2.txt)

**Comment by tshirtman** [comment]
hm, try adding `jdcal` (https://pypi.org/project/jdcal/) to requirements seems like it's missing

**Comment by anooprana985** [comment]
After that the app still crashes.I attaching the new adb logcat file:

12-13 18:59:59.212  4450  4450 V pythonutil: Library loading error: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/org.test.myapp-1/base.apk"],nativeLibraryDirectories=[/data/app/org.test.myapp-1/lib/arm, /data/app/org.test.myapp-1/base.apk!/lib/armeabi-v7a, /system/lib, /vendor/lib]]] couldn't find "libpython2.7.so"
12-13 18:59:59.212  4450  4450 V pythonutil: Loading library: python3.5m
12-13 18:59:59.213  4450  4450 V pythonutil: Library loading error: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/org.test.myapp-1/base.apk"],nativeLibraryDirectories=[/data/app/org.test.myapp-1/lib/arm, /data/app/org.test.myapp-1/base.apk!/lib/armeabi-v7a, /system/lib, /vendor/lib]]] couldn't find "libpython3.5m.so"
12-13 18:59:59.213  4450  4450 V pythonutil: Loading library: python3.6m
12-13 18:59:59.215  4450  4450 V pythonutil: Library loading error: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/org.test.myapp-1/base.apk"],nativeLibraryDirectories=[/data/app/org.test.myapp-1/lib/arm, /data/app/org.test.myapp-1/base.apk!/lib/armeabi-v7a, /system/lib, /vendor/lib]]] couldn't find "libpython3.6m.so"
12-13 18:59:59.215  4450  4450 V pythonutil: Loading library: python3.7m
12-13 18:59:59.221  4450  4450 V pythonutil: Loading library: main
12-13 18:59:59.224  4450  4450 V pythonutil: Failed to load _io.so or unicodedata.so...but that's okay.
12-13 18:59:59.224  4450  4450 V pythonutil: Unsatisfied linker when loading ctypes
12-13 18:59:59.224  4450  4450 V pythonutil: Loaded everything!
12-13 18:59:59.225  4450  4450 V SDL     : nativeSetupJNI()
12-13 18:59:59.225  4450  4450 V SDL     : AUDIO nativeSetupJNI()
12-13 18:59:59.225  4450  4450 V SDL     : CONTROLLER nativeSetupJNI()

12-13 19:00:02.489  4450  4650 I python  :    File "/home/physics/Desktop/test2/.buildozer/android/platform/build-armeabi-v7a/build/python-installs/myapp/openpyxl/styles/alignment.py", line 5, in <module>
12-13 19:00:02.490  4450  4650 I python  :    File "/home/physics/Desktop/test2/.buildozer/android/platform/build-armeabi-v7a/build/python-installs/myapp/openpyxl/descriptors/__init__.py", line 4, in <module>
12-13 19:00:02.491  4450  4650 I python  :    File "/home/physics/Desktop/test2/.buildozer/android/platform/build-armeabi-v7a/build/python-installs/myapp/openpyxl/descriptors/sequence.py", line 4, in <module>
12-13 19:00:02.491  4450  4650 I python  :    File "/home/physics/Desktop/test2/.buildozer/android/platform/build-armeabi-v7a/build/python-installs/myapp/openpyxl/xml/functions.py", line 48, in <module>
12-13 19:00:02.492  4450  4650 I python  :  ModuleNotFoundError: No module named 'et_xmlfile'
12-13 19:00:02.492  4450  4650 I python  : Python for android ended.
12-13 19:00:02.670  1911  9649 I chatty  : uid=1000(system) Binder:1911_20 expire 11 lines
12-13 19:00:02.671  1911  2589 I WindowManager: WIN DEATH: Window{42c13bc u0 org.test.myapp/org.kivy.android.PythonActivity}
12-13 19:00:02.671  1911  2589 I WindowManager: mPendingRelaunchCount: 0
12-13 19:00:02.671  1911  2589 D WindowManager: remove transit: 2
12-13 19:00:02.671  1911  2589 W WindowManager: Force-removing child win Window{e351d38 u0 SurfaceView - org.test.myapp/org.kivy.android.PythonActivity} from container Window{42c13bc u0 org.test.myapp/org.kivy.android.PythonActivity}
12-13 19:00:02.672  1911  1922 I ActivityManager: Process org.test.myapp (pid 4450) has died
12-13 19:00:02.673  1911  1922 D ActivityManager: cleanUpApplicationRecord -- 4450
12-13 19:00:02.674  1911  1922 W ActivityManager: Force removing ActivityRecord{37e1d60 u0 org.test.myapp/org.kivy.android.PythonActivity t239}: app died, no saved state
12-13 19:00:02.676  1911  2589 I chatty  : uid=1000(system) Binder:1911_6 expire 11 lines
12-13 19:00:02.677  1911  2589 V SurfaceControlWithBlanks: destroy(), Window{42c13bc u0 org.test.myapp/org.kivy.android.PythonActivity}
12-13 19:00:02.683   846   846 I Zygote  : Process 4450 exited cleanly (255)
12-13 19:00:02.685  1911 10677 W WindowManager: Failed looking up window
12-13 19:00:02.685  1911 10677 W WindowManager: java.lang.IllegalArgumentException: Requested window android.os.BinderProxy@36da095 does not exist
12-13 19:00:02.685  1911 10677 W WindowManager: 	at com.android.server.wm.WindowManagerService.windowForClientLocked(WindowManagerService.java:11190)
12-13 19:00:02.685  1911 10677 W WindowManager: 	at com.android.server.wm.WindowManagerService.windowForClientLocked(WindowManagerService.java:11181)
12-13 19:00:02.685  1911 10677 W WindowManager: 	at com.android.server.wm.WindowState$DeathRecipient.binderDied(WindowState.java:1900)
12-13 19:00:02.685  1911 10677 W WindowManager: 	at android.os.BinderProxy.sendDeathNotice(Binder.java:688)
12-13 19:00:02.685  1911 10677 I WindowManager: WIN DEATH: null
12-13 19:00:02.686  1911 10677 I WindowManager: mPendingRelaunchCount: 0
12-13 19:00:02.706   872  2051 V Netd    : unexpected event from subsystem cpu
12-13 19:00:02.709   872  2051 V Netd    : unexpected event from subsystem cpu

12-13 19:00:10.665  4758  4758 V pythonutil: Loading library: python2.7
12-13 19:00:10.666  4758  4758 V pythonutil: Library loading error: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/org.test.myapp-1/base.apk"],nativeLibraryDirectories=[/data/app/org.test.myapp-1/lib/arm, /data/app/org.test.myapp-1/base.apk!/lib/armeabi-v7a, /system/lib, /vendor/lib]]] couldn't find "libpython2.7.so"
12-13 19:00:10.666  4758  4758 V pythonutil: Loading library: python3.5m
12-13 19:00:10.667  4758  4758 V pythonutil: Library loading error: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/org.test.myapp-1/base.apk"],nativeLibraryDirectories=[/data/app/org.test.myapp-1/lib/arm, /data/app/org.test.myapp-1/base.apk!/lib/armeabi-v7a, /system/lib, /vendor/lib]]] couldn't find "libpython3.5m.so"
12-13 19:00:10.667  4758  4758 V pythonutil: Loading library: python3.6m
12-13 19:00:10.668  4758  4758 V pythonutil: Library loading error: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/org.test.myapp-1/base.apk"],nativeLibraryDirectories=[/data/app/org.test.myapp-1/lib/arm, /data/app/org.test.myapp-1/base.apk!/lib/armeabi-v7a, /system/lib, /vendor/lib]]] couldn't find "libpython3.6m.so"
12-13 19:00:10.668  4758  4758 V pythonutil: Loading library: python3.7m
12-13 19:00:10.673   848 21856 V AudioFlinger_Tracks: presentationComplete() mPresentationCompleteFrames 15976 framesWritten 10752
12-13 19:00:10.674  4758  4758 V pythonutil: Loading library: main
12-13 19:00:10.674  4677  4703 D Contact : updateContact: contact changed
12-13 19:00:10.676  4758  4758 V pythonutil: Failed to load _io.so or unicodedata.so...but that's okay.
12-13 19:00:10.676  4758  4758 V pythonutil: Unsatisfied linker when loading ctypes

12-13 19:00:13.982  4758  4778 I python  :    File "/home/physics/Desktop/test2/.buildozer/android/platform/build-armeabi-v7a/build/python-installs/myapp/openpyxl/xml/functions.py", line 48, in <module>
12-13 19:00:13.983  4758  4778 I python  :  ModuleNotFoundError: No module named 'et_xmlfile'
12-13 19:00:13.983  4758  4778 I python  : Python for android ended.
12-13 19:00:13.993  2661  2731 D ContactsProvider2ForLG: queryLocal match: 4000 return cursor
[CRASH_REPORT3.txt](https://github.com/kivy/buildozer/files/3961065/CRASH_REPORT3.txt)

**Comment by anooprana985** [comment]
Now i am going to add et_xmlfile in the requirements field.Also this seems to be a major issue:
12-13 18:59:59.212 4450 4450 V pythonutil: Library loading error: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/org.test.myapp-1/base.apk"],nativeLibraryDirectories=[/data/app/org.test.myapp-1/lib/arm, /data/app/org.test.myapp-1/base.apk!/lib/armeabi-v7a, /system/lib, /vendor/lib]]] couldn't find "libpython2.7.so"

**Comment by anooprana985** [comment]
Ok it is working now.After adding et_xmlfile in the requirements.Thank you so much .
Thanks for the help.

**Comment by tshirtman** [comment]
Ok, nice, i wonder if it's a failure of processing dependencies on our side, so i'll leave it open for further investigations.

**Comment by themockingjester** [comment]
> hm, try adding `jdcal` (https://pypi.org/project/jdcal/) to requirements seems like it's missing
plz tell me the command of using jdcal!!

**Comment by atheistrepublic** [comment]
I once had the same problem.I solved it by adding jdcal and et_xmlfile
inside the buildozer.spec file.
Below is the link if you want to see how I solved it:
https://github.com/kivy/buildozer/issues/1001

**Comment by atheistrepublic** [comment]
Problem solved using the below link:
*https://github.com/kivy/buildozer/issues/1001
<https://github.com/kivy/buildozer/issues/1001>*

**Comment by AlexLukyanov85** [comment]
This works well for writing a file, but not enough for reading xlsx. Obviously in the spec file some library is needed for this ...

all_players = pd.read_excel ('all_players.xlsx') - APPLICATION CRASHED
df = pd.DataFrame (all_players)
df.to_excel ('my_team.xlsx', index = False) - WORKS NORMALLY

Please help.

**Comment by harry95730** [comment]
> I have been trying to import openpyxl in my main.py file.When i run buildozer android debug everything seems to be working fine.But when i open the app on my android it crashes.Can you help me with finding the solution.
> 
> Why can't i import openpyxl.? When i don't use this module in my main file everthing works good but after importing it the app crashes.

i am facing same issue can u please help??

**Comment by AlexLukyanov85** [comment]
I think you should switch to csv format. This is a more appropriate solution.
--
Отправлено из Mail.ru для Android суббота, 24 декабря 2022г., 19:19 +03:00 от Vasa john harry Asher  ***@***.*** :
