### ISSUE TITLE
App crasches on Phone after Resplash Screen

### ISSUE THREAD

**Issue by MupfSpace** [kivy/buildozer#1009]
Hi,
I have compiled my Python / Kivy app to an APK but it crashed in android after Showing the Resplash screen.

this is the crashing apk:
https://drive.google.com/file/d/10_ViajNqq5GR9S8q6fKXFum4a3byjE5Y/view?usp=drivesdk
this is my python code:
https://drive.google.com/file/d/10cMUvwfQg2J1D8a3sdSOIyL_kgo6CCzD/view?usp=drivesdk
this is my buildozer.spec:
https://drive.google.com/file/d/10cnK1BK_8s2a6jfIeh6RD0eg3O4Xy-pO/view?usp=drivesdk

I hope someone can help me.

**Comment by Ham-Merhead** [comment]
Look in the logcat output for "Traceback"
