### ISSUE TITLE
Buildozer creates unexpected dist name

### ISSUE THREAD

**Issue by iPopcorn** [kivy/buildozer#1016]
### Versions

* Python: 3.6.8
* OS: Ubuntu 18.04.2 LTS
* Buildozer: 0.39

### Description

Hey all,
I've been using buildozer for awhile now, and have even deployed APKs to Google Play. I just finished a bunch of changes to my app, and so I wanted to build new release APKs, which I was able to do no problem. When I downloaded my latest release APK, it crashed. It turns out the 64-bit version of my APK was using 32-bit libraries for some reason. 

So I decided to remove the .buildozer/ directory from my app directory in order to get a completely fresh build, and that's when the trouble started. I had some problems getting my NDK set up again, and once I did, I reached the issue I'm raising now.

For some reason, buildozer is setting the dist/ dir for my app as 'cx__armeabi-v7a' but when it goes to package the app, it's looking for the dir 'cx'. I don't know why it is suddenly appending '__armeabi-v7a' to the directory name, but it seems not to expect that name.

[Here is a link to a minimum reproducible example](https://github.com/iPopcorn/Buildozer-Example)
[build-log-dev.txt](https://github.com/kivy/buildozer/files/4040317/build-log-dev.txt)
[buildozer-spec.txt](https://github.com/kivy/buildozer/files/4040320/buildozer-spec.txt)

I have attached the buildozer.spec and the build-log-dev.txt files, which can also be found in the repo.

Command: buildozer -v android debug

Thanks so much for your help with this issue, and I apologize if it is simple user error.

**Comment by AndreMiras** [comment]
Thanks for the detailed bug report.
You're running on `Buildozer: 0.39` could you try with recent 1.1.0 release?

**Comment by iPopcorn** [comment]
Hello,

Sorry for the late reply. This issue goes away with a more recent version.

Thanks!
