### ISSUE TITLE
Crash on buildozer android debug command. Command failed: /usr/bin/python -m pythonforandroid.toolchain

### ISSUE THREAD

**Issue by Znoleg** [kivy/buildozer#1017]
* Python: 2.7.17
* OS: Ubuntu 19.10 64-bit (VM)
* Buildozer: 1.0

### Description

I'm trying to use buildozer android debug. Buildozer spec already created.
I'm getting error: `File "pythonforandroid/distribution.py", line 48
*,
^
SyntaxError: invalid syntax`

`# Command failed: /usr/bin/python -m pythonforandroid.toolchain create —dist_name=myapp —bootstrap=sdl2 —requirements=python3,kivy —arch armeabi-v7a —copy-libs —color=always —storage-dir="/home/osboxes/Project/.buildozer/android/platform/build-armeabi-v7a" —ndk-api=21`
### buildozer.spec
Command:

buildozer android debug

Spec file:

[buildozer.zip](https://github.com/kivy/buildozer/files/4048131/buildozer.zip)

### Logs

[log.zip](https://github.com/kivy/buildozer/files/4048145/log.zip)

**Comment by jlegido** [comment]
Same error here performing a different command:

```
buildozer android debug deploy run
```

If makes sense to provide more information I will.

**Comment by jlegido** [comment]
@Znoleg I realized that 'buildozer' package was installed under python2, thus the [offending line](https://github.com/kivy/python-for-android/blob/develop/pythonforandroid/distribution.py#L48).
You can check it:
```
pip list | grep buildozer
```
This is how I fixed the issue in my scenario:
1. Uninstall 'buildozer' package:
```
pip uninstall buildozer
```
2. Install buildozer under python3
```
cd ~/git
git clone https://github.com/kivy/buildozer.git
cd buildozer
```
Important: use 'python3' here:
```
sudo python3 setup.py install
```
Hope this can fix your issue
```

**Comment by Znoleg** [comment]
> @Znoleg I realized that 'buildozer' package was installed under python2, thus the [offending line](https://github.com/kivy/python-for-android/blob/develop/pythonforandroid/distribution.py#L48).
> You can check it:
> 
> ```
> pip list | grep buildozer
> ```
> 
> This is how I fixed the issue in my scenario:
> 
> 1. Uninstall 'buildozer' package:
> 
> ```
> pip uninstall buildozer
> ```
> 
> 1. Install buildozer under python3
> 
> ```
> cd ~/git
> git clone https://github.com/kivy/buildozer.git
> cd buildozer
> ```
> 
> Important: use 'python3' here:
> 
> ```
> sudo python3 setup.py install
> ```
> 
> Hope this can fix your issue

Thx man!

**Comment by needyamin** [comment]
Thanks @jlegido
