### ISSUE TITLE
Windows support to build Android APK

### ISSUE THREAD

**Issue by josephernest** [kivy/buildozer#1022]
First of all, congrats for this wonderful project.

Is there a roadmap (if so, would you have a link?) about Windows support? 

More precisely I'm not speaking about building Windows .exe packages (I already use py2exe, cx_freeze, etc.), but rather build Android APK apps *from a Windows computer*.

Is there maybe an early beta / alpha version? I could help in beta-testing it.

___

Here is what I tried:

    pip install kivy buildozer

then create a main.py file:

```
from kivy.app import App
from kivy.uix.button import Button
class TestApp(App):
    def build(self):
        return Button(text='hello world')
if __name__ == '__main__':
    TestApp().run()
```

The command

    buildozer init

worked but 

    buildozer android debug

failed:

> Unknown command/target android

**Comment by tshirtman** [comment]
there is no current plan to do so, it might come in the future if some work is done to have prebuilt p4a distributions, but currently we don't, and building such a thing in windows would require a lot of adaptations.

We recommand windows users to either use WSL if they have windows 10, or to use an Ubuntu VM to achieve that.

**Comment by josephernest** [comment]
Thank you for your answer. I'll use my Debian server in the meantime!
