### ISSUE TITLE
Option to use cached packages

### ISSUE THREAD

**Issue by smaudet** [kivy/buildozer#1030]
This is a buildozer feature request.

You are currently downloading *every single package* every time a buildozer folder is removed and rebuilt from spec. I am currently trying to troubleshoot a broken recipe, meaning I am hitting these servers multiple times. My internet is fine, however this all costs $$$ - I don't think you intended to but you built a poorly coded DDOSing tool.

To be clear, I mean there should **a)** be indication that although a particular url *would* be fetched, it won't, and instead a cached local package (maybe in `~/.buildozer`) is used in its place. Not making any recommendation to do hash checking, but I suspect you could even fetch packages from pip's repositories? **b)** provide some option to re-download a particular package. A tree would be nice here so you know which packages depend on which others in case of corruption.

This is contrast to today where the only cache seems to the local `.buildozer` folder.

Please consider adding more to the docs for troubleshooting or cleaning builds and/or update buildozer so that it caches packages instead of constantly (re) downloading them.

**Comment by xandro0777** [comment]
Apparently  https://github.com/kivy/buildozer/pull/801 might address this?

**Comment by Julian-O** [comment]
This is being closed, but not forgotten. It has been consolidated into issue #1727.
