### ISSUE TITLE
problem

### ISSUE THREAD

**Issue by leonidussaks** [kivy/buildozer#1031]
### Versions

* Python: 3.8.1
* OS: Manjaro (Arch based)
* Buildozer: 1.0

### Description
I launched:
and got an error

### buildozer.spec
Command:
```sh
buildozer android debug deploy run
```

Spec file:
```
[app]

title = alarmclock
package.name = alarmclock
package.domain = org.alarmclock
source.dir = .
version = 0.1
requirements = python3,kivy
```

### Logs

```
/home/leonidussaks/Документы/python/kivy/alarm_clock/.buildozer/android/platform/build-armeabi-v7a/build/other_builds/python3-libffi-openssl-sqlite3/armeabi-v7a__ndk_target_21/python3/Include/Python.h:8:10: fatal error: 
      'pyconfig.h' file not found
#include "pyconfig.h"
         ^~~~~~~~~~~~
1 error generated.
make: *** [/home/leonidussaks/Документы/python/kivy/alarm_clock/.buildozer/android/platform/build-armeabi-v7a/build/bootstrap_builds/sdl2-python3/obj/local/armeabi-v7a/objs/main/start.o] Error 1

```

**Comment by kengsley1993** [comment]
same error i got
have you solve it?

**Comment by hvitis** [comment]
python.h is a part of python-dev versions so..
You could use venv with buildozer but you need to have python-dev inside it.
You can create it with:
```
virtualenv --python=/usr/bin/python3.6-dev <path>
```

**Comment by AndreMiras** [comment]
Thanks for the report. The title and body are so poorly formatted. We cannot make a bug report with a title saying "problem"...
We may still have issues running buildozer in a venv, but I can't judge without having a complete log.
Please feel free to re-open with more logs (and proper title)
