### ISSUE TITLE
Error packing apk with buildozer 

### ISSUE THREAD

**Issue by mohamedLT** [kivy/buildozer#1034]
### Versions

* Python:3
* OS: Linux Ubuntu 18
* Buildozer : 1.0
### Description

I am trying to build a apk but it keeps telling me that i need mpmath=>0.19 
the problem is coming from sympy because when i built the apk without it everything worked as expected I think its not downloading mpmath 
### buildozer.spec
Command:
`buildozer -v android debug `
`buildozer android  debug

Spec file:
https://pastebin.com/71maKs5n
### Logs
https://pastebin.com/EvALr3fW

**Comment by hvitis** [comment]
Are you running it within venv?

**Comment by MinorWannaBeDev** [comment]
I've faced the same issue.
However I've found a solution, that at least worked for me, and that is to import locally the modules, simply by copying them from `/usr/local/lib` to your app directory ,and remove sympy and mpmath from requirements, don't forget to rename your script to main.py if you haven't already done so.

**Comment by Ransometech** [comment]
> I've faced the same issue.
> However I've found a solution, that at least worked for me, that is to import locally the modules, simply by copying them from `/usr/local/lib` to your app directory ,and by removing sympy and mpmath from app requirements, don't forget to rename your script to main.py if you haven't already done so.

Please you imported the mpmath and sympy module? Because I included the mpmath and sympy folder in the app directory where the main.py file is located, it deploy successfully but the app is always crashing on start.

**Comment by Ohadforman** [comment]
> > I've faced the same issue.
> > However I've found a solution, that at least worked for me, that is to import locally the modules, simply by copying them from `/usr/local/lib` to your app directory ,and by removing sympy and mpmath from app requirements, don't forget to rename your script to main.py if you haven't already done so.
> 
> Please you imported the mpmath and sympy module? Because I included the mpmath and sympy folder in the app directory where the main.py file is located, it deploy successfully but the app is always crashing on start.

same here
