### ISSUE TITLE
How to import a module on android using buildozer?

### ISSUE THREAD

**Issue by iulianastroia** [kivy/buildozer#1049]
I am using kniteditor module to translate from English to German and I have added my own words and their translation. How can I add the installation directory for kniteditor when deploying to android using buildozer? Otherwise, if i don't add that module, the translation cannot be possible.

**Comment by AndreMiras** [comment]
I don't quite understand the question, but it feels more like a support request than a bug.
You can use Discord for support question, this here is more for tracking bugs in buildozer
