### ISSUE TITLE
error while buildozer android debug deploy run

### ISSUE THREAD

**Issue by akchawla41** [kivy/buildozer#1064]
/py/test$ buildozer android debug deploy run
# Check configuration tokens
# Ensure build layout
# Check configuration tokens
# Preparing build
# Check requirements for android
# Run 'dpkg --version'
# Cwd None
Debian 'dpkg' package management program version 1.19.0.5 (amd64).
This is free software; see the GNU General Public License version 2 or
later for copying conditions. There is NO warranty.
# Search for Git (git)
#  -> found at /usr/bin/git
# Search for Cython (cython)
#  -> found at /usr/local/bin/cython
# Search for Java compiler (javac)
#  -> found at /usr/lib/jvm/java-8-openjdk-amd64/bin/javac
# Search for Java keytool (keytool)
#  -> found at /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/keytool
# Install platform
# Run 'git config --get remote.origin.url'
# Cwd /home/anil/py/test/.buildozer/android/platform/python-for-android
https://github.com/kivy/python-for-android.git
# Run 'git branch -vv'
# Cwd /home/anil/py/test/.buildozer/android/platform/python-for-android
* master 8cf66cc1 [origin/master] Merge pull request #2111 from kivy/release-2020.03.30
# Run '/usr/bin/python -m pip install -q --user \'appdirs\' \'colorama>=0.3.3\' \'jinja2\' \'six\' \'enum34; python_version<"3.4"\' \'sh>=1.10; sys_platform!="nt"\' \'pep517<0.7.0"\' \'pytoml\' \'virtualenv<20\''
# Cwd None
DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. A future version of pip will drop support for Python 2.7. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
# Apache ANT found at /home/anil/.buildozer/android/platform/apache-ant-1.9.4
# Android SDK found at /home/anil/.buildozer/android/platform/android-sdk
# Recommended android's NDK version by p4a is: 19b
# Android NDK found at /home/anil/.buildozer/android/platform/android-ndk-r19b
# Check application requirements
# Check garden requirements
# Compile platform
# Run '/usr/bin/python -m pythonforandroid.toolchain create --dist_name=myapp --bootstrap=sdl2 --requirements=python3,kivy --arch armeabi-v7a --copy-libs --color=always --storage-dir="/home/anil/py/test/.buildozer/android/platform/build-armeabi-v7a" --ndk-api=21'
# Cwd /home/anil/py/test/.buildozer/android/platform/python-for-android
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/anil/py/test/.buildozer/android/platform/python-for-android/pythonforandroid/toolchain.py", line 96, in <module>
    from pythonforandroid.distribution import Distribution, pretty_log_dists
  File "pythonforandroid/distribution.py", line 48
    *,
     ^
SyntaxError: invalid syntax
# Command failed: /usr/bin/python -m pythonforandroid.toolchain create --dist_name=myapp --bootstrap=sdl2 --requirements=python3,kivy --arch armeabi-v7a --copy-libs --color=always --storage-dir="/home/anil/py/test/.buildozer/android/platform/build-armeabi-v7a" --ndk-api=21
# ENVIRONMENT:
#     DBUS_STARTER_ADDRESS = 'unix:path=/run/user/1000/bus,guid=8400c39e953fe8612c1053805e927bcd'
#     QT4_IM_MODULE = 'xim'
#     WINDOWPATH = '2'
#     XDG_CURRENT_DESKTOP = 'ubuntu:GNOME'
#     XDG_SESSION_TYPE = 'x11'
#     QT_IM_MODULE = 'xim'
#     LOGNAME = 'anil'
#     USER = 'anil'
#     PATH = '/home/anil/.buildozer/android/platform/apache-ant-1.9.4/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin'
#     XDG_VTNR = '2'
#     HOME = '/home/anil'
#     DISPLAY = ':0'
#     SSH_AGENT_PID = '1511'
#     LANG = 'en_IN'
#     MANAGERPID = '1387'
#     SHELL = '/bin/bash'
#     ANDROIDMINAPI = '21'
#     XAUTHORITY = '/run/user/1000/gdm/Xauthority'
#     JOURNAL_STREAM = '9:31261'
#     SESSION_MANAGER = 'local/jull:@/tmp/.ICE-unix/1416,unix/jull:/tmp/.ICE-unix/1416'
#     XDG_DATA_DIRS = '/usr/share/ubuntu:/usr/local/share/:/usr/share/:/var/lib/snapd/desktop'
#     ANDROIDSDK = '/home/anil/.buildozer/android/platform/android-sdk'
#     QT_ACCESSIBILITY = '1'
#     GNOME_DESKTOP_SESSION_ID = 'this-is-deprecated'
#     CLUTTER_IM_MODULE = 'xim'
#     TEXTDOMAIN = 'im-config'
#     XMODIFIERS = '@im=ibus'
#     GPG_AGENT_INFO = '/run/user/1000/gnupg/S.gpg-agent:0:1'
#     INVOCATION_ID = 'a9ea1586c9ce448bb3a6c6702491bea9'
#     USERNAME = 'anil'
#     XDG_SESSION_DESKTOP = 'ubuntu'
#     XDG_RUNTIME_DIR = '/run/user/1000'
#     SSH_AUTH_SOCK = '/run/user/1000/keyring/ssh'
#     TERM = 'xterm-256color'
#     VTE_VERSION = '5202'
#     GDMSESSION = 'ubuntu'
#     IM_CONFIG_PHASE = '2'
#     TEXTDOMAINDIR = '/usr/share/locale/'
#     GNOME_SHELL_SESSION_MODE = 'ubuntu'
#     XDG_CONFIG_DIRS = '/etc/xdg/xdg-ubuntu:/etc/xdg'
#     DBUS_STARTER_BUS_TYPE = 'session'
#     LESSOPEN = '| /usr/bin/lesspipe %s'
#     XDG_SESSION_ID = '2'
#     DBUS_SESSION_BUS_ADDRESS = 'unix:path=/run/user/1000/bus,guid=8400c39e953fe8612c1053805e927bcd'
#     _ = '/usr/local/bin/buildozer'
#     GNOME_TERMINAL_SERVICE = ':1.105'
#     GTK_IM_MODULE = 'ibus'
#     DESKTOP_SESSION = 'ubuntu'
#     PACKAGES_PATH = '/home/anil/.buildozer/android/packages'
#     LESSCLOSE = '/usr/bin/lesspipe %s %s'
#     GTK_MODULES = 'gail:atk-bridge'
#     XDG_SEAT = 'seat0'
#     ANDROIDNDK = '/home/anil/.buildozer/android/platform/android-ndk-r19b'
#     LANGUAGE = 'en_IN:en'
#     SHLVL = '1'
#     PWD = '/home/anil/py/test'
#     ANDROIDAPI = '27'
#     COLORTERM = 'truecolor'
#     XDG_MENU_PREFIX = 'gnome-'
#     LS_COLORS = 'rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=00:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.Z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.zst=01;31:*.tzst=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.wim=01;31:*.swm=01;31:*.dwm=01;31:*.esd=01;31:*.jpg=01;35:*.jpeg=01;35:*.mjpg=01;35:*.mjpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=00;36:*.au=00;36:*.flac=00;36:*.m4a=00;36:*.mid=00;36:*.midi=00;36:*.mka=00;36:*.mp3=00;36:*.mpc=00;36:*.ogg=00;36:*.ra=00;36:*.wav=00;36:*.oga=00;36:*.opus=00;36:*.spx=00;36:*.xspf=00;36:'
#     GNOME_TERMINAL_SCREEN = '/org/gnome/Terminal/screen/baf02bc3_b6bb_472f_bd61_d47490d8c0d0'
# 
# Buildozer failed to execute the last command
# The error might be hidden in the log above this error
# Please read the full log, and search for it before
# raising an issue with buildozer itself.
# In case of a bug report, please add a full log with log_level = 2

**Comment by AndreMiras** [comment]
Log is unreadable, you need to format it with the back ticks.
You need to install buildozer on Python 3, not Python 2
