### ISSUE TITLE
Fatal Python error: init_fs_encoding: failed to get the Python codec of the filesystem encoding

### ISSUE THREAD

**Issue by iamkkushal** [kivy/buildozer#1076]
### Versions

* Python: 3.7.5
* OS: Mac OS 10.14.1 (Mojave)
* Buildozer: 1.0.1

### Description

I am trying to run 
```sh
buildozer init
buildozer android debug deploy run
```
To generate and push the APK to my android device. I haven't edited the default buildozer.spec file. 

Spec file:

It is the default spec file when running:
```sh
 buildozer init
```

### Logs

Log file can be found here https://pastebin.com/RmgtwVaT

Apologies if I have made any mistake in posting the issue or generating the log file. I am very new to this environment.

**Comment by Ham-Merhead** [comment]
In the general case
`buildozer android debug`
doesn't work on MacOS
Workaround is install a Linux VM and use that.

**Comment by AndreMiras** [comment]
I've just tried on macOS `p4a.branch = develop` (in `buildozer.spec`) and I could build OK. See the end of my log:
```
[DEBUG]:        BUILD SUCCESSFUL in 1m 3s
[DEBUG]:        27 actionable tasks: 27 executed

[INFO]:    <- directory context /Users/vagrant/workspace/buildozer-test/.buildozer/android/platform/python-for-android
[INFO]:    Of the existing distributions, the following meet the given requirements:
[INFO]:         myapp: min API 21, includes recipes (hostpython3, libffi, openssl, sdl2_image, sdl2_mixer, sdl2_ttf, sqlite3, python3, sdl2, setuptools, six, pyjnius, android, kivy, certifi), built for archs (armeabi-v7a)
[INFO]:    myapp has compatible recipes, using this one
[INFO]:    # Copying android package to current directory
[INFO]:    # Android package filename not found in build output. Guessing...
[INFO]:    # Found android package file: /Users/vagrant/workspace/buildozer-test/.buildozer/android/platform/build-armeabi-v7a/dists/myapp__armeabi-v7a/build/outputs/apk/debug/myapp__armeabi-v7a-debug.apk
[INFO]:    # Add version number to android package
[INFO]:    # Android package renamed to myapp__armeabi-v7a-debug-0.1-.apk
[DEBUG]:   -> running cp /Users/vagrant/workspace/buildozer-test/.buildozer/android/platform/build-armeabi-v7a/dists/myapp__armeabi-v7a/build/outputs/apk/debug/myapp__armeabi-v7a-debug.apk myapp__armeabi-v7a-debug-0.1-.apk
WARNING: Received a --sdk argument, but this argument is deprecated and does nothing.
No setup.py/pyproject.toml used, copying full private data into .apk.
Applying Java source code patches...
Applying patch: src/patches/SDLActivity.java.patch
# Android packaging done!
# APK myapp-0.1-armeabi-v7a-debug.apk available in the bin directory
# Run '/Users/vagrant/.buildozer/android/platform/android-sdk/platform-tools/adb devices'
# Cwd None
* daemon not running; starting now at tcp:5037
* daemon started successfully
List of devices attached

# Application pushed.
# Application started.
```
@iamkkushal could you try again on `p4a.branch = develop`. Also to be sure try with buildozer master (so pip install https://github.com/kivy/buildozer/archive/master.zip)

**Comment by iamkkushal** [comment]
I'm sorry. I solved this issue by reinstalling python 3.7.7 using brew. And Got a fresh start of buildozer yet again.
Thank you for the comments.
I guess the problem was with the virtual environment package.

**Comment by iamkkushal** [comment]
> In the general case
> `buildozer android debug`
> doesn't work on MacOS
> Workaround is install a Linux VM and use that.

It does work with MacOS. I have tried it on MacOS 10.14.1

**Comment by jeb2112** [comment]
I got this same error with a .buildozer directory that I corrupted somehow by either moving it or changing some source files, not sure exactly. But simply removing it to force a fresh build cleared the issue. ie, it wasn't any issue with the virtual env. I think the virtual env thing is a separate issue from buildozer, and which just shares the same error.
