### ISSUE TITLE
buildozer Install python 3.8.1

### ISSUE THREAD

**Issue by TSoer** [kivy/buildozer#1090]
### Versions

* Python: 3.7.5
* OS: Xubuntu
* Buildozer: 1.0.1

### Description

When you start buildozer. Installs python 3.8.1 I have a suspicion that because of this I get a ReferenceError error. How do I set preferences so that apk builds on python <3.8?

**Comment by tshirtman** [comment]
you should be able to set the python version in buildozer.spec by putting for example `python==3.7.5` in the requirements line.

**Comment by TSoer** [comment]
Yes I did as you said

> requirements = python==3.7.6,kivy,kivymd==0.104.0,sqlite3

But while buildozer is running, you can see the logs

> [INFO]:    Downloading hostpython3
[INFO]:    -> running mkdir -p /home/kivy/compil/.buildozer/android/platform/build-armeabi-v7a/packages/hostpython3
[INFO]:    -> directory context /home/kivy/compil/.buildozer/android/platform/build-armeabi-v7a/packages/hostpython3
[INFO]:    -> running basename https://www.python.org/ftp/python/3.8.1/Python-3.8.1.tgz
[INFO]:    -> running rm -f .mark-Python-3.8.1.tgz                                                                                                                                                                                                                            
[INFO]:    Downloading hostpython3 from https://www.python.org/ftp/python/3.8.1/Python-3.8.1.tgz
[INFO]:    -> running touch .mark-Python-3.8.1.tgz
[INFO]:    <- directory context /home/kivy/compil/.buildozer/android/platform/python-for-android


after buildozer downloads work on errors

> ERROR: Could not find a version that satisfies the requirement python==3.7.6 (from -r requirements.txt (line 3)) (from versions: none)
ERROR: No matching distribution found for python==3.7.6 (from -r requirements.txt (line 3))

> Command failed: /usr/bin/python3 -m pythonforandroid.toolchain create --dist_name=PHU --bootstrap=sdl2 --requirements=python==3.7.6,kivy,kivymd==0.104.0,sqlite3 --arch armeabi-v7a --copy-libs --color=always --storage-dir="/home/kivy/compil/.buildozer/android/platform/build-armeabi-v7a" --ndk-api=21

**Comment by AndreMiras** [comment]
Oops yes, it should be `python3==3.7.5` (note the `3`). We should probably re-alias this as we only support `python3` recipe anyway.

**Comment by TSoer** [comment]
@AndreMiras
> Oops yes, it should be `python3==3.7.5` (note the `3`). We should probably re-alias this as we only support `python3` recipe anyway.

I checked it. The same thing happens as described above.

**Comment by AndreMiras** [comment]
Could you please share the actual log still. Please share the complete log including the buildozer.spec file

**Comment by TSoer** [comment]
@AndreMiras 
[buildozerSpec.txt](https://github.com/kivy/buildozer/files/4594223/buildozerSpec.txt)
[buildzerLog.txt](https://github.com/kivy/buildozer/files/4594224/buildzerLog.txt)
After building apk. I started getting other errors. and the application on the phone does not start, so I can’t say with confidence that I’ve packed python 3.7.6, but pay attention to the buildozerLog file, it can be seen that python 3.8.1 will be downloaded

**Comment by AndreMiras** [comment]
Oh OK thanks, I wanted to see the logs because earlier you said (deleted?) the error was the same with `python3==3.7.5` and I had my doubt that's why I needed the full log :sweat_smile: 
If the issue you have now is a runtime one, then this task can be closed since it's solved right?
For the runtime issue you also need to check the logs. But it could really be "just" this:
https://github.com/kivy/python-for-android/issues/2169
https://github.com/kivy/buildozer/issues/1091
https://github.com/kivy/python-for-android/issues/2167

**Comment by TSoer** [comment]
Your settings. Collect apk files that do not work.

**Comment by TSoer** [comment]
In order to select the python version. The argument python3 == 3.7.5 is not enough. In the buildozer.spec file, the requirements section must additionally specify hostpython3 == 3.7.5. An example is presented below

`requirements = hostpython3==3.7.5,python3==3.7.5,kivy,kivymd,sqlite3`

**Comment by purnama11** [comment]
i have remove buildozer and 
write ->requirements = hostpython3==3.7.5,python3==3.7.5,kivy,kivymd,sqlite3
but apk still wont install in my android 6.0
