### ISSUE TITLE
APK not running on Android 10?

### ISSUE THREAD

**Issue by MarcEngrie** [kivy/buildozer#1102]
Hi,

I finally got to the point where I can build (error-free) a APK with Buildozer 1.0. 
I build 2 sample apps, one with basic Python code, another with additional Python package (paho-mqtt). 
I can install the APK with mqtt and run it but it closed immediatelly. The basic Python app will not even install. 
The smartphone is a Nokia 6.1 with Android 10.
As said I am using buildozer 1.0, Python 3.8.2, open jdk 1.8.0_252, Android NDK r19c running on Ubuntu 20.04 Desktop 64bit (in VirtualBox 6.1).

Are compatibility issues among above? Can it be solved? How?

Thx

Marc Engrie

**Comment by AndreMiras** [comment]
It cannot be solved without seeing a log. For compile time error we need full compilation log. For install time error we need a log. For runtime we also need a log. There's a template proposed when you create an issue for this reason. Closing as not enough information and looks more like a support question than an actual bug report. Please ask the support channel chat on Discord for support

**Comment by brvier** [comment]
I confirm that s works on Android 10 device.
