### ISSUE TITLE
[Errno 13] Permission denied:

### ISSUE THREAD

**Issue by ren-02** [kivy/buildozer#1108]
* Python: 3.7
* OS: Windows 10
* Buildozer: buildozer 1.0

### Description

// REPLACE ME: What are you trying to get done, what has happened, what went wrong, and what did you expect?

### buildozer.spec
buildozer android debug
`

Spec file:
```
// REPLACE ME: Paste your buildozer.spec file here
```

### Logs
Traceback (most recent call last):
  File "/home/ren/.local/bin/buildozer", line 8, in <module>
    sys.exit(main())
  File "/home/ren/.local/lib/python3.6/site-packages/buildozer/scripts/client.py", line 13, in main
    Buildozer().run_command(sys.argv[1:])
  File "/home/ren/.local/lib/python3.6/site-packages/buildozer/__init__.py", line 1071, in run_command
    self.target.run_commands(args)
  File "/home/ren/.local/lib/python3.6/site-packages/buildozer/target.py", line 92, in run_commands
    func(args)
  File "/home/ren/.local/lib/python3.6/site-packages/buildozer/target.py", line 104, in cmd_debug
    self.buildozer.build()
  File "/home/ren/.local/lib/python3.6/site-packages/buildozer/__init__.py", line 211, in build
    self.build_application()
  File "/home/ren/.local/lib/python3.6/site-packages/buildozer/__init__.py", line 739, in build_application
    self._copy_application_libs()
  File "/home/ren/.local/lib/python3.6/site-packages/buildozer/__init__.py", line 839, in _copy_application_libs
    copytree(self.applibs_dir, join(self.app_dir, '_applibs'))
  File "/usr/lib/python3.6/shutil.py", line 365, in copytree
    raise Error(errors)
shutil.Error: [('/mnt/f/helo/.buildozer/applibs', '/mnt/f/helo/.buildozer/android/app/_applibs', "[Errno 13] Permission denied: '/mnt/f/helo/.buildozer/android/app/_applibs'")]

**Comment by quitegreensky** [comment]
I have this problem too . Don't know thy this happens

**Comment by AndreMiras** [comment]
We don't have enough logs to tell. We need full log and `buildozer.spec` file. Also code needs to be formatted (use grace accent/backquote) to be read properly

**Comment by suvidh** [comment]
I am facing same issue.

**Comment by suvidh** [comment]
![image](https://user-images.githubusercontent.com/19871090/89179251-f7667680-d5ac-11ea-8ab7-72ff58f57fac.png)

The issue persists regardless of what I add to buildozer.spec

**Comment by stefan-sherwood** [comment]
This happens because you are attempting to set permissions on mounted Windows drives from WSL, which is prohibited due to incompatibilities between Windows file permissions and Linux file permissions.

The function that is failing, [copytree()](https://docs.python.org/3/library/shutil.html#shutil.copytree), attempts to apply permissions to copied files, hence the `Permission Denied` error.

You can remedy this by building from a directory that is relative to the WSL root, e.g. `~/myProject`

**Comment by al-chris** [comment]
> This happens because you are attempting to set permissions on files on mounted Windows drives from WSL, which is prohibited due to incompatibilities between Windows file permissions and Linux file permissions.
> 
> The function that is failing, [copytree()](https://docs.python.org/3/library/shutil.html#shutil.copytree), attempts to apply permissions to copied files, hence the `Permission Denied` error.
> 
> You can remedy this by building from a directory that is relative to the WSL root, e.g. `~/myProject`

please, how?

**Comment by stefan-sherwood** [comment]
I explained how. Please use more words to describe what you don't understand about the solution I suggested.

**Comment by al-chris** [comment]
![16001305558037296554512254151079](https://user-images.githubusercontent.com/71184952/93151802-ca9d9700-f6f4-11ea-902d-b191942b9e12.jpg)
This I what I'm currently facing

**Comment by al-chris** [comment]
> I explained how. Please use more words to describe what you don't understand about the solution I suggested.

I am building from ~/camera and getting:
PermissionError: [Errno 13] Permission denied: '/home/alchris/camera/main.py'

**Comment by stefan-sherwood** [comment]
Thanks for the clarification. What do you see if you type `ls -l /home/alchris/camera/main.py`?

**Comment by stefan-sherwood** [comment]
Also, strange that it's getting the error when opening the file, not when actually copying it. You can add this log statement in `/usr/lib/python3.8/shuil.py` just before line 360 `print( f"{src=}, {dst=}" )` to get more clarity.

**Comment by SomyKamble** [comment]
Permission denied by Kivy at the very last stage of the build compile 

: shutil.Error: [('/mnt/d/kivy_projects/basics/.buildozer/applibs', '/mnt/d/kivy_projects/basics/.buildozer/android/app/_applibs', "[Errno 13] Permission denied: '/mnt/d/kivy_projects/basics/.buildozer/android/app/_applibs'")]

![image](https://user-images.githubusercontent.com/52233612/104086903-b2442000-5281-11eb-8e2f-0d6fe5f4c27f.png)


Can anyone please help

**Comment by stefan-sherwood** [comment]
@SomyKamble I described the cause and a workaround for the problem in my first comment.

**Comment by hladkky** [comment]
@stefan-sherwood Hello. I have the same issue:
![image](https://user-images.githubusercontent.com/60746298/104818854-b7314280-5832-11eb-8ab3-2cc7588ad05f.png)
I have created a directory with the same name as the application. But the issue has remained.
What should I change?

**Comment by hladkky** [comment]
@stefan-sherwood Hello. I am facing the same issue.
As you recommended, I create ~/app directory and I have tried to build from there, but have got this error.
![image](https://user-images.githubusercontent.com/60746298/104819154-4723bc00-5834-11eb-94ae-5f75d501c713.png)

But I have got this file in my project root folder. What should I do?

**Comment by stefan-sherwood** [comment]
As shown in your screenshot, it's trying to set permissions on a file whose root is `/mnt/d`. That is a Windows directory. You cannot build projects located in a Windows directory. Move it to WSL and try again.

**Comment by hladkky** [comment]
In what way can I totally copy application root folder to WSL? And the same question for returning apk, that will have been built.

**Comment by hladkky** [comment]
@stefan-sherwood I have started building, but at the very end got this error:

[WARNING]: ERROR: /home/hladkko/aliasapp/aliasapp/.buildozer/android/platform/build-armeabi-v7a/dists/alias__armeabi-v7a/gradlew failed!
# Command failed: /usr/bin/python3 -m pythonforandroid.toolchain apk --debug --bootstrap=sdl2 --dist_name alias --name 'Alias українською' --version 0.1 --package org.alias_ukr.alias --minsdk 21 --ndk-api 21 --private /home/hladkko/aliasapp/aliasapp/.buildozer/android/app --android-entrypoint org.kivy.android.PythonActivity --android-apptheme @android:style/Theme.NoTitleBar --presplash /home/hladkko/aliasapp/aliasapp/./assets/gifs/loading.gif --icon /home/hladkko/aliasapp/aliasapp/./assets/imgs/logo.png --orientation portrait --window --copy-libs --arch armeabi-v7a --color=always --storage-dir="/home/hladkko/aliasapp/aliasapp/.buildozer/android/platform/build-armeabi-v7a" --ndk-api=21
# ENVIRONMENT:
#     SHELL = '/bin/bash'
#     WSL_DISTRO_NAME = 'Ubuntu'
#     NAME = 'DESKTOP-HKIQIUM'
#     PWD = '/home/hladkko/aliasapp/aliasapp'
#     LOGNAME = 'hladkko'
#     HOME = '/home/hladkko'
#     LANG = 'C.UTF-8'
#     LS_COLORS = 'rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=00:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.zst=01;31:*.tzst=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.wim=01;31:*.swm=01;31:*.dwm=01;31:*.esd=01;31:*.jpg=01;35:*.jpeg=01;35:*.mjpg=01;35:*.mjpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=00;36:*.au=00;36:*.flac=00;36:*.m4a=00;36:*.mid=00;36:*.midi=00;36:*.mka=00;36:*.mp3=00;36:*.mpc=00;36:*.ogg=00;36:*.ra=00;36:*.wav=00;36:*.oga=00;36:*.opus=00;36:*.spx=00;36:*.xspf=00;36:'
#     LESSCLOSE = '/usr/bin/lesspipe %s %s'
#     TERM = 'xterm-256color'
#     LESSOPEN = '| /usr/bin/lesspipe %s'
#     USER = 'hladkko'
#     SHLVL = '1'
#     WSLENV = ''
#     XDG_DATA_DIRS = '/usr/local/share:/usr/share:/var/lib/snapd/desktop'
#     PATH = ('/home/hladkko/.buildozer/android/platform/apache-ant-1.9.4/bin:/home/hladkko/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/mnt/c/Program '
 'Files/WindowsApps/CanonicalGroupLimited.UbuntuonWindows_2004.2020.812.0_x64__79rhkp1fndgsc:/mnt/c/ProgramData/Oracle/Java/javapath:/mnt/c/Program '
 'Files (x86)/Common Files/Intel/Shared '
 'Libraries/redist/intel64/compiler:/mnt/c/WINDOWS/system32:/mnt/c/WINDOWS:/mnt/c/WINDOWS/System32/Wbem:/mnt/c/WINDOWS/System32/WindowsPowerShell/v1.0/:/mnt/c/WINDOWS/System32/OpenSSH/:/mnt/c/Program '
 'Files/MATLAB/R2016a/runtime/win64:/mnt/c/Program '
 'Files/MATLAB/R2016a/bin:/mnt/c/Program '
 'Files/MATLAB/R2016a/polyspace/bin:/mnt/c/Program '
 'Files/Git/cmd:/mnt/c/Program '
 'Files/nodejs/:/mnt/c/ProgramData/chocolatey/bin:/mnt/c/Program '
 'Files/Intel/WiFi/bin/:/mnt/c/Program Files/Common '
 'Files/Intel/WirelessCommon/:/mnt/d/ITprogs/MEGA-X:/mnt/d/ITprogs/Redis/:/mnt/c/Program '
 'Files/Docker/Docker/resources/bin:/mnt/c/ProgramData/DockerDesktop/version-bin:/mnt/c/Users/hladk/AppData/Local/Programs/Python/Python38-32:/mnt/c/Users/hladk/AppData/Local/Programs/Python/Python38-32/Scripts:/mnt/d/Microsoft '
 'VS '
 'Code/bin:/mnt/c/Users/hladk/AppData/Roaming/npm:/mnt/c/ProgramData/Microsoft/Windows/Start '
 'Menu/Programs/PostgreSQL '
 '11:/mnt/d/ITprogs/Postgre/bin:/mnt/d/ITprogs/Postgre/data:/mnt/d/ITprogs/heroku/bin:/snap/bin')
#     HOSTTYPE = 'x86_64'
#     OLDPWD = '/home/hladkko/aliasapp'
#     _ = '/home/hladkko/.local/bin/buildozer'
#     PACKAGES_PATH = '/home/hladkko/.buildozer/android/packages'
#     ANDROIDSDK = '/home/hladkko/.buildozer/android/platform/android-sdk'
#     ANDROIDNDK = '/home/hladkko/.buildozer/android/platform/android-ndk-r19c'
#     ANDROIDAPI = '27'
#     ANDROIDMINAPI = '21'
#
# Buildozer failed to execute the last command
# The error might be hidden in the log above this error
# Please read the full log, and search for it before
# raising an issue with buildozer itself.
# In case of a bug report, please add a full log with log_level = 2

Where can I check logs?

**Comment by stefan-sherwood** [comment]
Unfortunately the error is not shown. Try executing the exact command that comes after "Command failed: " and paste here what it says in response.

**Comment by hladkky** [comment]
This is a response of command. But this module has to be installed...

![image](https://user-images.githubusercontent.com/60746298/104823375-531e7680-5852-11eb-9447-ffc6f20e54b7.png)

**Comment by hladkky** [comment]
After installing this package, I have got the same error, and after trying to debug got this:

![image](https://user-images.githubusercontent.com/60746298/104823520-5ebe6d00-5853-11eb-9dfd-fd330523b337.png)

**Comment by stefan-sherwood** [comment]
The second one is a different error and it says exactly what the problem is 😮

**Comment by hladkky** [comment]
Well, what the solution could be?

**Comment by stefan-sherwood** [comment]
If you Google the error message then the answer comes up as the first result. I am not going to debug your whole application, especially if you don't demonstrate diligence in figuring it out yourself.

**Comment by myNameIsHamza** [comment]
Permission problem probably from using root(sudo -s) while typing commands!

**Comment by bycellatt** [comment]
Do sudo su. Install the buildozer later

**Comment by Uni-Creator** [comment]
@hladkky 
Fixed by installing libtool.

`sudo apt-get install -y libtool`

**Comment by Marcinosoft** [comment]
Ok, short story long.

In my case I placed project within:
`C:\Kivy\Project\`
I could create `Kivy` folder on root C: drive because I am member of Administrator group, which gives me indirectly `Full control` permission. But regular users by default have got: `Read`, `Read & Execute`, `List folder content` and `Write`. My user is an owner of `C:\Kivy\` and everything inside of it to be clear. Permissions for nested objects are inherited from parents.

Then we have Ubuntu Linux (WSL) process, running under my Windows user. My user as I wrote before is part of Administrators group, but in Windows my user does not act as admin by default. It acts like regular user first, then if something require admin rights, then it's able to request additional rights, which usually require human confirmation (behaviour can be changed at UAC account setting).

Ubuntu Linux is able to operate on Windows folders because they are mounted as `/mnt/?/`, where `?` is Windows drive letter, like `c` in my case. Ok, so under Linux I can operate on `/mnt/c/Kivy/Project/` same as `C:\Kivy\Project\` under Windows. When I create a file within `/mnt/c/Kivy/Project/` folder, it will produce the same result like file created under Windows.

But when Linux world want to do something, which Windows user running wsl process cannot do directly, It can't invoke Windows behaviour which asks human to agree to do such operation as administrator. Linux always operate on Windows mounted file system based on regular, direct user rights.

That's why Buildozer launched under Linux is able to download and store over 1.3GB content within '/mnt/c/Kivy/Project/.buildozer/' without permission errors. At this phase regular users rights are enought. But copytree() require something more at Linux, and also Windows side. That's why it ends with `[Errno 13] Permission denied: '/mnt/c/Kivy/Project/.buildozer/android/app/_applibs'`.

copytree() under Linux invokes file permission operations (duplicating) at Windows side, which is allowed with `Full control` only.
When I granted it to `C:\Kivy\` folder for my user, then no more admin right was required. Windows do not need to ask human to agree rights escalation. It directly have permissions to manage file rights under Windows, that's why copytree() under Linux succeed.

It's similar to this: https://stackoverflow.com/questions/11835833/why-would-shutil-copy-raise-a-permission-exception-when-cp-doesnt

**Comment by Tobias-deleter** [comment]
If someone would ever wonder, you can open root WSL directory on your windows by typing **cd ~**  in ubuntu and next typing **explorer.exe . **

**Comment by lunamihuelk** [comment]
cuando a veces me deniegan permiso suelo pasarme a superusuario `sudo -s` y ya me quito esas denegaciones o a veces me suele funcionar `sudo chmod +x ejemplo.txt`

**Comment by MariwanJ** [comment]
@Marcinosoft 
Thank you very much . You saved my time and you knew the solution. But, if this not working for you please try to know if you are missing other libraries. 
I have Windows 10, and Ubuntu VM  - you shouldn't use root to run buildozer

**Comment by zikkuratti** [comment]
solve it chmod 777 /home/YOURWSLNAME/.buildozer/android/platform/android-sdk/tools/bin/sdkmanager

**Comment by Mishabich42** [comment]
sudo chmod +x /root/.buildozer/android/platform/android-sdk/tools/bin/sdkmanager
sudo chmod -R 755 /root/.buildozer/android/platform/android-sdk
