### ISSUE TITLE
GitHub Action

### ISSUE THREAD

**Issue by oxr463** [kivy/buildozer#1110]
See: https://github.com/oxr463/setup-buildozer

**Comment by oxr463** [comment]
```sh
pkg_resources.DistributionNotFound: The 'buildozer==1.0.1.dev0' distribution was not found and is required by the application
```
Source: https://github.com/oxr463/setup-buildozer/runs/683109382?check_suite_focus=true#step:3:98

**Comment by Julian-O** [comment]
It is unclear what you would like the Buildozer team to do here. Please explain further.
