### ISSUE TITLE
Shrink app size

### ISSUE THREAD

**Issue by Hateman31** [kivy/buildozer#1117]
Recently I have built my "hello world" app and got 30 Mb apk. When I installed it on the phone app have taken 100 Mb of memory. Is it possible to decrease app size?

**Comment by tshirtman** [comment]
make sure you didn't include a previous build by mistake in your build, it can happen if you don't exclude the "bin" directory, and each build will be larger than the previous one.

There has been a recent change that made apps bigger than necessary by default in debug mode, as it wasn't removing the debug symbols from the libs anymore i think it should be f, but even then, 30MB sounds like too much, make sure you didn't include assets you didn't mean to. Check the size of an hello world build for comparison. It should be between 8 and 12MB i think, (depending on what version you have), it'll get bigger as well when installed on android, but that's hard to avoid, as we need to ship python with the standard library, which is a bit big.

**Comment by Hateman31** [comment]
I'll try to exclude bin directory. Thanks!

**Comment by Hateman31** [comment]
I've tried to exclude bin directory and made release version. Apk size became 22.4 Mb.

**Comment by AndreMiras** [comment]
Further size reduction can be achieved thanks to https://github.com/kivy/python-for-android/pull/2213 recently merged into develop
