### ISSUE TITLE
Android sdk dir was not specified, exiting.

### ISSUE THREAD

**Issue by Xeizzeth** [kivy/buildozer#1125]
The similar issue exists here: https://github.com/kivy/buildozer/issues/891  
  
But it looks like it uses python 2.7, while I try to build an app using python 3.8.  
  
And I will just copy-paste the comment I left in the original issue:  
  
Tried everything, installing all the dependencies, ncurses5, that just sucked all my blood out and I'm done.
I have this issue and I cannot find a way to get around it.
Also if I need to provide a full log, where I could find it? And how to actually set the log level to 2?
"buildozer android debug log=2" Or some other command?  
  
Any chance to resolve it somehow? This is such a showstopper for me.

**Comment by AndreMiras** [comment]
Please provide complete info as described in the issue template.
Feel free to re-open with all info required when you have it
