### ISSUE TITLE
private.mp3 is a lot smaller after untar

### ISSUE THREAD

**Issue by ricrudo** [kivy/buildozer#1138]
### Versions

* Python: 3.8
* OS: OSX
* Buildozer: 1.1.0

### Description

I'm trying to get a smaller APK, so I checked inside the APK file, and then I discovered that my private.mp3 is 18,4 MB, but when I untar the file I got a 373KB folder, which includes everything I need. Maybe I am missing something, but why the compressed folder is almost 40 times bigger that the uncompressed version? And my other question is if the file inside the APK is the big one, Is that part of the reason for a big APK?

**Comment by AndreMiras** [comment]
Yes I bet for the "Maybe I am missing something" :smile: 
When you `tar -xvf private.mp3` then please also share `du -sh *`
You should see that you have a `_python_bundle` folder and this one is certainly not 400KM, more like 20M+
Also to make a bug report, you should provide more info, like at least the `buildozer.spec` and and maybe in this case the actual APK.
But I think you're missing something

**Comment by ricrudo** [comment]
That's right: I was missing a huge thing!!!
Those are the file you were talking about, weren't you?
 `43M	_python_bundle`
 `18M	private.mp3`
That means two things: 
One: we don't have a issue with the `private.mp3`:) 
Two: I still have the problem with the APK size :(

**Comment by AndreMiras** [comment]
Ahah, regarding the problem you have with your APK size I can say only 3 things

1. make sure buildozer is only including dependencies and source file (so have `source.exclude_dirs` and `source.dir` properly setup
2. give it a try on `p4a.branch = develop`
3. come to Discord for further support request, we'll be happy to guide you

I'm closing the issue as it looks more like a support request than an actual bug.
We'll see you on Discord if you want to discuss further one of the points mentioned above
