### ISSUE TITLE
Requirements branch issue!

### ISSUE THREAD

**Issue by CikoXp** [kivy/buildozer#1143]
Hi guys, i need a way to set appropriate branch for kivy-garden.xcamera pkg in buildozer.spec requirements.
This github repo was updated yesterday because a PythonActivity issue, but the updated branch is the 'develop' and not the 'master'. But builzozer is still downloading the 'master' branch making a clean build.

How i can set desired branch in .spec? `package:branch` is not working.
Maybe `xcamera==branch='develop'`? But i won't continue to make unuseful try. Pls help.

**Comment by CikoXp** [comment]
I'm asking because I know it's possible to select the desired branch because i finded this code in target.py:

`            if branch != 'master':
                url = "--branch {} {}".format(branch, url)`

So my only issue is the appropriate syntax in buildozer.spec. That's all.
Tanx in advance to anyone will help me with this *** noobish issue.

**Comment by AndreMiras** [comment]
You're mistaken, the branch thing is only used for the `python-for-android` clone.
For packages you can do like any python packages by explicitly specifying it in the requirements e.g.
```
requirements = https://github.com/kivy-garden/xcamera/archive/a0058a9.zip
```
Closing as it's an invalid bug. For further support requests, please ask on Discord.
