### ISSUE TITLE
Buildozer Fails to Install garden packages

### ISSUE THREAD

**Issue by qodzero** [kivy/buildozer#1150]
### Versions

* Python: 3.7.6
* OS: Kubuntu 18.04
* Buildozer: 1.2.0

### Description

No matter which app i run, even a simple example app. The moment I add a garden package as a requirement, buildozer crashes. with
```sh
Traceback (most recent call last):
  File "/home/albi/CUCINA/.buildozer/venv/bin/garden", line 189, in <module>
    GardenTool().main(sys.argv[1:])
  File "/home/albi/CUCINA/.buildozer/venv/bin/garden", line 71, in main
    options.func()
  File "/home/albi/CUCINA/.buildozer/venv/bin/garden", line 109, in cmd_install
    fd = self.download(opts.package)
  File "/home/albi/CUCINA/.buildozer/venv/bin/garden", line 170, in download
    data += buf
TypeError: can only concatenate str (not "bytes") to str
``` 
\
Going through the error log, I noticed that this is because, by default buildozer install `Kivy-Garden==0.1.1` which for some reason simply doesn't work. I downgraded my `Kivy-Garden` to `0.1.1` and ran a simple `garden install navigationdrawer`. and the above error is the result so now I know for sure that the error is due to buildozer downloading the wrong version of `Kivy-Garden` because if I use `Kivy-Garden==0.1.4`, which is what Kivy requires, I can download my garden flowers. Ofcourse when I run `buildozer android debug`. Buildozer goes and downloads `Kivy-Garden==0.1.1` again and this error comes back.

Solution
---------------
Please, could you make buildozer download the correct `Kivy-Garden`, i.e version 1.4.0 as 0.1.1 simply doesn't work?
### buildozer.spec
Command:
```sh
buildozer android debug
```

Spec file:
```
The default spec file is fine, simply add any garden requirement
```

### Logs

```sh
Traceback (most recent call last):
  File "/home/albi/CUCINA/.buildozer/venv/bin/garden", line 189, in <module>
    GardenTool().main(sys.argv[1:])
  File "/home/albi/CUCINA/.buildozer/venv/bin/garden", line 71, in main
    options.func()
  File "/home/albi/CUCINA/.buildozer/venv/bin/garden", line 109, in cmd_install
    fd = self.download(opts.package)
  File "/home/albi/CUCINA/.buildozer/venv/bin/garden", line 170, in download
    data += buf
TypeError: can only concatenate str (not "bytes") to str
```

**Comment by AndreMiras** [comment]
Garden is deprecated, now garden packages install like any other Python packages using the `requirements` list, refs https://github.com/kivy/buildozer/pull/1142
Feel free to join Discord for support doing so if needed

**Comment by qodzero** [comment]
Two questions then:

1. What if the target garden flower hasn't been migrated yet?Things start to get confusing real quick (of course i could just install it to my app with the `--app` flag, but what about newbies)
2. Why then does the `garden.requirements` spec option still exists when buildozer won't/can't use it? doesn't that confuse people even more?, naturally if someone sees that spec option they are likely to put their flower requirements there than on the actual pip requirements

**Comment by AndreMiras** [comment]
Yes it's all valid points, the very few unpaid core dev that we're do the best to spend time on the most important things. This comes with a cost of taking some shortcuts like this one.

1. yes theses flowers need to be migrated then
2. the option no longer exists in (unreleased) master https://github.com/kivy/buildozer/pull/1142/files#diff-0b68bfd12f75175020450064eae77a55L47

**Comment by qodzero** [comment]
understood..thanks for clearing that out

**Comment by CoutinhoElias** [comment]
Solved with this tip:

https://stackoverflow.com/questions/62260608/kivy-garden-mapview-deploying-error-with-buildozer
