### ISSUE TITLE
Timed out

### ISSUE THREAD

**Issue by tellts** [kivy/buildozer#1181]
Hello. I did this launch yesterday, and before that I installed and configured in the last few days. Used Java 8 and in Lubuntu 18.0.4 installed Python 3.6.9. Below is the text: "Error log" (translated from Russian). There is also a fragment of text below:
`* master 1b3b0e3f [origin/master] Merge pull request #2225 from kivy/release-2020.06.02
# Run '/usr/bin/python3 -m pip install -q --user \'appdirs\' \'colorama>=0.3.3\' \'jinja2\' \'six\' \'enum34; python_version<"3.4"\' \'sh>=1.10; sys_platform!="nt"\' \'pep517<0.7.0"\' \'toml\''`
I have 2 gigabytes of RAM in my laptop and an operating system installed on a 32 gigabyte USB drive.
I attached a log file to the message.
For some reason, part of the text has become large and bold on the page. I did not do this on purpose.

``
[full log.txt](https://github.com/kivy/buildozer/files/4902378/full.log.txt)

**Comment by tshirtman** [comment]
looks like a platform/configuration problem, not sure we can do anything about it, closing, feel free to ask in support channels if you are still stuck with that.
