### ISSUE TITLE
Hii, facing the issue, after running buildozer android debug deploy run  it shows an error of checking configuration

### ISSUE THREAD

**Issue by pranit811** [kivy/buildozer#1188]
Hii, facing the issue, after running buildozer android debug deploy run  it shows an error of checking configuration. 
Kindly help. What  configuration should i change?

![image](https://user-images.githubusercontent.com/66911107/87516834-a34a2f80-c69b-11ea-8bd5-def04cedf8dd.png)

**Comment by AndreMiras** [comment]
This isn't a valid bug report (see report template). For Support requests use https://chat.kivy.org
