### ISSUE TITLE
Command failed: /usr/bin/python3 -m pythonforandroid.toolchain

### ISSUE THREAD

**Issue by batistadrg** [kivy/buildozer#1191]
Hi, this error is happening when i run the command: "buildozer android debug", or any other command with buildozer but "buildozer init". Can someonw help me?? 

PS: Im brazillian, my english isn perfect! Sorry for mistakes

# Command failed: /usr/bin/python3 -m pythonforandroid.toolchain clean_builds --color=always --storage-dir="/home/zakk/Área de trabalho/projeto original/.buildozer/android/platform/build-armeabi-v7a" --ndk-api=21
# ENVIRONMENT:
#     SHELL = '/bin/bash'
#     SESSION_MANAGER = 'local/kali:@/tmp/.ICE-unix/1483,unix/kali:/tmp/.ICE-unix/1483'
#     QT_ACCESSIBILITY = '1'
#     COLORTERM = 'truecolor'
#     SSH_AGENT_LAUNCHER = 'openssh'
#     XDG_MENU_PREFIX = 'gnome-'
#     GNOME_DESKTOP_SESSION_ID = 'this-is-deprecated'
#     LANGUAGE = 'pt_BR:pt:en'
#     POWERSHELL_TELEMETRY_OPTOUT = '1'
#     SSH_AUTH_SOCK = '/run/user/1000/keyring/ssh'
#     XMODIFIERS = '@im=ibus'
#     DESKTOP_SESSION = 'gnome'
#     GTK_MODULES = 'gail:atk-bridge'
#     PWD = '/home/zakk/Área de trabalho/projeto original'
#     LOGNAME = 'zakk'
#     XDG_SESSION_DESKTOP = 'gnome'
#     QT_QPA_PLATFORMTHEME = 'qt5ct'
#     XDG_SESSION_TYPE = 'wayland'
#     XAUTHORITY = '/run/user/1000/.mutter-Xwaylandauth.Q5N5N0'
#     GJS_DEBUG_TOPICS = 'JS ERROR;JS LOG'
#     GDM_LANG = 'pt_BR.UTF-8'
#     HOME = '/home/zakk'
#     USERNAME = 'zakk'
#     LANG = 'pt_BR.UTF-8'
#     LS_COLORS = 'rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=00:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.zst=01;31:*.tzst=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.wim=01;31:*.swm=01;31:*.dwm=01;31:*.esd=01;31:*.jpg=01;35:*.jpeg=01;35:*.mjpg=01;35:*.mjpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=00;36:*.au=00;36:*.flac=00;36:*.m4a=00;36:*.mid=00;36:*.midi=00;36:*.mka=00;36:*.mp3=00;36:*.mpc=00;36:*.ogg=00;36:*.ra=00;36:*.wav=00;36:*.oga=00;36:*.opus=00;36:*.spx=00;36:*.xspf=00;36:'
#     XDG_CURRENT_DESKTOP = 'GNOME'
#     VTE_VERSION = '6003'
#     WAYLAND_DISPLAY = 'wayland-0'
#     GNOME_TERMINAL_SCREEN = '/org/gnome/Terminal/screen/c84a083d_85a3_4f56_9f2a_9c26ee69fa05'
#     INVOCATION_ID = '1d4150059de44595b8e2d75f0d2e6ff5'
#     MANAGERPID = '1363'
#     GJS_DEBUG_OUTPUT = 'stderr'
#     GNOME_SETUP_DISPLAY = ':1'
#     XDG_SESSION_CLASS = 'user'
#     TERM = 'xterm-256color'
#     USER = 'zakk'
#     GNOME_TERMINAL_SERVICE = ':1.97'
#     DISPLAY = ':0'
#     SHLVL = '1'
#     QT_IM_MODULE = 'ibus'
#     XDG_RUNTIME_DIR = '/run/user/1000'
#     QT_AUTO_SCREEN_SCALE_FACTOR = '0'
#     JOURNAL_STREAM = '8:27635'
#     PATH = '/home/zakk/.local/bin:/usr/local/sbin:/usr/sbin:/sbin:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games'
#     GDMSESSION = 'gnome'
#     DBUS_SESSION_BUS_ADDRESS = 'unix:path=/run/user/1000/bus'
#     _JAVA_OPTIONS = '-Dawt.useSystemAAFontSettings=on -Dswing.aatext=true'
#     OLDPWD = '/home/zakk/Área de trabalho'
#     _ = '/usr/local/bin/buildozer'
# 
# Buildozer failed to execute the last command
# The error might be hidden in the log above this error
# Please read the full log, and search for it before
# raising an issue with buildozer itself.
# In case of a bug report, please add a full log with log_level = 2

**Comment by RobertFlatt** [comment]
> In case of a bug report, please add a full log with log_level = 2
Then run Buildozer again.
You should then see extra info that will explain the cause.

**Comment by batistadrg** [comment]
> > In case of a bug report, please add a full log with log_level = 2
> 
> Then run Buildozer again.
> You should then see extra info that will explain the cause.


/home/zakk/Área de trabalho/projeto original/.buildozer/android/platform/python-for-android/pythonforandroid/toolchain.py:84: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import imp
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/zakk/Área de trabalho/projeto original/.buildozer/android/platform/python-for-android/pythonforandroid/toolchain.py", line 1260, in <module>
    main()
  File "/home/zakk/Área de trabalho/projeto original/.buildozer/android/platform/python-for-android/pythonforandroid/entrypoints.py", line 18, in main
    ToolchainCL()
  File "/home/zakk/Área de trabalho/projeto original/.buildozer/android/platform/python-for-android/pythonforandroid/toolchain.py", line 694, in __init__
    self.ctx.setup_dirs(self.storage_dir)
  File "/home/zakk/Área de trabalho/projeto original/.buildozer/android/platform/python-for-android/pythonforandroid/build.py", line 173, in setup_dirs
    raise ValueError('storage dir path cannot contain spaces, please '
ValueError: storage dir path cannot contain spaces, please specify a path with --storage-dir


What is that value error?

**Comment by RobertFlatt** [comment]
> storage dir path cannot contain spaces, 

I expect it is complainig about these 3 whitespaces (' '):
/Área de trabalho/projeto original/

**Comment by batistadrg** [comment]
Oh yeah, thnks man!! But now i have another problem:

Could not fetch URL https://pypi.org/simple/pip/: There was a problem confirming the ssl certificate: HTTPSConnectionPool(host='pypi.org', port=443): Max retries exceeded with url: /simple/pip/ (Caused by SSLError("Can't connect to HTTPS URL because the SSL module is not available.")) - skipping


  STDERR:

do you know something??

**Comment by RobertFlatt** [comment]
I suspect this is required
`sudo apt install libssl-dev`

It was added to the dependencies a couple of months ago:
https://buildozer.readthedocs.io/en/latest/installation.html#android-on-ubuntu-20-04-64bit

**Comment by batistadrg** [comment]
> I suspect this is required
> `sudo apt install libssl-dev`
> 
> It was added to the dependencies a couple of months ago:
> https://buildozer.readthedocs.io/en/latest/installation.html#android-on-ubuntu-20-04-64bit


The same problem... But i found this message before the error:

Collecting Cython
  WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/cython/
  WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/cython/
  WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/cython/
  WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/cython/
  WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/cython/


Cython is installed but this error keeps.
idk why the issue was closed.

**Comment by RobertFlatt** [comment]
Try a
`buildozer appclean`
before
`buildozer android debug`

**Comment by batistadrg** [comment]
Worked!!! thnks man :)

**Comment by batistadrg** [comment]
> Try a
> `buildozer appclean`
> before
> `buildozer android debug`

Worked!!! Thanks man!!=)
