### ISSUE TITLE
Duplicate field in buildozer.spec

### ISSUE THREAD

**Issue by RobertFlatt** [kivy/buildozer#1207]
### Versions

* Python:
* OS:
* Buildozer: 1.2

### Description

Duplicate field in buildozer.spec, but descriptive texts for each instance are different. Field is:
#android.add_gradle_repositories =

More generally these exotic options need much more complete documention. A few lines in the .spec doesnt cut it.

### buildozer.spec

```
# (list) Gradle repositories to add {can be necessary for some android.gradle_dependencies}
# please enclose in double quotes 
# e.g. android.gradle_repositories = "maven { url 'https://kotlin.bintray.com/ktor' }"
#android.add_gradle_repositories =

# (list) packaging options to add 
# see https://google.github.io/android-gradle-dsl/current/com.android.build.gradle.internal.dsl.PackagingOptions.html
# can be necessary to solve conflicts in gradle_dependencies
# please enclose in double quotes 
# e.g. android.add_packaging_options = "exclude 'META-INF/common.kotlin_module'", "exclude 'META-INF/*.kotlin_module'"
#android.add_gradle_repositories =
```

### Logs

```
// REPLACE ME: Paste the build ouput containing the error
```

**Comment by AndreMiras** [comment]
Thanks for the report, could you make a pull request to fix?
https://github.com/kivy/buildozer/blob/1.2.0/buildozer/default.spec

**Comment by RobertFlatt** [comment]
Thank you for the invite, it would be an excellent low risk intrduction to the Github tools.
However I do not have the bandwidth to make a commitment at this time.
Regards.

**Comment by Julian-O** [comment]
Looking at default.spec several years later, the second entry has been corrected to

    #android.add_packaging_options =
    
Closing as complete (even though some more documentation would be nice)
