### ISSUE TITLE
Many SyntaxErrors and SyntaxWarning in Buildozer compile

### ISSUE THREAD

**Issue by HeRo002** [kivy/buildozer#1227]
I have a Kivy project that uses matplotlib etc. 

It worries me a little that Buildozer lists at least 17 SyntaxErrors and 3 SyntaxWarnings. 
The strangest thing is that the files with syntax errors have names like "bad_coding.py" and "badsyntax_future10.py"... 

I think Buildozer was run with the following in buildozer.spec.

requirements = python3,kivy==2.0.0rc3,pillow,docutils,matplotlib==3.1.2

### Versions

* Python: v3.8.2
* OS: Ubuntu 20.04.1 LTS
* Buildozer: 1.2.0

### Description

Buildozer didn't fail to compile! 

### buildozer.spec

I don't think it's necessary to list the whole spec file here.

Command: buildozer android debug

Here is the parts of the Buildozer log that displays the errors: 

Compiling '/mnt/4AF15A0435E762B4/mypython/GeoESP/.buildozer/android/platform/build-armeabi-v7a/build/other_builds/python3/armeabi-v7a__ndk_target_21/python3/Lib/lib2to3/tests/data/bom.py'...
***   File "/mnt/4AF15A0435E762B4/mypython/GeoESP/.buildozer/android/platform/build-armeabi-v7a/build/other_builds/python3/armeabi-v7a__ndk_target_21/python3/Lib/lib2to3/tests/data/bom.py", line 2
    print "BOM BOOM!"
          ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print("BOM BOOM!")?

Compiling '/mnt/4AF15A0435E762B4/mypython/GeoESP/.buildozer/android/platform/build-armeabi-v7a/build/other_builds/python3/armeabi-v7a__ndk_target_21/python3/Lib/lib2to3/tests/data/crlf.py'...
***   File "/mnt/4AF15A0435E762B4/mypython/GeoESP/.buildozer/android/platform/build-armeabi-v7a/build/other_builds/python3/armeabi-v7a__ndk_target_21/python3/Lib/lib2to3/tests/data/crlf.py", line 1
    print "hi"
          ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print("hi")?

Compiling '/mnt/4AF15A0435E762B4/mypython/GeoESP/.buildozer/android/platform/build-armeabi-v7a/build/other_builds/python3/armeabi-v7a__ndk_target_21/python3/Lib/lib2to3/tests/data/different_encoding.py'...
***   File "/mnt/4AF15A0435E762B4/mypython/GeoESP/.buildozer/android/platform/build-armeabi-v7a/build/other_builds/python3/armeabi-v7a__ndk_target_21/python3/Lib/lib2to3/tests/data/different_encoding.py", line 3
    print u'ßàáâãäåæçèéêëìíîïðñòóôõöøùúûüýþÿÀÁÂÃÄÅÆÇÈÉÊËÌÍÎÏÐÑÒÓÔÕÖØÙÚÛÜÝÞ'
          ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print(u'ßàáâãäåæçèéêëìíîïðñòóôõöøùúûüýþÿÀÁÂÃÄÅÆÇÈÉÊËÌÍÎÏÐÑÒÓÔÕÖØÙÚÛÜÝÞ')?

Compiling '/mnt/4AF15A0435E762B4/mypython/GeoESP/.buildozer/android/platform/build-armeabi-v7a/build/other_builds/python3/armeabi-v7a__ndk_target_21/python3/Lib/lib2to3/tests/data/false_encoding.py'...
***   File "/mnt/4AF15A0435E762B4/mypython/GeoESP/.buildozer/android/platform/build-armeabi-v7a/build/other_builds/python3/armeabi-v7a__ndk_target_21/python3/Lib/lib2to3/tests/data/false_encoding.py", line 2
    print '#coding=0'
          ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print('#coding=0')?

Compiling '/mnt/4AF15A0435E762B4/mypython/GeoESP/.buildozer/android/platform/build-armeabi-v7a/build/other_builds/python3/armeabi-v7a__ndk_target_21/python3/Lib/lib2to3/tests/data/py2_test_grammar.py'...
***   File "/mnt/4AF15A0435E762B4/mypython/GeoESP/.buildozer/android/platform/build-armeabi-v7a/build/other_builds/python3/armeabi-v7a__ndk_target_21/python3/Lib/lib2to3/tests/data/py2_test_grammar.py", line 31
    self.assertEquals(0377, 255)
                         ^
SyntaxError: leading zeros in decimal integer literals are not permitted; use an 0o prefix for octal integers

Compiling '/mnt/4AF15A0435E762B4/mypython/GeoESP/.buildozer/android/platform/build-armeabi-v7a/build/other_builds/python3/armeabi-v7a__ndk_target_21/python3/Lib/test/bad_coding.py'...
***   File "/mnt/4AF15A0435E762B4/mypython/GeoESP/.buildozer/android/platform/build-armeabi-v7a/build/other_builds/python3/armeabi-v7a__ndk_target_21/python3/Lib/test/bad_coding.py", line 0
SyntaxError: unknown encoding: uft-8

Compiling '/mnt/4AF15A0435E762B4/mypython/GeoESP/.buildozer/android/platform/build-armeabi-v7a/build/other_builds/python3/armeabi-v7a__ndk_target_21/python3/Lib/test/bad_coding2.py'...
***   File "/mnt/4AF15A0435E762B4/mypython/GeoESP/.buildozer/android/platform/build-armeabi-v7a/build/other_builds/python3/armeabi-v7a__ndk_target_21/python3/Lib/test/bad_coding2.py", line 0
SyntaxError: encoding problem: utf8 with BOM

Compiling '/mnt/4AF15A0435E762B4/mypython/GeoESP/.buildozer/android/platform/build-armeabi-v7a/build/other_builds/python3/armeabi-v7a__ndk_target_21/python3/Lib/test/badsyntax_3131.py'...
***   File "/mnt/4AF15A0435E762B4/mypython/GeoESP/.buildozer/android/platform/build-armeabi-v7a/build/other_builds/python3/armeabi-v7a__ndk_target_21/python3/Lib/test/badsyntax_3131.py", line 2
    € = 2
    ^
SyntaxError: invalid character in identifier

Compiling '/mnt/4AF15A0435E762B4/mypython/GeoESP/.buildozer/android/platform/build-armeabi-v7a/build/other_builds/python3/armeabi-v7a__ndk_target_21/python3/Lib/test/badsyntax_future10.py'...
***   File "/mnt/4AF15A0435E762B4/mypython/GeoESP/.buildozer/android/platform/build-armeabi-v7a/build/other_builds/python3/armeabi-v7a__ndk_target_21/python3/Lib/test/badsyntax_future10.py", line 3
    from __future__ import print_function
    ^
SyntaxError: from __future__ imports must occur at the beginning of the file

Compiling '/mnt/4AF15A0435E762B4/mypython/GeoESP/.buildozer/android/platform/build-armeabi-v7a/build/other_builds/python3/armeabi-v7a__ndk_target_21/python3/Lib/test/badsyntax_future3.py'...
***   File "/mnt/4AF15A0435E762B4/mypython/GeoESP/.buildozer/android/platform/build-armeabi-v7a/build/other_builds/python3/armeabi-v7a__ndk_target_21/python3/Lib/test/badsyntax_future3.py", line 3
    from __future__ import rested_snopes
    ^
SyntaxError: future feature rested_snopes is not defined

Compiling '/mnt/4AF15A0435E762B4/mypython/GeoESP/.buildozer/android/platform/build-armeabi-v7a/build/other_builds/python3/armeabi-v7a__ndk_target_21/python3/Lib/test/badsyntax_future4.py'...
***   File "/mnt/4AF15A0435E762B4/mypython/GeoESP/.buildozer/android/platform/build-armeabi-v7a/build/other_builds/python3/armeabi-v7a__ndk_target_21/python3/Lib/test/badsyntax_future4.py", line 3
    from __future__ import nested_scopes
    ^
SyntaxError: from __future__ imports must occur at the beginning of the file

Compiling '/mnt/4AF15A0435E762B4/mypython/GeoESP/.buildozer/android/platform/build-armeabi-v7a/build/other_builds/python3/armeabi-v7a__ndk_target_21/python3/Lib/test/badsyntax_future5.py'...
***   File "/mnt/4AF15A0435E762B4/mypython/GeoESP/.buildozer/android/platform/build-armeabi-v7a/build/other_builds/python3/armeabi-v7a__ndk_target_21/python3/Lib/test/badsyntax_future5.py", line 4
    from __future__ import nested_scopes
    ^
SyntaxError: from __future__ imports must occur at the beginning of the file

Compiling '/mnt/4AF15A0435E762B4/mypython/GeoESP/.buildozer/android/platform/build-armeabi-v7a/build/other_builds/python3/armeabi-v7a__ndk_target_21/python3/Lib/test/badsyntax_future6.py'...
***   File "/mnt/4AF15A0435E762B4/mypython/GeoESP/.buildozer/android/platform/build-armeabi-v7a/build/other_builds/python3/armeabi-v7a__ndk_target_21/python3/Lib/test/badsyntax_future6.py", line 3
    from __future__ import nested_scopes
    ^
SyntaxError: from __future__ imports must occur at the beginning of the file

Compiling '/mnt/4AF15A0435E762B4/mypython/GeoESP/.buildozer/android/platform/build-armeabi-v7a/build/other_builds/python3/armeabi-v7a__ndk_target_21/python3/Lib/test/badsyntax_future7.py'...
***   File "/mnt/4AF15A0435E762B4/mypython/GeoESP/.buildozer/android/platform/build-armeabi-v7a/build/other_builds/python3/armeabi-v7a__ndk_target_21/python3/Lib/test/badsyntax_future7.py", line 3
    from __future__ import nested_scopes; import string; from __future__ import \
                                                        ^
SyntaxError: from __future__ imports must occur at the beginning of the file

Compiling '/mnt/4AF15A0435E762B4/mypython/GeoESP/.buildozer/android/platform/build-armeabi-v7a/build/other_builds/python3/armeabi-v7a__ndk_target_21/python3/Lib/test/badsyntax_future8.py'...
***   File "/mnt/4AF15A0435E762B4/mypython/GeoESP/.buildozer/android/platform/build-armeabi-v7a/build/other_builds/python3/armeabi-v7a__ndk_target_21/python3/Lib/test/badsyntax_future8.py", line 3
    from __future__ import *
    ^
SyntaxError: future feature * is not defined

Compiling '/mnt/4AF15A0435E762B4/mypython/GeoESP/.buildozer/android/platform/build-armeabi-v7a/build/other_builds/python3/armeabi-v7a__ndk_target_21/python3/Lib/test/badsyntax_future9.py'...
***   File "/mnt/4AF15A0435E762B4/mypython/GeoESP/.buildozer/android/platform/build-armeabi-v7a/build/other_builds/python3/armeabi-v7a__ndk_target_21/python3/Lib/test/badsyntax_future9.py", line 3
    from __future__ import nested_scopes, braces
    ^
SyntaxError: not a chance

Compiling '/mnt/4AF15A0435E762B4/mypython/GeoESP/.buildozer/android/platform/build-armeabi-v7a/build/other_builds/python3/armeabi-v7a__ndk_target_21/python3/Lib/test/badsyntax_pep3120.py'...
***   File "/mnt/4AF15A0435E762B4/mypython/GeoESP/.buildozer/android/platform/build-armeabi-v7a/build/other_builds/python3/armeabi-v7a__ndk_target_21/python3/Lib/test/badsyntax_pep3120.py", line 1
SyntaxError: (unicode error) 'utf-8' codec can't decode byte 0xf6 in position 1: invalid start byte

/mnt/4AF15A0435E762B4/mypython/GeoESP/.buildozer/android/platform/build-armeabi-v7a/build/other_builds/python3/armeabi-v7a__ndk_target_21/python3/Lib/lib2to3/tests/data/py3_test_grammar.py:652: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if 1 is 1: pass
/mnt/4AF15A0435E762B4/mypython/GeoESP/.buildozer/android/platform/build-armeabi-v7a/build/other_builds/python3/armeabi-v7a__ndk_target_21/python3/Lib/lib2to3/tests/data/py3_test_grammar.py:653: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if 1 is not 1: pass
/mnt/4AF15A0435E762B4/mypython/GeoESP/.buildozer/android/platform/build-armeabi-v7a/build/other_builds/python3/armeabi-v7a__ndk_target_21/python3/Lib/lib2to3/tests/data/py3_test_grammar.py:656: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if 1 < 1 > 1 == 1 >= 1 <= 1 != 1 in 1 not in 1 is 1 is not 1: pass

**Comment by tito** [comment]
That's expected. We compile to pyo the whole site-packages, libs, etc, of Python and dependencies.
When you install one, it may come with tests files, maybe made for previous Python version.

It's a good indicator that you could blacklist all the tests files from the library you installed, as it wont be used in your app anyway.

**Comment by xucian** [comment]
what do you mean by blacklist? I thought you mean simply deleting that folder called 'test' which has all these (and it's under .buildozer), but it seems the build process (`buildozer android debug deploy run`) brings it back.
I see why 'failing' the test is expected, but my build just stops after that error

it's also weird that inside an android folder there's stuff about ios.. is that expected?

this is on an intel mac, where I've previously successfully built for ios (and ran it in simulator/device)

also, this works fine on windows, with the same commands, I was able to run it on my android device

```
# Copy /Users/luti/dev/py.angry.translator/build/pyobjus/iphonesimulator-x86_64/pyobjus-master/pyobjus/consts/corebluetooth.py
# Package the application
# project.properties updated
# Run ['/Users/luti/dev/py.angry.translator/venv/bin/python', '-m', 'pythonforandroid.toolchain', 'apk', '--bootstrap', 'sdl2', '--dist_name', 'angrytranslator', '--name', 'Angry Translator', '--version', '0.1', '--package', 'com.explode9.angrytranslator', '--minsdk', '21', '--ndk-api', '21', '--private', '/Users/luti/dev/py.angry.translator/.buildozer/android/app', '--permission', 'android.permission.INTERNET', '--permission', '(name=android.permission.WRITE_EXTERNAL_STORAGE;maxSdkVersion=18)', '--android-entrypoint', 'org.kivy.android.PythonActivity', '--android-apptheme', '@android:style/Theme.NoTitleBar', '--orientation', 'portrait', '--window', '--enable-androidx', '--copy-libs', '--arch', 'arm64-v8a', '--arch', 'armeabi-v7a', '--color=always', '--storage-dir=/Users/luti/dev/py.angry.translator/.buildozer/android/platform/build-arm64-v8a_armeabi-v7a', '--ndk-api=21', '--ignore-setup-py', '--debug']
# Cwd /Users/luti/dev/py.angry.translator/.buildozer/android/platform/python-for-android
[WARNING]: prerequisites.py is experimental and does not support all prerequisites yet.
[WARNING]: Please report any issues to the python-for-android issue tracker.
[INFO]:    Prerequisite homebrew is met
[INFO]:    Prerequisite autoconf is met
[INFO]:    Prerequisite automake is met
[INFO]:    Prerequisite libtool is met
[INFO]:    Prerequisite pkg-config is met
[INFO]:    Prerequisite cmake is met
[INFO]:    Prerequisite openssl is met
[INFO]:    Found a valid JDK at /Users/luti/Library/Java/JavaVirtualMachines/jdk-17.0.2+8/Contents/Home
[INFO]:    Prerequisite JDK is met
[WARNING]: prerequisites.py is experimental and does not support all prerequisites yet.
[WARNING]: Please report any issues to the python-for-android issue tracker.
[INFO]:    Prerequisite homebrew is met
[INFO]:    Prerequisite autoconf is met
[INFO]:    Prerequisite automake is met
[INFO]:    Prerequisite libtool is met
[INFO]:    Prerequisite pkg-config is met
[INFO]:    Prerequisite cmake is met
[INFO]:    Prerequisite openssl is met
[INFO]:    Found a valid JDK at /Users/luti/Library/Java/JavaVirtualMachines/jdk-17.0.2+8/Contents/Home
[INFO]:    Prerequisite JDK is met
[INFO]:    Will compile for the following archs: armeabi-v7a, arm64-v8a
[INFO]:    Found Android API target in $ANDROIDAPI: 31
[INFO]:    Available Android APIs are (31)
[INFO]:    Requested API target 31 is available, continuing.
[INFO]:    Found NDK dir in $ANDROIDNDK: /Users/luti/.buildozer/android/platform/android-ndk-r25b
[INFO]:    Found NDK version 25b
[INFO]:    Getting NDK API version (i.e. minimum supported API) from user argument
[INFO]:    ccache is missing, the build will not be optimized in the future.
[DEBUG]:   All possible dists: [<Distribution: name angrytranslator with recipes (hostpython3, libffi, openssl, sdl2_image, sdl2_mixer, sdl2_ttf, sqlite3, python3, sdl2, setuptools, six, pyjnius, android, kivy, urllib3, requests, idna, certifi, chardet)>]
[DEBUG]:   Dist matching name and arch: [<Distribution: name angrytranslator with recipes (hostpython3, libffi, openssl, sdl2_image, sdl2_mixer, sdl2_ttf, sqlite3, python3, sdl2, setuptools, six, pyjnius, android, kivy, urllib3, requests, idna, certifi, chardet)>]
[DEBUG]:   Dist matching ndk_api and recipe: [<Distribution: name angrytranslator with recipes (hostpython3, libffi, openssl, sdl2_image, sdl2_mixer, sdl2_ttf, sqlite3, python3, sdl2, setuptools, six, pyjnius, android, kivy, urllib3, requests, idna, certifi, chardet)>]
[INFO]:    Of the existing distributions, the following meet the given requirements:
[INFO]:         angrytranslator: min API 21, includes recipes (hostpython3, libffi, openssl, sdl2_image, sdl2_mixer, sdl2_ttf, sqlite3, python3, sdl2, setuptools, six, pyjnius, android, kivy, urllib3, requests, idna, certifi, chardet), built for archs (armeabi-v7a, arm64-v8a)
[INFO]:    angrytranslator has compatible recipes, using this one
[DEBUG]:   All possible dists: [<Distribution: name angrytranslator with recipes (hostpython3, libffi, openssl, sdl2_image, sdl2_mixer, sdl2_ttf, sqlite3, python3, sdl2, setuptools, six, pyjnius, android, kivy, urllib3, requests, idna, certifi, chardet)>]
[DEBUG]:   Dist matching name and arch: [<Distribution: name angrytranslator with recipes (hostpython3, libffi, openssl, sdl2_image, sdl2_mixer, sdl2_ttf, sqlite3, python3, sdl2, setuptools, six, pyjnius, android, kivy, urllib3, requests, idna, certifi, chardet)>]
[DEBUG]:   Dist matching ndk_api and recipe: [<Distribution: name angrytranslator with recipes (hostpython3, libffi, openssl, sdl2_image, sdl2_mixer, sdl2_ttf, sqlite3, python3, sdl2, setuptools, six, pyjnius, android, kivy, urllib3, requests, idna, certifi, chardet)>]
[INFO]:    Of the existing distributions, the following meet the given requirements:
[INFO]:         angrytranslator: min API 21, includes recipes (hostpython3, libffi, openssl, sdl2_image, sdl2_mixer, sdl2_ttf, sqlite3, python3, sdl2, setuptools, six, pyjnius, android, kivy, urllib3, requests, idna, certifi, chardet), built for archs (armeabi-v7a, arm64-v8a)
[INFO]:    angrytranslator has compatible recipes, using this one
[INFO]:    -> directory context /Users/luti/dev/py.angry.translator/.buildozer/android/platform/build-arm64-v8a_armeabi-v7a/build/bootstrap_builds/sdl2
[INFO]:    <- directory context /Users/luti/dev/py.angry.translator/.buildozer/android/platform/python-for-android
[INFO]:    -> directory context /Users/luti/dev/py.angry.translator/.buildozer/android/platform/build-arm64-v8a_armeabi-v7a/dists/angrytranslator
[DEBUG]:   Remove directory and subdirectory src/main/assets
[DEBUG]:   Create directory src/main/assets
Compiling '/Users/luti/dev/py.angry.translator/.buildozer/android/app/dist/hostpython3/lib/python3.11/test/test_future_stmt/badsyntax_future10.py'...
***   File "/Users/luti/dev/py.angry.translator/.buildozer/android/app/dist/hostpython3/lib/python3.11/test/test_future_stmt/badsyntax_future10.py", line 3
    from __future__ import print_function
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
SyntaxError: from __future__ imports must occur at the beginning of the file

No setup.py/pyproject.toml used, copying full private data into .apk.
Error while running "/Users/luti/dev/py.angry.translator/.buildozer/android/platform/build-arm64-v8a_armeabi-v7a/build/other_builds/hostpython3/desktop/hostpython3/native-build/python3 -OO -m compileall -b -f /Users/luti/dev/py.angry.translator/.buildozer/android/app/dist/hostpython3/lib/python3.11/test/test_future_stmt/badsyntax_future10.py"
This probably means one of your Python files has a syntax error, see logs above
# Command failed: ['/Users/luti/dev/py.angry.translator/venv/bin/python', '-m', 'pythonforandroid.toolchain', 'apk', '--bootstrap', 'sdl2', '--dist_name', 'angrytranslator', '--name', 'Angry Translator', '--version', '0.1', '--package', 'com.explode9.angrytranslator', '--minsdk', '21', '--ndk-api', '21', '--private', '/Users/luti/dev/py.angry.translator/.buildozer/android/app', '--permission', 'android.permission.INTERNET', '--permission', '(name=android.permission.WRITE_EXTERNAL_STORAGE;maxSdkVersion=18)', '--android-entrypoint', 'org.kivy.android.PythonActivity', '--android-apptheme', '@android:style/Theme.NoTitleBar', '--orientation', 'portrait', '--window', '--enable-androidx', '--copy-libs', '--arch', 'arm64-v8a', '--arch', 'armeabi-v7a', '--color=always', '--storage-dir=/Users/luti/dev/py.angry.translator/.buildozer/android/platform/build-arm64-v8a_armeabi-v7a', '--ndk-api=21', '--ignore-setup-py', '--debug']
# ENVIRONMENT:
#     PATH = '/Users/luti/.buildozer/android/platform/apache-ant-1.9.4/bin:/Users/luti/dev/py.angry.translator/venv/bin:/usr/local/bin:/usr/local/sbin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/Library/Apple/usr/bin'
#     __CFBundleIdentifier = 'com.jetbrains.pycharm.ce'
#     SHELL = '/bin/zsh'
#     TERM = 'xterm-256color'
#     USER = 'luti'
#     TMPDIR = '/var/folders/_8/jg10h83n5dl4t0tgrfkmlcs00000gn/T/'
#     COMMAND_MODE = 'unix2003'
#     TERMINAL_EMULATOR = 'JetBrains-JediTerm'
#     SSH_AUTH_SOCK = '/private/tmp/com.apple.launchd.hrD5GfExLB/Listeners'
#     XPC_FLAGS = '0x0'
#     TERM_SESSION_ID = '3999e6ef-b57f-4d18-ac59-f5240b323edf'
#     __CF_USER_TEXT_ENCODING = '0x1F5:0x0:0x0'
#     LOGNAME = 'luti'
#     LC_CTYPE = 'UTF-8'
#     XPC_SERVICE_NAME = '0'
#     IDEA_INITIAL_DIRECTORY = '/'
#     HOME = '/Users/luti'
#     SHLVL = '1'
#     PWD = '/Users/luti/dev/py.angry.translator'
#     OLDPWD = '/Users/luti/dev/py.angry.translator'
#     HOMEBREW_PREFIX = '/usr/local'
#     HOMEBREW_CELLAR = '/usr/local/Cellar'
#     HOMEBREW_REPOSITORY = '/usr/local/Homebrew'
#     MANPATH = '/usr/local/share/man::'
#     INFOPATH = '/usr/local/share/info:'
#     VIRTUAL_ENV = '/Users/luti/dev/py.angry.translator/venv'
#     VIRTUAL_ENV_PROMPT = 'venv'
#     PS1 = '(venv) %n@%m %1~ %# '
#     _ = '/Users/luti/dev/py.angry.translator/venv/bin/buildozer'
#     PACKAGES_PATH = '/Users/luti/.buildozer/android/packages'
#     ANDROIDSDK = '/Users/luti/.buildozer/android/platform/android-sdk'
#     ANDROIDNDK = '/Users/luti/.buildozer/android/platform/android-ndk-r25b'
#     ANDROIDAPI = '31'
#     ANDROIDMINAPI = '21'
# 
# Buildozer failed to execute the last command
# The error might be hidden in the log above this error
# Please read the full log, and search for it before
# raising an issue with buildozer itself.
# In case of a bug report, please add a full log with log_level = 2
(venv) luti@mac py.angry.translator % 
```





> That's expected. We compile to pyo the whole site-packages, libs, etc, of Python and dependencies. When you install one, it may come with tests files, maybe made for previous Python version.
> 
> It's a good indicator that you could blacklist all the tests files from the library you installed, as it wont be used in your app anyway.
