### ISSUE TITLE
Issue: Can't build app based on error log

### ISSUE THREAD

**Issue by kanbogkingdev** [kivy/buildozer#1234]
Hello all,

I have a problem with my app building android using kivy and kivymd - which is already put  in buildozer.spec requirements
Below is my error log: 

[INFO]:    Applying patches for pyjnius[armeabi-v7a]
[INFO]:    Applying patch sdl2_jnienv_getter.patch
[INFO]:    -> running patch -t -d /home/vas/Downloads/MOB(HWR)/.buildozer/android/platform/build-armeabi-v7a/build/other_builds/pyjnius-sdl2/armeabi-v7a__ndk_target_21/pyjnius ...(and 140 more)
[INFO]:    -> running touch /home/vas/Downloads/MOB(HWR)/.buildozer/android/platform/build-armeabi-v7a/build/other_builds/pyjnius-sdl2/armeabi-v7a__ndk_target_21/pyjnius/.patched                         
[INFO]:    Prebuilding android for armeabi-v7a
[INFO]:    android has no prebuild_armeabi_v7a, skipping
[INFO]:    -> directory context /home/vas/Downloads/MOB(HWR)/.buildozer/android/platform/build-armeabi-v7a/build/other_builds/android-sdl2/armeabi-v7a__ndk_target_21/android
[INFO]:    <- directory context /home/vas/Downloads/MOB(HWR)/.buildozer/android/platform/python-for-android
[INFO]:    Prebuilding kivy for armeabi-v7a
[INFO]:    kivy has no prebuild_armeabi_v7a, skipping
[INFO]:    # Building recipes
[INFO]:    Building hostpython3 for armeabi-v7a
[INFO]:    -> directory context /home/vas/Downloads/MOB(HWR)/.buildozer/android/platform/build-armeabi-v7a/build/other_builds/hostpython3/desktop/hostpython3/native-build
[INFO]:    -> running configure
[INFO]:    <- directory context /home/vas/Downloads/MOB(HWR)/.buildozer/android/platform/python-for-android                                                                                                
[INFO]:    -> directory context /home/vas/Downloads/MOB(HWR)/.buildozer/android/platform/build-armeabi-v7a/build/other_builds/hostpython3/desktop/hostpython3
[INFO]:    -> running make -j 6 -C /home/vas/Downloads/MOB(HWR)/.buildozer/android/platform/build-armeabi-v7a/build/other_builds/hostpython3/desktop/hostpython3/native-build
Exception in thread background thread for pid 25189:                                                                                                                                                       
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/home/vas/.local/lib/python3.6/site-packages/sh.py", line 1633, in wrap
    fn(*rgs, **kwargs)
  File "/home/vas/.local/lib/python3.6/site-packages/sh.py", line 2557, in background_thread
    handle_exit_code(exit_code)
  File "/home/vas/.local/lib/python3.6/site-packages/sh.py", line 2261, in fn
    return self.command.handle_command_exit_code(exit_code)
  File "/home/vas/.local/lib/python3.6/site-packages/sh.py", line 861, in handle_command_exit_code
    raise exc
sh.ErrorReturnCode_2: 

  RAN: /usr/bin/make -j 6 -C '/home/vas/Downloads/MOB(HWR)/.buildozer/android/platform/build-armeabi-v7a/build/other_builds/hostpython3/desktop/hostpython3/native-build'

  STDOUT:
make: Entering directory '/home/vas/Downloads/MOB(HWR)/.buildozer/android/platform/build-armeabi-v7a/build/other_builds/hostpython3/desktop/hostpython3/native-build'
gcc -pthread -c -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall    -std=c99 -Wextra -Wno-unused-result -Wno-unused-parameter -Wno-missing-field-initializers -Werror=implicit-function-declaration  -I/home/vas/Downloads/MOB(HWR)/.buildozer/android/platform/build-armeabi-v7a/build/other_builds/hostpython3/desktop/hostpython3/Include/internal -IObjects -IInclude -IPython -I. -I/home/vas/Downloads/MOB(HWR)/.buildozer/android/platform/build-armeabi-v7a/build/other_builds/hostpython3/desktop/hostpython3/Include    -DPy_BUILD_CORE -o Programs/python.o /home/vas/Downloads/MOB(HWR)/.buildozer/android/platform/build-armeabi-v7a/build/other_builds/hostpython3/desktop/hostpython3/Programs/python.c
gcc -pthread -c -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall    -std=c99 -Wextra -Wno-unused-result -Wno-unused-parameter -Wno-missing-field-initializers -Werror=implicit-function-declaration  -I/home/vas/Downloads/MOB(HWR)/.buildozer/android/platform/build-armeabi-v7a/build/other_builds/hostpython3/desktop/hostpython3/Include/internal -IObjects -IInclude -IPython -I. -I/home/vas/Downloads/MOB(HWR)/.buildozer/android/platform/build-armeabi-v7a/build/other_builds/hostpython3/desktop/hostpython3/Include    -DPy_BUILD_CORE -o Parser/acceler.o /home/vas/Downloads/MOB(HWR)/.buildozer/android/platform/build-armeabi-v7a/build/other_builds/hostpython3/desktop/hostpython3/Parser/acceler.c
/bin/sh: 1: Syntax error: "(" unexpected
Makefile:772: recipe for target 'Programs/python.o' failed
make: *** [Programs/python.o] Error 2
make: *** Waiting for unfinished jobs....
/bin/sh: 1: Syntax error: "(" unexpected
Makefile:1708: recipe for target 'Parser/acceler.o' failed
make: *** [Parser/acceler.o] Error 2
make: Leaving directory '/home/vas/Downloads/MOB(HWR)/.buildozer/android/platform/build-armeabi-v7a/build/other_builds/hostpython3/desktop/hostpython3/native-build'

  STDERR:

Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/vas/Downloads/MOB(HWR)/.buildozer/android/platform/python-for-android/pythonforandroid/toolchain.py", line 1260, in <module>
    main()
  File "/home/vas/Downloads/MOB(HWR)/.buildozer/android/platform/python-for-android/pythonforandroid/entrypoints.py", line 18, in main
    ToolchainCL()
  File "/home/vas/Downloads/MOB(HWR)/.buildozer/android/platform/python-for-android/pythonforandroid/toolchain.py", line 709, in __init__
    getattr(self, command)(args)
  File "/home/vas/Downloads/MOB(HWR)/.buildozer/android/platform/python-for-android/pythonforandroid/toolchain.py", line 154, in wrapper_func
    build_dist_from_args(ctx, dist, args)
  File "/home/vas/Downloads/MOB(HWR)/.buildozer/android/platform/python-for-android/pythonforandroid/toolchain.py", line 216, in build_dist_from_args
    args, "ignore_setup_py", False
  File "/home/vas/Downloads/MOB(HWR)/.buildozer/android/platform/python-for-android/pythonforandroid/build.py", line 577, in build_recipes
    recipe.build_arch(arch)
  File "/home/vas/Downloads/MOB(HWR)/.buildozer/android/platform/python-for-android/pythonforandroid/recipes/hostpython3/__init__.py", line 116, in build_arch
    shprint(sh.make, '-j', str(cpu_count()), '-C', build_dir)
  File "/home/vas/Downloads/MOB(HWR)/.buildozer/android/platform/python-for-android/pythonforandroid/logger.py", line 167, in shprint
    for line in output:
  File "/home/vas/.local/lib/python3.6/site-packages/sh.py", line 907, in next
    self.wait()
  File "/home/vas/.local/lib/python3.6/site-packages/sh.py", line 837, in wait
    self.handle_command_exit_code(exit_code)
  File "/home/vas/.local/lib/python3.6/site-packages/sh.py", line 861, in handle_command_exit_code
    raise exc
sh.ErrorReturnCode_2: 

  RAN: /usr/bin/make -j 6 -C '/home/vas/Downloads/MOB(HWR)/.buildozer/android/platform/build-armeabi-v7a/build/other_builds/hostpython3/desktop/hostpython3/native-build'

  STDOUT:
make: Entering directory '/home/vas/Downloads/MOB(HWR)/.buildozer/android/platform/build-armeabi-v7a/build/other_builds/hostpython3/desktop/hostpython3/native-build'
gcc -pthread -c -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall    -std=c99 -Wextra -Wno-unused-result -Wno-unused-parameter -Wno-missing-field-initializers -Werror=implicit-function-declaration  -I/home/vas/Downloads/MOB(HWR)/.buildozer/android/platform/build-armeabi-v7a/build/other_builds/hostpython3/desktop/hostpython3/Include/internal -IObjects -IInclude -IPython -I. -I/home/vas/Downloads/MOB(HWR)/.buildozer/android/platform/build-armeabi-v7a/build/other_builds/hostpython3/desktop/hostpython3/Include    -DPy_BUILD_CORE -o Programs/python.o /home/vas/Downloads/MOB(HWR)/.buildozer/android/platform/build-armeabi-v7a/build/other_builds/hostpython3/desktop/hostpython3/Programs/python.c
gcc -pthread -c -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall    -std=c99 -Wextra -Wno-unused-result -Wno-unused-parameter -Wno-missing-field-initializers -Werror=implicit-function-declaration  -I/home/vas/Downloads/MOB(HWR)/.buildozer/android/platform/build-armeabi-v7a/build/other_builds/hostpython3/desktop/hostpython3/Include/internal -IObjects -IInclude -IPython -I. -I/home/vas/Downloads/MOB(HWR)/.buildozer/android/platform/build-armeabi-v7a/build/other_builds/hostpython3/desktop/hostpython3/Include    -DPy_BUILD_CORE -o Parser/acceler.o /home/vas/Downloads/MOB(HWR)/.buildozer/android/platform/build-armeabi-v7a/build/other_builds/hostpython3/desktop/hostpython3/Parser/acceler.c
/bin/sh: 1: Syntax error: "(" unexpected
Makefile:772: recipe for target 'Programs/python.o' failed
make: *** [Programs/python.o] Error 2
make: *** Waiting for unfinished jobs....
/bin/sh: 1: Syntax error: "(" unexpected
Makefile:1708: recipe for target 'Parser/acceler.o' failed
make: *** [Parser/acceler.o] Error 2
make: Leaving directory '/home/vas/Downloads/MOB(HWR)/.buildozer/android/platform/build-armeabi-v7a/build/other_builds/hostpython3/desktop/hostpython3/native-build'

  STDERR:

# Command failed: /usr/bin/python3 -m pythonforandroid.toolchain create --dist_name=HRW --bootstrap=sdl2 --requirements=python3,kivy,kivymd --arch armeabi-v7a --copy-libs --color=always --storage-dir="/home/vas/Downloads/MOB(HWR)/.buildozer/android/platform/build-armeabi-v7a" --ndk-api=21 --ignore-setup-py
# ENVIRONMENT:
#     CLUTTER_IM_MODULE = 'xim'
#     LS_COLORS = 'rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=00:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.Z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.zst=01;31:*.tzst=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.wim=01;31:*.swm=01;31:*.dwm=01;31:*.esd=01;31:*.jpg=01;35:*.jpeg=01;35:*.mjpg=01;35:*.mjpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=00;36:*.au=00;36:*.flac=00;36:*.m4a=00;36:*.mid=00;36:*.midi=00;36:*.mka=00;36:*.mp3=00;36:*.mpc=00;36:*.ogg=00;36:*.ra=00;36:*.wav=00;36:*.oga=00;36:*.opus=00;36:*.spx=00;36:*.xspf=00;36:'
#     LC_MEASUREMENT = 'vi_VN'
#     LESSCLOSE = '/usr/bin/lesspipe %s %s'
#     LC_PAPER = 'vi_VN'
#     LC_MONETARY = 'vi_VN'
#     XDG_MENU_PREFIX = 'gnome-'
#     LANG = 'en_US.UTF-8'
#     DISPLAY = ':1'
#     GNOME_SHELL_SESSION_MODE = 'ubuntu'
#     GTK2_MODULES = 'overlay-scrollbar'
#     COLORTERM = 'truecolor'
#     USERNAME = 'vas'
#     XDG_VTNR = '2'
#     SSH_AUTH_SOCK = '/run/user/1000/keyring/ssh'
#     MANDATORY_PATH = '/usr/share/gconf/ubuntu.mandatory.path'
#     LC_NAME = 'vi_VN'
#     XDG_SESSION_ID = '3'
#     USER = 'vas'
#     DESKTOP_SESSION = 'ubuntu'
#     QT4_IM_MODULE = 'xim'
#     TEXTDOMAINDIR = '/usr/share/locale/'
#     GNOME_TERMINAL_SCREEN = '/org/gnome/Terminal/screen/51d9389e_6141_4bbe_9120_92d428ec6d71'
#     DEFAULTS_PATH = '/usr/share/gconf/ubuntu.default.path'
#     QT_QPA_PLATFORMTHEME = 'appmenu-qt5'
#     PWD = '/home/vas/Downloads/MOB(HWR)'
#     HOME = '/home/vas'
#     TEXTDOMAIN = 'im-config'
#     SSH_AGENT_PID = '1512'
#     QT_ACCESSIBILITY = '1'
#     XDG_SESSION_TYPE = 'x11'
#     XDG_DATA_DIRS = '/usr/share/ubuntu:/usr/local/share/:/usr/share/:/var/lib/snapd/desktop'
#     XDG_SESSION_DESKTOP = 'ubuntu'
#     LC_ADDRESS = 'vi_VN'
#     GJS_DEBUG_OUTPUT = 'stderr'
#     LC_NUMERIC = 'vi_VN'
#     GTK_MODULES = 'gail:atk-bridge'
#     WINDOWPATH = '2'
#     TERM = 'xterm-256color'
#     VTE_VERSION = '5202'
#     SHELL = '/bin/bash'
#     QT_IM_MODULE = 'ibus'
#     XMODIFIERS = '@im=ibus'
#     IM_CONFIG_PHASE = '2'
#     XDG_CURRENT_DESKTOP = 'ubuntu:GNOME'
#     GPG_AGENT_INFO = '/run/user/1000/gnupg/S.gpg-agent:0:1'
#     GNOME_TERMINAL_SERVICE = ':1.117'
#     SHLVL = '1'
#     XDG_SEAT = 'seat0'
#     LC_TELEPHONE = 'vi_VN'
#     GDMSESSION = 'ubuntu'
#     GNOME_DESKTOP_SESSION_ID = 'this-is-deprecated'
#     LOGNAME = 'vas'
#     DBUS_SESSION_BUS_ADDRESS = 'unix:path=/run/user/1000/bus'
#     XDG_RUNTIME_DIR = '/run/user/1000'
#     XAUTHORITY = '/run/user/1000/gdm/Xauthority'
#     XDG_CONFIG_DIRS = '/etc/xdg/xdg-ubuntu:/etc/xdg'
#     PATH = '/home/vas/.buildozer/android/platform/apache-ant-1.9.4/bin:/home/vas/bin:/home/vas/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin'
#     LC_IDENTIFICATION = 'vi_VN'
#     GJS_DEBUG_TOPICS = 'JS ERROR;JS LOG'
#     SESSION_MANAGER = 'local/vas:@/tmp/.ICE-unix/1408,unix/vas:/tmp/.ICE-unix/1408'
#     LESSOPEN = '| /usr/bin/lesspipe %s'
#     GTK_IM_MODULE = 'ibus'
#     LC_TIME = 'vi_VN'
#     OLDPWD = '/home/vas/Downloads'
#     _ = '/usr/local/bin/buildozer'
#     PACKAGES_PATH = '/home/vas/.buildozer/android/packages'
#     ANDROIDSDK = '/home/vas/.buildozer/android/platform/android-sdk'
#     ANDROIDNDK = '/home/vas/.buildozer/android/platform/android-ndk-r19c'
#     ANDROIDAPI = '27'
#     ANDROIDMINAPI = '21'
# 
# Buildozer failed to execute the last command
# The error might be hidden in the log above this error
# Please read the full log, and search for it before
# raising an issue with buildozer itself.
# In case of a bug report, please add a full log with log_level = 2

Thanks for your help!

**Comment by RobertFlatt** [comment]
> PWD = '/home/vas/Downloads/MOB(HWR)'

> /bin/sh: 1: Syntax error: "(" unexpected

**Comment by Julian-O** [comment]
This appears to be a support issue that has been answered.

We try to use GitHub Issues only to track work for developers to do to fix bugs and add new features to Buildozer.

This issue is being closed, because it doesn't describe a bug in Buildozer.

If you have further support questions, please don't post them here. Instead, there is a mailing list and a Discord channel to support Kivy users debugging their own systems, which should be able to help. They are linked in the [ReadMe](https://github.com/kivy/buildozer#support). For building Android apps, there is an unofficial [Buildozer Users' Guide](https://github.com/Android-for-Python/Android-for-Python-Users) that has a lot of useful debugging tips.
