### ISSUE TITLE
I am new to python and buildozer, using buildozer to compile my first android app,

### ISSUE THREAD

**Issue by tusharyadav** [kivy/buildozer#124]
I am new to python and buildozer, using buildozer to compile my first android app using python 3.4 and buildozer version 0.16, so on compiling it is showing -)
I check configration tokens
Unknown command/target android.

**Comment by JulianVolodia** [comment]
python-for-android still not work on Windows? :)

http://stackoverflow.com/questions/24382262/unable-to-compile-a-python-script-using-buildozer

**Comment by inclement** [comment]
Yes, python-for-android still does not work on Windows.

**Comment by ihavenonickname** [comment]
I created the app from [this tutorial](https://kivy.org/docs/tutorials/pong.html). It works fine on desktop. The following command:

    python main.py

opens a new window and the game runs.

Unfortunately, when I try to run it on my Android device:

    buildozer android debug deploy run

I see a slightly different output from the one described by OP:

    # Check configuration tokens
    Buildozer is running as root!
    This is not recommended, and may lead to problems later.
    Are you sure you want to continue [y/n]? y
    Unknown command/target android_old

(note the `_old`)

I used [this tutorial](https://kivy.org/docs/guide/packaging-android.html) to set up Buildolzer.

I am working on Windows 10 with CPython 3.6.

**Comment by inclement** [comment]
@ihavenonickname Post the full log and description of the problem on the kivy-users mailing list

**Comment by abulojoshua1** [comment]
I've failed to build an apk using buildozer.. i get an issue saying something like "failed to execute last command...", i searched the Internet and tried all solutions people provided but all in vain. am using ubuntu 16.04. having cython 0.27.3, Buildozer 0.34 and kivy 1.10.0... 
any help please!

**Comment by AnkitMArtin** [comment]
I am getting this error while running the command 


C:\Users\ankit\Desktop\test>buildozer android debug
Traceback (most recent call last):
  File "C:\Program Files\Python36\Scripts\buildozer-script.py", line 11, in <module>
    load_entry_point('buildozer', 'console_scripts', 'buildozer')()
  File "c:\users\ankit\buildozer\buildozer\scripts\client.py", line 13, in main
    Buildozer().run_command(sys.argv[1:])
  File "c:\users\ankit\buildozer\buildozer\__init__.py", line 122, in __init__
    self.config.read(filename)
  File "c:\program files\python36\lib\configparser.py", line 696, in read
    self._read(fp, filename)
  File "c:\program files\python36\lib\configparser.py", line 1077, in _read
    raise MissingSectionHeaderError(fpname, lineno, line)
configparser.MissingSectionHeaderError: File contains no section headers.
file: 'buildozer.spec', line: 1
'ï»¿[app]\n'

**Comment by inclement** [comment]
@AnkitMArtin buildozer does not work on windows.

**Comment by Spidy20** [comment]
If you are using windows, it will not work there, try to use Google Colab for it.

**Comment by RotonEvan** [comment]
> 
> 
> If you are using windows, it will not work there, try to use Google Colab for it.

Can you please elaborate a bit more on how would I build by app on Google Colab?

Thanks in advance ! :)

**Comment by Spidy20** [comment]
Hello, please create your kivy app on a local machine, then go to colab upload it, follow the same procedure as mentioned in the documentation of buildozer. Colab uses Linux so you can use bulldozer there, recently I made one calc app using colab.

**Comment by SnehaGupta0123** [comment]
I made my app with google colab and the apk is also created but when I open in phone the app opens and closes its just not working for me....
Any suggestions please.

**Comment by MariyaSha** [comment]
If anyone is struggling with using Buildozer on Windows, I've filmed a step by step tutorial about it a while back (using WSL):
https://youtu.be/VsTaM057rdc

@SnehaGupta0123 your app is probably crushing because of discrepancies in the buildozer.spec requirements section. 

- Make sure you specify the versions of the libraries you're using, for example: 
 `requirements = python3, kivy==2.0.0, kivymd==0.104.1`
- If you include images inside your application - you also need to require "pillow" (even if you don't import it inside your Python file) so then:
 `requirements = python3, kivy==2.0.0, kivymd==0.104.1, pillow`

This solved the crashing issues for me and I hope it helps you too! good luck! :)
