### ISSUE TITLE
Pafy lib

### ISSUE THREAD

**Issue by dovahkinnn** [kivy/buildozer#1241]
Im using pafy library in kivy and im start buildozer app build but not working this error show
AttributeError: 'LogFile' object has no attribute 'encoding'

**Comment by RobertFlatt** [comment]
Unable to replicate, as shown below.

I suggest looking further up in the logfile for some earlier and related message. If that does not help you then post the full log file as a text file attached to a question in the Users group (not here). https://groups.google.com/g/kivy-users 

Note, this is not a forum for usage issues.

> Listing '/home/bobf/ex/hello/.buildozer/android/platform/build-armeabi-v7a/build/python-installs/myapp/pafy'...
> Compiling '/home/bobf/ex/hello/.buildozer/android/platform/build-armeabi-v7a/build/python-installs/myapp/pafy/__init__.py'...
> Compiling '/home/bobf/ex/hello/.buildozer/android/platform/build-armeabi-v7a/build/python-installs/myapp/pafy/backend_internal.py'...
> Compiling '/home/bobf/ex/hello/.buildozer/android/platform/build-armeabi-v7a/build/python-installs/myapp/pafy/backend_shared.py'...
> Compiling '/home/bobf/ex/hello/.buildozer/android/platform/build-armeabi-v7a/build/python-installs/myapp/pafy/backend_youtube_dl.py'...
> Compiling '/home/bobf/ex/hello/.buildozer/android/platform/build-armeabi-v7a/build/python-installs/myapp/pafy/channel.py'...
> Compiling '/home/bobf/ex/hello/.buildozer/android/platform/build-armeabi-v7a/build/python-installs/myapp/pafy/g.py'...
> Compiling '/home/bobf/ex/hello/.buildozer/android/platform/build-armeabi-v7a/build/python-installs/myapp/pafy/jsinterp.py'...
> Compiling '/home/bobf/ex/hello/.buildozer/android/platform/build-armeabi-v7a/build/python-installs/myapp/pafy/pafy.py'...
> Compiling '/home/bobf/ex/hello/.buildozer/android/platform/build-armeabi-v7a/build/python-installs/myapp/pafy/playlist.py'...
> Compiling '/home/bobf/ex/hello/.buildozer/android/platform/build-armeabi-v7a/build/python-installs/myapp/pafy/util.py'...
> Listing '/home/bobf/ex/hello/.buildozer/android/platform/build-armeabi-v7a/build/python-installs/myapp/pafy-0.5.5.dist-info'...

**Comment by kengoon** [comment]
downgrade your pafy verision to 0.5.1
