### ISSUE TITLE
Buildozer on Windows

### ISSUE THREAD

**Issue by ntaraujo** [kivy/buildozer#1254]
Hi everyone! Its not a question, you can close this if want

I had difficulties trying to install buildozer on Windows some time ago: there was nothing so good to download and just compile the code, a lot of VM's including the official was not working. Some worked but was too large and was eating so many memory... Its not the end of the world find how to install manually on WSL, but as a noob I wish it had been easier

So, I published a tool to have buildozer commands working on cmd or PowerShell easily, just download the installer and next next

It also run workarounds automatically for adb to work properly

For those interested: [Kivy Easier](https://github.com/ntaraujo/kivy-easier)

Thanks a lot for this project

**Comment by jhay06** [comment]
i have the same issue , but created different approach , I modify buildozer (init.py and android.py) to work with windows platform

add JDK on registry 
change unzip command to jar command for unzipping .zip files 
and hola , this is the result waiting for the final result will get back to this thread if i confirm this works

![image](https://user-images.githubusercontent.com/5191437/108142089-099aa300-7100-11eb-9e57-0207c147a036.png)

**Comment by Julian-O** [comment]
There is no request for action here. Closing as won't fix.

**Comment by Julian-O** [comment]
There is no call for action here. Closing as Won't Fix, because there is nothing required.
