### ISSUE TITLE
Receive modules list for requirements line in buildozer.spec

### ISSUE THREAD

**Issue by xx113355** [kivy/buildozer#1255]
Hello! I start my kivy application on Ubuntu without problems. But when I deploy it on Android it falls with messages "ModuleNotFoundError: No module named". I must add modules from error messages one by one, this takes a long time. Maybe I can receive list of all needed modules by some command?

**Comment by RobertFlatt** [comment]
ModuleNotFoundError: 
This is an error from Python. It is a fatal Python error, it must be fixed in order to proceed.

The module list is what you previously told pip3 in order to run the app on Linux. 
Just remember this ;)

**Comment by xx113355** [comment]
> ModuleNotFoundError:
> This is an error from Python. It is a fatal Python error, it must be fixed in order to proceed.
> 
> The module list is what you previously told pip3 in order to run the app on Linux.
> Just remember this ;)

Yes. But then I run it on my Ubuntu, it work without problem. Problem exists on Android. I must set module list for Android. If I take all modules from pip3 freeze, buildozer takes a very long time for compiling.

**Comment by RobertFlatt** [comment]
Perhaps I was not clear. Do not add all the modules installed with pip3. Just the modules used by the app. The point is that we already know these because we added them with pip3 (though we may have chosen not to remember them). So the trial and error we dislike is not necessary.

**Comment by Julian-O** [comment]
This is not a Kivy issue, but a Python developer not keeping track of their dependencies.

Closing as Won't Fix.
