### ISSUE TITLE
Don't work "requirements.source" option in buildozer.spec

### ISSUE THREAD

**Issue by xx113355** [kivy/buildozer#1256]
I want to use local exchangelib module (i change some code inside this). In compile process I see info about using local module. But then I check .py files inside /home/andrey/PycharmProjects/pythonProject/.buildozer/android/platform/build-armeabi-v7a/build/python-installs/myapp/exchangelib, I see that files inside buildozer folder is not from my local module. Why? Some another options needed?

# (list) Application requirements
# comma separated e.g. requirements = sqlite3,kivy
requirements = python3,kivy,exchangelib,kivymd,cached-property,requests,urllib3,chardet,idna,oauthlib,requests-oauthlib,backports.zoneinfo,tzlocal,pytz,lxml,defusedxml,isodate,pygments,tzdata,requests-ntlm,cryptography,ntlm-auth,dnspython, setuptools

# (str) Custom source folders for requirements
# Sets custom source for any requirements with recipes
# requirements.source.kivy = ../../kivy
requirements.source.exchangelib = /home/andrey/.local/lib/python3.8/site-packages/exchangelib

**Comment by Silvesterrr** [comment]
I wanted to ask if you found solution to this problem?

**Comment by miniparth24** [comment]
This is still an issue for me, anyone found anything to fix this?
