### ISSUE TITLE
Requirement source from custome directory doesn't work 

### ISSUE THREAD

**Issue by aliyilddd** [kivy/buildozer#1259]
As seen in the following buildozer configuration, I want to use custom directory for plyer. Because I need to modify it. However, the modified code is not added to apk as I expected. I even tried after cleaning everything. But the result is the same. 

Python:  3.8.5
Kivy: 2.0.0rc4
Buildozer: 1.2.0
```
requirements = python3,kivy==2.0.0rc4,flask,pyjnius,plyer,setuptools
requirements.source.plyer = /home/ali/MathLight/venv/lib/plyer-master
```

**Comment by Julian-O** [comment]
Is this the same as #1256 ?
