### ISSUE TITLE
buildozer android debug failed in every attempts

### ISSUE THREAD

**Issue by dpatchupdate** [kivy/buildozer#1264]
`name = input("Please enter your name\n")
print("Welcome Mr/Mrs "+name)

age = int(input("Please enter your age\n"))

if age<13:
    print("You are too Young")
elif age<21:
    print("You are in Teen-Aged")

elif age< 30:
    print("You are Matured Now")

elif age<50:
    print("please Take care of yourself")

else:
    print("You are old")`

and i got error

\# Check configuration tokens
\# Ensure build layout
\# Check configuration tokens
\# Preparing build
\# Check requirements for android
\# Run 'dpkg --version'
\# Cwd None
Debian 'dpkg' package management program version 1.19.7 (amd64).
This is free software; see the GNU General Public License version 2 or
later for copying conditions. There is NO warranty.
\# Search for Git (git)
\#  -> found at /usr/bin/git
\# Search for Cython (cython)
\#  -> found at /home/rj/.local/bin/cython
\# Search for Java compiler (javac)
\#  -> found at /usr/lib/jvm/java-8-openjdk-amd64/bin/javac
\# Search for Java keytool (keytool)
\#  -> found at /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/keytool
\# Install platform
\# Run 'git config --get remote.origin.url'
\# Cwd /home/rj/PycharmProjects/Snake Game/.buildozer/android/platform/python-for-android
https://github.com/kivy/python-for-android.git
\# Run 'git branch -vv'
\# Cwd /home/rj/PycharmProjects/Snake Game/.buildozer/android/platform/python-for-android
* master 5a94d074 [origin/master] Merge pull request #2244 from Chronolife-team/native_services_upstream
\# Run '/usr/bin/python3 -m pip install -q --user \'appdirs\' \'colorama>=0.3.3\' \'jinja2\' \'six\' \'enum34; python_version<"3.4"\' \'sh>=1.10; sys_platform!="nt"\' \'pep517<0.7.0"\' \'toml\''
\# Cwd None
\# Apache ANT found at /home/rj/.buildozer/android/platform/apache-ant-1.9.4
\# Android SDK found at /home/rj/.buildozer/android/platform/android-sdk
\# Recommended android's NDK version by p4a is: 19c
\# Android NDK found at /home/rj/.buildozer/android/platform/android-ndk-r19c
\# Check application requirements
\# Check garden requirements
\# Compile platform
\# Run '/usr/bin/python3 -m pythonforandroid.toolchain create --dist_name=myapp --bootstrap=sdl2 --requirements=python3,kivy --arch armeabi-v7a --copy-libs --color=always --storage-dir="/home/rj/PycharmProjects/Snake Game/.buildozer/android/platform/build-armeabi-v7a" --ndk-api=21'
\# Cwd /home/rj/PycharmProjects/Snake Game/.buildozer/android/platform/python-for-android
/home/rj/PycharmProjects/Snake Game/.buildozer/android/platform/python-for-android/pythonforandroid/toolchain.py:84: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import imp
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/rj/PycharmProjects/Snake Game/.buildozer/android/platform/python-for-android/pythonforandroid/toolchain.py", line 1260, in <module>
    main()
  File "/home/rj/PycharmProjects/Snake Game/.buildozer/android/platform/python-for-android/pythonforandroid/entrypoints.py", line 18, in main
    ToolchainCL()
  File "/home/rj/PycharmProjects/Snake Game/.buildozer/android/platform/python-for-android/pythonforandroid/toolchain.py", line 694, in __init__
    self.ctx.setup_dirs(self.storage_dir)
  File "/home/rj/PycharmProjects/Snake Game/.buildozer/android/platform/python-for-android/pythonforandroid/build.py", line 173, in setup_dirs
    raise ValueError('storage dir path cannot contain spaces, please '
ValueError: storage dir path cannot contain spaces, please specify a path with --storage-dir
\# Command failed: /usr/bin/python3 -m pythonforandroid.toolchain create --dist_name=myapp --bootstrap=sdl2 --requirements=python3,kivy --arch armeabi-v7a --copy-libs --color=always --storage-dir="/home/rj/PycharmProjects/Snake Game/.buildozer/android/platform/build-armeabi-v7a" --ndk-api=21
\# ENVIRONMENT:
\#     SHELL = '/bin/bash'
\#     SESSION_MANAGER = 'local/rj-VirtualBox:@/tmp/.ICE-unix/1618,unix/rj-VirtualBox:/tmp/.ICE-unix/1618'
\#     QT_ACCESSIBILITY = '1'
\#     SNAP_REVISION = '222'
\#     XDG_CONFIG_DIRS = '/etc/xdg/xdg-ubuntu:/etc/xdg'
\#     XDG_MENU_PREFIX = 'gnome-'
\#     GNOME_DESKTOP_SESSION_ID = 'this-is-deprecated'
\#     SNAP_REAL_HOME = '/home/rj'
\#     TERMINAL_EMULATOR = 'JetBrains-JediTerm'
\#     SNAP_USER_COMMON = '/home/rj/snap/pycharm-community/common'
\#     LC_ADDRESS = 'bho_NP'
\#     GNOME_SHELL_SESSION_MODE = 'ubuntu'
\#     LC_NAME = 'bho_NP'
\#     SSH_AUTH_SOCK = '/run/user/1000/keyring/ssh'
\#     SNAP_INSTANCE_KEY = ''
\#     XMODIFIERS = '@im=ibus'
\#     DESKTOP_SESSION = 'ubuntu'
\#     LC_MONETARY = 'bho_NP'
\#     SSH_AGENT_PID = '1562'
\#     BAMF_DESKTOP_FILE_HINT = '/var/lib/snapd/desktop/applications/pycharm-community_pycharm-community.desktop'
\#     GTK_MODULES = 'gail:atk-bridge'
\#     PWD = '/home/rj/PycharmProjects/Snake Game'
\#     LOGNAME = 'rj'
\#     XDG_SESSION_DESKTOP = 'ubuntu'
\#     XDG_SESSION_TYPE = 'x11'
\#     GPG_AGENT_INFO = '/run/user/1000/gnupg/S.gpg-agent:0:1'
\#     XAUTHORITY = '/run/user/1000/gdm/Xauthority'
\#     DESKTOP_STARTUP_ID = 'gnome-shell/PyCharm Community Edition/1632-0-rj-VirtualBox_TIME124787'
\#     SNAP_CONTEXT = '66KUxd1z_xYhOGrZ3uuT-ikYJbe8vxFcIMXD-d5lOfP3nS6TaKsJ'
\#     GJS_DEBUG_TOPICS = 'JS ERROR;JS LOG'
\#     WINDOWPATH = '2'
\#     HOME = '/home/rj'
\#     USERNAME = 'rj'
\#     IM_CONFIG_PHASE = '1'
\#     LANG = 'en_US.UTF-8'
\#     LC_PAPER = 'bho_NP'
\#     LS_COLORS = 'rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=00:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.zst=01;31:*.tzst=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.wim=01;31:*.swm=01;31:*.dwm=01;31:*.esd=01;31:*.jpg=01;35:*.jpeg=01;35:*.mjpg=01;35:*.mjpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=00;36:*.au=00;36:*.flac=00;36:*.m4a=00;36:*.mid=00;36:*.midi=00;36:*.mka=00;36:*.mp3=00;36:*.mpc=00;36:*.ogg=00;36:*.ra=00;36:*.wav=00;36:*.oga=00;36:*.opus=00;36:*.spx=00;36:*.xspf=00;36:'
\#     XDG_CURRENT_DESKTOP = 'ubuntu:GNOME'
\#     SNAP_ARCH = 'amd64'
\#     SNAP_INSTANCE_NAME = 'pycharm-community'
\#     SNAP_USER_DATA = '/home/rj/snap/pycharm-community/222'
\#     INVOCATION_ID = '7f9d4a2d60854650810bcb31d9dd919a'
\#     MANAGERPID = '1350'
\#     SNAP_REEXEC = ''
\#     GJS_DEBUG_OUTPUT = 'stderr'
\#     LESSCLOSE = '/usr/bin/lesspipe %s %s'
\#     XDG_SESSION_CLASS = 'user'
\#     TERM = 'xterm-256color'
\#     LC_IDENTIFICATION = 'bho_NP'
\#     LESSOPEN = '| /usr/bin/lesspipe %s'
\#     USER = 'rj'
\#     SNAP = '/snap/pycharm-community/222'
\#     SNAP_COMMON = '/var/snap/pycharm-community/common'
\#     SNAP_VERSION = '2020.3'
\#     DISPLAY = ':0'
\#     SHLVL = '1'
\#     SNAP_LIBRARY_PATH = '/var/lib/snapd/lib/gl:/var/lib/snapd/lib/gl32:/var/lib/snapd/void'
\#     SNAP_COOKIE = '66KUxd1z_xYhOGrZ3uuT-ikYJbe8vxFcIMXD-d5lOfP3nS6TaKsJ'
\#     LC_TELEPHONE = 'bho_NP'
\#     QT_IM_MODULE = 'ibus'
\#     LC_MEASUREMENT = 'bho_NP'
\#     SNAP_DATA = '/var/snap/pycharm-community/222'
\#     XDG_RUNTIME_DIR = '/run/user/1000'
\#     LC_TIME = 'bho_NP'
\#     SNAP_NAME = 'pycharm-community'
\#     JOURNAL_STREAM = '9:32607'
\#     XDG_DATA_DIRS = '/usr/share/ubuntu:/usr/local/share/:/usr/share/:/var/lib/snapd/desktop'
\#     PATH = '/home/rj/.buildozer/android/platform/apache-ant-1.9.4/bin:/home/rj/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin'
\#     GDMSESSION = 'ubuntu'
\#     DBUS_SESSION_BUS_ADDRESS = 'unix:path=/run/user/1000/bus'
\#     GIO_LAUNCHED_DESKTOP_FILE_PID = '2116'
\#     GIO_LAUNCHED_DESKTOP_FILE = '/var/lib/snapd/desktop/applications/pycharm-community_pycharm-community.desktop'
\#     LC_NUMERIC = 'bho_NP'
\#     OLDPWD = '/snap/pycharm-community/222/bin'
\#     _ = '/home/rj/.local/bin/buildozer'
\#     PACKAGES_PATH = '/home/rj/.buildozer/android/packages'
\#     ANDROIDSDK = '/home/rj/.buildozer/android/platform/android-sdk'
\#     ANDROIDNDK = '/home/rj/.buildozer/android/platform/android-ndk-r19c'
\#     ANDROIDAPI = '27'
\#     ANDROIDMINAPI = '21'
\# 
\# Buildozer failed to execute the last command
\# The error might be hidden in the log above this error
\# Please read the full log, and search for it before
\# raising an issue with buildozer itself.
\# In case of a bug report, please add a full log with log_level = 2

**Comment by dpatchupdate** [comment]
if any body help me, it will so much helpful for me

**Comment by Ayush-Kushwaha** [comment]
Did you resolved?Facing almost same problem.....

**Comment by dpatchupdate** [comment]
Not yet.... 😥😥

**Comment by RobertFlatt** [comment]
`ValueError: storage dir path cannot contain spaces, please specify a path with --storage-dir`

In future address usage questions to the user group https://groups.google.com/g/kivy-users

Please close this thread.

**Comment by dpatchupdate** [comment]
thanks
