### ISSUE TITLE
cv2.so has unexpected e_machine: 62 (EM_X86_64)

### ISSUE THREAD

**Issue by joshuapaul2005** [kivy/buildozer#1276]
Hi, I created a camera app for android using opencv and kivy, but I get an error. Please help me.

`Reproduce`
``
The issue comes when building the app for the arch `arm64-v8a`.

`main.py`
    
from kivy.app import App
from kivy.uix.widget import Widget
import cv2
import numpy as np
import imutils

class Camera(Widget):
	cap= cv2.VideoCapture(0)
	cap.set(3,640)
	cap.set(4,480)
	while True:

		_,frame= cap.read()
		hsv = cv2.cvtColor(frame, cv2.COLOR_BGR2HSV)

		# RED 
		lower_red = np.array([0,50,120])
		upper_red = np.array([10,255,255])

		mask = cv2.inRange(hsv,lower_red,upper_red)

		cnts1 = cv2.findContours(mask, cv2.RETR_TREE, cv2.CHAIN_APPROX_SIMPLE)
		cnts1 = imutils.grab_contours(cnts1)

		for c in cnts1:
			area1 = cv2.contourArea(c)
			if area1 > 5000:
				cv2.drawContours(frame,[c],-1,(0,255,0), 3)
				M = cv2.moments(c)
				cx = int(M["m10"]/ M["m00"])
				cy = int(M["m01"]/ M["m00"])
				cv2.circle(frame,(cx,cy),7,(255,255,255),-1)
				cv2.putText(frame,"Red",(cx-20,cy-20),cv2.FONT_HERSHEY_SIMPLEX,2.5,(255,255,255),3)
		cv2.imshow("result",frame)
	
		

		k = cv2.waitKey(5)
		if k == 27:
			break			

	cap.release()
	cv2.destroyAllWindows()

class CamApp(App):
	def build(self):
		return Camera()

CamApp().run()

The error when ran `adb logcat | grep python`

`01-10 14:24:21.349 20205 20233 I python  : [INFO   ] [Logger      ] Record log in /data/user/0/org.test.myapp/files/app/.kivy/logs/kivy_21-01-10_2.txt
01-10 14:24:21.349 20205 20233 I python  : [INFO   ] [Kivy        ] v1.11.1
01-10 14:24:21.350 20205 20233 I python  : [INFO   ] [Kivy        ] Installed at "/data/user/0/org.test.myapp/files/app/_python_bundle/site-packages/kivy/__init__.pyc"
01-10 14:24:21.351 20205 20233 I python  : [INFO   ] [Python      ] v3.8.1 (default, Jan 10 2021, 14:04:00) 
01-10 14:24:21.351 20205 20233 I python  : [Clang 8.0.2 (https://android.googlesource.com/toolchain/clang 40173bab62ec7462
01-10 14:24:21.352 20205 20233 I python  : [INFO   ] [Python      ] Interpreter at ""
01-10 14:24:24.322 20205 20233 I python  : [INFO   ] [Factory     ] 184 symbols loaded
01-10 14:24:25.517 20205 20233 I python  : [INFO   ] [Image       ] Providers: img_tex, img_dds, img_sdl2, img_gif (img_pil, img_ffpyplayer ignored)
01-10 14:24:25.647 20205 20233 I python  :  Traceback (most recent call last):
01-10 14:24:25.648 20205 20233 I python  :    File "/home/joshuapaul/Desktop/app/.buildozer/android/app/main.py", line 3, in <module>
01-10 14:24:25.649 20205 20233 I python  :    File "/home/joshuapaul/Desktop/app/.buildozer/android/platform/build-arm64-v8a/build/python-installs/myapp/cv2/__init__.py", line 5, in <module>
01-10 14:24:25.651 20205 20233 I python  :  ImportError: dlopen failed: "/data/data/org.test.myapp/files/app/_python_bundle/site-packages/cv2/cv2.so" has unexpected e_machine: 62 (EM_X86_64)
01-10 14:24:25.651 20205 20233 I python  : Python for android ended.`

Please help Thank you.

**Comment by will702** [comment]
are there any solutions yet ?

**Comment by medyousef** [comment]
Having exactly the same problem, any solution ?
