### ISSUE TITLE
Buildozer.spec add numpy to requirements 

### ISSUE THREAD

**Issue by mezahirecebov** [kivy/buildozer#1282]
* Python:3.7.1
* OS:mac,ubuntu(I try both of them)
* Buildozer:1.2.0
[buildozer.txt](https://github.com/kivy/buildozer/files/5887448/buildozer.txt)

I am trying to run python code which used numpy ,opencv,gdal library; but when i add this library to buildozer.spec file in requirements it give error in run deploy android ;without it i didn't get error ;;;

***And additionally can you answer me -is it possible run "opencv" and "gdal" libraries in kivy buildozer and create apk for android ;

buildozer android debug deploy run logcat
[log_error.txt](https://github.com/kivy/buildozer/files/5887576/log_error.txt)

**Comment by misl6** [comment]
The issue has been fixed in the recently released `python-for-android` and `buildozer` versions, feel free to re-open the issue if it persists on your side.
