### ISSUE TITLE
AttributeError: 'LogFile' object has no attribute 'encoding' while executing sys.stdout.encoding

### ISSUE THREAD

**Issue by kengoon** [kivy/buildozer#1287]
each time I execute `sys.stdout.encoding` i will get this `AttributeError: 'LogFile' object has no attribute 'encoding` and application crashes

**Comment by Julian-O** [comment]
Your code is assuming that `sys.stdout` will always return an object that supports the `encoding attribute`. This is not a safe assumption. (`sys.stdout` can be None, for example.)

The code is working as intended. Closing as Won't Fix.
