### ISSUE TITLE
missing requirement: python for android on linux docs.

### ISSUE THREAD

**Issue by podraco** [kivy/buildozer#1291]
### Versions

* Python: 3.8
* OS: ubuntu
* Buildozer:  lastest - stable

### Description

The package under pip python-for-android is missing in the command line that installs the dependencies. After 30+ minutes downloading everything the terminal states that python-for-android command failed. But nothing more.
This is caused because python-for-android it's not included in the pip installation bash line.

File affected: https://github.com/kivy/buildozer/blob/master/docs/source/installation.rst

It should be like this:
```
pip3 install --user --upgrade Cython==0.29.19 virtualenv python-for-android  # the `--user` parameter should be removed if you do this in a virtual environment.
```
instead of :
```
pip3 install --user --upgrade Cython==0.29.19 virtualenv  # the --user should be removed if you do this in a venv
```

**Comment by tshirtman** [comment]
Buildozer normaly clones python-for-android itself (as the options in buildozer.spec allows you to set which source/branch to use),, you can use a local clone, but that's not the default configuration.

I'm not sure why (or if) installing python-for-android manually helped, but it shouldn't.

**Comment by podraco** [comment]
I'm not sure why. But I believe it was a problem on my end. Restarted my PC and got some logs of missing files and entries of the file system....
