### ISSUE TITLE
"/root/.buildozer/android/platform/android-sdk/tools/bin/sdkmanager" does not exist, sdkmanager is notinstalled

### ISSUE THREAD

**Issue by nian0** [kivy/buildozer#1293]
非常糟糕，很难解决啊
`"/root/.buildozer/android/platform/android-sdk/tools/bin/sdkmanager" does not exist, sdkmanager is notinstalled`

**Comment by levin2** [comment]
Under dir ~/android-sdk, there is a .zip package. Unzip it, and 'tools/bin/sdkmanager' will appear.
