### ISSUE TITLE
Implementing Android Adaptive Icons

### ISSUE THREAD

**Issue by cshumaker0** [kivy/buildozer#1294]
### Versions

* Python: 3.8.5
* OS: Ubuntu 20.04.1
* Buildozer: 1.2.0.dev0

### Description

As of API 26 and above, Android supports adaptive launcher icons, [as such](https://developer.android.com/guide/practices/ui_guidelines/icon_design_adaptive).

Here is how to implement adaptive icons in your Kivy application and export it using buildozer.

**1.**  Generate Background and Foreground images (.png/.xml, as prescribed in link above). Background must cover the entire image (no transparency). Foreground can have transparency, as 72dp on all 4 corners will be cut off. Leave default name `ic_launcher`.

**2.**  Open a New Project in Android Studio
  - Select `app` folder
  - Click _File --> New --> Image Asset_
  - Upload the Background and Foreground generated. Adjust as needed, and follow buttons to create it proper icon

**3.**  Copy contents of the `res` folder in Android Studio (minus `values` and `values-night`) to `~[app_name]/.buildozer/android/platform/python-for-android/pythonforandroid/bootstraps/sdl2/build/src/main/res`. Click and drag, "merge" folder contents if prompted. 

**4.**  In `~[app_name]/.buildozer/android/platform/python-for-android/pythonforandroid/bootstraps/sdl2/build/templates/AndroidManifest.tmpl.xml` 
  - **Line 59:** `android:icon="@drawable/icon"`  TO
    ```
    android:icon="@mipmap/ic_launcher"
    android:roundIcon="@mipmap/ic_launcher_round"
    ```

  - **Line 100 (now 101):** `android:icon="@drawable/icon"`  TO (same as above)
    ```
    android:icon="@mipmap/ic_launcher"
    android:roundIcon="@mipmap/ic_launcher_round"
    ```

**5.**  Remove `icon.filename` from `buildozer.spec`

**Comment by cshumaker0** [comment]
Copying images to `res` folder.
![image-20210217105208304](https://user-images.githubusercontent.com/77459303/108266049-758c0400-711e-11eb-853b-33a9ebc82593.png)

**Comment by tshirtman** [comment]
Thanks for the contribution, but an issue is not a proper place to document a procedure for future users.
If you think something should be done in buildozer or p4a to make this easier, i think the issue should reflect that.
If you simply want to document this procedure, i suggest creating a wiki page for it.

**Comment by cshumaker0** [comment]
That's a great idea! How do I create a wiki page for it?

**Comment by tshirtman** [comment]
https://github.com/kivy/kivy/wiki you should be able to create a page here.

**Comment by StudioPetrikas** [comment]
Doesn't seem to be working any more. Defaults to the default Kivy icon.
