### ISSUE TITLE
建议

### ISSUE THREAD

**Issue by nian0** [kivy/buildozer#1295]
因为有些时候不能下载python3.8.1,NDK等等，推荐在buildozer库里的__init__.py和/root/.buildozer/android/platform/python-for-android/pythonforandroid/toolchain.py
都填写上
```
import ssl
ssl._create_default_https_context=ssl._create_unverified_context
```

**Comment by tshirtman** [comment]
I understand that's a tip for some situation, it might be related to your internet connection, and in particular, the fact that you are connecting from china, but i'm not sure the situation can be considered a bug on in buildozer/p4a, and i would be against making p4a use unverified contexts by default, so i'm closing this for now, if you can describe more precisely the problem, and suggest a better solution for it, we can certainly reopen it.
