### ISSUE TITLE
How to add to requirements buildozer.spec: pip install https://github.com/kivymd/KivyMD/archive/3274d62.zip

### ISSUE THREAD

**Issue by shpaginoleg7755** [kivy/buildozer#1296]
### Versions

* Python: 3.8
* OS: Ubuntu 20.10
* Buildozer: latest

### Description

Hello!
My app working well on linux/windows
I used those commands to make it work OK: pip install kivy kivymd + pip install https://github.com/kivymd/KivyMD/archive/3274d62.zip

I need to add this command to buildozer.spec to compile it to Android apk file:
pip install https://github.com/kivymd/KivyMD/archive/3274d62.zip

How can I accomplish with it?

**Comment by Shiv-Patil** [comment]
`requirements = python3, kivy==2.0.0, https://github.com/kivymd/KivyMD/archive/3274d62.zip`
Better to ask such questions on the kivy discord server as this is not a bug.

**Comment by shpaginoleg7755** [comment]
Thanks a lot!!!!
