### ISSUE TITLE
OSError: Label: File 'Gilroy-light.otf.ttf' not found

### ISSUE THREAD

**Issue by Priyanshu-Kumar1** [kivy/buildozer#1297]
### Versions

* Python:3.9
* OS: android 9
* Buildozer: 1.2.0

### Description
My font file is **Gilroy-light.otf** but idk why **.ttf** is added at the end of error.
How can I solve it??

### script
```
MDLabel:
				text: "Today"
				font_name: 'Gilroy-light.otf'
				font_size: '23dp'
				pos_hint: {'center_x' : .9, 'center_y' : .8}
```
### buildozer.spec

```
source.include_exts = py,png,jpg,kv,atlas,otf
```

### Logs

```
OSError: Label: File 'Gilroy-light.otf.ttf' not found
```

**Comment by RobertFlatt** [comment]
Ask this one at KivyMD, it does not appear to be Buildozer related.

First check the KivyMD docs for an example using Label font_name in this way.

**Comment by androdev5557** [comment]
> Ask this one at KivyMD, it does not appear to be Buildozer related.
> 
> First check the KivyMD docs for an example using Label font_name in this way.

Its running fine as script this error log is after compiling apk

**Comment by RobertFlatt** [comment]
Check that the KivyMD versions are the same on both platforms. 
Upgrade any that are <dev> because we know that we don't know what is in them.
