### ISSUE TITLE
Feature request - better package management interfaze

### ISSUE THREAD

**Issue by podraco** [kivy/buildozer#1298]
Allow to arbitrary update for included libs
this is a simple idea, allow the developer to request an environment update for a specific library, something like:
`bulldozer android upgrade # to cast an update for every lib`
`bulldozer android upgrade lib1# to cast an update for lib1`

This would save time for people who's working with a specialized or private dependencies that need to be updated to fix an issue on the final app that it's not caused by the app's implementation, instead of having to download everything again.

**Comment by tshirtman** [comment]
I agree this would be nice, the feature must first be built in p4a before it can be exposed in buildozer though.

**Comment by podraco** [comment]
then, let me copy this feature request to p4a repo :9

**Comment by Julian-O** [comment]
This is being closed, but not forgotten. It has been consolidated into issue #1727.
