### ISSUE TITLE
Has anyone succeeded in converting apk on M1?

### ISSUE THREAD

**Issue by jbc0708** [kivy/buildozer#1331]
### Versions

* Python: 3.8.6 (anaconda3 venv)
* OS: Big Sur
* Buildozer: 1.2.0.dev

### Description
I succeded converting apk from ubuntu 20.04
but failed to converting apk from BigSur(M1)
just simple question..
Has anyone succeeded in converting apk or ipa on M1?

// REPLACE ME: What are you trying to get done, what has happened, what went wrong, and what did you expect?

### buildozer.spec
Command:
```sh
// REPLACE ME: buildozer command ran? e.g. buildozer android debug
```

Spec file:
```
// REPLACE ME: Paste your buildozer.spec file here
```

### Logs

```
// REPLACE ME: Paste the build ouput containing the error
```

**Comment by misl6** [comment]
Hi @jbc0708 !

Yesterday we released a new version for `python-for-android` which supports building Android apps on Apple Silicon macs.
Same applies for `kivy-ios` :)
