### ISSUE TITLE
hello ive been getting the same error but for me its module not found urllib3 i added it to my spec file but it gave me an error any help pls

### ISSUE THREAD

**Issue by woohoufeng** [kivy/buildozer#1342]
hello ive been getting the same error but for me its module not found urllib3 i added it to my spec file but it gave me an error any help pls

_Originally posted by @Abadjula in https://github.com/kivy/buildozer/issues/1204#issuecomment-884936677_

**Comment by Kulothungan16** [comment]
try deleting the .buildozer dir where u early runned the buildozer command and retry the build process

**Comment by woohoufeng** [comment]
@Kulothungan16 How do I delete it and where do I find the buildozer dir. Thanks btw I have been stuck for days.
