### ISSUE TITLE
Cannot compile `iri2uri.py` in `httplib2`

### ISSUE THREAD

**Issue by ljxangus** [kivy/buildozer#135]
Hi, while I am compiling a kivy project containing `httplib2` using buildozer, it will skip making `iri2uri.pyo`, which will lead to the module missing. Is there any way to solve it ?
##

**Comment by tarzzz** [comment]
In my application, I have `google-python-api` as the dependency, which has `httlib2` as its dependency. So everytime app is compiled, it downloads the buggy httlib2, and the app crashes. Is there any resolution for the same as well?

**Comment by akshayaurora** [comment]
Pure Python modules can simply be included inside a lib folder inside your
app,  just do `pip install google-python-api -t MyApp/libs` if you are
having trouble with bulldozer.

**Comment by akshayaurora** [comment]
I don;t think it would be feasible to patch every pure python that has a issue,  we should maybe look at fixing things upstream with these libs.
