### ISSUE TITLE
Android perm RECORD_AUDIO seem to be missing

### ISSUE THREAD

**Issue by Krozark** [kivy/buildozer#1350]
### Versions

* Python: 3.7.3
* OS: Android
* Buildozer: develop

### Description

permission RECORD_AUDIO   don't seem to be used in .spec file. I need to add `request_permissions([Permission.RECORD_AUDIO])` to my code.

### buildozer.spec
Command:
```sh
buildozer android debug run logcat
```

Spec file:
```
requirements = python3,kivy,pyjnius,pyler
android.permissions = INTERNET,RECORD_AUDIO
p4a.branch = develop

# other vars are default
```

**Comment by tshirtman** [comment]
These are two different things, adding the permission in the spec file declare that you use it, but as it's a "dangerous" permission, you still need to ask it at runtime, as you do, so this is not a bug.
https://developer.android.com/reference/android/Manifest.permission#RECORD_AUDIO
