### ISSUE TITLE
AAB

### ISSUE THREAD

**Issue by ruard85** [kivy/buildozer#1353]
Hey all, 
"From August 2021, new apps are required to publish with the Android App Bundle on Google Play." Buildozer doesn't support this. Does anyone know when buildozer will be able to make an .aab file? Or how I should do it?
Greetings, ruard

**Comment by RobertFlatt** [comment]
The current status and an unsupported hack are documented here https://github.com/Android-for-Python/Android-for-Python-Users#how-to-create-a-release-bundle-aab . The 'work in progress' link is probably what you want to watch.

**Comment by kengoon** [comment]
@RobertFlatt you and @misl6 have done a very great job on the p4a library. It would be perfect if the `bulldozer.spec` will be updated with the necessary option for compiling with aab

**Comment by RobertFlatt** [comment]
@kengoon Thanks for the acknowledgement, @misl6 did the heavy lifting on aab and deserves the credit. I just tested and documented a little.

**Comment by kengoon** [comment]
> @kengoon Thanks for the acknowledgement, @misl6 did the heavy lifting on aab and deserves the credit. I just tested and documented a little.

Yea, I know that, just commending you on the testing support you gave, it was never an easy task though

**Comment by misl6** [comment]
Closing as this is not anymore an issue as the last release of `buildozer` supports AAB packaging.
