### ISSUE TITLE
Opencv error

### ISSUE THREAD

**Issue by Ankrsi** [kivy/buildozer#1354]
Buildozer not support opencv or cv2

**Comment by RobertFlatt** [comment]
Opencv is available, as shown by:

https://github.com/kivy/python-for-android/tree/develop/pythonforandroid/recipes/opencv
https://github.com/kivy/python-for-android/tree/develop/pythonforandroid/recipes/opencv_extras

Usage issues should be directed to the user groups on Discord or Google Groups.
Usage issues are not address in this forum.
