### ISSUE TITLE
docker buildozer  Aidl not found, please install it.

### ISSUE THREAD

**Issue by oleg-medovikov** [kivy/buildozer#1357]
* Python: 3.9
* OS: clearlinux
* Buildozer:  1.2.0.dev0

### Description

On the first attempt to use it, he asked to install the package.

Apparently it needs to be added to the docker script

### buildozer.spec
default 

### Logs

```
# Aidl not found, please install it.
```

**Comment by RobertFlatt** [comment]
Aidl is part of the Google tools.
To get the tools you have to accept the Google license agreements.

Delete ~/.buildozer  , then `buildozer android debug` again accepting the license agreements if you want to get the tools.

**Comment by afmaster** [comment]
Same problem here trying to compile an apk with flask as webview. I'vew tested in 4 different computers, including google colab and same error occurs. "Aidl not found".

I've tested all the proposed solutions here: https://github.com/kivy/buildozer/issues/413

None of them worked.

I think Buildozer cannot install android sdk and android tools properly.

**Comment by RobertFlatt** [comment]
Assuming the install instructions are followed https://github.com/kivy/buildozer/blob/master/docs/source/installation.rst

The cause of "Aidl not found" is not accepting the Google license agreements. If you don't do this then Google does not allow downloading the tools and the Google tool Aidl is not found. Google's download requires you type Y to accept the license.

**Comment by afmaster** [comment]
That makes totally sense, Mr. RobertFlatt. Thank you. I've read a thread posting this issue, regarding "Y" to accept the license. But, I'm not asked to that agreement during the Buildozer processing. Is there some way to force buildozer to ask for this agreement. Thank you in advance.

**Comment by RobertFlatt** [comment]
If you don't type Y  Buildozer's data base is corrupted. 

https://github.com/Android-for-Python/Android-for-Python-Users#aidl-not-found

Delete ~/.buildozer    

Then you can start again, don't hit the space bar if it seems to pause on the first run, look for the accept question. 

This forum is for development issues, generally usage questions should be addressed to the user groups.
https://groups.google.com/g/kivy-users
https://discord.gg/Sa3e9AY3  (invite expires in 7 days)

**Comment by brunofitas** [comment]
I got this error as well. 
As mentioned above, the cause of "Aidl not found" is not accepting the Google license agreements.
Run the docker container in interactive mode and accept the agreements.

``` docker run -it -v "$(pwd)":/home/user/hostcwd kivy/buildozer ```

**Comment by vasi26ro** [comment]
`docker start -a <container_name> -i` works also.
