### ISSUE TITLE
Feature request: cache package downloads and builds

### ISSUE THREAD

**Issue by xandro0777** [kivy/buildozer#1363]
Whenever starting a new project, buidlozer will download many packages into project local .buidlozer and recompile them.

Could those be cached in ~./buildozer instead?

**Comment by damascene** [comment]
In each update to `buildozer.spec` file it's [suggested](https://github.com/Android-for-Python/Android-for-Python-Users#changing-buildozerspec) to run `buildozer appclean` which would need to re downlowed everything from start. 

I've just measured it it downloads about 550 MB in each run for my app. 

So please consider using caching. I've noticed many issues opened regarding this including:

#801 #1030 and #1336

**Comment by Julian-O** [comment]
This is being closed, but not forgotten. It has been consolidated into issue #1727.
