### ISSUE TITLE
Error while trying to create an APK using Buildozer for Kivy Image processing application. Below is the Error Log. Unable to create APK file

### ISSUE THREAD

**Issue by sbasu26** [kivy/buildozer#1376]
I have tried creating the APK file in both Python 3.8 and Python 3.6.9. I have tried all the Android Arch options mentioned in the buildozer spec file. In spite of that I am repeatedly getting the same below error, due to which I am unable to create the APK file for this Kivy module using Buildozer

Below is the Error Log:

File "/home/sayantani5/Desktop/Project1/KivyArsenalUpdated/.buildozer/android/platform/python-for-android/pythonforandroid/toolchain.py", line 1068, in _build_package
    gradlew = sh.Command('./gradlew')
  File "/home/sayantani5/anaconda3/envs/my_env4/lib/python3.6/site-packages/sh.py", line 1342, in __init__
    raise CommandNotFound(path)
sh.CommandNotFound: ./gradlew
WARNING: Received a --sdk argument, but this argument is deprecated and does nothing.
No setup.py/pyproject.toml used, copying full private data into .apk.
Applying Java source code patches...
Applying patch: src/patches/SDLActivity.java.patch
# Command failed: /home/sayantani5/anaconda3/envs/my_env4/bin/python -m pythonforandroid.toolchain apk --debug --bootstrap=sdl2 --dist_name myapp --name 'My Application' --version 0.1 --package org.test.myapp --minsdk 21 --ndk-api 21 --private /home/sayantani5/Desktop/Project1/KivyArsenalUpdated/.buildozer/android/app --android-entrypoint org.kivy.android.PythonActivity --android-apptheme @android:style/Theme.NoTitleBar --orientation portrait --window --copy-libs --arch armeabi-v7a --color=always --storage-dir="/home/sayantani5/Desktop/Project1/KivyArsenalUpdated/.buildozer/android/platform/build-armeabi-v7a" --ndk-api=21
# ENVIRONMENT:
#     SHELL = '/bin/bash'
#     SESSION_MANAGER = 'local/sayantani5-VirtualBox:@/tmp/.ICE-unix/1011,unix/sayantani5-VirtualBox:/tmp/.ICE-unix/1011'
#     QT_ACCESSIBILITY = '1'
#     COLORTERM = 'truecolor'
#     XDG_CONFIG_DIRS = '/etc/xdg/xdg-ubuntu:/etc/xdg'
#     XDG_MENU_PREFIX = 'gnome-'
#     GNOME_DESKTOP_SESSION_ID = 'this-is-deprecated'
#     CONDA_EXE = '/home/sayantani5/anaconda3/bin/conda'
#     _CE_M = ''
#     LANGUAGE = 'en_IN:en'
#     GNOME_SHELL_SESSION_MODE = 'ubuntu'
#     SSH_AUTH_SOCK = '/run/user/1000/keyring/ssh'
#     XMODIFIERS = '@im=ibus'
#     DESKTOP_SESSION = 'ubuntu'
#     SSH_AGENT_PID = '960'
#     GTK_MODULES = 'gail:atk-bridge'
#     DBUS_STARTER_BUS_TYPE = 'session'
#     PWD = '/home/sayantani5/Desktop/Project1/KivyArsenalUpdated'
#     LOGNAME = 'sayantani5'
#     XDG_SESSION_DESKTOP = 'ubuntu'
#     XDG_SESSION_TYPE = 'x11'
#     CONDA_PREFIX = '/home/sayantani5/anaconda3/envs/my_env4'
#     GPG_AGENT_INFO = '/run/user/1000/gnupg/S.gpg-agent:0:1'
#     XAUTHORITY = '/run/user/1000/gdm/Xauthority'
#     WINDOWPATH = '2'
#     HOME = '/home/sayantani5'
#     USERNAME = 'sayantani5'
#     IM_CONFIG_PHASE = '1'
#     LANG = 'en_IN'
#     LS_COLORS = 'rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=00:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.zst=01;31:*.tzst=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.wim=01;31:*.swm=01;31:*.dwm=01;31:*.esd=01;31:*.jpg=01;35:*.jpeg=01;35:*.mjpg=01;35:*.mjpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=00;36:*.au=00;36:*.flac=00;36:*.m4a=00;36:*.mid=00;36:*.midi=00;36:*.mka=00;36:*.mp3=00;36:*.mpc=00;36:*.ogg=00;36:*.ra=00;36:*.wav=00;36:*.oga=00;36:*.opus=00;36:*.spx=00;36:*.xspf=00;36:'
#     XDG_CURRENT_DESKTOP = 'ubuntu:GNOME'
#     VTE_VERSION = '6003'
#     CONDA_PROMPT_MODIFIER = '(my_env4) '
#     GNOME_TERMINAL_SCREEN = '/org/gnome/Terminal/screen/495dbc34_8a3e_47eb_9b5a_af50cb024c76'
#     INVOCATION_ID = '1a1d78c6744749129f7cabdb085764cf'
#     MANAGERPID = '661'
#     LESSCLOSE = '/usr/bin/lesspipe %s %s'
#     XDG_SESSION_CLASS = 'user'
#     TERM = 'xterm-256color'
#     _CE_CONDA = ''
#     LESSOPEN = '| /usr/bin/lesspipe %s'
#     USER = 'sayantani5'
#     GNOME_TERMINAL_SERVICE = ':1.85'
#     CONDA_SHLVL = '2'
#     DISPLAY = ':0'
#     SHLVL = '1'
#     QT_IM_MODULE = 'ibus'
#     DBUS_STARTER_ADDRESS = 'unix:path=/run/user/1000/bus,guid=6f7bd3967b6e798e325e4b92618e0d93'
#     CONDA_PYTHON_EXE = '/home/sayantani5/anaconda3/bin/python'
#     XDG_RUNTIME_DIR = '/run/user/1000'
#     CONDA_DEFAULT_ENV = 'my_env4'
#     JOURNAL_STREAM = '8:28163'
#     XDG_DATA_DIRS = '/usr/share/ubuntu:/usr/local/share/:/usr/share/:/var/lib/snapd/desktop'
#     PATH = '/home/sayantani5/.buildozer/android/platform/apache-ant-1.9.4/bin:/home/sayantani5/anaconda3/envs/my_env4/bin:/home/sayantani5/anaconda3/condabin:/root/anaconda3/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin'
#     GDMSESSION = 'ubuntu'
#     DBUS_SESSION_BUS_ADDRESS = 'unix:path=/run/user/1000/bus,guid=6f7bd3967b6e798e325e4b92618e0d93'
#     CONDA_PREFIX_1 = '/home/sayantani5/anaconda3'
#     OLDPWD = '/home/sayantani5/Desktop/Project1'
#     _ = '/home/sayantani5/anaconda3/envs/my_env4/bin/buildozer'
#     PACKAGES_PATH = '/home/sayantani5/.buildozer/android/packages'
#     ANDROIDSDK = '/home/sayantani5/.buildozer/android/platform/android-sdk'
#     ANDROIDNDK = '/home/sayantani5/.buildozer/android/platform/android-ndk-r19c'
#     ANDROIDAPI = '27'
#     ANDROIDMINAPI = '21'
# 
# Buildozer failed to execute the last command
# The error might be hidden in the log above this error
# Please read the full log, and search for it before
# raising an issue with buildozer itself.
# In case of a bug report, please add a full log with log_level = 2

**Comment by RobertFlatt** [comment]
There is an example of this issue here https://github.com/codelv/enaml-native-cli/issues/21 which suggests a permissions issue.

It is possible is it caused by running or installing using sudo. 
https://github.com/kivy/buildozer/blob/master/docs/source/installation.rst

This forum is for development issues, please direct any future communication on this issue to the user groups.
https://groups.google.com/g/kivy-users
https://discord.gg/7PjCsVqA

**Comment by QGB** [comment]
buildozer android release

```
[WARNING]: ERROR: /home/user/KivyJniusBluetoothApp/.buildozer/android/platform/build-arm64-v8a/dists/ble/gradlew failed!
['/home/user/KivyJniusBluetoothApp/.buildozer/android/platform/python-for-android/pythonforandroid/toolchain.py', 'apk', '--debug', '--bootstrap=sdl2', '--dist_name', 'ble', '--name', '
BLE_Control', '--version', '0.1', '--package', 'qgb.ble', '--minsdk', '21', '--ndk-api', '21', '--private', '/home/user/KivyJniusBluetoothApp/.buildozer/android/app', '--permission', 'I
NTERNET', '--permission', 'BLUETOOTH_ADMIN', '--permission', 'BLUETOOTH', '--permission', 'CAMERA', '--permission', 'READ_EXTERNAL_STORAGE', '--android-entrypoint', 'org.kivy.android.Py
thonActivity', '--android-apptheme', '@android:style/Theme.NoTitleBar', '--icon', '/home/user/KivyJniusBluetoothApp/./AppIcon.png', '--orientation', 'landscape', '--release', '--copy-li
bs', '--arch', 'arm64-v8a', '--color=always', '--storage-dir=/home/user/KivyJniusBluetoothApp/.buildozer/android/platform/build-arm64-v8a', '--ndk-api=21', '--ignore-setup-py'] ========
==========================================================
WARNING: Received a --sdk argument, but this argument is deprecated and does nothing.
No setup.py/pyproject.toml used, copying full private data into .apk.
Applying Java source code patches...
Applying patch: src/patches/SDLActivity.java.patch
Warning: failed to apply patch (exit code 1), assuming it is already applied:  src/patches/SDLActivity.java.patch
# Command failed: /usr/bin/python3 -m pythonforandroid.toolchain apk --debug --bootstrap=sdl2 --dist_name ble --name BLE_Control --version 0.1 --package qgb.ble --minsdk 21 --ndk-api 21
 --private /home/user/KivyJniusBluetoothApp/.buildozer/android/app --permission INTERNET --permission BLUETOOTH_ADMIN --permission BLUETOOTH --permission CAMERA --permission READ_EXTERN
AL_STORAGE --android-entrypoint org.kivy.android.PythonActivity --android-apptheme @android:style/Theme.NoTitleBar --icon /home/user/KivyJniusBluetoothApp/./AppIcon.png --orientation la
ndscape --release --copy-libs --arch arm64-v8a --color=always --storage-dir="/home/user/KivyJniusBluetoothApp/.buildozer/android/platform/build-arm64-v8a" --ndk-api=21 --ignore-setup-py
```

**Comment by QGB** [comment]
`Error: Google Play requires that apps target API level 30 or higher.`

**Comment by RobertFlatt** [comment]
https://discord.gg/pvUmAFyT
