### ISSUE TITLE
Compile with multiple .py files and requirements.txt

### ISSUE THREAD

**Issue by lasupernova** [kivy/buildozer#1394]
Hi, I have two issues that I can't find information for in the documentation.

The first one is: I have a main.py and corresponding .kv file. Additionally, I have multiple .py files that are imported by main.py (helper functions, that are imported to main.py via `from xyz import abc`. How can I include these files when compiling?

My second issue is regarding the dependencies and virtual environments. I have been running my app from a virtualenv, on which I pip installed all necessary dependencies (saved in requirements.txt). How can I include the virtualenv or the requirements.txt file in when  I compile?

Thanks in advance for your time and help :)

**Comment by RobertFlatt** [comment]
1) Leave them where they are.
2) https://github.com/Android-for-Python/Android-for-Python-Users#requirements

This forum is for development issues
Please address usage questions to the user groups
https://discord.gg/UQfFmgjQ
https://groups.google.com/g/kivy-users

**Comment by WojtekMs** [comment]
I would like to ask a complementary question about the first issue. What if those multiple .py files that are imported by main.py are kept inside a sub-directory? Could you please provide some insight how to include these files when compiling to android APK using buildozer?

**Comment by RobertFlatt** [comment]
Leave them where they are.
