### ISSUE TITLE
Feature: Make buildozer expose app resources folder.

### ISSUE THREAD

**Issue by DexerBR** [kivy/buildozer#1397]
### Is your feature request related to a problem? Please describe.

Currently, buildozer does not simplify adding resources to applications. Actually , if we want to add custom resources, we will have to manually access the resources folder available at:
```
.buildozer\android\platform\build-armeabi-v7a\dists\myapp__armeabi-v7a\src\main\res
```
And then add/change the files.

But still, there is another problem: When building/rebuilding some recipe, updating the ndk, in short, changing something in p4a that needs building/rebuilding, will result in the loss of these files, which requires much more caution to avoid complications while building applications.

An overview of the app resources:
https://developer.android.com/guide/topics/resources/providing-resources?hl=en

### Describe the solution you'd like
Based on most android projects, I would like to propose a new file structure, where the resource folder would be exposed to the buildozer user, as follows:
```
├── app_project
  ├── .buildozer
  ├── bin
  └── res
      ├── drawable
      ├── layout
      ├── values
      ...
   main.py
   ui.kv
```
That folder would be "permanent", just like bin. And if it was deleted, it would be generated again by p4a.
All changes made to them would be sent to the folder I mentioned above, as with the splashscreen images and the application icon.
By doing so, the files would be protected from "accidental deletion", and even if it were necessary to rebuild something on the p4a side, they would not be affected.

Basic flow, after the first run of buildozer:
1 - The `.buildozer`, `bin` and `res` folders would be created
2 - The res folder would have all the source files from the folder: `.buildozer\android\platform\build-armeabi-v7a\dists\myapp__armeabi-v7a\src\main\res`
3 - After user changes, new files would be uploaded/changed/deleted from source folder
4 - Even if the files in the source folder were deleted in some p4a build process, a scan would be made to match the files present in the source folder, and the `res` folder "available" to the user

The main intent of this issue is to discuss the best approaches to implement...
I hope I can do a PR with the addition of this feature!

**Comment by RobertFlatt** [comment]
The general approach in buildozer is "add_*"
```
#android.add_jars = 
#android.add_src =
#android.add_aars =
#android.add_assets =
#android.add_compile_options =
#android.add_gradle_repositories =
#android.add_packaging_options =
#android.add_activities = 
#android.add_libs_armeabi = 
#android.add_libs_armeabi_v7a = 
#android.add_libs_arm64_v8a = 
#android.add_libs_x86 = 
#android.add_libs_mips = 
```
See also https://github.com/kivy/buildozer/pull/1230
