### ISSUE TITLE
Приложение вылетает при запуске

### ISSUE THREAD

**Issue by 4a4ik9314** [kivy/buildozer#1399]
на пк работает нормально не вылетает, при сборке в buildozer ошибок не выдает, при запуске на android после загрузки логотипа kivy вылетает. в программе использую библиотеку gspread, openpyxl. 
после просмотра logcat подлючил google и прописал в buildozer.cpec толку нет
прошу помощи
[logcat.txt](https://github.com/kivy/buildozer/files/7940491/logcat.txt)
[buildozer.txt](https://github.com/kivy/buildozer/files/7940526/buildozer.txt)

**Comment by RobertFlatt** [comment]
In general https://github.com/Android-for-Python/Android-for-Python-Users#requirements

For specific questions https://discord.gg/QpVwqEtf

This forum is for development issues.
