### ISSUE TITLE
Buildozer setup.py fails with Module ImportError

### ISSUE THREAD

**Issue by prometx** [kivy/buildozer#140]
Hi,

trying to setup Buildozer like so:

"# latest dev
git clone git://github.com/kivy/buildozer
cd buildozer
sudo python2.7 setup.py install"

On install attempt Python reports:

"Traceback (most recent call last):
  File "setup.py", line 5, in <module>
    from setuptools import setup
ImportError: No module named setuptools"

This is on Ubuntu 14.04, 64bit

Is this module not "packaged" with Buildozer? Please let me know what you think when you have a moment.

Thanks!

**Comment by iiDatKat** [comment]
@prometx How did you solve it? I removed `setuptools` and installed it again via `wget https://bootstrap.pypa.io/ez_setup.py -O - | sudo python`. It still gives the same error!

**Comment by iiDatKat** [comment]
@inclement I followed those exact instructions on the link that you put. I can confirm setuptools is there (I did `sudo easy_install --help` and it worked), but buildozer is still giving the same error.

**Comment by iiDatKat** [comment]
@inclement Edit: If I go to the Python shell and type `from setuptools import setup` it's successful! Now I'm confused why setuptools is fine on Python but not Buildozer.

**Comment by inclement** [comment]
@iiDatKat Your problem is unrelated to this old issue. Please open a new issue with the full details and log of the failed build.

**Comment by iiDatKat** [comment]
@inclement Yep, understood. I see you're helping me on StackOverflow (@MingleLi), so I'll just do it on there.
