### ISSUE TITLE
Buildozer or p4a keeps rebuilding sdl2 every time

### ISSUE THREAD

**Issue by RazyRabbit** [kivy/buildozer#1406]
### Versions

* Python: Python 3.8.10
* OS: Ubuntu (WSL)
* Buildozer: Buildozer 1.2.0

### Description

Buildozer or p4a keeps rebuilding sdl2 every time

### buildozer.spec
Command:
```sh
buildozer android debug deploy run logcat
```

Spec file:
Default Spec File

### Logs

![image](https://user-images.githubusercontent.com/43307018/155827332-16bbf74c-b269-4ce9-9606-bc373f9da7d3.png)

**Comment by kuzeyron** [comment]
I would try setting this in `buildozer.spec`:
```python
# (str) python-for-android branch to use, defaults to master
p4a.branch = develop
```
And see if that solves it. I assume you have the same branch set for P4a.
Logs in text-format is more appreciated so we can read from the start -> end.

**Comment by RazyRabbit** [comment]
Already solved with develop branch!
Thanks!
