### ISSUE TITLE
FYI - Ubuntu 14.04 Necessary Java Path Adjustment

### ISSUE THREAD

**Issue by prometx** [kivy/buildozer#141]
Hi,

Had problems with Buildozer finding javac for my Ubuntu 14.04 install. I found that an additional package needs to be installed to add "javac", as per the below:

http://askubuntu.com/questions/471412/eclipse-and-java-7-but-no-javac

thought this might be useful to someone
##

**Comment by namchester** [comment]
When you install Java on your machine. "javac" comes invluded. :)
