### ISSUE TITLE
buildozer -v android debug error,please help me,thank you!

### ISSUE THREAD

**Issue by chineselzh** [kivy/buildozer#1413]
### Versions

* Python:3.8.10
* OS:Ubuntu20.04
* Buildozer:1.30

### Description

// REPLACE ME: What are you trying to get done, what has happened, what went wrong, and what did you expect?

### Logs

```
# Command failed: /usr/bin/python3 -m pythonforandroid.toolchain create --dist_name=LoongApp --bootstrap=sdl2 --requirements=python3,kivy --arch arm64-v8a --arch armeabi-v7a --copy-libs --color=always --storage-dir="/home/lzh/桌面/aaa/.buildozer/android/platform/build-arm64-v8a_armeabi-v7a" --ndk-api=21 --ignore-setup-py --debug
# ENVIRONMENT:
#     SHELL = '/bin/bash'
#     WINDOWID = '96468999'
#     QT_ACCESSIBILITY = '1'
#     COLORTERM = 'truecolor'
#     XDG_CONFIG_DIRS = '/etc/xdg/xdg-ukui:/etc/xdg'
#     XDG_SESSION_PATH = '/org/freedesktop/DisplayManager/Session1'
#     GTK_IM_MODULE = 'fcitx'
#     LANGUAGE = 'zh_CN:'
#     D_DISABLE_RT_SCREEN_SCALE = '1'
#     QT4_IM_MODULE = 'fcitx'
#     SSH_AUTH_SOCK = '/tmp/ssh-Ga8bqdcHz7fd/agent.129687'
#     XMODIFIERS = '@im=fcitx'
#     DESKTOP_SESSION = 'ukui'
#     SSH_AGENT_PID = '129768'
#     GTK_MODULES = 'gail:atk-bridge'
#     XDG_SEAT = 'seat0'
#     PWD = '/home/lzh/桌面/aaa'
#     LOGNAME = 'lzh'
#     XDG_SESSION_DESKTOP = 'ukui'
#     QT_QPA_PLATFORMTHEME = 'ukui'
#     XDG_SESSION_TYPE = 'x11'
#     GPG_AGENT_INFO = '/run/user/1000/gnupg/S.gpg-agent:0:1'
#     XAUTHORITY = '/home/lzh/.Xauthority'
#     XDG_GREETER_DATA_DIR = '/var/lib/lightdm-data/lzh'
#     GDM_LANG = 'zh_CN'
#     HOME = '/home/lzh'
#     LANG = 'zh_CN.UTF-8'
#     LS_COLORS = 'rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=00:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.zst=01;31:*.tzst=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.wim=01;31:*.swm=01;31:*.dwm=01;31:*.esd=01;31:*.jpg=01;35:*.jpeg=01;35:*.mjpg=01;35:*.mjpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=00;36:*.au=00;36:*.flac=00;36:*.m4a=00;36:*.mid=00;36:*.midi=00;36:*.mka=00;36:*.mp3=00;36:*.mpc=00;36:*.ogg=00;36:*.ra=00;36:*.wav=00;36:*.oga=00;36:*.opus=00;36:*.spx=00;36:*.xspf=00;36:'
#     XDG_CURRENT_DESKTOP = 'UKUI'
#     VTE_VERSION = '6003'
#     ANDROID_ENV = '1'
#     XDG_SEAT_PATH = '/org/freedesktop/DisplayManager/Seat0'
#     CLUTTER_IM_MODULE = 'fcitx'
#     QT_QPA_PLATFORM = 'xcb'
#     LESSCLOSE = '/usr/bin/lesspipe %s %s'
#     XDG_SESSION_CLASS = 'user'
#     TERM = 'xterm-256color'
#     LESSOPEN = '| /usr/bin/lesspipe %s'
#     USER = 'lzh'
#     DISPLAY = ':0'
#     SHLVL = '1'
#     QT_IM_MODULE = 'fcitx'
#     XDG_VTNR = '7'
#     XDG_SESSION_ID = 'c4'
#     QT_SCALE_FACTOR_ROUNDING_POLICY = 'PassThrough'
#     XDG_RUNTIME_DIR = '/run/user/1000'
#     ZIPINFO = '-O GBK'
#     UNZIP = '-O GBK'
#     XDG_DATA_DIRS = '/usr/share/ukui:/usr/local/share:/usr/share:/var/lib/snapd/desktop'
#     PATH = '/home/lzh/.buildozer/android/platform/apache-ant-1.9.4/bin:/home/lzh/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin'
#     GDMSESSION = 'ukui'
#     DBUS_SESSION_BUS_ADDRESS = 'unix:path=/run/user/1000/bus'
#     _ = '/home/lzh/.local/bin/buildozer'
#     PACKAGES_PATH = '/home/lzh/.buildozer/android/packages'
#     ANDROIDSDK = '/home/lzh/.buildozer/android/platform/android-sdk'
#     ANDROIDNDK = '/home/lzh/.buildozer/android/platform/android-ndk-r19c'
#     ANDROIDAPI = '27'
#     ANDROIDMINAPI = '21'
# 
# Buildozer failed to execute the last command
# The error might be hidden in the log above this error
# Please read the full log, and search for it before
# raising an issue with buildozer itself.
# In case of a bug report, please add a full log with log_level = 2

```

**Comment by tereshed** [comment]
have the same issue:
python: 3.7.7
OS: macOs Monteray 12.3
Buildozer:1.4.0.dev0

`checking for the platform triplet based on compiler characteristics... darwin
configure: error: internal configure error for the platform triplet, please file a bug report


  STDERR:

# Command failed: /Users/macbook/kivy/kivy_venv/bin/python -m pythonforandroid.toolchain create --dist_name=myapptemplate --bootstrap=sdl2 --requirements=python3,kivy --arch arm64-v8a --arch armeabi-v7a --copy-libs --color=always --storage-dir="/Users/macbook/kivy/apps/pivy_app_template/.buildozer/android/platform/build-arm64-v8a_armeabi-v7a" --ndk-api=21 --ignore-setup-py --debug
# ENVIRONMENT:
#     USER = 'macbook'
#     __CFBundleIdentifier = 'com.microsoft.VSCode'
#     COMMAND_MODE = 'unix2003'
#     LOGNAME = 'macbook'
#     PATH = '/Users/macbook/.buildozer/android/platform/apache-ant-1.9.4/bin:/Users/macbook/kivy/kivy_venv/bin:/Library/Frameworks/Python.framework/Versions/3.8/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/share/dotnet:~/.dotnet/tools:/Library/Apple/usr/bin:/Users/macbook/opt/anaconda3/bin:/Users/macbook/opt/anaconda3/condabin:/Library/Frameworks/Python.framework/Versions/3.8/bin:/Users/macbook/.cargo/bin:/Users/macbook/development/flutter/bin:/Users/macbook/development/flutter/bin'
#     SSH_AUTH_SOCK = '/private/tmp/com.apple.launchd.cpu5yRSZFH/Listeners'
#     SHELL = '/bin/zsh'
#     HOME = '/Users/macbook'
#     __CF_USER_TEXT_ENCODING = '0x1F5:0x7:0x31'
#     TMPDIR = '/var/folders/x2/8v5r88v14b3bh7m8hlhqjtfh0000gn/T/'
#     XPC_SERVICE_NAME = '0'
#     XPC_FLAGS = '0x0'
#     ORIGINAL_XDG_CURRENT_DESKTOP = 'undefined'
#     SHLVL = '1'
#     PWD = '/Users/macbook/kivy/apps/pivy_app_template'
#     OLDPWD = '/Users/macbook/kivy/apps/pivy_app_template'
#     CONDA_EXE = '/Users/macbook/opt/anaconda3/bin/conda'
#     CONDA_PYTHON_EXE = '/Users/macbook/opt/anaconda3/bin/python'
#     CONDA_SHLVL = '1'
#     CONDA_PREFIX = '/Users/macbook/opt/anaconda3'
#     CONDA_DEFAULT_ENV = 'base'
#     CONDA_PROMPT_MODIFIER = '(base) '
#     TERM_PROGRAM = 'vscode'
#     TERM_PROGRAM_VERSION = '1.65.2'
#     LANG = 'ru_RU.UTF-8'
#     COLORTERM = 'truecolor'
#     VSCODE_GIT_IPC_HANDLE = '/var/folders/x2/8v5r88v14b3bh7m8hlhqjtfh0000gn/T/vscode-git-12f692b420.sock'
#     GIT_ASKPASS = ('/Applications/Visual Studio '
 'Code.app/Contents/Resources/app/extensions/git/dist/askpass.sh')
#     VSCODE_GIT_ASKPASS_NODE = '/Applications/Visual Studio Code.app/Contents/MacOS/Electron'
#     VSCODE_GIT_ASKPASS_EXTRA_ARGS = '--ms-enable-electron-run-as-node'
#     VSCODE_GIT_ASKPASS_MAIN = ('/Applications/Visual Studio '
 'Code.app/Contents/Resources/app/extensions/git/dist/askpass-main.js')
#     TERM = 'xterm-256color'
#     _CE_M = ''
#     _CE_CONDA = ''
#     PS1 = '(kivy_venv) (base) %n@%m %1~ %# '
#     VIRTUAL_ENV = '/Users/macbook/kivy/kivy_venv'`

**Comment by RobertFlatt** [comment]
https://discord.gg/fPkd4Ykv
