### ISSUE TITLE
Not Able to change the python version under buildozer 1.3.0

### ISSUE THREAD

**Issue by jhay06** [kivy/buildozer#1432]
Hi ,
  I have an issue on buildozer 1.3.0 , on 1.2.0 version i can change the version of python to be download when packaging 

but after updating the buildozer 1.3.0 , even i add ==X.X.X version after python3 example python3==3.7.13 the version was disregarded and buildozer download the 3.8.9 version 
![image](https://user-images.githubusercontent.com/5191437/165436918-0cac899a-b764-44cd-a4df-7466bb4e7a04.png)

I am using macos monterey the latest version of Apple clang was not supported the python  3.8.9 , i need to download 3.7.13, 3.8.13 , 3.9.11 or 3.10.13 in able for me to  build python successfully 

below is the setup of the buildozer.spec 
![image](https://user-images.githubusercontent.com/5191437/165437355-6a53663f-a02a-4c1a-9e7d-c4e573e90510.png)

Please help

Thanks

**Comment by misl6** [comment]
Did you deleted your `.buildozer` folder?

**Comment by jhay06** [comment]
Hi this is what i've done but no success

* upgrade buildozer and pip to its latest , retain the .buildozer folder ,  but buildozer downloaded 3.8.9 
* remove the .buildozer folder but still the same .
* remove all .buildozer folder , but still the same 
*  remove buildozer.spec and start from the start , but still the same .
*

**Comment by misl6** [comment]
Uhm, I read it again and seems there's a typo in your requirements.

Is `hostpython3`, not `hostpython`.

**Comment by jhay06** [comment]
> Uhm, I read it again and seems there's a typo in your requirements.
> 
> Is `hostpython3`, not `hostpython`.
got this i did not notice that , thanks . i think it works
