### ISSUE TITLE
hostpython3 download error, ssl error

### ISSUE THREAD

**Issue by SamanthaZH** [kivy/buildozer#1441]
### Versions

* Python: 3.8.9
* OS: 12.3.1
* Buildozer: 1.3.0

### Description

  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/urllib/request.py", line 1357, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)>
Download failed: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)>; retrying in 1 second(s)...Download failed: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)>;

### buildozer.spec
Command:
```sh
// REPLACE ME: buildozer command ran? e.g. buildozer android debug
```

Spec file:
```
// REPLACE ME: Paste your buildozer.spec file here
```

### Logs

```
// REPLACE ME: Paste the build ouput containing the error
```

**Comment by misl6** [comment]
Hi @SamanthaZH,
How did you install the Python version that are you using?

**Comment by onuratakan** [comment]
I think my issue #1477 is have some part for this and i share the installation details.

**Comment by misl6** [comment]
Closing as stale
