### ISSUE TITLE
Solution for AttributeError: 'Buildozer' object has no attribute 'translate_target'

### ISSUE THREAD

**Issue by Shashankh001** [kivy/buildozer#1445]
I spent a lot of time digging stackoverflow and many more sources. and i found the solution
Check if you have installed jdk/javac. to check, run
`javac -version`

if its not found, install it by
`sudo apt-get install openjdk-14-jdk`

Let me know if you still need help

**Comment by Julian-O** [comment]
There is no request for action here. Closing as Won't Fix.
