### ISSUE TITLE
Command failed: /home/username/.buildozer/android/platform/android-sdk/tools/bin/sdkmanager --sdk_root=/home/username/.buildozer/android/platform/android-sdk platform-tools

### ISSUE THREAD

**Issue by Flamzyfreeman** [kivy/buildozer#1449]
Exception in thread "main" java.lang.NoClassDefFoundError: javax/xml/bind/annotation/XmlSchema
        at com.android.repository.api.SchemaModule$SchemaModuleVersion.<init>(SchemaModule.java:156)
        at com.android.repository.api.SchemaModule.<init>(SchemaModule.java:75)
        at com.android.sdklib.repository.AndroidSdkHandler.<clinit>(AndroidSdkHandler.java:81)
        at com.android.sdklib.tool.SdkManagerCli.main(SdkManagerCli.java:117)
        at com.android.sdklib.tool.SdkManagerCli.main(SdkManagerCli.java:93)
Caused by: java.lang.ClassNotFoundException: javax.xml.bind.annotation.XmlSchema
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
        ... 5 more
#Command failed: /home/freeman/.buildozer/android/platform/android-sdk/tools/bin/sdkmanager --sdk_root=/home/freeman/.buildozer/android/platform/android-sdk platform-tools
ENVIRONMENT:
     SHELL = '/bin/bash'
     WSL_DISTRO_NAME = 'Ubuntu'
     NAME = 'Freeman'
     PWD = '/mnt/c/Users/Jesse/Desktop/new_kivy'
     LOGNAME = 'freeman'
     MOTD_SHOWN = 'update-motd'
     HOME = '/home/freeman'
     LANG = 'C.UTF-8'
     LS_COLORS = 'rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=00:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.zst=01;31:*.tzst=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.wim=01;31:*.swm=01;31:*.dwm=01;31:*.esd=01;31:*.jpg=01;35:*.jpeg=01;35:*.mjpg=01;35:*.mjpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=00;36:*.au=00;36:*.flac=00;36:*.m4a=00;36:*.mid=00;36:*.midi=00;36:*.mka=00;36:*.mp3=00;36:*.mpc=00;36:*.ogg=00;36:*.ra=00;36:*.wav=00;36:*.oga=00;36:*.opus=00;36:*.spx=00;36:*.xspf=00;36:'
     LESSCLOSE = '/usr/bin/lesspipe %s %s'
     TERM = 'xterm-256color'
     LESSOPEN = '| /usr/bin/lesspipe %s'
     USER = 'freeman'
     SHLVL = '1'
     WSLENV = ''
     XDG_DATA_DIRS = '/usr/local/share:/usr/share:/var/lib/snapd/desktop'
     PATH = ('/home/freeman/.buildozer/android/platform/apache-ant-1.9.4/bin:/home/freeman/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/mnt/c/Python310/Scripts/:/mnt/c/Python310/:/mnt/c/Program '
 'Files (x86)/Java/jdk-13/bin/bin:/mnt/c/Program Files (x86)/Common '
 'Files/Oracle/Java/javapath:/mnt/c/WINDOWS/system32:/mnt/c/WINDOWS:/mnt/c/WINDOWS/System32/Wbem:/mnt/c/WINDOWS/System32/WindowsPowerShell/v1.0/:/mnt/c/WINDOWS/System32/OpenSSH/:/mnt/c/Program '
 'Files/PowerShell/7/:/mnt/c/Program '
 'Files/nodejs/:/mnt/c/Users/Jesse/AppData/Local/Microsoft/WindowsApps:/mnt/c/Users/Jesse/AppData/Local/Programs/mongosh/:/mnt/c/Users/Jesse/AppData/Local/Programs/Microsoft '
 'VS Code/bin:/mnt/c/Users/Jesse/AppData/Roaming/npm:/snap/bin')
     HOSTTYPE = 'x86_64'
     OLDPWD = '/home/freeman'
     _ = '/home/freeman/.local/bin/buildozer'

Buildozer failed to execute the last command
The error might be hidden in the log above this error
Please read the full log, and search for it before
raising an issue with buildozer itself.
In case of a bug report, please add a full log with log_level = 2

**Comment by damascene** [comment]
Why did you close it, did you solve it, How?
