### ISSUE TITLE
(WSL) buildozer adb doesn't recognize usb

### ISSUE THREAD

**Issue by Oc3anPho3nix** [kivy/buildozer#1453]
Problem the WSL buildozer adb doesn't recognize via USB connected devices, while the windows adb does and both are the same version

wsl adb:
`(venv-buildozer) oceanphoenix@OceanLaptop:~/.buildozer/android/platform/android-sdk/platform-tools$ ./adb devices
List of devices attached
`

Powershell:
`PS C:\andr-plat-tools> .\adb.exe devices \n
List of devices attached
sg4txchenbnjbir4        device
`

wsl adb restart in usb mode is not possible because it doesn't detect any devices
`(venv-buildozer) oceanphoenix@OceanLaptop:~/.buildozer/android/platform/android-sdk/platform-tools$ ./adb usb
error: no devices/emulators found`

**Comment by misl6** [comment]
See: https://devblogs.microsoft.com/commandline/connecting-usb-devices-to-wsl/
