### ISSUE TITLE
error

### ISSUE THREAD

**Issue by py928** [kivy/buildozer#1473]
[DEBUG]:   -> running patch -t -d /content/.buildozer/android/platform/build-arm64-v8a_armeabi-v7a/build/other_builds/openssl/armeabi-v7a__ndk_target_21/openssl1.1 -p1 -i /content/.buildozer/android/platform/python-for-android/pythonforandroid/recipes/openssl/disable-sover.patch
[DEBUG]:   	patching file Makefile
[DEBUG]:   -> running make build_libs
[DEBUG]:   	/usr/bin/perl "-I." -Mconfigdata "util/dofile.pl" \
[DEBUG]:   	    "-oMakefile" include/crypto/bn_conf.h.in > include/crypto/bn_conf.h
[DEBUG]:   	/usr/bin/perl "-I." -Mconfigdata "util/dofile.pl" \
[DEBUG]:   	    "-oMakefile" include/crypto/dso_conf.h.in > include/crypto/dso_conf.h
[DEBUG]:   	/usr/bin/perl "-I." -Mconfigdata "util/dofile.pl" \
[DEBUG]:   	    "-oMakefile" include/openssl/opensslconf.h.in > include/openssl/opensslconf.h
[DEBUG]:   	make depend && make _build_libs
[DEBUG]:   	make[1]: Entering directory '/content/.buildozer/android/platform/build-arm64-v8a_armeabi-v7a/build/other_builds/openssl/armeabi-v7a__ndk_target_21/openssl1.1'
[DEBUG]:   	make[1]: Leaving directory '/content/.buildozer/android/platform/build-arm64-v8a_armeabi-v7a/build/other_builds/openssl/armeabi-v7a__ndk_target_21/openssl1.1'
[DEBUG]:   	make[1]: Entering directory '/content/.buildozer/android/platform/build-arm64-v8a_armeabi-v7a/build/other_builds/openssl/armeabi-v7a__ndk_target_21/openssl1.1'
[DEBUG]:   	armv7a-linux-androideabi21-clang  -I. -Iinclude -fPIC -pthread -target armv7a-linux-androideabi21 -fomit-frame-pointer -march=armv7-a -mfloat-abi=softfp -mfpu=vfp -mthumb -fPIC -DOPENSSL_USE_NODELETE -DOPENSSL_PIC -DOPENSSLDIR="\"/usr/local/ssl\"" -DENGINESDIR="\"/usr/local/lib/engines-1.1\"" -DNDEBUG -D__ANDROID_API__=21 -DANDROID -I/root/.buildozer/android/platform/android-ndk-r23b/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/include -I/content/.buildozer/android/platform/build-arm64-v8a_armeabi-v7a/build/python-installs/myapp/armeabi-v7a/include/python3.9 -MMD -MF crypto/cms/cms_err.d.tmp -MT crypto/cms/cms_err.o -c -o crypto/cms/cms_err.o crypto/cms/cms_err.c
[DEBUG]:   	In file included from <built-in>:370:
[DEBUG]:   	<command line>:6:9: warning: '__ANDROID_API__' macro redefined [-Wmacro-redefined]
[DEBUG]:   	#define __ANDROID_API__ 21
[DEBUG]:   	        ^
[DEBUG]:   	<built-in>:363:9: note: previous definition is here
[DEBUG]:   	#define __ANDROID_API__ __ANDROID_MIN_SDK_VERSION__
[DEBUG]:   	        ^
[DEBUG]:   	1 warning generated.
[DEBUG]:   	armv7a-linux-androideabi21-clang  -I. -Iinclude -fPIC -pthread -target armv7a-linux-androideabi21 -fomit-frame-pointer -march=armv7-a -mfloat-abi=softfp -mfpu=vfp -mthumb -fPIC -DOPENSSL_USE_NODELETE -DOPENSSL_PIC -DOPENSSLDIR="\"/usr/local/ssl\"" -DENGINESDIR="\"/usr/local/lib/engines-1.1\"" -DNDEBUG -D__ANDROID_API__=21 -DANDROID -I/root/.buildozer/android/platform/android-ndk-r23b/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/include -I/content/.buildozer/android/platform/build-arm64-v8a_armeabi-v7a/build/python-installs/myapp/armeabi-v7a/include/python3.9 -MMD -MF crypto/cms/cms_ess.d.tmp -MT crypto/cms/cms_ess.o -c -o crypto/cms/cms_ess.o crypto/cms/cms_ess.c
[DEBUG]:   	In file included from <built-in>:370:
[DEBUG]:   	<command line>:6:9: warning: '__ANDROID_API__' macro redefined [-Wmacro-redefined]
[DEBUG]:   	#define __ANDROID_API__ 21
[DEBUG]:   	        ^
[DEBUG]:   	<built-in>:363:9: note: previous definition is here
[DEBUG]:   	#define __ANDROID_API__ __ANDROID_MIN_SDK_VERSION__
[DEBUG]:   	        ^
[DEBUG]:   	1 warning generated.
[DEBUG]:   	armv7a-linux-androideabi21-clang  -I. -Iinclude -fPIC -pthread -target armv7a-linux-androideabi21 -fomit-frame-pointer -march=armv7-a -mfloat-abi=softfp -mfpu=vfp -mthumb -fPIC -DOPENSSL_USE_NODELETE -DOPENSSL_PIC -DOPENSSLDIR="\"/usr/local/ssl\"" -DENGINESDIR="\"/usr/local/lib/engines-1.1\"" -DNDEBUG -D__ANDROID_API__=21 -DANDROID -I/root/.buildozer/android/platform/android-ndk-r23b/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/include -I/content/.buildozer/android/platform/build-arm64-v8a_armeabi-v7a/build/python-installs/myapp/armeabi-v7a/include/python3.9 -MMD -MF crypto/cms/cms_io.d.tmp -MT crypto/cms/cms_io.o -c -o crypto/cms/cms_io.o crypto/cms/cms_io.c
[DEBUG]:   	In file included from <built-in>:370:
[DEBUG]:   	<command line>:6:9: warning: '__ANDROID_API__' macro redefined [-Wmacro-redefined]
[DEBUG]:   	#define __ANDROID_API__ 21
[DEBUG]:   	        ^
[DEBUG]:   	<built-in>:363:9: note: previous definition is here
[DEBUG]:   	#define __ANDROID_API__ __ANDROID_MIN_SDK_VERSION__
[DEBUG]:   	        ^
[DEBUG]:   	1 warning generated.
[DEBUG]:   	armv7a-linux-androideabi21-clang  -I. -Iinclude -fPIC -pthread -target armv7a-linux-androideabi21 -fomit-frame-pointer -march=armv7-a -mfloat-abi=softfp -mfpu=vfp -mthumb -fPIC -DOPENSSL_USE_NODELETE -DOPENSSL_PIC -DOPENSSLDIR="\"/usr/local/ssl\"" -DENGINESDIR="\"/usr/local/lib/engines-1.1\"" -DNDEBUG -D__ANDROID_API__=21 -DANDROID -I/root/.buildozer/android/platform/android-ndk-r23b/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/include -I/content/.buildozer/android/platform/build-arm64-v8a_armeabi-v7a/build/python-installs/myapp/armeabi-v7a/include/python3.9 -MMD -MF crypto/cms/cms_kari.d.tmp -MT crypto/cms/cms_kari.o -c -o crypto/cms/cms_kari.o crypto/cms/cms_kari.c
[DEBUG]:   	In file included from <built-in>:370:
[DEBUG]:   	<command line>:6:9: warning: '__ANDROID_API__' macro redefined [-Wmacro-redefined]
[DEBUG]:   	#define __ANDROID_API__ 21
[DEBUG]:   	        ^
[DEBUG]:   	<built-in>:363:9: note: previous definition is here
[DEBUG]:   	#define __ANDROID_API__ __ANDROID_MIN_SDK_VERSION__
[DEBUG]:   	        ^
[DEBUG]:   	1 warning generated.
[DEBUG]:   	armv7a-linux-androideabi21-clang  -I. -Iinclude -fPIC -pthread -target armv7a-linux-androideabi21 -fomit-frame-pointer -march=armv7-a -mfloat-abi=softfp -mfpu=vfp -mthumb -fPIC -DOPENSSL_USE_NODELETE -DOPENSSL_PIC -DOPENSSLDIR="\"/usr/local/ssl\"" -DENGINESDIR="\"/usr/local/lib/engines-1.1\"" -DNDEBUG -D__ANDROID_API__=21 -DANDROID -I/root/.buildozer/android/platform/android-ndk-r23b/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/include -I/content/.buildozer/android/platform/build-arm64-v8a_armeabi-v7a/build/python-installs/myapp/armeabi-v7a/include/python3.9 -MMD -MF crypto/cms/cms_lib.d.tmp -MT crypto/cms/cms_lib.o -c -o crypto/cms/cms_lib.o crypto/cms/cms_lib.c
[DEBUG]:   	In file included from <built-in>:370:
[DEBUG]:   	<command line>:6:9: warning: '__ANDROID_API__' macro redefined [-Wmacro-redefined]
[DEBUG]:   	#define __ANDROID_API__ 21
[DEBUG]:   	        ^
[DEBUG]:   	<built-in>:363:9: note: previous definition is here
[DEBUG]:   	#define __ANDROID_API__ __ANDROID_MIN_SDK_VERSION__
[DEBUG]:   	        ^
[DEBUG]:   	1 warning generated.
[DEBUG]:   	armv7a-linux-androideabi21-clang  -I. -Iinclude -fPIC -pthread -target armv7a-linux-androideabi21 -fomit-frame-pointer -march=armv7-a -mfloat-abi=softfp -mfpu=vfp -mthumb -fPIC -DOPENSSL_USE_NODELETE -DOPENSSL_PIC -DOPENSSLDIR="\"/usr/local/ssl\"" -DENGINESDIR="\"/usr/local/lib/engines-1.1\"" -DNDEBUG -D__ANDROID_API__=21 -DANDROID -I/root/.buildozer/android/platform/android-ndk-r23b/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/include -I/content/.buildozer/android/platform/build-arm64-v8a_armeabi-v7a/build/python-installs/myapp/armeabi-v7a/include/python3.9 -MMD -MF crypto/cms/cms_pwri.d.tmp -MT crypto/cms/cms_pwri.o -c -o crypto/cms/cms_pwri.o crypto/cms/cms_pwri.c
[DEBUG]:   	In file included from <built-in>:370:
[DEBUG]:   	<command line>:6:9: warning: '__ANDROID_API__' macro redefined [-Wmacro-redefined]
[DEBUG]:   	#define __ANDROID_API__ 21
[DEBUG]:   	        ^

**Comment by misl6** [comment]
The log you have posted only shows some warnings, can you post the full log or the relevant part of it?
