### ISSUE TITLE
ffmpeg is not supported in latest buildozer update. 

### ISSUE THREAD

**Issue by josefputero** [kivy/buildozer#1474]
I faced an error with ffpyplayer after updating buildozer to 1.4.0 (where is lowest possible NDK version jump from 19b to 23b).
I found out that ffpyplayer doesn't support ndk 23b, so, what should I do? Downgrade the buildozer version is not the case because there will be problems with new sh version.
P.S. I'm on the road now, I can't attach log right now, but maybe you can help me without one?

**Comment by misl6** [comment]
Hi @josefputero , `ffpyplayer` supports `23b`, can you add a log of the error when you have some spare time?

**Comment by josefputero** [comment]
> Hi @josefputero , `ffpyplayer` supports `23b`, can you add a log of the error when you have some spare time?

[INFO]:    -> directory context /home/comp/Desktop/apps/.buildozer/android/platform/build-arm64-v8a_armeabi-v7a/build/other_builds/ffmpeg/arm64-v8a__ndk_target_21/ffmpeg
[DEBUG]:   -> running configure --disable-everything --enable-openssl --enable-nonfree --enable-protocol=https,tls_openssl --enable-gpl --enable-libx264 --enable-libshine --enable-libvpx --enable-parsers --enable-decoders --enable-encoders --enable-muxers --enable-demuxers --disable-symver --disable-programs --disable-doc --enable-filter=aresample,resample,crop,adelay,volume,scale --enable-protocol=file,http,hls --enable-small --enable-hwaccels --enable-pic --disable-static --disable-debug --enable-shared --target-os=android --enable-cross-compile --cross-prefix=aarch64-linux-android21- --arch=aarch64 --strip=/home/comp/.buildozer/android/platform/android-ndk-r23b/toolchains/llvm/prebuilt/linux-x86_64/bin/llvm-strip --sysroot=/home/comp/.buildozer/android/platform/android-ndk-r23b/toolchains/llvm/prebuilt/linux-x86_64/sysroot --enable-neon --prefix=/home/comp/Desktop/apps/.buildozer/android/platform/build-arm64-v8a_armeabi-v7a/build/other_builds/ffmpeg/arm64-v8a__ndk_target_21/ffmpeg
[DEBUG]:   	tput: No value for $TERM and no -T specified
[DEBUG]:   	tput: No value for $TERM and no -T specified
[DEBUG]:   	aarch64-linux-android21-clang is unable to create an executable file.
[DEBUG]:   	C compiler test failed.
[DEBUG]:   	
[DEBUG]:   	If you think configure made a mistake, make sure you are using the latest
[DEBUG]:   	version from Git.  If the latest version fails, report the problem to the
[DEBUG]:   	ffmpeg-user@ffmpeg.org mailing list or IRC #ffmpeg on irc.freenode.net.
[DEBUG]:   	Include the log file "ffbuild/config.log" produced by configure as this will help
[DEBUG]:   	solve the problem.
Exception in thread background thread for pid 7291:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/comp/.local/lib/python3.8/site-packages/sh.py", line 1641, in wrap
    fn(*rgs, **kwargs)
  File "/home/comp/.local/lib/python3.8/site-packages/sh.py", line 2569, in background_thread
    handle_exit_code(exit_code)
  File "/home/comp/.local/lib/python3.8/site-packages/sh.py", line 2269, in fn
    return self.command.handle_command_exit_code(exit_code)
  File "/home/comp/.local/lib/python3.8/site-packages/sh.py", line 869, in handle_command_exit_code
    raise exc
sh.ErrorReturnCode_1: 

  RAN: /home/comp/Desktop/apps/.buildozer/android/platform/build-arm64-v8a_armeabi-v7a/build/other_builds/ffmpeg/arm64-v8a__ndk_target_21/ffmpeg/configure --disable-everything --enable-openssl --enable-nonfree --enable-protocol=https,tls_openssl --enable-gpl --enable-libx264 --enable-libshine --enable-libvpx --enable-parsers --enable-decoders --enable-encoders --enable-muxers --enable-demuxers --disable-symver --disable-programs --disable-doc --enable-filter=aresample,resample,crop,adelay,volume,scale --enable-protocol=file,http,hls --enable-small --enable-hwaccels --enable-pic --disable-static --disable-debug --enable-shared --target-os=android --enable-cross-compile --cross-prefix=aarch64-linux-android21- --arch=aarch64 --strip=/home/comp/.buildozer/android/platform/android-ndk-r23b/toolchains/llvm/prebuilt/linux-x86_64/bin/llvm-strip --sysroot=/home/comp/.buildozer/android/platform/android-ndk-r23b/toolchains/llvm/prebuilt/linux-x86_64/sysroot --enable-neon --prefix=/home/comp/Desktop/apps/.buildozer/android/platform/build-arm64-v8a_armeabi-v7a/build/other_builds/ffmpeg/arm64-v8a__ndk_target_21/ffmpeg

  STDOUT:
tput: No value for $TERM and no -T specified
tput: No value for $TERM and no -T specified
aarch64-linux-android21-clang is unable to create an executable file.
C compiler test failed.

If you think configure made a mistake, make sure you are using the latest
version from Git.  If the latest version fails, report the problem to the
ffmpeg-user@ffmpeg.org mailing list or IRC #ffmpeg on irc.freenode.net.
Include the log file "ffbuild/config.log" produced by configure as this will help
solve the problem.


  STDERR:

Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/comp/Desktop/apps/.buildozer/android/platform/python-for-android/pythonforandroid/toolchain.py", line 1297, in <module>
    main()
  File "/home/comp/Desktop/apps/.buildozer/android/platform/python-for-android/pythonforandroid/entrypoints.py", line 18, in main
    ToolchainCL()
  File "/home/comp/Desktop/apps/.buildozer/android/platform/python-for-android/pythonforandroid/toolchain.py", line 731, in __init__
    getattr(self, command)(args)
  File "/home/comp/Desktop/apps/.buildozer/android/platform/python-for-android/pythonforandroid/toolchain.py", line 154, in wrapper_func
    build_dist_from_args(ctx, dist, args)
  File "/home/comp/Desktop/apps/.buildozer/android/platform/python-for-android/pythonforandroid/toolchain.py", line 213, in build_dist_from_args
    build_recipes(build_order, python_modules, ctx,
  File "/home/comp/Desktop/apps/.buildozer/android/platform/python-for-android/pythonforandroid/build.py", line 505, in build_recipes
    recipe.build_arch(arch)
  File "/home/comp/Desktop/apps/.buildozer/android/platform/python-for-android/pythonforandroid/recipes/ffmpeg/__init__.py", line 143, in build_arch
    shprint(configure, *flags, _env=env)
  File "/home/comp/Desktop/apps/.buildozer/android/platform/python-for-android/pythonforandroid/logger.py", line 167, in shprint
    for line in output:
  File "/home/comp/.local/lib/python3.8/site-packages/sh.py", line 915, in next
    self.wait()
  File "/home/comp/.local/lib/python3.8/site-packages/sh.py", line 845, in wait
    self.handle_command_exit_code(exit_code)
  File "/home/comp/.local/lib/python3.8/site-packages/sh.py", line 869, in handle_command_exit_code
    raise exc
sh.ErrorReturnCode_1: 

  RAN: /home/comp/Desktop/apps/.buildozer/android/platform/build-arm64-v8a_armeabi-v7a/build/other_builds/ffmpeg/arm64-v8a__ndk_target_21/ffmpeg/configure --disable-everything --enable-openssl --enable-nonfree --enable-protocol=https,tls_openssl --enable-gpl --enable-libx264 --enable-libshine --enable-libvpx --enable-parsers --enable-decoders --enable-encoders --enable-muxers --enable-demuxers --disable-symver --disable-programs --disable-doc --enable-filter=aresample,resample,crop,adelay,volume,scale --enable-protocol=file,http,hls --enable-small --enable-hwaccels --enable-pic --disable-static --disable-debug --enable-shared --target-os=android --enable-cross-compile --cross-prefix=aarch64-linux-android21- --arch=aarch64 --strip=/home/comp/.buildozer/android/platform/android-ndk-r23b/toolchains/llvm/prebuilt/linux-x86_64/bin/llvm-strip --sysroot=/home/comp/.buildozer/android/platform/android-ndk-r23b/toolchains/llvm/prebuilt/linux-x86_64/sysroot --enable-neon --prefix=/home/comp/Desktop/apps/.buildozer/android/platform/build-arm64-v8a_armeabi-v7a/build/other_builds/ffmpeg/arm64-v8a__ndk_target_21/ffmpeg

  STDOUT:
tput: No value for $TERM and no -T specified
tput: No value for $TERM and no -T specified
aarch64-linux-android21-clang is unable to create an executable file.
C compiler test failed.

If you think configure made a mistake, make sure you are using the latest
version from Git.  If the latest version fails, report the problem to the
ffmpeg-user@ffmpeg.org mailing list or IRC #ffmpeg on irc.freenode.net.
Include the log file "ffbuild/config.log" produced by configure as this will help
solve the problem.


  STDERR:

# Command failed: /usr/bin/python3 -m pythonforandroid.toolchain create --dist_name=myapp --bootstrap=sdl2 --requirements=python3,kivy,kivymd,pillow,ffpyplayer,ffpyplayer_codecs --arch arm64-v8a --arch armeabi-v7a --copy-libs --color=always --storage-dir="/home/comp/Desktop/apps/.buildozer/android/platform/build-arm64-v8a_armeabi-v7a" --ndk-api=21 --ignore-setup-py --debug
# ENVIRONMENT:
#     SHELL = '/bin/bash'
#     SESSION_MANAGER = 'local/comp-VirtualBox:@/tmp/.ICE-unix/1693,unix/comp-VirtualBox:/tmp/.ICE-unix/1693'
#     QT_ACCESSIBILITY = '1'
#     COLORTERM = 'truecolor'
#     XDG_CONFIG_DIRS = '/etc/xdg/xdg-ubuntu:/etc/xdg'
#     XDG_MENU_PREFIX = 'gnome-'
#     GNOME_DESKTOP_SESSION_ID = 'this-is-deprecated'
#     LC_ADDRESS = 'tr_TR.UTF-8'
#     GNOME_SHELL_SESSION_MODE = 'ubuntu'
#     LC_NAME = 'tr_TR.UTF-8'
#     SSH_AUTH_SOCK = '/run/user/1000/keyring/ssh'
#     XMODIFIERS = '@im=ibus'
#     DESKTOP_SESSION = 'ubuntu'
#     LC_MONETARY = 'tr_TR.UTF-8'
#     SSH_AGENT_PID = '1655'
#     GTK_MODULES = 'gail:atk-bridge'
#     DBUS_STARTER_BUS_TYPE = 'session'
#     PWD = '/home/comp/Desktop/apps'
#     LOGNAME = 'comp'
#     XDG_SESSION_DESKTOP = 'ubuntu'
#     XDG_SESSION_TYPE = 'x11'
#     GPG_AGENT_INFO = '/run/user/1000/gnupg/S.gpg-agent:0:1'
#     XAUTHORITY = '/run/user/1000/gdm/Xauthority'
#     WINDOWPATH = '2'
#     HOME = '/home/comp'
#     USERNAME = 'comp'
#     IM_CONFIG_PHASE = '1'
#     LC_PAPER = 'tr_TR.UTF-8'
#     LANG = 'en_US.UTF-8'
#     LS_COLORS = 'rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=00:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.zst=01;31:*.tzst=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.wim=01;31:*.swm=01;31:*.dwm=01;31:*.esd=01;31:*.jpg=01;35:*.jpeg=01;35:*.mjpg=01;35:*.mjpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=00;36:*.au=00;36:*.flac=00;36:*.m4a=00;36:*.mid=00;36:*.midi=00;36:*.mka=00;36:*.mp3=00;36:*.mpc=00;36:*.ogg=00;36:*.ra=00;36:*.wav=00;36:*.oga=00;36:*.opus=00;36:*.spx=00;36:*.xspf=00;36:'
#     XDG_CURRENT_DESKTOP = 'ubuntu:GNOME'
#     VTE_VERSION = '6003'
#     GNOME_TERMINAL_SCREEN = '/org/gnome/Terminal/screen/3a1be605_2c00_4094_8ae0_c333d58ced94'
#     INVOCATION_ID = '4ead743f2fce4cee9769724cc33d3d8a'
#     MANAGERPID = '1444'
#     LESSCLOSE = '/usr/bin/lesspipe %s %s'
#     XDG_SESSION_CLASS = 'user'
#     TERM = 'xterm-256color'
#     LC_IDENTIFICATION = 'tr_TR.UTF-8'
#     LESSOPEN = '| /usr/bin/lesspipe %s'
#     USER = 'comp'
#     GNOME_TERMINAL_SERVICE = ':1.69'
#     DISPLAY = ':0'
#     SHLVL = '1'
#     LC_TELEPHONE = 'tr_TR.UTF-8'
#     QT_IM_MODULE = 'ibus'
#     LC_MEASUREMENT = 'tr_TR.UTF-8'
#     DBUS_STARTER_ADDRESS = 'unix:path=/run/user/1000/bus,guid=8ba16665f6b894346bbffe8c62e06211'
#     XDG_RUNTIME_DIR = '/run/user/1000'
#     LC_TIME = 'tr_TR.UTF-8'
#     JOURNAL_STREAM = '9:35332'
#     XDG_DATA_DIRS = '/usr/share/ubuntu:/usr/local/share/:/usr/share/:/var/lib/snapd/desktop'
#     PATH = '/home/comp/.buildozer/android/platform/apache-ant-1.9.4/bin:/home/comp/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/home/comp/.local/bin/'
#     GDMSESSION = 'ubuntu'
#     DBUS_SESSION_BUS_ADDRESS = 'unix:path=/run/user/1000/bus,guid=8ba16665f6b894346bbffe8c62e06211'
#     LC_NUMERIC = 'tr_TR.UTF-8'
#     _ = '/home/comp/.local/bin/buildozer'
#     PACKAGES_PATH = '/home/comp/.buildozer/android/packages'
#     ANDROIDSDK = '/home/comp/.buildozer/android/platform/android-sdk'
#     ANDROIDNDK = '/home/comp/.buildozer/android/platform/android-ndk-r23b'
#     ANDROIDAPI = '27'
#     ANDROIDMINAPI = '21'
# 
# Buildozer failed to execute the last command
# The error might be hidden in the log above this error
# Please read the full log, and search for it before
# raising an issue with buildozer itself.
# In case of a bug report, please add a full log with log_level = 2

**Comment by misl6** [comment]
Hi @josefputero ,

There's a high chance that the error that is causing the build to fail is somewhere before that chunk of log, can you please add a full one?

**Comment by josefputero** [comment]
Hello @misl6, I have no more this error, thank you.
P.S. I don't know how to fix it, it fixed itself, without any changes from my side(just waited a few days)
