### ISSUE TITLE
Check for cython before building

### ISSUE THREAD

**Issue by damascene** [kivy/buildozer#1481]
When I run `buildozer android debug` it runs for some time then it stops complaining about unavailble `cython`.
```
ModuleNotFoundError: No module named 'Cython'
```
I suggest to have checks for `cython` before running the build as it will save time for builders not to wait in vain.

**Comment by pcgeek86** [comment]
I ran into the same issue in Ubuntu 22.04 LTS running on WSL2 / Windows 11.

Here's the commands I ran to work around it:

```
# Need to install cython3 and Java compiler (javac)
sudo apt-get install cython3 openjdk-18-headless --yes

# Create symbolic link for cython to cython3, else it won't be found
sudo ln -s $(which cython3) /usr/local/bin/cython
```

**Comment by Julian-O** [comment]
I believe this is now done (via `buildops.checkbin`) for android and ios.

Closing as complete. Let us know if it is still happening.
