### ISSUE TITLE
gradlew failed!

### ISSUE THREAD

**Issue by py928** [kivy/buildozer#1489]
* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org/

Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

See https://docs.gradle.org/7.4.1/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 1m 1s

<=------------> 13% EXECUTING [49s]> IDLE> IDLE2 actionable tasks: 2 executed

<-------------> 0% WAITING> IDLE> IDLE

  STDERR:

WARNING: Received a --sdk argument, but this argument is deprecated and does nothing.
No setup.py/pyproject.toml used, copying full private data into .apk.
Applying Java source code patches...
Applying patch: src/patches/SDLActivity.java.patch

[INFO]:    STDOUT (last 20 lines of 102):
	* Try:	
> Run with --stacktrace option to get the stack trace.	
> Run with --info or --debug option to get more log output.	
> Run with --scan to get full insights.	
	
* Get more help at https://help.gradle.org/	
	
Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.	
	
You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.	
	
See https://docs.gradle.org/7.4.1/userguide/command_line_interface.html#sec:command_line_warnings	
	
BUILD FAILED in 1m 1s	
	
	
	
<=------------> 13% EXECUTING [49s]> IDLE> IDLE2 actionable tasks: 2 executed	
	
<-------------> 0% WAITING> IDLE> IDLE
[INFO]:    STDERR:
	
[INFO]:    ENV:
export LIBRARY_PATH='/usr/local/cuda/lib64/stubs'
export PYTHONWARNINGS='ignore:::pip._internal.cli.base_command'
export NV_CUDA_COMPAT_PACKAGE='cuda-compat-11-1'
export NV_NVPROF_DEV_PACKAGE='cuda-nvprof-11-1=11.1.105-1'
export NV_LIBCUBLAS_VERSION='11.3.0.106-1'
export GCS_READ_CACHE_BLOCK_SIZE_MB='16'
export COLAB_GPU='0'
export DATALAB_SETTINGS_OVERRIDES='{"kernelManagerProxyPort":6000,"kernelManagerProxyHost":"172.28.0.3","jupyterArgs":["--ip=172.28.0.2"],"debugAdapterMultiplexerPath":"/usr/local/bin/dap_multiplexer","enableLsp":true}'
export USE_AUTH_EPHEM='1'
export MPLBACKEND='module://ipykernel.pylab.backend_inline'
export HOSTNAME='37ae3fc456a7'
export LD_LIBRARY_PATH='/usr/local/nvidia/lib:/usr/local/nvidia/lib64'
export NV_LIBNCCL_PACKAGE_VERSION='2.8.4-1'
export SHLVL='1'
export OLDPWD='/'
export HOME='/root'
export NV_LIBCUBLAS_DEV_VERSION='11.3.0.106-1'
export NO_GCE_CHECK='False'
export NV_CUDNN_PACKAGE_NAME='libcudnn8'
export PAGER='cat'
export GCE_METADATA_TIMEOUT='3'
export ANDROIDMINAPI='21'
export ENV='/root/.bashrc'
export NV_LIBNCCL_DEV_PACKAGE_VERSION='2.8.4-1'
export NV_LIBNPP_PACKAGE='libnpp-11-1=11.1.2.301-1'
export CUDA_VERSION='11.1.1'
export NV_CUDNN_PACKAGE='libcudnn8=8.0.5.39-1+cuda11.1'
export NV_NVPROF_VERSION='11.1.105-1'
export NV_LIBCUBLAS_PACKAGE_NAME='libcublas-11-1'
export LAST_FORCED_REBUILD='20220726'
export NVIDIA_REQUIRE_CUDA='cuda>=11.1 brand=tesla,driver>=418,driver<419 brand=tesla,driver>=450,driver<451'
export _='/usr/local/bin/buildozer'
export ANDROIDAPI='33'
export ENABLE_DIRECTORYPREFETCHER='1'
export NV_LIBCUSPARSE_VERSION='11.3.0.10-1'
export NV_CUDA_LIB_VERSION='11.1.1-1'
export NV_LIBNCCL_PACKAGE_NAME='libnccl2'
export NVIDIA_DRIVER_CAPABILITIES='compute,utility'
export NV_LIBNPP_DEV_PACKAGE='libnpp-dev-11-1=11.1.2.301-1'
export TERM='xterm-color'
export NV_NVML_DEV_VERSION='11.1.74-1'
export NV_CUDNN_PACKAGE_DEV='libcudnn8-dev=8.0.5.39-1+cuda11.1'
export NV_CUDA_CUDART_VERSION='11.1.74-1'
export ANDROIDNDK='/root/.buildozer/android/platform/android-ndk-r23b'
export TBE_EPHEM_CREDS_ADDR='172.28.0.1:8009'
export PATH='/root/.buildozer/android/platform/apache-ant-1.9.4/bin:/opt/bin:/usr/local/nvidia/bin:/usr/local/cuda/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/tools/node/bin:/tools/google-cloud-sdk/bin'
export NVARCH='x86_64'
export NV_LIBCUBLAS_PACKAGE='libcublas-11-1=11.3.0.106-1'
export NV_LIBCUBLAS_DEV_PACKAGE_NAME='libcublas-dev-11-1'
export CLOUDSDK_CONFIG='/content/.config'
export GLIBCPP_FORCE_NEW='1'
export NV_LIBCUSPARSE_DEV_VERSION='11.3.0.10-1'
export NV_LIBNCCL_PACKAGE='libnccl2=2.8.4-1+cuda11.1'
export NV_LIBNCCL_DEV_PACKAGE_NAME='libnccl-dev'
export LANG='en_US.UTF-8'
export TF_FORCE_GPU_ALLOW_GROWTH='true'
export LD_PRELOAD='/usr/lib/x86_64-linux-gnu/libtcmalloc.so.4'
export ANDROIDSDK='/root/.buildozer/android/platform/android-sdk'
export NV_CUDA_CUDART_DEV_VERSION='11.1.74-1'
export DEBIAN_FRONTEND='noninteractive'
export TBE_CREDS_ADDR='172.28.0.1:8008'
export CLOUDSDK_PYTHON='python3'
export NV_LIBCUBLAS_DEV_PACKAGE='libcublas-dev-11-1=11.3.0.106-1'
export SHELL='/bin/bash'
export PACKAGES_PATH='/root/.buildozer/android/packages'
export NV_LIBNCCL_DEV_PACKAGE='libnccl-dev=2.8.4-1+cuda11.1'
export NV_LIBNPP_VERSION='11.1.2.301-1'
export NV_NVTX_VERSION='11.1.74-1'
export NV_CUDNN_VERSION='8.0.5.39'
export GIT_PAGER='cat'
export PWD='/content/.buildozer/android/platform/python-for-android'
export CLICOLOR='1'
export JPY_PARENT_PID='45'
export PYDEVD_USE_FRAME_EVAL='NO'
export PYTHONPATH='/env/python'
export NVIDIA_VISIBLE_DEVICES='all'
export NCCL_VERSION='2.8.4-1'
export NV_LIBNPP_DEV_VERSION='11.1.2.301-1'
export GLIBCXX_FORCE_NEW='1'
export ANDROID_NDK_HOME='/root/.buildozer/android/platform/android-ndk-r23b'
export ANDROID_HOME='/root/.buildozer/android/platform/android-sdk'

[INFO]:    COMMAND:
cd /content/.buildozer/android/platform/build-armeabi-v7a_arm64-v8a/dists/filearranger && /content/.buildozer/android/platform/build-armeabi-v7a_arm64-v8a/dists/filearranger/gradlew bundleRelease

[WARNING]: ERROR: /content/.buildozer/android/platform/build-armeabi-v7a_arm64-v8a/dists/app/gradlew failed!
# Command failed: /usr/bin/python3 -m pythonforandroid.toolchain aab --bootstrap sdl2 --dist_name filearranger --name 'file arranger' --version 0.1 --package org.filearranger.filearranger --minsdk 21 --ndk-api 21 --private /content/.buildozer/android/app --permission INTERNET --permission ACCESS_NETWORK_STATE --permission READ_EXTERNAL_STORAGE --permission WRITE_EXTERNAL_STORAGE --android-entrypoint org.kivy.android.PythonActivity --android-apptheme @android:style/Theme.NoTitleBar --presplash /content/./icon.png --icon /content/./icon.png --orientation portrait --window --release --copy-libs --depend 'com.google.android.gms:play-services-ads:20.4.0' --arch armeabi-v7a --arch arm64-v8a --color=always --storage-dir="/content/.buildozer/android/platform/build-armeabi-v7a_arm64-v8a" --ndk-api=21 --ignore-setup-py --debug
# ENVIRONMENT:

**Comment by py928** [comment]
android.api = 31


android.minapi = 21


android.sdk = 20


android.ndk = 23b

**Comment by RobertFlatt** [comment]
Running as root is known to cause issues, Buildozer warns about running at root.

Run in a user account, you will have to delete ~/.buildozer and project/.buildozer because of file permissions due running as root.

also you may want to cleanup /.buildozer and /.gradle

**Comment by zikkuratti** [comment]
also dont use it from ~/ folder this equal root

**Comment by zikkuratti** [comment]
trying on wsl solve problem on native ubuntu 22 pc

**Comment by Ridola20** [comment]
> Running as root is known to cause issues, Buildozer warns about running at root.
> 
> Run in a user account, you will have to delete ~/.buildozer and project/.buildozer because of file permissions due running as root.
> 
> also you may want to cleanup /.buildozer and /.gradle




Gradlew is really wearing me out, pls help??

**Comment by RobertFlatt** [comment]
There is some OS configuration issue there, it is very hard to guess what that might be.
And you have kinda dug a hole for yourself by not following the instructions.

I suggest a restart
- it might even be safer to create a new Ubunti install is WSL (because don't know the state of yours) 
- from a *user* account follow the install instructions
- Build Hello World as described here: (don't make any changes other than the one described here)
   https://github.com/Android-for-Python/Android-for-Python-Users#try-hello-world
   
  This a usage issue, and belongs in the User groups (I'd suggest Discord)

**Comment by RobertFlatt** [comment]
Find the error message, its further up the log, 
see https://github.com/Android-for-Python/Android-for-Python-Users#gradlew-failed
