### ISSUE TITLE
fresh android sdk install requires sdk update

### ISSUE THREAD

**Issue by brentpicasso** [kivy/buildozer#151]
on a fresh install I need to enter the ~/.buildozer android directory and perform:

android update sdk -u

before I'm able to build the APK.

Brilliant script BTW!!
##

**Comment by dessant** [comment]
Is this still the case? If yes, it could be documented.

**Comment by brentpicasso** [comment]
It's been a long time since a fresh install, but I believe the latest buildozer seems to execute the update commands correctly. I'll close for now and if it happens again I will re-open.
