### ISSUE TITLE
C compiler cannot create executables

### ISSUE THREAD

**Issue by med-phisiker** [kivy/buildozer#152]
Hello, I try to compile APK from hello_world kivy aplication.
main.py is
from kivy.app import App
from kivy.uix.button import Button

class TestApp(App):
    def build(self):
        return Button(text='Hello World')

TestApp().run()

My system is Ubuntu 14.04 LTS
I install buildozer, then make buildozer.spec, via command
buildozer init
then run buildozer -v android debug
and then I see this error

"""
Run build
Skipped build_hostpython
Call build_python
Entering in ARM environment
Compiler found at /home/med-phisiker-linux/.buildozer/android/platform/android-ndk-r9c/toolchains/arm-linux-androideabi-4.8/prebuilt/linux-x86_64/bin//arm-linux-androideabi-gcc
configure: WARNING: if you wanted to set the --build type, don't use --host.
    If a cross compiler is detected then cross compile mode will be used
checking for --enable-universalsdk... no
checking for --with-universal-archs... 32-bit
checking MACHDEP... linux3
checking EXTRAPLATDIR... 
checking machine type as reported by uname -m... x86_64
checking for --without-gcc... no
checking for arm-eabi-gcc... arm-linux-androideabi-gcc -DANDROID -mandroid  -fomit-frame-pointer --sysroot /home/med-phisiker-linux/.buildozer/android/platform/android-ndk-r9c/platforms/android-14/arch-arm
checking whether the C compiler works... no
configure: error: in `/home/med-phisiker-linux/kivy_experiments/.buildozer/android/platform/python-for-android/build/python/Python-2.7.2':
configure: error: C compiler cannot create executables
See`config.log' for more details
Command failed: ./distribute.sh -m "kivy" -d "Hello_world"
"""
 please help me...

**Comment by monojk** [comment]
Did you get the problem solved? And how? I seem to have the same problem, looked also in stackoverflow where similar problems were posted w/o answers.
