### ISSUE TITLE
android.extra-manifest entry inserts bad code into AndroidManifest

### ISSUE THREAD

**Issue by lufebe16** [kivy/buildozer#1535]
### Versions

* Python: 3.10
* OS: any
* Buildozer: newest pip version

### Description

using the entry for:

 android.extra_manifest_xml = ./src/manifest/extra_permission.xml

to add a new permission. The file contains:
`
<uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE"/>
`
This results in a build failure on the last step. Gradle reclaims an error on parsing AndroidManifest.xml.

Investigation of the problem showed, that buildozer obviously removed all double quotes from the xml entry that has been added.

### Correction

To correct this failure one needs to change the following code in the source (android.py). Hier is a patch that applies to the current master.

[extra.zip](https://github.com/kivy/buildozer/files/10218375/extra.zip)

**Comment by RobertFlatt** [comment]
As a workaround use `android.permissions=READ_EXTERNAL_STORAGE` in buildozer.spec

**Comment by misl6** [comment]
Closed via #1555
