### ISSUE TITLE
Feature Request: Vagrantfile

### ISSUE THREAD

**Issue by Immortalin** [kivy/buildozer#154]
Hi, I am running running Kivy on a Windows Machine, I would really be grateful if someone could write a Vagrant file for the automated setup of buildozer as currently only a full-featured VM is available from the Kivy virtual machine page. I only need a simple isolated environment that can be use within vagrant without the need for extensive linux knowledge for building Android apps, not a fully featured VM. Thank you.
##

**Comment by olymk2** [comment]
not quite a vagrant file, but you maybe able to use docker , i have not tried this outside a linux machine myself but it should just work the build files are below they may need some slight adjustments.

https://github.com/olymk2/docker_kivy_buildozer_container

its a self contained environment that installs all required files and then uses your local project files to build and generate the apk.

you may have to adjust slightly as i am not sure about deploying over usb direct from the docker machine.

**Comment by dessant** [comment]
You could also use packer to create a vagrant file. @akshayaurora recently made a script for exporting an ovf, with minor changes this template can be used for creating vagrant files: https://github.com/kivy/buildozer/tree/master/buildozer/tools/packer

https://www.packer.io/docs/post-processors/vagrant.html

We intend to target both vagrant and docker in future releases.

**Comment by olymk2** [comment]
feel free to use the stuff in the repo above if its useful I am using it to package my apps.

it gets around the issues with having the correct versions and android sdk tools being missing etc and lets me just build my app, It would be nice to know if it works for other people as well

**Comment by dessant** [comment]
@olymk2 thanks for the share. :+1:

**Comment by Immortalin** [comment]
@olymk2 thanks!

**Comment by jedie** [comment]
see also: #589

**Comment by AndreMiras** [comment]
We now provide a Dockerfile that's also published on DockerHub https://hub.docker.com/r/kivy/buildozer
You can play with it in different ways, e.g.
```
docker run --interactive --tty --rm \
  --volume "$HOME/.buildozer":/home/user/.buildozer \
  --volume "$PWD":/home/user/hostcwd \
  --entrypoint /bin/bash \
  kivy/buildozer
```
Providing a Vagrantfile is not that difficult, but integrating it to automated test to it it more tricky.
I'm not sure we want to provide tools we don't test (anymore).
