### ISSUE TITLE
When I run the application on my smartphone, the application crashes and gives an error in logcat [WARNING] [Base ] Unknown <android> provider

### ISSUE THREAD

**Issue by Vladislav001414** [kivy/buildozer#1545]
When launched on my smartphone, the application crashes as soon as I enter it, in logcat it gives the following error: [WARNING] [Base] Unknown <android> provider
On the bluestacks emulator, everything works fine on other phones, too, on mine. 
My phone is Oppo A53 
Android version 12
![image](https://user-images.githubusercontent.com/120846729/212444320-b37ecffd-fd94-4ff0-8d30-708708dc62b5.png)
![image](https://user-images.githubusercontent.com/120846729/212444448-506dfd58-8059-4ca8-bffe-966e69ee50e8.png)
![image](https://user-images.githubusercontent.com/120846729/212444497-595ae7e0-58eb-446a-b0d4-a1876868c4e1.png)
![image](https://user-images.githubusercontent.com/120846729/212444538-526fd93a-2382-415e-88a4-b50e5a32ef3a.png)
![image](https://user-images.githubusercontent.com/120846729/212444552-7868f28b-f90f-4d48-844f-6f4931562ac3.png)
![image](https://user-images.githubusercontent.com/120846729/212444569-a5ef55c2-c77b-4a45-b058-11aef12e1fda.png)

**Comment by RobertFlatt** [comment]
Probably another instance of this issue https://github.com/Android-for-Python/Android-for-Python-Users#kivy-is-too-old

Use kivymd 1.0.2

**Comment by Vladislav001414** [comment]
> 

Thanks, it helped, but let's say I need to use the functions that were added to kivy == 1.1.0 but this version is not there and there is only 1.1.1 and how can I use the 1.1.0 functions on version 1.0.2?

**Comment by Vladislav001414** [comment]
And I installed kivy 1.0.2 instead of 1.1.1 did not help solve the problem on another program where there is a TopAppBar without it, everything works with it no (does not work only on my device)

**Comment by RobertFlatt** [comment]
> but let's say I need to use the functions that were added to kivy == 1.1.0 

That right you can't use features that are not implemented! 

The core issue is KivyMD releases greater than 1.0.2 depend on still in development Kivy code. We know the Kivy development code has issues portability related to OpenGL - its a challenging issue. 

> did not help solve the problem on another program where there is a TopAppBar 

If you have questions about KivyMD widgets, best to ask KivMD.

**Comment by Vladislav001414** [comment]
> > но допустим мне нужно использовать функции которые добавили в kivy == 1.1.0
> 
> Это право, вы не можете использовать функции, которые не реализованы!
> 
> Основная проблема заключается в том, что выпуски KivyMD выше 1.0.2 зависят от кода Kivy, который все еще находится в разработке. Мы знаем, что код разработки Kivy имеет проблемы с переносимостью, связанные с OpenGL — это сложная проблема.
> 
> > не помогло решить проблему на другой программе где есть TopAppBar
> 
> Если у вас есть вопросы о виджетах KivyMD, лучше всего задать KivMD.

Thank you for your answer, if it's not difficult for you, can you tell me where you can turn to kivymd to ask them a question?

**Comment by misl6** [comment]
Hi @Vladislav001414 !

You can find a link to the KivyMD server in our Discord #kivymd-support channel
