### ISSUE TITLE
Error compilation buildozer python from linux 

### ISSUE THREAD

**Issue by valter97** [kivy/buildozer#1559]
hi all i get this warning when i run buildozer on python from linux and i don't know how to fix it i tried to download all the packages again but it still comes out please give me a hand i don't know what to do

[WARNING]: ERROR: /home/cinghials/Scrivania/applicazione/.buildozer/android/platform/build-arm64-v8a_armeabi-v7a/build/other_builds/hostpython3/desktop/hostpython3/native-build/python3 failed!

# Command failed: ['/home/cinghials/Scrivania/applicazione/venv/bin/python', '-m', 'pythonforandroid.toolchain', 'create', '--dist_name=myapp', '--bootstrap=sdl2', '--requirements=python3=3.10.9,kivy', '--arch=arm64-v8a', '--arch=armeabi-v7a', '--copy-libs', '--color=always', '--storage-dir=/home/cinghials/Scrivania/applicazione/.buildozer/android/platform/build-arm64-v8a_armeabi-v7a', '--ndk-api=21', '--ignore-setup-py', '--debug']
# ENVIRONMENT:
#     POWERSHELL_TELEMETRY_OPTOUT = '1'
#     USER = 'cinghials'
#     XDG_SEAT = 'seat0'
#     XDG_SESSION_TYPE = 'x11'
#     DOTNET_CLI_TELEMETRY_OPTOUT = '1'
#     SSH_AGENT_PID = '1251'
#     HOME = '/home/cinghials'
#     DESKTOP_SESSION = 'lightdm-xsession'
#     XDG_SEAT_PATH = '/org/freedesktop/DisplayManager/Seat0'
#     GTK_MODULES = 'gail:atk-bridge'
#     DBUS_SESSION_BUS_ADDRESS = 'unix:path=/run/user/1000/bus'
#     COMMAND_NOT_FOUND_INSTALL_PROMPT = '1'
#     QT_QPA_PLATFORMTHEME = 'qt5ct'
#     LOGNAME = 'cinghials'
#     QT_AUTO_SCREEN_SCALE_FACTOR = '0'
#     XDG_SESSION_CLASS = 'user'
#     XDG_SESSION_ID = '2'
#     PATH = '/home/cinghials/.buildozer/android/platform/apache-ant-1.9.4/bin:/home/cinghials/Scrivania/applicazione/venv/bin:/usr/local/sbin:/usr/sbin:/sbin:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games:/home/cinghials/.dotnet/tools'
#     _JAVA_OPTIONS = '-Dawt.useSystemAAFontSettings=on -Dswing.aatext=true'
#     XDG_SESSION_PATH = '/org/freedesktop/DisplayManager/Session0'
#     XDG_RUNTIME_DIR = '/run/user/1000'
#     XDG_MENU_PREFIX = 'xfce-'
#     LANG = 'it_IT.UTF-8'
#     POWERSHELL_UPDATECHECK = 'Off'
#     XDG_CURRENT_DESKTOP = 'XFCE'
#     XDG_SESSION_DESKTOP = 'lightdm-xsession'
#     XAUTHORITY = '/home/cinghials/.Xauthority'
#     XDG_GREETER_DATA_DIR = '/var/lib/lightdm/data/cinghials'
#     SSH_AUTH_SOCK = '/tmp/ssh-XXXXXX8Mnztv/agent.1193'
#     SHELL = '/usr/bin/zsh'
#     GDMSESSION = 'lightdm-xsession'
#     QT_ACCESSIBILITY = '1'
#     XDG_VTNR = '7'
#     PWD = '/home/cinghials/Scrivania/applicazione'
#     XDG_DATA_DIRS = '/usr/share/xfce4:/usr/local/share/:/usr/share/:/usr/share'
#     XDG_CONFIG_DIRS = '/etc/xdg'
#     SESSION_MANAGER = 'local/kali-cinghials:@/tmp/.ICE-unix/1193,unix/kali-cinghials:/tmp/.ICE-unix/1193'
#     PANEL_GDK_CORE_DEVICE_EVENTS = '0'
#     DISPLAY = ':0.0'
#     CHROME_DESKTOP = 'code-url-handler.desktop'
#     ORIGINAL_XDG_CURRENT_DESKTOP = 'XFCE'
#     GDK_BACKEND = 'x11'
#     NO_AT_BRIDGE = '1'
#     SHLVL = '1'
#     OLDPWD = '/home/cinghials/Scrivania/applicazione'
#     LS_COLORS = 'rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=00:su=37;41:sg=30;43:ca=00:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.zst=01;31:*.tzst=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.wim=01;31:*.swm=01;31:*.dwm=01;31:*.esd=01;31:*.avif=01;35:*.jpg=01;35:*.jpeg=01;35:*.mjpg=01;35:*.mjpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.webp=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=00;36:*.au=00;36:*.flac=00;36:*.m4a=00;36:*.mid=00;36:*.midi=00;36:*.mka=00;36:*.mp3=00;36:*.mpc=00;36:*.ogg=00;36:*.ra=00;36:*.wav=00;36:*.oga=00;36:*.opus=00;36:*.spx=00;36:*.xspf=00;36:*~=00;90:*#=00;90:*.bak=00;90:*.old=00;90:*.orig=00;90:*.part=00;90:*.rej=00;90:*.swp=00;90:*.tmp=00;90:*.dpkg-dist=00;90:*.dpkg-old=00;90:*.ucf-dist=00;90:*.ucf-new=00;90:*.ucf-old=00;90:*.rpmnew=00;90:*.rpmorig=00;90:*.rpmsave=00;90::ow=30;44:'
#     LESS_TERMCAP_mb = '\x1b[1;31m'
#     LESS_TERMCAP_md = '\x1b[1;36m'
#     LESS_TERMCAP_me = '\x1b[0m'
#     LESS_TERMCAP_so = '\x1b[01;33m'
#     LESS_TERMCAP_se = '\x1b[0m'
#     LESS_TERMCAP_us = '\x1b[1;32m'
#     LESS_TERMCAP_ue = '\x1b[0m'
#     _ = '/home/cinghials/Scrivania/applicazione/venv/bin/buildozer'
#     TERM_PROGRAM = 'vscode'
#     TERM_PROGRAM_VERSION = '1.75.0'
#     COLORTERM = 'truecolor'
#     GIT_ASKPASS = '/usr/share/code/resources/app/extensions/git/dist/askpass.sh'
#     VSCODE_GIT_ASKPASS_NODE = '/usr/share/code/code'
#     VSCODE_GIT_ASKPASS_EXTRA_ARGS = '--ms-enable-electron-run-as-node'
#     VSCODE_GIT_ASKPASS_MAIN = '/usr/share/code/resources/app/extensions/git/dist/askpass-main.js'
#     VSCODE_GIT_IPC_HANDLE = '/run/user/1000/vscode-git-7511572551.sock'
#     VSCODE_INJECTION = '1'
#     ZDOTDIR = '/home/cinghials'
#     USER_ZDOTDIR = '/home/cinghials'
#     TERM = 'xterm-256color'
#     VIRTUAL_ENV = '/home/cinghials/Scrivania/applicazione/venv'
#     PACKAGES_PATH = '/home/cinghials/.buildozer/android/packages'
#     ANDROIDSDK = '/home/cinghials/.buildozer/android/platform/android-sdk'
#     ANDROIDNDK = '/home/cinghials/.buildozer/android/platform/android-ndk-r25b'
#     ANDROIDAPI = '31'
#     ANDROIDMINAPI = '21'
# 
# Buildozer failed to execute the last command
# The error might be hidden in the log above this error
# Please read the full log, and search for it before
# raising an issue with buildozer itself.
# In case of a bug report, please add a full log with log_level = 2

**Comment by RobertFlatt** [comment]
Address usage problems to the user groups:

https://discord.gg/TshtbsFg
https://groups.google.com/g/kivy-users

Include the full log as a .txt file.
