### ISSUE TITLE
[ERROR]:   Build failed: Android SDK dir was not specified, exiting.

### ISSUE THREAD

**Issue by masfaraud** [kivy/buildozer#1562]
### Versions

* Python: 3.10.6
* OS: Linux Mint 21
* Buildozer: 1.5.0

### Description

Trying to build a simple kivy application by running 
`buildozer android debug` 

### buildozer.spec
Command:
```sh
buildozer android debug
```

Spec file:
No edit apart from name after buildozer init

### Logs

Got some error in command
`/usr/bin/python3 -m pythonforandroid.toolchain create --dist_name=main --bootstrap=sdl2 --requirements=python3,kivy --arch=arm64-v8a --arch=armeabi-v7a --copy-libs --color=always --storage-dir=/home/steven/Documents/git/car-instruments/.buildozer/android/platform/build-arm64-v8a_armeabi-v7a --ndk-api=21 --ignore-setup-py --debug`

error is:
[ERROR]:   Build failed: Android SDK dir was not specified, exiting.

Got previously some errors with pip cache with wrong permission and clang missing package

**Comment by RobertFlatt** [comment]
This forum is for development issues not usage issues.

Please use the user groups:
https://discord.gg/TshtbsFg
https://groups.google.com/g/kivy-users
