### ISSUE TITLE
Gradle Error

### ISSUE THREAD

**Issue by BedrettinOrtak** [kivy/buildozer#1563]
Unzipping /home/ubuntu/.gradle/wrapper/dists/gradle-7.4.1-all/8bevta3mh7872g50ecurigeld/gradle-7.4.1-all.zip to /home/ubuntu/.gradle/wrapper/dists/gradle-7.4.1-all/8bevta3mh7872g50ecurigeld
[DEBUG]:   	Set executable permissions for: /home/ubuntu/.gradle/wrapper/dists/gradle-7.4.1-all/8bevta3mh7872g50ecurigeld/gradle-7.4.1/bin/gradle
[DEBUG]:   	
[DEBUG]:   	Welcome to Gradle 7.4.1!
[DEBUG]:   	
[DEBUG]:   	Here are the highlights of this release:
[DEBUG]:   	 - Aggregated test and JaCoCo reports
[DEBUG]:   	 - Marking additional test source directories as tests in IntelliJ
[DEBUG]:   	 - Support for Adoptium JDKs in Java toolchains
[DEBUG]:   	
[DEBUG]:   	For more details see https://docs.gradle.org/7.4.1/release-notes.html
[DEBUG]:   	
[DEBUG]:   	Starting a Gradle Daemon (subsequent builds will be faster)
[DEBUG]:   	
[DEBUG]:   	> Configure project :
[DEBUG]:   	WARNING:Using flatDir should be avoided because it doesn't support any meta-data formats.
[DEBUG]:   	
[DEBUG]:   	> Task :checkDebugAarMetadata
[DEBUG]:   	WARNING: [Processor] Library '/home/ubuntu/Downloads/Sideband-main/sbapp/.buildozer/android/platform/build-arm64-v8a_armeabi-v7a/dists/sideband/libs/support-compat-28.0.0.aar' contains references to both AndroidX and old support library. This seems like the library is partially migrated. Jetifier will try to rewrite the library anyway.
[DEBUG]:   	 Example of androidX reference: 'androidx/versionedparcelable/VersionedParcel'
[DEBUG]:   	 Example of support library reference: 'android/support/v4/graphics/drawable/IconCompat'
[DEBUG]:   	
[DEBUG]:   	> Task :processDebugResources FAILED
[DEBUG]:   	
[DEBUG]:   	FAILURE: Build failed with an exception.
[DEBUG]:   	
[DEBUG]:   	* What went wrong:
[DEBUG]:   	Execution failed for task ':processDebugResources'.
[DEBUG]:   	> A failure occurred while executing com.android.build.gradle.internal.res.LinkApplicationAndroidResourcesTask$TaskAction
[DEBUG]:   	   > Android resource linking failed
[DEBUG]:   	     ERROR:/home/ubuntu/Downloads/Sideband-main/sbapp/.buildozer/android/platform/build-arm64-v8a_armeabi-v7a/dists/sideband/build/intermediates/packaged_manifests/debug/AndroidManifest.xml:92: AAPT: error: resource xml/device_filter (aka io.unsigned.sideband:xml/device_filter) not found.
[DEBUG]:   	
[DEBUG]:   	
[DEBUG]:   	* Try:
[DEBUG]:   	> Run with --stacktrace option to get the stack trace.
[DEBUG]:   	> Run with --info or --debug option to get more log output.
[DEBUG]:   	> Run with --scan to get full insights.
[DEBUG]:   	
[DEBUG]:   	* Get more help at https://help.gradle.org
[DEBUG]:   	
[DEBUG]:   	Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.
[DEBUG]:   	
[DEBUG]:   	You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.
[DEBUG]:   	
[DEBUG]:   	See https://docs.gradle.org/7.4.1/userguide/command_line_interface.html#sec:command_line_warnings
[DEBUG]:   	
[DEBUG]:   	BUILD FAILED in 3m 57s
[DEBUG]:   	12 actionable tasks: 11 executed, 1 up-to-date
[DEBUG]:   	
[DEBUG]:   	
Exception in thread background thread for pid 159838:
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ubuntu/lib/python3.10/site-packages/sh.py", line 1641, in wrap
    fn(*rgs, **kwargs)
  File "/home/ubuntu/lib/python3.10/site-packages/sh.py", line 2569, in background_thread
    handle_exit_code(exit_code)
  File "/home/ubuntu/lib/python3.10/site-packages/sh.py", line 2269, in fn
    return self.command.handle_command_exit_code(exit_code)
  File "/home/ubuntu/lib/python3.10/site-packages/sh.py", line 869, in handle_command_exit_code
    raise exc
sh.ErrorReturnCode_1: 

  RAN: /home/ubuntu/Downloads/Sideband-main/sbapp/.buildozer/android/platform/build-arm64-v8a_armeabi-v7a/dists/sideband/gradlew clean assembleDebug

  STDOUT:
Downloading https://services.gradle.org/distributions/gradle-7.4.1-all.zip
.............................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................
Unzipping /home/ubuntu/.gradle/wrapper/dists/gradle-7.4.1-all/8bevta3mh7872g50ecurigeld/gradle-7.4.1-all.zip to /home/ubuntu/.gradle/wrapper/dists/gradle-7.4.1-all/8bevta3mh7872g50ecurigeld
Set executable permissions for: /home/ubuntu/.gradle/wrapper/dists/gradle-7.4.1-all/8bevta3mh7872g50ecurigeld/gradle-7.4.1/bin/gradle

Welcome to Gradle 7.4.1!

Here are the highlights of this release:
 - Aggregated test and JaCoCo reports
 - Marking additional test source directories as tests in IntelliJ
 - Support for Adoptium JDKs in Java toolchains

For more details see https://docs.gradle.org/7.4.1/release-notes.html

Starting a Gradle Daemon (subsequent builds will be faster)

> Configure project :
WARNING:Using flatDir should be avoided because it doesn't support any meta-data formats.

> Task :checkDebugAarMetadata
WARNING: [Processor] Library '/home/ubuntu/Downloads/Sideband-main/sbapp/.buildozer/android/platform/build-arm64-v8a_armeabi-v7a/dists/sideband/libs/support-compat-28.0.0.aar' contains references to both AndroidX and old support library. This seems like the library is partially migrated. Jetifier will try to rewrite the library anyway.
 Example of androidX reference: 'androidx/versionedparcelable/VersionedParcel'
 Example of support library reference: 'android/support/v4/graphics/drawable/IconCompat'

> Task :processDebugResources FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':processDebugResources'.
> A failure occurred while executing com.android.build.gradle.internal.res.LinkApplicationAndroidResourcesTask$TaskAction
   > Android resource linking failed
     ERROR:/home/ubuntu/Downloads/Sideband-main/sbapp/.buildozer/android/platform/build-arm64-v8a_armeabi-v7a/dists/sideband/build/intermediates/packaged_manifests/debug/AndroidManifest.xml:92: AAPT: error: resource xml/device_filter (aka io.unsigned.sideband:xml/device_filter) not found.
         

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

See https://docs.gradle.org/7.4.1/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 3m 57s
12 actionable tasks: 11 executed, 1 up-to-date

[INFO]:    STDOUT (last 20 lines of 59):
[DEBUG]:         	
	
* Try:	
> Run with --stacktrace option to get the stack trace.	
> Run with --info or --debug option to get more log output.	
> Run with --scan to get full insights.	
	
* Get more help at https://help.gradle.org	
	
Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.	
	
You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.	
	
See https://docs.gradle.org/7.4.1/userguide/command_line_interface.html#sec:command_line_warnings	
	
BUILD FAILED in 3m 57s	
12 actionable tasks: 11 executed, 1 up-to-date	

[INFO]:    STDERR:
	
[INFO]:    ENV:
export SHELL='/bin/bash'
export SESSION_MANAGER='local/ubuntu-2204:@/tmp/.ICE-unix/1656,unix/ubuntu-2204:/tmp/.ICE-unix/1656'
export QT_ACCESSIBILITY='1'
export COLORTERM='truecolor'
export XDG_CONFIG_DIRS='/etc/xdg/xdg-ubuntu:/etc/xdg'
export SSH_AGENT_LAUNCHER='gnome-keyring'
export XDG_MENU_PREFIX='gnome-'
export GNOME_DESKTOP_SESSION_ID='this-is-deprecated'
export CONDA_EXE='/home/ubuntu/anaconda3/bin/conda'
export _CE_M=''
export GNOME_SHELL_SESSION_MODE='ubuntu'
export SSH_AUTH_SOCK='/run/user/1000/keyring/ssh'
export XMODIFIERS='@im=ibus'
export DESKTOP_SESSION='ubuntu'
export GTK_MODULES='gail:atk-bridge'
export DBUS_STARTER_BUS_TYPE='session'
export PWD='/home/ubuntu/Downloads/Sideband-main/sbapp'
export LOGNAME='ubuntu'
export XDG_SESSION_DESKTOP='ubuntu'
export XDG_SESSION_TYPE='wayland'
export CONDA_PREFIX='/home/ubuntu/anaconda3'
export SYSTEMD_EXEC_PID='1656'
export XAUTHORITY='/run/user/1000/.mutter-Xwaylandauth.SG6B01'
export HOME='/home/ubuntu'
export USERNAME='ubuntu'
export IM_CONFIG_PHASE='1'
export LANG='en_US.UTF-8'
export LS_COLORS='rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=00:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.zst=01;31:*.tzst=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.wim=01;31:*.swm=01;31:*.dwm=01;31:*.esd=01;31:*.jpg=01;35:*.jpeg=01;35:*.mjpg=01;35:*.mjpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.webp=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=00;36:*.au=00;36:*.flac=00;36:*.m4a=00;36:*.mid=00;36:*.midi=00;36:*.mka=00;36:*.mp3=00;36:*.mpc=00;36:*.ogg=00;36:*.ra=00;36:*.wav=00;36:*.oga=00;36:*.opus=00;36:*.spx=00;36:*.xspf=00;36:'
export XDG_CURRENT_DESKTOP='ubuntu:GNOME'
export VTE_VERSION='6800'
export WAYLAND_DISPLAY='wayland-0'
export CONDA_PROMPT_MODIFIER='(base) '
export GNOME_TERMINAL_SCREEN='/org/gnome/Terminal/screen/5832043a_ccb3_4807_9fce_93b14a2a95ca'
export GNOME_SETUP_DISPLAY=':1'
export LESSCLOSE='/usr/bin/lesspipe %s %s'
export XDG_SESSION_CLASS='user'
export TERM='xterm-256color'
export _CE_CONDA=''
export LESSOPEN='| /usr/bin/lesspipe %s'
export USER='ubuntu'
export GNOME_TERMINAL_SERVICE=':1.117'
export CONDA_SHLVL='1'
export DISPLAY=':0'
export SHLVL='1'
export QT_IM_MODULE='ibus'
export DBUS_STARTER_ADDRESS='unix:path=/run/user/1000/bus,guid=659cb5033d753c3312ecc8b963ea505e'
export CONDA_PYTHON_EXE='/home/ubuntu/anaconda3/bin/python'
export XDG_RUNTIME_DIR='/run/user/1000'
export CONDA_DEFAULT_ENV='base'
export XDG_DATA_DIRS='/usr/share/ubuntu:/usr/local/share/:/usr/share/:/var/lib/snapd/desktop'
export PATH='/home/ubuntu/.buildozer/android/platform/apache-ant-1.9.4/bin:/home/ubuntu/anaconda3/bin:/home/ubuntu/anaconda3/condabin:/home/ubuntu/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/snap/bin'
export GDMSESSION='ubuntu'
export DBUS_SESSION_BUS_ADDRESS='unix:path=/run/user/1000/bus,guid=659cb5033d753c3312ecc8b963ea505e'
export _='/home/ubuntu/bin/buildozer'
export OLDPWD='/home/ubuntu/Downloads/Sideband-main'
export PACKAGES_PATH='/home/ubuntu/.buildozer/android/packages'
export ANDROIDSDK='/home/ubuntu/.buildozer/android/platform/android-sdk'
export ANDROIDNDK='/home/ubuntu/.buildozer/android/platform/android-ndk-r25b'
export ANDROIDAPI='30'
export ANDROIDMINAPI='24'
export P4A_kivymd_DIR='/home/ubuntu/Downloads/Others/KivyMD-master'
export ANDROID_NDK_HOME='/home/ubuntu/.buildozer/android/platform/android-ndk-r25b'
export ANDROID_HOME='/home/ubuntu/.buildozer/android/platform/android-sdk'

[INFO]:    COMMAND:
cd /home/ubuntu/Downloads/Sideband-main/sbapp/.buildozer/android/platform/build-arm64-v8a_armeabi-v7a/dists/sideband && /home/ubuntu/Downloads/Sideband-main/sbapp/.buildozer/android/platform/build-arm64-v8a_armeabi-v7a/dists/sideband/gradlew clean assembleDebug

[WARNING]: ERROR: /home/ubuntu/Downloads/Sideband-main/sbapp/.buildozer/android/platform/build-arm64-v8a_armeabi-v7a/dists/sideband/gradlew failed!
WARNING: Received a --sdk argument, but this argument is deprecated and does nothing.
No setup.py/pyproject.toml used, copying full private data into .apk.
Applying Java source code patches...
Applying patch: src/patches/SDLActivity.java.patch
# Command failed: ['/home/ubuntu/bin/python', '-m', 'pythonforandroid.toolchain', 'apk', '--bootstrap', 'sdl2', '--dist_name', 'sideband', '--name', 'Sideband', '--version', '0.5.2', '--package', 'io.unsigned.sideband', '--minsdk', '24', '--ndk-api', '24', '--private', '/home/ubuntu/Downloads/Sideband-main/sbapp/.buildozer/android/app', '--permission', 'INTERNET', '--permission', 'POST_NOTIFICATIONS', '--permission', 'WAKE_LOCK', '--permission', 'FOREGROUND_SERVICE', '--permission', 'CHANGE_WIFI_MULTICAST_STATE', '--permission', 'BLUETOOTH_CONNECT', '--android-entrypoint', 'org.kivy.android.PythonActivity', '--android-apptheme', '@android:style/Theme.NoTitleBar', '--presplash', '/home/ubuntu/Downloads/Sideband-main/sbapp/./assets/presplash_small.png', '--icon', '/home/ubuntu/Downloads/Sideband-main/sbapp/./assets/icon.png', '--orientation', 'portrait', '--window', '--enable-androidx', '--intent-filters', '/home/ubuntu/Downloads/Sideband-main/sbapp/patches/intent-filter.xml', '--numeric-version', '20230204', '--presplash-color', '#00000000', '--service', 'sidebandservice:services/sidebandservice.py:foreground', '--copy-libs', '--local-recipes', '/home/ubuntu/Downloads/Sideband-main/Others/python-for-android/pythonforandroid/recipes', '--add-aar', '/home/ubuntu/Downloads/Sideband-main/sbapp/patches/support-compat-28.0.0.aar', '--arch', 'arm64-v8a', '--arch', 'armeabi-v7a', '--color=always', '--storage-dir=/home/ubuntu/Downloads/Sideband-main/sbapp/.buildozer/android/platform/build-arm64-v8a_armeabi-v7a', '--ndk-api=24', '--ignore-setup-py', '--debug']
# ENVIRONMENT:
#     SHELL = '/bin/bash'
#     SESSION_MANAGER = 'local/ubuntu-2204:@/tmp/.ICE-unix/1656,unix/ubuntu-2204:/tmp/.ICE-unix/1656'
#     QT_ACCESSIBILITY = '1'
#     COLORTERM = 'truecolor'
#     XDG_CONFIG_DIRS = '/etc/xdg/xdg-ubuntu:/etc/xdg'
#     SSH_AGENT_LAUNCHER = 'gnome-keyring'
#     XDG_MENU_PREFIX = 'gnome-'
#     GNOME_DESKTOP_SESSION_ID = 'this-is-deprecated'
#     CONDA_EXE = '/home/ubuntu/anaconda3/bin/conda'
#     _CE_M = ''
#     GNOME_SHELL_SESSION_MODE = 'ubuntu'
#     SSH_AUTH_SOCK = '/run/user/1000/keyring/ssh'
#     XMODIFIERS = '@im=ibus'
#     DESKTOP_SESSION = 'ubuntu'
#     GTK_MODULES = 'gail:atk-bridge'
#     DBUS_STARTER_BUS_TYPE = 'session'
#     PWD = '/home/ubuntu/Downloads/Sideband-main/sbapp'
#     LOGNAME = 'ubuntu'
#     XDG_SESSION_DESKTOP = 'ubuntu'
#     XDG_SESSION_TYPE = 'wayland'
#     CONDA_PREFIX = '/home/ubuntu/anaconda3'
#     SYSTEMD_EXEC_PID = '1656'
#     XAUTHORITY = '/run/user/1000/.mutter-Xwaylandauth.SG6B01'
#     HOME = '/home/ubuntu'
#     USERNAME = 'ubuntu'
#     IM_CONFIG_PHASE = '1'
#     LANG = 'en_US.UTF-8'
#     LS_COLORS = 'rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=00:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.zst=01;31:*.tzst=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.wim=01;31:*.swm=01;31:*.dwm=01;31:*.esd=01;31:*.jpg=01;35:*.jpeg=01;35:*.mjpg=01;35:*.mjpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.webp=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=00;36:*.au=00;36:*.flac=00;36:*.m4a=00;36:*.mid=00;36:*.midi=00;36:*.mka=00;36:*.mp3=00;36:*.mpc=00;36:*.ogg=00;36:*.ra=00;36:*.wav=00;36:*.oga=00;36:*.opus=00;36:*.spx=00;36:*.xspf=00;36:'
#     XDG_CURRENT_DESKTOP = 'ubuntu:GNOME'
#     VTE_VERSION = '6800'
#     WAYLAND_DISPLAY = 'wayland-0'
#     CONDA_PROMPT_MODIFIER = '(base) '
#     GNOME_TERMINAL_SCREEN = '/org/gnome/Terminal/screen/5832043a_ccb3_4807_9fce_93b14a2a95ca'
#     GNOME_SETUP_DISPLAY = ':1'
#     LESSCLOSE = '/usr/bin/lesspipe %s %s'
#     XDG_SESSION_CLASS = 'user'
#     TERM = 'xterm-256color'
#     _CE_CONDA = ''
#     LESSOPEN = '| /usr/bin/lesspipe %s'
#     USER = 'ubuntu'
#     GNOME_TERMINAL_SERVICE = ':1.117'
#     CONDA_SHLVL = '1'
#     DISPLAY = ':0'
#     SHLVL = '1'
#     QT_IM_MODULE = 'ibus'
#     DBUS_STARTER_ADDRESS = 'unix:path=/run/user/1000/bus,guid=659cb5033d753c3312ecc8b963ea505e'
#     CONDA_PYTHON_EXE = '/home/ubuntu/anaconda3/bin/python'
#     XDG_RUNTIME_DIR = '/run/user/1000'
#     CONDA_DEFAULT_ENV = 'base'
#     XDG_DATA_DIRS = '/usr/share/ubuntu:/usr/local/share/:/usr/share/:/var/lib/snapd/desktop'
#     PATH = '/home/ubuntu/.buildozer/android/platform/apache-ant-1.9.4/bin:/home/ubuntu/anaconda3/bin:/home/ubuntu/anaconda3/condabin:/home/ubuntu/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/snap/bin'
#     GDMSESSION = 'ubuntu'
#     DBUS_SESSION_BUS_ADDRESS = 'unix:path=/run/user/1000/bus,guid=659cb5033d753c3312ecc8b963ea505e'
#     _ = '/home/ubuntu/bin/buildozer'
#     OLDPWD = '/home/ubuntu/Downloads/Sideband-main'
#     PACKAGES_PATH = '/home/ubuntu/.buildozer/android/packages'
#     ANDROIDSDK = '/home/ubuntu/.buildozer/android/platform/android-sdk'
#     ANDROIDNDK = '/home/ubuntu/.buildozer/android/platform/android-ndk-r25b'
#     ANDROIDAPI = '30'
#     ANDROIDMINAPI = '24'
#     P4A_kivymd_DIR = '/home/ubuntu/Downloads/Others/KivyMD-master'
# 
# Buildozer failed to execute the last command
# The error might be hidden in the log above this error
# Please read the full log, and search for it before
# raising an issue with buildozer itself.
# In case of a bug report, please add a full log with log_level = 2

**Comment by misl6** [comment]
Hi @BedrettinOrtak !

Can you please share your `buildozer.spec` file?

**Comment by BedrettinOrtak** [comment]
[app]
title = Sideband
package.name = sideband
package.domain = io.unsigned

source.dir = .
source.include_exts = py,png,jpg,jpeg,ttf,kv,pyi,typed,so,0,1,2,3,atlas,frag
source.include_patterns = assets/*
source.exclude_patterns = app_storage/*,venv/*,Makefile,./Makefil*,requirements,precompiled/*,parked/*,./setup.py,Makef*,./Makefile,Makefile

version.regex = __version__ = ['"](.*)['"]
version.filename = %(source.dir)s/main.py
android.numeric_version = 20230204
requirements = python3==3.9.5,hostpython3==3.9.5,cryptography,cffi,pycparser,kivy==2.1.0,pygments,sdl2,sdl2_ttf==2.0.15,pillow,qrcode==7.3.1,netifaces,libbz2,pydenticon,usb4a,usbserial4a
p4a.local_recipes = ../Others/python-for-android/pythonforandroid/recipes
requirements.source.kivymd = ../../Others/KivyMD-master
icon.filename = %(source.dir)s/assets/icon.png
presplash.filename = %(source.dir)s/assets/presplash_small.png
android.presplash_color = #00000000
# TODO: Fix
orientation = portrait
fullscreen = 0
android.permissions = INTERNET,POST_NOTIFICATIONS,WAKE_LOCK,FOREGROUND_SERVICE,CHANGE_WIFI_MULTICAST_STATE,BLUETOOTH_CONNECT
android.api = 30
android.minapi = 24
android.ndk = 25b
android.skip_update = False
android.accept_sdk_license = True
android.release_artifact = apk
android.archs = arm64-v8a,armeabi-v7a
#android.logcat_filters = *:S python:D
services = sidebandservice:services/sidebandservice.py:foreground
android.whitelist = lib-dynload/termios.so
android.manifest.intent_filters = patches/intent-filter.xml
android.add_aars = patches/support-compat-28.0.0.aar
[buildozer]
log_level = 2
warn_on_root = 0
build_dir = ./.buildozer
bin_dir = ./bin
Footer

**Comment by misl6** [comment]
Can you share the content of `patches/intent-filter.xml` ?

**Comment by BedrettinOrtak** [comment]
<intent-filter>
   <action android:name="android.hardware.usb.action.USB_DEVICE_ATTACHED" />
</intent-filter>


<intent-filter>
   <action android:name="android.intent.action.VIEW" />
   <category android:name="android.intent.category.DEFAULT" />
   <category android:name="android.intent.category.BROWSABLE" />
   <data android:scheme="lxm"/>
</intent-filter>


<intent-filter>
    <action android:name="android.intent.action.WEB_SEARCH" />
    <category android:name="android.intent.category.DEFAULT" />
    <category android:name="android.intent.category.LAUNCHER" />
</intent-filter>


<meta-data android:name="android.hardware.usb.action.USB_DEVICE_ATTACHED"
    android:resource="@xml/device_filter" />

**Comment by BedrettinOrtak** [comment]
<intent-filter>
   <action android:name="android.hardware.usb.action.USB_DEVICE_ATTACHED" />
</intent-filter>


<intent-filter>
   <action android:name="android.intent.action.VIEW" />
   <category android:name="android.intent.category.DEFAULT" />
   <category android:name="android.intent.category.BROWSABLE" />
   <data android:scheme="lxm"/>
</intent-filter>


<intent-filter>
    <action android:name="android.intent.action.WEB_SEARCH" />
    <category android:name="android.intent.category.DEFAULT" />
    <category android:name="android.intent.category.LAUNCHER" />
</intent-filter>


<meta-data android:name="android.hardware.usb.action.USB_DEVICE_ATTACHED"
    android:resource="@xml/device_filter" />

**Comment by BedrettinOrtak** [comment]
``
<intent-filter>
   <action android:name="android.hardware.usb.action.USB_DEVICE_ATTACHED" />
</intent-filter>


<intent-filter>
   <action android:name="android.intent.action.VIEW" />
   <category android:name="android.intent.category.DEFAULT" />
   <category android:name="android.intent.category.BROWSABLE" />
   <data android:scheme="lxm"/>
</intent-filter>


<intent-filter>
    <action android:name="android.intent.action.WEB_SEARCH" />
    <category android:name="android.intent.category.DEFAULT" />
    <category android:name="android.intent.category.LAUNCHER" />
</intent-filter>


<meta-data android:name="android.hardware.usb.action.USB_DEVICE_ATTACHED"
    android:resource="@xml/device_filter" />

**Comment by BedrettinOrtak** [comment]
[intent-filter.zip](https://github.com/kivy/buildozer/files/10736899/intent-filter.zip)
of course

**Comment by RobertFlatt** [comment]
> AAPT: error: resource xml/device_filter (aka io.unsigned.sideband:xml/device_filter) not found.

I don't see where the buildozer.spec adds the `device_filter.xml` resource
<https://github.com/markqvist/Sideband/tree/main/sbapp/patches>

**Comment by BedrettinOrtak** [comment]
what can ı do?

**Comment by RobertFlatt** [comment]
Search in buildozer.spec for resources
Probably should be using the latest Buildozer (1.5) to generate the .spec
