### ISSUE TITLE
Error While Building Kivy App on colab

### ISSUE THREAD

**Issue by yaitskeshav** [kivy/buildozer#1565]
### Versions

* Python: Python 3.8.10
* OS:  Using Google Colab
* Buildozer:  1.5.0

### Description

I am trying to build a kivy app using buildozer on colab. I have successfully built the app with same source code on 11 Feb 2023. But I am getting error on 14 Feb 2023. As I am unable to build the app, I am unable to push the new update to my already built app.

### buildozer.spec
Command:
```sh
 buildozer command ran:  buildozer -v android debug
```

Spec file:
```
https://drive.google.com/file/d/1F8H7KOl_z4jYbVEDHd7cGdWTZ0R5PDHI/view?usp=share_link
```

### Logs

```
https://drive.google.com/file/d/1b1SpBkthL78wdnouoqmPk0c_oupxU8yn/view?usp=sharing
```
Pasted link so that it should look clean. 

Here's the link of colab : https://colab.research.google.com/drive/1NXcfXkLTOltj5sAvzTOisgkrZRo1SfjA?usp=sharing

**Comment by misl6** [comment]
Hi @yaitskeshav !

As said on Discord, can you try to use `pip install -U cython` instead of `pip install cython==0.29.19` ?

**Comment by yaitskeshav** [comment]
Yes. this solved the problem.
