### ISSUE TITLE
Error While Building Kivy aab File on Colab

### ISSUE THREAD

**Issue by tahircankzn** [kivy/buildozer#1572]
### Versions

* Python: Unknown
* OS: Colab
* Buildozer:Unknown

### Description

I am trying to build a kivy app using buildozer on colab. I have successfully built the app with same source code . But I am getting error . As I am unable to build the app, I am unable to push the new update to my already built app.How can i find out python version and buildozer version?.I created aab file for google play but the same process is not working now.

### buildozer.spec
Command:
```
!buildozer -v android release
```

Spec file:
```
https://drive.google.com/file/d/1ZIrS4AapVj0VjY9KR2DRuaJa-OHwVZsK/view?usp=sharing
```

### Logs

```
https://drive.google.com/file/d/1CvOKfgZAXZJK4_Na1DRyaGu-YUZHgZFi/view?usp=sharing
```
Here's the link of colab : https://colab.research.google.com/drive/1j7ogS9WFki5vXLEaRXxbVZyruzx5y31A#scrollTo=9BeUroOJYdDM

**Comment by misl6** [comment]
Hi @tahircankzn !

You should exclude or remove files which are not intended to stay into your app package.

As an example, the file named `/content/.buildozer/android/app/drive/MyDrive/python/video indirme/video indirme.py` have syntax error in it:

```
Compiling '/content/.buildozer/android/app/drive/MyDrive/python/video indirme/video indirme.py'...
***   File "/content/.buildozer/android/app/drive/MyDrive/python/video indirme/video indirme.py", line 2
    Microsoft Visual Studio Solution File, Format Version 12.00
              ^
SyntaxError: invalid syntax
```

**Comment by kavi7775** [comment]
> ### Versions
> 
> * Python: Unknown
> * OS: Colab
> * Buildozer:Unknown
> 
> ### Description
> 
> I am trying to build a kivy app using buildozer on colab. I have successfully built the app with same source code . But I am getting error . As I am unable to build the app, I am unable to push the new update to my already built app.How can i find out python version and buildozer version?.I created aab file for google play but the same process is not working now.
> 
> ### buildozer.spec
> Command:
> ```
> !buildozer -v android release
> ```
> 
> Spec file:
> ```
> https://drive.google.com/file/d/1ZIrS4AapVj0VjY9KR2DRuaJa-OHwVZsK/view?usp=sharing
> ```
> 
> ### Logs
> 
> ```
> https://drive.google.com/file/d/1CvOKfgZAXZJK4_Na1DRyaGu-YUZHgZFi/view?usp=sharing
> ```
> Here's the link of colab : https://colab.research.google.com/drive/1j7ogS9WFki5vXLEaRXxbVZyruzx5y31A#scrollTo=9BeUroOJYdDM


Did you solve this?

**Comment by tahircankzn** [comment]
> > ### Versiyonlar
> > 
> > * Python: Bilinmiyor
> > * İşletim Sistemi: Colab
> > * Buildozer:Bilinmiyor
> > 
> > ### Tanım
> > colab üzerinde buildozer kullanarak bir kivy uygulaması oluşturmaya çalışıyorum. Uygulamayı aynı kaynak koduyla başarıyla oluşturdum. Ama hata alıyorum. Uygulamayı oluşturamadığım için, zaten oluşturulmuş uygulamama yeni güncellemeyi aktaramıyorum. Python sürümünü ve buildozer sürümünü nasıl öğrenebilirim? Google play için aab dosyası oluşturdum ancak aynı işlem şu anda çalışmıyor .
> > ### buildozer.spec
> > Emretmek:
> > ```
> > !buildozer -v android release
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Özel dosya:
> > ```
> > https://drive.google.com/file/d/1ZIrS4AapVj0VjY9KR2DRuaJa-OHwVZsK/view?usp=sharing
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ### Kütükler
> > ```
> > https://drive.google.com/file/d/1CvOKfgZAXZJK4_Na1DRyaGu-YUZHgZFi/view?usp=sharing
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > İşte colab'ın bağlantısı: https://colab.research.google.com/drive/1j7ogS9WFki5vXLEaRXxbVZyruzx5y31A#scrollTo=9BeUroOJYdDM
> 
> Bunu çözdün mü?

Yes , I solved.
