### ISSUE TITLE
(Python) Libraries with Buildozer

### ISSUE THREAD

**Issue by sereksim** [kivy/buildozer#1584]
Is it possible to build a kivy app with buildozer that contains a .pyd-library or does buildozer support only .py-files? Is there maybe another way to include a (dynamic) library with the App?

**Comment by misl6** [comment]
Hi @sereksim !

Kivy itself is not plain-python, but runs on iOS and Android. (packaged via `buildozer`).
But, you will need a recipe to cross-compile your non-plain python package, unless one already exists.

**Comment by sereksim** [comment]
Hey @misl6, thanks for your quick response :)

I did not completely understand your answer. You said Kivy is not plain python (probably because it uses .kv files for its graphics). Does that mean it is completely impossible to use python libraries with Kivy? On windows I could use my library without any problems, so I think my problem is more with buildozer than with Python or Kivy.

If I have a Kivy app which runs on windows and includes a python library (.pyd), is it possible to use the same library with the Kkivy app on android?

How could I create such a recipe so the cross-compilation to an android package would work? Is there maybe some documentation on this topic somewhere?
