### ISSUE TITLE
Forgets to stop somewhat RAM intensive Java application. (My laptop kept running out of RAM. xD)

### ISSUE THREAD

**Issue by Red-exe-Engineer** [kivy/buildozer#1586]
### Versions

* Python: 3.10.10
* OS: Arch Linux
* Buildozer: 1.5.0

### Description

Just building an app, the Java application should probably be stopped to conserve RAM on potato computers like mine.
 
[ram-2023-04-05_23.01.47.webm](https://user-images.githubusercontent.com/90420989/230231659-b81b080a-0d25-4c63-a630-dde1dd7bab95.webm)

**Comment by T-Dynamos** [comment]
Use swap space. https://www.tecmint.com/create-a-linux-swap-file/
I also used to build on a 2GB ram computer with swap space.

**Comment by Julian-O** [comment]
It isn't clear to me what Java app you are stopping and whether it is necessary for Buildozer. Are you saying the build is over, and the Java app is still running? Can you get the full command line of the task?

**Comment by Red-exe-Engineer** [comment]
> It isn't clear to me what Java app you are stopping and whether it is necessary for Buildozer. Are you saying the build is over, and the Java app is still running? Can you get the full command line of the task?

I don't have that stuff installed anymore as I've had to reinstall my operating system and don't have a lot of free time now, but I can tell you that Buildozer did complete.

**Comment by Julian-O** [comment]
I am going to close this as Can't Repro because it isn't clear that this is related to Buildozer directly.

However, if anyone else has these symptoms, please let us know.
