### ISSUE TITLE
buildozer, kivy, linux, virtualbox

### ISSUE THREAD

**Issue by godsegg** [kivy/buildozer#1589]
Я пытаюсь собрать kivy на виртуальной машине, и когда я ввожу последнюю команду, я получаю эту ошибку:

# Command failed: ['/usr/bin/python3', '-m', 'pythonforandroid.toolchain', 'create', '--dist_name=myapp', '--bootstrap=sdl2', '--requirements=python3,kivy', '--arch=arm64-v8a', '--arch=armeabi-v7a', '--copy-libs', '--color=always', '--storage-dir=/home/linuks/Рабочий стол/.buildozer/android/platform/build-arm64-v8a_armeabi-v7a', '--ndk-api=21', '--ignore-setup-py', '--debug']
# ENVIRONMENT:
# SHELL = '/bin/bash'
# SESSION_MANAGER = 'local/linuks-VirtualBox:@/tmp/.ICE-unix/1137,unix/linuks-VirtualBox:/tmp/.ICE-unix/1137'
# QT_ACCESSIBILITY = '1'
# COLORTERM = 'truecolor'
# XDG_CONFIG_DIRS = '/etc/xdg/xdg-ubuntu:/etc/xdg'
# SSH_AGENT_LAUNCHER = 'gnome-keyring'
# XDG_MENU_PREFIX = 'gnome-'
# GNOME_DESKTOP_SESSION_ID = 'this-is-deprecated'
# LC_ADDRESS = 'be_BY.UTF-8'
# GNOME_SHELL_SESSION_MODE = 'ubuntu'
# LC_NAME = 'be_BY.UTF-8'
# SSH_AUTH_SOCK = '/run/user/1000/keyring/ssh'
# XMODIFIERS = '@im=ibus'
# DESKTOP_SESSION = 'ubuntu'
# LC_MONETARY = 'be_BY.UTF-8'
# GTK_MODULES = 'gail:atk-bridge'
# PWD = '/home/linuks/Рабочий стол'
# LOGNAME = 'linuks'
# XDG_SESSION_DESKTOP = 'ubuntu'
# XDG_SESSION_TYPE = 'wayland'
# SYSTEMD_EXEC_PID = '1161'
# XAUTHORITY = '/run/user/1000/.mutter-Xwaylandauth.DXJC31'
# HOME = '/home/linuks'
# USERNAME = 'linuks'
# IM_CONFIG_PHASE = '1'
# LC_PAPER = 'be_BY.UTF-8'
# LANG = 'ru_RU.UTF-8'
# LS_COLORS = 'rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=00:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.zst=01;31:*.tzst=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.wim=01;31:*.swm=01;31:*.dwm=01;31:*.esd=01;31:*.jpg=01;35:*.jpeg=01;35:*.mjpg=01;35:*.mjpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.webp=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=00;36:*.au=00;36:*.flac=00;36:*.m4a=00;36:*.mid=00;36:*.midi=00;36:*.mka=00;36:*.mp3=00;36:*.mpc=00;36:*.ogg=00;36:*.ra=00;36:*.wav=00;36:*.oga=00;36:*.opus=00;36:*.spx=00;36:*.xspf=00;36:'
# XDG_CURRENT_DESKTOP = 'ubuntu:GNOME'
# VTE_VERSION = '6800'
# WAYLAND_DISPLAY = 'wayland-0'
# GNOME_TERMINAL_SCREEN = '/org/gnome/Terminal/screen/de60e4c2_dbc2_46cd_a90a_5261b405b390'
# GNOME_SETUP_DISPLAY = ':1'
# LESSCLOSE = '/usr/bin/lesspipe %s %s'
# XDG_SESSION_CLASS = 'user'
# TERM = 'xterm-256color'
# LC_IDENTIFICATION = 'be_BY.UTF-8'
# LESSOPEN = '| /usr/bin/lesspipe %s'
# USER = 'linuks'
# GNOME_TERMINAL_SERVICE = ':1.162'
# DISPLAY = ':0'
# SHLVL = '1'
# LC_TELEPHONE = 'be_BY.UTF-8'
# QT_IM_MODULE = 'ibus'
# LC_MEASUREMENT = 'be_BY.UTF-8'
# XDG_RUNTIME_DIR = '/run/user/1000'
# LC_TIME = 'be_BY.UTF-8'
# XDG_DATA_DIRS = '/usr/share/ubuntu:/usr/local/share/:/usr/share/:/var/lib/snapd/desktop'
# PATH = '/home/linuks/.buildozer/android/platform/apache-ant-1.9.4/bin:/home/linuks/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/snap/bin'
# GDMSESSION = 'ubuntu'
# DBUS_SESSION_BUS_ADDRESS = 'unix:path=/run/user/1000/bus'
# LC_NUMERIC = 'be_BY.UTF-8'
# OLDPWD = '/home/linuks'
# _ = '/usr/local/bin/buildozer'
# PACKAGES_PATH = '/home/linuks/.buildozer/android/packages'
# ANDROIDSDK = '/home/linuks/.buildozer/android/platform/android-sdk'
# ANDROIDNDK =
'/home/linuks/.buildozer/android/platform/android-ndk-r25b'
# ANDROIDAPI = '31'
# ANDROIDMINAPI = '21'
#
# Buildozer failed to execute the last command
# The error might be hidden in the log above this error
# Please read the full log, and search for it before
# raising an issue with buildozer itself.
# In case of a bug report, please add a full log with log_level = 2

**Comment by RobertFlatt** [comment]
The error message is further up the log file.

For a better response ask in one of the user groups https://discord.gg/u8U3GNQ4 or https://groups.google.com/g/kivy-users and post the full log as a .txt file.
