### ISSUE TITLE
[FeatureRequest] bootstrap the build environment.

### ISSUE THREAD

**Issue by cederom** [kivy/buildozer#1594]
Hello world :-)

I have problems building my application, even worse, I cannot build kivy examples/android right now, tried on various platforms and architectures as reported in other issues :-(

In my projects I usually provide a bootstrap script that sets up the build environment (compilers, programs, libraries, dependencies, etc) on a bare metal target OS installation, so after bootstrap developer can go directly to work on a coherent environment with other developers.

I think such bootsrap (i.e. `buildozer bootstrap`) would be very handy here.

No problems with outdated documentation, different packages versions, the same questions asked on the mailing lists, etc.

I am willing to help create such functionality with the development team acceptance and support :-)

**Comment by misl6** [comment]
Hi @cederom !

What you're asking is already a thing on `python-for-android`, at least when using macOS (even if is experimental, fixed the majority of support-related issues, and could be extended to cover more cases).

See: https://github.com/kivy/python-for-android/blob/develop/pythonforandroid/prerequisites.py

This is run by default, when needed, and the user does not need to specifically ask to boostrap the build environment.

**Comment by cederom** [comment]
Okay I will remove brew, create venv from system python, and see what happens :-)

**Comment by cederom** [comment]
Okay, so prerequisites cannot find `brew`, and his can be fixed easily, I will close this issue and open dedicated issues related with prerequisites so it bootstraps everything :-)

Thank you for the quick response and hints @misl6 :-)

**Comment by cederom** [comment]
brew stuff reported here https://github.com/kivy/python-for-android/issues/2777.
