### ISSUE TITLE
macOS homebrew python@3.9 and python@3.10 pip ssl blocker.

### ISSUE THREAD

**Issue by cederom** [kivy/buildozer#1595]
### Versions

* Python: `3.9.16` / `3.10.11`.
* OS: `macOS 13.3.1 ARM/M1`.
* Buildozer: `1.5.0`.
* Homebrew: `4.0.13-28-g4fe3436`.

### Description

With recent version of HomeBrew Python 3.9 and 3.10 is not the latest release anymore and its pip does not seem to have ssl built in that prevents from fetching dependencies during `buildozer android debug`. Python 3.11 is not yet supported by Kivy. I need macOS in order to crosscompile for iOS (and Android ). Any hints appreciated :-)

Solution presented in the "latest" docs [1] seems outdated, openssl is installed, additionally homebrew new location is `/opt/homebrew` not `/usr/local/opt`.

[1] https://python-for-android.readthedocs.io/en/latest/troubleshooting/#sslerror-can-t-connect-to-https-url-because-the-ssl-module-is-not-available

**Comment by cederom** [comment]
I have also asked for help on HomeBrew project (https://github.com/Homebrew/brew/issues/15234), I can see that this pip + ssl problem happened before, maybe they will know the best solution :-)

**Comment by misl6** [comment]
Hi @cederom !

Well, that definitely looks like an issue on `homebrew` + `pyvenv` side (likely due to something in your environment).

The guide you mentioned is referring to `ssl` support missing for `hostpython3`, which is now handled via `prerequisites.py` for both Intel and Apple Silicon macs (https://github.com/kivy/python-for-android/blob/8cae1f63e4ced626e9989f8611804a2b8c22d0e8/pythonforandroid/prerequisites.py#L267-L290)

Feel free to jump in on our [Discord](https://chat.kivy.org) chat (#android-support channel) and ask for help.

**Comment by cederom** [comment]
Thank you @misl6 :-)
* Please do not close this issue until problem is resolved.
* Prerequisites is only a partial solution, because it will not work on a bare install machine out of the box, homebrew needs to be installed in the first place + packages in homebrew + environmental variables configuration for each package in homebrew (I have reported a feature request in homebrew project so `brew shellenv` would provide all necessary variables to be fed into `~/.profile`. 
* Additional bootstrap needs to be performed before prerequisites is even available. This is complex task as it turns out, incoherent at this point, requires reading the documentation, in a perfect situation it should be scripted and performed automatically to provide coherent build environment on different machines/OS. This is my point that I have pointed in a dedicated issue.
* In a perfect world we (the  Kivy project) would want to provide virtual machine images with all packages and environment setup ready to just git clone the application and build it with one command (i.e. `buildozer android debug` / `buildozer android release`).
