### ISSUE TITLE
I have PermissionError: [Errno 13] Permission denied: '/data/.cache'? on android kivy application

### ISSUE THREAD

**Issue by bokras** [kivy/buildozer#1596]
When I run my kivy app on android I get the error: " PermissionError: [Errno 13] Permission denied: '/data/.cache'"
Python version: 3.6.9
Kivy: (2.0.0)
Kivy-Garden: (0.1.5)
buildozer: (1.5.1.dev0)
Cython: (0.29.34)
OS: XUbuntu 18.04

**buildozer.spec:**

[buidozer_spec.txt](https://github.com/kivy/buildozer/files/11303934/buidozer_spec.txt)

**Logcat android:**

04-23 14:41:12.798  3353  3392 I python  :  Traceback (most recent call last):
04-23 14:41:12.799  3353  3392 I python  :    File "/home/bodya/program_nastena/.buildozer/android/platform/build-arm64-v8a_armeabi-v7a/build/other_builds/python3/armeabi-v7a__ndk_target_22/python3/Lib/pathlib.py", line 1323, in mkdir
04-23 14:41:12.799  3353  3392 I python  :  FileNotFoundError: [Errno 2] No such file or directory: '/data/.cache/fakeua'
04-23 14:41:12.799  3353  3392 I python  :  
04-23 14:41:12.799  3353  3392 I python  :  During handling of the above exception, another exception occurred:
04-23 14:41:12.799  3353  3392 I python  :  
04-23 14:41:12.799  3353  3392 I python  :  Traceback (most recent call last):
04-23 14:41:12.799  3353  3392 I python  :    File "/home/bodya/program_nastena/.buildozer/android/app/main.py", line 8, in <module>
04-23 14:41:12.800  3353  3392 I python  :    File "/home/bodya/program_nastena/.buildozer/android/platform/build-arm64-v8a_armeabi-v7a/build/python-installs/myapp/armeabi-v7a/fake_user_agent/__init__.py", line 3, in <module>
04-23 14:41:12.800  3353  3392 I python  :    File "/home/bodya/program_nastena/.buildozer/android/platform/build-arm64-v8a_armeabi-v7a/build/python-installs/myapp/armeabi-v7a/fake_user_agent/user_agent.py", line 30, in <module>
04-23 14:41:12.800  3353  3392 I python  :    File "/home/bodya/program_nastena/.buildozer/android/platform/build-arm64-v8a_armeabi-v7a/build/python-installs/myapp/armeabi-v7a/fake_user_agent/settings.py", line 12, in <module>
04-23 14:41:12.800  3353  3392 I python  :    File "/home/bodya/program_nastena/.buildozer/android/platform/build-arm64-v8a_armeabi-v7a/build/other_builds/python3/armeabi-v7a__ndk_target_22/python3/Lib/pathlib.py", line 1327, in mkdir
04-23 14:41:12.801  3353  3392 I python  :    File "/home/bodya/program_nastena/.buildozer/android/platform/build-arm64-v8a_armeabi-v7a/build/other_builds/python3/armeabi-v7a__ndk_target_22/python3/Lib/pathlib.py", line 1323, in mkdir
04-23 14:41:12.801  3353  3392 I python  :  PermissionError: [Errno 13] Permission denied: '/data/.cache'
04-23 14:41:12.801  3353  3392 I python  : Python for android ended.

**Comment by RobertFlatt** [comment]
On modern Android devices `/data/.cache` is not readable or writeable.
Use https://github.com/Android-for-Python/Android-for-Python-Users#app-storage-directory , no manifest permissions are required.
