### ISSUE TITLE
File not found error: aidl

### ISSUE THREAD

**Issue by jebko0429** [kivy/buildozer#1597]
FileNotFoundError: [Errno 2] No such file or directory: '/.buildozer/android/platform/android-sdk/build-tools/34.0.0-rc3/aidl'

**Comment by RobertFlatt** [comment]
Buildozer's configuration is incomplete. 

The usual error message and fix is https://github.com/Android-for-Python/Android-for-Python-Users#aidl-not-found.

**Comment by RobertFlatt** [comment]
> we use the issue tracker exclusively for bug reports and feature requests. However, this issue appears to be a support request. Please use our [support channels](https://github.com/kivy/buildozer#support) to get help with the project.
Let us know if this comment was made in error, and we'll be happy to reopen the issue.

If you tried this https://github.com/kivy/buildozer/issues/1597#issuecomment-1521131565 and it didn't help, contact us on [support channels](https://github.com/kivy/buildozer#support).
