### ISSUE TITLE
Apk not Asking for permission 

### ISSUE THREAD

**Issue by ghost** [kivy/buildozer#1598]
i've a problem. i made a kivymd app. i used pytube in my app to download videos and it was working before converting it to apk.I gave all necessary permission in buildozer.spec file but after installing my apk when i try to download a video it’s give me an error '<urlopen error [Errno 7] No address  associated with hostname>'. even my apk don’t asks for any permission. please help me

**Comment by RobertFlatt** [comment]
This is a usage question, you should ask in the user groups https://discord.gg/pvUmAFyT

You have two (or more) separate issues. You can read about run time/user permissions here https://github.com/Android-for-Python/Android-for-Python-Users#app-permissions
