### ISSUE TITLE
Doesnt install sdkmanager and cant find it when manually installed

### ISSUE THREAD

**Issue by 123Coder231youneverknow** [kivy/buildozer#1603]
crampage@DESKTOP-4J7SHCO:~$ cd Rampage\ raiders/
rampage@DESKTOP-4J7SHCO:~/Rampage raiders$ ls
background.png  bin  buildozer.spec  enemy.png  grass.png  main.py  player.png  wall.png
rampage@DESKTOP-4J7SHCO:~/Rampage raiders$ buildozer android debug
# Check configuration tokens
# Ensure build layout
# Check configuration tokens
# Preparing build
# Check requirements for android
# Search for Git (git)
#  -> found at /usr/bin/git
# Search for Cython (cython)
#  -> found at /home/rampage/.local/bin/cython
# Search for Java compiler (javac)
#  -> found at /usr/lib/jvm/java-11-openjdk-amd64/bin/javac
# Search for Java keytool (keytool)
#  -> found at /usr/lib/jvm/java-11-openjdk-amd64/bin/keytool
# Install platform
# Run ['git', 'config', '--get', 'remote.origin.url']
# Cwd /home/rampage/Rampage raiders/.buildozer/android/platform/python-for-android
https://github.com/kivy/python-for-android.git
# Run ['git', 'branch', '-vv']
# Cwd /home/rampage/Rampage raiders/.buildozer/android/platform/python-for-android
* master 56bf7335 [origin/master] Merge pull request #2747 from misl6/release-2023.02.10
# Run ['/usr/bin/python3', '-m', 'pip', 'install', '-q', '--user', 'appdirs', 'colorama>=0.3.3', 'jinja2', 'sh>=1.10, <2.0; sys_platform!="nt"', 'pep517', 'toml', 'packaging']
# Cwd None
# Apache ANT found at /home/rampage/.buildozer/android/platform/apache-ant-1.9.4
# Android SDK found at /home/rampage/.buildozer/android/platform/android-sdk
# Recommended android's NDK version by p4a is: 25b
# Android NDK found at /home/rampage/.buildozer/android/platform/android-ndk-r25b
# Installing/updating SDK platform tools if necessary
# Check configuration tokens
# sdkmanager path "/home/rampage/.buildozer/android/platform/android-sdk/tools/bin/sdkmanager" does not exist, sdkmanager is notinstalled
rampage@DESKTOP-4J7SHCO:~/Rampage raiders$ cd ..
rampage@DESKTOP-4J7SHCO:~$ /home/rampage/.buildozer/android/platform/android-sdk/tools/bin/sdkmanager
-bash: /home/rampage/.buildozer/android/platform/android-sdk/tools/bin/sdkmanager: Is a directory
rampage@DESKTOP-4J7SHCO:~$ cd /home/rampage/.buildozer/android/platform/android-sdk/tools/bin/sdkmanager
rampage@DESKTOP-4J7SHCO:~/.buildozer/android/platform/android-sdk/tools/bin/sdkmanager$

i have to install that manually and i did but it just cant find it, anyone can help?, also my main.py is a pygame project that requires .png for the textures but i dont know if thats compatible 

thats 2 questions, bye

**Comment by misl6** [comment]
Hi @123Coder231youneverknow !

Can you please confirm your OS?

**Comment by 123Coder231youneverknow** [comment]
> Hi @123Coder231youneverknow !
> 
> Can you please confirm your OS?

Yes ubuntu WSL  via windows

**Comment by RobertFlatt** [comment]
https://github.com/Android-for-Python/Android-for-Python-Users#sdkmanager-is-not-installed

**Comment by swalter972** [comment]
Edit : did not work on my system, always getting the sdk manager error : "sdkmanager path "/home/blablabla/.buildozer/android/platform/android-sdk/tools/bin/sdkmanager" does not exist, sdkmanager is notinstalled"

You have to go in WSL to your home directoray etc and unzip the sdk then rerun buildozer

**Comment by RobertFlatt** [comment]
Not a known behavior.
Was `~/.buildozer` deleted before rebuilding?

**Comment by swalter972** [comment]
🤔 I think so but which one ? The one in the WSL or the one in the windows kivy project ?

**Comment by RobertFlatt** [comment]
> which one

`~/.buildozer`   (the `~` is important)

Also `<project>/.buildozer` can be deleted with `buildozer appclean`

> The one in the WSL or the one in the windows kivy project ?

Does this mean you are building on the Windows partition? Don't do that!
https://github.com/Android-for-Python/Android-for-Python-Users#install
And yes if there is a legacy `<project>/.buildozer`  on the Windows partition, delete that before copying to Linux.

**Comment by swalter972** [comment]
Thanks ! 

I did that, 

strange that I have to appclean though, deleting more than 1Go just for new dependencies 

I did : 

`requirements = python3,kivy,pillow,plyer,kivymd`

Very hard to get working on file manager in android, got it but impossible as it seems with sdk 33 and other file than media

**Comment by RobertFlatt** [comment]
Yes, Android (10+) uses uris not files. A file manager does not know about these.

https://github.com/Android-for-Python/Android-for-Python-Users#android-storage

The simple approach is to use use the Android Chooser (see link above). 
Or write your own picker, for example the music picker here https://github.com/Android-for-Python/music_service_example

Either way these are support issues and off topic here.
