### ISSUE TITLE
Is there a way to prevent re-downloading the same dependencies while making a new project

### ISSUE THREAD

**Issue by mmdmoa** [kivy/buildozer#1604]
Guys I created a new project, 
and buildozer is re-downloading everything that I'm sure it downloaded before
things like sdl_ttf, sld_mixer, and other stuff
I think it's keeping those files in my project directory, 
is there a way to bypass that and make all of those repositories and dependencies go in the ~/.buildozer folder instead of current project's .buildozer?

**Comment by RobertFlatt** [comment]
No

**Comment by mmdmoa** [comment]
Copying it to my new projects saves me the trouble of downloading the dependencies again, but thanks anyway lol
