### ISSUE TITLE
Bug when using the argument `extra_manifest_application_arguments`

### ISSUE THREAD

**Issue by Neizvestnyj** [kivy/buildozer#1611]
### Versions

* Python: 3.9.15
* OS: Debian-11.6
* Buildozer: 1.5.0
* kivy: 2.2.0
* p4a: develop

I previously used in **buildozer.spec** _(1.4.0)_
```sh
android.extra_manifest_application_arguments = ./android/extra_manifest_application_arguments.xml
``` 
in **extra_manifest_application_arguments.xml**  file
```
android:requestLegacyExternalStorage="true"
```
but now in **AndroidManifeset.xml** the values were added as follows (in double quotes): `"android:requestLegacyExternalStorage=\"true\" "`  and this leads to a bug:
```shell
lineNumber: 65; columnNumber: 18; Element type "application" must be followed by either attribute specifications, ">" or "/>".
```

**Comment by DexerBR** [comment]
I also came across this issue, however it seems to be fixed in the master branch!

**Comment by skarl-api** [comment]
persist

**Comment by grekichi** [comment]
Hi there !

Have this problem already fixed ?

I have same problem in extra_manifest_xml as follows,

`"<uses-feature android:name=...>"` in **AndroidManifest.xml**

How to remove double quote ?

**Comment by grekichi** [comment]
@snuq 

Thanks for your advice.

I tried your method and success !
