### ISSUE TITLE
command error buildozer android debug 

### ISSUE THREAD

**Issue by Siam-Rayhan1** [kivy/buildozer#1624]
I'm getting error while trying to build apk using buildozer by Github Action. 
Here's my full log. Please 
[logs_13.zip](https://github.com/kivy/buildozer/files/11928876/logs_13.zip)
 help me

**Comment by misl6** [comment]
Hi @Siam-Rayhan1 !

The issue is likely related to the Cython version available in the docker image.
You should consider upgrading it (or using a non dockerized environment ATM)

Feel free to ask for help on our support channels!

**Comment by Siam-Rayhan1** [comment]
> Hi @Siam-Rayhan1 !
> 
> The issue is likely related to the Cython version available in the docker image. You should consider upgrading it (or using a non dockerized environment ATM)
> 
> Feel free to ask for help on our support channels!

How do i upgrade Cython version sir?

**Comment by Siam-Rayhan1** [comment]
@misl6 I tried this but still getting error. 

name: CI

on:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Get Date
        id: get-date
        run: |
          echo "::set-output name=date::$(/bin/date -u "+%Y%m%d")"

      - name: Cache Buildozer directory
        uses: actions/cache@v2
        with:
          path: .buildozer
          key: ${{ runner.os }}-{{ steps.get-date.outputs.date }}-${{ hashFiles('buildozer.spec') }}

      - name: Upgrade Cython
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
          

      - name: Build with Buildozer
        uses: ArtemSBulgakov/buildozer-action@v1
        id: buildozer
        with:
          command: buildozer android debug
          buildozer_version: master
          
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: package
          path: ${{ steps.buildozer.outputs.filename }}

**Comment by T-Dynamos** [comment]
@Siam-Rayhan1 You can try this workflow:
```
name: Build APK
on: [push,pull_request]

jobs:
  build-android:
    name: Build for Android
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build with Buildozer
        run: |
          pip3 install --user --upgrade buildozer Cython virtualenv
          export PATH=$PATH:~/.local/bin/
          export APP_ANDROID_ACCEPT_SDK_LICENSE=1
          export BUILDOZER_WARN_ON_ROOT=0
          sudo apt update
          sudo apt install -y git zip unzip openjdk-17-jdk python3-pip autoconf libtool pkg-config zlib1g-dev libncurses5-dev libncursesw5-dev libtinfo5 cmake libffi-dev libssl-dev
          cd ${{ github.workspace }}
          buildozer android debug
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: package
          path: bin/*.apk
```

**Comment by Siam-Rayhan1** [comment]
> @Siam-Rayhan1 You can try this workflow:
> 
> ```
> name: Build APK
> on: [push,pull_request]
> 
> jobs:
>   build-android:
>     name: Build for Android
>     runs-on: ubuntu-latest
>     steps:
>       - name: Checkout
>         uses: actions/checkout@v2
>       - name: Build with Buildozer
>         run: |
>           pip3 install --user --upgrade buildozer Cython virtualenv
>           export PATH=$PATH:~/.local/bin/
>           export APP_ANDROID_ACCEPT_SDK_LICENSE=1
>           export BUILDOZER_WARN_ON_ROOT=0
>           sudo apt update
>           sudo apt install -y git zip unzip openjdk-17-jdk python3-pip autoconf libtool pkg-config zlib1g-dev libncurses5-dev libncursesw5-dev libtinfo5 cmake libffi-dev libssl-dev
>           cd ${{ github.workspace }}
>           buildozer android debug
>       - name: Upload artifacts
>         uses: actions/upload-artifact@v2
>         with:
>           name: package
>           path: bin/*.apk
> ```

I don’t know how do i say thanks to you...man you just saved my time..i have been suffering from 3 months for this error. Thanks thanks Thanks.it works.Please give me one of your social media address i wanna stay tuned with you for any kinnda help 💖

**Comment by T-Dynamos** [comment]
@Siam-Rayhan1 You can join kivy's discord.

**Comment by Siam-Rayhan1** [comment]
> @Siam-Rayhan1 You can join kivy's discord.

Now it’s not working. I'm getting this error
```
Traceback (most recent call last):
  File "/home/runner/.local/bin/buildozer", line 8, in <module>
    sys.exit(main())
  File "/home/runner/.local/lib/python3.7/site-packages/buildozer/scripts/client.py", line 13, in main
    Buildozer().run_command(sys.argv[1:])
  File "/home/runner/.local/lib/python3.7/site-packages/buildozer/__init__.py", line 1024, in run_command
    self.target.run_commands(args)
  File "/home/runner/.local/lib/python3.7/site-packages/buildozer/target.py", line 93, in run_commands
    func(args)
  File "/home/runner/.local/lib/python3.7/site-packages/buildozer/target.py", line 103, in cmd_debug
    self.buildozer.prepare_for_build()
  File "/home/runner/.local/lib/python3.7/site-packages/buildozer/__init__.py", line 172, in prepare_for_build
    self.target.install_platform()
  File "/home/runner/.local/lib/python3.7/site-packages/buildozer/targets/android.py", line 613, in install_platform
    self._install_apache_ant()
  File "/home/runner/.local/lib/python3.7/site-packages/buildozer/targets/android.py", line 343, in _install_apache_ant
    os.makedirs(ant_dir)
  File "/opt/hostedtoolcache/Python/3.7.17/x64/lib/python3.7/os.py", line 213, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/opt/hostedtoolcache/Python/3.7.17/x64/lib/python3.7/os.py", line 213, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/opt/hostedtoolcache/Python/3.7.17/x64/lib/python3.7/os.py", line 213, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/opt/hostedtoolcache/Python/3.7.17/x64/lib/python3.7/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/root/.buildozer'
Error: Process completed with exit code 1.
```
Help me
