### ISSUE TITLE
android.add_src dont work

### ISSUE THREAD

**Issue by MininDMhvh** [kivy/buildozer#1634]
I am trying to add files to my Java project, but they are not added to the final build, I do not get any errors during the build, only when I run the application on android I get this exception jnius.jnius.JavaException: JVM exception occurred: Didn't find class "some.kivy_test.Test"
I use ubuntu 20.04, python 3.10.12.
My spec file 
```
[app]

# (str) Title of your application
title = KivyTest

# (str) Package name
package.name = kivy_test

# (str) Package domain (needed for android/ios packaging)
package.domain = com.heattheatr

# (str) Source code where the main.py live
source.dir = .

# (list) Source files to include (let empty to include all the files)
source.include_exts = py,png,jpg,jpeg,ttf,kv,mp3,so,2,6,2,1,a, java

source.include_patterns = img/*, font/*, ui/*, music/*

# (list) Application version
version = 0.0.28

# (list) Application requirements
# comma separated e.g. requirements = sqlite3,kivy
requirements = python3==3.10.11,kivy==2.1.0, jnius

# (str) Custom source folders for requirements
# Sets custom source for any requirements with recipes
# requirements.source.kivy = ../../kivy
#requirements.source.libtest = lib/libtest

# (str) Supported orientation (one of landscape, sensorLandscape, portrait or all)
orientation = portrait

# (bool) Indicate if the application should be fullscreen or not
fullscreen = 1

# (list) Permissions
android.permissions = WRITE_EXTERNAL_STORAGE

# (int) Target Android API, should be as high as possible.
android.api = 31

# (int) Minimum API your APK will support.
android.minapi = 21

# (str) Android NDK version to use
android.ndk = 25

# (bool) If True, then skip trying to update the Android sdk
# This can be useful to avoid excess Internet downloads or save time
# when an update is due and you just want to test/build your package
android.skip_update = False

# (bool) If True, then automatically accept SDK license
# agreements. This is intended for automation only. If set to False,
# the default, you will be shown the license when first running
# buildozer.
android.accept_sdk_license = True

# (str) The Android arch to build for, choices: armeabi-v7a, arm64-v8a, x86, x86_64
android.archs = arm64-v8a, armeabi-v7a

#android.add_jars = %(source.dir)s/java_lib/AJVoIP.jar
#android.add_aars = %(source.dir)s/libs_lib/*.aar

# (list) Android additionnal libraries to copy into libs/armeabi
android.add_src = %(source.dir)s/src/some/kivy_test*.java
android.add_libs_arm64_v8a = %(source.dir)s/libs/libs_arm64_v8a/*.*
android.add_libs_armeabi_v7a = %(source.dir)s/libs/libs_armeabi-v7a/*.*
#android.library_references = /home/djvu/workspace/intercom/phone/libs/libs_arm64_v8a/*.*

#android.copy_libs = 1

[buildozer]

# (int) Log level (0 = error only, 1 = info, 2 = debug (with command output))
log_level = 2

# (int) Display warning if buildozer is run as root (0 = False, 1 = True)
warn_on_root = 0

# (str) Path to build artifact storage, absolute or relative to spec file
build_dir = ./.buildozer

# (str) Path to build output (i.e. .apk, .ipa) storage
bin_dir = ./bin
```

**Comment by RobertFlatt** [comment]
It works.  For example <https://github.com/Android-for-Python/speech_recognizer_example>

Perhaps `android.add_src = %(source.dir)s/src/some/kivy_test*.java` should be `android.add_src = %(source.dir)s/src/some/kivy_test/*.java`  ?

Also check  the Java contains package statements.

In future please direct usage questions to the user groups.

**Comment by MininDMhvh** [comment]
> It works.  For example <https://github.com/Android-for-Python/speech_recognizer_example>
> 
> 
> 
> Perhaps `android.add_src = %(source.dir)s/src/some/kivy_test*.java` should be `android.add_src = %(source.dir)s/src/some/kivy_test/*.java`  ?
> 
> 
> 
> Also check  the Java contains package statements.
> 
> 
> 
> In future please direct usage questions to the user groups.

It doesn't work, there are also no error messages.

**Comment by RobertFlatt** [comment]
1) Check that you did this <https://github.com/Android-for-Python/Android-for-Python-Users#changing-buildozerspec>

2) Check that the add_src option works by trying this example https://github.com/Android-for-Python/speech_recognizer_example   (it does work)

3) If your code does not work, ask for help in the user group  https://discord.gg/9d9saEMv

**Comment by MininDMhvh** [comment]
> 1. Check that you did this https://github.com/Android-for-Python/Android-for-Python-Users#changing-buildozerspec
> 2. Check that the add_src option works by trying this example https://github.com/Android-for-Python/speech_recognizer_example   (it does work)
> 3. If your code does not work, ask for help in the user group  https://discord.gg/9d9saEMv

I tried to do this, but I still get the error that I can't find the class ` JVM exception occurred: Didn't find class "com.github.hbldh.bleak.PythonScanCallback" on path: DexPathList[[directory "."],nativeLibraryDirectories=[/system/lib, /system/lib]] java.lang.ClassNotFoundException`

![image](https://github.com/kivy/buildozer/assets/72999911/a80e07da-29a3-4f5e-8fc1-13ea4e89d6c8)

**Comment by RobertFlatt** [comment]
That `)s/` seems strange.
And the %(source.dir) is unnecessary
Do it like the example

**Comment by MininDMhvh** [comment]
> That `)s/` seems strange. And the %(source.dir) is unnecessary Do it like the example

Like this - add_src = src ?

**Comment by Julian-O** [comment]
This appears to be a support issue that has been answered.

We try to use GitHub Issues only to track work for developers to do to fix bugs and add new features to Buildozer.

This issue is being closed, because it doesn't describe a bug in Buildozer.

If you have further support questions, please don't post them here. Instead, there is a mailing list and a Discord channel to support Kivy users debugging their own systems, which should be able to help. They are linked in the [ReadMe](https://github.com/kivy/buildozer#support). For building Android apps, there is an unofficial [Buildozer Users' Guide](https://github.com/Android-for-Python/Android-for-Python-Users) that has a lot of useful debugging tips.
