### ISSUE TITLE
Build errors on OSX 10.10 (for android)

### ISSUE THREAD

**Issue by DrMoriarty** [kivy/buildozer#165]
Hello, I'm trying to build my project for android on osx yosemite and have a lot of errors during python compilation.
There is full build log: https://gist.github.com/DrMoriarty/e8816fbb3e8e287289dd
gcc 4.2.1
I tried to change gcc to 4.9.2, but no lucky. Full log: https://gist.github.com/DrMoriarty/a5421c16adf0a53d66c5
Could anybody help me?
##

**Comment by tito** [comment]
Can you give us the output of your `env` command?
Maybe you have an environemtn variable that breaks the compilation?

**Comment by DrMoriarty** [comment]
Hello! As I can see it started work well a week or two ago.
I think it was a trouble in python for android
https://github.com/kivy/python-for-android/issues/311

**Comment by AndreMiras** [comment]
This issue is 4 years old and we got recent fixes on p4a. Please try again from `develop` branch
