### ISSUE TITLE
# Command failed: ['/Users/veles/PycharmProjects/pythonProject5/venv/bin/python', '-m', 'pythonforandroid.toolchain', 'create', '--dist_name=myapp', '--bootstrap=sdl2', '--requirements=python3,kivy', '--arch=arm64-v8a', '--arch=armeabi-v7a', '--copy-libs', '--color=always', '--storage-dir=/Users/veles/PycharmProjects/pythonProject5/.buildozer/android/platform/build-arm64-v8a_armeabi-v7a', '--ndk-api=21', '--ignore-setup-py', '--debug']

### ISSUE THREAD

**Issue by 77woody77** [kivy/buildozer#1665]
Я выполнил buildozer android debug deploy run и получил следующую ошибку:
# ENVIRONMENT:
#     PATH = '/Users/veles/.buildozer/android/platform/apache-ant-1.9.4/bin:/opt/homebrew/bin:/Users/veles/PycharmProjects/pythonProject5/venv/bin:/Users/veles/.pyenv/shims:/Users/veles/.pyenv/bin:/Library/Frameworks/Python.framework/Versions/3.11/bin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Applications/VMware'
#     __CFBundleIdentifier = 'com.jetbrains.pycharm.ce'
#     SHELL = '/bin/zsh'
#     TERM = 'xterm-256color'
#     USER = 'veles'
#     FIG_JETBRAINS_SHELL_INTEGRATION = '1'
#     TMPDIR = '/var/folders/_8/w5l952hn1zz6cvqkg0p4psv00000gn/T/'
#     COMMAND_MODE = 'unix2003'
#     TERMINAL_EMULATOR = 'JetBrains-JediTerm'
#     SSH_AUTH_SOCK = '/private/tmp/com.apple.launchd.vLAbOE5em8/Listeners'
#     XPC_FLAGS = '0x0'
#     TERM_SESSION_ID = 'ba4d1cae-54d0-44a4-887f-59f55508bc21'
#     __CF_USER_TEXT_ENCODING = '0x1F5:0x0:0x0'
#     LOGNAME = 'veles'
#     LC_CTYPE = 'UTF-8'
#     XPC_SERVICE_NAME = '0'
#     HOME = '/Users/veles'
#     SHLVL = '1'
#     PWD = '/Users/veles/PycharmProjects/pythonProject5'
#     OLDPWD = '/Users/veles/PycharmProjects/pythonProject5'
#     MAMBA_EXE = '/Users/veles/.micromamba/bin/micromamba'
#     MAMBA_ROOT_PREFIX = '/Users/veles/micromamba'
#     PYENV_ROOT = '/Users/veles/.pyenv'
#     VIRTUAL_ENV = '/Users/veles/PycharmProjects/pythonProject5/venv'
#     PS1 = '(venv) %n@%m %1~ %# '
#     _ = '/Users/veles/PycharmProjects/pythonProject5/venv/bin/buildozer'
#     PACKAGES_PATH = '/Users/veles/.buildozer/android/packages'
#     ANDROIDSDK = '/Users/veles/.buildozer/android/platform/android-sdk'
#     ANDROIDNDK = '/Users/veles/.buildozer/android/platform/android-ndk-r25b'
#     ANDROIDAPI = '31'
#     ANDROIDMINAPI = '21'
# 
# Buildozer failed to execute the last command
# The error might be hidden in the log above this error
# Please read the full log, and search for it before
# raising an issue with buildozer itself.
# In case of a bug report, please add a full log with log_level = 2

**Comment by RobertFlatt** [comment]
https://github.com/Android-for-Python/Android-for-Python-Users#if-buildozer-fails-to-compile
