### ISSUE TITLE
kivy app crash

### ISSUE THREAD

**Issue by PedroBigai** [kivy/buildozer#1676]

**Comment by Julian-O** [comment]
Please do not use the Issue tracker for support requests. It is for reporting bugs in Kivy.

The readme explains:

> If you need assistance, you can ask for help on our mailing list:
>
> User Group : https://groups.google.com/group/kivy-users
> Email : kivy-users@googlegroups.com 
> We also have a Discord channel:
>
> Server : https://chat.kivy.org/
> Channel : #support
