### ISSUE TITLE
buildozer failed to debug - 

### ISSUE THREAD

**Issue by Misu4342** [kivy/buildozer#1677]
Hello,

I have an issue building my apk with buildozer.
I get the error command failed for libffi.

I have attached the log, I would really appreciate your help.

Thank you in advance

[log.txt](https://github.com/kivy/buildozer/files/12504186/log.txt)

**Comment by Julian-O** [comment]
Please do not use the Issue tracker for support requests. It is for reporting bugs in Kivy projects.

The readme explains:

> If you need assistance, you can ask for help on our mailing list:
>
> User Group : https://groups.google.com/group/kivy-users
> Email : kivy-users@googlegroups.com 
> We also have a Discord channel:
>
> Server : https://chat.kivy.org/
> Channel : #support
