### ISSUE TITLE
Failing to build apk using buildozer/kivy

### ISSUE THREAD

**Issue by Misu4342** [kivy/buildozer#1678]
Hello and nice to meet you all,

I am trying to build an apk using these methods:
https://github.com/denczo/kivy_examples
https://github.com/kivy/buildozer.git
Followed the steps from this yt video:
https://www.youtube.com/watch?v=pzsvN3fuBA0

I have encountered many errors which I managed to solve but this one that I got now, honestly it did broke my brain .

I am using buildozor on WSL 2, kivy 2.2.1, Python 3.10.12, Cython version 3.0.2

I have found 3 config.log (used the command find .buildozer/ -name config.log):

location: \\wsl.localhost\Ubuntu-22.04\home\devapp\kivy_examples\graphs\.buildozer\android\platform\build-arm64-v8a_armeabi-v7a\build\other_builds\python3\arm64-v8a__ndk_target_21\python3\android-build

file: config0.log

location: \\wsl.localhost\Ubuntu-22.04\home\devapp\kivy_examples\graphs\.buildozer\android\platform\build-arm64-v8a_armeabi-v7a\build\other_builds\libffi\arm64-v8a__ndk_target_21\libffi

file: config1.log

location: \\wsl.localhost\Ubuntu-22.04\home\devapp\kivy_examples\graphs\.buildozer\android\platform\build-arm64-v8a_armeabi-v7a\build\other_builds\hostpython3\desktop\hostpython3\native-build

file: config2.log

[buildozer.spec.txt](https://github.com/kivy/buildozer/files/12506036/buildozer.spec.txt)
[config0.log](https://github.com/kivy/buildozer/files/12506037/config0.log)
[config1.log](https://github.com/kivy/buildozer/files/12506038/config1.log)
[config2.log](https://github.com/kivy/buildozer/files/12506039/config2.log)
[Errors .txt](https://github.com/kivy/buildozer/files/12506040/Errors.txt)

could you kindly help me because it is my first time doing this and i have reached my limits, eagerly looiking forward to learn how to solve it.

Best regards

**Comment by Julian-O** [comment]
Please do not use the Issue tracker for support requests. It is for reporting bugs in Kivy projects.

The readme explains:

> If you need assistance, you can ask for help on our mailing list:
>
> User Group : https://groups.google.com/group/kivy-users
> Email : kivy-users@googlegroups.com 
> We also have a Discord channel:
>
> Server : https://chat.kivy.org/
> Channel : #support

**Comment by Misu4342** [comment]
Hello,
Thanks You for guidance
I have emailed my problema to the email recommended.

**Comment by Misu4342** [comment]
ok
