### ISSUE TITLE
Buildozer tries to install android sdk every time you try to compile an android application.

### ISSUE THREAD

**Issue by osiloke** [kivy/buildozer#169]
It does not use the global android sdk at ~/.buildozer. In order to compile a new project i have to copy .buildozer to the current path.

Buildozer 0.20-dev

**Comment by tito** [comment]
This has been fixed, it will download the sdk only if you change the ndk/sdk version in your buildozer.spec.

**Comment by MuhikaThomas** [comment]
My buildozer ain't compiling. it keeps repeating an error:

mkdir: cannot create directory ‘/media/pc_name/Projects\nProjects’: Permission denied
# Command failed: ./distribute.sh -m "kivy" -d "app_name"

**Comment by lcddrm** [comment]
The error says that it cannot create a directory because "Permission denied". Running buildozer with appropriate permissions should fix this. (Try sudo buildozer ...)

**Comment by bunmalik** [comment]
Hello! i have successfully run buildozer and had my apk. However, when I install on an android it crushes. Please could tell me the possible reason for that!
