### ISSUE TITLE
Python 3.12 doesn't support distutils

### ISSUE THREAD

**Issue by Julian-O** [kivy/buildozer#1699]
### Versions

* Python: 3.12rc2
* OS: Ubuntu
* Buildozer: master

### Description

I did an experiment; I added '3.12.0-rc.2' to the Python matrix in `test_python.yml` to see if any wave of pain is coming down the pipe.

Indeed there is:

> buildozer/targets/android.py:36: in <module>
>    from distutils.version import LooseVersion
>E   ModuleNotFoundError: No module named 'distutils'

What happened? [PEP 632](https://peps.python.org/pep-0632/#:~:text=In%20Python%203.12%2C%20distutils%20will,process%20that%20currently%20use%20distutils.) happened:

> In Python 3.12, distutils will no longer be installed by make install or any of the first-party distribution. Third-party redistributors should no longer include distutils in their bundles or repositories.

`LooseVersion` has been giving deprecation warnings anyway. Time for a replacement.

**Comment by misl6** [comment]
On https://github.com/kivy/kivy/pull/8070 we made use of `packaging.version`, as suggested by PEP632 migration advice.

**Comment by Julian-O** [comment]
In [kivy/python-for-android#2866](https://github.com/kivy/python-for-android/pull/2866), I also used `packaging.version` - `packaging` was already installed. 

In that case, I investigated the version numbers being used and confirmed they conformed to the tighter definitions of `packaging`. The library has a `LegacyVersion` and a `parse()`, so I imagine it could be made to work, but I haven't done this. So some effort to be done there. I wanted to raise the issue because I didn't have time to investigate immediately.

Also, I don't think Buildozer has `packaging` installed, put it does have `libs/version.py` . So, could use that, maybe. Except, I just checked and appears to have been copied from `packaging` at least 8 years ago.

So the task list:
* Check that in practice, the tools versions confirm to `packaging` rules.
* Figure if we need to call `parse()` or just `packaging.Version()`
* Delete the unmaintained version of the library from source code.
* Add a `packaging` dependency to `setup.py`
   * Perhaps under `[android]` extras? Doesn't seem warranted just to avoid ios developers needing to have it automatically pip installed when they don't need it.
* Update any existing clients - i.e. `android.py`
* Commit  '3.12.0-rc.2' to the matrix, to be updated to `3.12' when GitHub supports it.

**Comment by misl6** [comment]
> Also, I don't think Buildozer has packaging installed, put it does have libs/version.py . So, could use that, maybe. Except, I just checked and it appears to have been copied from packaging at least 8 years ago.

Do we really want to continue vendoring this outdated code? I do not think so. Better migrating to `packaging` IMHO, if that works for us.

**Comment by Julian-O** [comment]
> Do we really want to continue vendoring this outdated code? I do not think so. Better migrating to `packaging` IMHO, if that works for us.

I absolutely agree. My task list included:

> * Delete the unmaintained version of the library from source code.

by which I mean get rid of libs/version.py

**Comment by Bill-Robinson63** [comment]
So....  How do I make buildozer work for me now?  Quickest, easiest...

**Comment by eMPee584** [comment]
@misl6 maybe a new release should be cut that actually contains these changes, as more and more distros ship python `3.12` by default and 1.5.0 fails on all these.

> So.... How do I make buildozer work for me now? Quickest, easiest...

`pipx/pip3 install […] git+https://github.com/kivy/buildozer` will install current master branch (`1.5.1.dev0` as of now) which works with python 3.12.. @Bill-Robinson63
