### ISSUE TITLE
always show python-for-android output on failure

### ISSUE THREAD

**Issue by kived** [kivy/buildozer#170]
Buildozer should collect output from p4a and emit it on build failure. This will avoid a common complaint that an app won't build and the output merely states `Command failed`, which for some can bring back bad memories of Excel error messages such as `File not opened`. ;)

**Comment by tito** [comment]
I added a message when any command failed to execute, if the log_level was <= 1, ask for raising it then re-execute the command. If it's log_level > 1, ask the user to check the backlog. And if he want to raise an issue, include the full log as well.

Let's see if we'll have less unmeaning issue.
