### ISSUE TITLE
Feature request: buildozer not use '--user' for 'pip install ...' when  in a python venv

### ISSUE THREAD

**Issue by AJRepo** [kivy/buildozer#1736]
### Versions

* Python: Python 3.11.6
* OS: Linux (Ubuntu 23.10)
* Buildozer: Buildozer 1.5.0

### Description

The README.md Instructions state that when using a virtualenv to not use '--user'  

I followed that advice, however buildozer when calling "pip install"  does use '--user' causing errors. 

To replicate: 
1. Install a python virtual env  e.g. ` python3 -m venv /path/to/venv && cd /path/to/venv`
2. Install buildozer NOT using `--user` as per instructions in that virtual env e.g. `bin/pip3 install buildozer`
3. attempt to use buildozer

When buildozer users the `--user` flag you get errors like

`ERROR: Can not perform a '--user' install. User site-packages are not visible in this virtualenv.`
or
`ERROR: Will not install to the user site because it will lack sys.path precedence to sh`

I have a workaround as noted below. If buildozer had the ability to test to see if the '--user' flag was a problem and not use it for `pip install ... ` then it would have saved quite a bit of time in figuring out what wasn't working.  Unless that's breaking something that I'm not aware of, it would be great to have a test for being in a venv as a feature of buildozer and then not using `--user`. 

### Workaround

1. install each pip package separately using `bin/pip3 install X` where X is the resource that buildozer barfed on. 
E.g.  ['appdirs', 'colorama>=0.3.3', 'jinja2', 'sh>=1.10, <2.0; sys_platform!="win32"', 'build', 'toml', 'packaging' ] and not using the --user flag. 

2. Change `include-system-site-packages = true` in the file `pyvenv.cfg`

And then all works. 

### buildozer.spec
Command:
```sh
/path/to/venv/bin/buildozer --verbose android debug
```

Spec file:
```
Other than changing the title,name, domain, version - it's the default .spec file. 
```

### Logs

```
../bin/buildozer --verbose android debug
# Check configuration tokens
# Ensure build layout
# Check configuration tokens
# Preparing build
# Check requirements for android
# Search for Git (git)
#  -> found at /usr/bin/git
# Search for Cython (cython)
#  -> found at /usr/bin/cython
# Search for Java compiler (javac)
#  -> found at /usr/lib/jvm/java-17-openjdk-amd64/bin/javac
# Search for Java keytool (keytool)
#  -> found at /usr/lib/jvm/java-17-openjdk-amd64/bin/keytool
# Install platform
# Run ['git', 'config', '--get', 'remote.origin.url']
# Cwd /srv/afan_Documents/Software/venv/pietimer_kivy/.buildozer/android/platform/python-for-android
https://github.com/kivy/python-for-android.git
# Run ['git', 'branch', '-vv']
# Cwd /srv/afan_Documents/Software/venv/pietimer_kivy/.buildozer/android/platform/python-for-android
* master e155baf9 [origin/master] Merge pull request #2891 from misl6/release-2023.09.16
# Run ['/home/afan/Documents/Software/venv/bin/python3', '-m', 'pip', 'install', '-q', '--user', 'appdirs', 'colorama>=0.3.3', 'jinja2', 'sh>=1.10, <2.0; sys_platform!="win32"', 'build', 'toml', 'packaging']
# Cwd None
ERROR: Can not perform a '--user' install. User site-packages are not visible in this virtualenv.
# Command failed: ['/path/to/venv/bin/python3', '-m', 'pip', 'install', '-q', '--user', 'appdirs', 'colorama>=0.3.3', 'jinja2', 'sh>=1.10, <2.0; sys_platform!="win32"', 'build', 'toml', 'packaging']
...
```

**Comment by HyTurtle** [comment]
Did you activate the venv?

**Comment by Julian-O** [comment]
Buildozer checks if the `VIRTUAL_ENV` environment variable is set, and doesn't use "--user" if it is. [Also checks for Conda]

Sounds like the environment wasn't activated.

Closing as a support issue. Please let us know if that is incorrect.

**Comment by m24371845-spec** [comment]
.../698A-3DA7/LIZA_GOD_FINAL $ proot-distro login debian --bind=/storage/698A-3DA7:/mnt/liza_sd --bind=/storage/698A-3DA7/LIZA_GOD_FINAL:/mnt/liza                                              root@localhost:~# /path/to/venv/bin/buildozer --verbose android debug
bash: /path/to/venv/bin/buildozer: No such file or directory
root@localhost:~# Other than changing the title,name, domain, version - it's the default .spec file.
> ../bin/buildozer --verbose android debug
> # Check configuration tokens
> # Ensure build layout
> # Check configuration tokens
> # Preparing build
> # Check requirements for android
> # Search for Git (git)
> #  -> found at /usr/bin/git
> # Search for Cython (cython)
> #  -> found at /usr/bin/cython
> # Search for Java compiler (javac)
> #  -> found at /usr/lib/jvm/java-17-openjdk-amd64/bin/javac
> # Search for Java keytool (keytool)
> #  -> found at /usr/lib/jvm/java-17-openjdk-amd64/bin/keytool
> # Install platform
> # Run ['git', 'config', '--get', 'remote.origin.url']
> # Cwd /srv/afan_Documents/Software/venv/pietimer_kivy/.buildozer/android/platform/python-for-android
> https://github.com/kivy/python-for-android.git
> # Run ['git', 'branch', '-vv']
> # Cwd /srv/afan_Documents/Software/venv/pietimer_kivy/.buildozer/android/platform/python-for-android
> * master e155baf9 [origin/master] Merge pull request #2891 from misl6/release-2023.09.16
> # Run ['/home/afan/Documents/Software/venv/bin/python3', '-m', 'pip', 'install', '-q', '--user', 'appdirs', 'colorama>=0.3.3', 'jinja2', 'sh>=1.10, <2.0; sys_platform!="win32"', 'build', 'toml', 'packaging']
> # Cwd None
> ERROR: Can not perform a '--user' install. User site-packages are not visible in this virtualenv.
> # Command failed: ['/path/to/venv/bin/python3', '-m', 'pip', 'install', '-q', '--user', 'appdirs', 'colorama>=0.3.3', 'jinja2', 'sh>=1.10, <2.0; sys_platform!="win32"', 'build', 'toml', 'packaging']
> ...
>
