### ISSUE TITLE
Buildozer .apk file creation issue

### ISSUE THREAD

**Issue by jayece09** [kivy/buildozer#177]
When I am using requirements = kivy==master in buildozer.spec file The .apk file creation terminated with :-
*************************
Package the application
Captured version: 1.0
project.properties updated
Run "/usr/bin/python2.7 build.py --name 'My Application' --version 1.0 --package org.test.myapp --private /home/jp/Desktop/test2/.buildozer/android/app --sdk 14 --minsdk 8 --orientation landscape debug"
Cwd /home/jp/Desktop/test2/.buildozer/android/platform/python-for-android/dist/myapp
/usr/bin/python2.7: can't open file 'build.py': [Errno 2] No such file or directory
# Command failed: /usr/bin/python2.7 build.py --name 'My Application' --version 1.0 --package org.test.myapp --private /home/jp/Desktop/test2/.buildozer/android/app --sdk 14 --minsdk 8 --orientation landscape debug
************************************************************************
When I used just" kivy" as requirement it returned with multiple Cythole compilation failure. 
How to figure this out?

**Comment by Kovak** [comment]
You should run buildozer with the .spec's loglevel set to 2 so that we get full debug output.
