### ISSUE TITLE
Buiding error with docker 

### ISSUE THREAD

**Issue by MininDMhvh** [kivy/buildozer#1784]
I got thit error `
 RAN: /usr/bin/python3 '-cimport sys; from Cython.Compiler.Main import setuptools_main; sys.exit(setuptools_main());' ./kivy/core/image/img_imageio.pyx

  STDOUT:
/home/user/.local/lib/python3.10/site-packages/Cython/Compiler/Main.py:369: FutureWarning: Cython directive 'language_level' not set, using 2 for now (Py2). This will change in a later release! File: /home/user/hostcwd/.buildozer/android/platform/build-arm64-v8a_armeabi-v7a/build/other_builds/kivy/armeabi-v7a__ndk_target_22/kivy/kivy/core/image/img_imageio.pyx
  tree = Parsing.p_module(s, pxd, full_module_name)

Error compiling Cython file:
------------------------------------------------------------
...

cdef class _ImageIOInterface:
    cdef KivyImageIOProvider* _provider

    def __cinit__(self):
        self._provider = new KivyImageIOProvider()
                            ^
------------------------------------------------------------

kivy/core/image/img_imageio.pyx:330:29: Operation only allowed in c++`
I hadn't noticed this before, but after updating buildozer, I started getting these errors

**Comment by misl6** [comment]
Please refer to: https://github.com/kivy/kivy/issues/8635#issuecomment-1964701547
