### ISSUE TITLE
Buildozer not failing when source files have indentation errors

### ISSUE THREAD

**Issue by Samureus** [kivy/buildozer#181]
Not sure if this should be reported here or in python-for-android, but attaching the relevant snippets:

``` python
# Package the application
(cut)
Compiling /home/samo/Dev/Projects/kivy-android-samples/ads/adbuddiz/.buildozer/android/app/main.py ...
Sorry: IndentationError: ('expected an indented block',
('/home/samo/Dev/Projects/kivy-android-samples/ads/adbuddiz/.buildozer/android/app/main.py',
20, 12, '    AdBuddiz.showAd(PythonActivity.mActivity)\n'))
```

Buildozer will ignore the IndentationError and continue to build the APK. I believe it should abort at this point as the app will not run anyway, it will just fail with a cryptic message in logcat:

``` python
I/python  ( 6713): No main.pyo / main.py found.
```
##

**Comment by tito** [comment]
Yep, buildozer doesn't do any sanity check on your source code to ensure it is correctly formatted. Neither python -m compileall will stop if a source is not working.

**Comment by AndreMiras** [comment]
Indeed buildozer is not a Python parser
