### ISSUE TITLE
using Lottie

### ISSUE THREAD

**Issue by krolaper** [kivy/buildozer#1810]
Give working instructions on how to use Lottie for a loading scene instead of a static image.

After all, the instructions `buildozer.spec`:
- ```source.include_exts = py,png,jpg,kv,atlas,json```
- ```android.presplash_lottie = "path/to/lottie/file.json"```
- ```android.minapi = 28 or android.api = 28 (or only above 28)```
- ```p4a.branch = develop```
- ```android.enable_androidx = True```

This does not work. There will always be an error when packing.

The lottie file was created at ```https://lottiefiles.com/```

**Comment by Ahd999** [comment]
You need to make sure that tere is no work done until the app class is initialised in main.py or else your lottie won't work, what you've done are the only steps required to implement a lottie, Under most scenarios work is done before app class is initialised
