### ISSUE TITLE
subprocess.CalledProcessError: Command '['ant', 'debug']' returned non-zero exit status 1

### ISSUE THREAD

**Issue by GijsTimmers** [kivy/buildozer#183]
Hello, I'm trying to package my Kivy app into an Android APK file. I want to use buildozer for this.

I'm running Ubuntu 14.04 64-bit, with the git version of `buildozer`.
Everything seems to work, until at the end, this error appears:

```
Traceback (most recent call last):
  File "build.py", line 497, in <module>
    make_package(args)
  File "build.py", line 351, in make_package
    subprocess.check_call([ANT, arg])
  File "/usr/lib/python2.7/subprocess.py", line 540, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['ant', 'debug']' returned non-zero exit status 1
# Command failed: /usr/bin/python2.7 build.py --name Kotnetcli --version 1.2.0 --package org.gijs.kotnetcli --private /home/gijs/Scripts/mobile-kotnetcli/.buildozer/android/app --sdk 14 --minsdk 8 --orientation portrait debug
```

You can find the full log [here.](http://paste.ubuntu.com/10519919/) Sadly, I don't know how to strip the color escape codes.

**Comment by tito** [comment]
It is possibel that you need 32 bits libraries to execute the android sdk. Please retry with the latest buildozer.
