### ISSUE TITLE
how to package the indirect dependency?

### ISSUE THREAD

**Issue by wilsonlv** [kivy/buildozer#1831]
buildozer.spec
```
requirements=kivy,whisper-live==0.5.0
```

When we run `buildozer android debug`,  the indirect dependency will not be downloaded or packaged, is there any config param to support?

**Comment by misl6** [comment]
@wilsonlv FYI:

You should add every dependency and sub-dependency to your requirements list.
`pipdeptree` can help to have a proper list of all the sub-dependencies.
