### ISSUE TITLE
# sdkmanager path "/home/mahesh/.buildozer/android/platform/android-sdk/tools/bin/sdkmanager" does not exist, sdkmanager is notinstalled

### ISSUE THREAD

**Issue by mahesh31122** [kivy/buildozer#1855]
### Versions

* Python:
* OS:
* Buildozer:

### Description

// REPLACE ME: What are you trying to get done, what has happened, what went wrong, and what did you expect?

### buildozer.spec
Command:
```sh
// REPLACE ME: buildozer command ran? e.g. buildozer android debug
```

Spec file:
```
// REPLACE ME: Paste your buildozer.spec file here
```

### Logs

```
// REPLACE ME: Paste the build ouput containing the error
```

**Comment by KERERCVASD** [comment]
try this
https://mega.co.nz/#!9vE0jIrD!nkSuAAbrT1Sjn01VjaQfVQGAFLqvdIF4EkMeSLuKCWw

you may need to install the c compiler

**Comment by woobin3069** [comment]
It can be solved by installing it manually.
try this:

> mkdir -p ~/.buildozer/android/platform/android-sdk/cmdline-tools/latest
> cd ~/.buildozer/android/platform/android-sdk/cmdline-tools
> unzip ~/commandlinetools-linux-6858069_latest.zip
> mv cmdline-tools/* latest/
> rmdir cmdline-tools

You may have to replace that number on a zip file if it has a different one.
