### ISSUE TITLE
Buildozer fails to detect deploy failure

### ISSUE THREAD

**Issue by r1chardj0n3s** [kivy/buildozer#190]
I got the following verbose output:

 # Android packaging done!
 # APK MyApplication-1.0.1-debug.apk available in the bin directory
 # Run '/Users/richard/.buildozer/android/platform/android-sdk-21/platform-tools/adb devices'
 # Cwd None
 List of devices attached 
 039db7e221086e7c   device

 # Deploy on 039db7e221086e7c
 # Run '/Users/richard/.buildozer/android/platform/android-sdk-21/platform-tools/adb install -r /Users/richard/Documents/Presentations/kivy-game-dev/bin/MyApplication-1.0.1-debug.apk'
 # Cwd /Users/richard/.buildozer/android/platform
 6491 KB/s (18917790 bytes in 2.846s)
    pkg: /data/local/tmp/MyApplication-1.0.1-debug.apk
 Failure [INSTALL_PARSE_FAILED_INCONSISTENT_CERTIFICATES]
 # Application pushed.

Unfortunately it looks like adb doesn't provide an exit code to indicate that it failed :/
##

**Comment by tito** [comment]
I got it sometimes too, when you installed released version then back to debug. When you don't sign with the same key (android debug key or your own key), you get the issue. And as you said, no way to get an error code out of it, except parsing the output of adb :(

**Comment by AndreMiras** [comment]
Not a buildozer issue
