### ISSUE TITLE
Cant build APK for android.api = 10

### ISSUE THREAD

**Issue by 4544fa8d** [kivy/buildozer#193]
Hello,

I'm trying to build apk for my phone with Android 2.3.3 (api version 10), so...

1. I'm editing buildozer.spec
2. Editing line from: #android.api = to android.api = 10
3. Run build process:
    buildozer android debug
4. Build process ends with error:

    [aapt] /home/bps/workspace/todo/.buildozer/android/platform/python-for-android/dist/todo/bin/AndroidManifest.xml:29: error: Error: String types not allowed (at 'configChanges' with value 'mcc|mnc|locale|touchscreen|keyboard|keyboardHidden|navigation|orientation|screenLayout|fontScale|uiMode|screenSize').
     [aapt] 

BUILD FAILED
/home/bps/.buildozer/android/platform/android-sdk-21/tools/ant/build.xml:653: The following error occurred while executing this line:
/home/bps/.buildozer/android/platform/android-sdk-21/tools/ant/build.xml:698: null returned: 1

I've tried building my app with default values (commented line android.api) and it builds fine.
p.s. i have newest buildozer version from git.

**Comment by tito** [comment]
You should set minapi not api. Api is a strong requirement, and right now python-for-android itself seems not to support it. Please report on python-for-android project itself instead :)
