### ISSUE TITLE
Buildozer isn't building if I try to include some requirements

### ISSUE THREAD

**Issue by trabak** [kivy/buildozer#195]
Hi, I'm doing an android kivy app and I would like the app to generate some document to be sent via email. I've made some test apps to see how tools that create pdf and docx documents work on a kivy enviroment. More concretely, I've done a test with ReportLab (for PDF) and with python-docx (for docx). The problem is that when I try to build the app with buildozer, the build fails with similar errors in both cases. In the case of python-docx:

"""
creating build/temp.linux-x86_64-2.7

creating build/temp.linux-x86_64-2.7/src

creating build/temp.linux-x86_64-2.7/src/lxml

/bin/false -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -I/home/genis/Escriptori/Proves/provarst/.buildozer/venv/build/lxml/src/lxml/includes -I/usr/include/python2.7 -c src/lxml/lxml.etree.c -o build/temp.linux-x86_64-2.7/src/lxml/lxml.etree.o -w

error: command '/bin/false' failed with exit status 1

----------------------------------------
Cleaning up...
Command /home/genis/Escriptori/Proves/provarst/.buildozer/venv/bin/python2.7 -c "import setuptools, tokenize;__file__='/home/genis/Escriptori/Proves/provarst/.buildozer/venv/build/lxml/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-TKtfIU-record/install-record.txt --single-version-externally-managed --compile --install-headers /home/genis/Escriptori/Proves/provarst/.buildozer/venv/include/site/python2.7 --home=/tmp/tmpz4RShj failed with error code 1 in /home/genis/Escriptori/Proves/provarst/.buildozer/venv/build/lxml
Storing debug log for failure in /home/genis/.pip/pip.log
# Command failed: pip install --download-cache=/home/genis/.buildozer/cache --target=/home/genis/Escriptori/Proves/provarst/.buildozer/applibs python-docx
# 
"""

What am I missing here? Is it that those libraries need a recipe to build properly on buildozer?

**Comment by tito** [comment]
That's expected. Only pure python package can be installed automatically, all the packages that depends of binary compilation must have a recipe written.
