### ISSUE TITLE
buildozer -v android debug : Compile fails at fcntlmodule.c

### ISSUE THREAD

**Issue by Lakshmipathi** [kivy/buildozer#196]
I'm using Fedora-18 and while running the command "buildozer -v android debug" It hits the following error. How to resolve this ? thanks for any help.

gcc -pthread -fno-strict-aliasing  -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes  -I. -IInclude -I./Include   -DPy_BUILD_CORE  -c ./Modules/selectmodule.c -o Modules/selectmodule.o
gcc -pthread -fno-strict-aliasing  -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes  -I. -IInclude -I./Include   -DPy_BUILD_CORE  -c ./Modules/socketmodule.c -o Modules/socketmodule.o
./Modules/fcntlmodule.c: In function ‘all_ins’:
./Modules/fcntlmodule.c:568:5: error: ‘I_PUSH’ undeclared (first use in this function)
./Modules/fcntlmodule.c:568:5: note: each undeclared identifier is reported only once for each function it appears in
./Modules/fcntlmodule.c:569:5: error: ‘I_POP’ undeclared (first use in this function)
./Modules/fcntlmodule.c:570:5: error: ‘I_LOOK’ undeclared (first use in this function)
./Modules/fcntlmodule.c:571:5: error: ‘I_FLUSH’ undeclared (first use in this function)
./Modules/fcntlmodule.c:572:5: error: ‘I_FLUSHBAND’ undeclared (first use in this function)
./Modules/fcntlmodule.c:573:5: error: ‘I_SETSIG’ undeclared (first use in this function)
./Modules/fcntlmodule.c:574:5: error: ‘I_GETSIG’ undeclared (first use in this function)
./Modules/fcntlmodule.c:575:5: error: ‘I_FIND’ undeclared (first use in this function)
./Modules/fcntlmodule.c:576:5: error: ‘I_PEEK’ undeclared (first use in this function)
./Modules/fcntlmodule.c:577:5: error: ‘I_SRDOPT’ undeclared (first use in this function)
./Modules/fcntlmodule.c:578:5: error: ‘I_GRDOPT’ undeclared (first use in this function)
./Modules/fcntlmodule.c:579:5: error: ‘I_NREAD’ undeclared (first use in this function)
./Modules/fcntlmodule.c:580:5: error: ‘I_FDINSERT’ undeclared (first use in this function)
./Modules/fcntlmodule.c:581:5: error: ‘I_STR’ undeclared (first use in this function)
./Modules/fcntlmodule.c:582:5: error: ‘I_SWROPT’ undeclared (first use in this function)
./Modules/fcntlmodule.c:587:5: error: ‘I_SENDFD’ undeclared (first use in this function)
./Modules/fcntlmodule.c:588:5: error: ‘I_RECVFD’ undeclared (first use in this function)
./Modules/fcntlmodule.c:589:5: error: ‘I_LIST’ undeclared (first use in this function)
./Modules/fcntlmodule.c:590:5: error: ‘I_ATMARK’ undeclared (first use in this function)
./Modules/fcntlmodule.c:591:5: error: ‘I_CKBAND’ undeclared (first use in this function)
./Modules/fcntlmodule.c:592:5: error: ‘I_GETBAND’ undeclared (first use in this function)
./Modules/fcntlmodule.c:593:5: error: ‘I_CANPUT’ undeclared (first use in this function)
./Modules/fcntlmodule.c:594:5: error: ‘I_SETCLTIME’ undeclared (first use in this function)
./Modules/fcntlmodule.c:598:5: error: ‘I_LINK’ undeclared (first use in this function)
./Modules/fcntlmodule.c:599:5: error: ‘I_UNLINK’ undeclared (first use in this function)
./Modules/fcntlmodule.c:600:5: error: ‘I_PLINK’ undeclared (first use in this function)
./Modules/fcntlmodule.c:601:5: error: ‘I_PUNLINK’ undeclared (first use in this function)
make: **\* [Modules/fcntlmodule.o] Error 1
make: **\* Waiting for unfinished jobs....
./Modules/socketmodule.c: In function ‘socket_gethostbyname_ex’:
./Modules/socketmodule.c:3371:9: warning: variable ‘result’ set but not used [-Wunused-but-set-variable]
./Modules/socketmodule.c: In function ‘socket_gethostbyaddr’:
./Modules/socketmodule.c:3447:9: warning: variable ‘result’ set but not used [-Wunused-but-set-variable]
command failed: ./distribute.sh -m "kivy"
##

**Comment by AndreMiras** [comment]
`distribute.sh` was part of the old p4a code base, plus we don't have enough info (e.g. buildozer.spec) to reproduce, closing
