### ISSUE TITLE
Hang up at Fetching https://dl-ssl.google.com/android/repository/addons_list-2.xml

### ISSUE THREAD

**Issue by jjling2011** [kivy/buildozer#198]
If the system did not install python(2) -pyopenssl, 
`buildozer -v android debug deploy run`
 will hang at "Fetching ...." , without any warning. 
Please add some hints or check whether the system has been installed python(2) -pyopenssl.

Please marked this issue as closed.

**Comment by jjling2011** [comment]
Sorry guys! After a day of installing and removing android sdk, I found that it is the proxy settings problem of sdk manager.
Issue closed.

**Comment by bambooeater** [comment]
Thanks for reporting, this is helpful information.
