### ISSUE TITLE
cython issue with kivy and buildozer development versions

### ISSUE THREAD

**Issue by consultit** [kivy/buildozer#207]
I followed the instructions for installing both kivy and buildozer development version (from git) on debian jessie. 
But I was able to build successfully the 'demo' example (from kivy) only with cython version 0.20 and not 0.22 as suggested.

**Comment by DiMartinoXBMC** [comment]
Same on ubuntu x64

**Comment by inclement** [comment]
Cython 0.22 will work only with kivy master (which you can use by including `kivy==master` in the buildozer requirements).

**Comment by consultit** [comment]
In buildozer.spec I just put 
requirements = kivy==master
and build was successful.
Thanks.
