### ISSUE TITLE
Problems with adding wav, ogg and ttf files

### ISSUE THREAD

**Issue by VasilishinDmitry** [kivy/buildozer#208]
I/python  ( 6900):  Traceback (most recent call last):
I/python  ( 6900):    File "/home/kivy/Desktop/jump/.buildozer/android/app/main.py", line 212, in <module>
I/python  ( 6900):    File "/home/kivy/Desktop/jump/.buildozer/android/app/main.py", line 231, in Game
I/python  ( 6900):    File "/home/kivy/Desktop/jump/.buildozer/android/platform/python-for-android/build/python-install/lib/python2.7/site-packages/kivy/core/audio/__init__.py", line 69, in load
I/python  ( 6900):    File "/home/kivy/Desktop/jump/.buildozer/android/platform/python-for-android/build/python-install/lib/python2.7/site-packages/kivy/core/audio/audio_pygame.py", line 47, in __init__
I/python  ( 6900):    File "kivy/_event.pyx", line 271, in kivy._event.EventDispatcher.__init__ (kivy/_event.c:4930)
I/python  ( 6900):    File "kivy/properties.pyx", line 397, in kivy.properties.Property.__set__ (kivy/properties.c:4677)
I/python  ( 6900):    File "kivy/properties.pyx", line 429, in kivy.properties.Property.set (kivy/properties.c:5202)
I/python  ( 6900):    File "kivy/properties.pyx", line 484, in kivy.properties.Property.dispatch (kivy/properties.c:5851)
I/python  ( 6900):    File "kivy/_event.pyx", line 1168, in kivy._event.EventObservers.dispatch (kivy/_event.c:12191)
I/python  ( 6900):    File "kivy/_event.pyx", line 1074, in kivy._event.EventObservers._dispatch (kivy/_event.c:11486)
I/python  ( 6900):    File "/home/kivy/Desktop/jump/.buildozer/android/platform/python-for-android/build/python-install/lib/python2.7/site-packages/kivy/core/audio/__init__.py", line 147, in on_source
I/python  ( 6900):    File "/home/kivy/Desktop/jump/.buildozer/android/platform/python-for-android/build/python-install/lib/python2.7/site-packages/kivy/core/audio/audio_pygame.py", line 85, in load
I/python  ( 6900):    File "/home/kivy/Desktop/jump/.buildozer/android/platform/python-for-android/build/python-install/lib/python2.7/site-packages/android/mixer.py", line 202, in __init__
**I/python  ( 6900):  IOError: [Errno 2] No such file or directory: '/data/data/com.meltingrocks.jump/files/data/sound/jump2.wav'**
I/ActivityManager(  410): Process com.android.mms (pid 6427) (adj 8) has died.
I/python  ( 6900): Python for android ended.

buildozer last version

**Comment by VasilishinDmitry** [comment]
my SPEC

[app]

# (str) Title of your application
title = Jump jump

# (str) Package name
package.name = jump

# (str) Package domain (needed for android/ios packaging)
package.domain = com.meltingrocks

# (str) Source code where the main.py live
source.dir = .

# (list) Source files to include (let empty to include all the files)
source.include_exts = py,png,jpg,kv,atlas,wav

# (list) Source files to exclude (let empty to not exclude anything)
#source.exclude_exts = spec

# (list) List of directory to exclude (let empty to not exclude anything)
source.exclude_dirs = tests, bin, build

# (list) List of exclusions using pattern matching
#source.exclude_patterns = license,images/*/*.jpg

# (str) Application versioning (method 1)
version.regex = __version__ = '(.*)'
version.filename = %(source.dir)s/main.py

# (str) Application versioning (method 2)
# version = 1.2.0

# (list) Application requirements
requirements = kivy

# (list) Garden requirements
#garden_requirements =

# (str) Presplash of the application
presplash.filename = %(source.dir)s/data/presplash.png

# (str) Icon of the application
icon.filename = %(source.dir)s/data/icon.png

# (str) Supported orientation (one of landscape, portrait or all)
orientation = portrait

# (bool) Indicate if the application should be fullscreen or not
fullscreen = 1

**Comment by VasilishinDmitry** [comment]
my spec 
[app]

 # (str) Title of your application
title = Jump jump

 # (str) Package name
package.name = jump

 # (str) Package domain (needed for android/ios packaging)
package.domain = com.meltingrocks

 # (str) Source code where the main.py live
source.dir = .

 # (list) Source files to include (let empty to include all the files)
source.include_exts = py,png,jpg,kv,atlas,wav

 # (list) Source files to exclude (let empty to not exclude anything)
 #source.exclude_exts = spec

 # (list) List of directory to exclude (let empty to not exclude anything)
source.exclude_dirs = tests, bin, build

 # (list) List of exclusions using pattern matching
 #source.exclude_patterns = license,images/*/*.jpg

 # (str) Application versioning (method 1)
version.regex = __version__ = '(.*)'
version.filename = %(source.dir)s/main.py

 # (str) Application versioning (method 2)
 # version = 1.2.0

 # (list) Application requirements
requirements = kivy

 # (list) Garden requirements
 #garden_requirements =

 # (str) Presplash of the application
presplash.filename = %(source.dir)s/data/presplash.png

 # (str) Icon of the application
icon.filename = %(source.dir)s/data/icon.png

 # (str) Supported orientation (one of landscape, portrait or all)
orientation = portrait

 # (bool) Indicate if the application should be fullscreen or not
fullscreen = 1

**Comment by NumesSanguis** [comment]
Can confirm the .ttf file. I deleted the previous .buildozer folder and the .buildozer in my Home directory and ran the command: buildozer debug
I have a different error log though:

BUILD FAILED
/home/numessanguis3/.buildozer/android/platform/android-sdk-21/tools/ant/build.xml:484: SDK does not have any Build Tools installed.

Total time: 0 seconds
/screens/credits.kv
assets/private.mp3: .../.buildozer/android/app/data/screens/learnkanji.pyo
assets/private.mp3: .../.buildozer/android/app/data/screens/mainmenu.kv
assets/private.mp3: .../.buildozer/android/app/data/db/Kanji-story.db
assets/private.mp3: .../.buildozer/android/app/data/db/Kanji-story_org.db
assets/private.mp3: .../.buildozer/android/app/data/fonts/TakaoPMincho**.ttf**
Traceback (most recent call last):
  File "build.py", line 508, in <module>
    make_package(args)
  File "build.py", line 357, in make_package
    subprocess.check_call([ANT, arg])
  File "/usr/lib/python2.7/subprocess.py", line 540, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['ant', 'debug']' returned non-zero exit status 1

**Comment by tito** [comment]
It does work. You need to give us the full build log, not the issue you got on the device if we want to help you.

By the way, please stop using com.meltingrocks as a prefix, it's my own company :)
