### ISSUE TITLE
Add android.ant_path to default.spec

### ISSUE THREAD

**Issue by akkana** [kivy/buildozer#209]
I have kivy and ant installed from debian packages, buildozer from git because there is no debian package. Following a tutorial, I ran 
buildozer android debug deploy run
and noticed it wanted to download a new version of ant:
Android ANT is missing, downloading

Poking through the source of buildozer I discovered that it checks a config variable android.ant_path, but that variable wasn't in the buildozer.spec file it created for me. Since android.ndk_path and android.sdk_path were in the default spec, it would have been helpful if android.ant_path was too.

**Comment by dvenkatsagar** [comment]
:+1:
