### ISSUE TITLE
Buildozer recompiles p4a when a custom for of plyer is used.

### ISSUE THREAD

**Issue by po9794** [kivy/buildozer#210]
To reproduce :

• Make a fork of plyer
• Have it refered in your buildozer.spec : requirements.source.plyer = path/to/plyer

And everytime you launch the command "buildozer -v android debug", buildozer recompiles p4a.

• Remove the line requirements.source.plyer = path/to/plyer
• Define P4A_plyer_DIR environement variable to your plyer fork.

And it works! (without recompiling p4a and everything...)

**Comment by tito** [comment]
It was intented. Everytime you try to build on android or iOS, it would try to recompile the source as well. I'll remove that pseudo feature which i think made things worst.
