### ISSUE TITLE
Error when first time Building apk  

### ISSUE THREAD

**Issue by spac3-monkey** [kivy/buildozer#212]
I followed the installation doc as it says and when building my first android `.apk` I keep getting the following error output:
```
Command failed: tar xzf android-sdk_r21-linux.tgz
 
Buildozer failed to execute the last command
The error might be hidden in the log above this error
Please read the full log, and search for it before
raising an issue with buildozer itself.
In case of a bug report, please add a full log with log_level = 2
```

I'm running ubuntu **14.04 x86_64**

**Comment by tito** [comment]
The message say everything. In case of a bug report, please add the full log with log_level = 2. You cutted the log yourself, we can't know what is going on ^^
