### ISSUE TITLE
how to use custom android library in my kivy app?

### ISSUE THREAD

**Issue by python-programmer** [kivy/buildozer#214]
I want to use a custom android library 

step 1: add bellow codes to manifest

```
<activity
    android:name="com.example.activity"
    android:theme="@android:style/Theme.Dialog">
</activity>
```

step 2: add this code to main layout

```
 <com.example.View
    android:id="@+id/practice"
    android:layout_width="wrap_content"
    android:layout_height="wrap_content" />
```

can i do this two step in my kivy app?
##

**Comment by tito** [comment]
Python-for-android doesn't provide tool to change manifest yet, so your first step is not possible in buildozer itself.
As for the second, there is lot of resource on the internet to do so. This is not the job of buildozer.

**Comment by AndreMiras** [comment]
I believe this is now possible. Feel free to reopen otherwise
