### ISSUE TITLE
ImportError: No module named pygments

### ISSUE THREAD

**Issue by consultit** [kivy/buildozer#216]
I'm new on kivy/buildozer sdk.
I'm just trying to run some of the examples from kivy source on my android phones. 
After connecting phones, I use this command:
```
buildozer -v android debug deploy run logcat | grep -i python
```
but some examples ( demo/kivycatalog, demo/shadereditor) don't start on phones and debug console outputs something related to "missing" pygments module:
```
...
I/python  ( 4413):    File "/Projects/demo/kivycatalog/.buildozer/android/platform/python-for-android/build/python-install/lib/python2.7/site-packages/kivy/uix/codeinput.py", line 37, in <module>
I/python  ( 4413):  ImportError: No module named pygments
I/python  ( 4413): Python for android ended.
...
```
I verified that pygments module is installed on my build system (debian jessie with both kivy and buildozer development versions), and these apps works fine on it.

**Comment by akshayaurora** [comment]
requirements = kivy, pygements in bulldozer.spec

**Comment by brentpicasso** [comment]
I just ran into this myself - does adding pygments to the requirements list actually work?

I immediately get an error with this:

**Comment by brentpicasso** [comment]
I seem to be on the latest version of buildozer. pygments is currently installed via pip, and app run from command line (linux)

**Comment by inclement** [comment]
Apparently you don't have virtualenv installed. Install it and see if that works.

I did think it should check for virtualenv before getting this far, so maybe there's something else as well.

**Comment by brentpicasso** [comment]
Seemed to get me further, now to figure out why it can't find the bbcode formatter...  even though it seems to be packaged.

**Comment by brentpicasso** [comment]
(thanks @inclement )

**Comment by brentpicasso** [comment]
Yes, success. Github needs a thank you / gifting system :)
