### ISSUE TITLE
Buildozer fails because of build-tools package name

### ISSUE THREAD

**Issue by nox1203** [kivy/buildozer#217]
On Ubuntu 14.04.1 the latest build-tools package is:
build-tools-23.0.0-preview

and because of this buildozer fails with:
ValueError: invalid literal for int() with base 10: '0-preview'.

**Comment by anarchyonline** [comment]
Experiencing the same problem.
Workaround that fixed it for me is to modify the parsing code in android.py

    def _process_version_string(self, version_string):
	lijst = version_string.split('-')
        #version = [int(i) for i in version_string.split(".")]
	version = [int(i) for i in lijst[0].split(".")]        
	return version

**Comment by nox1203** [comment]
Thank you for the answer.
There are many workarounds. I used just:
version = [i for i in version_string.split(".")]
but this are all just workarounds.

I was hoping for real solution or maybe just the code that
does not return the latest package name but does not crash.

**Comment by BarbourSmith** [comment]
There is a pull request out to fix this  (#213)

**Comment by tito** [comment]
`-preview` doesn't seem to be here anymore. This is a shame that android guys doesn't follow version notation :/

**Comment by tito** [comment]
Please reopen when it happen again.
