### ISSUE TITLE
Making reverse engineering .apk harder

### ISSUE THREAD

**Issue by NumesSanguis** [kivy/buildozer#224]
Would it be possible to add an option in which you can make the process of reverse engineering a kivy .apk harder?
For example: passing modules names to convert with cython instead of using python -OO (advice from tshirman)

**Comment by tito** [comment]
Unless you make a tool for that, this is not a job for buildozer itself. Buildozer just reflect the capabilities of underlaying toolchain. If later you have a library for that, or another tool, either integrate it into python-for-android if it's apply, or if it's a general tool that work on source itself (like source obfuscation), then we might be able to integrate it here.
