### ISSUE TITLE
Error while trying to install Buildozer in Windows  10

### ISSUE THREAD

**Issue by AzaJimenez** [kivy/buildozer#225]
Hi Guys! Have a little problem when I try to install Buildozer in Windows 10, and can't  find how to fix it!

When using pip for installing Buildozer, I get this error:

UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 5939: character maps to <undefined>

Appreciate your help!

PD: I have Python 3.4

[error buildozer](https://cloud.githubusercontent.com/assets/12603040/9429240/322f68ee-498f-11e5-99a8-3af76f1fd50c.png)

**Comment by dvenkatsagar** [comment]
Its a encoding issue, i think..

Just try this out.
open setup.py and change these lines below:
```python
curdir = dirname(__file__)
with open(join(curdir, "README.rst")) as fd:
    readme = fd.read()
with open(join(curdir, "CHANGELOG.md")) as fd:
    changelog = fd.read()
```

Change it to this : 
```python
curdir = dirname(__file__)
with open(join(curdir, "README.rst"),encoding='utf8') as fd:
    readme = fd.read()
with open(join(curdir, "CHANGELOG.md"),encoding='utf8') as fd:
    changelog = fd.read()
```

And try it out.
