### ISSUE TITLE
Rebuild only selected packages

### ISSUE THREAD

**Issue by hottwaj** [kivy/buildozer#226]
Hi guys, I don't seem to be able to rebuild a single package at a time when I'm using buildozer and python-for-android.  I don't know if this is a buildozer or a python-for-android problem - but thought I'd start here.

Some of my app involves compiled cython code that is android specific (i.e. I can't test it on Linux/Windows).  I have put this portion of my app in a recipe for P4A which I can compile and package up using buildozer

However, whenever I make a change to my cython package the only way I seem to be able to get the changes into my android app so that I can test them is to rebuild my entire app from scratch using buildozer - including recompiling python and kivy which take a long time to recompile.

I've tried using the "update" option with buildozer, which claims to only update the given packages, but this appears to just start the build process again from scratch (python and kivy are recompiled).

Am I missing something or doing something wrong?

Many thanks!  Loving being able to code apps in Python - Kivy is an awesome project...
##

**Comment by inclement** [comment]
This is probably more of a python-for-android issue than a buildozer one, except possibly the buildozer update command.

The python-for-android revamp branch does behave properly if a single recipe is deleted, and actually has a command to do this.

**Comment by hottwaj** [comment]
OK thanks, I guess I should test out the P4A revamp branch and see if that works.  Cheers

**Comment by inclement** [comment]
Note that you'll need to check out this branch directly, it won't work
with buildozer right now.

**Comment by hottwaj** [comment]
Checking back through my own old issues.  P4A can do this as mentioned above so I'll close.  Thanks!
