### ISSUE TITLE
subprocess.CalledProcessError: Command '['ant', 'debug']' returned non-zero exit status 1

### ISSUE THREAD

**Issue by jligeza** [kivy/buildozer#234]
I am new to kivy and I am trying to build + deploy a ,,hello world'' project.

This is the error message:

Traceback (most recent call last):
  File "build.py", line 509, in <module>
    make_package(args)
  File "build.py", line 357, in make_package
    subprocess.check_call([ANT, arg])
  File "/usr/lib/python2.7/subprocess.py", line 540, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['ant', 'debug']' returned non-zero exit status 1

 # Command failed: /usr/bin/python2.7 build.py --name 'My Application' --version 1.0 --package org.test.myapp --private /home/stefan/kivy/test_project/.buildozer/android/app --sdk 14 --minsdk 8 --orientation landscape debug

Also tried to set in buildozer.spec `android.sdk` from default to 20-24, but neither worked.

My SDK Manager looks like this:
![sdk](https://cloud.githubusercontent.com/assets/12465301/10198676/57166596-679d-11e5-92c4-1c0cb3c3a7db.png)

I've downloaded buildozer today.
How can I build + deploy my project?

**Comment by akshayaurora** [comment]
Make sure you are using java version like openjdk-7-jdk or oracle version
and not gcj or other such option​.

**Comment by jligeza** [comment]
I don't have gcj installed, and `java -version` produces this output:

`java version "1.7.0_79"
OpenJDK Runtime Environment (IcedTea 2.5.6) (7u79-2.5.6-0ubuntu1.14.04.1)
OpenJDK 64-Bit Server VM (build 24.79-b02, mixed mode)`

**Comment by jligeza** [comment]
I haven't uploaded full error, so here it is:

...
[getbuildtools] Using latest Build Tools: 20.0.0
     [echo] Resolving Build Target for MyApplication-1.0...

BUILD FAILED
/home/stefan/.buildozer/android/platform/android-sdk-21/tools/ant/build.xml:538: Unable to resolve project target 'android-14'

Total time: 1 second
/home/stefan/kivy/test_project/.buildozer/android/app/old_main.pyo
assets/private.mp3: /home/stefan/kivy/test_project/.buildozer/android/app/normal_log
assets/private.mp3: /home/stefan/kivy/test_project/.buildozer/android/app/gui (kopia bez floata).kv
assets/private.mp3: /home/stefan/kivy/test_project/.buildozer/android/app/log
assets/private.mp3: /home/stefan/kivy/test_project/.buildozer/android/app/gui.kv
assets/private.mp3: /home/stefan/kivy/test_project/.buildozer/android/app/error_log2
assets/private.mp3: /home/stefan/kivy/test_project/.buildozer/android/app/err_log
assets/private.mp3: /home/stefan/kivy/test_project/.buildozer/android/app/normal_log2
Traceback (most recent call last):
  File "build.py", line 509, in <module>
    make_package(args)
  File "build.py", line 357, in make_package
    subprocess.check_call([ANT, arg])
  File "/usr/lib/python2.7/subprocess.py", line 540, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['ant', 'debug']' returned non-zero exit status 1

And here is my buildozer.spec (from default, changed only sdk, api and target): http://pastebin.com/WxME7paG

**Comment by tito** [comment]
Android-14 doesn't seems to exists anymore. Try using 19 instead.

**Comment by 700brains** [comment]
@tito please sir, am using ubuntu OS and am having same problem where and where should i look for #android-19. or is it the API you're talking about.?

**Comment by 700brains** [comment]
@jligeza  
I recomend younot running with ROOT instead run outside root
Your buildozer.spec file has......
# (str) Source code where the main.py live
source.dir = .

Then change it to something like
# (str) Source code where the main.py live
source.dir = home/jligeza/kivyapps/where_your_application_folder_is

Notice:::: your .spec file allows the use of SUDO but buildozer does not allow it even if your app builds to run it in android device "IT CRASHES". 
I don't know whether you understood me. if am wrong guys please correct me
