### ISSUE TITLE
Provide custom path for android SDK to buildozer

### ISSUE THREAD

**Issue by udiboy1209** [kivy/buildozer#237]
I frequently use Android Studio for development, and have a regularly updated collection of SDKs of different android versions in a specific directory.

I don't want buildozer to keep its own set of SDKs separately under `~/.buildozer/`

Is there any global configuration I can edit to specify this to buildozer? 

Currently using the latest stable version from `pip` : 0.30

**Comment by pythonic64** [comment]
There is in buildozer.spec file:
https://github.com/kivy/buildozer/blob/master/buildozer/default.spec#L84

Set path to android sdk directory and remove "#"

**Comment by dessant** [comment]
@pythonic64 thanks for the quick solution. :+1:

**Comment by udiboy1209** [comment]
Is there a global buildozer.spec so I dont have to do it for every project? I guess I could update default.spec in the source, but that would not allow me to change the location later. I'd have to change the spec file for every project I build.

P.S. from what I understand about default.spec, it is used to generate a buildozer.spec when `buildozer init` is run. But I may be wrong here!

**Comment by akshayaurora** [comment]
@udiboy1209 use sum links symlink your android ndk and sdks folder to where bulldozer expects them to be in ~/.buildozer/...

**Comment by inclement** [comment]
You actually can also set it globally with the `APP_ANDROID_SDK_PATH' and `APP_ANDROID_NDK_PATH` environment variables.

**Comment by udiboy1209** [comment]
@akshayaurora thanks for the nice hack! Although I would like to implement a global config file, probably situated in `~/.buildozer/global.spec`. Just seems better. 

I'll have to merge configs from both `global.spec` and the local `buildozer.spec` giving the latter more priority, right? I found the project uses `ConfigParser`. Am I in the right direction?

**Comment by udiboy1209** [comment]
@inclement I just understood what you were trying to say after looking at `set_config_token_fron_env()`.

So I guess a global file isn't needed then! Thanks everyone for your help :smile:
