### ISSUE TITLE
java.lang.NoSuchMethodException: isSupportChangeBadgeByCallMethod []

### ISSUE THREAD

**Issue by eviltomato** [kivy/buildozer#243]
I  deployed this app on my mobile with the commad`buildozer android deploy run logcat`,
after I complied my application with buildozer.And I got the following exception when I runnig the app.
`beginning of /dev/log/main`
`W/System.err(15337): java.lang.NoSuchMethodException: isSupportChangeBadgeByCallMethod []`
`W/System.err(15337): 	at java.lang.Class.getConstructorOrMethod(Class.java:472)`
`W/System.err(15337): 	at java.lang.Class.getMethod(Class.java:857)`
`W/System.err(15337): 	at com.tencent.mobileqq.msf.core.push.BadgeUtilImpl.isSupportHuawei(BadgeUtilImpl.java:396)`
`W/System.err(15337): 	at com.tencent.mobileqq.msf.core.push.BadgeUtilImpl.setHuaweiBadge(BadgeUtilImpl.java:194)`
`W/System.err(15337): 	at com.tencent.mobileqq.msf.core.push.BadgeUtilImpl.setBadge(BadgeUtilImpl.java:343)`
`W/System.err(15337): 	at com.tencent.mobileqq.msf.core.push.BadgeUtilImpl.setBadge(BadgeUtilImpl.java:354)`
`W/System.err(15337): 	at nvb.run(ProGuard:51)`
`W/System.err(15337): 	at mqq.os.MqqHandler.handleCallback(MqqHandler.java:320)`
`W/System.err(15337): 	at mqq.os.MqqHandler.dispatchMessage(MqqHandler.java:89)`
`W/System.err(15337): 	at mqq.os.MqqHandler$NativeHandler.dispatchMessage(MqqHandler.java:333)`
`W/System.err(15337): 	at android.os.Looper.loop(Looper.java:136)`
`W/System.err(15337): 	at android.os.HandlerThread.run(HandlerThread.java:61)`

**Comment by tito** [comment]
This has nothing to do with buildozer. It seems you actually used an external library that fail, or something like that. We don't use com.tecent.mobileqq or anything like that in our source code.
