### ISSUE TITLE
Implement source.include_patterns

### ISSUE THREAD

**Issue by dessant** [kivy/buildozer#245]
ref https://github.com/kivy/buildozer/pull/30.

**Comment by udiboy1209** [comment]
How difficult would it be for a beginner to buildozer to implement this feature? I have contributed to kivy and also have good enough python knowledge, but I haven't contributed to buildozer so I'm not familiar with the source. But this seems like an interesting feature to code, so I am asking.

**Comment by inclement** [comment]
I think it should be quite doable - there's probably just one place in the code where you need to check and use such a config token, and it will be in the same place as all the similar ones.

**Comment by udiboy1209** [comment]
What should be the priority of the include/exclude options. I mean if files satisfy both include_pattern and exclude_pattern then? And what of files which do not satisfy include_pattern but are in the source dir?

**Comment by kived** [comment]
This has been added in #269
