### ISSUE TITLE
Not quite an issue, just some dependency stuff

### ISSUE THREAD

**Issue by Naruto0** [kivy/buildozer#247]
Shouldn't ether kivy or builldozer make sure of installed dependencies? Buildozer checks for cython, javac, but for example not python-dev etc. (errers listed down)

Thing is, when somebody wants to use kivy and installs fresh new Linux based OS in virtualbox, installing should be somewhat cornerstone to make buildozer work.

http://stackoverflow.com/questions/11094718/error-command-gcc-failed-with-exit-status-1-while-installing-eventlet

http://georgik.sinusgear.com/2014/03/22/kivy-buildozer-android-debug-failed-with-libstdc-so-6-cannot-open-shared-object-file/comment-page-1/

To note, i'm using 1.9.0, so it might not be issue in 1.9.1
##

**Comment by inclement** [comment]
I don't think buildozer depends on python-dev.

What exactly are you asking/requesting, are you just saying that the dependency checks don't check for everything?

**Comment by Naruto0** [comment]
Exactly. With some prior default package installations on one computer i have no problem at all. Just with fresh installed xubuntu i went through many solutions, which were wrong. I just simply had not installed couple of packages. I'm really quite new to the community so i have no knowledge to build on. Simply as you say, that if someone checks the dependency checks for future releases.

**Comment by AndreMiras** [comment]
Thanks for the bug report, this is now tracked in https://github.com/kivy/python-for-android/issues/1750
