### ISSUE TITLE
Try to build with caldav requirement fails

### ISSUE THREAD

**Issue by salomonderossi** [kivy/buildozer#248]
I want to build a kivy app with the caldav package included
https://bitbucket.org/cyrilrbt/caldav/wiki/Home
https://pypi.python.org/pypi/caldav/

I'm using kivy (1.9.0) and buildozer (0.30) from pip on Ubuntu 14.04.3 LTS.

As I have read in #195 that only pure python packages or packages with a recipe can be build. The caldav package is pure python with a dependency to a lxml (which is not pure python but has a recipe).

Building lxml as a separate requirement works as expected, but when in is build as a dependency from caldav I get the following error:

    /bin/false -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -I/usr/include/libxml2 -I/home/philipp/tmp/python/kivy_list_test/.buildozer/venv/build/lxml/src/lxml/includes -I/usr/include/python2.7 -c src/lxml/lxml.etree.c -o build/temp.linux-x86_64-2.7/src/lxml/lxml.etree.o -w

    error: command '/bin/false' failed with exit status 1

    ----------------------------------------
    Cleaning up...

Do I need to write a recipe or is there another way to build the project with the caldav package?

**Comment by tito** [comment]
Hi. Yes, any python library that require compilation need a recipe in python-for-android project. The /bin/false is the compiler that buildozer set to prevent trying to install compiled-libraries that would fail anyway.

**Comment by kived** [comment]
The new p4a toolchain (buildozer `android_new` target) does not install dependencies of pure-Python packages (you have to specify them yourself), which makes it work in these situations as you can build the lxml recipe and get caldav from pypi. However, the lxml recipe has not been ported to the new toolchain. Doing so would probably be fairly easy if you wanted to try it and submit a PR.
