### ISSUE TITLE
Please update SDK url

### ISSUE THREAD

**Issue by afidegnum** [kivy/buildozer#249]
There is an issue of accessing http://dl.google.com/android  at https://github.com/kivy/buildozer/blob/master/buildozer/targets/android.py#L251

can you please check and update ?

**Comment by dessant** [comment]
The archive does work, see for example http://dl.google.com/android/android-sdk_r22.2.1-linux.tgz.
The root will 404, but that's normal.

Do you have a specific issue?

**Comment by afidegnum** [comment]
ok, thanks, sorry for not getting back earlier, the issue was rather from my Internet connection. the root return 404 but was able to download and set up later, thanks a lot for the good work.
