### ISSUE TITLE
Please upgrade the documentation

### ISSUE THREAD

**Issue by kiok46** [kivy/buildozer#255]
This link https://buildozer.readthedocs.org/en/latest/installation.html is outdated.

**Android on Ubuntu 13.10 (64bit)**

`sudo pip install --upgrade cython
sudo dpkg --add-architecture i386
sudo apt-get update
sudo apt-get install build-essential ccache git ia32-libs libncurses5:i386 libstdc++6:i386 python2.7 python2.7-dev openjdk-7-jdk unzip zlib1g-dev zlib1g:i386`

**Installing ia32-libs shows this error**
    
    Package ia32-libs is not available, but is referred to by another package.
    This may mean that the package is missing, has been obsoleted, or
    is only available from another source
    However the following packages replace it:
          lib32z1 lib32ncurses5

Please change it to this or as you please. I just wanted to bring this into consideration.

`sudo apt-get install build-essential ccache git libncurses5:i386 libstdc++6:i386 python2.7 python2.7-dev openjdk-7-jdk unzip zlib1g-dev zlib1g:i386 libgtk2.0-0:i386 libpangox-1.0-0:i386 libpangoxft-1.0-0:i386 libidn11:i386`

**Comment by dessant** [comment]
The source is here: https://github.com/kivy/buildozer/blob/master/docs/source/installation.rst.

**Comment by kiok46** [comment]
Saw it already, but I think new users don't go this deep to to check for installation

**Comment by matham** [comment]
I think @dessant meant it as a hint that you can submit a pr that fixes the issue by changing that source.

**Comment by kiok46** [comment]
@matham  alright, will do it.

**Comment by kiok46** [comment]
Done in. #256
