### ISSUE TITLE
error while deploying android 

### ISSUE THREAD

**Issue by daryasary** [kivy/buildozer#257]
I've installed buildozer recentley but getting this error, what's the matter?

    hosein@red$buildozer android debug deploy run
    # Check configuration tokens
    # Ensure build layout
    # Check configuration tokens
    # Preparing build
    # Check requirements for android
    # Install platform
    # Apache ANT found at /home/hosein/.buildozer/android/platform/apache-ant-1.9.4
    # Android SDK found at /home/hosein/.buildozer/android/platform/android-sdk-20
    # Android NDK found at /home/hosein/.buildozer/android/platform/android-ndk-r9c
    Refresh Sources:
      Fetching https://dl-ssl.google.com/android/repository/addons_list-2.xml
      Validate XML
      Parse XML
      Fetched Add-ons List successfully
      Refresh Sources
      Fetching URL: https://dl-ssl.google.com/android/repository/repository-7.xml
      Validate XML: https://dl-ssl.google.com/android/repository/repository-7.xml
      Parse XML:    https://dl-ssl.google.com/android/repository/repository-7.xml
      Fetching URL: https://dl-ssl.google.com/android/repository/addon.xml
      Validate XML: https://dl-ssl.google.com/android/repository/addon.xml
      Fetching URL: https://dl-ssl.google.com/android/repository/addon-6.xml
      Validate XML: https://dl-ssl.google.com/android/repository/addon-6.xml
      Fetching URL: https://dl-ssl.google.com/glass/gdk/addon.xml
      Validate XML: https://dl-ssl.google.com/glass/gdk/addon.xml
      Parse XML:    https://dl-ssl.google.com/glass/gdk/addon.xml
      Fetching URL: https://dl-ssl.google.com/android/repository/extras/intel/addon.xml
      Validate XML: https://dl-ssl.google.com/android/repository/extras/intel/addon.xml
      Fetching URL: https://dl-ssl.google.com/android/repository/sys-img/android/sys-img.xml
      Validate XML: https://dl-ssl.google.com/android/repository/sys-img/android/sys-img.xml
      Fetching URL: https://dl-ssl.google.com/android/repository/sys-img/android-wear/sys-img.xml
      Validate XML: https://dl-ssl.google.com/android/repository/sys-img/android-wear/sys-img.xml
      Fetching URL: https://dl-ssl.google.com/android/repository/sys-img/android-tv/sys-img.xml
      Validate XML: https://dl-ssl.google.com/android/repository/sys-img/android-tv/sys-img.xml
      Fetching URL: https://dl-ssl.google.com/android/repository/sys-img/google_apis/sys-img.xml
      Validate XML: https://dl-ssl.google.com/android/repository/sys-img/google_apis/sys-img.xml
      Fetching URL: https://dl-ssl.google.com/android/repository/sys-img/x86/addon-x86.xml
      Validate XML: https://dl-ssl.google.com/android/repository/sys-img/x86/addon-x86.xml
    Refresh Sources:
      Fetching URL: https://dl-ssl.google.com/android/repository/addon.xml
      Validate XML: https://dl-ssl.google.com/android/repository/addon.xml
      Fetching URL: https://dl-ssl.google.com/android/repository/addon-6.xml
      Validate XML: https://dl-ssl.google.com/android/repository/addon-6.xml
      Fetching URL: https://dl-ssl.google.com/android/repository/extras/intel/addon.xml
      Validate XML: https://dl-ssl.google.com/android/repository/extras/intel/addon.xml
      Fetching URL: https://dl-ssl.google.com/android/repository/sys-img/android/sys-img.xml
      Validate XML: https://dl-ssl.google.com/android/repository/sys-img/android/sys-img.xml
      Fetching URL: https://dl-ssl.google.com/android/repository/sys-img/android-wear/sys-img.xml
      Validate XML: https://dl-ssl.google.com/android/repository/sys-img/android-wear/sys-img.xml
      Fetching URL: https://dl-ssl.google.com/android/repository/sys-img/android-tv/sys-img.xml
      Validate XML: https://dl-ssl.google.com/android/repository/sys-img/android-tv/sys-img.xml
      Fetching URL: https://dl-ssl.google.com/android/repository/sys-img/google_apis/sys-img.xml
     Validate XML: https://dl-ssl.google.com/android/repository/sys-img/google_apis/sys-img.xml
      Fetching URL: https://dl-ssl.google.com/android/repository/sys-img/x86/addon-x86.xml
      Validate XML: https://dl-ssl.google.com/android/repository/sys-img/x86/addon-x86.xml
    Refresh Sources:
      Fetching URL: https://dl-ssl.google.com/android/repository/addon.xml
      Validate XML: https://dl-ssl.google.com/android/repository/addon.xml
      Fetching URL: https://dl-ssl.google.com/android/repository/addon-6.xml
      Validate XML: https://dl-ssl.google.com/android/repository/addon-6.xml
      Fetching URL: https://dl-ssl.google.com/android/repository/extras/intel/addon.xml
      Validate XML: https://dl-ssl.google.com/android/repository/extras/intel/addon.xml
      Fetching URL: https://dl-ssl.google.com/android/repository/sys-img/android/sys-img.xml
      Validate XML: https://dl-ssl.google.com/android/repository/sys-img/android/sys-img.xml
      Fetching URL: https://dl-ssl.google.com/android/repository/sys-img/android-wear/sys-img.xml
      Validate XML: https://dl-ssl.google.com/android/repository/sys-img/android-wear/sys-img.xml
      Fetching URL: https://dl-ssl.google.com/android/repository/sys-img/android-tv/sys-img.xml
      Validate XML: https://dl-ssl.google.com/android/repository/sys-img/android-tv/sys-img.xml
      Fetching URL: https://dl-ssl.google.com/android/repository/sys-img/google_apis/sys-img.xml
      Validate XML: https://dl-ssl.google.com/android/repository/sys-img/google_apis/sys-img.xml
      Fetching URL: https://dl-ssl.google.com/android/repository/sys-img/x86/addon-x86.xml
      Validate XML: https://dl-ssl.google.com/android/repository/sys-img/x86/addon-x86.xml
    Packages available for installation or update: 3
    ----------
    id: 1 or "tools"
         Type: Tool
         Desc: Android SDK Tools, revision 22.6.2
    ----------
    id: 2 or "platform-tools"
         Type: PlatformTool
         Desc: Android SDK Platform-tools, revision 19.0.1
    ----------
    id: 3 or "addon-google_gdk-google-19"
         Type: Addon
         Desc: Glass Development Kit Preview, Android API 19, revision 11
               By Google Inc.
               Preview of the Glass Development Kit
               Requires SDK Platform Android API 19
    

I try to update it but not worked too.

**Comment by celstark2** [comment]
Let it go on that for a *long* time.  It's downloading, I believe. Run with the -v flag to see the progress.

**Comment by kived** [comment]
I don't see any error in that output. If you are still experiencing an error please open a new issue.

**Comment by vshantam** [comment]
use command after creating the buidozer.spec file..'''buildozer -v android debug deploy '''.it will show you the exact process going on in the background.i am adding an sample attachments please refer it.
![screenshot from 2017-07-29 01-05-13](https://user-images.githubusercontent.com/22946038/28733515-26bc63f8-73fa-11e7-9b07-6920152af574.png)
