### ISSUE TITLE
buildozer must be ran with sudo

### ISSUE THREAD

**Issue by jligeza** [kivy/buildozer#258]
Trying to run buildozer 0.30 (cython 0.20.1) without sudo with command `buildozer android debug run` gives this error:
http://pastebin.com/6uv1C2Mq

It works when ran with sudo, but if doing so, buildozer warns that it's unsafe and should be avoided. It's also kind of uncomfortable.

Also, this is my test buildozer.spec:
http://pastebin.com/sdCfYDw9

**Comment by inclement** [comment]
Buildozer simply doesn't need sudo. If it seems to, you probably have a permissions problem, e.g. if you run with sudo once then again without then it will have created root-owned files that cannot be overwritten.

Try deleting the ~/.buildozer dir, and the .buildozer dir in your app dir, and run it again. Also make sure you have write permissions in all the relevant directories.

**Comment by jligeza** [comment]
I've removed ~/.buildozer and project specific .buildozer directories.

Running `buildozer android debug run` produces connection errors similar to these here: https://groups.google.com/forum/#!topic/kivy-dev/gWvBErCWzDo
And ends with error ,,Aidl not found, please install it."

The only way to fix it is to run the command with `sudo` - no more connection errors, the missing packages are downloaded.

To fix privileges, I've ran `sudo chown -R my_username .buildozer` and `sudo chgrp -R my_username .buildozer` - didn't work. Received ,,ant debug'' error.

Tried to also run these for ~/.buildozer and project's bin catalog. Same error.

**Comment by inclement** [comment]
Did you try the solution in the linked mailing list thread, manually installing aidl?

**Comment by jligeza** [comment]
When I run android SDK manager without sudo, it fails to download data from google repository, so I have to use root anyway. I have ownership of all files inside.

**Comment by inclement** [comment]
Are you using an SDK installed with your package manager or otherwise installed as root? If so, you do need root to modify its files, but can just do this first then run buildozer without root.

You still shouldn't run buildozer as root, because this will modify many more files.

**Comment by jligeza** [comment]
I am not sure how to answer the question. The SDK is being automatically downloaded and installed in ~/.buildozer/android/platform/android-sdk-20 by buildozer, and it needs root to connect to google (I don't know why is that). Even if I change ownership from root to myself after that, it still doesn't work.

**Comment by 700brains** [comment]
Go to your buildozer.spec file and point the directory to where your main.py file is
eg dir=./ change it to dir=path/to/your/main.py/file
save and run again
