### ISSUE TITLE
Logo aspect ratio problem

### ISSUE THREAD

**Issue by belskikh** [kivy/buildozer#263]
When app is launching, Kivy logo looks squezzed horisontaly. It is not a circle but an oval.

**Comment by jacobcui** [comment]
Thanks for bring this up as I've got same problem for my app 'My World of Animals' on Google play market.

Jacob

**Comment by inclement** [comment]
Can you raise this issue for python-for-android rather than buildozer?

**Comment by belskikh** [comment]
inclement,
Ok.
