### ISSUE TITLE
App crash when changing orientation

### ISSUE THREAD

**Issue by belskikh** [kivy/buildozer#264]
When I change orientation from portrait to landscape, app closing. 
If in buildozer.spec file I change set 'android.minapi = 13', then all works fine.

**Comment by dessant** [comment]
I can reproduce the bug with the kivy showcase app.

**Comment by dessant** [comment]
@inclement, should we move this to p4a?

**Comment by inclement** [comment]
Yes please, although there was at least one other bug report about it which may have been partially resolved.

**Comment by dessant** [comment]
This issue was moved to kivy/python-for-android#730
