### ISSUE TITLE
Support python3

### ISSUE THREAD

**Issue by wannaphongcom** [kivy/buildozer#265]
Today, In python for android support python3.  https://github.com/kivy/python-for-android/tree/python3_support
What buildozer support python3 ?

**Comment by dessant** [comment]
@wannaphongcom, could you share the error you're facing?

**Comment by kived** [comment]
You just have to add `python3crystax` to your requirements, and possibly `hostpython3`. Buildozer itself will also run under Python 3 - if you have any problems using it, please open separate issues for those.
