### ISSUE TITLE
buildozer should be usable without internet

### ISSUE THREAD

**Issue by dessant** [kivy/buildozer#267]
Ported from https://github.com/kivy/kivy/issues/3895.

At the moment, buildozer updates metadata for its android distribution every time it's run. This is fine as long as it's run on a machine with internet, but my build machine isn't supposed to connect to the internet.

Please add a switch to disable the update behavior.
##

**Comment by Julian-O** [comment]
This is being closed, but not forgotten. It has been consolidated into issue #1727.
