### ISSUE TITLE
Is it possible to move the .buildozer folder somewhere else?

### ISSUE THREAD

**Issue by jabbalaci** [kivy/buildozer#273]
I have a Python 2 virtual environment where I installed kivy and buildozer. My virtualenv is kept separated from the project folder in a dedicated folder in `~/.virtualenvs`. I tried buildozer today and I noticed that it created two folders: 1) `~/.buildozer` , and 2) `PROJ/.buildozer` , where `PROJ` is the project directory. Is it possible to move `PROJ/.buildozer` somewhere else?

Rationale: I like keeping my project folders in Dropbox, so they are accessible on all my machines. However, `PROJ/.buildozer` is currently 251 MB (too big). I cannot move it somewhere else and put a symbolic link on it because Dropbox doesn't treat symlinks correctly and pulls in the linked folders :(

I think one should be able to set the location of this folder in the `buildozer.spec` file.

**Edit:**

OK, after diving in the source I found it. It is supported in `buildozer.spec` the following way (example):

```
[buildozer]

builddir = /home/jabba/.kivy_builddirs/kivy_project
```

Tip: such a line should be in `buildozer.spec` in a commented state. This way it would be easier to find and customize.

**Comment by AndrewSmart** [comment]
I noticed that too, that PROJ/.buildozer was awefully large. Looks like there is a per-project clone of python-for-android.
From what I can see given the architecture (with multiple projects), it may be better to instead set in `buildozer.spec`:
```
#Default setting is to clone python-for-android per project.
android.p4a_dir = /home/jabba/.buildozer/python-for-android/
```

This way project specific stuff isn't merged if you have multiple projects. I'm not sure why they're treating python-for-android differently then other things like the NDK.

**Comment by kived** [comment]
Yes, this was previously available with an undocumented spec option. It is now documented in the default spec file. In the `[buildozer]` section, you can set `build_dir = path/to/dir` and everything which would previously go into `.buildozer` will go there instead. Similarly, you can now set the output bin folder `bin_dir = path/to/dir`, and your APK files will end up there.

Do note that running buildozer in a virtualenv is not recommended, as buildozer uses a venv itself for installing pure-Python requirements, and virtualenv does not support nesting.

**Comment by jb1123** [comment]
On Ubuntu 14.04 with Buildozer 0.32dev I've tried to move .buildozer to another directory and add the buildzer.spec:

[buildozer]
# (int) Log level (0 = error only, 1 = info, 2 = debug (with command output))
log_level = 1
build_dir = /home/jb/python/buildozer

Unfortunately 'buildozer android debug' seems to ignore build_dir, creates new .buildozer and downloads software there. Any suggestions how to fix it are welcomed.

**Comment by kived** [comment]
@jb1123 Please upgrade to the release version of 0.32 or update to the latest development version 0.33dev.
