### ISSUE TITLE
Cython2 not recognized in Fedora23 ?

### ISSUE THREAD

**Issue by shakle17** [kivy/buildozer#278]
I use Fedora 23 , 64bit. When i run `buildozer --verbose android debug deploy run` i get the following error `no cython2 in ..`.  I tried reinstalling cython from rpm , from pip etc. but still error remains. I've seen similar error for Arch here : [https://github.com/kivy/kivy/issues/1185](url) 
Maybe here is the same ?

**Comment by kived** [comment]
Please provide a full log of the output.

**Comment by shakle17** [comment]
Kind of solved it already , by switching from Fedora to Ubuntu to build the APK file. Apparently Fedora23 (and bellow i assume ) confuses cython2 with cython3 somehow and building an APK there took me way longer than building it on Ubuntu ( about 35 mins , full with installing missing dependencies )

**Comment by kived** [comment]
Ok then. In that case, I'm going to close this. :)
