### ISSUE TITLE
buildozer don't work if whitespace in path

### ISSUE THREAD

**Issue by bennibaermann** [kivy/buildozer#287]
buildozer can't handle whitespace in path.

command was 

 buildozer android debug deploy run

after removing whitespaces in the path to my working directory it works (or at least more than before).

thanks for your work!

Benni

**Comment by kived** [comment]
Unfortunately, this is a bug with Python itself: https://bugs.python.org/issue12956. The "official" answer is that the Python devs don't care about spaces.

The only workaround is to not use a path with spaces.

![4234662800_monty20python20spam_answer_1_xlarge](https://cloud.githubusercontent.com/assets/1126441/13124773/a638d980-d587-11e5-987e-950e3cd39a31.jpeg)
