### ISSUE TITLE
Installation instructions for non-root?

### ISSUE THREAD

**Issue by pastcompute** [kivy/buildozer#289]
Hi

The instructions in [README.rst](https://github.com/kivy/buildozer/blob/b4f21f7/README.rst) only show how to install as root using sudo; this is not ideal security practice and also leaves working directories owned by root in the working copy. 

I was able to install and use buildozer as normal user (not requiring sudo) as follows:
- add `$HOME/.local/bin` to `$PATH`, logout and login again 
- run `python setup.py install --user`
- tested under ubuntu 15.10 with python2.7

This might need more testing under other O/S situations before finalising the instructions?
##

**Comment by kived** [comment]
User installation instructions would be a good addition.

Also, the order of the system-wide installation instructions should change (stable before dev), and the dev version should use different instructions:

```
python setup.py build
sudo pip install -e .
```

This builds with normal user credentials first, so no files will be owned by root, and installs in editable mode (meaning if you update your clone, it updates the installed version).

**Comment by AndreMiras** [comment]
Completely agree, no package should ever require to be root.
This is fixed now
