### ISSUE TITLE
Disable "Open with file manager" when USB cable is connected in virtual machine

### ISSUE THREAD

**Issue by miohtama** [kivy/buildozer#299]
There is a pop up dialog box every time you connect a device USB cable.

Because the most likely use case is adb, it would make sense to disable this dialog box hopping on your face all the time.

**Comment by tito** [comment]
Hi,

There is no relation between buildozer and this behavior which is not something we can control or would manage at all, Sorry !

(this is due to your device being detected as an usb storage)

**Comment by miohtama** [comment]
Thanks. My thinking was along the lines disable this feature in predistributed VM image.
