### ISSUE TITLE
Feature: Create a compat.py for correct PY3 support and implement it

### ISSUE THREAD

**Issue by udiboy1209** [kivy/buildozer#300]
If buildozer is to work on Py3, such a file is required. 

We can just use this file from kivy: https://github.com/kivy/kivy/blob/master/kivy/compat.py

But implementing it will require replacing current code to use `compat`.
##

**Comment by dessant** [comment]
It can be started by just adding the file, and using it where we have discussed in the other pr, all the changes doesn't have to happen at once.

**Comment by udiboy1209** [comment]
There currently might be a lot of bugs in buildozer when run in py3. Atleast getting it working in py3 under some condition is required I guess. Then addressing bugs one at a time will be possible, else no one will be able to test correctly.

**Comment by dessant** [comment]
Are you suggesting that https://github.com/kivy/buildozer/pull/293 should not use compat now because there may be other bugs in other places where using compat would be the right option?

**Comment by dessant** [comment]
The compat file can be added in a separate pr, the you can update #293, if mixing them is your main concern.

**Comment by udiboy1209** [comment]
Mixing the pr s was a concern,  but my main concern is not being able to test it until other bugs(such as the one I posted another issue about) are resolved. Probably I should rename this issue to "support py3" :P.

**Comment by udiboy1209** [comment]
There's another issue regarding supporting py3 #175.

**Comment by AndreMiras** [comment]
Python3 is now supported
