### ISSUE TITLE
Bump default min SDK to 13: Fix crash on orientation change bug

### ISSUE THREAD

**Issue by miohtama** [kivy/buildozer#302]
Currently min SDK is 9. Applications deployed with the default settings crash on orientation change. Please see:

https://github.com/kivy/python-for-android/issues/148#issuecomment-195872448

Min SDK 13 fixes the issue.

It would be better development experience to deploy with non-crashing defaults, though not sure about device market shares and such.

**Comment by dessant** [comment]
Duplicate of https://github.com/kivy/buildozer/issues/264.
