### ISSUE TITLE
arm-linux-androideabi-gcc: error

### ISSUE THREAD

**Issue by prestb** [kivy/buildozer#307]
I am getting the same error:

`arm-linux-androideabi-gcc: error: x86_64: No such file or directory
arm-linux-androideabi-gcc: error: unrecognized command line option '-arch'
error: command 'arm-linux-androideabi-gcc' failed with exit status 1
Command failed: ./distribute.sh -m "kivy"`

I'm using osx 10.8.5 and have the latest buildozer installed from the github page. Any help appreciated!
##

**Comment by inclement** [comment]
Apparently your NDK doesn't have the x86_64 build tools, I think you probably need a newer one. Are you using the `android_new` target, but downloaded the NDK some time ago? If so (or maybe even if you downloaded recently), I think buildozer just isn't aware of these dependencies yet.

**Comment by prestb** [comment]
I am using a recent version of NDK == r11 and i was surprised when the error popped up. 
Please is there any fix to this?

**Comment by kived** [comment]
Please try using the `android_new` target - i.e. `buildozer android_new debug deploy run logcat`

**Comment by awhobbs** [comment]
I'm getting the same error, but just downloaded the latest version of Crystax NDK (using python 3.5).

`arm-linux-androideabi-gcc: error: x86_64: No such file or directory
arm-linux-androideabi-gcc: error: unrecognized command line option '-arch'
error: command 'arm-linux-androideabi-gcc' failed with exit status 1`

Apparently `android_new` is now `android`, so it seems that is not the solution in this case. Any ideas?

**Comment by AndreMiras** [comment]
Could you please share the complete log? For example in my case I had the issue running buildozer in docker container that didn't have the `file` binary. First error was:
```
/home/user/.buildozer/android/platform/android-ndk-r9c/ndk-build: 158: /home/user/.buildozer/android/platform/android-ndk-r9c/ndk-build: file: not found
/bin/sh: 1: file: not found
```
And that's why I then had the second error you describe when trying to compile SDL:
```
...
ccache: error: execv of /home/user/.buildozer/android/platform/android-ndk-r9c/toolchains/arm-linux-androideabi-4.6/prebuilt/linux-x86/bin/arm-linux-androideabi-gcc failed: No such file or directory
...
```
So unless you share the complete log it's hard to help.

**Comment by awhobbs** [comment]
Sorry about that - I should have shared the complete log. Unfortunately, I no longer have it.

I managed to circumvent the problem by switching to Python 2 (my code only required a few changes). So though that's a kind of unsatisfying fix it may be a relatively easy solution if someone gets this error again.
