### ISSUE TITLE
Marshmallow sdk not found

### ISSUE THREAD

**Issue by songproducer** [kivy/buildozer#310]
Installed the Android 6 API 23 through Android Studio. How can I get Buildozer to find it?

**Comment by inclement** [comment]
Tell buildozer to use the SDK that has this api installed, e.g. via the buildozer.spec token for this path.

I did think that buildozer should download this itself if you ask for it but it isn't available. If that's the case, could you open a separate issue with the full log when buildozer fails?

**Comment by songproducer** [comment]
I tried changing sdk to 23 and now get this when running:
buildozer -v android debug

Error: Target id 'android-23' is not valid. Use 'android list targets' to get the target ids.
