### ISSUE TITLE
android.p4a_dir use old toolchain?

### ISSUE THREAD

**Issue by Tungsteno74** [kivy/buildozer#325]
Probably not very relevant but, if you use the spec `android.p4a_dir` ( for example `android.p4a_dir = /usr/local/lib/python2.7/dist-packages/pythonforandroid/`) the buildozer build your app with the old toolchain regardless of the parameters `android/android_new`.

I said that because i receive the following error:

```
valerio@valerio-virtual01-xubuntu:~/PROGETTI/opentest$ sudo -H buildozer android debug
# Check configuration tokens
Buildozer is running as root!
This is not recommended, and may lead to problems later.
Are you sure you want to continue [y/n]? y
# Ensure build layout
# Check configuration tokens
# Preparing build
# Check requirements for android
# Run 'dpkg --version'
# Cwd None
Debian "dpkg", programma di gestione dei pacchetti versione 1.17.5 (amd64).
Questo è software libero; consultare la GNU General Public Licence versione 2
o successiva per le condizioni di copia. NON c'è alcuna garanzia.
# Search for Git (git)
#  -> found at /usr/bin/git
# Search for Cython (cython)
#  -> found at /usr/local/bin/cython
# Search for Java compiler (javac)
#  -> found at /usr/lib/jvm/java-7-oracle/bin/javac
# Search for Java keytool (keytool)
#  -> found at /usr/lib/jvm/java-7-oracle/jre/bin/keytool
# Install platform
# Apache ANT found at /root/.buildozer/android/platform/apache-ant-1.9.4
# Android SDK found at /root/.buildozer/android/platform/android-sdk-20
# Android NDK found at /root/.buildozer/android/platform/android-ndk-r9c
# Check application requirements
# Run './distribute.sh -l'
# Cwd /usr/local/lib/python2.7/dist-packages/pythonforandroid/
/bin/sh: 1: ./distribute.sh: not found
# Command failed: ./distribute.sh -l
# 
# Buildozer failed to execute the last command
# The error might be hidden in the log above this error
# Please read the full log, and search for it before
# raising an issue with buildozer itself.
# In case of a bug report, please add a full log with log_level = 2
```

buildozer version:
```
sudo buildozer version
# Check configuration tokens
Buildozer is running as root!
This is not recommended, and may lead to problems later.
Are you sure you want to continue [y/n]? y
Buildozer 0.32dev
```

**Comment by kived** [comment]
It built what you told it to build - the `android` target. You need to use the `android_new` target to use the new toolchain.

**Comment by kived** [comment]
And don't run buildozer as root! It gives that warning for a reason.

**Comment by Tungsteno74** [comment]
I used both. But distribute.sh should be obsolete? or i'm wrong? idk why this error
in any case thanks

**Comment by kived** [comment]
The `android` target uses the old toolchain, with `distribute.sh`. The `android_new` target uses the new toolchain, without `distribute.sh`.

**Comment by Tungsteno74** [comment]
If i use the old toolchain with android.p4a dir as above i receive the distribute.sh problem, instead if i use the new toolchain it is builded with default python implementation (so ignore the android.p4a parameter). This is normal?

**Comment by kived** [comment]
What you described above is using old toolchain and pointing android.p4a_dir to the new toolchain. This obviously won't work. The new toolchain target (android_new) does not ignore android.p4a_dir at all, I've used this myself.

**Comment by Tungsteno74** [comment]
You could give me the path you've tested?

**Comment by kived** [comment]
Either point android.p4a_dir to a clone of the old toolchain, and use the `android` target, or else point android.p4a_dir to a clone of the new toolchain, and use the `android_new` target.
