### ISSUE TITLE
Can't add uuid pytz datetime time dbf to requirements

### ISSUE THREAD

**Issue by george72** [kivy/buildozer#329]
Buildozer builds my app and it runs on android fine with changing requirements = sqlalchemy,sqlite3,kivy  but when I want to add some columns to save a uuid and record insert time I do require more than kivy and the database, 

So when requirements = sqlalchemy,uuid,sqlite3,kivy 

or adding any combination of the following: pytz,datetime,time,dbf to requierments fails:

In this case was for uuid module:

VIRTUAL_ENV=/home/jorge/InventarioFisico/dg/.buildozer/venv
PATH=/home/jorge/InventarioFisico/dg/.buildozer/venv/bin:/home/jorge/.buildozer/android/platform/apache-ant-1.9.4/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games
MAIL=/var/mail/jorge
ANDROIDAPI=19
PWD=/home/jorge/InventarioFisico/dg/.buildozer
LANG=en_US.UTF-8
ANDROIDNDK=/home/jorge/.buildozer/android/platform/android-ndk-r9c
PS1=(venv)
PACKAGES_PATH=/home/jorge/.buildozer/android/packages
HOME=/home/jorge
SHLVL=2
ANDROIDSDK=/home/jorge/.buildozer/android/platform/android-sdk-20
LOGNAME=jorge
SSH_CONNECTION=192.168.1.53 54315 192.168.1.55 22
LESSOPEN=| /usr/bin/lesspipe %s
ANDROIDNDKVER=r9c
XDG_RUNTIME_DIR=/run/user/1000
LESSCLOSE=/usr/bin/lesspipe %s %s
_=/usr/bin/env
|## Install distribute
#|# Run 'curl http://python-distribute.org/distribute_setup.py | venv/bin/python'
#|# Cwd /home/jorge/InventarioFisico/dg/.buildozer
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
#|# Install requirement uuid in virtualenv
#|# Run 'pip install --download-cache=/home/jorge/.buildozer/cache --target=/home/jorge/InventarioFisico/dg/.buildozer/applibs uuid'
#|# Cwd /home/jorge/InventarioFisico/dg/.buildozer

Usage:
  pip install [options] <requirement specifier> [package-index-options] ...
  pip install [options] -r <requirements file> [package-index-options] ...
  pip install [options] [-e] <vcs project url> ...
  pip install [options] [-e] <local project path> ...
  pip install [options] <archive url/path> ...

no such option: --download-cache
#|# Command failed: pip install --download-cache=/home/jorge/.buildozer/cache --target=/home/jorge/InventarioFisico/dg/.buildozer/applibs uuid
#|#
#|# Buildozer failed to execute the last command
#|# The error might be hidden in the log above this error
#|# Please read the full log, and search for it before
#|# raising an issue with buildozer itself.
#|# In case of a bug report, please add a full log with log_level = 2

**Comment by george72** [comment]
Fixed with Remove pip --download-cache flag (fixes #279) #282

**Comment by kived** [comment]
FYI - uuid, datetime and time are all part of the Python standard library, and don't need to be added to requirements anyway.
