### ISSUE TITLE
Apk built with buildozer and multiple python file crashes

### ISSUE THREAD

**Issue by tanayz** [kivy/buildozer#331]
As long as I've deployed my android app using buildozer that only had one python file (main.py) that works fine in my android device.However whenever the solution has multiple py file and main.py is importing them that,upon building that apk file installs properly in android device but crashes upon launching.Any suggestion or solution for that.

**Comment by jligeza** [comment]
Post logcat (`adb logcat`) from the crash.

**Comment by tanayz** [comment]
To add to this,this app works fine in ubuntu desktop
and the buildozer.spec has following entry customization

> requirements = kivy,openssl,requests,hostpython2
> android.p4a_whitelist = lib-dynload/_json.so

also the code uses json and urllib2 as can be seen from log.The app crashes when it makes 
urllib2 request.Below is the full log from my android device.

> 
> I/ActivityManager(  475): START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=org.test.fstest/org.kivy.android.PythonActivity} from pid 778
> 
> I/ActivityManager(  475): Start proc org.test.fstest for activity org.test.fstest/org.kivy.android.PythonActivity: pid=9504 uid=10113 gids={50113, 1028, 1015}
> 
> D/dalvikvm( 9504): Late-enabling CheckJNI
> 
> I/dalvikvm( 9504): Enabling JNI app bug workarounds for target SDK version 9...
> 
> I/InputReader(  475): Reconfiguring input devices.  changes=0x00000004
> 
> I/InputReader(  475): Device reconfigured: id=2, name='elan-touchscreen', size 800x1280, orientation 1, mode 1, display id 0
> 
> I/ActivityManager(  475): Config changes=480 {1.0 310mcc?mnc en_US ldltr sw600dp w961dp h528dp 213dpi lrg land finger -keyb/v/h -nav/h s.24}
> 
> D/PhoneStatusBar(  585): mSettingsPanelGravity = 8388661
> 
> V/PythonActivity( 9504): My oncreate running
> 
> V/SDL     ( 9504): getting identifier
> 
> V/SDL     ( 9504): kind is drawable and name presplash
> 
> V/SDL     ( 9504): result is 2130837506
> 
> D/dalvikvm( 9504): GC_FOR_ALLOC freed 29K, 1% free 7631K/7700K, paused 19ms, total 20ms
> 
> I/dalvikvm-heap( 9504): Grow heap (frag case) to 7.986MB for 524304-byte allocation
> 
> D/dalvikvm( 9504): GC_FOR_ALLOC freed <1K, 1% free 8143K/8216K, paused 34ms, total 34ms
> 
> V/PythonActivity( 9504): Ready to unpack
> 
> D/dalvikvm( 9504): GC_CONCURRENT freed <1K, 1% free 8164K/8216K, paused 3ms+32ms, total 70ms
> 
> V/PythonActivity( 9504): UNPACKING!!! private files
> 
> V/SDL     ( 9504): asked to get string private_version
> 
> V/SDL     ( 9504): getting identifier
> 
> V/SDL     ( 9504): kind is string and name private_version
> 
> V/SDL     ( 9504): result is 2130968577
> 
> V/PythonActivity( 9504): Data version is 1463082439.2
> 
> V/PythonActivity( 9504): About to do super onCreate
> 
> V/SDL     ( 9504): Device: grouper
> 
> V/SDL     ( 9504): Model: Nexus 7
> 
> V/SDL     ( 9504): onCreate():null
> 
> D/dalvikvm( 9504): Trying to load lib /data/app-lib/org.test.fstest-1/libSDL2.so 0x420b9eb8
> 
> D/dalvikvm( 9504): Added shared lib /data/app-lib/org.test.fstest-1/libSDL2.so 0x420b9eb8
> 
> D/dalvikvm( 9504): Trying to load lib /data/app-lib/org.test.fstest-1/libSDL2_image.so 0x420b9eb8
> 
> V/PhoneStatusBar(  585): setLightsOn(true)
> 
> D/dalvikvm( 9504): Added shared lib /data/app-lib/org.test.fstest-1/libSDL2_image.so 0x420b9eb8
> 
> D/dalvikvm( 9504): No JNI_OnLoad found in /data/app-lib/org.test.fstest-1/libSDL2_image.so 0x420b9eb8, skipping init
> 
> D/dalvikvm( 9504): Trying to load lib /data/app-lib/org.test.fstest-1/libSDL2_mixer.so 0x420b9eb8
> 
> D/dalvikvm( 9504): Added shared lib /data/app-lib/org.test.fstest-1/libSDL2_mixer.so 0x420b9eb8
> 
> D/dalvikvm( 9504): No JNI_OnLoad found in /data/app-lib/org.test.fstest-1/libSDL2_mixer.so 0x420b9eb8, skipping init
> 
> D/dalvikvm( 9504): Trying to load lib /data/app-lib/org.test.fstest-1/libSDL2_ttf.so 0x420b9eb8
> 
> D/dalvikvm( 9504): Added shared lib /data/app-lib/org.test.fstest-1/libSDL2_ttf.so 0x420b9eb8
> 
> D/dalvikvm( 9504): No JNI_OnLoad found in /data/app-lib/org.test.fstest-1/libSDL2_ttf.so 0x420b9eb8, skipping init
> 
> D/dalvikvm( 9504): Trying to load lib /data/app-lib/org.test.fstest-1/libpython2.7.so 0x420b9eb8
> 
> D/dalvikvm( 9504): Added shared lib /data/app-lib/org.test.fstest-1/libpython2.7.so 0x420b9eb8
> 
> D/dalvikvm( 9504): No JNI_OnLoad found in /data/app-lib/org.test.fstest-1/libpython2.7.so 0x420b9eb8, skipping init
> 
> D/dalvikvm( 9504): Trying to load lib /data/app-lib/org.test.fstest-1/libmain.so 0x420b9eb8
> 
> D/dalvikvm( 9504): Added shared lib /data/app-lib/org.test.fstest-1/libmain.so 0x420b9eb8
> 
> D/dalvikvm( 9504): No JNI_OnLoad found in /data/app-lib/org.test.fstest-1/libmain.so 0x420b9eb8, skipping init
> 
> D/dalvikvm( 9504): Trying to load lib /data/data/org.test.fstest/files/lib/python2.7/lib-dynload/_io.so 0x420b9eb8
> 
> D/dalvikvm( 9504): Added shared lib /data/data/org.test.fstest/files/lib/python2.7/lib-dynload/_io.so 0x420b9eb8
> 
> D/dalvikvm( 9504): No JNI_OnLoad found in /data/data/org.test.fstest/files/lib/python2.7/lib-dynload/_io.so 0x420b9eb8, skipping init
> 
> D/dalvikvm( 9504): Trying to load lib /data/data/org.test.fstest/files/lib/python2.7/lib-dynload/unicodedata.so 0x420b9eb8
> 
> D/dalvikvm( 9504): Added shared lib /data/data/org.test.fstest/files/lib/python2.7/lib-dynload/unicodedata.so 0x420b9eb8
> 
> D/dalvikvm( 9504): No JNI_OnLoad found in /data/data/org.test.fstest/files/lib/python2.7/lib-dynload/unicodedata.so 0x420b9eb8, skipping init
> 
> D/dalvikvm( 9504): Trying to load lib /data/data/org.test.fstest/files/lib/python2.7/lib-dynload/_ctypes.so 0x420b9eb8
> 
> D/dalvikvm( 9504): Added shared lib /data/data/org.test.fstest/files/lib/python2.7/lib-dynload/_ctypes.so 0x420b9eb8
> 
> D/dalvikvm( 9504): No JNI_OnLoad found in /data/data/org.test.fstest/files/lib/python2.7/lib-dynload/_ctypes.so 0x420b9eb8, skipping init
> 
> V/PythonUtil( 9504): Loaded everything!
> 
> V/PythonActivity( 9504): Did super onCreate
> 
> V/PythonActivity( 9504): Setting env vars for start.c and Python to use
> 
> V/PythonActivity( 9504): Access to our meta-data...
> 
> I/PythonActivity( 9504): Surface will NOT be transparent
> 
> V/SDL     ( 9504): onResume()
> 
> D/libEGL  ( 9504): loaded /system/lib/egl/libEGL_tegra.so
> 
> D/libEGL  ( 9504): loaded /system/lib/egl/libGLESv1_CM_tegra.so
> 
> D/libEGL  ( 9504): loaded /system/lib/egl/libGLESv2_tegra.so
> 
> D/OpenGLRenderer( 9504): Enabling debug mode 0
> 
> V/SDL     ( 9504): surfaceCreated()
> 
> V/SDL     ( 9504): surfaceChanged()
> 
> V/SDL     ( 9504): pixel format RGB_565
> 
> V/SDL     ( 9504): Window size:1280x736
> 
> I/SDL     ( 9504): SDL_Android_Init()
> 
> I/SDL     ( 9504): SDL_Android_Init() finished!
> 
> I/python  ( 9504): Initialize Python for Android
> 
> I/python  ( 9504): Changing directory to the one provided by ANDROID_ARGUMENT
> 
> I/python  ( 9504): /data/data/org.test.fstest/files
> 
> I/python  ( 9504): Preparing to initialize python
> 
> I/python  ( 9504): crystax_python does not exist
> 
> I/python  ( 9504): Initialized python
> 
> I/python  ( 9504): AND: Init threads
> 
> I/python  ( 9504): testing python print redirection
> 
> V/SDL     ( 9504): onWindowFocusChanged(): true
> 
> W/IInputConnectionWrapper(  778): showStatusIcon on inactive InputConnection
> 
> I/Keyboard.Facilitator(  713): onFinishInput()
> 
> I/ActivityManager(  475): Displayed org.test.fstest/org.kivy.android.PythonActivity: +948ms
> 
> I/python  ( 9504): Setting up python from ANDROID_PRIVATE
> 
> I/WindowManager(  475): Screen frozen for +870ms due to Window{42ef1178 u0 Starting org.test.fstest}
> 
> I/python  ( 9504): ('Android path', ['/data/data/org.test.fstest/files/lib/python27.zip', '/data/data/org.test.fstest/files/lib/python2.7/', '/data/data/org.test.fstest/files/lib/python2.7/lib-dynload/', '/data/data/org.test.fstest/files/lib/python2.7/site-packages/', '/data/data/org.test.fstest/files'])
> 
> I/python  ( 9504): ('os.environ is', {'ANDROID_APP_PATH': '/data/data/org.test.fstest/files', 'EXTERNAL_STORAGE': '/storage/emulated/legacy', 'LOOP_MOUNTPOINT': '/mnt/obb', 'ANDROID_SOCKET_zygote': '10', 'BOOTCLASSPATH': '/system/framework/core.jar:/system/framework/conscrypt.jar:/system/framework/okhttp.jar:/system/framework/core-junit.jar:/system/framework/bouncycastle.jar:/system/framework/ext.jar:/system/framework/framework.jar:/system/framework/framework2.jar:/system/framework/telephony-common.jar:/system/framework/voip-common.jar:/system/framework/mms-common.jar:/system/framework/android.policy.jar:/system/framework/services.jar:/system/framework/apache-xml.jar:/system/framework/webviewchromium.jar', 'ANDROID_PROPERTY_WORKSPACE': '9,0', 'PATH': '/sbin:/vendor/bin:/system/sbin:/system/bin:/system/xbin', 'ANDROID_STORAGE': '/storage', 'ANDROID_BOOTLOGO': '1', 'EMULATED_STORAGE_TARGET': '/storage/emulated', 'ANDROID_ASSETS': '/system/app', 'LD_LIBRARY_PATH': '/vendor/lib:/system/lib', 'ANDROID_PRIVATE': '/data/data/org.test.fstest/files', 'ANDROID_ENTRYPOINT': 'main.pyo', 'PYTHONPATH': '/data/data/org.test.fstest/files:/data/data/org.test.fstest/files/lib', 'ANDROID_DATA': '/data', 'EMULATED_STORAGE_SOURCE': '/mnt/shell/emulated', 'PYTHON_NAME': 'python', 'ANDROID_ROOT': '/system', 'PYTHONHOME': '/data/data/org.test.fstest/files', 'ASEC_MOUNTPOINT': '/mnt/asec', 'ANDROID_ARGUMENT': '/data/data/org.test.fstest/files'})
> 
> I/python  ( 9504): ('Android kivy bootstrap done. __name__ is', '__main__')
> 
> I/python  ( 9504): ['/data/data/org.test.fstest/files/lib/python2.7/site-packages', '/data/data/org.test.fstest/files/lib/site-python']
> 
> I/python  ( 9504): AND: Ran string
> 
> I/python  ( 9504): Run user program, change dir and execute entrypoint
> 
> I/python  ( 9504): main.py
> 
> I/python  ( 9504): [INFO              ] [Logger      ] Record log in /data/data/org.test.fstest/files/.kivy/logs/kivy_16-05-12_8.txt
> 
> I/python  ( 9504): [INFO              ] [Kivy        ] v1.9.2-dev0
> 
> I/python  ( 9504): [INFO              ] [Python      ] v2.7.2 (default, May 12 2016, 09:27:35) 
> 
> I/python  ( 9504): [GCC 4.8]
> 
> I/python  ( 9504): [INFO              ] [Factory     ] 193 symbols loaded
> 
> I/python  ( 9504): [INFO              ] [Image       ] Providers: img_tex, img_dds, img_gif, img_sdl2 (img_pil, img_ffpyplayer ignored)
> 
> I/python  ( 9504): [INFO              ] [OSC         ] using <thread> for socket
> 
> I/python  ( 9504): [ERROR             ] [Input       ] AndroidJoystick is not supported by your version of linux
> 
> I/python  ( 9504): Traceback (most recent call last):
> 
> I/python  ( 9504):   File "/data/data/org.test.fstest/files/lib/python2.7/site-packages/kivy/input/providers/__init__.py", line 57, in <module>
> 
> I/python  ( 9504):     import kivy.input.providers.androidjoystick
> 
> I/python  ( 9504):   File "/data/data/org.test.fstest/files/lib/python2.7/site-packages/kivy/input/providers/androidjoystick.py", line 20, in <module>
> 
> I/python  ( 9504):     raise Exception('android lib not found.')
> 
> I/python  ( 9504): Exception: android lib not found.
> 
> I/python  ( 9504): [INFO              ] [Window      ] Provider: sdl2
> 
> I/python  ( 9504): [INFO              ] [GL          ] OpenGL version <OpenGL ES 2.0 14.01003>
> 
> I/python  ( 9504): [INFO              ] [GL          ] OpenGL vendor <NVIDIA Corporation>
> 
> I/python  ( 9504): [INFO              ] [GL          ] OpenGL renderer <NVIDIA Tegra 3>
> 
> I/python  ( 9504): [INFO              ] [GL          ] OpenGL parsed version: 2, 0
> 
> I/python  ( 9504): [INFO              ] [GL          ] Texture max size <2048>
> 
> I/python  ( 9504): [INFO              ] [GL          ] Texture max units <16>
> 
> I/python  ( 9504): [INFO              ] [Window      ] auto add sdl2 input provider
> 
> I/python  ( 9504): [INFO              ] [Window      ] virtual keyboard not allowed, single mode, not docked
> 
> I/python  ( 9504): [INFO              ] [Text        ] Provider: sdl2
> 
> D/dalvikvm(  475): GC_EXPLICIT freed 422K, 36% free 21693K/33724K, paused 4ms+10ms, total 109ms
> 
> I/python  ( 9504): [WARNING           ] [Base        ] Unknown <android> provider
> 
> I/python  ( 9504): [INFO              ] [Base        ] Start application main loop
> 
> I/python  ( 9504): [INFO              ] [GL          ] NPOT texture support is available
> 
> D/dalvikvm( 9504): GC_CONCURRENT freed 865K, 11% free 7684K/8588K, paused 9ms+2ms, total 39ms
> 
> I/python  ( 9504): [INFO              ] [Base        ] Leaving application in progress...
> 
> I/python  ( 9504):  Traceback (most recent call last):
> 
> I/python  ( 9504):    File "main.py", line 206, in <module>
> 
> I/python  ( 9504):      TestApp().run()
> 
> I/python  ( 9504):    File "/data/data/org.test.fstest/files/lib/python2.7/site-packages/kivy/app.py", line 828, in run
> 
> I/python  ( 9504):      runTouchApp()
> 
> I/python  ( 9504):    File "/data/data/org.test.fstest/files/lib/python2.7/site-packages/kivy/base.py", line 487, in runTouchApp
> 
> I/python  ( 9504):      EventLoop.window.mainloop()
> 
> I/python  ( 9504):    File "/data/data/org.test.fstest/files/lib/python2.7/site-packages/kivy/core/window/window_sdl2.py", line 633, in mainloop
> 
> I/python  ( 9504):      self._mainloop()
> 
> I/python  ( 9504):    File "/data/data/org.test.fstest/files/lib/python2.7/site-packages/kivy/core/window/window_sdl2.py", line 388, in _mainloop
> 
> I/python  ( 9504):      EventLoop.idle()
> 
> I/python  ( 9504):    File "/data/data/org.test.fstest/files/lib/python2.7/site-packages/kivy/base.py", line 330, in idle
> 
> I/python  ( 9504):      self.dispatch_input()
> 
> I/python  ( 9504):    File "/data/data/org.test.fstest/files/lib/python2.7/site-packages/kivy/base.py", line 315, in dispatch_input
> 
> I/python  ( 9504):      post_dispatch_input(*pop(0))
> 
> I/python  ( 9504):    File "/data/data/org.test.fstest/files/lib/python2.7/site-packages/kivy/base.py", line 221, in post_dispatch_input
> 
> I/python  ( 9504):      listener.dispatch('on_motion', etype, me)
> 
> I/python  ( 9504):    File "kivy/_event.pyx", line 718, in kivy._event.EventDispatcher.dispatch (kivy/_event.c:7726)
> 
> I/python  ( 9504):    File "/data/data/org.test.fstest/files/lib/python2.7/site-packages/kivy/core/window/__init__.py", line 1040, in on_motion
> 
> I/python  ( 9504):      self.dispatch('on_touch_up', me)
> 
> I/python  ( 9504):    File "kivy/_event.pyx", line 718, in kivy._event.EventDispatcher.dispatch (kivy/_event.c:7726)
> 
> I/python  ( 9504):    File "/data/data/org.test.fstest/files/lib/python2.7/site-packages/kivy/core/window/__init__.py", line 1076, in on_touch_up
> 
> I/python  ( 9504):      if w.dispatch('on_touch_up', touch):
> 
> I/python  ( 9504):    File "kivy/_event.pyx", line 718, in kivy._event.EventDispatcher.dispatch (kivy/_event.c:7726)
> 
> I/python  ( 9504):    File "/data/data/org.test.fstest/files/lib/python2.7/site-packages/kivy/uix/screenmanager.py", line 1105, in on_touch_up
> 
> I/python  ( 9504):      return super(ScreenManager, self).on_touch_up(touch)
> 
> I/python  ( 9504):    File "/data/data/org.test.fstest/files/lib/python2.7/site-packages/kivy/uix/widget.py", line 454, in on_touch_up
> 
> I/python  ( 9504):      if child.dispatch('on_touch_up', touch):
> 
> I/python  ( 9504):    File "kivy/_event.pyx", line 718, in kivy._event.EventDispatcher.dispatch (kivy/_event.c:7726)
> 
> I/python  ( 9504):    File "/data/data/org.test.fstest/files/lib/python2.7/site-packages/kivy/uix/relativelayout.py", line 294, in on_touch_up
> 
> I/python  ( 9504):      ret = super(RelativeLayout, self).on_touch_up(touch)
> 
> I/python  ( 9504):    File "/data/data/org.test.fstest/files/lib/python2.7/site-packages/kivy/uix/widget.py", line 454, in on_touch_up
> 
> I/python  ( 9504):      if child.dispatch('on_touch_up', touch):
> 
> I/python  ( 9504):    File "kivy/_event.pyx", line 718, in kivy._event.EventDispatcher.dispatch (kivy/_event.c:7726)
> 
> I/python  ( 9504):    File "/data/data/org.test.fstest/files/lib/python2.7/site-packages/kivy/uix/widget.py", line 454, in on_touch_up
> 
> I/python  ( 9504):      if child.dispatch('on_touch_up', touch):
> 
> I/python  ( 9504):    File "kivy/_event.pyx", line 718, in kivy._event.EventDispatcher.dispatch (kivy/_event.c:7726)
> 
> I/python  ( 9504):    File "/data/data/org.test.fstest/files/lib/python2.7/site-packages/kivy/uix/filechooser.py", line 544, in on_touch_up
> 
> I/python  ( 9504):      return super(FileChooserController, self).on_touch_up(touch)
> 
> I/python  ( 9504):    File "/data/data/org.test.fstest/files/lib/python2.7/site-packages/kivy/uix/relativelayout.py", line 294, in on_touch_up
> 
> I/python  ( 9504):      ret = super(RelativeLayout, self).on_touch_up(touch)
> 
> I/python  ( 9504):    File "/data/data/org.test.fstest/files/lib/python2.7/site-packages/kivy/uix/widget.py", line 454, in on_touch_up
> 
> I/python  ( 9504):      if child.dispatch('on_touch_up', touch):
> 
> I/python  ( 9504):    File "kivy/_event.pyx", line 718, in kivy._event.EventDispatcher.dispatch (kivy/_event.c:7726)
> 
> I/python  ( 9504):    File "/data/data/org.test.fstest/files/lib/python2.7/site-packages/kivy/uix/widget.py", line 454, in on_touch_up
> 
> I/python  ( 9504):      if child.dispatch('on_touch_up', touch):
> 
> I/python  ( 9504):    File "kivy/_event.pyx", line 718, in kivy._event.EventDispatcher.dispatch (kivy/_event.c:7726)
> 
> I/python  ( 9504):    File "/data/data/org.test.fstest/files/lib/python2.7/site-packages/kivy/uix/scrollview.py", line 808, in on_touch_up
> 
> I/python  ( 9504):      if self.dispatch('on_scroll_stop', touch):
> 
> I/python  ( 9504):    File "kivy/_event.pyx", line 718, in kivy._event.EventDispatcher.dispatch (kivy/_event.c:7726)
> 
> I/python  ( 9504):    File "/data/data/org.test.fstest/files/lib/python2.7/site-packages/kivy/uix/scrollview.py", line 843, in on_scroll_stop
> 
> I/python  ( 9504):      self.simulate_touch_down(touch)
> 
> I/python  ( 9504):    File "/data/data/org.test.fstest/files/lib/python2.7/site-packages/kivy/uix/scrollview.py", line 577, in simulate_touch_down
> 
> I/python  ( 9504):      ret = super(ScrollView, self).on_touch_down(touch)
> 
> I/python  ( 9504):    File "/data/data/org.test.fstest/files/lib/python2.7/site-packages/kivy/uix/widget.py", line 432, in on_touch_down
> 
> I/python  ( 9504):      if child.dispatch('on_touch_down', touch):
> 
> I/python  ( 9504):    File "kivy/_event.pyx", line 718, in kivy._event.EventDispatcher.dispatch (kivy/_event.c:7726)
> 
> I/python  ( 9504):    File "/data/data/org.test.fstest/files/lib/python2.7/site-packages/kivy/uix/scatter.py", line 510, in on_touch_down
> 
> I/python  ( 9504):      if super(Scatter, self).on_touch_down(touch):
> 
> I/python  ( 9504):    File "/data/data/org.test.fstest/files/lib/python2.7/site-packages/kivy/uix/widget.py", line 432, in on_touch_down
> 
> I/python  ( 9504):      if child.dispatch('on_touch_down', touch):
> 
> I/python  ( 9504):    File "kivy/_event.pyx", line 718, in kivy._event.EventDispatcher.dispatch (kivy/_event.c:7726)
> 
> I/python  ( 9504):    File "/data/data/org.test.fstest/files/lib/python2.7/site-packages/kivy/uix/widget.py", line 432, in on_touch_down
> 
> I/python  ( 9504):      if child.dispatch('on_touch_down', touch):
> 
> I/python  ( 9504):    File "kivy/_event.pyx", line 714, in kivy._event.EventDispatcher.dispatch (kivy/_event.c:7681)
> 
> I/python  ( 9504):    File "kivy/_event.pyx", line 1224, in kivy._event.EventObservers.dispatch (kivy/_event.c:13524)
> 
> I/python  ( 9504):    File "kivy/_event.pyx", line 1108, in kivy._event.EventObservers._dispatch (kivy/_event.c:12356)
> 
> I/python  ( 9504):    File "/data/data/org.test.fstest/files/lib/python2.7/site-packages/kivy/lang/builder.py", line 64, in custom_callback
> 
> I/python  ( 9504):      exec(__kvlang__.co_value, idmap)
> 
> I/python  ( 9504):    File "/data/data/org.test.fstest/files/lib/python2.7/site-packages/kivy/data/style.kv", line 378, in <module>
> 
> I/python  ( 9504):      on_touch_down: self.collide_point(*args[1].pos) and ctx.controller().entry_touched(self, args[1])
> 
> I/python  ( 9504):    File "/data/data/org.test.fstest/files/lib/python2.7/site-packages/kivy/uix/filechooser.py", line 605, in entry_touched
> 
> I/python  ( 9504):      self.selection = [abspath(join(self.path, entry.path)), ]
> 
> I/python  ( 9504):    File "kivy/properties.pyx", line 410, in kivy.properties.Property.__set__ (kivy/properties.c:5172)
> 
> I/python  ( 9504):    File "kivy/properties.pyx", line 735, in kivy.properties.ListProperty.set (kivy/properties.c:11327)
> 
> I/python  ( 9504):    File "kivy/properties.pyx", line 448, in kivy.properties.Property.set (kivy/properties.c:5934)
> 
> I/python  ( 9504):    File "kivy/properties.pyx", line 503, in kivy.properties.Property.dispatch (kivy/properties.c:6615)
> 
> I/python  ( 9504):    File "kivy/_event.pyx", line 1224, in kivy._event.EventObservers.dispatch (kivy/_event.c:13524)
> 
> I/python  ( 9504):    File "kivy/_event.pyx", line 1106, in kivy._event.EventObservers._dispatch (kivy/_event.c:12328)
> 
> I/python  ( 9504):    File "/data/data/org.test.fstest/files/lib/python2.7/site-packages/kivy/lang/builder.py", line 64, in custom_callback
> 
> I/python  ( 9504):      exec(__kvlang__.co_value, idmap)
> 
> I/python  ( 9504):    File "<string>", line 30, in <module>
> 
> I/python  ( 9504):    File "main.py", line 190, in update_stat
> 
> I/python  ( 9504):      self.imgstat.text = dp.scan(label_stat)
> 
> I/python  ( 9504):    File "main.py", line 162, in scan
> 
> I/python  ( 9504):      no = int(self.azapi(test_data))
> 
> I/python  ( 9504):    File "main.py", line 115, in azapi
> 
> I/python  ( 9504):      response = urllib2.urlopen(req)
> 
> I/python  ( 9504):    File "/home/tanay/Documents/deptest/.buildozer/android/platform/build/build/other_builds/python2-openssl/armeabi-v7a/python2/python-install/lib/python2.7/urllib2.py", line 126, in urlopen
> 
> I/python  ( 9504):    File "/home/tanay/Documents/deptest/.buildozer/android/platform/build/build/other_builds/python2-openssl/armeabi-v7a/python2/python-install/lib/python2.7/urllib2.py", line 394, in open
> 
> I/python  ( 9504):    File "/home/tanay/Documents/deptest/.buildozer/android/platform/build/build/other_builds/python2-openssl/armeabi-v7a/python2/python-install/lib/python2.7/urllib2.py", line 412, in _open
> 
> I/python  ( 9504):    File "/home/tanay/Documents/deptest/.buildozer/android/platform/build/build/other_builds/python2-openssl/armeabi-v7a/python2/python-install/lib/python2.7/urllib2.py", line 372, in _call_chain
> 
> I/python  ( 9504):    File "/home/tanay/Documents/deptest/.buildozer/android/platform/build/build/other_builds/python2-openssl/armeabi-v7a/python2/python-install/lib/python2.7/urllib2.py", line 1207, in https_open
> 
> I/python  ( 9504):    File "/home/tanay/Documents/deptest/.buildozer/android/platform/build/build/other_builds/python2-openssl/armeabi-v7a/python2/python-install/lib/python2.7/urllib2.py", line 1174, in do_open
> 
> I/python  ( 9504):  urllib2.URLError: <urlopen error [Errno 4] non-recoverable failure in name resolution.>
> 
> I/python  ( 9504): Python for android ended.

**Comment by tanayz** [comment]
It worked when I've put all the content in a single python file and gave that the INTERNET permission.However still need to check the multiple python file case.

**Comment by kived** [comment]
Yes, you need the INTERNET permission to access the internet. Multiple Python files work just fine - my primary app has 506 .py files, not including all the libraries I use. If you need more help with this, please [join our IRC channel #kivy on freenode](https://kivy.org/docs/contact.html#irc).
