### ISSUE TITLE
outdated openssl

### ISSUE THREAD

**Issue by jligeza** [kivy/buildozer#332]
I'm not sure if this issue belongs here on in p4a, but: 

Buildozer clones p4a for my android app. For some unknown reasons, it uses an old version of `openssl` (1.0.1p - can be seen in `openssl/recipe.sh`), what causes google's play store to display this security warning:

> Please migrate your app(s) to OpenSSL 1.02f/1.01r or higher as soon as possible and increment the version number of the upgraded APK. Beginning July 11, 2016, Google Play will block publishing of any new apps or updates that use older versions of OpenSSL.  

When I look into recipes on p4a, it says it uses version `1.0.2g`, and so says `p4a recipes` in my local installation.

From where does it get that `1.0.1p` version? It is not written anywhere.

PS: in my buildozer.spec requirements, I have written just `openssl`, no version specified.

**Comment by kived** [comment]
Buildozer does not control recipes in python-for-android or kivy-ios. Any issues with such recipes would need to be taken up in the respective repository. That said, you're using the old toolchain target (`android`) rather than the new toolchain target (`android_new`), which is why you're seeing the old version of OpenSSL. Try upgrading buildozer to master (`sudo pip install https://github.com/kivy/buildozer/archive/master.zip`) and building with the new toolchain (`buildozer android_new debug deploy`).

**Comment by kshkaran2k** [comment]
I was also facing the same issue. After exploring(hit and trail) on the system, I found the solution. Proceed with the following steps.

- Download the 1.0.2f or 1.0.1r or the higher version of openssl.
- Goto `openssl` folder in configured buildozer. It will be present in `~/.buildozer/android/packages/openssl`.
- Replace the old openssl i.e. `openssl-x-x-x.tar.gz` with the latest downloaded one (tar.gz).

**Comment by FilipDem** [comment]
I did the same as mentioned by kshkaran2k, but did not help. I downloaded OpenSSL version 1.1.0e, but the APK was anyway refused on Google Play due to old OpenSSL version. Migration to the new toolchain is not yet possible because I use lxml and there is not yet a recipe migrated.

**Comment by FilipDem** [comment]
And what is very strange... I even don't use OpenSSL (I don't have it in my requirements). And google suggested to do first the check with `unzip -p YourApp.apk | strings | grep "OpenSSL"`. And this doesn't even find OpenSSL in my APK. Would this be the problem? That there is no OpenSSL?

**Comment by inclement** [comment]
I've made the PR at https://github.com/kivy/python-for-android/pull/1017 to update the version, but haven't tested it. If anyone would like to test it and confirm it works, I'll merge it.

@FilipDem I don't know what would be wrong if you don't have openssl at all. Have you ever built with openssl before?

**Comment by FilipDem** [comment]
I never build with OpenSSL  before. Will look if I can find a contact point at google...

**Comment by ivanlamega** [comment]
I have this same problem, I've updated openssl to version 1.0.2h.
But I still have the same problem. (I use android_new).

I have executed this command: unzip -p YourApp.apk | Strings | Grep "OpenSSL"
And gives me this result:

```
OpenSSLDie
DH_OpenSSL
DSA_OpenSSL
ECDSA_OpenSSL
ECDH_OpenSSL
UI_OpenSSL
OpenSSL 1.0.2h  3 May 2016
%s(%d): OpenSSL internal error, assertion failed: %s
OpenSSL DH Method
OpenSSL X9.42 DH method
OpenSSL PKCS#3 DH method
OpenSSL CMAC method
OpenSSL HMAC method
OpenSSL EC algorithm
OpenSSL RSA method
OpenSSL DSA method
OpenSSL ECDSA method
OpenSSL ECDH method
You need to read the OpenSSL FAQ, http://www.openssl.org/support/faq.html
OpenSSL default
OpenSSL default user interface
SSLv3 part of OpenSSL 1.0.2h  3 May 2016
TLSv1 part of OpenSSL 1.0.2h  3 May 2016
nopqrsDTLSv1 part of OpenSSL 1.0.2h  3 May 2016
MD5 part of OpenSSL 1.0.2h  3 May 2016
SHA1 part of OpenSSL 1.0.2h  3 May 2016
SHA-256 part of OpenSSL 1.0.2h  3 May 2016
SHA-512 part of OpenSSL 1.0.2h  3 May 2016
Big Number part of OpenSSL 1.0.2h  3 May 2016
EC part of OpenSSL 1.0.2h  3 May 2016
(1RSA part of OpenSSL 1.0.2h  3 May 2016
Diffie-Hellman part of OpenSSL 1.0.2h  3 May 2016
Stack part of OpenSSL 1.0.2h  3 May 2016
lhash part of OpenSSL 1.0.2h  3 May 2016
EVP part of OpenSSL 1.0.2h  3 May 2016
ASN.1 part of OpenSSL 1.0.2h  3 May 2016
PEM part of OpenSSL 1.0.2h  3 May 2016
X.509 part of OpenSSL 1.0.2h  3 May 2016
DES part of OpenSSL 1.0.2h  3 May 2016
libdes part of OpenSSL 1.0.2h  3 May 2016
AES part of OpenSSL 1.0.2h  3 May 2016
RC2 part of OpenSSL 1.0.2h  3 May 2016
IDEA part of OpenSSL 1.0.2h  3 May 2016
CAMELLIA part of OpenSSL 1.0.2h  3 May 2016
EDSA part of OpenSSL 1.0.2h  3 May 2016
ECDSA part of OpenSSL 1.0.2h  3 May 2016
ECDH part of OpenSSL 1.0.2h  3 May 2016
RAND part of OpenSSL 1.0.2h  3 May 2016
CONF part of OpenSSL 1.0.2h  3 May 2016
CONF_def part of OpenSSL 1.0.2h  3 May 2016
TXT_DB part of OpenSSL 1.0.2h  3 May 2016
RC4 part of OpenSSL 1.0.2h  3 May 2016
OpenSSLDie
DSA_OpenSSL
ECDSA_OpenSSL
DH_OpenSSL
ECDH_OpenSSL
OpenSSL_add_all_ciphers
OpenSSL_add_all_digests
UI_OpenSSL
%s(%d): OpenSSL internal error, assertion failed: %s
OpenSSL 1.0.2h  3 May 2016
OpenSSL HMAC method
OpenSSL EC algorithm
OpenSSL RSA method
OpenSSL DSA method
OpenSSL ECDSA method
OpenSSL DH Method
OpenSSL X9.42 DH method
OpenSSL PKCS#3 DH method
OpenSSL ECDH method
You need to read the OpenSSL FAQ, http://www.openssl.org/support/faq.html
OpenSSL default
OpenSSL default user interface
OpenSSL CMAC method
MD4 part of OpenSSL 1.0.2h  3 May 2016
MD5 part of OpenSSL 1.0.2h  3 May 2016
SHA part of OpenSSL 1.0.2h  3 May 2016
SHA1 part of OpenSSL 1.0.2h  3 May 2016
SHA-256 part of OpenSSL 1.0.2h  3 May 2016
SHA-512 part of OpenSSL 1.0.2h  3 May 2016
RIPE-MD160 part of OpenSSL 1.0.2h  3 May 2016
DES part of OpenSSL 1.0.2h  3 May 2016
libdes part of OpenSSL 1.0.2h  3 May 2016
 !"#$% !"#$%&'()*+,-./0123456789:;<=>?@ABCD./0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyzAES part of OpenSSL 1.0.2h  3 May 2016
RC2 part of OpenSSL 1.0.2h  3 May 2016
RC4 part of OpenSSL 1.0.2h  3 May 2016
IDEA part of OpenSSL 1.0.2h  3 May 2016
:Blowfish part of OpenSSL 1.0.2h  3 May 2016
\CAST part of OpenSSL 1.0.2h  3 May 2016
OCAMELLIA part of OpenSSL 1.0.2h  3 May 2016
Big Number part of OpenSSL 1.0.2h  3 May 2016
EC part of OpenSSL 1.0.2h  3 May 2016
(1RSA part of OpenSSL 1.0.2h  3 May 2016
ggenDSA part of OpenSSL 1.0.2h  3 May 2016
ECDSA part of OpenSSL 1.0.2h  3 May 2016
Diffie-Hellman part of OpenSSL 1.0.2h  3 May 2016
ECDH part of OpenSSL 1.0.2h  3 May 2016
Stack part of OpenSSL 1.0.2h  3 May 2016
lhash part of OpenSSL 1.0.2h  3 May 2016
RAND part of OpenSSL 1.0.2h  3 May 2016
EVP part of OpenSSL 1.0.2h  3 May 2016
ASN.1 part of OpenSSL 1.0.2h  3 May 2016
PEM part of OpenSSL 1.0.2h  3 May 2016
X.509 part of OpenSSL 1.0.2h  3 May 2016
CONF part of OpenSSL 1.0.2h  3 May 2016
CONF_def part of OpenSSL 1.0.2h  3 May 2016
TXT_DB part of OpenSSL 1.0.2h  3 May 2016
Returns 1 if the OpenSSL PRNG has been seeded with enough data and 0 if not.
Mix string into the OpenSSL PRNG state.  entropy (a float) is a lower
```
