### ISSUE TITLE
no way to change bootstrap

### ISSUE THREAD

**Issue by jligeza** [kivy/buildozer#341]
There should be an option in buildozer.spec allowing to switch bootstraps between pygame, sdl2 and webview. I would like to test the new webview, but buildozer forces the sdl2.

**Comment by kived** [comment]
You can now do this with buildozer master using `android.bootstrap = webview`.

**Comment by andresmrm** [comment]
@jligeza, did you managed to get it working?
The webview mode worked for me using p4a directly, but with buildozer I'm getting a black screen.
Maybe it's the `port` parameter that is missing? I don't know how to set it in the spec file.

**Comment by jligeza** [comment]
@andresmrm Yes, I managed to launch it, here is the spec file: http://pastebin.com/un7szCmJ
However, it was very buggy and kept crashing all the time, probably because I used python 2 instead of 3.

**Comment by andresmrm** [comment]
Thanks, I'll test it.

Strange you say that it was buggy for you. For me the Flask webview worked much better then Kivy (with the last one, even a simple button was crashing randomly, with the first, I'm yet to see a crash).
But I'm building directly with `p4a`:
https://github.com/andresmrm/sshd-switch/blob/master/build.sh
Using `ANDROIDAPI="21"` and `ANDROIDNDKVER="r12b"`.
I'm not sure but it seems the `flask` requirement installs `python2` and `python3` (not `python3crystax`). But it only worked installing `p4a` using `pip` from Python 2 and not from Python 3...
