### ISSUE TITLE
Unavailability of important packages

### ISSUE THREAD

**Issue by tanayz** [kivy/buildozer#343]
Upto version 0.32 dev below are the supported packages in buildozer
Available modules: android apsw audiostream bidi boost cherrypy c_igraph click cprotobuf cymunk django docutils ecdsa enum34 evdev ffmpeg ffmpeg2 ffpyplayer ffpyplayer_tito flask freetype gevent greenlet harfbuzz hostpython igraph itsdangerous jinja2 jpeg kivent_core kivent_cymunk kivy leveldb libevent libpq libsodium libswift libtorrent libxml2 libxslt libyaml lxml m2crypto markupsafe midistream msgpack mysql_connector netifaces numpy opencv openssl paramiko pil plyer plyvel png polygon protobuf psutil psycopg2 pyasn1 pycrypto pygame pyjnius pylibpd pyopenssl pyparsing pyqrcode python pyyaml sdl setuptools six sqlalchemy sqlite3 storm swift thrift twisted txws werkzeug wokkel zeroconf zope#
However there are other highly used important python packages,I was wondering how I can manage using that with buildozer,such as pandas,json,urllib2,scikit-learn etc.

**Comment by Kovak** [comment]
If a library is pure python it should work fine. If it is not pure python you will need to write some compilation recipe similar to the other supported packages.

**Comment by kived** [comment]
> requirements: List, Python modules or extensions that your application requires.
> 
> The requirements can be either a name of a recipe in the Python-for-android project, or a pure-Python package. For example, if your application requires Kivy and requests, you need to write:
> 
> `requirements = kivy,requests`

http://buildozer.readthedocs.io/en/latest/specifications.html

**Comment by tanayz** [comment]
@kived I've tried that and got the list from there only.Surprisingly when I try 
requirements = kivy,numpy
it works as numpy is among the listed supported packages,but when I try 
requirements = kivy,requests 
I get error that says
Available modules: android apsw audiostream bidi boost cherrypy c_igraph click cprotobuf cymunk django docutils ecdsa enum34 evdev ffmpeg ffmpeg2 ffpyplayer ffpyplayer_tito flask freetype gevent greenlet harfbuzz hostpython igraph itsdangerous jinja2 jpeg kivent_core kivent_cymunk kivy leveldb libevent libpq libsodium libswift libtorrent libxml2 libxslt libyaml lxml m2crypto markupsafe midistream msgpack mysql_connector netifaces numpy opencv openssl paramiko pil plyer plyvel png polygon protobuf psutil psycopg2 pyasn1 pycrypto pygame pyjnius pylibpd pyopenssl pyparsing pyqrcode python pyyaml sdl setuptools six sqlalchemy sqlite3 storm swift thrift twisted txws werkzeug wokkel zeroconf zope
#

**Comment by kived** [comment]
I don't see any error when I build with those requirements (`kivy,requests`), and my APK builds fine. That message prints out, but it always prints out - it's not an error, just information about the available recipes. If you are having an issue with actually building an APK, please make sure you have set `log_level = 2` in the appropriate section of buildozer.spec, and submit the *entire build log* in a new issue.

Also, make sure you're running the latest release of buildozer (0.32, released 2 days ago) or the development version (GitHub master). You also might try the `android_new` target (i.e. `buildozer android_new debug`), which uses the new version of the python-for-android toolchain supporting SDL2 (the old toolchain uses pygame and SDL1.2).
