### ISSUE TITLE
Requirement example Requirements = kivy,requests fails

### ISSUE THREAD

**Issue by tanayz** [kivy/buildozer#344]
I have created a simple python file and for that after creating buildozer.spec with buildozer.init when I added requests at to make
Requirements = kivy,requests
the apk creation fails with both command buildozer -v android debug and builozer android_new debug
I'm using the latest version 0.33 of buildozer and surprisingly when I try Requiremets=kivy,numpy and try buildozer -v android debug that succeeds but buildozer android_new debug fails in that case as well with same error like what I see for Requirements = kivy,requests

Here is the full log

    tanay@ubuntu:~/Documents/deptest$ buildozer -v android debug
    # Check configuration tokens
    # Ensure build layout
    # Check configuration tokens
    # Preparing build
    # Check requirements for android
    # Run 'dpkg --version'
    # Cwd None
    Debian `dpkg' package management program version 1.17.5 (amd64).
    This is free software; see the GNU General Public License version 2 or
    later for copying conditions. There is NO warranty.
    # Search for Git (git)
    #  -> found at /usr/bin/git
    # Search for Cython (cython)
    #  -> found at /home/tanay/anaconda2/bin/cython
    # Search for Java compiler (javac)
    #  -> found at /usr/lib/jvm/java-7-openjdk-amd64/bin/javac
    # Search for Java keytool (keytool)
    #  -> found at /usr/lib/jvm/java-7-openjdk-amd64/jre/bin/keytool
    # Install platform
    # Apache ANT found at /home/tanay/.buildozer/android/platform/apache-ant-1.9.4
    # Android SDK found at /home/tanay/.buildozer/android/platform/android-sdk-20
    # Android NDK found at /home/tanay/.buildozer/android/platform/android-ndk-r9c
    # Check application requirements
    # Run './distribute.sh -l'
    # Cwd /home/tanay/Documents/deptest/.buildozer/android/platform/python-for-android
    Available modules: android apsw audiostream bidi boost cherrypy c_igraph click cprotobuf cymunk django docutils ecdsa enum34 evdev ffmpeg ffmpeg2 ffpyplayer ffpyplayer_tito flask freetype gevent greenlet harfbuzz hostpython igraph itsdangerous jinja2 jpeg kivent_core kivent_cymunk kivy leveldb libevent libpq libsodium libswift libtorrent libxml2 libxslt libyaml lxml m2crypto markupsafe midistream msgpack mysql_connector netifaces numpy opencv openssl paramiko pil plyer plyvel png polygon protobuf psutil psycopg2 pyasn1 pycrypto pygame pyjnius pylibpd pyopenssl pyparsing pyqrcode python pyyaml sdl setuptools six sqlalchemy sqlite3 storm swift thrift twisted txws werkzeug wokkel zeroconf zope
    # Remove directory and subdirectory /home/tanay/Documents/deptest/.buildozer/applibs
    # Create directory /home/tanay/Documents/deptest/.buildozer/applibs
    # Run 'bash -c "source venv/bin/activate && env"'
    # Cwd /home/tanay/Documents/deptest/.buildozer
    bash: venv/bin/activate: No such file or directory
    # Command failed: bash -c "source venv/bin/activate && env"
    # 
    # Buildozer failed to execute the last command
    # The error might be hidden in the log above this error
    # Please read the full log, and search for it before
    # raising an issue with buildozer itself.
    # In case of a bug report, please add a full log with log_level = 2
    tanay@ubuntu:~/Documents/deptest$ buildozer android_new debug
    # Check configuration tokens
    # Ensure build layout
    # Check configuration tokens
    # Preparing build
    # Check requirements for android
    # Run 'dpkg --version'
    # Cwd None
    Debian `dpkg' package management program version 1.17.5 (amd64).
    This is free software; see the GNU General Public License version 2 or
    later for copying conditions. There is NO warranty.
    # Search for Git (git)
    #  -> found at /usr/bin/git
    # Search for Cython (cython)
    #  -> found at /home/tanay/anaconda2/bin/cython
    # Search for Java compiler (javac)
    #  -> found at /usr/lib/jvm/java-7-openjdk-amd64/bin/javac
    # Search for Java keytool (keytool)
    #  -> found at /usr/lib/jvm/java-7-openjdk-amd64/jre/bin/keytool
    # Install platform
    # Apache ANT found at /home/tanay/.buildozer/android/platform/apache-ant-1.9.4
    # Android SDK found at /home/tanay/.buildozer/android/platform/android-sdk-20
    # Android NDK found at /home/tanay/.buildozer/android/platform/android-ndk-r9c
    # Check application requirements
    # Check garden requirements
    # Compile platform
    # Run 'python -m pythonforandroid.toolchain --color=always --storage-dir=/home/tanay/Documents/deptest/.buildozer/android/platform/build create --dist_name=fstest --bootstrap=sdl2 --requirements=kivy,requests --arch armeabi-v7a --copy-libs'
    # Cwd /home/tanay/Documents/deptest/.buildozer/android/platform/python-for-android-master
    Traceback (most recent call last):
      File "/home/tanay/anaconda2/lib/python2.7/runpy.py", line 162, in _run_module_as_main
        "__main__", fname, loader, pkg_name)
      File "/home/tanay/anaconda2/lib/python2.7/runpy.py", line 72, in _run_code
        exec code in run_globals
      File "/home/tanay/Documents/deptest/.buildozer/android/platform/python-for-android-master/pythonforandroid/toolchain.py", line 24, in <module>
        import sh
    ImportError: No module named sh
    # Command failed: python -m pythonforandroid.toolchain --color=always --storage-dir=/home/tanay/Documents/deptest/.buildozer/android/platform/build create --dist_name=fstest --bootstrap=sdl2 --requirements=kivy,requests --arch armeabi-v7a --copy-libs
    # 
    # Buildozer failed to execute the last command
    # The error might be hidden in the log above this error
    # Please read the full log, and search for it before
    # raising an issue with buildozer itself.
    # In case of a bug report, please add a full log with log_level = 2

**Comment by inclement** [comment]
You don't have the sh module, as the traceback says. Install it.
