### ISSUE TITLE
App built with buildozer does not open on android

### ISSUE THREAD

**Issue by batth** [kivy/buildozer#356]
Hi,

I was working on an app which stores some data in kivy json storage. It works fine on desktop testing. When I deployed it on android, the app refuses to open.

Do I need to specify json call in buildozer.spec file?

Please help.

Thanks

**Comment by redfast00** [comment]
Can you give the buildozer.spec / source code?

**Comment by batth** [comment]
In python code I am using below:

from kivy.storage.jsonstore import JsonStore
store = JsonStore('score.json')

and then I am putting some value to store and getting the value from store. It works fine on desktop.

The buildozer.spec file is normal one, I added nothing specific to json in there.

**Comment by batth** [comment]
This issue can be closed. 

I have resolved it by adding below to buildozer.spec file:

# (list) Source files to include (let empty to include all the files)
source.include_exts = py,png,kv,json
