### ISSUE TITLE
Plyer not available in buildozer android_new

### ISSUE THREAD

**Issue by tanayz** [kivy/buildozer#358]
While creating the apk using the command 
`buildozer android_new debug`
with 
`requirements = kivy,hostpython2,plyer`
the building failed with usual error that it shows when a recipe isn't available
however when I ran 
`buildozer -v android debug`
with 
`requirements = kivy,plyer`
it succeeded. So it seems android_new is not having the plyer recipe that the old one has.
Can you check this.

**Comment by kived** [comment]
Plyer does not need a recipe as it is a pure-Python package. Make sure you're running the most recent buildozer release (0.32) or the development version from github (0.33dev), and that you're not running buildozer in a virtualenv. Building packages including Plyer with android_new does work fine.

**Comment by tanayz** [comment]
My buildozer is 0.33dev and I'm not running buildozer in virtualenv and still the error appears.Attached is the error log
tanay@ubuntu:~/Documents/ktest/t1$ buildozer android_new debug > log.txt
[INFO]:    This python-for-android revamp is an experimental alpha release!
[INFO]:    It should work (mostly), but you may experience missing features or bugs.
[INFO]:    Will compile for the following archs: armeabi-v7a
[INFO]:    Found Android API target in $ANDROIDAPI
[INFO]:    Available Android APIs are (19)
[INFO]:    Requested API target 19 is available, continuing.
[INFO]:    Found NDK dir in $ANDROIDNDK
[INFO]:    Got NDK version from $ANDROIDNDKVER
[INFO]:    Using Google NDK r9c
[INFO]:    Found virtualenv at /home/tanay/anaconda2/bin/virtualenv
[INFO]:    Found the following toolchain versions: ['4.6', '4.8', 'clang3.3']
[INFO]:    Picking the latest gcc toolchain, here 4.8
[INFO]:    No existing dists meet the given requirements!
[INFO]:    No dist exists that meets your requirements, so one will be built.
[INFO]:    Bootstrap requires recipes ['sdl2', ('python2', 'python3crystax')]
[INFO]:    No recipe named plyer; will attempt to install with pip
[INFO]:    Loaded recipe sdl2 (depends on [('python2', 'python3crystax'), 'sdl2_image', 'sdl2_mixer', 'sdl2_ttf'], conflicts ['sdl', 'pygame', 'pygame_bootstrap_components'])
[INFO]:    Loaded recipe hostpython2 (depends on [], conflicts ['hostpython3'])
[INFO]:    Loaded recipe kivy (depends on ['pyjnius', ('sdl2', 'pygame'), ('python2', 'python3crystax')])
[INFO]:    Loaded recipe sdl2_image (depends on [])
[INFO]:    Loaded recipe sdl2_mixer (depends on [])
[INFO]:    Loaded recipe sdl2_ttf (depends on [])
[INFO]:    Loaded recipe pyjnius (depends on ['six', ('python2', 'python3crystax'), ('sdl2', 'sdl', 'webviewjni')])
[INFO]:    Loaded recipe six (depends on [('python2', 'python3crystax')])
[INFO]:    Found multiple valid recipe sets:
[INFO]:        ['six', 'sdl2', u'kivy', 'sdl2_ttf', u'hostpython2', 'sdl2_mixer', 'sdl2_image', 'pyjnius', 'python2']
[INFO]:        ['sdl2', 'six', 'sdl2_ttf', u'hostpython2', 'python3crystax', 'sdl2_mixer', 'sdl2_image', 'pyjnius', u'kivy']
[INFO]:    Using the first of these: ['six', 'sdl2', u'kivy', 'sdl2_ttf', u'hostpython2', 'sdl2_mixer', 'sdl2_image', 'pyjnius', 'python2']
[INFO]:    The selected bootstrap is sdl2
[INFO]:    # Creating dist with sdl2 bootstrap
[INFO]:    Dist will have name mycam and recipes (kivy, plyer, hostpython2)
[INFO]:    -> running cp -r /home/tanay/Documents/ktest/t1/.buildozer/android/platform/python-for-android-master/pythonforandr...(and 126 more)
[INFO]:    -> directory context /home/tanay/Documents/ktest/t1/.buildozer/android/platform/build/build/bootstrap_builds/sdl2-python2
[INFO]:    <- directory context /home/tanay/Documents/ktest/t1/.buildozer/android/platform/python-for-android-master
[INFO]:    Recipe build order is [u'hostpython2', 'python2', 'sdl2_image', 'sdl2_mixer', 'sdl2_ttf', 'sdl2', 'six', 'pyjnius', u'kivy']
[INFO]:    The requirements (plyer) were not found as recipes, they will be installed with pip.
[INFO]:    # Downloading recipes 
[INFO]:    Downloading hostpython2
[INFO]:    -> running mkdir -p /home/tanay/Documents/ktest/t1/.buildozer/android/platform/build/packages/hostpython2
[INFO]:    -> directory context /home/tanay/Documents/ktest/t1/.buildozer/android/platform/build/packages/hostpython2
[INFO]:    -> running basename http://python.org/ftp/python/2.7.2/Python-2.7.2.tar.bz2
[INFO]:    hostpython2 download already cached, skipping
[WARNING]: Should check headers here! Skipping for now.
[INFO]:    <- directory context /home/tanay/Documents/ktest/t1/.buildozer/android/platform/python-for-android-master
[INFO]:    Downloading python2
[INFO]:    -> running mkdir -p /home/tanay/Documents/ktest/t1/.buildozer/android/platform/build/packages/python2
[INFO]:    -> directory context /home/tanay/Documents/ktest/t1/.buildozer/android/platform/build/packages/python2
[INFO]:    -> running basename http://python.org/ftp/python/2.7.2/Python-2.7.2.tar.bz2
[INFO]:    python2 download already cached, skipping
[WARNING]: Should check headers here! Skipping for now.
[INFO]:    <- directory context /home/tanay/Documents/ktest/t1/.buildozer/android/platform/python-for-android-master
[INFO]:    Downloading sdl2_image
[INFO]:    -> running mkdir -p /home/tanay/Documents/ktest/t1/.buildozer/android/platform/build/packages/sdl2_image
[INFO]:    -> directory context /home/tanay/Documents/ktest/t1/.buildozer/android/platform/build/packages/sdl2_image
[INFO]:    -> running basename https://www.libsdl.org/projects/SDL_image/release/SDL2_image-2.0.1.tar.gz
[INFO]:    sdl2_image download already cached, skipping
[WARNING]: Should check headers here! Skipping for now.
[INFO]:    <- directory context /home/tanay/Documents/ktest/t1/.buildozer/android/platform/python-for-android-master
[INFO]:    Downloading sdl2_mixer
[INFO]:    -> running mkdir -p /home/tanay/Documents/ktest/t1/.buildozer/android/platform/build/packages/sdl2_mixer
[INFO]:    -> directory context /home/tanay/Documents/ktest/t1/.buildozer/android/platform/build/packages/sdl2_mixer
[INFO]:    -> running basename https://www.libsdl.org/projects/SDL_mixer/release/SDL2_mixer-2.0.1.tar.gz
[INFO]:    sdl2_mixer download already cached, skipping
[WARNING]: Should check headers here! Skipping for now.
[INFO]:    <- directory context /home/tanay/Documents/ktest/t1/.buildozer/android/platform/python-for-android-master
[INFO]:    Downloading sdl2_ttf
[INFO]:    -> running mkdir -p /home/tanay/Documents/ktest/t1/.buildozer/android/platform/build/packages/sdl2_ttf
[INFO]:    -> directory context /home/tanay/Documents/ktest/t1/.buildozer/android/platform/build/packages/sdl2_ttf
[INFO]:    -> running basename https://www.libsdl.org/projects/SDL_ttf/release/SDL2_ttf-2.0.14.tar.gz
[INFO]:    sdl2_ttf download already cached, skipping
[WARNING]: Should check headers here! Skipping for now.
[INFO]:    <- directory context /home/tanay/Documents/ktest/t1/.buildozer/android/platform/python-for-android-master
[INFO]:    Downloading sdl2
[INFO]:    -> running mkdir -p /home/tanay/Documents/ktest/t1/.buildozer/android/platform/build/packages/sdl2
[INFO]:    -> directory context /home/tanay/Documents/ktest/t1/.buildozer/android/platform/build/packages/sdl2
[INFO]:    -> running basename https://www.libsdl.org/release/SDL2-2.0.4.tar.gz
[INFO]:    sdl2 download already cached, skipping
[WARNING]: Should check headers here! Skipping for now.
[INFO]:    <- directory context /home/tanay/Documents/ktest/t1/.buildozer/android/platform/python-for-android-master
[INFO]:    Downloading six
[INFO]:    -> running mkdir -p /home/tanay/Documents/ktest/t1/.buildozer/android/platform/build/packages/six
[INFO]:    -> directory context /home/tanay/Documents/ktest/t1/.buildozer/android/platform/build/packages/six
[INFO]:    -> running basename https://pypi.python.org/packages/source/s/six/six-1.9.0.tar.gz
[INFO]:    six download already cached, skipping
[WARNING]: Should check headers here! Skipping for now.
[INFO]:    <- directory context /home/tanay/Documents/ktest/t1/.buildozer/android/platform/python-for-android-master
[INFO]:    Downloading pyjnius
[INFO]:    -> running mkdir -p /home/tanay/Documents/ktest/t1/.buildozer/android/platform/build/packages/pyjnius
[INFO]:    -> directory context /home/tanay/Documents/ktest/t1/.buildozer/android/platform/build/packages/pyjnius
[INFO]:    -> running basename https://github.com/kivy/pyjnius/archive/master.zip
[INFO]:    pyjnius download already cached, skipping
[WARNING]: Should check headers here! Skipping for now.
[INFO]:    <- directory context /home/tanay/Documents/ktest/t1/.buildozer/android/platform/python-for-android-master
[INFO]:    Downloading kivy
[INFO]:    -> running mkdir -p /home/tanay/Documents/ktest/t1/.buildozer/android/platform/build/packages/kivy
[INFO]:    -> directory context /home/tanay/Documents/ktest/t1/.buildozer/android/platform/build/packages/kivy
[INFO]:    -> running basename https://github.com/kivy/kivy/archive/master.zip
[INFO]:    kivy download already cached, skipping
[WARNING]: Should check headers here! Skipping for now.
[INFO]:    <- directory context /home/tanay/Documents/ktest/t1/.buildozer/android/platform/python-for-android-master
[INFO]:    # Building all recipes for arch armeabi-v7a
[INFO]:    # Unpacking recipes
[INFO]:    Unpacking hostpython2 for armeabi-v7a
[INFO]:    -> running basename http://python.org/ftp/python/2.7.2/Python-2.7.2.tar.bz2
[INFO]:    -> directory context /home/tanay/Documents/ktest/t1/.buildozer/android/platform/build/build/other_builds/hostpython2/desktop
[INFO]:    hostpython2 is already unpacked, skipping
[INFO]:    <- directory context /home/tanay/Documents/ktest/t1/.buildozer/android/platform/python-for-android-master
[INFO]:    Unpacking python2 for armeabi-v7a
[INFO]:    -> running basename http://python.org/ftp/python/2.7.2/Python-2.7.2.tar.bz2
[INFO]:    -> directory context /home/tanay/Documents/ktest/t1/.buildozer/android/platform/build/build/other_builds/python2/armeabi-v7a
[INFO]:    python2 is already unpacked, skipping
[INFO]:    <- directory context /home/tanay/Documents/ktest/t1/.buildozer/android/platform/python-for-android-master
[INFO]:    Unpacking sdl2_image for armeabi-v7a
[INFO]:    -> running basename https://www.libsdl.org/projects/SDL_image/release/SDL2_image-2.0.1.tar.gz
[INFO]:    -> directory context /home/tanay/Documents/ktest/t1/.buildozer/android/platform/build/build/bootstrap_builds/sdl2-python2/jni
[INFO]:    sdl2_image is already unpacked, skipping
[INFO]:    <- directory context /home/tanay/Documents/ktest/t1/.buildozer/android/platform/python-for-android-master
[INFO]:    Unpacking sdl2_mixer for armeabi-v7a
[INFO]:    -> running basename https://www.libsdl.org/projects/SDL_mixer/release/SDL2_mixer-2.0.1.tar.gz
[INFO]:    -> directory context /home/tanay/Documents/ktest/t1/.buildozer/android/platform/build/build/bootstrap_builds/sdl2-python2/jni
[INFO]:    sdl2_mixer is already unpacked, skipping
[INFO]:    <- directory context /home/tanay/Documents/ktest/t1/.buildozer/android/platform/python-for-android-master
[INFO]:    Unpacking sdl2_ttf for armeabi-v7a
[INFO]:    -> running basename https://www.libsdl.org/projects/SDL_ttf/release/SDL2_ttf-2.0.14.tar.gz
[INFO]:    -> directory context /home/tanay/Documents/ktest/t1/.buildozer/android/platform/build/build/bootstrap_builds/sdl2-python2/jni
[INFO]:    sdl2_ttf is already unpacked, skipping
[INFO]:    <- directory context /home/tanay/Documents/ktest/t1/.buildozer/android/platform/python-for-android-master
[INFO]:    Unpacking sdl2 for armeabi-v7a
[INFO]:    -> running basename https://www.libsdl.org/release/SDL2-2.0.4.tar.gz
[INFO]:    -> directory context /home/tanay/Documents/ktest/t1/.buildozer/android/platform/build/build/bootstrap_builds/sdl2-python2/jni
[INFO]:    sdl2 is already unpacked, skipping
[INFO]:    <- directory context /home/tanay/Documents/ktest/t1/.buildozer/android/platform/python-for-android-master
[INFO]:    Unpacking six for armeabi-v7a
[INFO]:    -> running basename https://pypi.python.org/packages/source/s/six/six-1.9.0.tar.gz
[INFO]:    -> directory context /home/tanay/Documents/ktest/t1/.buildozer/android/platform/build/build/other_builds/six-python2/armeabi-v7a
[INFO]:    six is already unpacked, skipping
[INFO]:    <- directory context /home/tanay/Documents/ktest/t1/.buildozer/android/platform/python-for-android-master
[INFO]:    Unpacking pyjnius for armeabi-v7a
[INFO]:    -> running basename https://github.com/kivy/pyjnius/archive/master.zip
[INFO]:    -> directory context /home/tanay/Documents/ktest/t1/.buildozer/android/platform/build/build/other_builds/pyjnius-python2-sdl2/armeabi-v7a
[INFO]:    pyjnius is already unpacked, skipping
[INFO]:    <- directory context /home/tanay/Documents/ktest/t1/.buildozer/android/platform/python-for-android-master
[INFO]:    Unpacking kivy for armeabi-v7a
[INFO]:    -> running basename https://github.com/kivy/kivy/archive/master.zip
[INFO]:    -> directory context /home/tanay/Documents/ktest/t1/.buildozer/android/platform/build/build/other_builds/kivy-python2-sdl2/armeabi-v7a
[INFO]:    kivy is already unpacked, skipping
[INFO]:    <- directory context /home/tanay/Documents/ktest/t1/.buildozer/android/platform/python-for-android-master
[INFO]:    # Prebuilding recipes
[INFO]:    Prebuilding hostpython2 for armeabi-v7a
[INFO]:    -> running cp /home/tanay/Documents/ktest/t1/.buildozer/android/platform/python-for-android-master/pythonforandroid...(and 156 more)
[INFO]:    Prebuilding python2 for armeabi-v7a
[INFO]:    python2 has no prebuild_armeabi_v7a, skipping
[INFO]:    Applying patches for python2[armeabi-v7a]
[INFO]:    python2 already patched, skipping
[INFO]:    Prebuilding sdl2_image for armeabi-v7a
[INFO]:    sdl2_image has no prebuild_armeabi_v7a, skipping
[INFO]:    Applying patches for sdl2_image[armeabi-v7a]
[INFO]:    sdl2_image already patched, skipping
[INFO]:    Prebuilding sdl2_mixer for armeabi-v7a
[INFO]:    sdl2_mixer has no prebuild_armeabi_v7a, skipping
[INFO]:    Applying patches for sdl2_mixer[armeabi-v7a]
[INFO]:    sdl2_mixer already patched, skipping
[INFO]:    Prebuilding sdl2_ttf for armeabi-v7a
[INFO]:    sdl2_ttf has no prebuild_armeabi_v7a, skipping
[INFO]:    Prebuilding sdl2 for armeabi-v7a
[INFO]:    sdl2 has no prebuild_armeabi_v7a, skipping
[INFO]:    Applying patches for sdl2[armeabi-v7a]
[INFO]:    sdl2 already patched, skipping
[INFO]:    Prebuilding six for armeabi-v7a
[INFO]:    six has no prebuild_armeabi_v7a, skipping
[INFO]:    Prebuilding pyjnius for armeabi-v7a
[INFO]:    pyjnius has no prebuild_armeabi_v7a, skipping
[INFO]:    Applying patches for pyjnius[armeabi-v7a]
[INFO]:    pyjnius already patched, skipping
[INFO]:    Prebuilding kivy for armeabi-v7a
[INFO]:    kivy has no prebuild_armeabi_v7a, skipping
[INFO]:    # Building recipes
[INFO]:    Building hostpython2 for armeabi-v7a
[INFO]:    -> directory context /home/tanay/Documents/ktest/t1/.buildozer/android/platform/build/build/other_builds/hostpython2/desktop/hostpython2
[INFO]:    hostpython already exists, skipping build
[INFO]:    <- directory context /home/tanay/Documents/ktest/t1/.buildozer/android/platform/python-for-android-master
[INFO]:    Building python2 for armeabi-v7a
[INFO]:    Copying hostpython binary to targetpython folder
[INFO]:    -> running cp /home/tanay/Documents/ktest/t1/.buildozer/android/platform/build/build/other_builds/hostpython2/deskt...(and 134 more)
[INFO]:    Building sdl2_image for armeabi-v7a
[INFO]:    Building sdl2_mixer for armeabi-v7a
[INFO]:    Building sdl2_ttf for armeabi-v7a
[INFO]:    Building sdl2 for armeabi-v7a
[INFO]:    -> directory context /home/tanay/Documents/ktest/t1/.buildozer/android/platform/build/build/bootstrap_builds/sdl2-python2/jni
[INFO]:    -> running ndk-build V=1
[INFO]:    <- directory context /home/tanay/Documents/ktest/t1/.buildozer/android/platform/python-for-android-master
[INFO]:    Building six for armeabi-v7a
[INFO]:    Python package already exists in site-packages
[INFO]:    six said it is already built, skipping
[INFO]:    Building pyjnius for armeabi-v7a
[INFO]:    Python package already exists in site-packages
[INFO]:    pyjnius said it is already built, skipping
[INFO]:    Building kivy for armeabi-v7a
[INFO]:    Python package already exists in site-packages
[INFO]:    kivy said it is already built, skipping
[INFO]:    # Biglinking object files
[INFO]:    Collating object files from each recipe
[INFO]:    hostpython2 recipe has no biglinkable files dir, skipping
[INFO]:    python2 recipe has no biglinkable files dir, skipping
[INFO]:    sdl2_image recipe has no biglinkable files dir, skipping
[INFO]:    sdl2_mixer recipe has no biglinkable files dir, skipping
[INFO]:    sdl2_ttf recipe has no biglinkable files dir, skipping
[INFO]:    sdl2 recipe has no biglinkable files dir, skipping
[INFO]:    six recipe has no biglinkable files dir, skipping
[INFO]:    pyjnius recipe has object files, copying
[INFO]:    -> running cp -r /home/tanay/Documents/ktest/t1/.buildozer/android/platform/build/build/other_builds/pyjnius-python...(and 316 more)
[INFO]:    kivy recipe has object files, copying
[INFO]:    -> running cp -r /home/tanay/Documents/ktest/t1/.buildozer/android/platform/build/build/other_builds/kivy-python2-...(and 8902 more)
[INFO]:    Biglinking
[INFO]:    target /home/tanay/Documents/ktest/t1/.buildozer/android/platform/build/build/libs_collections/mycam/armeabi-v7a/libpymodules.so
[INFO]:    # Postbuilding recipes
[INFO]:    Postbuilding hostpython2 for armeabi-v7a
[INFO]:    Postbuilding python2 for armeabi-v7a
[INFO]:    Postbuilding sdl2_image for armeabi-v7a
[INFO]:    Postbuilding sdl2_mixer for armeabi-v7a
[INFO]:    Postbuilding sdl2_ttf for armeabi-v7a
[INFO]:    Postbuilding sdl2 for armeabi-v7a
[INFO]:    Postbuilding six for armeabi-v7a
[INFO]:    Postbuilding pyjnius for armeabi-v7a
[INFO]:    Copying pyjnius java class to classes build dir
[INFO]:    -> directory context /home/tanay/Documents/ktest/t1/.buildozer/android/platform/build/build/other_builds/pyjnius-python2-sdl2/armeabi-v7a/pyjnius
[INFO]:    -> running cp -a jnius/src/org /home/tanay/Documents/ktest/t1/.buildozer/android/platform/build/build/javaclasses/mycam
[INFO]:    <- directory context /home/tanay/Documents/ktest/t1/.buildozer/android/platform/python-for-android-master
[INFO]:    Postbuilding kivy for armeabi-v7a
[INFO]:    # Installing pure Python modules
[INFO]:    The requirements (plyer) don't have recipes, attempting to install them with pip
[INFO]:    If this fails, it may mean that the module has compiled components and needs a recipe.
[INFO]:    -> directory context /home/tanay/Documents/ktest/t1/.buildozer/android/platform/build/build
[INFO]:    -> running virtualenv --python=python2.7 venv
Traceback (most recent call last):
  File "/home/tanay/anaconda2/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/home/tanay/anaconda2/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/tanay/Documents/ktest/t1/.buildozer/android/platform/python-for-android-master/pythonforandroid/toolchain.py", line 755, in <module>
    main()
  File "/home/tanay/Documents/ktest/t1/.buildozer/android/platform/python-for-android-master/pythonforandroid/toolchain.py", line 752, in main
    ToolchainCL()
  File "/home/tanay/Documents/ktest/t1/.buildozer/android/platform/python-for-android-master/pythonforandroid/toolchain.py", line 341, in __init__
    getattr(self, args.command)(unknown)
  File "/home/tanay/Documents/ktest/t1/.buildozer/android/platform/python-for-android-master/pythonforandroid/toolchain.py", line 93, in wrapper_func
    build_dist_from_args(ctx, dist, dist_args)
  File "/home/tanay/Documents/ktest/t1/.buildozer/android/platform/python-for-android-master/pythonforandroid/toolchain.py", line 138, in build_dist_from_args
    build_recipes(build_order, python_modules, ctx)
  File "pythonforandroid/build.py", line 579, in build_recipes
  File "pythonforandroid/build.py", line 598, in run_pymodules_install
  File "pythonforandroid/logger.py", line 173, in shprint
  File "/home/tanay/anaconda2/lib/python2.7/site-packages/sh.py", line 565, in next
    self.wait()
  File "/home/tanay/anaconda2/lib/python2.7/site-packages/sh.py", line 500, in wait
    self.handle_command_exit_code(exit_code)
  File "/home/tanay/anaconda2/lib/python2.7/site-packages/sh.py", line 516, in handle_command_exit_code
    raise exc(self.ran, self.process.stdout, self.process.stderr)
sh.ErrorReturnCode_1: 

  RAN: '/home/tanay/anaconda2/bin/virtualenv --python=python2.7 venv'

  STDOUT:
Running virtualenv with interpreter /home/tanay/anaconda2/bin/python2.7
New python executable in /home/tanay/Documents/ktest/t1/.buildozer/android/platform/build/build/venv/bin/python2.7
Not overwriting existing python script /home/tanay/Documents/ktest/t1/.buildozer/android/platform/build/build/venv/bin/python (you must use /home/tanay/Documents/ktest/t1/.buildozer/android/platform/build/build/venv/bin/python2.7)
Installing setuptools, pip, wheel...
  Complete output from command /home/tanay/Document...d/venv/bin/python2.7 - setuptools pip wheel:
  Traceback (most recent call last):
  File "<stdin>", line 7, in <module>
  File "/home/tanay/anaconda2/lib/python2.7/site-packages/virtualenv_support/pip-8.1.1-py2.py3-none-any.whl/pip/__init__.py", line 16, in <module>
  File "/home/tanay/anaconda2/lib/python2.7/site-packages/virtualenv_support/pip-8.1.1-py2.py3-none-any.whl/pip/vcs/mercurial.py", line 9, in <module>
  File "/home/tanay/anaconda2/lib/python2.7/site-packages/virtualenv_support/pip-8.1.1-py2.py3-none-any.whl/pip/download.py", line 39, in <module>
  File "/home/tanay/anaconda2/lib/python2.7/site-packages/virtualenv_support/pip-8.1.1-py2.py3-none-any.whl/pip/_vendor/requests/__init__.py", line 58, in <module>
  File "/home/tanay/anaconda2/lib/python2.7/site-packages/virtualenv_support/pip-8.1.1-py2.py3-none-any.whl/pip/_vendor/requests/utils.py", line 26, in <module>
  File "/home/tanay/anaconda2/lib/python2.7/site-packages/virtualenv_support/pip-8.1.1-py2.py3-none-any.whl/pip/_vendor/requests/compat.py", line 7, in <module>
  File "/home/tanay/anaconda2/lib/python2.7/site-packages/virtualenv_support/pip-8.1.1-py2.py3-none-any.whl/pip/_vendor/requests/packages/__init__.py", line 29, in <module>
ImportError: No module named urllib3
----------------------------------------
...Installing setuptools, pip, wheel...done.
Traceback (most recent call last):
  File "/home/tanay/anaconda2/lib/python2.7/site-packages/virtualenv.py", line 2316, in <module>
    main()
  File "/home/tanay/anaconda2/lib/python2.7/site-packages/virtualenv.py", line 708, in main
    symlink=options.symlink)
  File "/home/tanay/anaconda2/lib/python2.7/site-packages/virtualenv.py", line 941, in create_environment
    download=download,
  File "/home/tanay/anaconda2/lib/python2.7/site-packages/virtualenv.py", line 897, in install_wheel
    call_subprocess(cmd, show_stdout=False, extra_env=env, stdin=SCRIPT)
  File "/home/tanay/anaconda2/lib/python2.7/site-packages/virtualenv.py", line 792, in call_subprocess
    % (cmd_desc, proc.returncode))
OSError: Command /home/tanay/Document...d/venv/bin/python2.7 - setuptools pip wheel failed with error code 1


  STDERR:
