### ISSUE TITLE
app always crash in android

### ISSUE THREAD

**Issue by doomzhou** [kivy/buildozer#360]
hi folks, my app always crash after build apk
my origin example code

    from kivy.app import App
    from kivy.uix.scatter import Scatter
    from kivy.properties import StringProperty
    from kivy.uix.boxlayout import BoxLayout
    from kivy.uix.floatlayout import FloatLayout
    from kivy.uix.image import Image
    from kivy.uix.label import Label
    from kivy.properties import StringProperty

    class pictures(Scatter):
        pass

    class picapp(App):
        
        def build(self):
            App.title = "Hello"
            scatter = Scatter()
            Lab1 = Label(text="Hello world")
            scatter.add_widget(Lab1)
            root = self.root
            return scatter

    if __name__ == '__main__':
        picapp().run()

*this is fun , but when i add my python code in it *

    from kivy.app import App
    from kivy.uix.scatter import Scatter
    from kivy.properties import StringProperty
    from kivy.uix.boxlayout import BoxLayout
    from kivy.uix.floatlayout import FloatLayout
    from kivy.uix.image import Image
    from kivy.uix.label import Label
    from kivy.properties import StringProperty

    import os
    import urllib
    import random
    from bs4 import BeautifulSoup
    from uuid import uuid1

    class pictures(Scatter):
        pass

    class picapp(App):
        
        def build(self):
            App.title = "Hello"
            scatter = Scatter()
            Lab1 = Label(text="Hello world")
            scatter.add_widget(Lab1)
            root = self.root
            return scatter

    if __name__ == '__main__':
        picapp().run()

app always crash how can i debug it , 

>with kivy Launcher cannot find my code in /storage/emulated/0/kivy/pro1,
i have already pull my code to /storage/emulated/0/kivy/pro1(equal:/sdcard/kivy/pro1)

![](https://66.media.tumblr.com/02a0e46017362043286c461773255a95/tumblr_o7mlct5br11r68ev5o1_540.jpg)
![](https://67.media.tumblr.com/d75411342b6f41fa4a1fe273d59fa2be/tumblr_o7mlct5br11r68ev5o2_1280.png)

**Comment by inclement** [comment]
Follow [this documentation](https://kivy.org/docs/guide/android.html#debugging-your-application-on-the-android-platform) to debug the problem.
