### ISSUE TITLE
Command failed: tar xzf android-sdk_r20-linux.tgz

### ISSUE THREAD

**Issue by afaki077** [kivy/buildozer#383]
I was trying to build kivy app to android and got this error

    # Check configuration tokens
    # Ensure build layout
    # Check configuration tokens
    # Preparing build
    # Check requirements for android
    # Install platform
    # Apache ANT found at /home/ali/.buildozer/android/platform/apache-ant-1.9.4
    # Android SDK is missing, downloading
    # Unpacking Android SDK
    # Command failed: tar xzf android-sdk_r20-linux.tgz
    # 
    # Buildozer failed to execute the last command
    # If the error is not obvious, please raise the log_level to 2
    # and retry the latest command.
    # In case of a bug report, please add a full log with log_level = 2

command

    $ buildozer android_new debug

log:
http://paste.ubuntu.com/20850804/

want any details? request in the comments

**Comment by inclement** [comment]
# If the error is not obvious, please raise the log_level to 2
# and retry the latest command.
# In case of a bug report, please add a full log with log_level = 2

**Comment by afaki077** [comment]
@inclement 
the log_level is already 2
log: http://paste.ubuntu.com/20850804/

**Comment by afaki077** [comment]
I figured it out!

the problem was some google services are not available where i live due to USA sanctions on my country (Sudan) and the returned response is html (not in gzip format).

the solution is to use vpn

**Comment by inclement** [comment]
Thanks for reporting the problem!

**Comment by bed72** [comment]
I'm with the same problem, I'm from Brazil. The solution is vpn? Can someone help me please

gabriel@Bed ~/AppKv $ wget -O - http://dl.google.com/android/android-sdk_r20-linux.tgz | md5sum
--2017-07-19 21:56:27--  http://dl.google.com/android/android-sdk_r20-linux.tgz
Resolvendo dl.google.com (dl.google.com)... 216.58.222.14, 2800:3f0:4001:801::200e
Conectando-se a dl.google.com (dl.google.com)|216.58.222.14|:80... conectado.
A requisição HTTP foi enviada, aguardando resposta... 200 OK
Tamanho: 82589455 (79M) [application/x-tar]
Salvando em: “STDOUT”

-                   100%[===================>]  78,76M  15,5KB/s    in 10m 6s  

2017-07-19 22:06:33 (133 KB/s) - escrito para a saída padrão  [82589455/82589455]

22a81cf1d4a951c62f71a8758290e9bb  -
gabriel@Bed ~/AppKv $ 
gabriel@Bed ~/AppKv $ buildozer  -v android debug 
# Check configuration tokens
# Ensure build layout
# Create directory /home/gabriel/AppKv/.buildozer
# Create directory /home/gabriel/AppKv/bin
# Create directory /home/gabriel/AppKv/.buildozer/applibs
# Create directory /home/gabriel/AppKv/.buildozer/android/platform
# Create directory /home/gabriel/AppKv/.buildozer/android/app
# Check configuration tokens
# Read available permissions from api-versions.xml
# Preparing build
# Check requirements for android
# Run 'dpkg --version'
# Cwd None
Programa de gerenciamento de pacotes Debian 'dpkg' versão 1.18.4 (amd64).
Isto é software livre; veja a GNU General Public License versão 2 ou
posterior para condições de cópia. Não existe NENHUMA garantia.
# Search for Git (git)
#  -> found at /usr/bin/git
# Search for Cython (cython)
#  -> found at /usr/local/bin/cython
# Search for Java compiler (javac)
#  -> found at /usr/lib/jvm/java-8-oracle/bin/javac
# Search for Java keytool (keytool)
#  -> found at /usr/lib/jvm/java-8-oracle/jre/bin/keytool
# Install platform
# Run 'git clone -b stable --single-branch https://github.com/kivy/python-for-android.git python-for-android-master'
# Cwd /home/gabriel/AppKv/.buildozer/android/platform
Cloning into 'python-for-android-master'...
# Run 'pip install -q --user "appdirs" "colorama>=0.3.3" "sh>=1.10" "jinja2" "six"'
# Cwd None
# Apache ANT found at /home/gabriel/.buildozer/android/platform/apache-ant-1.9.4
# Android SDK is missing, downloading
# Downloading http://dl.google.com/android/android-sdk_r2-linux.tgz
# Unpacking Android SDK
# Run 'tar xzf android-sdk_r2-linux.tgz'
# Cwd /home/gabriel/.buildozer/android/platform

gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now
# Command failed: tar xzf android-sdk_r2-linux.tgz
# 
# Buildozer failed to execute the last command
# The error might be hidden in the log above this error
# Please read the full log, and search for it before
# raising an issue with buildozer itself.
# In case of a bug report, please add a full log with log_level = 2


gabriel@Bed ~/AppKv $
