### ISSUE TITLE
 ConfigParser.NoOptionError: No option 'p4a.local_recipes' in section: 'app' (android_new)

### ISSUE THREAD

**Issue by Tungsteno74** [kivy/buildozer#394]
I get this error when i debug a simple app with _android_new_ as target:

```
# Check configuration tokens
# Ensure build layout
# Create directory /home/valerio/PROGETTI/pyTBE/.buildozer/android/platform
# Check configuration tokens
# Preparing build
# Check requirements for android
# Run 'dpkg --version'
# Cwd None
Debian "dpkg", programma di gestione dei pacchetti versione 1.18.4 (amd64).
Questo è software libero; consultare la GNU General Public Licence versione 2
o successiva per le condizioni di copia. NON c'è alcuna garanzia.
# Search for Git (git)
#  -> found at /usr/bin/git
# Search for Cython (cython)
#  -> found at /usr/local/bin/cython
# Search for Java compiler (javac)
#  -> found at /usr/lib/jvm/java-8-openjdk-amd64/bin/javac
# Search for Java keytool (keytool)
#  -> found at /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/keytool
# Install platform
# Run 'git clone -b master --single-branch https://github.com/kivy/python-for-android.git python-for-android-master'
# Cwd /home/valerio/PROGETTI/pyTBE/.buildozer/android/platform
Cloning into 'python-for-android-master'...
# Apache ANT found at /home/valerio/.buildozer/android/platform/apache-ant-1.9.4
# Android SDK found at /home/valerio/.buildozer/android/platform/android-sdk-20
# Android NDK found at /home/valerio/.buildozer/android/platform/android-ndk-r9c
# Check application requirements
# Check garden requirements
# Garden requirements already installed, pass
# Compile platform
Traceback (most recent call last):
  File "/usr/local/bin/buildozer", line 9, in <module>
    load_entry_point('buildozer==0.33.dev0', 'console_scripts', 'buildozer')()
  File "/usr/local/lib/python2.7/dist-packages/buildozer/scripts/client.py", line 13, in main
    Buildozer().run_command(sys.argv[1:])
  File "/usr/local/lib/python2.7/dist-packages/buildozer/__init__.py", line 1028, in run_command
    self.target.run_commands(args)
  File "/usr/local/lib/python2.7/dist-packages/buildozer/target.py", line 90, in run_commands
    func(args)
  File "/usr/local/lib/python2.7/dist-packages/buildozer/target.py", line 100, in cmd_debug
    self.buildozer.prepare_for_build()
  File "/usr/local/lib/python2.7/dist-packages/buildozer/__init__.py", line 183, in prepare_for_build
    self.target.compile_platform()
  File "/usr/local/lib/python2.7/dist-packages/buildozer/targets/android_new.py", line 42, in compile_platform
    local_recipes = self.get_local_recipes_dir()
  File "/usr/local/lib/python2.7/dist-packages/buildozer/targets/android_new.py", line 76, in get_local_recipes_dir
    local_recipes = self.buildozer.config.get('app', 'p4a.local_recipes')
  File "/usr/lib/python2.7/ConfigParser.py", line 618, in get
    raise NoOptionError(option, section)
ConfigParser.NoOptionError: No option 'p4a.local_recipes' in section: 'app'
```

I use Xubuntu 16.04.1 LST and buildozer 0.33dev

Any idea?

**Comment by newnick** [comment]
There is an option missing in your buildozer.spec
First locate where you installed python-for-android and than add the recipes folder location to your buildozer.spec somewherebetween "[app]" and "[buildozer]"

For me python-for-android was located in `/home/kivy/Documents/firstproject/.buildozer/android/platform/python-for-android/recipes ` and because `/home/kivy/Documents/firstproject` is my source.dir I added the following line to my buildozer.spec somewherebetween "[app]" and "[buildozer]":
`p4a.local_recipes = %(source.dir)s/.buildozer/android/platform/python-for-android/recipes`

**Comment by kolruds** [comment]
Having the same problem. OSX 10.11.4, buildozer version 0.33dev.

I cant find the folder `.buildozer/android/platform/python-for-android/recipes`, but I found a `.buildozer/android/platform/python-for-android-master/pythonforandroid/recipes`.
Not sure if this folder is the same one though.

I tried to replace this with newnicks solution, but it did not solve my problem, just gave me more ConfigParser errors.

**Comment by Tungsteno74** [comment]
@newnick So, seem that with the last release of Ubuntu something was broken in the path configuration of buildozer.

**Comment by kolruds** [comment]
A solution to my problem (on mac) was to remove Kivy and buildozer and reinstall using homebrew and pip. I previously installed Kivy using the Kivy.app method. After this all worked well

**Comment by Tungsteno74** [comment]
@newkic What version of linux do you use? I didn't touch the installation path, so it should be in the default location and i don't know where it is. :( 
But always it worked in the past versions. So this is a lot of strange.

**Comment by nmz787** [comment]
I get this after building with 'android' then trying to use 'android_new'

**Comment by Tungsteno74** [comment]
@nmz787 Which Os do you have? And if you use Ubuntu-like what version?

**Comment by Paradisee** [comment]
I'm actually having the same problem on: Linux paradisee 4.4.0-31-generic #50-Ubuntu SMP Wed Jul 13 00:07:12 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

**Comment by nmz787** [comment]
@Tungsteno74 
```
uname -a
Linux nathan-lenovo 4.4.0-34-generic #53-Ubuntu SMP Wed Jul 27 16:06:39 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
```


```
lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.1 LTS
Release:	16.04
Codename:	xenial

```

**Comment by NumesSanguis** [comment]
I'm suffering the same with a new buildozer pulled from Github 3 days ago and a new `buildozer init`.

    uname -a
    Linux someoneubuntu-AI 4.4.0-38-generic #57-Ubuntu SMP Tue Sep 6 15:42:33 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

    lsb_release -a
    No LSB modules are available.
    Distributor ID:	Ubuntu
    Description:	Ubuntu 16.04.1 LTS
    Release:	16.04
    Codename:	xenial

**Comment by NumesSanguis** [comment]
Even when I add `p4a.local_recipes = %(source.dir)s/.buildozer/android/platform/python-for-android-master/pythonforandroid/recipes` to my `buildozer.spec`, from the error log it seems it is still looking in the old dir: `# Cwd /home/*my_dir*/.buildozer/android/platform/python-for-android-master`

Could it be related to this?

**Comment by jayboyd** [comment]
I get same issue on OS X 10.11.6, using either buildozer 0.32 or buildozer 0.33dev. 

buildozer android_new debug 
fails because spec has no p4a.local_recipes param. Adding this allows build to get further but still fails (sorry didnt capture that log). 

buildozer android debug
builds an APK which crashes on run, the log complaining that the "ext" symbol could not be found. 

I've tried many different approaches to building a simple app for Android, including directly invoking the p4a tool, and all result in either failed build or same crash on run. Was just banned from IRC chat trying to troubleshoot, as apparently my attitude sucks. This issue was reported a year ago...

**Comment by kolruds** [comment]
@jayboyd See my reply above. Does this help you?

**Comment by Paradisee** [comment]
I've been working on the application for almost 2 months and i'm not able
to try it out yet. This is weird! How can be possible the building is
totally broken? Didn't they try it before releasing?

**Comment by inclement** [comment]
I made the PR at https://github.com/kivy/buildozer/pull/405 to fix this, is anyone able to test it? My buildozer isn't set up to build at the moment, although it's a simple change so hopefully just works.

**Comment by NumesSanguis** [comment]
@inclement 's fix solves OP's issue, but I still can't succesfully run an app build with 'android_new': https://github.com/kivy/buildozer/issues/410

**Comment by Tungsteno74** [comment]
The inclement fix work for me too. thanks!
