### ISSUE TITLE
No instructions for utilizing buildozer in Arch linux (i686 / x86_64)

### ISSUE THREAD

**Issue by UNIcodeX** [kivy/buildozer#396]
**NOTE:** The following commands assume that your user has sudo access. If not, this can be accomplished by "usermod -G wheel {user}" without quotes, as root. It is also necessary to uncomment the following line in /etc/sudoers:
%wheel ALL=(ALL) ALL
# **If platform is Arch x86_64 Enable multilib repository**

Uncomment the following in /etc/pacman.conf:
[multilib]
Include = /etc/pacman.d/mirrorlist
# **Update the package database** 

sudo pacman -Syu
# **If platform is Arch x86_64:**

sudo pacman -S jdk7-openjdk \
python2 \
python2-pip \
python2-kivy \
mesa-libgl \
lib32-mesa-libgl \
lib32-sdl2 \
lib32-sdl2_image \
lib32-sdl2_mixer \
sdl2_ttf \
unzip \
gcc-multilib \
gcc-libs-multilib

If prompted with the following, answer 'y' for both prompts:
::gcc-multilib and gcc are in conflict. Remove gcc?
::gcc-libs-multilib and gcc-libs are in conflict. Remove gcc-libs?
# **If platform is Arch x86:**

sudo pacman -S jdk7-openjdk \
python2 \
python2-pip \
python2-kivy \
mesa-libgl \
sdl2 \
sdl2_image \
sdl2_mixer \
sdl2_ttf \
unzip
# **Install Cython:**

sudo pip2 install cython
# **Install buildozer:**

git clone http://github.com/kivy/buildozer
sudo python2 setup.py install

**DONE!**

From here you should be able to run the buildozer build process.
- buildozer init
- modify the buildozer.conf as necessary
- buildozer android debug serve

**Comment by jupart** [comment]
Hello! Recently installed on Arch and found that dependencies "mesa-libgl" (and "lib32-mesa-libgl") are now "mesa" ("and "lib32-mesa"). I do prefer installing kivy via pip though (in a virtualenv).

**Comment by wasimafser** [comment]
Hello ! I'm trying to build a kivy app using buildozer but fail everytime at this point : 

```
pkg_resources.DistributionNotFound: The 'distlib<1,>=0.3.0' distribution was not found and is required by virtualenv
```

distlib is already installed on my venv

**Comment by AndreMiras** [comment]
Arch Linux instructions got updated recently
