### ISSUE TITLE
Building with "android_new" target fails due to missing architecture on pythonforandroid.toolchain apk

### ISSUE THREAD

**Issue by gcobos** [kivy/buildozer#407]
Trying the "android_new" target, the parameter --arch=armeabi-v7a  is populated correctly when calling to the module pythonforandroid.toolchain for "create", but then is missing when trying to call "apk" to build the package. So it's trying to build it with the default "--arch=armeabi" which is incorrect for android_api=24, therefore the build process fails.

This works ok: 

`# Run 'python -m pythonforandroid.toolchain --color=always --storage-dir=/home/drone/src/kivy/esprobot/.buildozer/android/platform/build create --dist_name=leggedrobot.esprobot --bootstrap=sdl2 --requirements=kivy,python2 --arch armeabi-v7a --copy-libs'
`

But then this fails: 

`# Run 'python -m pythonforandroid.toolchain --color=always --storage-dir=/home/drone/src/kivy/esprobot/.buildozer/android/platform/build apk --bootstrap=sdl2 --dist_name leggedrobot.esprobot --name ESPRobot --version 0.1 --package com.leggedrobot.esprobot --android_api 24 --minsdk 9 --private /home/drone/src/kivy/esprobot/.buildozer/android/app --permission INTERNET --orientation landscape --release --copy-libs'
`

**Comment by dtorio** [comment]
Hi to all.

I also tried to make an apk for api 21 and above (api 23) using all ndk (between 10e ... 13), using target  android_new. All is running in buildozer fine until:

```
# Package the application
# Run 'python -m pythonforandroid.toolchain --color=always --storage-dir=/home/dtorio/PycharmProjects/myapp/src/.buildozer/android/platform/build apk --bootstrap=sdl2 --dist_name myapp --name App --version 0.1 --package org.test.myapp --android_api 21 --minsdk 21 --private /home/dtorio/PycharmProjects/myapp/src/.buildozer/android/app --presplash /home/dtorio/PycharmProjects/myapp/src/./data/presplash.png --icon /home/dtorio/PycharmProjects/myapp/src/./data/icon.png --orientation portrait --copy-libs'
# Cwd /home/dtorio/PycharmProjects/myapp/src/.buildozer/android/platform/python-for-android-master
```

```
[INFO]:    Will compile for the following archs: armeabi
[INFO]:    Getting Android API version from user argument
[ERROR]:   Asked to build for armeabi architecture with API 21, but API 21 or greater does not support armeabi
[ERROR]:   You probably want to build with --arch=armeabi-v7a instead
# Command failed: python -m pythonforandroid.toolchain --color=always --storage-dir=/home/dtorio/PycharmProjects/myapp/src/.buildozer/android/platform/build apk --bootstrap=sdl2 --dist_name myapp --name myapp --version 0.1 --package org.test.myapp --android_api 21 --minsdk 21 --private /home/dtorio/PycharmProjects/myapp/src/.buildozer/android/app --presplash /home/dtorio/PycharmProjects/myapp/src/./data/presplash.png --icon /home/dtorio/PycharmProjects/myapp/src/./data/icon.png --orientation portrait --copy-libs
```

I added --arch=armeabi-v7a to buildozer.spec but it didn't work, always the same error above.

Myapp builds sucessfully for sdk 19 and ndk 9c, but now I have to use api 21 or above, because myapp uses bluetooth and my smartphone runs android 6.0.

I'm using buildozer 0.32, python 2.7, ubuntu 14.04
Thanks in advance.

**Comment by lovableLavz** [comment]
Dear Friends , 
Am also getting same error , can anyone please help me how to get rid of this ? 


**python -m pythonforandroid.toolchain --color=always --storage-dir=/home/kivy/.buildozer/android/platform/build create --dist_name=myapp --bootstrap=sdl2 --requirements=kivy --arch armeabi-v7a --copy-libs**

Can anyone let me know where APK file will generate ? 
Thanks In Advance

**Comment by inclement** [comment]
Closing as stale, p4a's arch handling no longer has this issue.
