### ISSUE TITLE
specifying a url for a requirements item vs a version?

### ISSUE THREAD

**Issue by brentpicasso** [kivy/buildozer#408]
Is it possible to specify an exact source archive for the requirements string instead of the version number?

Currently this works:
requirements = kivy==1.9.1, plyer=1.2.3

And somewhere within buildozer or python-for-android this gets translated into a URL to download from github. 

Could we do something like:
requirements = kivy==1.9.1, plyer=http://path/to/source_or_github_archive

**Comment by mrhdias** [comment]
Add only the url work for me:
requirements = png, pycrypto, https://codeload.github.com/kivy/plyer/zip/master, kivy==master

**Comment by brentpicasso** [comment]
Thanks! is there a way to get this into the buildozer docs?

**Comment by dessant** [comment]
@brentpicasso, yes, the doc source is in this repo.
