### ISSUE TITLE
buildozer android created apk fails if application source kept in multiple files

### ISSUE THREAD

**Issue by jb1123** [kivy/buildozer#411]
Depending on repository files configuration kivy buildozer makes either working or crashing .apk. If all code is in main.py .apk works fine. With code divided among modules .apk crashes at start producing strange error messages: 

E/dalvikvm( 2277): dlopen("/data/data/eu.ijbd.nmeter/files/lib/python2.7/lib-dynload/_sqlite3.so") failed: dlopen failed: library "/data/data/eu.ijbd.nmeter/files/lib/python2.7/lib-dynload/_sqlite3.so" not found E/dalvikvm( 2277): dlopen("/data/data/eu.ijbd.nmeter/files/lib/python2.7/lib-dynload/_imaging.so") failed: dlopen failed: library "/data/data/eu.ijbd.nmeter/files/lib/python2.7/lib-dynload/_imaging.so" not found

Working / crashing .apk statuis same for android and android_new. Both working and crashing examples can be found in repository: https://github.com/jb1123/kivy-buildozer-bug

**Comment by jb1123** [comment]
In crashing_apk main.py import statement modification seems to fix crashing_apk problem:

from nmeter.meterlist import MeterList #apk crashes 
from meterlist import MeterList #apk works

Since both versions work on linux I believe it is a buildozer bug. Repository https://github.com/jb1123/kivy-buildozer-bug holds sample code, see tags 'crashing_apk' and 'crashing_apk_fixed'

**Comment by tito** [comment]
It may just because the source are incorrectly redirected? You seems to use a module, but your module disapear on android. If you show the buildozer.spec + the structure/files of your project, we may help.
