### ISSUE TITLE
Build on arm64 android

### ISSUE THREAD

**Issue by virus-on** [kivy/buildozer#412]
I have a phone based on arm64 architecture, but buildozer builds with standard arm7 toolchain, so my programs cant be tested on my phone. What could I do to bypass this issue and build binaries for my architecture?

**Comment by inclement** [comment]
I think arm32 builds should work on arm64, are you sure about the phone arch? What error do you get?

Either way, python-for-android has some code to build with arm64 but I haven't tested it. If it were to work, it would be with the `--arch=arm64-v8a` cli argument to p4a.

**Comment by inclement** [comment]
The android.arch buildozer.spec option now exists for this.
