### ISSUE TITLE
Buildozer not finding aidl

### ISSUE THREAD

**Issue by martini97** [kivy/buildozer#413]
I'm trying to package an app to apk but when I run the buildozer (buildozer android debug) it fails as it's not finding the Aidl, I installed the aidl package (apt install aidl) but it still doesn't find it, I tried updating everything, used the right version for Cpython, and still nothing, any thoughts?

**Comment by ranjian0** [comment]
# Check that aidl can be executed
# Search for Aidl
# Run '/home/ranjian0/sdk/android-sdk-linux/build-tools/25.0.0/aidl'
# Cwd None
# Aidl cannot be executed
Traceback (most recent call last):
  File "/usr/local/bin/buildozer", line 9, in <module>
    load_entry_point('buildozer==0.32', 'console_scripts', 'buildozer')()
  File "/usr/local/lib/python3.4/dist-packages/buildozer/scripts/client.py", line 13, in main
    Buildozer().run_command(sys.argv[1:])
  File "/usr/local/lib/python3.4/dist-packages/buildozer/__init__.py", line 1020, in run_command
    self.target.run_commands(args)
  File "/usr/local/lib/python3.4/dist-packages/buildozer/target.py", line 90, in run_commands
    func(args)
  File "/usr/local/lib/python3.4/dist-packages/buildozer/target.py", line 100, in cmd_debug
    self.buildozer.prepare_for_build()
  File "/usr/local/lib/python3.4/dist-packages/buildozer/__init__.py", line 174, in prepare_for_build
    self.target.install_platform()
  File "/usr/local/lib/python3.4/dist-packages/buildozer/targets/android.py", line 500, in install_platform
    self._install_android_packages()
  File "/usr/local/lib/python3.4/dist-packages/buildozer/targets/android.py", line 422, in _install_android_packages
    self._check_aidl(v_build_tools)
  File "/usr/local/lib/python3.4/dist-packages/buildozer/targets/android.py", line 450, in _check_aidl
    if sys.maxint > 2**32:
AttributeError: 'module' object has no attribute 'maxint'


Is this a bug or something? I have spent that whole day trying to find a solution for this. None so far. 
Updating android sdk, changing permissions, upgrading python packages etc. The few threads on google for this error have no specific solution.

Someone help!!!!

**Comment by alej0varas** [comment]
My previous comment doesn't solve the problem at the end. But running `buildozer android debug deploy run` **3** times works :P

**Comment by tito** [comment]
The issue about maxint has been fixed.

**Comment by farzinh** [comment]
but I still have the same problem

**Comment by Platun0v** [comment]
I have this problem also

**Comment by ImtiyazKhan117** [comment]
@farzinh  
@Platun0v 
try this its work for me
i copy past  my project into another folder and refactor it
than 
run:
 buildozer android clean
and
run:
buildozer android debug deppoy

**Comment by Flajt** [comment]
@alej0varas is there something to change for 16.04?

**Comment by psionman** [comment]
I still have this problem on 16.04

# Check that aidl can be executed
# build-tools folder not found /home/user/.buildozer/android/platform/android-sdk/build-tools
# Search for Aidl
# Aidl not found, please install it.

So i created  build-tools/0/ and copied in aidl

the message now says:

# Check that aidl can be executed
# Search for Aidl
# Aidl not found, please install it.

**Comment by IgorCode** [comment]
I didn't have "build-tools" folder, running `./home/MY_USERNAME/.buildozer/android/platform/android-sdk/tools/bin/sdkmanager "build-tools;28.0.0"` installed build tools and fixed missing aidl issue.

**Comment by cristinarivera** [comment]
> I didn't have "build-tools" folder, running `./home/MY_USERNAME/.buildozer/android/platform/android-sdk/tools/bin/sdkmanager "build-tools;28.0.0"` installed build tools and fixed missing aidl issue.

Perfecto!

**Comment by bogbasic** [comment]
In the buildozer.spec file you can set "android.skip_update = False". Then it finds aidl and you can move on to the next error ;-0

**Comment by tabete1st** [comment]
Make sure these are installed first by typing these commands in terminal: 
`sudo apt-get update`
`sudo apt-get install build-essential`
`sudo apt-get install libstdc++6`

then lastly
`sudo apt-get install aidl `

**Comment by IgorCode** [comment]
@tabete1st What does `v2` switch do?

**Comment by tabete1st** [comment]
> @tabete1st What does `v2` switch do?

That is for accepting the sdk licence, sometimes it doesn't give you the (Y/n) options to accept the license at log level 1 . 

The switch is an optional step if `buildozer android debug deploy run` still does not run after installing aidl.

**Comment by alchimiehub** [comment]
> ln -s /usr/bin/aidl ~/.buildozer/android/platform/android-sdk-20/build-tools/0/aidl
this worked Great

**Comment by Ridola20** [comment]
How about we do it this way, someone should use or who uses a virtual environment should upload the directory to his or her kivy convertertion project so others can also use that same VM.........what do you guys think
