### ISSUE TITLE
using android_new causes missing packages errors

### ISSUE THREAD

**Issue by Cedware** [kivy/buildozer#420]
Running this command:

> buildozer -v android_new debug

causes a list of allegedly missing packages

> ERROR: The colorama Python module could not be found, please install version 0.3.3 or higher
> ERROR: The appdirs Python module could not be found, please install it.
> ERROR: The sh Python module could not be found, please install version 1.10 or higher
> ERROR: The jinja2 Python module could not be found, please install it.

If i try to install them with pip, it seems any of the named packages is installed

**Comment by khalakhelo** [comment]
When you install them, do you make sure you upgrade ?
like:
`sudo pip install -U colorama`
`sudo pip install -U appdirs`
`sudo pip install -U sh`
`sudo pip install -U jinja2`

**Comment by Cedware** [comment]
Yes for my python3 installation all thoese packages are up-to-date

**Comment by frmdstryr** [comment]
Had the same thing, turns out it was using anaconda's python. If you have multiple python versions make sure it's using the correct ones.

**Comment by inclement** [comment]
Closing as stale, buildozer handles this now.
