### ISSUE TITLE
how to solve the build error for "java"?

### ISSUE THREAD

**Issue by Mr-Binary** [kivy/buildozer#421]
The err log is here https://github.com/Mr-Binary/trybuildozer/blob/master/e.txt
Thanks

Have spend several days to deal with problems, finally get this, but seems no more useful err output here. Need some help, please :)

**Comment by dessant** [comment]
Please try to set `log_level = 2` and share the new log.

**Comment by Mr-Binary** [comment]
Solved the problem by completely re-install
