### ISSUE TITLE
Big Bug, ORMs cant find sqlite3.so

### ISSUE THREAD

**Issue by ghost** [kivy/buildozer#426]
Hi

I used Peewee ORM on my kivy app but my app crashed on android device and i replaced my orm by SqlAlchemy, but both ORM can't recognize sqlite connector, SqlAlchemy trying to import db driver by below code:

@classmethod
     def dbapi(cls):
         try:
             from pysqlite2 import dbapi2 as sqlite
         except ImportError as e:
             try:
                 from sqlite3 import dbapi2 as sqlite  # try 2.5+ stdlib name.
             except ImportError:
                 raise e
         return sqlite

But cant import sqlite3 library... this recipe added in requirements and i can find `libsqlite3.so` on my package.

My Desktop OS: Ubuntu 15.10
My Android Version: 4.1.2
requirements: python2,kivy,sqlite3,sqlalchemy,kivymd,plyer,khayyam,python-bidi,hostpython2
arch: armeabi-v7a

My important question is:
But other libraries and code cant import sqlite3 library on android devices?

**Comment by nesergen** [comment]
Same problem. I am glad that not alone.
It is bug of android 4.1 -4.3 
[https://code.google.com/p/android/issues/detail?id=35962](url)

I have found two possible solutions, but not tested yet by me:
[http://stackoverflow.com/questions/32860294/android-load-library-failed](url)
[https://medium.com/keepsafe-engineering/relinker-v1-2-is-here-b8f1799e22fe#.nnbsr97dz](url)
This methods require to use pyjnius.

**Comment by inclement** [comment]
Closing as stale, this is probably fixed in python-for-android master, please open a new issue on that project if you still have issues.
