### ISSUE TITLE
compiling crash

### ISSUE THREAD

**Issue by nesergen** [kivy/buildozer#431]
When I compile APK with buildozer with property 
```
# (list) Android additionnal libraries to copy into libs/armeabi
android.add_libs_armeabi_v7a = libs/android-v7/*.so
```
the ERROR occure

```
# Package the application
# Search and copy libs for armeabi-v7a
Traceback (most recent call last):
  File "/usr/local/bin/buildozer", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/buildozer/scripts/client.py", line 13, in main
    Buildozer().run_command(sys.argv[1:])
  File "/usr/local/lib/python2.7/dist-packages/buildozer/__init__.py", line 1027, in run_command
    self.target.run_commands(args)
  File "/usr/local/lib/python2.7/dist-packages/buildozer/target.py", line 90, in run_commands
    func(args)
  File "/usr/local/lib/python2.7/dist-packages/buildozer/target.py", line 102, in cmd_debug
    self.buildozer.build()
  File "/usr/local/lib/python2.7/dist-packages/buildozer/__init__.py", line 210, in build
    self.target.build_package()
  File "/usr/local/lib/python2.7/dist-packages/buildozer/targets/android.py", line 637, in build_package
    for fn in self.buildozer.file_matches(patterns):
TypeError: 'NoneType' object is not iterable

```
1) for what purposes this property (Android additionnal libraries to copy into libs/armeabi) needs ?
2) FROM where and TO where must be copied the *.so files ?

**Comment by inclement** [comment]
I've no idea exactly what has gone wrong here, but the file_matches function looks like this:

    def file_matches(self, patterns):
        from glob import glob
        result = []
        for pattern in patterns:
            matches = glob(expanduser(pattern.strip()))
            if not matches:
                return
            result.extend(matches)
        return result

This clearly can return None when it shouldn't, but I'm not sure what the author intended, whether the `return` should be `continue` (seems likely), or whether it should at least `return []`.

**Comment by inclement** [comment]
I made a PR to fix it (linked above). If you need a quick fix, you could try out that change.

**Comment by nesergen** [comment]
I figured out how it works. But to fix I need to know from where the files must be copied

**Comment by nesergen** [comment]
You right  583rd line in file `/usr/local/lib/python2.7/dist-packages/buildozer/__init__.py` ("return")must be replaced by "continue" then error disappear. But it is not single problem.  The function `expanduser` do not any changes to the `pattern`string. It is becoms like `libs/android-v7/*.so` and returns like `libs/android-v7/*.so` but must be something like `/home_folder/libs/android-v7/*.so`. Therefore function `globe` can`t to find any right path and returns empty list. To properly fix the problem I need to know which folder must to parse the `glob` function.

**Comment by nesergen** [comment]
You right  586rd line in file `/usr/local/lib/python2.7/dist-packages/buildozer/__init__.py` ("return") must be replaced by "continue" then the error disappears. But it is not single problem.  The function `expanduser` (line 584) do not any changes to the `pattern`string. It is becoms like `libs/android-v7/*.so` and returns like `libs/android-v7/*.so` but must be something like `/home_folder/libs/android-v7/*.so`. Therefore function `globe` can`t to find any right path and returns empty list. To properly fix the problem I need to know which folder must to parse the `glob` function.
