### ISSUE TITLE
Successfully run via command line but crashed after packaging and install to mobile device.

### ISSUE THREAD

**Issue by Mr-Binary** [kivy/buildozer#434]
Use the latest version.
Can run the app via `python main.py`

The application is written by python3
and run it via python 3.5.2 with kivy 1.9.1

I add the `hostpython2` to that `requirement` section of buildozer.spec to fix that `Context has no hostpython attribute error`

The `log-error=2` is turn on and full log is [here](https://gist.github.com/Mr-Binary/d7e0e25b6f90aef6df6194343adde537)

Seems no error via building phase, but after installing and run, it crashes,
and I don't know what is wrong.

Tried on Android 7, Android 5.1.1.

**Comment by razzbee** [comment]
you can check for the real python error using : 
```
adb logcat | grep python
```
after you have run this , re open the app so that when it crashes , you will know the actual bug ..

**Comment by tito** [comment]
Check your device log, that's the only way to understand what's going on.

```
buildozer android_new logcat
```
