### ISSUE TITLE
Expose kivy download source?

### ISSUE THREAD

**Issue by Tungsteno74** [kivy/buildozer#435]
I could be wrong, but I could not find any specific item in buildozer.spec that defines from which branch and which version of kivy to download.

I think it would be helpful to use a different version of kivy to do specific tests.

It could be added?

thanks

**Comment by akshayaurora** [comment]
It's just like pip you simply say `kivy==master` or `requests==1.3.4` or `git+http://path/to/purepython/repo`

**Comment by Tungsteno74** [comment]
@akshayaurora sorry Alain, bug you mena on command-line?

**Comment by Tungsteno74** [comment]
@akshayaurora please can show me an example? i can't figure out how to do it in buildozer. Thanks
