### ISSUE TITLE
Error while compiling a kivy app for android (undefined reference to 'SDL_main' collect2: error: ld returned 1 exit status)

### ISSUE THREAD

**Issue by xyzrico** [kivy/buildozer#438]
Hello. Hope you are fine.
I'm trying to build and test android application with kivy and buildozer.
I'm under Kali linux. When I tape this

> buildozer android debug

and I get this error

> error: undefined reference to 'SDL_main'
collect2: error: ld returned 1 exit status
make: *** [/home/konrad/Bureau/kivyapp/.buildozer/android/platform/python-for-android/src/obj/local/armeabi/libsdl_main.so] Error 1

This the full log (I think)

> find: "/home/konrad/Bureau/kivyapp/.buildozer/android/platform/python-for-android/src/jni/../jni/application/src/": Aucun fichier ou dossier de ce type
Android NDK: WARNING:/home/konrad/Bureau/kivyapp/.buildozer/android/platform/python-for-android/src/jni/../jni/application/Android.mk:application: non-system libraries in linker flags: -lpython2.7    
Android NDK:     This is likely to result in incorrect builds. Try using LOCAL_STATIC_LIBRARIES    
Android NDK:     or LOCAL_SHARED_LIBRARIES instead to list the library dependencies of the    
Android NDK:     current module    
Android NDK: WARNING:/home/konrad/Bureau/kivyapp/.buildozer/android/platform/python-for-android/src/jni/../jni/png/Android.mk:png: LOCAL_LDLIBS is always ignored for static libraries    
rm -f /home/konrad/Bureau/kivyapp/.buildozer/android/platform/python-for-android/src/libs/arm64-v8a/lib*.so /home/konrad/Bureau/kivyapp/.buildozer/android/platform/python-for-android/src/libs/armeabi/lib*.so /home/konrad/Bureau/kivyapp/.buildozer/android/platform/python-for-android/src/libs/armeabi-v7a/lib*.so /home/konrad/Bureau/kivyapp/.buildozer/android/platform/python-for-android/src/libs/armeabi-v7a-hard/lib*.so /home/konrad/Bureau/kivyapp/.buildozer/android/platform/python-for-android/src/libs/mips/lib*.so /home/konrad/Bureau/kivyapp/.buildozer/android/platform/python-for-android/src/libs/mips64/lib*.so /home/konrad/Bureau/kivyapp/.buildozer/android/platform/python-for-android/src/libs/x86/lib*.so /home/konrad/Bureau/kivyapp/.buildozer/android/platform/python-for-android/src/libs/x86_64/lib*.so
rm -f /home/konrad/Bureau/kivyapp/.buildozer/android/platform/python-for-android/src/libs/arm64-v8a/gdbserver /home/konrad/Bureau/kivyapp/.buildozer/android/platform/python-for-android/src/libs/armeabi/gdbserver /home/konrad/Bureau/kivyapp/.buildozer/android/platform/python-for-android/src/libs/armeabi-v7a/gdbserver /home/konrad/Bureau/kivyapp/.buildozer/android/platform/python-for-android/src/libs/armeabi-v7a-hard/gdbserver /home/konrad/Bureau/kivyapp/.buildozer/android/platform/python-for-android/src/libs/mips/gdbserver /home/konrad/Bureau/kivyapp/.buildozer/android/platform/python-for-android/src/libs/mips64/gdbserver /home/konrad/Bureau/kivyapp/.buildozer/android/platform/python-for-android/src/libs/x86/gdbserver /home/konrad/Bureau/kivyapp/.buildozer/android/platform/python-for-android/src/libs/x86_64/gdbserver
rm -f /home/konrad/Bureau/kivyapp/.buildozer/android/platform/python-for-android/src/libs/arm64-v8a/gdb.setup /home/konrad/Bureau/kivyapp/.buildozer/android/platform/python-for-android/src/libs/armeabi/gdb.setup /home/konrad/Bureau/kivyapp/.buildozer/android/platform/python-for-android/src/libs/armeabi-v7a/gdb.setup /home/konrad/Bureau/kivyapp/.buildozer/android/platform/python-for-android/src/libs/armeabi-v7a-hard/gdb.setup /home/konrad/Bureau/kivyapp/.buildozer/android/platform/python-for-android/src/libs/mips/gdb.setup /home/konrad/Bureau/kivyapp/.buildozer/android/platform/python-for-android/src/libs/mips64/gdb.setup /home/konrad/Bureau/kivyapp/.buildozer/android/platform/python-for-android/src/libs/x86/gdb.setup /home/konrad/Bureau/kivyapp/.buildozer/android/platform/python-for-android/src/libs/x86_64/gdb.setup
[armeabi] Install        : libapplication.so => libs/armeabi/libapplication.so
install -p /home/konrad/Bureau/kivyapp/.buildozer/android/platform/python-for-android/src/obj/local/armeabi/libapplication.so /home/konrad/Bureau/kivyapp/.buildozer/android/platform/python-for-android/src/libs/armeabi/libapplication.so
/home/konrad/.buildozer/android/platform/android-ndk-r10e/toolchains/arm-linux-androideabi-4.8/prebuilt/linux-x86_64/bin/arm-linux-androideabi-strip --strip-unneeded  /home/konrad/Bureau/kivyapp/.buildozer/android/platform/python-for-android/src/libs/armeabi/libapplication.so
[armeabi] Install        : libsdl.so => libs/armeabi/libsdl.so
install -p /home/konrad/Bureau/kivyapp/.buildozer/android/platform/python-for-android/src/obj/local/armeabi/libsdl.so /home/konrad/Bureau/kivyapp/.buildozer/android/platform/python-for-android/src/libs/armeabi/libsdl.so
/home/konrad/.buildozer/android/platform/android-ndk-r10e/toolchains/arm-linux-androideabi-4.8/prebuilt/linux-x86_64/bin/arm-linux-androideabi-strip --strip-unneeded  /home/konrad/Bureau/kivyapp/.buildozer/android/platform/python-for-android/src/libs/armeabi/libsdl.so
[armeabi] SharedLibrary  : libsdl_main.so
/home/konrad/.buildozer/android/platform/android-ndk-r10e/toolchains/arm-linux-androideabi-4.8/prebuilt/linux-x86_64/bin/arm-linux-androideabi-g++ -Wl,-soname,libsdl_main.so -shared --sysroot=/home/konrad/.buildozer/android/platform/android-ndk-r10e/platforms/android-19/arch-arm /home/konrad/Bureau/kivyapp/.buildozer/android/platform/python-for-android/src/obj/local/armeabi/objs/sdl_main/sdl_main.o -lgcc /home/konrad/Bureau/kivyapp/.buildozer/android/platform/python-for-android/src/obj/local/armeabi/libsdl.so /home/konrad/Bureau/kivyapp/.buildozer/android/platform/python-for-android/src/obj/local/armeabi/libapplication.so -no-canonical-prefixes  -Wl,--no-undefined -Wl,-z,noexecstack -Wl,-z,relro -Wl,-z,now -mthumb  -L/home/konrad/.buildozer/android/platform/android-ndk-r10e/platforms/android-19/arch-arm/usr/lib -llog -lc -lm -o /home/konrad/Bureau/kivyapp/.buildozer/android/platform/python-for-android/src/obj/local/armeabi/libsdl_main.so
/home/konrad/Bureau/kivyapp/.buildozer/android/platform/python-for-android/src/jni/../jni/sdl_main/sdl_main.c:34: error: undefined reference to 'SDL_main'
collect2: error: ld returned 1 exit status
make: *** [/home/konrad/Bureau/kivyapp/.buildozer/android/platform/python-for-android/src/obj/local/armeabi/libsdl_main.so] Error 1
# Command failed: ./distribute.sh -m "kivy" -d "app"
# 
# Buildozer failed to execute the last command
# The error might be hidden in the log above this error
# Please read the full log, and search for it before
# raising an issue with buildozer itself.
# In case of a bug report, please add a full log with log_level = 2

**Comment by inclement** [comment]
Closing as an old toolchain issue, no longer supported and probably fixed in p4a master.
