### ISSUE TITLE
`buildozer android debug` fails with `jinja2.exceptions.TemplateNotFound: build.xml`

### ISSUE THREAD

**Issue by ronbarak** [kivy/buildozer#442]
`buildozer android debug` fails with the massage<br> `jinja2.exceptions.TemplateNotFound: build.xml`

    openstack@ubuntu1604:~/python/kivy$ buildozer -v android debug
    # Check configuration tokens
    # Ensure build layout
    # Check configuration tokens
    # Preparing build
    # Check requirements for android
    # Run 'dpkg --version'
    # Cwd None
    Debian 'dpkg' package management program version 1.18.4 (amd64).
    This is free software; see the GNU General Public License version 2 or
    later for copying conditions. There is NO warranty.
    # Search for Git (git)
    #  -> found at /usr/bin/git
    # Search for Cython (cython)
    #  -> found at /usr/local/bin/cython
    # Search for Java compiler (javac)
    #  -> found at /usr/lib/jvm/java-7-openjdk-amd64/bin/javac
    # Search for Java keytool (keytool)
    #  -> found at /usr/lib/jvm/java-7-openjdk-amd64/jre/bin/keytool
    # Install platform
    # Apache ANT found at /home/openstack/.buildozer/android/platform/apache-ant-1.9.4
    # Android SDK found at /home/openstack/.buildozer/android/platform/android-sdk-20
    # Android NDK found at /home/openstack/.buildozer/android/platform/android-ndk-r9c
    # Check application requirements
    # Run './distribute.sh -l'
    # Cwd /home/openstack/python/kivy/.buildozer/android/platform/python-for-android
    Available modules: android apsw audiostream bidi boost cherrypy c_igraph click cprotobuf cymunk django docutils ecdsa enum34 evdev ffmpeg ffmpeg2 ffpyplayer ffpyplayer_tito flask freetype gevent greenlet harfbuzz hostpython igraph itsdangerous jinja2 jpeg kivent_core kivent_cymunk kivy leveldb libevent libpq libsodium libswift libtorrent libxml2 libxslt libyaml lxml m2crypto markupsafe midistream msgpack mysql_connector netifaces numpy opencv openssl paramiko pil plyer plyvel png polygon protobuf psutil psycopg2 pyasn1 pycrypto pygame pyjnius pylibpd pyopenssl pyparsing pyqrcode python pyyaml sdl setuptools six sqlalchemy sqlite3 storm swift thrift twisted txws werkzeug wokkel zeroconf zope
    # Application requirements already installed, pass
    # Check garden requirements
    # Compile platform
    # Run './distribute.sh -l'
    # Cwd /home/openstack/python/kivy/.buildozer/android/platform/python-for-android
    Available modules: android apsw audiostream bidi boost cherrypy c_igraph click cprotobuf cymunk django docutils ecdsa enum34 evdev ffmpeg ffmpeg2 ffpyplayer ffpyplayer_tito flask freetype gevent greenlet harfbuzz hostpython igraph itsdangerous jinja2 jpeg kivent_core kivent_cymunk kivy leveldb libevent libpq libsodium libswift libtorrent libxml2 libxslt libyaml lxml m2crypto markupsafe midistream msgpack mysql_connector netifaces numpy opencv openssl paramiko pil plyer plyvel png polygon protobuf psutil psycopg2 pyasn1 pycrypto pygame pyjnius pylibpd pyopenssl pyparsing pyqrcode python pyyaml sdl setuptools six sqlalchemy sqlite3 storm swift thrift twisted txws werkzeug wokkel zeroconf zope
    # Distribution already compiled, pass.
    # Build the application #16
    # Copy application source from /home/openstack/python/kivy
    # Create directory /home/openstack/python/kivy/.buildozer/android/app
    # Copy /home/openstack/python/kivy/buildozer android debug
    # Copy /home/openstack/python/kivy/main.py
    # Create directory /home/openstack/python/kivy/.buildozer/android/app/buildozer
    # Copy /home/openstack/python/kivy/buildozer/LICENSE
    # Copy /home/openstack/python/kivy/buildozer/setup.py
    # Create directory /home/openstack/python/kivy/.buildozer/android/app/buildozer/build/lib.linux-x86_64-2.7/buildozer
    # Copy /home/openstack/python/kivy/buildozer/build/lib.linux-x86_64-2.7/buildozer/sitecustomize.py
    # Copy /home/openstack/python/kivy/buildozer/build/lib.linux-x86_64-2.7/buildozer/target.py
    # Copy /home/openstack/python/kivy/buildozer/build/lib.linux-x86_64-2.7/buildozer/jsonstore.py
    # Copy /home/openstack/python/kivy/buildozer/build/lib.linux-x86_64-2.7/buildozer/__main__.py
    # Copy /home/openstack/python/kivy/buildozer/build/lib.linux-x86_64-2.7/buildozer/__init__.py
    # Create directory /home/openstack/python/kivy/.buildozer/android/app/buildozer/build/lib.linux-x86_64-2.7/buildozer/libs
    # Copy /home/openstack/python/kivy/buildozer/build/lib.linux-x86_64-2.7/buildozer/libs/version.py
    # Copy /home/openstack/python/kivy/buildozer/build/lib.linux-x86_64-2.7/buildozer/libs/_structures.py
    # Copy /home/openstack/python/kivy/buildozer/build/lib.linux-x86_64-2.7/buildozer/libs/__init__.py
    # Create directory /home/openstack/python/kivy/.buildozer/android/app/buildozer/build/lib.linux-x86_64-2.7/buildozer/scripts
    # Copy /home/openstack/python/kivy/buildozer/build/lib.linux-x86_64-2.7/buildozer/scripts/remote.py
    # Copy /home/openstack/python/kivy/buildozer/build/lib.linux-x86_64-2.7/buildozer/scripts/client.py
    # Copy /home/openstack/python/kivy/buildozer/build/lib.linux-x86_64-2.7/buildozer/scripts/__init__.py
    # Create directory /home/openstack/python/kivy/.buildozer/android/app/buildozer/build/lib.linux-x86_64-2.7/buildozer/targets
    # Copy /home/openstack/python/kivy/buildozer/build/lib.linux-x86_64-2.7/buildozer/targets/osx.py
    # Copy /home/openstack/python/kivy/buildozer/build/lib.linux-x86_64-2.7/buildozer/targets/android.py
    # Copy /home/openstack/python/kivy/buildozer/build/lib.linux-x86_64-2.7/buildozer/targets/android_new.py
    # Copy /home/openstack/python/kivy/buildozer/build/lib.linux-x86_64-2.7/buildozer/targets/__init__.py
    # Copy /home/openstack/python/kivy/buildozer/build/lib.linux-x86_64-2.7/buildozer/targets/ios.py
    # Create directory /home/openstack/python/kivy/.buildozer/android/app/buildozer/buildozer.egg-info
    # Copy /home/openstack/python/kivy/buildozer/buildozer.egg-info/PKG-INFO
    # Create directory /home/openstack/python/kivy/.buildozer/android/app/buildozer/buildozer
    # Copy /home/openstack/python/kivy/buildozer/buildozer/sitecustomize.py
    # Copy /home/openstack/python/kivy/buildozer/buildozer/target.py
    # Copy /home/openstack/python/kivy/buildozer/buildozer/jsonstore.py
    # Copy /home/openstack/python/kivy/buildozer/buildozer/__main__.py
    # Copy /home/openstack/python/kivy/buildozer/buildozer/__init__.py
    # Create directory /home/openstack/python/kivy/.buildozer/android/app/buildozer/buildozer/libs
    # Copy /home/openstack/python/kivy/buildozer/buildozer/libs/version.py
    # Copy /home/openstack/python/kivy/buildozer/buildozer/libs/_structures.py
    # Copy /home/openstack/python/kivy/buildozer/buildozer/libs/__init__.py
    # Create directory /home/openstack/python/kivy/.buildozer/android/app/buildozer/buildozer/scripts
    # Copy /home/openstack/python/kivy/buildozer/buildozer/scripts/remote.py
    # Copy /home/openstack/python/kivy/buildozer/buildozer/scripts/client.py
    # Copy /home/openstack/python/kivy/buildozer/buildozer/scripts/__init__.py
    # Create directory /home/openstack/python/kivy/.buildozer/android/app/buildozer/buildozer/targets
    # Copy /home/openstack/python/kivy/buildozer/buildozer/targets/osx.py
    # Copy /home/openstack/python/kivy/buildozer/buildozer/targets/android.py
    # Copy /home/openstack/python/kivy/buildozer/buildozer/targets/android_new.py
    # Copy /home/openstack/python/kivy/buildozer/buildozer/targets/__init__.py
    # Copy /home/openstack/python/kivy/buildozer/buildozer/targets/ios.py
    # Create directory /home/openstack/python/kivy/.buildozer/android/app/buildozer/buildozer/tools/packer
    # Copy /home/openstack/python/kivy/buildozer/buildozer/tools/packer/launch
    # Create directory /home/openstack/python/kivy/.buildozer/android/app/buildozer/docs
    # Copy /home/openstack/python/kivy/buildozer/docs/Makefile
    # Create directory /home/openstack/python/kivy/.buildozer/android/app/buildozer/docs/source
    # Copy /home/openstack/python/kivy/buildozer/docs/source/conf.py
    # Package the application
    # project.properties updated
    # Run "python build.py --name 'Kivy Test' --version 0.1 --package org.test.kivytest --sdk 19 --minsdk 9 --private /home/openstack/python/kivy/.buildozer/android/app --orientation sensor --window debug"
    # Cwd /home/openstack/python/kivy/.buildozer/android/platform/python-for-android/dist/kivytest
    Traceback (most recent call last):
      File "build.py", line 517, in <module>
        make_package(args)
      File "build.py", line 303, in make_package
        versioned_name=versioned_name)
      File "build.py", line 68, in render
        template = environment.get_template(template)
      File "buildlib/jinja2.egg/jinja2/environment.py", line 791, in get_template
        return self._load_template(name, self.make_globals(globals))
      File "buildlib/jinja2.egg/jinja2/environment.py", line 765, in _load_template
        template = self.loader.load(self, name, globals)
      File "buildlib/jinja2.egg/jinja2/loaders.py", line 113, in load
        source, filename, uptodate = self.get_source(environment, name)
      File "buildlib/jinja2.egg/jinja2/loaders.py", line 178, in get_source
        raise TemplateNotFound(template)
    jinja2.exceptions.TemplateNotFound: build.xml
    # Command failed: python build.py --name 'Kivy Test' --version 0.1 --package org.test.kivytest --sdk 19 --minsdk 9 --private /home/openstack/python/kivy/.buildozer/android/app --orientation sensor --window debug
    # 
    # Buildozer failed to execute the last command
    # The error might be hidden in the log above this error
    # Please read the full log, and search for it before
    # raising an issue with buildozer itself.
    # In case of a bug report, please add a full log with log_level = 2
    openstack@ubuntu1604:~/python/kivy$ 

There's `build.xml` in `/home/openstack/.buildozer/android/platform/android-sdk-20/tools/ant/build.xml` but from the error above, this is not what `jinja2` expects.

How can I fix the problem and have `buildozer android debug` not fail on this issue?
---

---
*Environment:*

    $ uname -a
    Linux ubuntu1604 4.4.0-57-generic #78-Ubuntu SMP Fri Dec 9 23:50:32 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
    $ buildozer --version
    # Check configuration tokens
    Buildozer 0.32
    $ python -V
    Python 2.7.12

buildozer.spec 

    [app]
    
    # (str) Title of your application
    title = Kivy Test
    
    # (str) Package name
    package.name = kivytest
    
    # (str) Package domain (needed for android/ios packaging)
    package.domain = org.ronbarak
    
    # (str) Source code where the main.py live
    source.dir = .
    
    # (list) Source files to include (let empty to include all the files)
    source.include_exts = py,png,jpg,kv,atlas
    
    # (list) List of inclusions using pattern matching
    #source.include_patterns = assets/*,images/*.png
    
    # (list) Source files to exclude (let empty to not exclude anything)
    #source.exclude_exts = spec
    
    # (list) List of directory to exclude (let empty to not exclude anything)
    #source.exclude_dirs = tests, bin
    
    # (list) List of exclusions using pattern matching
    #source.exclude_patterns = license,images/*/*.jpg
    
    # (str) Application versioning (method 1)
    version = 0.1
    
    # (str) Application versioning (method 2)
    # version.regex = __version__ = ['"](.*)['"]
    # version.filename = %(source.dir)s/main.py
    
    # (list) Application requirements
    # comma seperated e.g. requirements = sqlite3,kivy
    requirements = kivy
    
    # (str) Custom source folders for requirements
    # Sets custom source for any requirements with recipes
    # requirements.source.kivy = ../../kivy
    
    # (list) Garden requirements
    #garden_requirements =
    
    # (str) Presplash of the application
    #presplash.filename = %(source.dir)s/data/presplash.png
    
    # (str) Icon of the application
    #icon.filename = %(source.dir)s/data/icon.png
    
    # (str) Supported orientation (one of landscape, portrait or all)
    #orientation = landscape
    orientation = all
    
    # (list) List of service to declare
    #services = NAME:ENTRYPOINT_TO_PY,NAME2:ENTRYPOINT2_TO_PY
    
    #
    # OSX Specific
    #
    
    #
    # author = © Copyright Info
    
    #
    # Android specific
    #
    
    # (bool) Indicate if the application should be fullscreen or not
    fullscreen = 0
    #fullscreen = 1
    
    # (list) Permissions
    #android.permissions = INTERNET
    
    # (int) Android API to use
    #android.api = 19
    
    # (int) Minimum API required
    #android.minapi = 9
    
    # (int) Android SDK version to use
    #android.sdk = 20
    
    # (str) Android NDK version to use
    #android.ndk = 9c
    
    # (bool) Use --private data storage (True) or --dir public storage (False)
    #android.private_storage = True
    
    # (str) Android NDK directory (if empty, it will be automatically downloaded.)
    #android.ndk_path =
    
    # (str) Android SDK directory (if empty, it will be automatically downloaded.)
    #android.sdk_path =
    
    # (str) ANT directory (if empty, it will be automatically downloaded.)
    #android.ant_path =
    
    # (str) python-for-android git clone directory (if empty, it will be automatically cloned from github)
    #android.p4a_dir =
    
    # (list) python-for-android whitelist
    #android.p4a_whitelist =
    
    # (bool) If True, then skip trying to update the Android sdk
    # This can be useful to avoid excess Internet downloads or save time
    # when an update is due and you just want to test/build your package
    # android.skip_update = False
    
    # (str) Android entry point, default is ok for Kivy-based app
    #android.entrypoint = org.renpy.android.PythonActivity
    
    # (list) List of Java .jar files to add to the libs so that pyjnius can access
    # their classes. Don't add jars that you do not need, since extra jars can slow
    # down the build process. Allows wildcards matching, for example:
    # OUYA-ODK/libs/*.jar
    #android.add_jars = foo.jar,bar.jar,path/to/more/*.jar
    
    # (list) List of Java files to add to the android project (can be java or a
    # directory containing the files)
    #android.add_src =
    
    # (str) python-for-android branch to use, if not master, useful to try
    # not yet merged features.
    #android.branch = master
    
    # (str) OUYA Console category. Should be one of GAME or APP
    # If you leave this blank, OUYA support will not be enabled
    #android.ouya.category = GAME
    
    # (str) Filename of OUYA Console icon. It must be a 732x412 png image.
    #android.ouya.icon.filename = %(source.dir)s/data/ouya_icon.png
    
    # (str) XML file to include as an intent filters in <activity> tag
    #android.manifest.intent_filters =
    
    # (list) Android additionnal libraries to copy into libs/armeabi
    #android.add_libs_armeabi = libs/android/*.so
    #android.add_libs_armeabi_v7a = libs/android-v7/*.so
    #android.add_libs_x86 = libs/android-x86/*.so
    #android.add_libs_mips = libs/android-mips/*.so
    
    # (bool) Indicate whether the screen should stay on
    # Don't forget to add the WAKE_LOCK permission if you set this to True
    #android.wakelock = False
    
    # (list) Android application meta-data to set (key=value format)
    #android.meta_data =
    
    # (list) Android library project to add (will be added in the
    # project.properties automatically.)
    #android.library_references =
    
    # (str) Android logcat filters to use
    #android.logcat_filters = *:S python:D
    
    # (bool) Copy library instead of making a libpymodules.so
    #android.copy_libs = 1
    
    #
    # iOS specific
    #
    
    # (str) Path to a custom kivy-ios folder
    #ios.kivy_ios_dir = ../kivy-ios
    
    # (str) Name of the certificate to use for signing the debug version
    # Get a list of available identities: buildozer ios list_identities
    #ios.codesign.debug = "iPhone Developer: <lastname> <firstname> (<hexstring>)"
    
    # (str) Name of the certificate to use for signing the release version
    #ios.codesign.release = %(ios.codesign.debug)s
    
    
    [buildozer]
    
    # (int) Log level (0 = error only, 1 = info, 2 = debug (with command output))
    log_level = 2
    #log_level = 1
    
    # (int) Display warning if buildozer is run as root (0 = False, 1 = True)
    warn_on_root = 1
    
    # (str) Path to build artifact storage, absolute or relative to spec file
    # build_dir = ./.buildozer
    
    # (str) Path to build output (i.e. .apk, .ipa) storage
    # bin_dir = ./bin
    
    #    -----------------------------------------------------------------------------
    #    List as sections
    #
    #    You can define all the "list" as [section:key].
    #    Each line will be considered as a option to the list.
    #    Let's take [app] / source.exclude_patterns.
    #    Instead of doing:
    #
    #[app]
    #source.exclude_patterns = license,data/audio/*.wav,data/images/original/*
    #
    #    This can be translated into:
    #
    #[app:source.exclude_patterns]
    #license
    #data/audio/*.wav
    #data/images/original/*
    #
    
    
    #    -----------------------------------------------------------------------------
    #    Profiles
    #
    #    You can extend section / key with a profile
    #    For example, you want to deploy a demo version of your application without
    #    HD content. You could first change the title to add "(demo)" in the name
    #    and extend the excluded directories to remove the HD content.
    #
    #[app@demo]
    #title = My Application (demo)
    #
    #[app:source.exclude_patterns@demo]
    #images/hd/*
    #
    #    Then, invoke the command line with the "demo" profile:
    #
    #buildozer --profile demo android debug

main.py
     
    from kivy.app import App
    
    from kivy.uix.scatter import Scatter
    from kivy.uix.label import Label
    from kivy.uix.floatlayout import FloatLayout
    
    __version__ = '1.0'
    
    class TutorialApp(App):
        def build(self):
            f = FloatLayout()
            s = Scatter()
            l = Label(text="Hello!",
                      font_size=150)
    
            f.add_widget(s)
            s.add_widget(l)
            return f
    
    if __name__ == "__main__":
        TutorialApp().run()

**Comment by tito** [comment]
Try again, but with android_new target !
