### ISSUE TITLE
how to add  --arch=armeabi-v7a to buildozer spec

### ISSUE THREAD

**Issue by razzbee** [kivy/buildozer#443]
Hello , I am getting this error You probably want to build with --arch=armeabi-v7a instead when I switch to android api > 19 , please how do I change the arch armeabi-v7a in buildozer spec file

**Comment by Terrydaktal** [comment]
I am also having the same issue

**Comment by gcobos** [comment]
+1

**Comment by leftis** [comment]
Any help on this one?

**Comment by tito** [comment]
If you use android_new (now renamed android), it already does it.
The buildozer.spec use "android.arch" which is by default "armeabi-v7a". And we pass the option "--arch" to python-for-android.
