### ISSUE TITLE
[Errno 13] Permission denied; Buildozer on Flask Server

### ISSUE THREAD

**Issue by minglethepringle** [kivy/buildozer#445]
I have a very basic Flask server:

    from flask import Flask
    app = Flask(__name__)

    @app.route('/')
    def hello():
        return "Hello World!"

    if __name__ == '__main__':
        app.run() 

I built the file using buildozer with `buildozer android_new debug` (thanks @inclement , it successfully builds), but when I install the APK it crashes, giving out an error message, saying "Permission Denied." I searched this error up and apparently it's because the port is under 1025, which requires root. However, I specified `android.bootstrap=webview` in `buildozer.spec` to use the WebView bootstrap, which runs on port 5000. I also did include Flask as a requirement. 

My ADB log: http://pastebin.com/Tbsw5eEQ
My `buildozer.spec`: http://pastebin.com/3dDUL764

**Comment by kchomski** [comment]
It works on current buildozer version (0.33dev). You have to remove `kivy` from requirements (leave only `flask`) and uncomment line with android permissions (remove '#' from `#android.permissions = INTERNET`).

**Comment by inclement** [comment]
Closing as fixed, thanks @kchomski
