### ISSUE TITLE
CalledProcessError: Command '['python', 'package_app.py', '--displayname=Music Favorites']' returned non-zero exit status 1

### ISSUE THREAD

**Issue by Ajax12345** [kivy/buildozer#448]
Hello,
I am trying to build an osx app with kivy and buildozer, but I am getting "returned non-zero exit status 1". I have browsed the buildozer issue feed on github, but I am not able to find anything related to OSX. Could anybody point me in the right direction?

Thank you

**Comment by inclement** [comment]
Closing as not specific enough, but probably fixed in master.
