### ISSUE TITLE
Update the Virtual Machine @ https://kivy.org/#download

### ISSUE THREAD

**Issue by jcsantosx** [kivy/buildozer#449]
I downloaded the Virtual Machine, had to do some updates(buildozer, python-for-android, cython, appdirs, sh) but can't get an app running on Android like the e.g. issue #445

If you guys could upload an updated version and python 3 ready of Virtual Machine, would be fantastic

**Comment by tito** [comment]
It has been done! But because buildozer is not ready for python3 automatically, VM doesn't preinstall anything about it.
