### ISSUE TITLE
New toolchain - lxml included but not able to import

### ISSUE THREAD

**Issue by ngoonee** [kivy/buildozer#451]
Now that I'm using android_new, I get crashing when trying to import lxml. The relevant error is:-

ImportError: dlopen failed: "/data/data/org.test.songprez/files/app/lib/python2.7/site-packages/lxml/etree.so" is 64-bit instead of 32-bit

My requirements line is requirements = kivy, twisted, Whoosh, lxml, xmltodict, blinker, netifaces
and the rest seems to import and work as expected. Somehow lxml doesn't.

Same symptom on 0.32 and on latest git.

    01-08 06:50:13.746   635   635 W linker  : /data/app/org.test.songprez-2/lib/arm/libpython2.7.so: is missing DT_SONAME will use basename as a replacement: "libpython2.7.so"
    01-08 06:50:13.761   635   635 W linker  : /data/data/org.test.songprez/files/app/lib/python2.7/lib-dynload/_io.so: is missing DT_SONAME will use basename as a replacement: "_io.so"
    01-08 06:50:13.763   635   635 W linker  : /data/data/org.test.songprez/files/app/lib/python2.7/lib-dynload/unicodedata.so: is missing DT_SONAME will use basename as a replacement: "unicodedata.so"
    01-08 06:50:13.767   635   635 W linker  : /data/data/org.test.songprez/files/app/lib/python2.7/lib-dynload/_ctypes.so: is missing DT_SONAME will use basename as a replacement: "_ctypes.so"
    01-08 06:50:14.024   635   804 I python  : Initialize Python for Android
    01-08 06:50:14.024   635   804 I python  : Changing directory to the one provided by ANDROID_ARGUMENT
    01-08 06:50:14.024   635   804 I python  : /data/user/0/org.test.songprez/files/app
    01-08 06:50:14.024   635   804 I python  : Preparing to initialize python
    01-08 06:50:14.024   635   804 I python  : crystax_python does not exist
    01-08 06:50:14.040   635   804 I python  : Initialized python
    01-08 06:50:14.040   635   804 I python  : AND: Init threads
    01-08 06:50:14.042   635   804 I python  : testing python print redirection
    01-08 06:50:14.043   635   804 I python  : Setting up python from ANDROID_PRIVATE
    01-08 06:50:14.045   635   804 I python  : ('Android path', ['/data/user/0/org.test.songprez/files/app/lib/python27.zip', '/data/user/0/org.test.songprez/files/app/lib/python2.7/', '/data/user/0/org.test.songprez/files/app/lib/python2.7/lib-dynload/', '/data/user/0/org.test.songprez/files/app/lib/python2.7/site-packages/', '/data/user/0/org.test.songprez/files/app'])
    01-08 06:50:14.108   635   804 I python  : ('os.environ is', {'ANDROID_APP_PATH': '/data/user/0/org.test.songprez/files/app', 'EXTERNAL_STORAGE': '/sdcard', 'SYSTEMSERVERCLASSPATH': '/system/framework/services.jar:/system/framework/wifi-service.jar:/system/framework/ethernet-service.jar', 'ANDROID_SOCKET_zygote': '11', 'BOOTCLASSPATH': '/system/framework/core-libart.jar:/system/framework/conscrypt.jar:/system/framework/okhttp.jar:/system/framework/core-junit.jar:/system/framework/bouncycastle.jar:/system/framework/ext.jar:/system/framework/framework.jar:/system/framework/telephony-common.jar:/system/framework/voip-common.jar:/system/framework/ims-common.jar:/system/framework/apache-xml.jar:/system/framework/org.apache.http.legacy.boot.jar:/system/framework/tcmiface.jar:/system/framework/qcmediaplayer.jar:/system/framework/WfdCommon.jar:/system/framework/qcom.fmradio.jar:/system/framework/oem-services.jar:/system/framework/com.qti.dpmframework.jar:/system/framework/dpmapi.jar:/system/framework/com.qti.location.sdk.jar', 'ANDROID_PROPERTY_WORKSPACE': '9,0', 'PATH': '/sbin:/vendor/bin:/system/sbin:/system/bin:/system/xbin:/bin', 'ANDROID_STORAGE': '/storage', 'ANDROID_BOOTLOGO':'1', 'ANDROID_DATA': '/data', 'ANDROID_ASSETS': '/system/app', 'PYTHONOPTIMIZE': '2', 'ANDROID_PRIVATE': '/data/user/0/org.test.songprez/files', 'ANDROID_ENTRYPOINT': 'main.pyo', 'SECONDARY_STORAGE': '/storage/sdcard1', 'PYTHONPATH': '/data/user/0/org.test.songprez/files/app:/data/user/0/org.test.songprez/files/app/lib', 'CLASSPATH': '/system/framework/XposedBridge.jar', 'PYTHON_NAME': 'python', 'LD_PRELOAD': 'libNimsWrap.so', 'ANDROID_ROOT': '/system', 'PYTHONHOME': '/data/user/0/org.test.songprez/files/app', 'ASEC_MOUNTPOINT': '/mnt/asec', 'ANDROID_ARGUMENT': '/data/user/0/org.test.songprez/files/app'})
    01-08 06:50:14.108   635   804 I python  : ('Android kivy bootstrap done. __name__ is', '__main__')
    01-08 06:50:14.407   635   804 I python  : ['/data/user/0/org.test.songprez/files/app/lib/python2.7/site-packages', '/data/user/0/org.test.songprez/files/app/lib/site-python']
    01-08 06:50:14.407   635   804 I python  : AND: Ran string
    01-08 06:50:14.407   635   804 I python  : Run user program, change dir and execute entrypoint
    01-08 06:50:14.760   635   804 I python  : [WARNING] [Config      ] Older configuration version detected (0 instead of 17)
    01-08 06:50:14.760   635   804 I python  : [WARNING] [Config      ] Upgrading configuration in progress.
    01-08 06:50:14.779   635   804 I python  : [INFO   ] [Logger      ] Record log in /data/user/0/org.test.songprez/files/app/.kivy/logs/kivy_17-01-08_0.txt
    01-08 06:50:14.780   635   804 I python  : [INFO   ] [Kivy        ] v1.9.2-dev0
    01-08 06:50:14.780   635   804 I python  : [INFO   ] [Python      ] v2.7.2 (default, Jan  7 2017, 11:33:08)
    01-08 06:50:14.780   635   804 I python  : [GCC 4.8]
    01-08 06:50:15.357   635   804 W linker  : /data/data/org.test.songprez/files/app/lib/python2.7/site-packages/twisted/python/_sendmsg.so: is missing DT_SONAME will use basename as a replacement: "_sendmsg.so"
    01-08 06:50:15.439   635   804 W linker  : /data/data/org.test.songprez/files/app/lib/python2.7/site-packages/kivy/_clock.so: is missing DT_SONAME will use basename as a replacement: "_clock.so"
    01-08 06:50:15.455   635   804 W linker  : /data/data/org.test.songprez/files/app/lib/python2.7/site-packages/kivy/_event.so: is missing DT_SONAME will use basename as a replacement: "_event.so"
    01-08 06:50:15.458   635   804 W linker  : /data/data/org.test.songprez/files/app/lib/python2.7/site-packages/kivy/properties.so: is missing DT_SONAME will use basename as a replacement: "properties.so"
    01-08 06:50:15.471   635   804 I python  : [INFO   ] [Factory     ] 193 symbols loaded
    01-08 06:50:16.513   635   804 W linker  : /data/data/org.test.songprez/files/app/lib/python2.7/site-packages/kivy/graphics/instructions.so: is missing DT_SONAME will use basename as a replacement: "instructions.so"
    01-08 06:50:16.524   635   804 W linker  : /data/data/org.test.songprez/files/app/lib/python2.7/site-packages/kivy/graphics/buffer.so: is missing DT_SONAME will use basename as a replacement: "buffer.so"
    01-08 06:50:16.528   635   804 W linker  : /data/data/org.test.songprez/files/app/lib/python2.7/site-packages/kivy/graphics/vertex.so: is missing DT_SONAME will use basename as a replacement: "vertex.so"
    01-08 06:50:16.531   635   804 W linker  : /data/data/org.test.songprez/files/app/lib/python2.7/site-packages/kivy/graphics/cgl.so: is missing DT_SONAME will use basename as a replacement: "cgl.so"
    01-08 06:50:16.536   635   804 W linker  : /data/data/org.test.songprez/files/app/lib/python2.7/site-packages/kivy/graphics/vbo.so: is missing DT_SONAME will use basename as a replacement: "vbo.so"
    01-08 06:50:16.540   635   804 W linker  : /data/data/org.test.songprez/files/app/lib/python2.7/site-packages/kivy/graphics/compiler.so: is missing DT_SONAME will use basename as a replacement: "compiler.so"
    01-08 06:50:16.550   635   804 W linker  : /data/data/org.test.songprez/files/app/lib/python2.7/site-packages/kivy/graphics/transformation.so: is missing DT_SONAME will use basename as a replacement: "transformation.so"
    01-08 06:50:16.554   635   804 W linker  : /data/data/org.test.songprez/files/app/lib/python2.7/site-packages/kivy/graphics/shader.so: is missing DT_SONAME will use basename as a replacement: "shader.so"
    01-08 06:50:16.558   635   804 W linker  : /data/data/org.test.songprez/files/app/lib/python2.7/site-packages/kivy/graphics/texture.so: is missing DT_SONAME will use basename as a replacement: "texture.so"
    01-08 06:50:16.562   635   804 W linker  : /data/data/org.test.songprez/files/app/lib/python2.7/site-packages/kivy/graphics/context_instructions.so: is missing DT_SONAME will use basename as a replacement: "context_instructions.so"
    01-08 06:50:16.585   635   804 W linker  : /data/data/org.test.songprez/files/app/lib/python2.7/site-packages/kivy/core/image/_img_sdl2.so: is missing DT_SONAME will use basename as a replacement: "_img_sdl2.so"
    01-08 06:50:16.598   635   804 I python  : [INFO   ] [Image       ] Providers: img_tex, img_dds, img_sdl2, img_gif (img_pil, img_ffpyplayer ignored)
    01-08 06:50:16.601   635   804 W linker  : /data/data/org.test.songprez/files/app/lib/python2.7/site-packages/kivy/graphics/fbo.so: is missing DT_SONAME will use basename as a replacement: "fbo.so"
    01-08 06:50:16.605   635   804 W linker  : /data/data/org.test.songprez/files/app/lib/python2.7/site-packages/kivy/graphics/context.so: is missing DT_SONAME will use basename as a replacement: "context.so"
    01-08 06:50:16.610   635   804 W linker  : /data/data/org.test.songprez/files/app/lib/python2.7/site-packages/kivy/graphics/opengl.so: is missing DT_SONAME will use basename as a replacement: "opengl.so"
    01-08 06:50:16.615   635   804 W linker  : /data/data/org.test.songprez/files/app/lib/python2.7/site-packages/kivy/graphics/opengl_utils.so: is missing DT_SONAME will use basename as a replacement: "opengl_utils.so"
    01-08 06:50:16.623   635   804 W linker  : /data/data/org.test.songprez/files/app/lib/python2.7/site-packages/kivy/graphics/vertex_instructions.so: is missing DT_SONAME will use basename as a replacement: "vertex_instructions.so"
    01-08 06:50:16.628   635   804 W linker  : /data/data/org.test.songprez/files/app/lib/python2.7/site-packages/kivy/graphics/stencil_instructions.so: is missing DT_SONAME will use basename as a replacement: "stencil_instructions.so"
    01-08 06:50:16.633   635   804 W linker  : /data/data/org.test.songprez/files/app/lib/python2.7/site-packages/kivy/graphics/gl_instructions.so: is missing DT_SONAME will use basename as a replacement: "gl_instructions.so"
    01-08 06:50:16.637   635   804 W linker  : /data/data/org.test.songprez/files/app/lib/python2.7/site-packages/kivy/graphics/scissor_instructions.so: is missing DT_SONAME will use basename as a replacement: "scissor_instructions.so"
    01-08 06:50:16.646   635   804 W linker  : /data/data/org.test.songprez/files/app/lib/python2.7/site-packages/kivy/weakproxy.so: is missing DT_SONAME will use basename as a replacement: "weakproxy.so"
    01-08 06:50:16.660   635   804 W linker  : /data/data/org.test.songprez/files/app/lib/python2.7/site-packages/kivy/core/text/text_layout.so: is missing DT_SONAME will use basename as a replacement: "text_layout.so"
    01-08 06:50:16.667   635   804 W linker  : /data/data/org.test.songprez/files/app/lib/python2.7/site-packages/kivy/core/text/_text_sdl2.so: is missing DT_SONAME will use basename as a replacement: "_text_sdl2.so"
    01-08 06:50:16.671   635   804 I python  : [INFO   ] [Text        ] Provider: sdl2
    01-08 06:50:16.690   635   804 W linker  : /data/data/org.test.songprez/files/app/lib/python2.7/site-packages/kivy/core/window/_window_sdl2.so: is missing DT_SONAME will use basename as a replacement: "_window_sdl2.so"
    01-08 06:50:16.722   635   804 I python  : [INFO   ] [OSC         ] using <thread> for socket
    01-08 06:50:16.730   635   804 I python  : [ERROR  ] [Input       ] AndroidJoystick is not supported by your version of linux
    01-08 06:50:16.730   635   804 I python  : Traceback (most recent call last):
    01-08 06:50:16.730   635   804 I python  :   File "/home/data/Coding/buildozer/.buildozer/android/platform/build/dists/songprez/private/lib/python2.7/site-packages/kivy/input/providers/__init__.py", line 57, in <module>
    01-08 06:50:16.730   635   804 I python  :   File "/home/data/Coding/buildozer/.buildozer/android/platform/build/dists/songprez/private/lib/python2.7/site-packages/kivy/input/providers/androidjoystick.py", line 20, in <module>
    01-08 06:50:16.730   635   804 I python  : Exception: android lib not found.
    01-08 06:50:16.733   635   804 I python  : [INFO   ] [Window      ] Provider: sdl2
    01-08 06:50:16.750   635   804 W linker  : /data/data/org.test.songprez/files/app/lib/python2.7/site-packages/kivy/graphics/cgl_backend/cgl_glew.so: is missing DT_SONAME will use basename as a replacement: "cgl_glew.so"
    01-08 06:50:16.755   635   804 W linker  : /data/data/org.test.songprez/files/app/lib/python2.7/site-packages/kivy/graphics/cgl_backend/cgl_gl.so: is missing DT_SONAME will use basename as a replacement: "cgl_gl.so"
    01-08 06:50:16.791   635   804 I python  : [INFO   ] [GL          ] Using the "OpenGL ES 2" graphics system
    01-08 06:50:16.792   635   804 I python  : [INFO   ] [GL          ] Backend used <gl>
    01-08 06:50:16.793   635   804 I python  : [INFO   ] [GL          ] OpenGL version <OpenGL ES 3.0 V@140.0 AU@ (GIT@I3f4bae6ca5)>
    01-08 06:50:16.793   635   804 I python  : [INFO   ] [GL          ] OpenGL vendor <Qualcomm>
    01-08 06:50:16.794   635   804 I python  : [INFO   ] [GL          ] OpenGL renderer <Adreno (TM) 330>
    01-08 06:50:16.795   635   804 I python  : [INFO   ] [GL          ] OpenGL parsed version: 3, 0
    01-08 06:50:16.795   635   804 I python  : [INFO   ] [GL          ] Texture max size <4096>
    01-08 06:50:16.796   635   804 I python  : [INFO   ] [GL          ] Texture max units <16>
    01-08 06:50:16.857   635   804 I python  : [INFO   ] [Shader      ] program: <--From Vertex Shader:
    01-08 06:50:16.857   635   804 I python  : --From Fragment Shader:
    01-08 06:50:16.857   635   804 I python  : Link was successful.>
    01-08 06:50:16.864   635   804 I python  : [INFO   ] [Window      ] auto add sdl2 input provider
    01-08 06:50:16.866   635   804 I python  : [INFO   ] [Window      ] virtual keyboard not allowed, single mode, not docked
    01-08 06:50:16.872   635   804 W linker  : /data/data/org.test.songprez/files/app/lib/python2.7/site-packages/jnius/jnius.so: is missing DT_SONAME will use basename as a replacement: "jnius.so"
    01-08 06:50:18.658   635   804 I python  :  Traceback (most recent call last):
    01-08 06:50:18.659   635   804 I python  :    File "/home/data/Coding/buildozer/.buildozer/android/app/main.py", line 47, in <module>
    01-08 06:50:18.660   635   804 I python  :    File "/home/data/Coding/buildozer/.buildozer/android/app/songprez/phone/app.py", line 22, in <module>
    01-08 06:50:18.661   635   804 I python  :    File "/home/data/Coding/buildozer/.buildozer/android/app/songprez/control/spservercontrol.py", line 10, in <module>
    01-08 06:50:18.662   635   804 I python  :    File "/home/data/Coding/buildozer/.buildozer/android/app/songprez/control/spsearch.py", line 10, in <module>
    01-08 06:50:18.663   635   804 I python  :    File "/home/data/Coding/buildozer/.buildozer/android/app/songprez/control/spsong.py", line 18, in <module>
    01-08 06:50:18.664   635   804 I python  :    File "/home/data/Coding/buildozer/.buildozer/android/app/songprez/control/sputil.py", line 9, in <module>
    01-08 06:50:18.665   635   804 I python  :  ImportError: dlopen failed: "/data/data/org.test.songprez/files/app/lib/python2.7/site-packages/lxml/etree.so" is 64-bit instead of 32-bit
    01-08 06:50:18.739   635   804 I python  : Python for android ended.
    01-08 06:50:18.859   742   742 F DEBUG   :     #00 pc 000bf63a  /data/app/org.test.songprez-2/lib/arm/libpython2.7.so (PyThreadState_New+93)
    01-08 06:50:18.859   742   742 F DEBUG   :     #01 pc 000c9975  /data/app/org.test.songprez-2/lib/arm/libpython2.7.so (PyThread_acquire_lock+76)

**Comment by tito** [comment]
I'm closing this, as you said, it's an issue in python-for-android, nothing to do with buildozer itself. Thanks for reporting!
