### ISSUE TITLE
how to set path for p4a

### ISSUE THREAD

**Issue by malverick** [kivy/buildozer#454]
I have python-for-android installed in my machine but whenever I run `buildozer android debug` it clones python for android repository for generating the apk. Is there any way so that it can access the python-for-android directory already installed in my system instead of cloning it again and again.

**Comment by inclement** [comment]
There is an option in the buildozer.spec for this, `android.p4a_dir = ...`

**Comment by malverick** [comment]
thanks for the help @inclement.
