### ISSUE TITLE
sqlite3 not working with android_new

### ISSUE THREAD

**Issue by ngala** [kivy/buildozer#457]
Before raising the issue, I have tried to refer any old issues with similar problems. Making attempts to work out solutions.

The Kivy App is running fine on the setup(Ubuntu 15.04 VM). The app was basic and did not have any other python libraries. I could successfully create an APK file and the App worked same on Android(Nexus 5x, Nougat 7.1.1) as it did on Ubuntu.

Now when I tried to import sqlite3, it worked fine on Ubuntu but it crashed on the phone. I was getting `no module named sqlite3` in my logcat.

On some digging,  I referred to https://github.com/kivy/kivy/issues/705
I removed the blacklisted files referring to sqlite3(including both sqlite3/* and lib-dynload/_sqlite3.so) from blacklist.txt and also installed libsqlite3-dev package. The error changed slightly... `no module named _sqlite3`

Apparently solution in that issue was partially applicable to new toolchain.

I went a step further and deleted .buildozer folder completely so that it would download and install packages in case they are broken.

but that did not resolve the issue...now it is getting compiler error

```
checking machine type as reported by uname -m... x86_64
checking for --without-gcc... no
checking for arm-eabi-gcc... /usr/bin/ccache arm-linux-androideabi-gcc -DANDROID -mandroid -fomit-frame-pointer --sysroot /home/droid/.buildozer/android/platform/android-ndk-r9c/platforms/android-19/arch-arm
checking whether the C compiler works... no
configure: error: in `/home/droid/andr/.buildozer/android/platform/build/build/other_builds/python2-sqlite3/armeabi-v7a/python2':
configure: error: C compiler cannot create executables
See `config.log' for more details
```
here's the complete file for buildozer debug output (http://pastebin.com/ANuYTu8R) and config.log(http://pastebin.com/maWgbBpw)

The apps created without sqlite3 are still working fine on both Ubuntu and Android.

**Comment by ngala** [comment]
Hi...any update in this?

**Comment by tito** [comment]
I think that's an issue with python-for-android directly. The recipe build order put sqlite3 after compiling Python, but it should been done before. I'm moving it.

**Comment by tito** [comment]
Issue moved to [kivy/python-for-android #1053](https://github.com/kivy/python-for-android/issues/1053) via [**ZenHub**](https://www.zenhub.com/)
