### ISSUE TITLE
Tkinter as buildozer requirement

### ISSUE THREAD

**Issue by Ormgair** [kivy/buildozer#462]
Hello! Is there any way to include tkinter as requirement for buildozer? I've tried to print this:
`requirements=tkinter`
`requirements=Tkinter`
`requirements=tk`
`requirements=Tk`

But  `buildozer android debug deploy run` return this error:
> No matching distribution found

**Comment by yaki29** [comment]
@Ormgair Buildozer uses python-for-android recipes to satisfy your application's requirements. But p4a doesn't have any recipe for tkinter. You can try to add recipe for this.

**Comment by rafalo1333** [comment]
Isn't Tkinter part od python standard library? It shouldn't need a recipe. Maybe a blacklist removes the tkinter files?

BTW, why do you need TK on android? It wont work surely, because Tkinter doesnt know how to handle Android windowing system.

**Comment by tito** [comment]
Not an issue with buildozer, closing.
