### ISSUE TITLE
apk doesn't load gifs (as jpg in zip files)

### ISSUE THREAD

**Issue by fisiodes** [kivy/buildozer#466]
My app run perfectly on windows but, in buildozer apk, gifs (as jpg in zip files) are replaced by white squares. Same issue with kivy launcher.
Added zip format in source.include_exts and added pil requirement in buildozer.spec but nothing seems work. Zips are in the right path (indeed they are shown on pc).
Logcat report this error: `I/python (24189): [ERROR ] [Image ] Error loading texture killbtn.zip` .
Is this a bug or what am i missing? thanks anyway!

**Comment by tito** [comment]
Try to activate the debug log and see if you can have more information. But this is not an issue with buildozer itself.

**Comment by KajaMohyaddeen** [comment]
> My app run perfectly on windows but, in buildozer apk, gifs (as jpg in zip files) are replaced by white squares. Same issue with kivy launcher. Added zip format in source.include_exts and added pil requirement in buildozer.spec but nothing seems work. Zips are in the right path (indeed they are shown on pc). Logcat report this error: `I/python (24189): [ERROR ] [Image ] Error loading texture killbtn.zip` . Is this a bug or what am i missing? thanks anyway!

I have also the same problem , how could you resolved ?
