### ISSUE TITLE
Crash of APK on start

### ISSUE THREAD

**Issue by cocodevienne** [kivy/buildozer#467]
Ok guys, so I have following problem: I made a Kivy App and tested the code on Android using the Kivy Launcher. Now that worked just fine. I then tested the code on my Windows PC and that worked fine also and finally I tested the code on Kali Linux and that also worked fine. Now when I run my code through Buildozer using different API, MinAPI, SDK and NDK levels I always get the same result. The APK builds just fine but when I install it on my phone, the App crashes on startup. What is going on? My environment: Windows 7 with a Kali Linux VM 64-bit inside of VMWare. Guys please help me, I'm going nuts. The repo is here: http://github.com/cocodevienne/pique
The last APK I built is in the bin folder.

**Comment by FeralBytes** [comment]
Please attach a full adb logcat session. Also include your buildozer.spec since it is not in your repository. Can you clarify; does the application work with a lover API level; or is it broken no matter what API level you use.

**Comment by cocodevienne** [comment]
I cannot take the logcat as I am working in a VM. It crashes no matter what API I use. For the last build I used the following: API to use: 14
Min API: 8
SDK: 23
NDK: 9

I managed to make a working APK some time ago but I forgot which config I used! @FeralBytes

**Comment by inclement** [comment]
@cocodevienne We can't help you unless you provide debug information. There's no reason that working in a VM should prevent you from accessing logcat - you should be able to pass through the usb device to the VM, or use logcat outside the VM, or possibly use something else like wifi logcat.

**Comment by cocodevienne** [comment]
The problem is that I do not know which drivers to use for my phone and the phone is very new and I do not want to screw it up! So what advice can you give me? @inclement @FeralBytes Which SDK, NDK and API should I use for a Marshmallow device?

**Comment by inclement** [comment]
Screw what up? You won't break your phone by using an old SDK. But anyway, probably just install install the newest SDK.

**Comment by cocodevienne** [comment]
How do I uninstall the SDK? @inclement

**Comment by matham** [comment]
The issue tracker is for reporting bugs and requesting features. Not for help questions. 

Also, when given an answer with a follow up question, please respond as requested and don't switch to something else. You were requested to add a logcat, please reopen when you have one that shows the problem. Also, please do some basic research before asking a question. How to uninstall the SDK is something you should be able to easily figure out yourself.

**Comment by cocodevienne** [comment]
I am completely new to this! I said why I cannot attach a logcat! So instead of being so aggressive help me, I am kind enough to try out your tools and it is your duty to help people and not to tell them go figure it out themselves! If they were able they ould do it by themselves! @matham  What I meant is if  I install the wrong driver for my phone, I might damage my phone and I do not wanmt to risk that. Maybe you could install it on yours assuming you have everything set up on your PC and tell me if it wokrs for you and if not maybe paste the logacte here and see what the error is. I know its asking a bit much but I would be infinitely grateful to you! @inclement

**Comment by inclement** [comment]
None of this involves installing drivers on your phone. The process of using logcat is independent of Kivy, or python-for-android, and you can check the normal android documentation to learn about it. If you have questions, that's fine, but you need to look for the answers yourself first.

**Comment by cocodevienne** [comment]
All I want to know is which SDK, NDK and API levels I should use for my buildozer.spec! @inclement 
I bpought a wireless charger for my phone today because my USB cable and port are broken! Now that's why I canot take logcats! @inclement

**Comment by yaki29** [comment]
@cocodevienne you can use wifi logcat applications https://play.google.com/store/apps/details?id=com.ryosoftware.adbw .

**Comment by cocodevienne** [comment]
I need root, which I do not have! @yaki29

**Comment by matham** [comment]
Did you really just ask us to install and run your apk? You have asked on IRC for help on how to silently install things from a py4a app without user knowledge, do you really think one of us would install this apk given that? 

You also need an expectation re-adjustment about open source software. We create these tools, not so that users can do us a favor and test it. It's so that we can make things easier for users in their applications. And as I'm sure you know, none of us get paid for this. So it's not OK to ask us to do your work for you or demand things from us.

So, given your previous behavior on github and similar behavior on IRC; you have opened PRs that seemed to be just for trolling, and your behavior on IRC has been similarly aggressive, I think we'll ban you for now in order to maintain the health of the community.
