### ISSUE TITLE
buildozer fails to find Android SDK

### ISSUE THREAD

**Issue by jbillhei** [kivy/buildozer#468]
Android apparently doesn't post zip files of the sdk anymore, so buildozer cannot find them.  It ends downloading the 404 message and then fails to unzip it.

If I manually obtain the SDK, zip it with the name buildozer expects, and place it in the folder where buildozer says it is looking, it ignores that and tries to download it anyway.

I've tried pointing the buildozer.spec to the SDK path.  It seems to completely ignore that option, and tries to download.

I've tried this on OS X and Ubuntu, using the master branch, same results.

Clearly, other people are managing to build for Android, so there must be something obvious that I'm missing.  Is there anything else I can try?

Here's what I've been looking at: 

```
# Check configuration tokens
# Ensure build layout
# Check configuration tokens
# Read available permissions from api-versions.xml
# Preparing build
# Check requirements for android
# Search for Git (git)
#  -> found at /usr/bin/git
# Search for Cython (cython)
#  -> found at /Users/<myusername>/PythonVirtualEnv/sapphire/bin/cython
# Search for Java compiler (javac)
#  -> found at /System/Library/Frameworks/JavaVM.framework/Versions/A/Commands/javac
# Search for Java keytool (keytool)
#  -> found at /System/Library/Frameworks/JavaVM.framework/Versions/A/Commands/keytool
# Install platform
# Apache ANT found at /Users/<myusername>/.buildozer/android/platform/apache-ant-1.9.4
# Android SDK is missing, downloading
# Downloading http://dl.google.com/android/android-sdk_r25-macosx.zip
# Unpacking Android SDK
# Run 'unzip /Users/<myusername>/.buildozer/android/platform/android-sdk_r25-macosx.zip'
# Cwd /Users/<myusername>/.buildozer/android/platform
Archive:  /Users/<myusername>/.buildozer/android/platform/android-sdk_r25-macosx.zip
# Command failed: unzip /Users/<myusername>/.buildozer/android/platform/android-sdk_r25-macosx.zip
# 
# Buildozer failed to execute the last command
# The error might be hidden in the log above this error
# Please read the full log, and search for it before
# raising an issue with buildozer itself.
# In case of a bug report, please add a full log with log_level = 2
```

**Comment by jbillhei** [comment]
Ok, turns out I was, in fact, pointing to the wrong path for the SDK.  Head ---> desk.  I do have a working build now.

In any case, it would be nice to patch this at some point.  I'll see if I have time to make a pull request once I get farther into development.

**Comment by DXCanas** [comment]
Updating the URL structure for SDK downloads still hasn't been take care of as far as I can tell.
