### ISSUE TITLE
websocket-client "SSL not available."

### ISSUE THREAD

**Issue by mangodan2003** [kivy/buildozer#473]
Service fails with the below when try to use wss://

`I/python  ( 6997):  Traceback (most recent call last):
I/python  ( 6997):    File "/home/dan/workspace/android-projects/osc_test/.buildozer/android/app/service/main.py", line 7, in <module>
I/python  ( 6997):    File "/home/dan/workspace/android-projects/osc_test/.buildozer/android/app/_applibs/websocket/_core.py", line 487, in create_connection
I/python  ( 6997):    File "/home/dan/workspace/android-projects/osc_test/.buildozer/android/app/_applibs/websocket/_core.py", line 211, in connect
I/python  ( 6997):    File "/home/dan/workspace/android-projects/osc_test/.buildozer/android/app/_applibs/websocket/_http.py", line 79, in connect
I/python  ( 6997):  websocket._exceptions.WebSocketException: SSL not available.
I/python  ( 6997): Python for android ended.
`
requirements = kivy, openssl, pyopenssl, websocket-client

**Comment by tito** [comment]
Clean and rebuild everything. If you added openssl and just build, maybe python didn't rebuild. Openssl must be build before python.
