### ISSUE TITLE
ImportError: No module named parse

### ISSUE THREAD

**Issue by sam3241** [kivy/buildozer#478]
Python 3.5.3
shows this error on android apk.
I/python  (  681):    File "/home/kivy/Desktop/Application/.buildozer/android/app/feed.py", line 2, in <module>
I/python  (  681):  ImportError: No module named parse
I/python  (  681): Python for android ended.
V/SDL     (  681): onPause()
V/SDL     (  681): nativePause()

**Comment by tito** [comment]
Yep, maybe your app is running with python 2.7 on android. Not an issue with buildozer.
