### ISSUE TITLE
dlopen failed: python2.7/site-packages/grpc/_cython/cygrpc.so not 32-bit: 2

### ISSUE THREAD

**Issue by gbdantoni** [kivy/buildozer#479]
I'm trying to build a python app for Android that uses grpc. I'm using Buildozer 0.32 with the new toolchain on Ubuntu 16.04.2.  The build succeeds and it produces an APK but when I try to launch it on an Android tablet I'm getting the following output from logcat.  My requirements statement includes kivy, grpcio, hostpython2, enum

```I/python  (29857): Run user program, change dir and execute entrypoint
I/python  (29857): Traceback (most recent call last):
I/python  (29857):   File "/media/newDrive/gaitan/PythonProjects/hwclient/.buildozer/android/app/main.py", line 34, in <module>
I/python  (29857):   File "/media/newDrive/gaitan/PythonProjects/hwclient/.buildozer/android/platform/build/dists/hwclient/private/lib/python2.7/site-packages/grpc/__init__.py", line 37, in <module>
I/python  (29857): ImportError: dlopen failed: "/data/data/ddw_gd.com.hwclient/files/app/lib/python2.7/site-packages/grpc/_cython/cygrpc.so" not 32-bit: 2
I/python  (29857): Python for android ended.
```

**Comment by tito** [comment]
Hi, this is not related to buildozer itself, but python-for-android at least. I'm moving the issue.

**Comment by tito** [comment]
Issue moved to [kivy/python-for-android #1052](https://github.com/kivy/python-for-android/issues/1052) via [**ZenHub**](https://www.zenhub.com/)
