### ISSUE TITLE
android-new landscape error on restart

### ISSUE THREAD

**Issue by babarehner** [kivy/buildozer#482]
Built Kivy app using landscape mode only. On restart (resume) when compiled with android_new app does not always go back to landscape mode. App usually goes to portrait mode and only when tapped goes to landscape mode. When compiled with 'android' always goes back to landscape mode on restart (resume). Spash icon also larger when compiled with 'android_new'. Buildozer spec file below- 
[buildozer.spec.txt](https://github.com/kivy/buildozer/files/865014/buildozer.spec.txt)

**Comment by inclement** [comment]
Closing as stale, I think this is working in p4a master, please open an issue there if not.
