### ISSUE TITLE
android.arch ignored

### ISSUE THREAD

**Issue by martirius** [kivy/buildozer#488]
I want to build an app for android with arm64-v8a architecture. 
But i have two problems: 1) The parameter android.arch is not present if i run buildozer init in my project directory. 2) if i add the line in buildozer.spec, buildozer completely ignore it and always builds with armeabi-v7a architecture. How to resolve?

**Comment by inclement** [comment]
It sounds like you are using the latest buildozer stable release, but I don't think this option is present there. For now, you'll need to use buildozer from the github master branch, where the option is present and seems to be accessed properly.

**Comment by inclement** [comment]
Also, arm64-v8a may work, but has been tested very little if at all. If you find problems with it, issue reports are welcome at https://github.com/kivy/python-for-android .

**Comment by martirius** [comment]
Thanks for the reply, i will try :)
