### ISSUE TITLE
android_new target hardcodes python2 support for p4a

### ISSUE THREAD

**Issue by mixmastamyk** [kivy/buildozer#491]
I'm using Python3.5 to build my app, and buildozer runs under it, but it runs p4a as:         
 
    python -m pythonforandroid.toolchain ...

This hardcodes it to run under python2, meaning I have to install a lot of prerequisites there.  Would prefer not to.

I've found this string in: `buildozer/targets/android_new.py`, at line 22.

**Comment by inclement** [comment]
This is fixed in buildozer master.
