### ISSUE TITLE
Buildozer APK Cannot LAUNCH

### ISSUE THREAD

**Issue by wilsonreuben** [kivy/buildozer#493]
After succesful APK build, the file won't launch on Android Devices.

Below is my log(file too large cannot paste here)

https://raw.githubusercontent.com/CoreElites/nairamanager-frontend/master/buildozer_log

and when i press ctrl+c, i get this:

^CTraceback (most recent call last):
  File "/usr/local/bin/buildozer", line 11, in <module>
    load_entry_point('buildozer==0.33.dev0', 'console_scripts', 'buildozer')()
  File "/usr/local/lib/python2.7/dist-packages/buildozer-0.33.dev0-py2.7.egg/buildozer/scripts/client.py", line 13, in main
    Buildozer().run_command(sys.argv[1:])
  File "/usr/local/lib/python2.7/dist-packages/buildozer-0.33.dev0-py2.7.egg/buildozer/__init__.py", line 1026, in run_command
    self.target.run_commands(args)
  File "/usr/local/lib/python2.7/dist-packages/buildozer-0.33.dev0-py2.7.egg/buildozer/target.py", line 91, in run_commands
    func(args)
  File "/usr/local/lib/python2.7/dist-packages/buildozer-0.33.dev0-py2.7.egg/buildozer/targets/android.py", line 936, in cmd_logcat
    show_output=True)
  File "/usr/local/lib/python2.7/dist-packages/buildozer-0.33.dev0-py2.7.egg/buildozer/__init__.py", line 302, in cmd
    readx = select.select([fd_stdout, fd_stderr], [], [])[0]
KeyboardInterrupt

Please how to fix this?

**Comment by inclement** [comment]
```
05-11 13:50:59.891  4582  4652 I python  :  Traceback (most recent call last):
05-11 13:50:59.891  4582  4652 I python  :    File "/home/wilsonreuben/Documents/nm_kivy_build/.buildozer/android/app/main.py", line 30, in <module>
05-11 13:50:59.891  4582  4652 I python  :  ImportError: No module named androidtabs
```

It looks like you try to import something that isn't present on the device.

**Comment by wilsonreuben** [comment]
I never noticed that.
Let me fix it and see how it goes

**Comment by wilsonreuben** [comment]
Didn't work.
I once used androidtabs before now. I didn't use it again afterwards and no part of the application is using any class from the garden package.
I commented it out, still getting errors.

**Comment by inclement** [comment]
```
05-11 17:36:20.081 21325 21432 I python  :  Traceback (most recent call last):
05-11 17:36:20.081 21325 21432 I python  :    File "/home/wilsonreuben/Documents/nm_kivy_build/.buildozer/android/app/main.py", line 31, in <module>
05-11 17:36:20.081 21325 21432 I python  :  ImportError: No module named recycleview
```

It *did* work, you fixed the bug, it just wasn't the only bug.

As above, you're also importing recycleview, which also isn't present.

To find these tracebacks, look at the log lines containing `python`.

**Comment by wilsonreuben** [comment]
recycleview comes bundled with kivy 1.9.2dev, how can this be?

----------------------------------------------------------------------------------------------------------------------------------------------
let me check

**Comment by wilsonreuben** [comment]
# Fixed

This is how:

i ran "buildozer -v android debug deploy run logcat > my_log.txt" without quote.

where "my_log.txt" is the file name to save the build logcat, the file will appear in your current directory.

Now for each crash i got, i opened the corresponding logcat file in a text editor and searched for 'traceback'(to find the errors) using the find function in the text editor. I did this until i fixed all bugs.

Thanks inclement
