### ISSUE TITLE
Need Help Fatal signal 11 (SIGSEGV) at 0x00000000 (code=1), thread 4579 (SDLThread)

### ISSUE THREAD

**Issue by Macatuz** [kivy/buildozer#495]
I am trying to get just one apk well done, just one. now look at this.
This is a normal apk. an small program.
Bugs: I/python ( 4561): Run user program, change dir and execute entrypoint
I/python ( 4561): [WARNING] [Config ] Older configuration version detected (0 instead of 19)
I/python ( 4561): [WARNING] [Config ] Upgrading configuration in progress.
I/python ( 4561): [INFO ] [Logger ] Record log in /data/data/org.test.codicooking/files/app/.kivy/logs/kivy_17-05-12_0.txt
I/python ( 4561): [INFO ] [Kivy ] v1.10.0
I/python ( 4561): [INFO ] [Python ] v2.7.2 (default, May 11 2017, 23:45:28)
I/python ( 4561): [GCC 4.8]
F/libc ( 4561): Fatal signal 11 (SIGSEGV) at 0x00000000 (code=1), thread 4579 (SDLThread)
I/DEBUG ( 158): *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
I/DEBUG ( 158): Build fingerprint: 'Android/samsung/samsung:4.4.2/KOT49H/3.8.117.0504:userdebug/test-keys'
I/DEBUG ( 158): Revision: '0'
I/DEBUG ( 158): pid: 4561, tid: 4579, name: SDLThread >>> org.test.codicooking <<<
I/DEBUG ( 158): signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 00000000
I/DEBUG ( 158): eax 00000000 ebx b7707fdc ecx 0000002b edx b76e2004
I/DEBUG ( 158): esi 00000000 edi b77027bc
I/DEBUG ( 158): xcs 00000073 xds 0000007b xes 0000007b xfs 00000043 xss 0000007b
I/DEBUG ( 158): eip b76e7bdb ebp b7708020 esp 7ee80610 flags 00210246
I/DEBUG ( 158):
I/DEBUG ( 158): backtrace:
I/DEBUG ( 158): #0 pc 00001bdb /system/bin/linker
I/DEBUG ( 158): #1 pc 001ac3af /system/lib/libhoudini.so
I/DEBUG ( 158): #2 pc ffffffff 
I/DEBUG ( 158):
I/DEBUG ( 158): stack:
I/DEBUG ( 158): 7ee805d0 b76e2000
I/DEBUG ( 158): 7ee805d4 00000f8c
I/DEBUG ( 158): 7ee805d8 00000001
I/DEBUG ( 158): 7ee805dc 7ee8064c [stack:4579]
I/DEBUG ( 158): 7ee805e0 85f5ce85 /system/lib/libhoudini.so
I/DEBUG ( 158): 7ee805e4 1a115030 [stack:4578]
I/DEBUG ( 158): 7ee805e8 00004000
I/DEBUG ( 158): 7ee805ec 00004000
I/DEBUG ( 158): 7ee805f0 1a115030 [stack:4578]
I/DEBUG ( 158): 7ee805f4 00000473
I/DEBUG ( 158): 7ee805f8 b76ed8c9 /system/bin/linker
I/DEBUG ( 158): 7ee805fc b7707fdc /system/bin/linker
I/DEBUG ( 158): 7ee80600 00000000
I/DEBUG ( 158): 7ee80604 00000000
I/DEBUG ( 158): 7ee80608 b7708020 /system/bin/linker
I/DEBUG ( 158): 7ee8060c b76e7b91 /system/bin/linker
I/DEBUG ( 158): #0 7ee80610 00000000
I/DEBUG ( 158): 7ee80614 00000000
I/DEBUG ( 158): 7ee80618 15204398 /data/data/org.test.codicooking/files/app/lib/python2.7/lib-dynload/_ctypes.so
I/DEBUG ( 158): 7ee8061c 7ee8063c [stack:4579]
I/DEBUG ( 158): 7ee80620 860381f1 /system/lib/libhoudini.so
I/DEBUG ( 158): 7ee80624 86237b6c
I/DEBUG ( 158): 7ee80628 15204398 /data/data/org.test.codicooking/files/app/lib/python2.7/lib-dynload/_ctypes.so
I/DEBUG ( 158): 7ee8062c 00000000
I/DEBUG ( 158): 7ee80630 00000001
I/DEBUG ( 158): 7ee80634 00000001
I/DEBUG ( 158): 7ee80638 00000000
I/DEBUG ( 158): 7ee8063c 7ee80748 [stack:4579]
I/DEBUG ( 158): 7ee80640 00000000
I/DEBUG ( 158): 7ee80644 00000000
I/DEBUG ( 158): 7ee80648 7ee80678 [stack:4579]
I/DEBUG ( 158): 7ee8064c 860563b0 /system/lib/libhoudini.so
I/DEBUG ( 158): #1 7ee80650 00000000
I/DEBUG ( 158): 7ee80654 00000000
I/DEBUG ( 158): 7ee80658 8618dc84 /system/lib/libhoudini.so
I/DEBUG ( 158): 7ee8065c 7ee8068c [stack:4579]
I/DEBUG ( 158): 7ee80660 1a1151c0 [stack:4578]
I/DEBUG ( 158): 7ee80664 86237b6c
I/DEBUG ( 158): 7ee80668 00000002
I/DEBUG ( 158): 7ee8066c 7ee8068c [stack:4579]
I/DEBUG ( 158): 7ee80670 00000000
I/DEBUG ( 158): 7ee80674 1a115030 [stack:4578]
I/DEBUG ( 158): 7ee80678 7ee80738 [stack:4579]
I/DEBUG ( 158): 7ee8067c 860486e8 /system/lib/libhoudini.so
I/DEBUG ( 158): 7ee80680 00000000
I/DEBUG ( 158): 7ee80684 00000000
I/DEBUG ( 158): 7ee80688 00000004
I/DEBUG ( 158): 7ee8068c 7ee806fc [stack:4579]
Expected Results
Work.
This is Codi Cook Timer.

**Comment by tito** [comment]
Hi,

This is not related to Buildozer itself. It's about SDL2 not working on Android with your x86 processor (we support officially only ARM). Check the python-for-android project instead about it.

Good luck!
