### ISSUE TITLE
Failed to build APK with python 3.6 : [sh.CommandNotFound: python3.5]

### ISSUE THREAD

**Issue by lutre69** [kivy/buildozer#504]
I've been willing to make an app written on python3.6 using kivy.
Hello,
I'm trying to compile an apk for android with python 3.6 but i'm have some troubles for quite some time now. I made a test with a dummy "Hello World" app but i had no chance with that, i get stuck on the same Error message : [sh.CommandNotFound: python3.5]
I reinstalled my manjaro(up to date, with xcfe desk) and only installed kivy 1.10 and cython .25.
Python 3.6 comes pre installed with manjaro.
I downloaded buildozer dev version from the clone url on git
I downloaded and unpacked Crystax 10.3.2. (last version)
I modified the spec file as specified on the README.rst
Same error again. 
Here is the buildozer.spec file : https://pastebin.com/UPLdwUsn
Here is the log : https://pastebin.com/ST0DU7PC

Any idea what is happening? It looks like the receipe for p4a is trying to look for python3.5 and only finds python3.6 ...

A little help would be appreciated.

EDIT : 
I tried to build the same APK on the same computer with ubuntu and it worked fine. I think it has to do with the fact that Manjaro is building the APK trough python 3.6 which is the native version of python on this distro. So there is definitely a bug with either the building of buildozer under ArchLinux (by the way, i have installed the missing packages and 32bit dependencies) or the way buildozer is coded that doesn't go well with python 3.6.

At least I know that i can build the APK with Ubuntu, not very fond of this distro though...

Is there a way to force buildozer to build the APK using python 2.7? I think that might do the trick...

EDIT :
I tired to install buildozer with python 2.7 _sudo pip2 install buildozer_
Still not working...
 **File "/usr/lib/python2.7/site-packages/sh.py", line 1202, in __init__
    raise CommandNotFound(path)
sh.CommandNotFound: python3.5** 
Looks like no matter what, buildozer is trying to look for Python 3.5...
I don't know what to do...

**Comment by inclement** [comment]
This was a python-for-android issue, and is already fixed in python-for-android master.
