### ISSUE TITLE
buildozer still download ndk from wrong path

### ISSUE THREAD

**Issue by mahomahomaho** [kivy/buildozer#506]
related to #474 , buildozer still downloads NDK from wrong path

```
 # Android NDK is missing, downloading
 # Downloading http://dl.google.com/android/ndk/android-ndk-r13b-linux-x86_64.bin
```

which leads to corrupted .bin file

**Comment by KeyWeeUsr** [comment]
Works just fine with the default NDK version.

**Comment by mahomahomaho** [comment]
But doesn't when using non-default. according to wiki,  p4a works ok with 13b. Buildozer should download it properly IMHO.
