### ISSUE TITLE
Possible FileNotFoundError issue with script due to dealing with spaces in folder/file name?

### ISSUE THREAD

**Issue by simon2x** [kivy/buildozer#510]
Possibly related to: https://github.com/kivy/buildozer/issues/306

I tried to build from a source folder which includes spaces e.g. "tennis game"

Which raised the following error:

```
  File "/home/user/buildozer/buildozer/targets/android.py", line 852, in _update_libraries_references
    with io.open(project_fn, 'w', encoding='utf-8') as fd:
  FileNotFoundError: [Errno 2] No such file or directory:
```

              

Having renamed the folder + removed the spaces from the name, I was able to successfully package an apk. :)

So could it be possible, there is an issue with pa_dir? 

```  project_fn = join(dist_dir, 'project.properties') ```

which leads to

```self.pa_dir = pa_dir = join(self.buildozer.platform_dir, self.p4a_directory)```

**Comment by tshirtman** [comment]
I suspect the error would be there
https://github.com/kivy/buildozer/blob/master/buildozer/targets/android.py#L504

because if there is a space in this path, it needs to be escaped for the shell command, or maybe just put the path between quotes, like 

    '"{}"').format(source, self.p4a_directory),
