### ISSUE TITLE
[features] Snapcraft implementation

### ISSUE THREAD

**Issue by Tungsteno74** [kivy/buildozer#514]
Hi guys. I'd like to know if someone is already implementing the Ubuntu Store (Snapcraft) packaging tool inside Buildozer or if someone is going to implement it shortly.

I said that because, I would like to contribute to the project as I'm using it for some projects and i think that include it in Buildozer be useful.

Thanks

**Comment by inclement** [comment]
I'm not aware of anyone looking at this. As far as I know, a PR to add this capability to buildozer would be very welcome!

**Comment by Tungsteno74** [comment]
ok, thanks @inclement . I'm working on the first usable version of snapcraft into a separate buildozer branch. When ready, I will create a PR to share information with you.
