### ISSUE TITLE
apk way too large - 800mb

### ISSUE THREAD

**Issue by lukftw** [kivy/buildozer#520]
I have created an apk which contains some basic sockets(under 100 lines of code) and only importing sockets and the apk generated using 
`buildozer android debug` and following the tutorial from README docs was over 800mb. What did I do wrong?

Debian Stretch
Python 3.5
Kivy 1.10

**Comment by KeyWeeUsr** [comment]
Please share the code and buildozer.spec. I really wonder how did you package the APK and what's its content.

**Comment by inclement** [comment]
This is almost always because you have accidentally indluded something you didn't mean to, such as the previous version of the apk. You can see what's inside by extracting the apk (it is a zip file), locating the file `private.mp3` inside it (I think it's in the `assets` folder) and extracting it - that file is a .tar.gz file.

**Comment by lukftw** [comment]
[buildozer.spec.txt](https://github.com/kivy/buildozer/files/1116298/buildozer.spec.txt)

**Comment by KeyWeeUsr** [comment]
Judging from

```
# (str) Source code where the main.py live
source.dir = .

# (list) Source files to include (let empty to include all the files)
source.include_exts = py,png,jpg,kv,atlas
```

you must have something in the folder with `buildozer.spec`, a lot of images perhaps? A `Downloads` folder? Also, the `private.mp3` content would be good to see too.

**Comment by lukftw** [comment]
I have found the problem, the files were in a folder which contained crystalx files so I've moved the files in another folder and set the path to it, now it has 18 mb, but the app is only displaying a black screen on my phone, any ideeas?

**Comment by inclement** [comment]
You can debug this with [adb logcat](https://kivy.org/docs/guide/android.html#debugging-your-application-on-the-android-platform).
