### ISSUE TITLE
Kivy and Beautifulsoup with Buildozer fail on Python 3.

### ISSUE THREAD

**Issue by fomalhaut88** [kivy/buildozer#529]
I am trying to build a kivy app written in Python 3 having beautifulsoup library. I have followed these steps:

1. I installed buildozer for Python 3 according to the doc: [https://pypi.python.org/pypi/buildozer](https://pypi.python.org/pypi/buildozer)
2. I downloaded and unpacked crystax
3. I modifyed requirements and android.ndk_path in buildozer.spec:
    requirements = python3crystax,beautifulsoup4,kivy==master
    android.ndk_path = ~/Programs/crystax-ndk-10.3.2
4. I ran buildozer:
    buildozer android debug deploy

Everything was built successfully. But when I run the app on my mobile it falls with error:

I/python  (15014):      'You are trying to run the Python 2 version of Beautiful Soup under Python 3. This will not work.'<>'You need to convert the code, either by installing it (`python setup.py install`) or by running 2to3 (`2to3 -w bs4`).'
I/python  (15014):                                                                                                         ^
I/python  (15014):  SyntaxError: invalid syntax

It looks like buildozer installed beautifulsoup for Python 2 instead. But I specified nothing about Python 2 when I was installing and configuring buildozer. Also I had looked at .buildozer directory and found the directory venv that contains Python 2.7 only. It seems to be weird, because I have done everything to avoid Python 2.

How can I make my app build and work correctly?

Thanks for advance.

**Comment by mark-marinas** [comment]
I am not sure if this has already been answered, but here's what I have done to fix the problem.
1. go to your app directory.
2. there is a hidden folder, .buildozer. cd into that. 
   cd .buildozer/android/platform/python-for-android-master/pythonforandroid
3. look for all those files (you can just use grep) that has 2.7 in it, and change it to your python version (in my case its 3.5).
4. go back to your app dir, do a buildozer android clean. 
5. build your app as you previously did.

**Comment by mark-marinas** [comment]
I am not sure if you already found the anwer, but here's what i did to make it work.
1. go to your app folder, then cd to .buildozer/android/platform/python-for-anroid-master/pythonforanrdoid
2. look for the files with 2.7, (you can just use grep), and replace 2.7 with yoiur python version (3.5 in mycase).
3. go back to your app folder, do a buildozer android clean
4. build as you normally would.

**Comment by inclement** [comment]
Closing as stale, python3 support has changed a lot since then. Please make a new issue for any issues on master.
