### ISSUE TITLE
Error: Aidl cannot be executed

### ISSUE THREAD

**Issue by Enteleform** [kivy/buildozer#532]
```
System:
    Windows 10 x64 + Bash on Ubuntu 16.04.2 LTS
    Python 3.5.2
    Buildozer0.33
```

Followed the instructions @ [buildozer.readthedocs.org/en/latest/installation.html](http://buildozer.readthedocs.org/en/latest/installation.html)
Ran `android update sdk --no-ui --all`
Tried running `buildozer android deploy` and got the following error:

```
# Check that aidl can be executed
# Search for Aidl
# Run '/home/fico/.buildozer/android/platform/android-sdk-23/build-tools/23.0.1/aidl'
# Cwd None
# Aidl cannot be executed
# 
# You might have missed to install 32bits libs
# Check http://buildozer.readthedocs.org/en/latest/installation.html
# 
# Check configuration tokens
 ```

### [buildozer.spec](https://gist.github.com/Enteleform/348c4ae4dd465aaa87d232ea7925d0dc#file-buildozer-spec)

**Comment by vshantam** [comment]
you can not run buildozer as a root .i was having the same problem then i created a non root user and run buildozer application an i worked perfectly fine .if you still faces the same problem try upgrading the application .

**Comment by KhishorekumarBS** [comment]
I got the same error and ran these commands,

- sudo pip install --upgrade cython==0.21
- sudo dpkg --add-architecture i386
- sudo apt-get update
- sudo apt-get install build-essential ccache git libncurses5:i386 libstdc++6:i386 libgtk2.0-0:i386 libpangox-1.0-0:i386 libpangoxft-1.0-0:i386 libidn11:i386 python2.7 python2.7-dev openjdk-8-jdk unzip zlib1g-dev zlib1g:i386

But still I'm getting the **same** error.
Please help

**Comment by oriolpiera** [comment]
I got the same error with Android SDK Build-tools 19.1. I updated to version 27.0.3, and no 32bits libs required.

So, update de Android SDK Built-tools and the problem will be solved.

**Comment by uxmatthew** [comment]
Getting this same thing. Tried several versions of sdk and of build tools. Still not working.

**Comment by cplager** [comment]
I, too, have the same problem and am running Ubuntu on Windows 10.

[log.txt](https://github.com/kivy/buildozer/files/1905330/log.txt)


[buildozer.spec.txt](https://github.com/kivy/buildozer/files/1905331/buildozer.spec.txt)

**Comment by ImtiyazKhan117** [comment]
i am dealing same problem today before now everything was fine with my buildozer :(
but now i  refactor my project and now its working i simply copy past my project file into another folder
run buildozer android clean 
and then
buildozer android debug deploy 
its working for me

**Comment by fl118543** [comment]
I fixed the aidl problem by installing the 32bits version of the C++ library.
\# sudo apt-get install lib32stdc++6
Maybe you could try it.

Hope this help,
Francois

**Comment by inclement** [comment]
Closing as stale, please reopen if this is still an issue.

**Comment by SCORPIA-oss** [comment]
sudo apt-get install lib32stdc++6 not working!

**Comment by tshirtman** [comment]
do you have all the dependencies documented there?
https://buildozer.readthedocs.io/en/latest/installation.html#android-on-ubuntu-18-04-64bit

i'm pretty sure it's about everything that is needed, if not that list needs to be completed.
