### ISSUE TITLE
Remove app permissions added by default

### ISSUE THREAD

**Issue by aminrasekh** [kivy/buildozer#534]
I have created an app and published on Play Store.

I had not set any app permissions anywhere. But when I want to install the app via play store, it requires the following permission:

> Photos/Media/Files
>        - read the contents of your USB storage
>        - modify or delete the contents of your USB storage

It this added by buildozer by default? If yes, how can this be removed. Or even better, this default is just reconsidered. 

Here is the spec file:
[buildozer.txt](https://github.com/kivy/buildozer/files/1167367/buildozer.txt)

**Comment by inclement** [comment]
Yes, this is added by default. The only way to remove it is to edit the python-for-android source, as it's currently hardcoded in the AndroidManifest.xml file.

The reason it's there is that it used to be required by Kivy, but it hasn't been essential for some time. It's possible that Kivy assumes it's available and will fail if it can't write there, but that just needs a small fix in Kivy itself. I've been meaning to look at this for a while, but it looks like there wasn't a python-for-android issue open about it, so I've made one at https://github.com/kivy/python-for-android/issues/1081 .

I'll close this issue as it's a python-for-android issue, but thanks for raising it.

**Comment by aminrasekh** [comment]
Thanks @inclement for the quick response and opening the new issue there in p4a.

Hopefully, this requirement is made optional.
