### ISSUE TITLE
Requirements: Requests, Ssl

### ISSUE THREAD

**Issue by wsdt** [kivy/buildozer#539]
I need the package requests and Openssl/Pyopenssl or similar for my project. 

But unfortunately i cannot use Python3crystax because 'requests' uses python2. So i have to use python2 in the buildozer-spec-file. 

After adding openssl/pyopenssl i need to import cryptography in the requirements, because it depends on that. But cryptography cannot be added while compiling. I get several errors like 'Unknown url type 'https'' or 'Cannot unpack tar.gz "tar" not an archive' 

I tried everything so I assume that there must be a problem with buildozer. 

Thank you.

**Comment by SamuelHaidu** [comment]
I use requests without cryptography in requirements.
You can try: requests, pyasn1, ndg_httpsclient, certifi
the libcrypto.so and libssl.so will be added

**Comment by Fisk24** [comment]
I'm also having this issue when try adding your requirements the build fails

`[INFO]:    No existing dists meet the given requirements!
[INFO]:    No dist exists that meets your requirements, so one will be built.
[ERROR]:   Didn't find any valid dependency graphs.
[ERROR]:   This means that some of your requirements pull in conflicting dependencies.
[ERROR]:   Exiting.
# Command failed: /usr/bin/python -m pythonforandroid.toolchain create --dist_name=lgt --bootstrap=sdl2 --requirements=kivy,python3crystax,requests,pyasn1,ndg_httpsclient,certifi --arch armeabi-v7a --copy-libs --color=always --storage-dir=/home/fisk/Projects/Python/ram_test/.buildozer/android/platform/build
# 
# Buildozer failed to execute the last command
# The error might be hidden in the log above this error
# Please read the full log, and search for it before
# raising an issue with buildozer itself.
# In case of a bug report, please add a full log with log_level = 2
`

**Comment by inclement** [comment]
Closing as stale, requests and openssl are currently working fine in p4a.
