### ISSUE TITLE
App Crashes

### ISSUE THREAD

**Issue by wilsonreuben** [kivy/buildozer#541]
I don't know if this is a buildozer issue.

Successfully built my app with buildozer
The app seems to be running only on android lollipop upwards. Crashes with kitkat downwards.

I use the following android settings:

# (int) Android API to use
android.api = 19

# (int) Minimum API required
android.minapi = 9

# (int) Android SDK version to use
android.sdk = 20

# (str) Android NDK version to use
android.ndk = 9c

**Comment by FeralBytes** [comment]
Where is the crash log from ADB?

**Comment by inclement** [comment]
Closing as lacking details, please post a full report on the python-for-android repository if still occurring.
