### ISSUE TITLE
This indian trash not work

### ISSUE THREAD

**Issue by mraksoll** [kivy/buildozer#542]
/root/.buildozer/android/platform/android-sdk-20/tools/ant/build.xml:377: SDK Platform Tools component is missing. Please install it with the SDK Manager (tools/android)

**Comment by mraksoll** [comment]
WARNING]: ERROR: /root/.buildozer/android/platform/apache-ant-1.9.4/bin/ant failed!
# Command failed: /usr/bin/python -m pythonforandroid.toolchain apk --debug --bootstrap=sdl2 --dist_name Electrum_LTC --name Electrum-LTC --version 2.9.3 --package org.electrum_ltc.electrum_ltc --android_api 19 --sdk 19 --minsdk 9 --private /root/electrum-ltc/.buildozer/android/app --permission INTERNET --permission WRITE_EXTERNAL_STORAGE --permission READ_EXTERNAL_STORAGE --presplash /root/electrum-ltc/./icons/electrum_presplash.png --icon /root/electrum-ltc/./icons/electrum_launcher.png --orientation portrait --window --intent-filters /root/electrum-ltc/gui/kivy/tools/bitcoin_intent.xml --copy-libs --arch armeabi-v7a --color=always --storage-dir=/root/electrum-ltc/.buildozer/android/platform/build
# 
# Buildozer failed to execute the last command
# The error might be hidden in the log above this error
# Please read the full log, and search for it before
# raising an issue with buildozer itself.
# In case of a bug report, please add a full log with log_level = 2

**Comment by inclement** [comment]
Closing for inappropriate issue name.

**Comment by mraksoll** [comment]
Ok

**Comment by mraksoll** [comment]
You only can close ticket's , primitive indian monkety's. Clear earth from some trash nation

**Comment by inclement** [comment]
I have now also blocked this user.
