### ISSUE TITLE
buildozer android debug deploy run ERROR

### ISSUE THREAD

**Issue by ovaaq** [kivy/buildozer#550]
[INFO]:    Will compile for the following archs: armeabi-v7a
[INFO]:    Found Android API target in $ANDROIDAPI
[INFO]:    Available Android APIs are ()
[WARNING]: Requested API target 19 is not available, install it with the SDK android tool.
[WARNING]: Exiting.

# Command failed: /usr/bin/python2.7 -m pythonforandroid.toolchain create --dist_name=myapp --bootstrap=sdl2 --requirements=kivy,numpy --arch armeabi-v7a --copy-libs --color=always --storage-dir=/home/ovaaq/Desktop/tunnistus/.buildozer/android/platform/build

**Comment by FeralBytes** [comment]
You need to install the API version that you want to use.... you currently have none installed. This is not a bug.
Please close.

**Comment by inclement** [comment]
Closing as stale, this should currently work properly.
