### ISSUE TITLE
 Websocket error: SSL not available.

### ISSUE THREAD

**Issue by brentpicasso** [kivy/buildozer#552]
09-02 09:12:04.037 10328 10719 I python  : [ERROR  ] [MyApp] Websocket error: SSL not available.
09-02 09:12:04.037 10328 10719 I python  : [INFO   ] [MyApp] Websocket closed

Getting this error when attempting to open a secure websocket ('wss://') using websocket-client. 

Still happens after a `buildozer android clean` and after deleting the .buildozer directory. 

buildozer requirements:

requirements = kivy==1.10.0, sqlite3, openssl, pyopenssl, pygments, websocket-client

**Comment by brentpicasso** [comment]
still getting it with the latest python-for-android: `buildozer android update`

Thinking maybe this is a py4a issue?

**Comment by brentpicasso** [comment]
Digging further: 

I disabled the SSL check on websocket-client and found a lower level exception:

09-02 10:00:43.215 13478 13511 I python  : [ERROR  ] [MyApp] Websocket error: _ssl.c:331: No root certificates specified for verification of other-side certificates.

**Comment by inclement** [comment]
This would indeed be a python-for-android issue.

Does openssl work in general for you, e.g. downloading an https:// site?

**Comment by brentpicasso** [comment]
Thank you for the quick reply.  I'm successfully using https with ururllib2 , so it seems ssl is working. 

I'll open an issue in python-for-android.

**Comment by brentpicasso** [comment]
https://github.com/kivy/python-for-android/issues/1107
