### ISSUE TITLE
python3 import networkx needs lib2to3 but cannot be imported

### ISSUE THREAD

**Issue by chemelnucfin** [kivy/buildozer#554]
I tried a couple of ways to import networkx into kivy, but I'm still getting errors and I'm not sure what is the best solution to try going forward.  Python3 has no problem importing networkx, lib2to3, lib2to3.pgen2, and lib2to3.pgen2.parse.  Should I try making the recipe work or is there a way to copy into site-packages, or something else?  Help appreciated, thanks in advance.

For reference, this is the directory if I import numpy in python3
`$HOME/.local/lib/python3.5/site-packages/numpy/__pycache__/__init__.cpython-35.pyc matches $HOME/.local/lib/python3.5/site-packages/numpy/__init__.py`
`code object from '$home/.local/lib/python3.5/site-packages/numpy/__pycache__/__init__.cpython-35.pyc'`

and this is the directory if I import lib2to3
`# /usr/lib/python3.5/lib2to3/__pycache__/__init__.cpython-35.pyc matches /usr/lib/python3.5/lib2to3/__init__.py`
`# code object from '/usr/lib/python3.5/lib2to3/__pycache__/__init__.cpython-35.pyc'`

**Requiring just networkx**
If I just set requirements = kivy, python3crystax, networkx, logcat shows:

`09-02 13:16:13.211 11466 11928 I python  :  Traceback (most recent call last):`
`09-02 13:16:13.212 11466 11928 I python  :    File "main.py", line 1, in <module>`
`09-02 13:16:13.213 11466 11928 I python  :      import program`
`09-02 13:16:13.213 11466 11928 I python  :    File "./program.py", line 16, in <module>`
`09-02 13:16:13.213 11466 11928 I python  :      import networkx as nx`
`09-02 13:16:13.214 11466 11928 I python  :    File "/data/user/0/org.test.myapp/files/app/crystax_python/site-packages/networkx/__init__.py", line 87, in <module>`
`09-02 13:16:13.214 11466 11928 I python  :      import networkx.readwrite`
`09-02 13:16:13.215 11466 11928 I python  :    File "/data/user/0/org.test.myapp/files/app/crystax_python/site-packages/networkx/readwrite/__init__.py", line 14, in <module>`
`09-02 13:16:13.215 11466 11928 I python  :      from networkx.readwrite.gml import *`
`09-02 13:16:13.215 11466 11928 I python  :    File "/data/user/0/org.test.myapp/files/app/crystax_python/site-packages/networkx/readwrite/gml.py", line 44, in <module>`
`09-02 13:16:13.216 11466 11928 I python  :      from lib2to3.pgen2.parse import ParseError`
`09-02 13:16:13.216 11466 11928 I python  :  ImportError: No module named 'lib2to3'`
`09-02 13:16:13.336 11466 11928 I python  : Python for android ended.`

**If I add lib2to3 and try setting recipes, shell shows:**
`[INFO]:    -> directory context $HOME/projects/program/.buildozer/android/platform/build/build/other_builds/lib2to3-python3crystax/armeabi-v7a/lib2to3`
`[INFO]:    -> running python3.5 setup.py install -O2...(and 114 more)`
`Exception in thread background thread for pid 9353:`
`Traceback (most recent call last):`
`  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner`
`    self.run()`
`  File "/usr/lib/python3.5/threading.py", line 862, in run`
`    self._target(*self._args, **self._kwargs)`
`  File "$HOME/.local/lib/python3.5/site-packages/sh.py", line 1540, in wrap`
`    fn(*args, **kwargs)`
`  File "$HOME/.local/lib/python3.5/site-packages/sh.py", line 2459, in background_thread`
`    handle_exit_code(exit_code)`
`  File "$HOME/.local/lib/python3.5/site-packages/sh.py", line 2157, in fn`
`    return self.command.handle_command_exit_code(exit_code)`
`  File "$HOME/.local/lib/python3.5/site-packages/sh.py", line 815, in handle_command_exit_code`
`    raise exc`
`sh.ErrorReturnCode_2: `

`  RAN: /usr/bin/python3.5 setup.py install -O2 --root=$HOME/projects/program/.buildozer/android/platform/build/build/python-installs/myapp --install-lib=.`

`  STDOUT:`
`/usr/bin/python3.5: can't open file 'setup.py': [Errno 2] No such file or directory`

`  STDERR:`
`Traceback (most recent call last):`
`  File "/usr/lib/python3.5/runpy.py", line 184, in _run_module_as_main`
`    "__main__", mod_spec)`
`  File "/usr/lib/python3.5/runpy.py", line 85, in _run_code`
`    exec(code, run_globals)`
`  File "$HOME/projects/program/.buildozer/android/platform/python-for-android-master/pythonforandroid/toolchain.py", line 905, in <module>`
`    main()`
`  File "$HOME/projects/program/.buildozer/android/platform/python-for-android-master/pythonforandroid/toolchain.py", line 902, in main`
`    ToolchainCL()`
`  File "$HOME/projects/program/.buildozer/android/platform/python-for-android-master/pythonforandroid/toolchain.py", line 508, in __init__`
`    getattr(self, args.subparser_name.replace('-', '_'))(args)`
`  File "$HOME/projects/program/.buildozer/android/platform/python-for-android-master/pythonforandroid/toolchain.py", line 147, in wrapper_func`
`    build_dist_from_args(ctx, dist, args)`
`  File "$HOME/projects/program/.buildozer/android/platform/python-for-android-master/pythonforandroid/toolchain.py", line 190, in build_dist_from_args`
`    build_recipes(build_order, python_modules, ctx)`
`  File "$HOME/projects/program/.buildozer/android/platform/python-for-android-master/pythonforandroid/build.py", line 565, in build_recipes`
`    recipe.build_arch(arch)`
`  File "$HOME/projects/program/.buildozer/android/platform/python-for-android-master/pythonforandroid/recipe.py", line 806, in build_arch`
`    self.install_python_package(arch)`
`  File "$HOME/projects/program/.buildozer/android/platform/python-for-android-master/pythonforandroid/recipe.py", line 839, in install_python_package`
`    _env=hpenv, *self.setup_extra_args)`
`  File "$HOME/projects/program/.buildozer/android/platform/python-for-android-master/pythonforandroid/logger.py", line 175, in shprint`
`    for line in output:`
`  File "$HOME/.local/lib/python3.5/site-packages/sh.py", line 863, in next`
`    self.wait()`
`  File "$HOME/.local/lib/python3.5/site-packages/sh.py", line 792, in wait`
`    self.handle_command_exit_code(exit_code)`
`  File "$HOME/.local/lib/python3.5/site-packages/sh.py", line 815, in handle_command_exit_code`
`    raise exc`
`sh.ErrorReturnCode_2: `

`  RAN: /usr/bin/python3.5 setup.py install -O2 --root=$HOME/projects/program/.buildozer/android/platform/build/build/python-installs/myapp --install-lib=.`

`  STDOUT:`
`/usr/bin/python3.5: can't open file 'setup.py': [Errno 2] No such file or directory`

`  STDERR:`
`# Command failed: /usr/bin/python3 -m pythonforandroid.toolchain create --dist_name=myapp --bootstrap=sdl2 --requirements=kivy,python3crystax,ws4py,networkx,decorator,lib2to3 --arch armeabi-v7a --copy-libs --color=always --storage-dir=$HOME/projects/program/.buildozer/android/platform/build`

**Requirements with networkx, lib2to3 without recipes**
If I just try to set requirements=kivy, python3crystax, networkx, lib2to3 without recipes, logcat shows

`09-02 14:55:18.480 19850 20608 I python  :  Traceback (most recent call last):`
`09-02 14:55:18.480 19850 20608 I python  :    File "main.py", line 1, in <module>`
`09-02 14:55:18.482 19850 20608 I python  :      import program`
`09-02 14:55:18.483 19850 20608 I python  :    File "./program.py", line 16, in <module>`
`09-02 14:55:18.484 19850 20608 I python  :      import networkx as nx`
`09-02 14:55:18.484 19850 20608 I python  :    File "/data/user/0/org.test.myapp/files/app/crystax_python/site-packages/networkx/__init__.py", line 87, in <module>`
`09-02 14:55:18.485 19850 20608 I python  :      import networkx.readwrite`
`09-02 14:55:18.486 19850 20608 I python  :    File "/data/user/0/org.test.myapp/files/app/crystax_python/site-packages/networkx/readwrite/__init__.py", line 14, in <module>`
`09-02 14:55:18.486 19850 20608 I python  :      from networkx.readwrite.gml import *`
`09-02 14:55:18.487 19850 20608 I python  :    File "/data/user/0/org.test.myapp/files/app/crystax_python/site-packages/networkx/readwrite/gml.py", line 44, in <module>`
`09-02 14:55:18.488 19850 20608 I python  :      from lib2to3.pgen2.parse import ParseError`
`09-02 14:55:18.488 19850 20608 I python  :  ImportError: No module named 'lib2to3'`

**Comment by inclement** [comment]
Closing as a python-for-android issue, please reopen there if it's still a problem. Probably lib2to3 needs a recipe to be included in the hostpython build.
