### ISSUE TITLE
p4a.source_dir set and android clean --> crash

### ISSUE THREAD

**Issue by mixmastamyk** [kivy/buildozer#556]
Reset:

    p4a.source_dir = /....

    ⏵ rm -rf .buildozer
    ⏵ buildozer android clean

    FileNotFoundError: [Errno 2] No such file or directory: '/.../.buildozer/android/platform/python-for-android-master'

Can never recover from this until commenting: `p4a.source_dir ` in `buildozer.spec`.

**Comment by kuzeyron** [comment]
`p4a.source_dir` path is wrong.
`p4a.source_dir = /real-path/to/python-for-android`
is how it should be. And don't use `.buildozer` as path, as of it's the working directory that runs the magic for you.

Cheers!
