### ISSUE TITLE
failed to build numpy on Mac

### ISSUE THREAD

**Issue by Chao-Jen** [kivy/buildozer#557]
I'm using buildozer v0.34dev on Mac to build an Android APK that requires numpy. The same python code and buildozer spec can build successfully on Ubuntu, but they don't build on Mac as I get the following error when building numpy:
**numpy/core/src/private/npy_fpmath.h:48:6: error: #error No long double representation defined**

Please refer to the buildozer log as attached below.
[buildozer.txt](https://github.com/kivy/buildozer/files/1289483/buildozer.txt)

**Comment by tiksem** [comment]
Did you find a solution? I faced the same problem.

**Comment by inclement** [comment]
Closing as stale, should be working on p4a master.
