### ISSUE TITLE
Requests SSL error

### ISSUE THREAD

**Issue by SamuelHaidu** [kivy/buildozer#565]
I want to make a simple request for youtube but i can build my project and when I make the request:

> I/python  (17495):  requests.exceptions.SSLError: Can't connect to HTTPS URL because the SSL module is not available.
I/python  (17495): Python for android ended.

[log_23_09_2017.txt](https://github.com/kivy/buildozer/files/1326253/log_23_09_2017.txt)

The buildozer requirements:

requirements = kivy,requests,png,pyopenssl,pyasn1,ndg_httpsclient,python2,hostpython2

**Comment by inclement** [comment]
Add 'openssl' to your requirements.
