### ISSUE TITLE
file exists error.. use  distutils.dir_util.copy_tree instead of shutils.copytree

### ISSUE THREAD

**Issue by dav01it** [kivy/buildozer#569]
please **replace** the copytree from shutil.copytree with:

from distutils.dir_util import copy_tree
copy_tree("/dir1", "/dir2")

otherwise I get file exists error.
see: [https://stackoverflow.com/questions/1868714/how-do-i-copy-an-entire-directory-of-files-into-an-existing-directory-using-pyth](https://stackoverflow.com/questions/1868714/how-do-i-copy-an-entire-directory-of-files-into-an-existing-directory-using-pyth)
**in particular Brendan Abel answer.**

For me works only with copy_tree-> modified  in `~/buildozer/buildozer/__init__.py`

Sorry I'm not so experienced to submit the code... fear to do some mistakes!

**Comment by nateshmbhat** [comment]
Ya this is an essential addon which is really required when using the copytree method . Please at least provide an extra commandline argument to copy entire folders along with files recursively .

**Comment by AndreMiras** [comment]
Pull requests welcome

**Comment by Julian-O** [comment]
This is an old issue.

* It isn't clear here under what conditions the "file exists error" is being raised and whether it is still reproduceable.
* Buildozer is not using `buildops`, which sometimes uses shutil.copy_tree().
* distutils is deprecated, and not in Python 3.12, so the proposed solution is not tenable.

Given there is no clear problem to be solved here, I am closing this issue. If this is in error, please let us know.
