### ISSUE TITLE
Apple Watch Support

### ISSUE THREAD

**Issue by mbrockman1** [kivy/buildozer#574]
Can you write apps for Apple Watch with buildozer/Kivy-iOS?

**Comment by hackalog** [comment]
As of Jan, 2019, not that I know of. It should definitely go on the roadmap, thought.

**Comment by hackalog** [comment]
Since this will have to be implemented in kivy-ios, (and there's an issue for it there: https://github.com/kivy/kivy-ios/issues/269) I think this can be safely closed.
