### ISSUE TITLE
Problem upgrade to newest version

### ISSUE THREAD

**Issue by FilipDem** [kivy/buildozer#583]
I am trying to upgrade to the newest version of buildozer ie 0.33 (and Kivy 1.10). I am still using the old_toolchain because there is not yet a recipe for lxml. Unfortunately it is not with lot of success.
I upgraded using pip. I got always the error:
configure: error: in `/home/filip/git/MyPortfolio/.buildozer/android/platform/python-for-android/build/libxml2/libxml2-2.7.8':
configure: error: C compiler cannot create executables
Can sb help?

Attached you can find the *.spec and the config.log with the problem.
[buildozer.spec.txt](https://github.com/kivy/buildozer/files/1464873/buildozer.spec.txt)
[config.log](https://github.com/kivy/buildozer/files/1464871/config.log)

**Comment by inclement** [comment]
Closing as an old toolchain issue, no longer supported, lxml is supported in p4a master.
