### ISSUE TITLE
Problem running buildozer android debug first time

### ISSUE THREAD

**Issue by tsolorio** [kivy/buildozer#586]
I don't normally ask for help but I'm frustrated and really want to get this to work. I've been struggling with this for a few days and I managed to work out some of the errors and of course more errors come up. Now I'm just plan stuck and can't move forward. Let me know if I need to add anything else that maybe I forgot to mention. So when I run buildozer android debug or with debug deploy run I get the error that can't open setup.py. I check that directory and there are .py files there but no setup.py. I'm a bit new to python so maybe I'm missing something and just need a 2nd pair of eyes to spot it. TIA

Error log here:
https://pastebin.com/heXfHW0s

**Comment by inclement** [comment]
Please post support questions on the [kivy-users mailing list](https://groups.google.com/forum/#!forum/kivy-users), we use github issues mainly for development issues.

I think your log is missing some information about the actual error that occurred - is this really all that is printed?
