### ISSUE TITLE
ERROR: Trying to release a package that starts with org.test; what can I do?

### ISSUE THREAD

**Issue by trDjango** [kivy/buildozer#593]
After installing buildozer program I gave the following command and it worked properly.
`buildozer android debug deploy run`
and then:
when I want to package a different file(via this command: `buildozer android release`), i am getting this error:

```
# 
# ERROR: Trying to release a package that starts with org.test
# 
# The package.domain org.test is, as the name intented, a test.
# Once you published an application with org.test,
# you cannot change it, it will be part of the identifier
# for Google Play / App Store / etc.
# 
# So change package.domain to anything else.
# 
# If you messed up before, set the environment variable to force the build:
# export BUILDOZER_ALLOW_ORG_TEST_DOMAIN=1
# 
Traceback (most recent call last):
  File "/usr/local/bin/buildozer", line 11, in <module>
    load_entry_point('buildozer', 'console_scripts', 'buildozer')()
  File "/home/yemrems/buildozer/buildozer/scripts/client.py", line 13, in main
    Buildozer().run_command(sys.argv[1:])
  File "/home/yemrems/buildozer/buildozer/__init__.py", line 1058, in run_command
    self.target.run_commands(args)
  File "/home/yemrems/buildozer/buildozer/target.py", line 91, in run_commands
    func(args)
  File "/home/yemrems/buildozer/buildozer/target.py", line 122, in cmd_release
    if "BUILDOZER_ALLOW_ORG_TEST_DOMAIN" not in os.environ:
NameError: name 'os' is not defined
```

**Comment by inclement** [comment]
This is a simple import bug, I've made a PR that should fix it at https://github.com/kivy/buildozer/pull/594. You can try making that same change to fix the issue.

If you don't want to do that, you can just use any other package name format other than `org.kivy`. You probably may as well do this anyway, there isn't much reason to use `org.test` in a release APK.

**Comment by trDjango** [comment]
thank you so much inclement; I used python3 to buildozer program with the following commands:
but but I can not find where the module is now. where is the buildozer module path? do you have an idea?
```
git clone https://github.com/kivy/buildozer
cd buildozer
python3 setup.py build
sudo pip3 install -e .
```

**Comment by trDjango** [comment]
i found, many thanks:))
```
import os
import buildozer
path = os.path.abspath(buildozer.__file__)
print(path)
```

**Comment by Fizik77768** [comment]
> i found, many thanks:))
> 
> ```
> import os
> import buildozer
> path = os.path.abspath(buildozer.__file__)
> print(path)
> ```

which file to insert?
