### ISSUE TITLE
Issu with buildozer packing

### ISSUE THREAD

**Issue by upam00** [kivy/buildozer#596]
HI There! 
I am having the following error while packing my very first "hello world" kivy apps. Any suggestion would be highly appreciated.
[WARNING]: ERROR: /home/upam/.buildozer/android/platform/apache-ant-1.9.4/bin/ant failed!
WARNING: Received a --sdk argument, but this argument is deprecated and does nothing.
# Command failed: /usr/bin/python2 -m pythonforandroid.toolchain apk --debug --bootstrap=sdl2 --dist_name upamor_app --name 'Upam'"'"'s App' --version 1.0 --package org.test.upamor_app --android_api 19 --sdk 19 --minsdk 9 --private /home/upam/Documents/.buildozer/android/app --permission INTERNET --orientation sensor --window --copy-libs --arch armeabi-v7a --color=always --storage-dir=/home/upam/Documents/.buildozer/android/platform/build
# 
# Buildozer failed to execute the last command
# The error might be hidden in the log above this error
# Please read the full log, and search for it before
# raising an issue with buildozer itself.
# In case of a bug report, please add a full log with log_level = 2

**Comment by PoireWilliams** [comment]
i have the same problem. help please.

**Comment by tito** [comment]
Guys, please read the error and follow the rules.
