### ISSUE TITLE
FileNotFoundError at end of build when copying APK file.

### ISSUE THREAD

**Issue by metamarcdw** [kivy/buildozer#602]
Using buildozer VM and Python 3. Running a simple test app copied straight from https://github.com/kivy/kivy/wiki/Community-Guidelines. APK seems to build and work if copied manually to the phone, but deploy does not work. Copy file fails with FileNotFoundError.

[DEBUG log](https://gist.github.com/metamarcdw/0d8001d9559211b5445ad4af037d46c5)
[buildozer.spec](https://gist.github.com/metamarcdw/8d92c91fd9c48f9721df10964bef98f5)

**Comment by metamarcdw** [comment]
Nevermind. Did a git pull, deleted .buildozer/ and started over. Everything seems to be working now.

**Comment by metamarcdw** [comment]
Reopening this issue. Turns out that this error does still happen, whenever the build is done using Ant as opposed to Gradle.

**Comment by inclement** [comment]
Closing as probably fixed now, ant is not supported and the issue was likely resolved anyway.
