### ISSUE TITLE
Installing buildozer for Python 3 failed

### ISSUE THREAD

**Issue by davetest123** [kivy/buildozer#604]
I tried to install buildozer with Python 3 support as per the instructions here: 

https://pypi.python.org/pypi/buildozer

which are 

> Installing Buildozer with python3 support:
> 
> The pip package does not yet support python3.
> 
>     Install buildozer from source:
> 
>     git clone https://github.com/kivy/buildozer
>     cd buildozer
>     python setup.py build
>     sudo pip install -e .

but the last step (sudo pip install -e .) fails.  

I'm using XUbuntu 16.04.  The output of the commands is below.  Any help would be greatly appreciated.

david.toth@cs-owl:~$ git clone https://github.com/kivy/buildozer
Cloning into 'buildozer'...
remote: Counting objects: 2713, done.
remote: Compressing objects: 100% (78/78), done.
remote: Total 2713 (delta 58), reused 39 (delta 15), pack-reused 2620
Receiving objects: 100% (2713/2713), 930.21 KiB | 0 bytes/s, done.
Resolving deltas: 100% (1667/1667), done.
Checking connectivity... done.

david.toth@cs-owl:~$ cd buildozer/

david.toth@cs-owl:~/buildozer$ python setup.py build
/usr/lib/python2.7/dist-packages/setuptools/dist.py:285: UserWarning: Normalizing '0.35dev' to '0.35.dev0'
  normalized_version,
running build
running build_py
creating build
creating build/lib.linux-x86_64-2.7
creating build/lib.linux-x86_64-2.7/buildozer
copying buildozer/jsonstore.py -> build/lib.linux-x86_64-2.7/buildozer
copying buildozer/__main__.py -> build/lib.linux-x86_64-2.7/buildozer
copying buildozer/sitecustomize.py -> build/lib.linux-x86_64-2.7/buildozer
copying buildozer/target.py -> build/lib.linux-x86_64-2.7/buildozer
copying buildozer/__init__.py -> build/lib.linux-x86_64-2.7/buildozer
creating build/lib.linux-x86_64-2.7/buildozer/targets
copying buildozer/targets/android.py -> build/lib.linux-x86_64-2.7/buildozer/targets
copying buildozer/targets/ios.py -> build/lib.linux-x86_64-2.7/buildozer/targets
copying buildozer/targets/osx.py -> build/lib.linux-x86_64-2.7/buildozer/targets
copying buildozer/targets/android_new.py -> build/lib.linux-x86_64-2.7/buildozer/targets
copying buildozer/targets/__init__.py -> build/lib.linux-x86_64-2.7/buildozer/targets
creating build/lib.linux-x86_64-2.7/buildozer/libs
copying buildozer/libs/version.py -> build/lib.linux-x86_64-2.7/buildozer/libs
copying buildozer/libs/__init__.py -> build/lib.linux-x86_64-2.7/buildozer/libs
copying buildozer/libs/_structures.py -> build/lib.linux-x86_64-2.7/buildozer/libs
creating build/lib.linux-x86_64-2.7/buildozer/scripts
copying buildozer/scripts/remote.py -> build/lib.linux-x86_64-2.7/buildozer/scripts
copying buildozer/scripts/client.py -> build/lib.linux-x86_64-2.7/buildozer/scripts
copying buildozer/scripts/__init__.py -> build/lib.linux-x86_64-2.7/buildozer/scripts
running egg_info
creating buildozer.egg-info
writing requirements to buildozer.egg-info/requires.txt
writing buildozer.egg-info/PKG-INFO
writing top-level names to buildozer.egg-info/top_level.txt
writing dependency_links to buildozer.egg-info/dependency_links.txt
writing entry points to buildozer.egg-info/entry_points.txt
writing manifest file 'buildozer.egg-info/SOURCES.txt'
reading manifest file 'buildozer.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no files found matching '*COPYING'
writing manifest file 'buildozer.egg-info/SOURCES.txt'
copying buildozer/default.spec -> build/lib.linux-x86_64-2.7/buildozer

david.toth@cs-owl:~/buildozer$ sudo pip install -e .
The directory '/home/david.toth/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/home/david.toth/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Obtaining file:///home/david.toth/buildozer
    Complete output from command python setup.py egg_info:
    /usr/lib/python2.7/dist-packages/setuptools/dist.py:285: UserWarning: Normalizing '0.35dev' to '0.35.dev0'
      normalized_version,
    running egg_info
    writing requirements to buildozer.egg-info/requires.txt
    error: [Errno 13] Permission denied: 'buildozer.egg-info/requires.txt'

I did try the -H option but that didn't help:

david.toth@cs-owl:~/buildozer$ sudo -H pip install -e .
Obtaining file:///home/david.toth/buildozer
    Complete output from command python setup.py egg_info:
    /usr/lib/python2.7/dist-packages/setuptools/dist.py:285: UserWarning: Normalizing '0.35dev' to '0.35.dev0'
      normalized_version,
    running egg_info
    writing requirements to buildozer.egg-info/requires.txt
    error: [Errno 13] Permission denied: 'buildozer.egg-info/requires.txt'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /home/david.toth/buildozer/

**Comment by aaronjohnson92** [comment]
Look at the error
`error: [Errno 13] Permission denied: 'buildozer.egg-info/requires.txt'`
run with sudo -H and you'll be fine.
`sudo -H python setup.py build`
`sudo -H python pip install -e `

the -H flag of sudo does the following (for your own knowledge!)
`-H, --set-home                set HOME variable to target user's home dir`

**Comment by SonofPoseidon1982** [comment]
FUCK OFF fuck off fuck off
