### ISSUE TITLE
APK Build Failing with Python 3.6

### ISSUE THREAD

**Issue by OptimusGREEN** [kivy/buildozer#605]
> MacOS High Sierra

> Python 3.6

Just to note i was previously using python 2.7 and could build apps no problem but can't seem to get past this error.

in requirements i've tried various combos of the following based on snippets throughout my googling.
requirements = kivy, android, python3crystax==3.6, hostpython3, backports.ssl-match-hostname

here is the level 2 log [https://pastebin.com/MVsEidQK](url)

any help would be greatly appreciated.

**Comment by tito** [comment]
So far, the link works for me here now

**Comment by OptimusGREEN** [comment]
Hi, 

Thanks for the reply.

If I paste the link into a browser the file downloads but not working in buildozer.

I have no idea where to go from here.

Any further suggestions would be great.

**Comment by OptimusGREEN** [comment]
UPDATE

I found something online which seems to have solved this for me.

running  /Applications/Python\ 3.6/Install\ Certificates.command in terminal updated my certs.

Hope this helps someone else.
