### ISSUE TITLE
failing to compile sample android app with buildozer 

### ISSUE THREAD

**Issue by RudolfVonKrugstein** [kivy/buildozer#61]
Hey,

I am on ubuntu 13.10 and I installed buildozer via pip.
Now, in a directory with a simple main.py, I run:

```
buildozer init
```

Then I change the requirements in the buildozer.spec so that it reads:

```
requirements = kivy pyjnius
```

and I run

```
 buildozer --verbose android debug deploy run
```

which finishes with this error message:

```
# Install requirement kivy pyjnius in virtualenv
# Run 'pip-2.7 install --download-cache=/home/ls/.buildozer/cache --target=/home/ls/src/BuildozerTest/.buildozer/applibs kivy pyjnius'
# Cwd /home/ls/src/BuildozerTest/.buildozer
Downloading/unpacking kivy
  Using download cache from /home/ls/.buildozer/cache/https%3A%2F%2Fpypi.python.org%2Fpackages%2Fsource%2FK%2FKivy%2FKivy-1.7.2.tar.gz
  Running setup.py egg_info for package kivy

    Cython is missing, its required for compiling kivy !


    Traceback (most recent call last):
      File "<string>", line 16, in <module>
      File "/home/ls/src/BuildozerTest/.buildozer/venv/build/kivy/setup.py", line 58, in <module>
        from Cython.Distutils import build_ext
    ImportError: No module named Cython.Distutils
    Complete output from command python setup.py egg_info:


Cython is missing, its required for compiling kivy !





Traceback (most recent call last):

  File "<string>", line 16, in <module>

  File "/home/ls/src/BuildozerTest/.buildozer/venv/build/kivy/setup.py", line 58, in <module>

    from Cython.Distutils import build_ext

ImportError: No module named Cython.Distutils

----------------------------------------
Cleaning up...
Command python setup.py egg_info failed with error code 1 in /home/ls/src/BuildozerTest/.buildozer/venv/build/kivy
Storing complete log in /home/ls/.pip/pip.log
# Command failed: pip-2.7 install --download-cache=/home/ls/.buildozer/cache --target=/home/ls/src/BuildozerTest/.buildozer/applibs kivy pyjnius
```

**Comment by Priler** [comment]
SOLVED

**Comment by tejastank** [comment]
I had Cython version 0.25.2 installed even face similar issue.

Collecting KivyCalendar
  Using cached KivyCalendar-0.1.3.tar.gz
Collecting kivy (from KivyCalendar)
  Using cached Kivy-1.10.0.tar.gz
    Complete output from command python setup.py egg_info:
    Using distutils
    
    Cython is missing, it's required for compiling kivy !
    
    
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-kWlYZa/kivy/setup.py", line 219, in <module>
        from Cython.Distutils import build_ext
    ImportError: No module named Cython.Distutils
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-kWlYZa/kivy/
# Command failed: pip install --target=/home/devid/source/nnnn/qbinterfaceversion2/.buildozer/applibs KivyCalendar
# 
# Buildozer failed to execute the last command
# The error might be hidden in the log above this error
# Please read the full log, and search for it before
# raising an issue with buildozer itself.
# In case of a bug report, please add a full log with log_level = 2
