### ISSUE TITLE
Build failing in final ANT stage

### ISSUE THREAD

**Issue by bedachtm** [kivy/buildozer#610]
The app works perfectly within my Pycharm environment as well as with the Kivy Launcher on Android. Every time I try to package I get the same error:

BUILD FAILED	
/home/kivy/.buildozer/android/platform/android-sdk-20/tools/ant/build.xml:928: The following error occurred while executing this line:	
/home/kivy/.buildozer/android/platform/android-sdk-20/tools/ant/build.xml:946: null returned: 139

The same Kivy/VM environment packages other apps successfully without errors. I've been looking at this for months now with no success.

Can anybody point me in the right direction?

[buildozer.spec.txt](https://github.com/kivy/buildozer/files/1591138/buildozer.spec.txt)
[console.txt](https://github.com/kivy/buildozer/files/1591136/console.txt)
[compile.txt](https://github.com/kivy/buildozer/files/1591137/compile.txt)

**Comment by inclement** [comment]
Closing as stale, ant is no longer used.
