### ISSUE TITLE
Java compiling issue: buildozer uses obsolete source value 1.5

### ISSUE THREAD

**Issue by saband** [kivy/buildozer#619]
I'm trying to compile project with Facebook SDK and there is an error:

[DEBUG]:   	-compile:
[DEBUG]:   	    [javac] Compiling 154 source files to /home/saband/python/kivy/Simple-Facebook-Login-on-Kivy/facebook-android-sdk-4.5.1/facebook/bin/classes
[DEBUG]:   	    [javac] warning: [options] source value 1.5 is obsolete and will be removed in a future release
[DEBUG]:   	    [javac] warning: [options] target value 1.5 is obsolete and will be removed in a future release
[DEBUG]:   	    [javac] warning: [options] To suppress warnings about obsolete options, use -Xlint:-options.
[DEBUG]:   	    [javac] /home/saband/python/kivy/Simple-Facebook-Login-on-Kivy/facebook-android-sdk-4.5.1/facebook/src/com/facebook/AccessToken.java:559: error: diamond operator is not supported in -source 1.5
[DEBUG]:   	    [javac]         ArrayList<String> permissionsList = new ArrayList<>();
[DEBUG]:   	    [javac]                                                           ^
[DEBUG]:   	    [javac]   (use -source 7 or higher to enable diamond operator)

Full log (level 2) here: https://pastebin.com/mADD63ex

I have openjdk-8-jdk installed and I don't know why buildozer uses source 5 and how to correct it (where I can "use -source 7 or higher" as recommended.

**Comment by inclement** [comment]
Are you using python-for-android master, and a recent SDK? I think p4a sets a more appropriate source value in this case.

**Comment by saband** [comment]
I'm sorry, it's really issue of SDK. How to fix it: open android-sdk-21/tools/ant/build.xml and change
```
<property name="java.target" value="1.5" />
<property name="java.source" value="1.5" />
```
