### ISSUE TITLE
unexpected e_machine: 3

### ISSUE THREAD

**Issue by ajurna** [kivy/buildozer#621]
Hello when i compile my apk file i get the following error on the console. not sure what exactly i need to do to fix it.

    02-15 14:29:53.969  9343  9546 I python  : Android kivy bootstrap done. __name__ is __main__
    02-15 14:29:53.969  9343  9546 I python  : AND: Ran string
    02-15 14:29:53.969  9343  9546 I python  : Run user program, change dir and execute entrypoint
    02-15 14:29:53.969  9343  9546 I python  : main.py
    02-15 14:29:54.155  9343  9546 I python  : Traceback (most recent call last):
    02-15 14:29:54.155  9343  9546 I python  :   File "main.py", line 4, in <module>
    02-15 14:29:54.156  9343  9546 I python  :     import cv2
    02-15 14:29:54.156  9343  9546 I python  :   File "/data/user/0/org.test.myapp/files/app/crystax_python/site-packages/cv2/__init__.py", line 4, in <module>
    02-15 14:29:54.156  9343  9546 I python  :     from .cv2 import *
    02-15 14:29:54.156  9343  9546 I python  : ImportError: dlopen failed: "/data/data/org.test.myapp/files/app/crystax_python/site-packages/cv2/cv2.so" has unexpected e_machine: 3
    02-15 14:29:54.164  9343  9546 I python  : Python for android ended.

**Comment by inclement** [comment]
This means the library is built for the wrong architecture - I guess it's probably a bug with the opencv recipe.

**Comment by ajurna** [comment]
ok, any chance you could point me in the right direction? any part of the docs that would help?

**Comment by inclement** [comment]
Closing as stale, I don't think this error is occurring any more.

**Comment by joshuapaul2005** [comment]
Hi I am facing the same issue as well please help me

**Comment by Vampirebat** [comment]
Loading library: sqlite3
                         V  Library loading error: dlopen failed: "/data/ap
                            p/org.test.tcfeb231-lNtqjD9OUYXH0qPtE1HAzQ==/li
                            b/arm/libsqlite3.so" has unexpected e_machine: 
                            40 (EM_ARM)
                         V  An UnsatisfiedLinkError occurred loading sqlite
                            3
             System.err  W  dlopen failed: "/data/app/org.test.tcfeb231-lNt
                            qjD9OUYXH0qPtE1HAzQ==/lib/arm/libsqlite3.so" ha
                            s unexpected e_machine: 40 (EM_ARM)
         g.test.tcfeb23  E  No implementation found for void org.libsdl.app
                            .SDLActivity.nativeSetenv(java.lang.String, jav
                            a.lang.String) (tried Java_org_libsdl_app_SDLAc
                            tivity_nativeSetenv and Java_org_libsdl_app_SDL
                            Activity_nativeSetenv__Ljava_lang_String_2Ljava
                            _lang_String_2)

**Comment by jspuser123** [comment]
Loading library: sqlite3
V Library loading error: dlopen failed: "/data/ap
p/org.test.tcfeb231-lNtqjD9OUYXH0qPtE1HAzQ==/li
b/arm/libsqlite3.so" has unexpected e_machine:
40 (EM_ARM)
V An UnsatisfiedLinkError occurred loading sqlite
3
System.err W dlopen failed: "/data/app/org.test.tcfeb231-lNt
qjD9OUYXH0qPtE1HAzQ==/lib/arm/libsqlite3.so" ha
s unexpected e_machine: 40 (EM_ARM)
g.test.tcfeb23 E No implementation found for void org.libsdl.app
.SDLActivity.nativeSetenv(java.lang.String, jav
a.lang.String) (tried Java_org_libsdl_app_SDLAc
tivity_nativeSetenv and Java_org_libsdl_app_SDL
Activity_nativeSetenv__Ljava_lang_String_2Ljava
_lang_String_2)




same issue
