### ISSUE TITLE
"OSError: [Errno 30] Read-only file system" (# Command failed: virtualenv --python=python2.7 ./venv)

### ISSUE THREAD

**Issue by hebozhe** [kivy/buildozer#626]
I've gone through a lot of the documentations and so forth, but I'm still stuck on the following error code, and don't know where else to turn:

Here are some details. Let me know if you need more relevant ones:

- On Windows 10.
- Built a set of four py files (one main.py) all in Python 2.7.9.
- Built in all in PyCharm.
- Using manually downloaded Miniconda2 as my interpreter.
- Miniconda2 and all other files loaded in C:\Users\Me\Miniconda2\...
- Downloaded Kivy and other non-built-in modules from Windows command prompt.
- Using Kivy Buildozer VM on Oracle VM VirtualBox.
- First error was solved with the sudo install of i386 stuff from within the /media/sf_PyProjects/IdiomasApp/ folder.
- I did edit my buildozer.spec file to say "log_level = 2".
- Still can't get by this second error. The documentation is below:

```
# Remove directory and subdirectory /media/sf_PyProjects/IdiomasApp/.buildozer/applibs
# Create directory /media/sf_PyProjects/IdiomasApp/.buildozer/applibs
# Run 'virtualenv --python=python2.7 ./venv'
# Cwd /media/sf_PyProjects/IdiomasApp/.buildozer
New python executable in /media/sf_PyProjects/IdiomasApp/.buildozer/venv/bin/python2.7
Also creating executable in /media/sf_PyProjects/IdiomasApp/.buildozer/venv/bin/python
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/virtualenv.py", line 2328, in <module>
    main()
  File "/usr/local/lib/python2.7/dist-packages/virtualenv.py", line 713, in main
    symlink=options.symlink)
  File "/usr/local/lib/python2.7/dist-packages/virtualenv.py", line 925, in create_environment
    site_packages=site_packages, clear=clear, symlink=symlink))
  File "/usr/local/lib/python2.7/dist-packages/virtualenv.py", line 1370, in install_python
    os.symlink(py_executable_base, full_pth)
OSError: [Errno 30] Read-only file system
Running virtualenv with interpreter /usr/bin/python2.7
# Command failed: virtualenv --python=python2.7 ./venv
# 
# Buildozer failed to execute the last command
# The error might be hidden in the log above this error
# Please read the full log, and search for it before
# raising an issue with buildozer itself.
# In case of a bug report, please add a full log with log_level = 2
```
Do I need to share a certain set of files bidirectionally with VirtualBox to get this thing running correctly? That's my best guess, but I'm really out of my element outside of my Windows/Python bubble.

**Comment by inclement** [comment]
Are you currently using some kind of shared folder between virtualbox and windows? If so, try not using a shared folder.

**Comment by hebozhe** [comment]
Indeed I am. The files are all sitting in my Dropbox, however, so let me try to load the file into the VM from the built-in browser, and I'll ge back with you.

**Comment by hebozhe** [comment]
Good advice, @inclement 

It got a lot further, but it threw another error, [the link to which is here](https://github.com/kivy/buildozer/issues/627).

**Comment by inclement** [comment]
I'll close this then. I'll also look at adding some instructions about shared folders, though, there should be a warning about it.
