### ISSUE TITLE
x86 and armeabi-v7 libs

### ISSUE THREAD

**Issue by RudolfVonKrugstein** [kivy/buildozer#63]
Hey,

Using android.add_libs_armeabi I can choose *.so files to be added to libs/armeabi. Nice!

But how can choose *.so files for libs/x86 and libs/armeabi-v7? Is that somehow possible?

**Comment by DrMoriarty** [comment]
Yes, it isn't working. I set directories for armeabi, armeabi-v7a and for x86 libs. And buildozer shows me an error: IOError: [Errno 2] No such file or directory: '/Users/vasya/projects/mymath/.buildozer/android/platform/python-for-android/dist/mymath/libs/armeabi-v7a/libMyScript2D.so'

I checked the building files and noticed that only armeabi libs have been copied. But I can see in log:
    # Search and copy libs for armeabi
    ...
    # Search and copy libs for armeabi-v7a
    ...

**Comment by timmahhtimmahh** [comment]
Has anyone found a fix for this? I can't seem to find anything on the internet and I have no idea where the .so files buildozer is looking for would be.

**Comment by hinesmr** [comment]
@tito Ping?

**Comment by timmahhtimmahh** [comment]
I seem to have fixed the issue. I was using that to change the build to use armeabi-v7a instead of armeabi. Instead, I added a new line in the spec file called android.arch = armeabi-v7a and it worked.

**Comment by nmz787** [comment]
adding this `android.arch = armeabi-v7a` did not solve this issue for me. It also seems that using the pattern `android.add_libs_armeabi_v7a = libs/android-v7/*.so` fails to create a directory in the `dist-dir` and the following `file_copy` fails as a result. Adding a call to `os.makedirs` from `buildozer/targets/android.py` prior to trying to copy the .so libs seems to have no impact on the packaged state of the APK... logcat still shows `armeabi` not `armeabi-v7a` as being a path it searched on for my .so files... and my class is still not found.
