### ISSUE TITLE
App crashes with aws boto3

### ISSUE THREAD

**Issue by TheRealRed7** [kivy/buildozer#635]
I am creating a simple Kivy app that accesses an aws Dynamodb table. My test app runs fine locally from the command line (returns data without errors) but when I build and run on an Android device using Buildozer the app compiles and deploys but crashes as soon I try to communicate with aws.

adb logcat shows this:

`03-07 12:39:25.570 10601 10825 I python  :  ValueError: Expecting , delimiter: line 70 column 29 (char 1787)`
`03-07 12:39:25.625 10601 10825 I python  : Python for android ended.`

The line my app fails on is this:

`dynamodb = boto3.resource('dynamodb',a_access_key_id = 'AKImy keyH6Q',aws_secret_access_key = 'nl4ymSnZ9my keyecx',region_name = 'eu-west-1')`

My buildozer.spec file contains these requirements:

# (list) Permissions
android.permissions = INTERNET

# (list) Application requirements
requirements = kivy,boto3,botocore,python-dateutil,jmespath,openssl,futures,pyjnius, android

**Comment by tito** [comment]
Just FYI, i have on an old app something about it:

```
import boto3

# Hook to fix an android issue with json.loads + OrderedDict
# Seems to have everytime an issue for loading endpoints.json
# About a delimiter not there. I got down to this. It sucks
import botocore.loaders
old_load_file = botocore.loaders.JSONFileLoader.load_file


def custom_load_file(self, filename):
    full_path = filename + ".json"
    if not os.path.exists(full_path):
        return
    with open(full_path, "rb") as fd:
        data = fd.read()
        # payload = loads(data, object_pairs_hook=OrderedDict)
        payload = loads(data)
        return payload


botocore.loaders.JSONFileLoader.load_file = custom_load_file
```

Must be executed before any other boto3 import, aka before S3Transfer.

I personally moved then to direct requests, not using boto3. It take less space on the device.
