### ISSUE TITLE
IOError: [Errno 2] No such file or directory:

### ISSUE THREAD

**Issue by hebozhe** [kivy/buildozer#636]
Took a hiatus, and came back with a totally fresh (unaltered) Buildozer VM to attempt the run. A few lib installs and other installs later, I complete a debug build with 

`buildozer -v android debug`

Now, the terminal tells me that it succeeds in building the APK, and I can find the APK in the stated file. However, the debugger then says that it can't find the APK in that directory where it is.

```
[DEBUG]:   	BUILD SUCCESSFUL
[DEBUG]:   	Total time: 42 seconds
[INFO]:    <- directory context /home/kivy/Downloads/PollyGotApp/.buildozer/android/platform/python-for-android-new-toolchain
[INFO]:    # Copying APK to current directory
[INFO]:    # Found APK file: /home/kivy/Downloads/PollyGotApp/.buildozer/android/platform/build/dists/pollygot/bin/PollyGot-1.0-debug.apk
[DEBUG]:   -> running cp /home/kivy/Downloads/PollyGotApp/.buildozer/android/platform/build/dists/pollygot/bin/PollyGot-1.0-debug.apk ./
Traceback (most recent call last):
  File "/usr/local/bin/buildozer", line 11, in <module>
    load_entry_point('buildozer==0.34', 'console_scripts', 'buildozer')()
  File "/usr/local/lib/python2.7/dist-packages/buildozer/scripts/client.py", line 13, in main
    Buildozer().run_command(sys.argv[1:])
  File "/usr/local/lib/python2.7/dist-packages/buildozer/__init__.py", line 1058, in run_command
    self.target.run_commands(args)
  File "/usr/local/lib/python2.7/dist-packages/buildozer/target.py", line 92, in run_commands
    func(args)
  File "/usr/local/lib/python2.7/dist-packages/buildozer/target.py", line 104, in cmd_debug
    self.buildozer.build()
  File "/usr/local/lib/python2.7/dist-packages/buildozer/__init__.py", line 212, in build
    self.target.build_package()
  File "/usr/local/lib/python2.7/dist-packages/buildozer/targets/android.py", line 817, in build_package
    copyfile(join(apk_dir, apk), join(self.buildozer.bin_dir, apk_dest))
  File "/usr/lib/python2.7/shutil.py", line 82, in copyfile
    with open(src, 'rb') as fsrc:
IOError: [Errno 2] No such file or directory: u'/home/kivy/Downloads/PollyGotApp/.buildozer/android/platform/build/dists/pollygot/build/outputs/apk/pollygot-debug.apk'
```
Here's my buildozer.spec file:

```
[app]

# (str) Title of your application
title = PollyGot

# (str) Package name
package.name = pollygot

# (str) Package domain (needed for android/ios packaging)
package.domain = pollygot.test

# (str) Source code where the main.py live
source.dir = .

# (list) Source files to include (let empty to include all the files)
source.include_exts = csv,txt,otf,ttc,ttf,mp3,py,png,jpg,kv,atlas

# (str) Application versioning (method 1)
version = 1.0

# (list) Application requirements
# comma seperated e.g. requirements = sqlite3,kivy
requirements = gTTS,stringdist,kivy

# (str) Supported orientation (one of landscape, portrait or all)
orientation = portrait

# change the major version of python used by the app
osx.python_version = 2.7.9

# Kivy version to use
osx.kivy_version = 1.10.0

# (bool) Indicate if the application should be fullscreen or not
fullscreen = 0

# (list) Permissions
android.permissions = INTERNET

# (str) The Android arch to build for, choices: armeabi-v7a, arm64-v8a, x86
android.arch = armeabi-v7a

[buildozer]

# (int) Log level (0 = error only, 1 = info, 2 = debug (with command output))
log_level = 2

# (int) Display warning if buildozer is run as root (0 = False, 1 = True)
warn_on_root = 1
```
I've seen a handful of attempted solutions, but none of them seemed definitive, so I wanted to consult with some experts before I altered the android.py file, upgraded or downgraded to buildozer from pip, altered my buildozer.spec, or anything else.

I'm on the most recent update of buildozer currently, using Python 2.7.9, Cython 0.25.2, and obeying most every other recommendation, I think.

**Comment by sihardfo** [comment]
I had the same problem two weeks ago and I couldn't find any solution that worked for me including editing android.py so I came up with this solution (not practical but it actually works):
1- Go to your project directory and select the option "Show hidden files".
2- When step 1 is done, you will see a new folder called "_.buildozer_". Then go to _.buildozer/android/platform/build/dists/APPNAME/bin_. You'll see there are some files inside including apks.
3- Copy all this files (no cut) and paste it to _.buildozer/android/platform/build/dists/APPNAME/build/outputs/apk_. You'll have to create the folders "_outputs_" and "_apk_" manually. 
4- When you get your files on the folder "apk" look for a file called "_APPNAME-version-debug.apk_" and rename it to  "_APPNAME-debug.apk_" (delete the version from the name).
5- Run the command _buildozer -v android debug_ again and the final apk will appear on your rootdirectory/bin.

I will only recommend to use this if you ran out of options like in my case because it is very tedious and you have to repeat the process every time you want to create an apk.

**Comment by hebozhe** [comment]
Meh, it's no more tedious than surfing a dozen different answers and finding no clear solution. I'll give this a shot, since it's easily undone if it fails.

**Comment by sihardfo** [comment]
If it fails just delete the folders made on step 3 and you'll be in the same place where you started.

**Comment by hebozhe** [comment]
Also, questions:
First, ".buildozer/android/platform/build/dists/APPNAME/build/" was not present in my directory, so I just manually added it, as well. Is there anything else in "/build/" that I should worry about?

**Comment by hebozhe** [comment]
However, I do have two "/build/" directories, ".buildozer/android/platform/build/build", which does have some libraries, my venv, python installs, and other stuff.

**Comment by hebozhe** [comment]
Okay, a slight revision on your solution worked for me, @sihardfo:

> 1- Go to your project directory and select the option "Show hidden files".
> 2- When step 1 is done, you will see a new folder called ".buildozer". Then go to .buildozer/android/platform/build/dists/APPNAME/bin. You'll see there are some files inside including apks.
> 3- Copy all this files (no cut) and paste it to .buildozer/android/platform/build/dists/APPNAME/build/outputs/apk. You'll have to create the folders "outputs" and "apk" manually.
> 4- When you get your files on the folder "apk" look for a file called "APPNAME-version-debug.apk" and rename it to "PACKAGENAME-debug.apk" **(delete the version from the name, and replace it with APPNAME with the "package.name = PACKAGENAME" in your buildozer.spec file)**.
> 5- Run the command buildozer -v android debug again and the final apk will appear on your rootdirectory/bin.

Many thanks. Never considered the brute force approach. (Can't find it? Just shove it in there!)

**Comment by sihardfo** [comment]
Hahaha, no problem!
