### ISSUE TITLE
.so lib files missing debug symbols

### ISSUE THREAD

**Issue by hebozhe** [kivy/buildozer#637]
So I tried getting my bin/debug.apk to work in the Buildozer VM, but there was a problem with loading adb and attaching my Android device via USB, so I exported my bin/debug.apk to my desktop to debug it in Android Studio. However, in its first steps, it throws an error that asks me to replace the .so libraries with identical ones that have debug symbols.

![Android Studio Error: .so lib files missing debug symbols](https://user-images.githubusercontent.com/20052850/37626498-e7276158-2b95-11e8-8bd8-4feb1a9c4d5e.jpg)

Are these stashed anywhere in the Buildozer VM during the `buildozer android debug` phase?

Is there a way to either get the libs with the symbols or work around not having them on either Android Studio or the Buildozer VM?

**Comment by TheIronNinja** [comment]
Having the same problem here, any help appreciated!

**Comment by kuzeyron** [comment]
Have you tried adding 'hostpython2' to the requirements in the buildozer.spec?

**Comment by msseibel** [comment]
Similar problem. I used 'hostpython2'. I found the mentionend .so files inside 
...../.buildozer/android/platform/build/build/bootstrap_builds/sdl2_gradle-python2/libs/armeabi-v7a/ 

and

....../.buildozer/android/platform/build/build/libs_collections/myapp/armeabi-v7a/

and tried to add them, but that didnt changed the problem.

**Comment by kuzeyron** [comment]
And of course you've tried to 'buildozer clean' or 'rm -rf .buildozer'?

**Comment by inclement** [comment]
Closing as a python-for-android issue, feel free to open an issue about adding debug symbols there.
