### ISSUE TITLE
Kivy Crashing

### ISSUE THREAD

**Issue by Weffle** [kivy/buildozer#638]
I compiled my kivy code with Buildozer on ubuntu, and i put the apk on my device. When I start the app, it shows the kivy loading screen, then it crashes and says "Unfortunately App, has stopped." what should I do? I dont know how to fix this. Please help.

This might be a bug?
I have Android Studio but don't use it and don't know how to use "logcat".

**Comment by nbawane** [comment]
you got to use adb. https://www.xda-developers.com/install-adb-windows-macos-linux/
put your phone on debugging mode. start logcat and app and see why is it crashing.

**Comment by farzinh** [comment]
I have the same Issues in my emulator, 4 days on it, still coulden't find any solution.
[ADB_logcat.txt](https://github.com/kivy/buildozer/files/2075152/ADB_logcat.txt)

**Comment by inclement** [comment]
Closed as solved per @nbawane's commend.
