### ISSUE TITLE
python.host failed

### ISSUE THREAD

**Issue by nogur9** [kivy/buildozer#640]
I've tried multiple times to compile my app using buildozer, 
but this error keep happening  - 
[WARNING]: ERROR: /home/kivy/meow/.buildozer/android/platform/build/build/python-installs/GraphGame/bin/python.host failed!
Command failed: /usr/bin/python -m pythonforandroid.toolchain create --dist_name=GraphGame --bootstrap=sdl2 --requirements=hostpython2,kivy,twisted --arch armeabi-v7a --copy-libs --color=always --storage-dir=/home/kivy/meow/.buildozer/android/platform/build

in the requirements there is - hostpython2,kivy,twisted

do you have any suggestions?

**Comment by inclement** [comment]
Closing as stale, probably fixed in python-for-android.
