### ISSUE TITLE
sslv3 alert handshake failure on Addroid

### ISSUE THREAD

**Issue by nbawane** [kivy/buildozer#643]
request working fine on the windows machine but on android giving the error "_[Errno 1] _ssl.c:503: error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure_". I am issueing many other requests also but only  '_https://www.buyucoin.com/api/v1.2/currency/markets_' request fails. Any suggestions?

requirements = kivy,requests[security],openssl

**Comment by inclement** [comment]
closing as stale, openssl should currently be working fine.
