### ISSUE TITLE
 The python3crystax recipe can only be built when using the CrystaX NDK. Exiting.

### ISSUE THREAD

**Issue by AhSem** [kivy/buildozer#648]
Python: 3.6.3
Kivy: v1.10.1.dev0, git-Unknown, 20180329
pip: v9.0.3
PC: MacOS Sierra v10.12.6
crystax: crystax-ndk-10.3.2

When running "buildozer android debug", I eventually got the error "The python3crystax recipe can only be built when using the CrystaX NDK. Exiting."

The log is as follow. 

....
[INFO]:    python3crystax has no prebuild_armeabi_v7a, skipping
[ERROR]:   The python3crystax recipe can only be built when using the CrystaX NDK. Exiting.
b'\x1b[0m\r           working: SDL2_image-2.0.1.tar.gz                                    'b'\x1b[0m\r                                                                               \r'b'\x1b[0m\r           working: SDL2_mixer-2.0.1.tar.gz                                    'b'\x1b[0m\r                                                                               \r'b'\x1b[0m\r           working: SDL2_ttf-2.0.14.tar.gz                                     'b'\x1b[0m\r                                                                               \r'b'\x1b[0m\r           working: SDL2-2.0.4.tar.gz                                          'b'\x1b[0m\r                                                                               \r'b'\x1b[0m\r           working: six-1.9.0.tar.gz                                           'b'\x1b[0m\r                                                                               \r'b'\x1b[0m\r           working: master.zip                                                 'b'\x1b[0m\r                                                                               \r'b'\x1b[0m\r           working: 1.10.0.zip                                                 'b'\x1b[0m\r                                                                               \r'b'\x1b[0m\r           working: SDL2_image-2.0.1.tar.gz                                    'b'\x1b[0m\r                                                                               \r'b'\x1b[0m\r           working: SDL2_mixer-2.0.1.tar.gz                                    'b'\x1b[0m\r                                                                               \r'b'\x1b[0m\r           working: SDL2_ttf-2.0.14.tar.gz                                     'b'\x1b[0m\r                                                                               \r'b'\x1b[0m\r           working: SDL2-2.0.4.tar.gz                                          'b'\x1b[0m\r                                                                               \r'b'\x1b[0m\r           working: six-1.9.0.tar.gz                                           'b'\x1b[0m\r                                                                               \r'b'\x1b[0m\r           working: master.zip                                                 'b'\x1b[0m\r                                                                               \r'b'\x1b[0m\r           working: 1.10.0.zip                                                 'b'\x1b[0m\r                                                                               \r'# Command failed: /Library/Frameworks/Python.framework/Versions/3.6/bin/python3 -m pythonforandroid.toolchain create --dist_name=unitconverter --bootstrap=sdl2 --requirements=python3crystax,kivy --arch armeabi-v7a --copy-libs --color=always --storage-dir=/Users/Sem/Dropbox/unit_converter/.buildozer/android/platform/build

What exactly is the problem? I am suspecting CrystaX NDK is the problem, because I do not know which version of CrystaX NDK i should download from https://www.crystax.net/en/download. I eventually used "crystax-ndk-10.3.2-linux-x86_64.tar.xz"

Please advice. Thank you.

**Comment by inclement** [comment]
Closing as stale, crystax is no longer recommended, everything should work in master.
