### ISSUE TITLE
Error building Kivy app with opencv(and numpy) - raise CommandNotFoundError(path)

### ISSUE THREAD

**Issue by ViktorBarzin** [kivy/buildozer#651]
Hi all,

I am trying to build an android application with kivy and buildozer which uses opencv.

Unfortunately adding either numpy or opencv in the requirements line results in error building the apk file.
Here are the log of the build as well as my .spec file.

[Build log](http://paste.ubuntu.com/p/rKNQXQbss9/)
[buildozer.spec](http://paste.ubuntu.com/p/MGW6FcBwFp/)

I have tried both with and without `crystaxNDK`  without any success.
Not including numpy or opencv in requirements just results in `ImportError` once the apk is run. 
Adding other modules like `sqlite3` build successfully. 
I have `Cython` installed as well as all the other requirements for building a kivy app.

Any suggestions would be appreciated.

Thanks,

**Comment by inclement** [comment]
Closing as fixed in python-for-android master.
