### ISSUE TITLE
SDK does not have any Build Tools installed.

### ISSUE THREAD

**Issue by cplager** [kivy/buildozer#652]
Here's what I did:

- Download V25 SDK (Version 26 has[ this problem](https://stackoverflow.com/questions/43648201/cannot-find-build-xml-error-building-android-sdk-sample
- Tell it to install V24 API
- Soft-link already installed aidl
- Build.(Complete history in shortHistory.txt attached

The problem now is that I get (full error in error.txt; full build log is build.out)
BUILD FAILED
/home/cplager/.buildozer/android/platform/android-sdk-25.2.5/tools/ant/build.xml:483: SDK does not have any Build Tools installed.

Spec file is also attached.

Any hints?

Thanks,
  Charles

[buildozer.spec.txt](https://github.com/kivy/buildozer/files/1911284/buildozer.spec.txt)
[shortHistory.txt](https://github.com/kivy/buildozer/files/1911285/shortHistory.txt)
[error.txt](https://github.com/kivy/buildozer/files/1911286/error.txt)
[build.txt](https://github.com/kivy/buildozer/files/1911287/build.txt)

**Comment by inclement** [comment]
Closing as stale, ant is no longer used.
