### ISSUE TITLE
How to correctly build an APK package with Python 3?

### ISSUE THREAD

**Issue by HeaTTheatR** [kivy/buildozer#655]
I get an error when building a package:

>ERROR: The appdirs Python module could not be found, please install it
ERROR: The sh Python module could not be found, please install version 1.10 or higher
ERROR: The jinja2 Python module could not be found, please install it.
python-for-android is exiting due to the errors above.
Command failed: /usr/bin/python3 -m pythonforandroid.toolchain create --dist_name=quotessaint --bootstrap=sdl2 --requirements=kivy==master,python3crystax --arch armeabi-v7a --copy-libs --color=always --storage-dir=/home/zavulon/Programming/Projects/Python/Mobile/Kivy/QuotesSaints/.buildozer/android/platform/build

>Ubuntu 12.10
Python 3.4
Kivy 1.10.0
Buildozer 0.34

The jinja2 module could not be installed because it is supported with Python 3.5. Module appdirs installed. Module sh installed.

bulldozer.spec:

>title = Test
package.name = test
package.domain = org.test
source.dir = .
source.include_exts = py,png,jpg,kv,atlas
version = 0.0.1
requirements = kivy==master,python3crystax
orientation = landscape
fullscreen = 1
android.api = 19
android.minapi = 9
android.sdk = 23
android.ndk_path = /home/opt/crystax-ndk-10-3-2
p4a.branch = master
android.arch = armeabi-v7a
log_level = 2
warn_on_root = 1

**Comment by inclement** [comment]
Closing as stale, probably fixed in p4a master or a local issue.
