### ISSUE TITLE
Unable to build _ctypes.so

### ISSUE THREAD

**Issue by smpsupply** [kivy/buildozer#660]
Hello all, I tried to compile _ctypes.so with buildozer and python-2.7.2 is downloaded. I had tried various of solution online but without success. 
The first method is to change the recipe, applying patch in pythonforandroid. but the online solution is not going to work since the changes suggested is not match with the target files.
The second method is straight away compile from python source code. Python 2.7.2 and 2.7.9 step by step can be found online. unfortunately, only 2.7.9 can successfully compile. but if copy _ctypes.so to the lib-dynload, error image not found occurs. then, a ready to use 2.7.2 version _ctypes.so is downloaded and same error encountered. Using command 'file' to check the _ctypes.so, it indicates ELF arm. 
My environment is MacOS 10.13.4. Hope someone can help. Thanks.

**Comment by inclement** [comment]
Closing as stale, should be working in python-for-android master.
