### ISSUE TITLE
Failed building wheel for pyaudio

### ISSUE THREAD

**Issue by 1010Manoj** [kivy/buildozer#665]
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/microdesign/Manoj/kivyPyaudio/.buildozer/android/platform/python-for-android-new-toolchain/pythonforandroid/toolchain.py", line 978, in <module>
    main()
  File "/home/microdesign/Manoj/kivyPyaudio/.buildozer/android/platform/python-for-android-new-toolchain/pythonforandroid/toolchain.py", line 975, in main
    ToolchainCL()
  File "/home/microdesign/Manoj/kivyPyaudio/.buildozer/android/platform/python-for-android-new-toolchain/pythonforandroid/toolchain.py", line 512, in __init__
    getattr(self, args.subparser_name.replace('-', '_'))(args)
  File "/home/microdesign/Manoj/kivyPyaudio/.buildozer/android/platform/python-for-android-new-toolchain/pythonforandroid/toolchain.py", line 149, in wrapper_func
    build_dist_from_args(ctx, dist, args)
  File "/home/microdesign/Manoj/kivyPyaudio/.buildozer/android/platform/python-for-android-new-toolchain/pythonforandroid/toolchain.py", line 193, in build_dist_from_args
    build_recipes(build_order, python_modules, ctx)
  File "pythonforandroid/build.py", line 592, in build_recipes
  File "pythonforandroid/build.py", line 633, in run_pymodules_install
  File "pythonforandroid/logger.py", line 175, in shprint
  File "/home/microdesign/.local/lib/python2.7/site-packages/sh.py", line 720, in next
    self.wait()
  File "/home/microdesign/.local/lib/python2.7/site-packages/sh.py", line 651, in wait
    self.handle_command_exit_code(exit_code)
  File "/home/microdesign/.local/lib/python2.7/site-packages/sh.py", line 672, in handle_command_exit_code
    raise exc
sh.ErrorReturnCode_1: 

  RAN: /bin/bash -c source venv/bin/activate && env CC=/bin/false CXX=/bin/false PYTHONPATH=/home/microdesign/Manoj/kivyPyaudio/.buildozer/android/platform/build/build/python-installs/Myrecord/lib/python2.7/site-packages pip install --target '/home/microdesign/Manoj/kivyPyaudio/.buildozer/android/platform/build/build/python-installs/Myrecord/lib/python2.7/site-packages' --no-deps -r requirements.txt

  STDOUT:
Collecting pyaudio (from -r requirements.txt (line 1))
  Using cached https://files.pythonhosted.org/packages/ab/42/b4f04721c5c5bfc196ce156b3c768998ef8c0ae3654ed29ea5020c749a6b/PyAudio-0.2.11.tar.gz
Collecting wave (from -r requirements.txt (line 2))
Building wheels for collected packages: pyaudio
  Running setup.py bdist_wheel for pyaudio ... error
  Complete output from command /home/microdesign/Manoj/kivyPyaudio/.buildozer/android/platform/build/build/venv/bin/python2.7 -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-i0kNR8/pyaudio/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/pip-wheel-b2wY2W --python-tag cp27:
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-x86_64-2.7
  copying src/pyaudio.py -> build/lib.linux-x86_64-2.7
  running build_ext
  building '_portaudio' extension
  creating build/temp.linux-x86_64-2.7
  creating build/temp.linux-x86_64-2.7/src
  /bin/false -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -Wdate-time -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -I/usr/include/python2.7 -c src/_portaudiomodule.c -o build/temp.linux-x86_64-2.7/src/_portaudiomodule.o
  error: command '/bin/false' failed with exit status 1
  
  ----------------------------------------
  Failed building wheel for pyaudio
  Running setup.py clean for pyaudio
Failed to build pyaudio
Installing collected packages: pyaudio, wave
  Running setup.py install for pyaudio ... error
    Complete output from command /home/microdesign/Manoj/kivyPyaudio/.buildozer/android/platform/build/build/venv/bin/python2.7 -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-i0kNR8/pyaudio/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-iTeWDk/install-record.txt --single-version-externally-managed --compile --install-headers /home/microdesign/Manoj/kivyPyaudio/.buildozer/android/platform/build/build/venv/include/site/python2.7/pyaudio --home=/tmp/pip-target-InujX9:
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-2.7
    copying src/pyaudio.py -> build/lib.linux-x86_64-2.7
    running build_ext
    building '_portaudio' extension
    creating build/temp.linux-x86_64-2.7
    creating build/temp.linux-x86_64-2.7/src
    /bin/false -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -Wdate-time -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -I/usr/include/python2.7 -c src/_portaudiomodule.c -o build/temp.linux-x86_64-2.7/src/_portaudiomodule.o
    error: command '/bin/false' failed with exit status 1
    
    ----------------------------------------
Command "/home/microdesign/Manoj/kivyPyaudio/.buildozer/android/platform/build/build/venv/bin/python2.7 -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-i0kNR8/pyaudio/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-iTeWDk/install-record.txt --single-version-externally-managed --compile --install-headers /home/microdesign/Manoj/kivyPyaudio/.buildozer/android/platform/build/build/venv/include/site/python2.7/pyaudio --home=/tmp/pip-target-InujX9" failed with error code 1 in /tmp/pip-install-i0kNR8/pyaudio/

  STDERR:

# Command failed: /usr/bin/python2.7 -m pythonforandroid.toolchain create --dist_name=Myrecord --bootstrap=sdl2 --requirements=kivy,pyaudio,wave --arch armeabi-v7a --copy-libs --color=always --storage-dir=/home/microdesign/Manoj/kivyPyaudio/.buildozer/android/platform/build
# 
# Buildozer failed to execute the last command
# The error might be hidden in the log above this error
# Please read the full log, and search for it before
# raising an issue with buildozer itself.
# In case of a bug report, please add a full log with log_level = 2

**Comment by inclement** [comment]
Closing as not a buildozer issue, and possibly fixed. Please open a python-for-android issue about pyaudio if the problem still occurs.

**Comment by DrBelk** [comment]
Hi,
Was this issue fixed? If yes, could you please lett me how? Have the same at the moment.

**Comment by JayantSeth** [comment]
I am facing the same issue
