### ISSUE TITLE
Buildozer gets stuck at unpacking kivy

### ISSUE THREAD

**Issue by NovotnyMCAT** [kivy/buildozer#667]
Hello everyone, 
during the compilation buildozer gets stuck at this point every time. 

[**INFO]:    Unpacking kivy for armeabi-v7a
[INFO]:    -> running basename https://github.com/kiv...(and 25 more)
[INFO]:    -> directory context /home/kivy/beerctrl/src/.buildozer/android/platform/build/build/other_builds/kivy-pygame-python2/armeabi-v7a**

It just stops here forever and does nothing. Do you have any suggestions please? 

...the general part on the begining of the log is: 

[INFO]:    Will compile for the following archs: armeabi-v7a
[INFO]:    Found Android API target in $ANDROIDAPI
[INFO]:    Available Android APIs are (19)
[INFO]:    Requested API target 19 is available, continuing.
[INFO]:    Found NDK dir in $ANDROIDNDK
[INFO]:    Got NDK version from $ANDROIDNDKVER
[INFO]:    Using Google NDK r9c
[INFO]:    Found virtualenv at /usr/local/bin/virtualenv
[INFO]:    ccache is missing, the build will not be optimized in the future.
[INFO]:    Found the following toolchain versions: ['4.6', '4.8', 'clang3.3']
[INFO]:    Picking the latest gcc toolchain, here 4.8
[INFO]:    No existing dists meet the given requirements!
[INFO]:    No dist exists that meets your requirements, so one will be built.
[INFO]:    Found a single valid recipe set: ['constantly', 'hostpython2', 'incremental', u'plyer', 'pygame_bootstrap_components', u'sqlite3', 'python2', 'sdl', 'setuptools', 'six', 'zope_interface', u'pygame', 'pyjnius', u'twisted', u'android', u'kivy']

**Comment by inclement** [comment]
Could you post the full log?

**Comment by NovotnyMCAT** [comment]
Sure, full log is: 

kivy@kivy-VirtualBox:~/beerctrl/src$ buildozer android debug
# Check configuration tokens
# Ensure build layout
# Check configuration tokens
# Preparing build
# Check requirements for android
# Run 'dpkg --version'
# Cwd None
Debian „dpkg“ - program pro správu balíků verze 1.17.5 (i386).
Toto je svobodný software; podrobnosti o podmínkách kopírování naleznete
v Obecné veřejné licenci GNU (GNU General Public Licence) verze 2 nebo
pozdější. Toto programové vybavení je absolutně bez záruky.
# Search for Git (git)
#  -> found at /usr/bin/git
# Search for Cython (cython)
#  -> found at /usr/local/bin/cython
# Search for Java compiler (javac)
#  -> found at /usr/lib/jvm/java-7-openjdk-i386/bin/javac
# Search for Java keytool (keytool)
#  -> found at /usr/lib/jvm/java-7-openjdk-i386/jre/bin/keytool
# Install platform
# Run 'pip install -q --user "appdirs" "colorama>=0.3.3" "sh>=1.10,<1.12.5" "jinja2" "six"'
# Cwd None
# Apache ANT found at /home/kivy/.buildozer/android/platform/apache-ant-1.9.4
# Android SDK found at /home/kivy/.buildozer/android/platform/android-sdk-20
# Android NDK found at /home/kivy/.buildozer/android/platform/android-ndk-r9c
# Check application requirements
# Check garden requirements
# Compile platform
# Run '/usr/bin/python -m pythonforandroid.toolchain create --dist_name=selfserviceapp --bootstrap=sdl2 --requirements=pygame,sqlite3,twisted,android,plyer,kivy --arch armeabi-v7a --copy-libs --color=always --storage-dir=/home/kivy/beerctrl/src/.buildozer/android/platform/build'
# Cwd /home/kivy/beerctrl/src/.buildozer/android/platform/python-for-android-new-toolchain
[INFO]:    Will compile for the following archs: armeabi-v7a
[INFO]:    Found Android API target in $ANDROIDAPI
[INFO]:    Available Android APIs are (19)
[INFO]:    Requested API target 19 is available, continuing.
[INFO]:    Found NDK dir in $ANDROIDNDK
[INFO]:    Got NDK version from $ANDROIDNDKVER
[INFO]:    Using Google NDK r9c
[INFO]:    Found virtualenv at /usr/local/bin/virtualenv
[INFO]:    ccache is missing, the build will not be optimized in the future.
[INFO]:    Found the following toolchain versions: ['4.6', '4.8', 'clang3.3']
[INFO]:    Picking the latest gcc toolchain, here 4.8
[INFO]:    No existing dists meet the given requirements!
[INFO]:    No dist exists that meets your requirements, so one will be built.
[INFO]:    Found a single valid recipe set: ['constantly', 'hostpython2', 'incremental', u'plyer', 'pygame_bootstrap_components', u'sqlite3', 'python2', 'sdl', 'setuptools', 'six', 'zope_interface', u'pygame', 'pyjnius', u'twisted', u'android', u'kivy']
[INFO]:    The selected bootstrap is sdl2_gradle
[INFO]:    # Creating dist with sdl2_gradle bootstrap
[INFO]:    Dist will have name selfserviceapp and recipes (pygame, sqlite3, twisted, android, plyer, kivy)
[INFO]:    Dist will also contain modules (plyer, constantly, incremental) installed from pip
[INFO]:    -> running cp -r /home/kivy/beerctrl/src/...(and 200 more)
[INFO]:    -> directory context /home/kivy/beerctrl/src/.buildozer/android/platform/build/build/bootstrap_builds/sdl2_gradle-python2
[INFO]:    <- directory context /home/kivy/beerctrl/src/.buildozer/android/platform/python-for-android-new-toolchain
[INFO]:    Recipe build order is ['hostpython2', 'pygame_bootstrap_components', u'sqlite3', 'python2', 'sdl', 'setuptools', 'six', 'zope_interface', u'pygame', 'pyjnius', u'twisted', u'android', u'kivy']
[INFO]:    The requirements (constantly, incremental, plyer) were not found as recipes, they will be installed with pip.
[INFO]:    # Downloading recipes 
[INFO]:    Downloading hostpython2
[INFO]:    -> running mkdir -p /home/kivy/beerctrl/s...(and 57 more)
[INFO]:    -> directory context /home/kivy/beerctrl/src/.buildozer/android/platform/build/packages/hostpython2
[INFO]:    -> running basename https://python.org/ftp...(and 34 more)
[INFO]:    hostpython2 download already cached, skipping
[INFO]:    <- directory context /home/kivy/beerctrl/src/.buildozer/android/platform/python-for-android-new-toolchain
[INFO]:    Downloading pygame_bootstrap_components
[INFO]:    -> running mkdir -p /home/kivy/beerctrl/s...(and 73 more)
[INFO]:    -> directory context /home/kivy/beerctrl/src/.buildozer/android/platform/build/packages/pygame_bootstrap_components
[INFO]:    -> running basename https://github.com/ki...(and 53 more)
[INFO]:    pygame_bootstrap_components download already cached, skipping
[INFO]:    <- directory context /home/kivy/beerctrl/src/.buildozer/android/platform/python-for-android-new-toolchain
[INFO]:    Downloading sqlite3
[INFO]:    -> running mkdir -p /home/kivy/beerctrl/s...(and 53 more)
[INFO]:    -> directory context /home/kivy/beerctrl/src/.buildozer/android/platform/build/packages/sqlite3
[INFO]:    -> running basename https://www.sqlite.org...(and 37 more)
[INFO]:    sqlite3 download already cached, skipping
[INFO]:    <- directory context /home/kivy/beerctrl/src/.buildozer/android/platform/python-for-android-new-toolchain
[INFO]:    Downloading python2
[INFO]:    -> running mkdir -p /home/kivy/beerctrl/s...(and 53 more)
[INFO]:    -> directory context /home/kivy/beerctrl/src/.buildozer/android/platform/build/packages/python2
[INFO]:    -> running basename https://python.org/ftp...(and 34 more)
[INFO]:    python2 download already cached, skipping
[INFO]:    <- directory context /home/kivy/beerctrl/src/.buildozer/android/platform/python-for-android-new-toolchain
[INFO]:    Downloading sdl
[INFO]:    Skipping sdl download as no URL is set
[INFO]:    Downloading setuptools
[INFO]:    -> running mkdir -p /home/kivy/beerctrl/s...(and 56 more)
[INFO]:    -> directory context /home/kivy/beerctrl/src/.buildozer/android/platform/build/packages/setuptools
[INFO]:    -> running basename https://pypi.python.o...(and 56 more)
[INFO]:    setuptools download already cached, skipping
[INFO]:    <- directory context /home/kivy/beerctrl/src/.buildozer/android/platform/python-for-android-new-toolchain
[INFO]:    Downloading six
[INFO]:    -> running mkdir -p /home/kivy/beerctrl/sr...(and 48 more)
[INFO]:    -> directory context /home/kivy/beerctrl/src/.buildozer/android/platform/build/packages/six
[INFO]:    -> running basename https://pypi.python.or...(and 40 more)
[INFO]:    six download already cached, skipping
[INFO]:    <- directory context /home/kivy/beerctrl/src/.buildozer/android/platform/python-for-android-new-toolchain
[INFO]:    Downloading zope_interface
[INFO]:    -> running mkdir -p /home/kivy/beerctrl/s...(and 60 more)
[INFO]:    -> directory context /home/kivy/beerctrl/src/.buildozer/android/platform/build/packages/zope_interface
[INFO]:    -> running basename https://pypi.python.o...(and 63 more)
     [INFO]:    zope_interface download already cached, skipping               
[INFO]:    <- directory context /home/kivy/beerctrl/src/.buildozer/android/platform/python-for-android-new-toolchain
[INFO]:    Downloading pygame
[INFO]:    -> running mkdir -p /home/kivy/beerctrl/s...(and 52 more)
[INFO]:    -> directory context /home/kivy/beerctrl/src/.buildozer/android/platform/build/packages/pygame
[INFO]:    -> running basename http://pygame.org/ftp/...(and 26 more)
[INFO]:    pygame download already cached, skipping
[INFO]:    <- directory context /home/kivy/beerctrl/src/.buildozer/android/platform/python-for-android-new-toolchain
[INFO]:    Downloading pyjnius
[INFO]:    -> running mkdir -p /home/kivy/beerctrl/s...(and 53 more)
[INFO]:    -> directory context /home/kivy/beerctrl/src/.buildozer/android/platform/build/packages/pyjnius
[INFO]:    -> running basename https://github.com/kiv...(and 28 more)
[INFO]:    pyjnius download already cached, skipping
[INFO]:    <- directory context /home/kivy/beerctrl/src/.buildozer/android/platform/python-for-android-new-toolchain
[INFO]:    Downloading twisted
[INFO]:    -> running mkdir -p /home/kivy/beerctrl/s...(and 53 more)
[INFO]:    -> directory context /home/kivy/beerctrl/src/.buildozer/android/platform/build/packages/twisted
[INFO]:    -> running basename https://github.com/twi...(and 42 more)
[INFO]:    twisted download already cached, skipping
[INFO]:    <- directory context /home/kivy/beerctrl/src/.buildozer/android/platform/python-for-android-new-toolchain
[INFO]:    Downloading android
[INFO]:    Skipping android download as no URL is set
[INFO]:    Downloading kivy
[INFO]:    -> running mkdir -p /home/kivy/beerctrl/s...(and 50 more)
[INFO]:    -> directory context /home/kivy/beerctrl/src/.buildozer/android/platform/build/packages/kivy
[INFO]:    -> running basename https://github.com/kiv...(and 25 more)
[INFO]:    kivy download already cached, skipping
[INFO]:    <- directory context /home/kivy/beerctrl/src/.buildozer/android/platform/python-for-android-new-toolchain
[INFO]:    # Building all recipes for arch armeabi-v7a
[INFO]:    # Unpacking recipes
[INFO]:    Unpacking hostpython2 for armeabi-v7a
[INFO]:    -> running basename https://python.org/ftp...(and 34 more)
[INFO]:    -> directory context /home/kivy/beerctrl/src/.buildozer/android/platform/build/build/other_builds/hostpython2/desktop
[INFO]:    hostpython2 is already unpacked, skipping
[INFO]:    <- directory context /home/kivy/beerctrl/src/.buildozer/android/platform/python-for-android-new-toolchain
[INFO]:    Unpacking pygame_bootstrap_components for armeabi-v7a
[INFO]:    -> running basename https://github.com/ki...(and 53 more)
           work[INFO]:    -> directory context /home/kivy/beerctrl/src/.buildozer/android/platform/build/build/bootstrap_builds/sdl2_gradle-python2/jni
[INFO]:    pygame_bootstrap_components is already unpacked, skipping
[INFO]:    <- directory context /home/kivy/beerctrl/src/.buildozer/android/platform/python-for-android-new-toolchain
[INFO]:    Unpacking sqlite3 for armeabi-v7a
[INFO]:    -> running basename https://www.sqlite.org...(and 37 more)
[INFO]:    -> directory context /home/kivy/beerctrl/src/.buildozer/android/platform/build/build/other_builds/sqlite3/armeabi-v7a
[INFO]:    sqlite3 is already unpacked, skipping
[INFO]:    <- directory context /home/kivy/beerctrl/src/.buildozer/android/platform/python-for-android-new-toolchain
[INFO]:    Unpacking python2 for armeabi-v7a
[INFO]:    -> running basename https://python.org/ftp...(and 34 more)
[INFO]:    -> directory context /home/kivy/beerctrl/src/.buildozer/android/platform/build/build/other_builds/python2-sqlite3/armeabi-v7a
[INFO]:    python2 is already unpacked, skipping
[INFO]:    <- directory context /home/kivy/beerctrl/src/.buildozer/android/platform/python-for-android-new-toolchain
[INFO]:    Unpacking sdl for armeabi-v7a
[INFO]:    Skipping sdl unpack as no URL is set
[INFO]:    Unpacking setuptools for armeabi-v7a
[INFO]:    -> running basename https://pypi.python.o...(and 56 more)
[INFO]:    -> directory context /home/kivy/beerctrl/src/.buildozer/android/platform/build/build/other_builds/setuptools/armeabi-v7a
[INFO]:    setuptools is already unpacked, skipping
[INFO]:    <- directory context /home/kivy/beerctrl/src/.buildozer/android/platform/python-for-android-new-toolchain
[INFO]:    Unpacking six for armeabi-v7a
[INFO]:    -> running basename https://pypi.python.or...(and 40 more)
[INFO]:    -> directory context /home/kivy/beerctrl/src/.buildozer/android/platform/build/build/other_builds/six-python2/armeabi-v7a
[INFO]:    six is already unpacked, skipping
[INFO]:    <- directory context /home/kivy/beerctrl/src/.buildozer/android/platform/python-for-android-new-toolchain
[INFO]:    Unpacking zope_interface for armeabi-v7a
[INFO]:    -> running basename https://pypi.python.o...(and 63 more)
[INFO]:    -> directory context /home/kivy/beerctrl/src/.buildozer/android/platform/build/build/other_builds/zope_interface/armeabi-v7a
[INFO]:    zope_interface is already unpacked, skipping
[INFO]:    <- directory context /home/kivy/beerctrl/src/.buildozer/android/platform/python-for-android-new-toolchain
[INFO]:    Unpacking pygame for armeabi-v7a
[INFO]:    -> running basename http://pygame.org/ftp/...(and 26 more)
           working: pygam[INFO]:    -> directory context /home/kivy/beerctrl/src/.buildozer/android/platform/build/build/other_builds/pygame/armeabi-v7a
[INFO]:    pygame is already unpacked, skipping
[INFO]:    <- directory context /home/kivy/beerctrl/src/.buildozer/android/platform/python-for-android-new-toolchain
[INFO]:    Unpacking pyjnius for armeabi-v7a
[INFO]:    -> running basename https://github.com/kiv...(and 28 more)
[INFO]:    -> directory context /home/kivy/beerctrl/src/.buildozer/android/platform/build/build/other_builds/pyjnius-python2-sdl/armeabi-v7a
[INFO]:    pyjnius is already unpacked, skipping
[INFO]:    <- directory context /home/kivy/beerctrl/src/.buildozer/android/platform/python-for-android-new-toolchain
[INFO]:    Unpacking twisted for armeabi-v7a
[INFO]:    -> running basename https://github.com/twi...(and 42 more)
[INFO]:    -> directory context /home/kivy/beerctrl/src/.buildozer/android/platform/build/build/other_builds/twisted-python2/armeabi-v7a
[INFO]:    twisted is already unpacked, skipping
[INFO]:    <- directory context /home/kivy/beerctrl/src/.buildozer/android/platform/python-for-android-new-toolchain
[INFO]:    -> running rm -rf /home/kivy/beerctrl/src...(and 96 more)
[INFO]:    -> running cp -a /home/kivy/beerctrl/src/...(and 217 more)
[INFO]:    Unpacking kivy for armeabi-v7a
[INFO]:    -> running basename https://github.com/kiv...(and 25 more)
[INFO]:    -> directory context /home/kivy/beerctrl/src/.buildozer/android/platform/build/build/other_builds/kivy-pygame-python2/armeabi-v7a

**Comment by inclement** [comment]
It looks like the unpacking of the downloaded Kivy bundle is just hanging. I'm not sure why that would happen.
What files are present in `/home/kivy/beerctrl/src/.buildozer/android/platform/build/build/other_builds/kivy-pygame-python2/armeabi-v7a`?

**Comment by NovotnyMCAT** [comment]
just:  kivy 1.10.0

**Comment by inclement** [comment]
Is that a folder? What's in that folder? Please post the exact output of `ls -lah`

**Comment by NovotnyMCAT** [comment]
the output for armea... folder is: 

kivy@kivy-VirtualBox:~/beerctrl/src/.buildozer/android/platform/build/build/other_builds/kivy-pygame-python2/armeabi-v7a$ ls -ah
.  ..  kivy-1.10.0

and for inside of the folder: 

kivy@kivy-VirtualBox:~/beerctrl/src/.buildozer/android/platform/build/build/other_builds/kivy-pygame-python2/armeabi-v7a/kivy-1.10.0$ ls -ah
.             AUTHORS   .gitattributes  kivy      MANIFEST.in  setup.py
..            doc       .github         LICENSE   README.md    .travis.yml
appveyor.yml  examples  .gitignore      Makefile  setup.cfg

**Comment by inclement** [comment]
I think this is fixed in buildozer master, please reopen if not.
