### ISSUE TITLE
App crashes on android but works fine in idle window using buildozer

### ISSUE THREAD

**Issue by utkarsh123bholu** [kivy/buildozer#675]
I am trying to make simple portscanner using nmap module. It works fine in my laptop but it crashes in my android phone after displaying launcher icon.
My main.py file is
[main.txt](https://github.com/kivy/buildozer/files/2089726/main.txt)

Buildozer spec file is
[buildozer.txt](https://github.com/kivy/buildozer/files/2089730/buildozer.txt)

Please help regarding this

**Comment by utkarsh123bholu** [comment]
How can I get nmap receipe...Is there any way to do it?

**Comment by utkarsh123bholu** [comment]
Just want to perform simple nmap scan on android using python..

**Comment by kuzeyron** [comment]
Better to ask for @inclement. He's more specialised than me with the recipes.
But I still wonder what your Device is trying to tell you.
Can you add the logs here?

**Comment by utkarsh123bholu** [comment]
06-11 17:06:08.345 10419 10870 I python  : [INFO   ] [Text        ] Provider: sdl2
06-11 17:06:08.350 10419 10870 I python  :  Traceback (most recent call last):
06-11 17:06:08.350 10419 10870 I python  :    File "/home/utkarsh/PycharmProjects/Test/.buildozer/android/app/main.py", line 15, in <module>
06-11 17:06:08.351 10419 10870 I python  :    File "/home/utkarsh/PycharmProjects/Test/.buildozer/android/platform/build/dists/test/private/lib/python2.7/site-packages/kivy/app.py", line 802, in run
06-11 17:06:08.351 10419 10870 I python  :    File "/home/utkarsh/PycharmProjects/Test/.buildozer/android/app/main.py", line 8, in build
06-11 17:06:08.352 10419 10870 I python  :  **AttributeError: 'module' object has no attribute 'PortScanner'**
06-11 17:06:08.379 10419 10870 I python  : Python for android ended.

**Comment by utkarsh123bholu** [comment]
This is some important part of logs...

**Comment by kuzeyron** [comment]
I guess it's only nmap api that's being packed. That means it leaves the nmap program out of the package.
You would need to ask some nmap peoples to help you with that.
I did a quick search on Google and it's needed to compile it for Android.
And the problem isn't Buildozer.

So, I believe we can't help you any further with this.

**Comment by utkarsh123bholu** [comment]
06-11 17:35:10.392 14485 14791 I python  :  Traceback (most recent call last):
06-11 17:35:10.393 14485 14791 I python  :    File "/home/utkarsh/PycharmProjects/Test/.buildozer/android/app/main.py", line 15, in <module>
06-11 17:35:10.394 14485 14791 I python  :    File "/home/utkarsh/PycharmProjects/Test/.buildozer/android/platform/build/dists/test/private/lib/python2.7/site-packages/kivy/app.py", line 802, in run
06-11 17:35:10.395 14485 14791 I python  :    File "/home/utkarsh/PycharmProjects/Test/.buildozer/android/app/main.py", line 8, in build
06-11 17:35:10.395 14485 14791 I python  :    File "/home/utkarsh/PycharmProjects/Test/.buildozer/android/platform/build/dists/test/private/lib/python2.7/site-packages/nmap/nmap.py", line 131, in __init__
06-11 17:35:10.396 14485 14791 I python  :  **nmap.nmap.PortScannerError: 'nmap program was not found in path. PATH is : /sbin:/system/sbin:/system/bin:/system/xbin:/vendor/bin:/vendor/xbin'
06-11 17:35:10.436 14485 14791 I python  : Python for android ended.**
06-11 17:35:10.441  2623  8379 D ActivityTrigger: ActivityTrigger activityPauseTrigger 
06-11 17:35:10.443 14485 14485 V PythonActivity: onPause()
06-11 17:35:10.443 14485 14485 V SDL     : onPause()
06-11 17:35:10.444 14485 14485 V SDL     : nativePause()
06-11 17:35:10.450  2623  4040 D ActivityTrigger: activityResumeTrigger: The activity in ApplicationInfo{95a4f61 com.android.launcher3} is now in focus and seems to be in full-screen mode

**Comment by utkarsh123bholu** [comment]
This is some more logs...

 But it is working in my laptop....only thing is not working in my phone..
if you can help something please help

**Comment by tito** [comment]
This has nothing to do with buildozer, nor python-for-android. The nmap library you're trying look like a pure python wrapper around "nmap" executable. It's not part of the nmap python library.

Either find a way to install nmap executable yourself on android, either try to find another library that would work by design on Android.
