### ISSUE TITLE
virtual machine does not compile apk Fails with errors

### ISSUE THREAD

**Issue by littlegreenbean33** [kivy/buildozer#677]
Hi,

I have tried to compile a simple apk without success witha fresh virtual machine. The one posted in kivy site.

First it complained that it was missing 32 bit libraries, so I decided to follow standard steps as per the documentation to install a buildozer afresh. 

It failed to compile never the less.

I installed dev branch, as per the instruction in readthedocs. Fails with same error.

This is the error

`Traceback (most recent call last):
      File "/usr/local/bin/buildozer", line 9, in <module>
        load_entry_point('buildozer', 'console_scripts', 'buildozer')()
      File "/home/kivy/alarma/buildozer/buildozer/scripts/client.py", line 13, in main
        Buildozer().run_command(sys.argv[1:])
      File "/home/kivy/alarma/buildozer/buildozer/__init__.py", line 1059, in run_command
        self.target.run_commands(args)
      File "/home/kivy/alarma/buildozer/buildozer/target.py", line 92, in run_commands
        func(args)
      File "/home/kivy/alarma/buildozer/buildozer/target.py", line 104, in cmd_debug
        self.buildozer.build()
      File "/home/kivy/alarma/buildozer/buildozer/__init__.py", line 212, in build
        self.target.build_package()
      File "/home/kivy/alarma/buildozer/buildozer/targets/android.py", line 828, in build_package
        copyfile(join(apk_dir, apk), join(self.buildozer.bin_dir, apk_dest))
      File "/usr/lib/python2.7/shutil.py", line 82, in copyfile
        with open(src, 'rb') as fsrc:`

I did apply the hack form @cdyangbo to no sucess.

Is this the right virtual machine ? is it the right version? Maybe a non working virtual machine was posted to the site by mistake?

**Comment by kuzeyron** [comment]
Hello! Can you make a list on how you created the VM and also every steps for the Buildozer?
The more info you have, the more we might are able to help!

**Comment by littlegreenbean33** [comment]
@kuzeyron  Apologies for my late reply.

I just use the stock VM posted in kivy site. First try, it  did not work ( lib32 missing).
 Reinstall v34 follow the three steps from readthedocs to reach the above issue.
Reinstall with dev version, same issue.

Browse the forums and there is apparently a hack already devised to solve this  issue. I was tempted to introduce it, but after later maintenance of the file, the number of the line where the changes had to be introduced was incorrect so I decided to stay put. I am too now to kivy to make such changes without loosing control of what happens.

My app is a simple 2 screen kv file with about 12 buttons, no processing.  Only  calls to urls in the server to perform some easy stuff.

Runs perfectly on linux, windows and android kivy launcher. I managed to find the app in a borked compile tree from a different machine I have, to no avail.

Sorry I am a bit helpless and after 2 weeks hardly trying to make this work, a bit frustrated. I can only spend time looking into details over the weekend. I will give it another try creating new virtual machines again from scratch.

Many Thanks.

JC

**Comment by littlegreenbean33** [comment]
OK, gave it another try. I can't replicate the same error. What I am not doing anymore is brining my buildozer.spec from my  local ( and possibly corrupted ) environment. I am generating it locally and retrofitting manual the changes. 

My application successfully make calls to https via urlrequest correctly.

Thanks.
