### ISSUE TITLE
Is there something like multiprocessing?

### ISSUE THREAD

**Issue by Davincible** [kivy/buildozer#685]
I've read online that the multiprocessing module doesn't work under Android, and that I should just use a simple tread. However, this makes the app unusable because it is doing way too much on one process. 

I have a kivy app which originally runs web scrapers in different processes. Is there any work around for running more intensive tasks alongside a kivy application on android?

**Comment by AndreMiras** [comment]
Not really buildozer related. You will have better chances taking a look at p4a services https://python-for-android.readthedocs.io/en/latest/services/
Also the mailing list or IRC is more appropriated for questions other the issue tracker will be a mess :/
