### ISSUE TITLE
Buildozer fails to run on Arch Linux ASCII codec issues

### ISSUE THREAD

**Issue by Huyston** [kivy/buildozer#686]
Hello,

When I pip install buildozer and use it in the command line, the following traceback is given:

`Traceback (most recent call last):
  File "/usr/bin/buildozer", line 11, in <module>
    load_entry_point('buildozer==0.34', 'console_scripts', 'buildozer')()
  File "/usr/lib/python3.6/site-packages/buildozer/scripts/client.py", line 13, in main
    Buildozer().run_command(sys.argv[1:])
  File "/usr/lib/python3.6/site-packages/buildozer/__init__.py", line 122, in __init__
    self.config.read(filename)
  File "/usr/lib/python3.6/configparser.py", line 697, in read
    self._read(fp, filename)
  File "/usr/lib/python3.6/configparser.py", line 1015, in _read
    for lineno, line in enumerate(fp, start=1):
  File "/usr/lib/python3.6/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc2 in position 1652: ordinal not in range(128)
`

However, I noted that buildozer is meant for python2 and modified the the first line of the file in /usr/bin/buildozer from:
#!/usr/bin/python
to:
#!/usr/bin/python2

After this modification, buildozer runs fine. This is because on Arch, the default python interpreter is the python3, not python2 as most linux distributions.

So, one suggestion to avoid versioning problems would be to always point to python2, instead of the default python interpreter of the system. Of course, making buildozer work in python3 would be even better, but maybe that's more work to do.

**Comment by Julian-O** [comment]
The codec issues seem to be a duplicate of #672.

The Python 2 versus Python 3 issues: Python 2 is no longer supported.

Closing as stale.
