### ISSUE TITLE
32-bit SDK installed on 64-bit system

### ISSUE THREAD

**Issue by sarimak** [kivy/buildozer#69]
buildozer android release
fails due to missing libstdc++6 required by aidl.

After consulting stackoverflow,
objdump -x /home/sarim/.buildozer/android/platform/android-sdk-21/platform-tools/aidl | grep NEED
shows that 32-bit libraries are required by the Android SDK.

Workaround: sudo apt-get install libc6:i386 libstdc++6:i386
(Ubuntu 13.10, 64-bit)

**Comment by nelson6e65** [comment]
How is this for Fedora?
