### ISSUE TITLE
Fail on build

### ISSUE THREAD

**Issue by matthew-nm** [kivy/buildozer#692]
I was finally able to get kivy working successfully on my Linux (Ubuntu 18.04) machine, and I'm now trying to use Buildozer to create an apk via the command `buildozer android debug deploy run`.

I am using the python3 version of kivy and as such I am using a specified NDK (crystax-ndk-10.3.2).

The output of the command is as follows,
[log.txt](https://github.com/kivy/buildozer/files/2172596/log.txt)

And the spec file is,
[buildozer.spec.txt](https://github.com/kivy/buildozer/files/2172600/buildozer.spec.txt)
Note that I specified `android.ndk_path = /opt/crystax-ndk-10.3.2` and `requirements = python3crystax==3.6,kivy`.

Thanks for any insight!

**Comment by AndreMiras** [comment]
Hi @matthew-nm, the error is a bit misleading, but I think it comes from your Cython installation.
For of Cython should not be installed in a virtual environment (annoying I know).
So what I do myself is to install it with `--user` flag so it doesn't mess up too much with my system, even though it's not as cleanly isolated as if it were installed in a venv.
Also could you share the installed python version you're using.
Please share the following outputs:
- `pip freeze`
- `cython --version`
- `which cython`

For instance I gave it a try within the Docker VM (modified for Ubuntu Bionic 18.04), APK with kivy works OK here.
```
(venv) root@dd67110dcb7f:/app/testapps# cython --version
Cython version 0.21
(venv) root@dd67110dcb7f:/app/testapps# which cython
/usr/local/bin/cython
(venv) root@dd67110dcb7f:/app/testapps#
```
And even though I'm in a venv, Cython is not installed here:
```
pip freeze
appdirs==1.4.3
colorama==0.3.9
Jinja2==2.10
MarkupSafe==1.0
pkg-resources==0.0.0
-e git+git@github.com:AndreMiras/python-for-android.git@8983db5e287ba6d609b00dd6bb81599b0a782097#egg=python_for_android
sh==1.12.14
six==1.11.0
```
Please come back with fresh news, I hope it helps.

**Comment by matthew-nm** [comment]
Hi again!
I recently cleaned up all my virtual envs, and I decided I'd try using Buildozer again. Here are the outputs you asked for above, but for this new setup:

`pip freeze`:
```
appdirs==1.4.3
asn1crypto==0.24.0
certifi==2018.8.13
cffi==1.11.5
chardet==3.0.4
click==6.7
colorama==0.3.9
conda==4.5.10
cryptography==2.2.2
cycler==0.10.0
Cython==0.28.5
docutils==0.14
flake8==3.5.0
greenlet==0.4.14
idna==2.6
Jinja2==2.10
kaptan==0.5.10
Kivy==1.11.0.dev0
Kivy-Garden==0.1.4
kiwisolver==1.0.1
libtmux==0.8.0
MarkupSafe==1.0
matplotlib==2.2.3
mccabe==0.6.1
mkl-fft==1.0.4
mkl-random==1.0.1
msgpack==0.5.6
neovim==0.2.6
numpy==1.15.0
pudb==2018.1
pycodestyle==2.3.1
pycosat==0.6.3
pycparser==2.18
pyflakes==1.6.0
Pygments==2.2.0
pyOpenSSL==18.0.0
pyparsing==2.2.0
PySocks==1.6.8
python-dateutil==2.7.3
pytz==2018.5
PyYAML==3.13
requests==2.18.4
rockstar-py==1.3.5
ruamel-yaml==0.15.37
sh==1.12.4
six==1.11.0
tmuxp==1.4.0
tornado==5.1
urllib3==1.22
urwid==2.0.1
```

`cython --version` & `which cython`:
```
Cython version 0.28.5
/home/matthew/miniconda3/bin/cython
```

Instead of having a separate Kivy virtual env, I used pip to install Kivy in my base Anaconda environment (python=3.6.5). I don't remember installing Cython, but it seems to be in there already. I tried `pip install --user cython`, but it said it was already installed so it didn't try to install it again. 

If this is still an issue, I can certainly remove Cython from my virtual env and try a --user install again.

And finally, here is the output from my latest attempt with Buildozer in the new setup. I think it gets farther this time! [build.log](https://github.com/kivy/buildozer/files/2320701/build.log)

**Comment by AndreMiras** [comment]
Indeed it's getting further. From the logs, your Python installation looks a bit messy, because I see references to both (host) python2 and python3, but I'm not sure.
Anyway it seems that you're pulling kivy 1.10.0 even though the last release is 1.10.1. I also realize your `buildozer.spec` is using the default branch (most likely the stable), I recommend you to change it to:
```
p4a.branch = master
```
Clean the env and give it another try.
Good luck!

**Comment by matthew-nm** [comment]
I've been getting farther and farther along, but I keep hitting stumbling blocks. I think part of it as to do with the fact that the Buildozer executable calls `#!/usr/bin/python`, which is python 2, and I'm trying to point everything toward python 3 on my system. 

I removed everything Kivy and Buildozer related for now, and eventually I will try again to set it up the right way from scratch.

Thanks for the help!

**Comment by AndreMiras** [comment]
Yes I can tell buildozer 2/3 could be a mess. Usually buildozer works with python3, but it needs to be installed from pip python3. However I usually run it from python2 because otherwise logs lines ending are a bit messy, I didn't investigate why.
So basically make sure it's uninstall `pip uninstall buildozer` and then install it with `python2 -m pip install buildozer` make sure the `bin` install location is in your path.

**Comment by inclement** [comment]
The buildozer executable should be generated by pip, and I think it uses the specific python version you installed it with. Is it possible you installed it with python2?

**Comment by matthew-nm** [comment]
Ah, understood.

Yes, it's entirely possible that I used my system's python2. I added a symlink for python3 in my $PATH recently, but this was almost certainly after originally installing Buildozer, where I had probably used python2.

**Comment by inclement** [comment]
Closing as stale, probably fixed in master.
