### ISSUE TITLE
Aidl not detected

### ISSUE THREAD

**Issue by Toothless204** [kivy/buildozer#694]
When trying to build an app using the command "buildozer android debug" I get this error:
```
Check configuration tokens
Ensure build layout
Check configuration tokens
Preparing build
Check requirements for android
Install platform
Apache ANT found at /home/toothless204/.buildozer/android/platform/apache-ant-1.9.4
Android SDK found at /home/toothless204/.buildozer/android/platform/android-sdk-20
Android NDK found at /home/toothless204/.buildozer/android/platform/android-ndk-r9c
Refresh Sources:
  Fetching https://dl-ssl.google.com/android/repository/addons_list-2.xml
  Fetched Add-ons List successfully
  Refresh Sources
  Fetching URL: https://dl-ssl.google.com/android/repository/repository-7.xml
Refresh Sources:
  Fetching URL: https://dl-ssl.google.com/android/repository/repository-7.xml
Refresh Sources:
  Fetching URL: https://dl-ssl.google.com/android/repository/repository-7.xml
Refresh Sources:
  Fetching URL: https://dl-ssl.google.com/android/repository/repository-7.xml
Packages available for installation or update: 0

Refresh Sources:
  Fetching https://dl-ssl.google.com/android/repository/addons_list-2.xml
  Fetched Add-ons List successfully
  Refresh Sources
  Fetching URL: https://dl-ssl.google.com/android/repository/repository-7.xml
Refresh Sources:
  Fetching URL: https://dl-ssl.google.com/android/repository/repository-7.xml
Packages available for installation or update: 0

Aidl not found, please install it.
```

I checked aidl is installed with apt and it says it is.

My machine is running Kubuntu 18.04 if it helps

**Comment by AndreMiras** [comment]
Weird, could you try a:
```sh
ls -l ~/.buildozer/android/platform/android-sdk-20/
```
And a:
```
find ~/.buildozer/android/platform/android-sdk-20/ -name aidl
```
Please share the command output of both, normally `aidl` should be under:
```
~/.buildozer/android/platform/android-sdk-20/build-tools/*/aidl
``` 
Also please increase your log level from `buildozer.spec` and share again the output of the `buildozer android debug`, it may give some very crucial information we're missing here.

**Comment by Toothless204** [comment]
The output of your first command is the following:

total 16
drwxr-x--- 2 toothless204 toothless204 4096 Jun 24  2012  add-ons
drwxr-x--- 2 toothless204 toothless204 4096 Jun 24  2012  platforms
-rw-r----- 1 toothless204 toothless204 1158 Jun 24  2012 'SDK Readme.txt'
drwxr-x--- 9 toothless204 toothless204 4096 Jun 24  2012  tools

Second command output nothing.

By the way does it help that there is no "build-tools" directory anywhere in ~/.buildozer

**Comment by ruegr** [comment]
Hi there,
i'm experiencing the same issue with Ubuntu 16.04.4 LTS, installed with WSL under Windows 10.
aidl is installed via apt.
I tried to create the missing "build-tools" folder by hand an linked the apt-aidl from /usr/bin/aidl to this location - but with no effect at all :-|
Last log-lines (with log level 2):
`  Fetching https://dl-ssl.google.com/android/repository/addons_list-2.xml
  Fetched Add-ons List successfully
  Refresh Sources
  Fetching URL: https://dl-ssl.google.com/android/repository/repository-7.xml
Refresh Sources:
  Fetching URL: https://dl-ssl.google.com/android/repository/repository-7.xml
Refresh Sources:
  Fetching URL: https://dl-ssl.google.com/android/repository/repository-7.xml
Refresh Sources:
  Fetching URL: https://dl-ssl.google.com/android/repository/repository-7.xml
Packages available for installation or update: 0

# Run '/home/###/.buildozer/android/platform/android-sdk-20/tools/android list sdk -u -e -a'
# Cwd /home/###/.buildozer/android/platform
b'Refresh Sources:\n'b'  Fetching https://dl-ssl.google.com/android/repository/addons_list-2.xml\n'b'  Fetched Add-ons List successfully\n'b'  Refresh Sources\n'b'  Fetching URL: https://dl-ssl.google.com/android/repository/repository-7.xml\n'b'Refresh Sources:\n'b'  Fetching URL: https://dl-ssl.google.com/android/repository/repository-7.xml\n'b'Packages available for installation or update: 0'b'\n'Refresh Sources:
  Fetching https://dl-ssl.google.com/android/repository/addons_list-2.xml
  Fetched Add-ons List successfully
  Refresh Sources
  Fetching URL: https://dl-ssl.google.com/android/repository/repository-7.xml
Refresh Sources:
  Fetching URL: https://dl-ssl.google.com/android/repository/repository-7.xml
Packages available for installation or update: 0

# Check that aidl can be executed
# Search for Aidl
# Aidl not found, please install it.`

**Comment by AndreMiras** [comment]
Thanks to both of you for logs, well that's weird seeing your SDK directory so empty.
I'm not 100% sure, but from what I recall, normally `~/.buildozer/android/platform/android-sdk-20/tools/bin/sdkmanager` should get called to download the rest at some stage.
For records, mine is:
```
ls -l ~/.buildozer/android/platform/android-sdk-20/
total 32
drwxr-x---  2 andre andre 4096 Jun 24  2012  add-ons
drwxr-xr-x  5 andre andre 4096 Jun 16 23:33  build-tools
drwxr-xr-x 10 andre andre 4096 Dec  4  2013  ndk-bundle
drwxr-x---  3 andre andre 4096 Apr 29 23:15  platforms
drwxr-xr-x  5 andre andre 4096 Jun 16 23:35  platform-tools
-rw-r-----  1 andre andre 1158 Jun 24  2012 'SDK Readme.txt'
drwxr-xr-x  2 andre andre 4096 Jun 16 23:33  temp
drwxr-xr-x 12 andre andre 4096 Jun 16 23:35  tools
```
Could you try to delete `~/.buildozer/` directory and run `buildozer android debug` again from scratch to see if this time it gets somehow created?
Also could you share your `buildozer.spec` files?
Last but not least, do you have experience with Docker? If you do that would be awesome if you could somehow reproduce your issue in Docker and share the Dockerfile since a reproduced bug is a solved bug :smile:

**Comment by Toothless204** [comment]
Deleting the .buildozer directory does not make a difference, the issue still occurs

Here is the spec file:
~~~~ [app]

# (str) Title of your application
title = 2048 with Kivy

# (str) Package name
package.name = kivy2048

# (str) Package domain (needed for android/ios packaging)
package.domain = com.meltingrocks

# (str) Source code where the main.py live
source.dir = .

# (list) Source files to include (let empty to include all the files)
source.include_exts = py,png,jpg,kv,atlas

# (list) Source files to exclude (let empty to not exclude anything)
#source.exclude_exts = spec

# (list) List of directory to exclude (let empty to not exclude anything)
source.exclude_dirs = libs

# (list) List of exclusions using pattern matching
source.exclude_patterns = README.md,screenshot.png

# (str) Application versioning (method 1)
version.regex = __version__ = '(.*)'
version.filename = %(source.dir)s/main.py

# (str) Application versioning (method 2)
# version = 1.2.0

# (list) Application requirements
requirements = kivy

# (str) Presplash of the application
presplash.filename = %(source.dir)s/data/presplash.png

# (str) Icon of the application
icon.filename = %(source.dir)s/data/icon.png

# (str) Supported orientation (one of landscape, portrait or all)
orientation = all

# (bool) Indicate if the application should be fullscreen or not
fullscreen = 0


#
# Android specific
#

# (list) Permissions
android.permissions = INTERNET

# (int) Android API to use
#android.api = 14

# (int) Minimum API required (8 = Android 2.2 devices)
android.minapi = 10

# (int) Android SDK version to use
#android.sdk = 21

# (str) Android NDK version to use
#android.ndk = 9c

# (bool) Use --private data storage (True) or --dir public storage (False)
#android.private_storage = True

# (str) Android NDK directory (if empty, it will be automatically downloaded.)
#android.ndk_path =

# (str) Android SDK directory (if empty, it will be automatically downloaded.)
#android.sdk_path = 

# (str) python-for-android git clone directory (if empty, it will be automatically cloned from github)
#android.p4a_dir =

# (str) Android entry point, default is ok for Kivy-based app
#android.entrypoint = org.renpy.android.PythonActivity

# (list) List of Java .jar files to add to the libs so that pyjnius can access
# their classes. Don't add jars that you do not need, since extra jars can slow
# down the build process. Allows wildcards matching, for example:
# OUYA-ODK/libs/*.jar
android.add_jars = libs/*.jar

# (list) List of Java files to add to the android project (can be java or a
# directory containing the files)
android.add_src = libs/basegameutils/java/

# (str) python-for-android branch to use, if not master, useful to try
# not yet merged features.
#android.branch = master

# (str) OUYA Console category. Should be one of GAME or APP
# If you leave this blank, OUYA support will not be enabled
#android.ouya.category = GAME

# (str) Filename of OUYA Console icon. It must be a 732x412 png image.
#android.ouya.icon.filename = %(source.dir)s/data/ouya_icon.png

# (str) XML file to include as an intent filters in <activity> tag
#android.manifest.intent_filters = 

# (list) Android additionnal libraries to copy into libs/armeabi
#android.add_libs_armeabi = libs/android/*.so

# (bool) Indicate whether the screen should stay on
# Don't forget to add the WAKE_LOCK permission if you set this to True
#android.wakelock = False

# (list) Android application meta-data to set (key=value format)
#android.meta_data =
#[app:android.meta_data]
#com.google.android.gms.version = @integer/google_play_services_version

# (list) Android library project to add (will be added in the
# project.properties automatically.)
android.library_references = libs/google-play-services_lib

#
# iOS specific
#

# (str) Name of the certificate to use for signing the debug version
# Get a list of available identities: buildozer ios list_identities
#ios.codesign.debug = "iPhone Developer: <lastname> <firstname> (<hexstring>)"

# (str) Name of the certificate to use for signing the release version
#ios.codesign.release = %(ios.codesign.debug)s


[buildozer]

# (int) Log level (0 = error only, 1 = info, 2 = debug (with command output))
log_level = 2


# -----------------------------------------------------------------------------
# List as sections
# 
# You can define all the "list" as [section:key].
# Each line will be considered as a option to the list.
# Let's take [app] / source.exclude_patterns.
# Instead of doing:
#
#     [app]
#     source.exclude_patterns = license,data/audio/*.wav,data/images/original/*
#
# This can be translated into:
#
#     [app:source.exclude_patterns]
#     license
#     data/audio/*.wav
#     data/images/original/*
#


# -----------------------------------------------------------------------------
# Profiles
#
# You can extend section / key with a profile
# For example, you want to deploy a demo version of your application without
# HD content. You could first change the title to add "(demo)" in the name
# and extend the excluded directories to remove the HD content.
#
#     [app@demo]
#     title = My Application (demo)
#
#     [app:source.exclude_patterns@demo]
#     images/hd/*
#
# Then, invoke the command line with the "demo" profile:
#
#     buildozer --profile demo android debug

[app:android.meta_data]
com.google.android.gms.version = @integer/google_play_services_version
com.google.android.gms.games.APP_ID = @string/app_id
com.google.android.gms.appstate.APP_ID = @string/app_id
~~~~ 

Will look into Docker to sort that for you

**Comment by Toothless204** [comment]
Docker version does not work either, build output can be found here:

https://pastebin.com/A947gLr9

Please note: Had to use pastebin as GitHub would not allow me to comment the whole thing

Here is the Dockerfile for buildozer i used:

~~~~
# Dockerfile for providing buildozer
# Build with:
# docker build --tag=buildozer .
# In order to give the container access to your current working directory
# it must be mounted using the --volume option.
# Run with (e.g. `buildozer --version`):
# docker run --volume "$(pwd)":/home/user/hostcwd buildozer --version
# Or for interactive shell:
# docker run --volume "$(pwd)":/home/user/hostcwd --entrypoint /bin/bash -it --rm buildozer
FROM ubuntu:18.04

ENV USER="user"
ENV HOME_DIR="/home/${USER}"
ENV WORK_DIR="${HOME_DIR}/hostcwd" \
    PATH="${HOME_DIR}/.local/bin:${PATH}"

# configures locale
RUN apt update -qq > /dev/null && \
    apt install -qq --yes --no-install-recommends \
    locales && \
    locale-gen en_US.UTF-8
ENV LANG="en_US.UTF-8" \
    LANGUAGE="en_US.UTF-8" \
    LC_ALL="en_US.UTF-8"

# installs system dependencies (required to setup all the tools)
RUN apt install -qq --yes --no-install-recommends \
    sudo python-pip python-setuptools file

# https://buildozer.readthedocs.io/en/latest/installation.html#android-on-ubuntu-18-04-64bit
RUN dpkg --add-architecture i386 && apt update -qq > /dev/null && \
	apt install -qq --yes --no-install-recommends \
	build-essential ccache git libncurses5:i386 libstdc++6:i386 libgtk2.0-0:i386 \
	libpangox-1.0-0:i386 libpangoxft-1.0-0:i386 libidn11:i386 python2.7 \
	python2.7-dev openjdk-8-jdk unzip zlib1g-dev zlib1g:i386

# prepares non root env
RUN useradd --create-home --shell /bin/bash ${USER}
# with sudo access and no password
RUN usermod -append --groups sudo ${USER}
RUN echo "%sudo ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers

USER ${USER}
WORKDIR ${WORK_DIR}

# installs buildozer and dependencies
RUN pip install --user Cython==0.25.2 buildozer
# calling buildozer adb command should trigger SDK/NDK first install and update
# but it requires a buildozer.spec file
RUN cd /tmp/ && buildozer init && buildozer android adb -- version && cd -
# fixes source and target JDK version, refs https://github.com/kivy/buildozer/issues/625
RUN sed s/'name="java.source" value="1.5"'/'name="java.source" value="7"'/ -i ${HOME_DIR}/.buildozer/android/platform/android-sdk-20/tools/ant/build.xml
RUN sed s/'name="java.target" value="1.5"'/'name="java.target" value="7"'/ -i ${HOME_DIR}/.buildozer/android/platform/android-sdk-20/tools/ant/build.xml

ENTRYPOINT ["buildozer"]
~~~~

Hope this is helpful

**Comment by Toothless204** [comment]
@AndreMiras what version of buildozer do you have, so I could try that version to see if it works?

**Comment by AndreMiras** [comment]
> Deleting the .buildozer directory does not make a difference, the issue still occurs

How annoying :disappointed: 

> Docker version does not work either, build output can be found here:

OK two things, first the error from the logs is way later in the process, so there's no aidl issue here at least.
Second is the error is super weird to me:
```
BUILD FAILED
/home/user/.buildozer/android/platform/android-sdk-20/tools/ant/build.xml:601: The following error occurred while executing this line:
/home/user/hostcwd/libs/google-play-services_lib/build.xml:90: Cannot find /home/tito/.buildozer/android/platform/android-sdk-21/tools/ant/build.xml imported from /home/user/hostcwd/libs/google-play-services_lib/build.xml
```
Why is it looking for `/home/tito` suddenly when the path was `/home/user` from the beginning?
You're using that [Dockerfile](https://github.com/kivy/buildozer/blob/84561c3/Dockerfile) correct?
I'll setup Docker on this laptop and give it a try, because this is super weird and the Docker image should not be broken that way.

> @AndreMiras what version of buildozer do you have, so I could try that version to see if it works?

I believe I use the last one.
```
pip freeze | grep buildozer
buildozer==0.34
$ buildozer --version
# Check configuration tokens
Buildozer 0.34
$ which buildozer
/home/andre/.local/bin/buildozer
```

**Comment by ruegr** [comment]
Unfortunately i'm not used to docker.
I'm using a fresh installation of buildozer with the following versions:
buildozer==0.35.dev0
Python 3.5.2

My buildozer.spec is very basic, just added the python3-requirements and change title / code-path:
```
[app]

# (str) Title of your application
title = CUSTOMTITLE

# (str) Package name
package.name = CUSTOMPACKAGENAME

# (str) Package domain (needed for android/ios packaging)
package.domain =  CUSTOMPACKAGEDOMAIN

# (str) Source code where the main.py live
source.dir = ../code

# (list) Source files to include (let empty to include all the files)
source.include_exts = py,png,jpg,kv,atlas

# (list) List of inclusions using pattern matching
#source.include_patterns = assets/*,images/*.png

# (list) Source files to exclude (let empty to not exclude anything)
#source.exclude_exts = spec

# (list) List of directory to exclude (let empty to not exclude anything)
#source.exclude_dirs = tests, bin

# (list) List of exclusions using pattern matching
#source.exclude_patterns = license,images/*/*.jpg

# (str) Application versioning (method 1)
version = 0.1

# (str) Application versioning (method 2)
# version.regex = __version__ = ['"](.*)['"]
# version.filename = %(source.dir)s/main.py

# (list) Application requirements
# comma seperated e.g. requirements = sqlite3,kivy
requirements = python3crystax, kivy

# (str) Custom source folders for requirements
# Sets custom source for any requirements with recipes
# requirements.source.kivy = ../../kivy

# (list) Garden requirements
#garden_requirements =

# (str) Presplash of the application
#presplash.filename = %(source.dir)s/data/presplash.png

# (str) Icon of the application
#icon.filename = %(source.dir)s/data/icon.png

# (str) Supported orientation (one of landscape, portrait or all)
orientation = all

# (list) List of service to declare
#services = NAME:ENTRYPOINT_TO_PY,NAME2:ENTRYPOINT2_TO_PY

#
# OSX Specific
#

#
# author = © Copyright Info

# change the major version of python used by the app
osx.python_version = 3

# Kivy version to use
osx.kivy_version = 1.9.1

#
# Android specific
#

# (bool) Indicate if the application should be fullscreen or not
fullscreen = 0

# (string) Presplash background color (for new android toolchain)
# Supported formats are: #RRGGBB #AARRGGBB or one of the following names:
# red, blue, green, black, white, gray, cyan, magenta, yellow, lightgray,
# darkgray, grey, lightgrey, darkgrey, aqua, fuchsia, lime, maroon, navy,
# olive, purple, silver, teal.
#android.presplash_color = #FFFFFF

# (list) Permissions
#android.permissions = INTERNET

# (int) Android API to use
#android.api = 19

# (int) Minimum API required
#android.minapi = 9

# (int) Android SDK version to use
#android.sdk = 20

# (str) Android NDK version to use
#android.ndk = 9c

# (bool) Use --private data storage (True) or --dir public storage (False)
#android.private_storage = True

# (str) Android NDK directory (if empty, it will be automatically downloaded.)
#android.ndk_path =

# (str) Android SDK directory (if empty, it will be automatically downloaded.)
#android.sdk_path =

# (str) ANT directory (if empty, it will be automatically downloaded.)
#android.ant_path =

# (bool) If True, then skip trying to update the Android sdk
# This can be useful to avoid excess Internet downloads or save time
# when an update is due and you just want to test/build your package
# android.skip_update = False

# (str) Android entry point, default is ok for Kivy-based app
#android.entrypoint = org.renpy.android.PythonActivity

# (list) Pattern to whitelist for the whole project
#android.whitelist =

# (str) Path to a custom whitelist file
#android.whitelist_src =

# (str) Path to a custom blacklist file
#android.blacklist_src =

# (list) List of Java .jar files to add to the libs so that pyjnius can access
# their classes. Don't add jars that you do not need, since extra jars can slow
# down the build process. Allows wildcards matching, for example:
# OUYA-ODK/libs/*.jar
#android.add_jars = foo.jar,bar.jar,path/to/more/*.jar

# (list) List of Java files to add to the android project (can be java or a
# directory containing the files)
#android.add_src =

# (list) Android AAR archives to add (currently works only with sdl2_gradle
# bootstrap)
#android.add_aars =

# (list) Gradle dependencies to add (currently works only with sdl2_gradle
# bootstrap)
#android.gradle_dependencies =

# (list) Java classes to add as activities to the manifest.
#android.add_activites = com.example.ExampleActivity

# (str) python-for-android branch to use, defaults to stable
#p4a.branch = stable

# (str) OUYA Console category. Should be one of GAME or APP
# If you leave this blank, OUYA support will not be enabled
#android.ouya.category = GAME

# (str) Filename of OUYA Console icon. It must be a 732x412 png image.
#android.ouya.icon.filename = %(source.dir)s/data/ouya_icon.png

# (str) XML file to include as an intent filters in <activity> tag
#android.manifest.intent_filters =

# (str) launchMode to set for the main activity
#android.manifest.launch_mode = standard

# (list) Android additionnal libraries to copy into libs/armeabi
#android.add_libs_armeabi = libs/android/*.so
#android.add_libs_armeabi_v7a = libs/android-v7/*.so
#android.add_libs_x86 = libs/android-x86/*.so
#android.add_libs_mips = libs/android-mips/*.so

# (bool) Indicate whether the screen should stay on
# Don't forget to add the WAKE_LOCK permission if you set this to True
#android.wakelock = False

# (list) Android application meta-data to set (key=value format)
#android.meta_data =

# (list) Android library project to add (will be added in the
# project.properties automatically.)
#android.library_references =

# (str) Android logcat filters to use
#android.logcat_filters = *:S python:D

# (bool) Copy library instead of making a libpymodules.so
#android.copy_libs = 1

# (str) The Android arch to build for, choices: armeabi-v7a, arm64-v8a, x86
android.arch = armeabi-v7a

#
# Python for android (p4a) specific
#

# (str) python-for-android git clone directory (if empty, it will be automatically cloned from github)
#p4a.source_dir =

# (str) The directory in which python-for-android should look for your own build recipes (if any)
#p4a.local_recipes =

# (str) Filename to the hook for p4a
#p4a.hook =

# (str) Bootstrap to use for android builds
# p4a.bootstrap = sdl2

# (int) port number to specify an explicit --port= p4a argument (eg for bootstrap flask)
#p4a.port =


#
# iOS specific
#

# (str) Path to a custom kivy-ios folder
#ios.kivy_ios_dir = ../kivy-ios

# (str) Name of the certificate to use for signing the debug version
# Get a list of available identities: buildozer ios list_identities
#ios.codesign.debug = "iPhone Developer: <lastname> <firstname> (<hexstring>)"

# (str) Name of the certificate to use for signing the release version
#ios.codesign.release = %(ios.codesign.debug)s


[buildozer]

# (int) Log level (0 = error only, 1 = info, 2 = debug (with command output))
log_level = 2

# (int) Display warning if buildozer is run as root (0 = False, 1 = True)
warn_on_root = 1

# (str) Path to build artifact storage, absolute or relative to spec file
# build_dir = ./.buildozer

# (str) Path to build output (i.e. .apk, .ipa) storage
# bin_dir = ./bin

#    -----------------------------------------------------------------------------
#    List as sections
#
#    You can define all the "list" as [section:key].
#    Each line will be considered as a option to the list.
#    Let's take [app] / source.exclude_patterns.
#    Instead of doing:
#
#[app]
#source.exclude_patterns = license,data/audio/*.wav,data/images/original/*
#
#    This can be translated into:
#
#[app:source.exclude_patterns]
#license
#data/audio/*.wav
#data/images/original/*
#


#    -----------------------------------------------------------------------------
#    Profiles
#
#    You can extend section / key with a profile
#    For example, you want to deploy a demo version of your application without
#    HD content. You could first change the title to add "(demo)" in the name
#    and extend the excluded directories to remove the HD content.
#
#[app@demo]
#title = My Application (demo)
#
#[app:source.exclude_patterns@demo]
#images/hd/*
#
#    Then, invoke the command line with the "demo" profile:
#
#buildozer --profile demo android debug

```

**Comment by Toothless204** [comment]
@AndreMiras do you think the issue could be related to python version, what version do you buildozer with?

**Comment by AndreMiras** [comment]
I confirm I didn't get this error on the Docker. So I'm not sure what's causing it, but that would be great to be able to reproduce in order to come with a fix.

**Comment by Toothless204** [comment]
Can I confirm the version of python 3 that it was designed to work with?

I'll spin up a VM and test older versions of python and ubuntu to see if it works

**Comment by AndreMiras** [comment]
Being able to reproduce in a VM would be great. Well in a light container e.g. Docker would be even better, because it's easier to share and tweak.
I'm not sure what Python version it was designed for, but the current Docker is running with stock Python from Ubuntu 18.04 which is 2.7, see https://github.com/kivy/buildozer/blob/84561c3/Dockerfile

**Comment by Toothless204** [comment]
On a new Ubuntu 18.04 server VM the build still fails but not because of aidl not being detected it fails during the actual build, I'm gonna try reinstalling my system and recreating my user account and see if that works

Here is a link to a download for the VM:

https://mega.nz/#!0ipBgLhK!KHrLhBSaUCPAN54eBnIIQsCpxp7jO0bLtoUuyHdVeLA

Username: toothless204
Password: toothless204

**Comment by OptimusGREEN** [comment]
try running android from the sdk tools folder and install any updates from the sdkmanager. might need to do it a couple of times to get all the updates. the build-tools and platform-tools folders should be installed.

worked for me anyway.

**Comment by Toothless204** [comment]
On my system the ~/.buildozer/android/platform/android-sdk-20 directory is almost completely empty here is its content

`` 
add-ons platforms 'SDK Readme.txt' tools
``

**Comment by OptimusGREEN** [comment]
Go into the tools folder.

**Comment by Toothless204** [comment]
Tried that and it doesn't say there are any updates

**Comment by Toothless204** [comment]
For some reason reinstalling my system fixed it, the sdk folder now has all the right stuff

Now getting errors about Cython will open a new issue about it

**Comment by jbsidis** [comment]
My name is Josué Carranza
The solution for the AIDL issue is easy to fix, the reason why this always happens is because the Google files (stored in buildozer or python for android) those files require a command to be able to ACCEPT THE LICENSE of Google, so if that did happen or did not happen that is why Aidl will always throws errors when you build your APK, I think that was done on Purpose, the Solution is:

1. Make sure your using an Official Release of Ubuntu, not a distribution, the Official Ubuntu, I worked with many distributions, and when I used the others and not Ubuntu oficial, it worked but later it did not work, so make sure you use Ubuntu, in Windows I think it will not work, why? Because windows was designed to do not develop your own programs easy
2. Delete all .buildozer directories manually (all of them) from the file explorer, you must delete at least 12 Gigabytes of data, if you delete less than that, then you are not deleting everything
3. Follow the process to Reinstall Buildozer and everything else
4. If you get the issue Aidl not found or similar you can run the following commands:
Read Carefully

The first error in Buildozer was,
* # Aidl not found, please install it *
Which was solved by checking if the folders located in * / home / josh / .buildozer / android / platform / android-sdk / build-tools / 29.0.2 / aidl * contained the file that is called "aidl" and which size is almost 1MB (993kb approx.), If that directory and that file exists, but still the error is * Aidl not found, please install it *, then it should be checked if in the directory * / home / josh / .buildozer / android / platform / android-sdk / build-tools / * there are subfolders with names like * "28.0.0" *, * "29.0.2" *, * "30.0.0_r3" * or something like that, in those folders check if in any There is a subfolder and within it a * .Install * file whose size is very little, less than 5kb, if it exists, they must * Delete it, * * Close the terminal and open it again, and start over

5. Repeat the process from the beginning Josué Carranza

If it is not working, Josué Carranza

Then do the following in the terminal


yes | sudo /home/josh/.buildozer/android/platform/android-sdk/tools/bin/sdkmanager --licenses

Remember to replace josh for your username, that one is mine (Josue Carranza)

If it does not work, then make sure about the following

Josué Carranza🐋🐋🐋🐋: 
python3.8 -m buildozer -v android debug
Josué Carranza🐋🐋🐋🐋: 
python3 -m buildozer -v android debug

Sometimes buildozer uses the wrong python, so you must be specific,

If still does not work, Re Install your Operative System completely, then Re Install Java, re install everything, 

But if after all, it is not working, and you give up, dont worry, it has to work Someday

**Comment by theo2bel** [comment]
> My name is Josué Carranza The solution for the AIDL issue is easy to fix, the reason why this always happens is because the Google files (stored in buildozer or python for android) those files require a command to be able to ACCEPT THE LICENSE of Google, so if that did happen or did not happen that is why Aidl will always throws errors when you build your APK, I think that was done on Purpose, the Solution is:
> 
> 1. Make sure your using an Official Release of Ubuntu, not a distribution, the Official Ubuntu, I worked with many distributions, and when I used the others and not Ubuntu oficial, it worked but later it did not work, so make sure you use Ubuntu, in Windows I think it will not work, why? Because windows was designed to do not develop your own programs easy
> 2. Delete all .buildozer directories manually (all of them) from the file explorer, you must delete at least 12 Gigabytes of data, if you delete less than that, then you are not deleting everything
> 3. Follow the process to Reinstall Buildozer and everything else
> 4. If you get the issue Aidl not found or similar you can run the following commands:
>    Read Carefully
> 
> The first error in Buildozer was,
> 
> * # Aidl not found, please install it *
> 
> Which was solved by checking if the folders located in * / home / josh / .buildozer / android / platform / android-sdk / build-tools / 29.0.2 / aidl * contained the file that is called "aidl" and which size is almost 1MB (993kb approx.), If that directory and that file exists, but still the error is * Aidl not found, please install it *, then it should be checked if in the directory * / home / josh / .buildozer / android / platform / android-sdk / build-tools / * there are subfolders with names like * "28.0.0" *, * "29.0.2" *, * "30.0.0_r3" * or something like that, in those folders check if in any There is a subfolder and within it a * .Install * file whose size is very little, less than 5kb, if it exists, they must * Delete it, * * Close the terminal and open it again, and start over
> 
> 5. Repeat the process from the beginning Josué Carranza
> 
> If it is not working, Josué Carranza
> 
> Then do the following in the terminal
> 
> yes | sudo /home/josh/.buildozer/android/platform/android-sdk/tools/bin/sdkmanager --licenses
> 
> Remember to replace josh for your username, that one is mine (Josue Carranza)
> 
> If it does not work, then make sure about the following
> 
> Josué Carranza🐋🐋🐋🐋: python3.8 -m buildozer -v android debug Josué Carranza🐋🐋🐋🐋: python3 -m buildozer -v android debug
> 
> Sometimes buildozer uses the wrong python, so you must be specific,
> 
> If still does not work, Re Install your Operative System completely, then Re Install Java, re install everything,
> 
> But if after all, it is not working, and you give up, dont worry, it has to work Someday

Is it supposed to work with wsl or other ubuntu from windows, having an official release of ubuntu ?

**Comment by Harjeeth4444** [comment]
Where do i run all the commands

**Comment by Ridola20** [comment]
How about we do it this way, someone should use or who uses a virtual environment should upload the directory to his or her kivy convertertion project so others can also use that same VM.........what do you guys think
