### ISSUE TITLE
App minimizes instantly after launching. 

### ISSUE THREAD

**Issue by Skyr3ndWolf** [kivy/buildozer#695]
Hello,

I'm a newbie to kivy programming. I built a simple app which will increment the number displayed on the button every time the button is clicked. I used the Buildozer VM provided by kivy to create the apk. The apk launches and immediately goes to the minimized app tray. Kindly help solve my Problem.

PS: I tried building one of the open source examples provided by kivy and the example app works as it should. I'll attach the main.py and the kv language file along with the apk generated.

[App.zip](https://github.com/kivy/buildozer/files/2216755/App.zip)

**Comment by inclement** [comment]
Your app crashed, use [adb logcat](https://kivy.org/docs/guide/android.html#debugging-your-application-on-the-android-platform) to debug the issue.
