### ISSUE TITLE
Bug or support request?

### ISSUE THREAD

**Issue by johnlarfour** [kivy/buildozer#708]
I post here but i don't know if is a bug or a support request. If it is not a bug I close this issue.
The problem is this: https://stackoverflow.com/questions/52058611/app-crash-with-kivy-and-bs4
I read on internet there are a lot of people there are this problem so, i don't know.
Sorry if I have not respected the rules

**Comment by tito** [comment]
Already reported at https://github.com/kivy/python-for-android/issues/1060
