### ISSUE TITLE
jar files can't package to the apk

### ISSUE THREAD

**Issue by zx013** [kivy/buildozer#709]
When I use lastest buildozer and lastest build-tools(28.0.2), it auto choose grade to pack. Then I set option android.add_jars in buildozer.spec, it seems not work well. The java class can not found in apk. So I check the code and add line in /root/.buildozer/android/platform/build/dists/zx013/templates/build.tmpl.gradle. And before run 'buildozer android release', I remove /root/.buildozer/android/platform/build/dists/zx013/build. After do this, the jar files can work well. So I think it maybe some mistake in it or I got the wrong way.

That is the build.tmpl.gradle I modify, compile fileTree(dir: 'src/main/libs', include: '*.jar') is the line I have added.
dependencies {
        compile fileTree(dir: 'src/main/libs', include: '*.jar')
        {%- for aar in aars %}
        compile(name: '{{ aar }}', ext: 'aar')
        {%- endfor -%}
        {%- if args.depends -%}
        {%- for depend in args.depends %}
        compile '{{ depend }}'
        {%- endfor %}
        {%- endif %}
}

**Comment by piropiro2018** [comment]
I am suffering from similar problems.

Have you successfully built and path to android.add_jars by setting path?
Please allow me to disclose it. (The jar file name is like a stub character)

**Comment by zx013** [comment]
Just modify  /root/.buildozer/android/platform/build/dists/zx013/templates/build.tmpl.gradle, android.add_jars will take effect.

**Comment by OptimusGREEN** [comment]
try this PR https://github.com/kivy/python-for-android/pull/1693 to see if it fixes the issue.

**Comment by AndreMiras** [comment]
Should be fixed with the PR linked above. Otherwise feel free to re-open with info
