### ISSUE TITLE
Python3Crystax instructions in README

### ISSUE THREAD

**Issue by tshirtman** [kivy/buildozer#710]
The instructions for python3 support on android don't seem up to date (https://github.com/kivy/buildozer/blob/master/README.rst#installing-buildozer-with-python3-support)
- I'm not sure point 1 is still relevant
- It seems the "android_new"->"android" change in the last bullet point was done without checking if the result still made sense, i think the whole point can be deleted.

**Comment by AndreMiras** [comment]
Good spot @tshirtman thanks! I made a pull request to address it and also tried to make the difference between host and target Python a bit more explicit.
 Please let me know what you think https://github.com/kivy/buildozer/pull/711
