### ISSUE TITLE
ndk_platform doesn't exist (when switching to API = 28)

### ISSUE THREAD

**Issue by Petar-Luketina** [kivy/buildozer#717]
Hello all,

I'm trying to get my app onto the app store. When I tried to upload the apk file, I got an error from Google stating that I need to set my app's API to 26+.

I installed an API of 28 and set it on my buildozer.spec file. I tried to run `buildozer android debug` to test the new API but it didn't work. I got this error in my terminal:

```
[INFO]:    Will compile for the following archs: armeabi-v7a
[INFO]:    Found Android API target in $ANDROIDAPI
[INFO]:    Available Android APIs are (19, 28)
[INFO]:    Requested API target 28 is available, continuing.
[INFO]:    Found NDK dir in $ANDROIDNDK
[INFO]:    Got NDK version from $ANDROIDNDKVER
[INFO]:    Using Google NDK r9c
[INFO]:    Found virtualenv at /home/pl/anaconda3/bin/virtualenv
[WARNING]: ndk_platform doesn't exist: /home/pl/.buildozer/android/platform/android-ndk-r9c/platforms/android-28/arch-arm
[INFO]:    Found the following toolchain versions: ['4.6', '4.8', 'clang3.3']
[INFO]:    Picking the latest gcc toolchain, here 4.8
[ERROR]:   python-for-android cannot continue; aborting
```
My buildozer spec file is:
```
android.api = 28
#android.minapi = 9
#android.sdk = 20
#android.ndk = 9c
#android.private_storage = True
#android.ndk_path =
#android.sdk_path =
#android.ant_path =
```
As seen above, I commented out many of the specs. I believe the error lies in one of those specs. If anyone has any clue as to what's going on, I would appreciate the help. (I'm using KivMob with Python 2.7, but I don't believe that's relevant to my issue.)

**Thank you in advance!**

**Comment by rnixx** [comment]
https://github.com/kivy/python-for-android/pull/1381 and https://github.com/kivy/python-for-android/issues/1219

**Comment by Petar-Luketina** [comment]
Wonderful! Thank you for the information. But it seems like there is still a strange error. Perhaps you might have some insight. I posted it to the link that you sent.

Here is the link of my problem: https://github.com/kivy/python-for-android/pull/1381#issuecomment-426182895

**Comment by Petar-Luketina** [comment]
Hey @bunmalik, I took the discussion to https://github.com/kivy/python-for-android/pull/1381. All the hurdles that I faced should be on there. If you have any problems, you can comment on there. Best of luck!
