### ISSUE TITLE
Error compiling Cython file:

### ISSUE THREAD

**Issue by franciscovargas** [kivy/buildozer#73]
This is my first time and my first time running buidozer and it prints the following error: 

```
Leaving ARM enviromnent
Call build_pyjnius
Entering in ARM enviromnent
Compiler found at /home/ligia/.buildozer/android/platform/android-ndk-r9/toolchains/arm-linux-androideabi-4.8/prebuilt/linux-x86_64/bin//arm-linux-androideabi-gcc
/home/ligia/kiv/.buildozer/android/platform/python-for-android/build/python-install/lib/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'install_requires'
  warnings.warn(msg)
running build_ext
building 'jnius' extension
creating build
creating build/temp.linux-x86_64-2.7
creating build/temp.linux-x86_64-2.7/jnius
arm-linux-androideabi-gcc -DANDROID -mandroid -fomit-frame-pointer --sysroot /home/ligia/.buildozer/android/platform/android-ndk-r9/platforms/android-14/arch-arm -DNDEBUG -DANDROID -mandroid -fomit-frame-pointer --sysroot /home/ligia/.buildozer/android/platform/android-ndk-r9/platforms/android-14/arch-arm -fPIC -I/home/ligia/kiv/.buildozer/android/platform/python-for-android/build/python-install/include/python2.7 -c jnius/jnius.c -o build/temp.linux-x86_64-2.7/jnius/jnius.o
arm-linux-androideabi-gcc: error: jnius/jnius.c: No such file or directory
arm-linux-androideabi-gcc: fatal error: no input files
compilation terminated.
error: command 'arm-linux-androideabi-gcc' failed with exit status 1

Error compiling Cython file:
------------------------------------------------------------
...

cdef class ByteArray:
    cdef LocalRef _jobject
    cdef long _size
    cdef jbyte *_buf
    cdef jbyte[:] _arr
              ^
------------------------------------------------------------

jnius/jnius_nativetypes.pxi:19:15: Expected an identifier or literal
/home/ligia/kiv/.buildozer/android/platform/python-for-android/build/python-install/lib/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'install_requires'
  warnings.warn(msg)
running build_ext
building 'jnius' extension
arm-linux-androideabi-gcc -DANDROID -mandroid -fomit-frame-pointer --sysroot /home/ligia/.buildozer/android/platform/android-ndk-r9/platforms/android-14/arch-arm -DNDEBUG -DANDROID -mandroid -fomit-frame-pointer --sysroot /home/ligia/.buildozer/android/platform/android-ndk-r9/platforms/android-14/arch-arm -fPIC -I/home/ligia/kiv/.buildozer/android/platform/python-for-android/build/python-install/include/python2.7 -c jnius/jnius.c -o build/temp.linux-x86_64-2.7/jnius/jnius.o
jnius/jnius.c:1:2: error: #error Do not use this file, it is the result of a failed Cython compilation.
 #error Do not use this file, it is the result of a failed Cython compilation.
  ^
error: command 'arm-linux-androideabi-gcc' failed with exit status 1
# Command failed: ./distribute.sh -m "kivy"
```

**Comment by jayece09** [comment]
I am having a similar problem. Though I installed cython using pip when I run 

" Packages missing: cython 
It might break the compilation, except if you installed thoses packages manually. "

and in later parts the error returned are:-
" building 'kivy.graphics.vertex_instructions' extension
ccache arm-linux-androideabi-gcc -DANDROID -mandroid -fomit-frame-pointer --sysroot /home/jp/.buildozer/android/platform/android-ndk-r9c/platforms/android-14/arch-arm -DNDEBUG -DANDROID -mandroid -fomit-frame-pointer --sysroot /home/jp/.buildozer/android/platform/android-ndk-r9c/platforms/android-14/arch-arm -fPIC -I/home/jp/.buildozer/android/platform/android-ndk-r9c/platforms/android-14/arch-arm/usr/include -I/home/jp/Desktop/test2/.buildozer/android/platform/python-for-android/build/python-install/include/python2.7 -c kivy/graphics/vertex_instructions.c -o build/temp.linux-x86_64-2.7/kivy/graphics/vertex_instructions.o
kivy/graphics/vertex_instructions.c:1:2: error: #error Do not use this file, it is the result of a failed Cython compilation.
 #error Do not use this file, it is the result of a failed Cython compilation.
  ^
 error: command 'ccache' failed with exit status 1

Error compiling Cython file:
------------------------------------------------------------
...
    #    perhaps tangents, what's the position on the spline for parameter t),
    #
    #    b) make that a superclass Spline,
    #    c) create BezierSpline subclass that does the computation

    cdef list _points
             ^
------------------------------------------------------------
" 

There are multiple instances of errors in same folder /kivy/graphics/vertex_instructions.
Whats can be probable reason?
 Are these errors two linked? When I checked for version of Cython jp@jp-VirtualBox:~/Desktop/test2$ cython -V
Cython version 0.21.2

And final error returned is:-
building 'kivy.graphics.vertex_instructions' extension
ccache arm-linux-androideabi-gcc -DANDROID -mandroid -fomit-frame-pointer --sysroot /home/jp/.buildozer/android/platform/android-ndk-r9c/platforms/android-14/arch-arm -DNDEBUG -DANDROID -mandroid -fomit-frame-pointer --sysroot /home/jp/.buildozer/android/platform/android-ndk-r9c/platforms/android-14/arch-arm -fPIC -I/home/jp/.buildozer/android/platform/android-ndk-r9c/platforms/android-14/arch-arm/usr/include -I/home/jp/Desktop/test2/.buildozer/android/platform/python-for-android/build/python-install/include/python2.7 -c kivy/graphics/vertex_instructions.c -o build/temp.linux-x86_64-2.7/kivy/graphics/vertex_instructions.o
kivy/graphics/vertex_instructions.c:1:2: error: #error Do not use this file, it is the result of a failed Cython compilation.
 #error Do not use this file, it is the result of a failed Cython compilation.
  ^
 error: command 'ccache' failed with exit status 1
#Command failed: ./distribute.sh -m "kivy" -d "myapp"

**Comment by vmisiko** [comment]
yes i have the same proboem, i have alrady installed cython , downgraded, upgraded nothing seems to be working
