### ISSUE TITLE
CrystaX no longer the preferred NDK for Python3

### ISSUE THREAD

**Issue by fherbine** [kivy/buildozer#745]
As per https://python-for-android.readthedocs.io/en/latest/buildoptions/ CrystaX NDK seems to be deprecated in favor of python3 requirement. Please reflect this on the README.md as @Cheaterman and me wasted quite some time on this :-)

Thanks in advance!

**Comment by tito** [comment]
I made some changes on the README, hope it will be ok.

**Comment by fherbine** [comment]
Thank you !
