### ISSUE TITLE
Documentation refers to `buildozer.ini`

### ISSUE THREAD

**Issue by tshirtman** [kivy/buildozer#748]
Documentation (in https://github.com/kivy/buildozer/blob/a6cd679c5c04dd3fd84b5741fb7721a4b24ef25b/buildozer/tools/packer/http/welcome/index.html#L74-L81) refers to a `buildozer.ini` file, which certainly should be `buildozer.spec`, that seems to be an error.

**Comment by MesaJonathan** [comment]
I'd like to try to contribute to this

**Comment by tshirtman** [comment]
Feel free to make a pull request with the change, if you see other things that are not up to date, it can also be a good opportunity to improve the current state.
