### ISSUE TITLE
Where are custom python-for-android recipes meant to go?

### ISSUE THREAD

**Issue by rantecki** [kivy/buildozer#76]
Tried adding a recipe in `.buildozer/android/platform/python-for-android/recipes` but buildozer runs a `git clean` on the python-for-android install before every build which deletes it.

What is the intended method for adding custom recipes?

**Comment by jtoledo1974** [comment]
Can you give an example of how to point the recipe to a different repository?

**Comment by AndreMiras** [comment]
@jtoledo1974 `p4a.local_recipes = ./src/python-for-android/recipes/` in `buildozer.spec`

**Comment by kamenchunathan** [comment]
Editing the local python for android repository and committing the changes also works just fine provided you don't run `buuldozer clean`
