### ISSUE TITLE
Error: minsdk argument does not match the api that is compiled against

### ISSUE THREAD

**Issue by Petar-Luketina** [kivy/buildozer#768]
I got this error while building a Python 2.7 android app:
```
WARNING: --minsdk argument does not match the api that is compiled against.
Only proceed if you know what you are doing, otherwise use --minsdk=21 or
recompile against api 19
You must pass --allow-minsdk-ndkapi-mismatch to build with --minsdk different to
the target NDK api from the build step
```
Does anyone have any insight into this error? Is `minsdk` new, because I never included it in my previous apps.  **Thank you in advance!**

Buildozer spec:
```ndk-api=21
# (int) Android API to use
android.api = 27
# (int) Minimum API required
android.minapi = 19
# (int) Android SDK version to use
android.sdk = 23
# (str) Android NDK version to use
android.ndk = 16b
```

**Comment by AndreMiras** [comment]
Yes things have changed recently in p4a.
Can you try `android.minapi = 21` as suggested in your spec and see if it works?

**Comment by Petar-Luketina** [comment]
Hey @AndreMiras , I get this error when I do that:

`IOError: [Errno 2] No such file or directory: u'/home/pl/Desktop/blind/.buildozer/android/platform/build/dists/blindgames1/build/outputs/apk/blindgames1-debug.apk'`

Any ideas?

**Comment by AndreMiras** [comment]
Yes I think these path have moved recently, see #1507
Try: `find .buildozer/ -name "*.apk"`

**Comment by Petar-Luketina** [comment]
I followed the steps, and I still go the same error. My apk is here:
`.buildozer/android/platform/build/dists/blindgames1/build/outputs/apk/debug/blindgames1-debug.apk`

What is this that's in #1507? `sudo p4aspaces cmd p4a-py2-api19-ndkbundle testbuild --p4a https://github.com/opacam/python-for-android/archive/fix-ci-gradle.zip`

Are you supposed to run this code to download his spec to test it?

**Comment by JonasT** [comment]
@AndreMiras for the last person having this issue, using `p4a clean-all` helped. So basically, building once with an older p4a version, then using a newer one on the existing distribution breaks this

**Comment by inclement** [comment]
Closing as apparently resolved.
