### ISSUE TITLE
 Command failed: ./distribute.sh -m "kivy" error message

### ISSUE THREAD

**Issue by Lakshmipathi** [kivy/buildozer#77]
When I try buildozer it fails with following message. Is it possible to auto-download this missing file (distribute.sh) and proceed? If not, how to resolve this manually ? 

$  buildozer android debug
    # Check configuration tokens
    # Ensure build layout
    # Check configuration tokens
    # Preparing build
    # Check requirements for android
    # Install platform
    # Apache ANT found at /root/.buildozer/android/platform/apache-ant-1.8.4  
    # Android SDK found at /root/.buildozer/android/platform/android-sdk-21
    # Android NDK found at /root/.buildozer/android/platform/android-ndk-r9
    # Android packages already installed.
    # Check application requirements
    # Compile platform
    # Command failed: ./distribute.sh -m "kivy"

btw, thanks for this nice tool :)

**Comment by Torxed** [comment]
Not intending to re-open, but for those Googling and ending up here.

Most common issue appears to be the lack of "unzip", especially coming from Arch Linux.
