### ISSUE TITLE
`default.spec` specifies `python3` but also incompatible NDK and API settings

### ISSUE THREAD

**Issue by brady-ds** [kivy/buildozer#770]
### Versions

* Python: 3.6.5
* OS: OpenSUSE 15.0
* Kivy: 1.10.1
* Cython: 0.28.3

### Description

When building with the requirements in `default.spec`, which include `python3`, Buildozer reports that the API settings are incompatible.  Furthermore, to support API versions past 19, the NDK version also has to be increased.  These increases should probably be the defaults so that Buildozer works out of the box.

### buildozer.spec

Commands:

```
$ sudo pip3 install --upgrade pyjnius pygame kivy buildozer
$ touch main.py
$ buildozer init
$ sudo sed -i 's|android/repository|android/ndk|' /usr/lib/python3.6/site-packages/buildozer/targets/android.py
$ sed -i -e 's/.*p4a.branch .*/p4a.branch = master/' buildozer.spec
$ buildozer -v android debug
```

(The first `sed` is to work around [buildozer 760](https://github.com/kivy/buildozer/issues/760) and friends.  The second `sed` is because the current `p4a` stable branch doesn't know the `python3` recipe, which also keeps Buildozer from working out of the box, but that's a separate problem.)

Spec file: just [the current default.spec](https://github.com/kivy/buildozer/blob/c4c632f7da9d636803aefe32065d1565c2a92d07/buildozer/default.spec) with that second `sed` command run on it to switch to `p4a.branch = master`.  (If a full copy is preferred, let me know, and I can paste it.)

### Logs

```
…
[ERROR]:   Build failed: Target ndk-api is 19, but the python3 recipe supports only 21+
# Command failed: /usr/bin/python3 -m pythonforandroid.toolchain create --dist_name=myapp --bootstrap=sdl2 --requirements=python3,kivy --arch armeabi-v7a --copy-libs --color=always --storage-dir="/home/cse/.buildozer/android/platform/build"
# 
# Buildozer failed to execute the last command
# The error might be hidden in the log above this error
# Please read the full log, and search for it before
# raising an issue with buildozer itself.
# In case of a bug report, please add a full log with log_level = 2
```

(To get past such errors, I must:
*   Change `android.api` to at least 21,
*   Change `android.minapi` to at least 21,
*   Increase `android.ndk` [I chose `17c`], and
*   Unpatch `android.py` because the NDK version is new enough that [buildozer 760](https://github.com/kivy/buildozer/issues/760) isn't an issue.)

**Comment by inclement** [comment]
Al the defaults have been updated in master now. Thanks.
