### ISSUE TITLE
Outdated Android NDK download URL in Kivy Virtual Machine

### ISSUE THREAD

**Issue by stroobandt** [kivy/buildozer#778]
Using the latest Version 2.0, released the 13 May 2017, of the Kivy virtual Machine
and after having updated `buildozer` to version `0.37` as required by the instructions,
the `buildozer` build process fails when trying to unzip `android-ndk-r9c-linux-x86_64.tar.bz2`

This happens because on old URL to the Android NDK is being referenced, namely:
<http://dl.google.com/android/repository/android-ndk-r9c-linux-x86_64.tar.bz2>

The issue can be circumvented by manually downloading the Android NDK using `wget` to the `~/.buildozer/android/platform/` directory but this time from the correct URL, namely:
<http://dl.google.com/android/ndk/android-ndk-r9c-linux-x86_64.tar.bz2>

This issue was [previously reported by other people on StackExchange](https://stackoverflow.com/a/42191418/2192488).

**Comment by brady-ds** [comment]
Based on [caver456's comment](https://github.com/kivy/buildozer/issues/760#issuecomment-445544664), would this be the same as #760?

**Comment by guysoft** [comment]
This also happends in master, Yes it looks like #760, same error here

**Comment by guysoft** [comment]
Fixed in master, this issue can be closed

**Comment by inclement** [comment]
Thanks @guysoft, we also now default to a much newer NDK.
