### ISSUE TITLE
Hello World impossible: checking whether the C compiler works... no

### ISSUE THREAD

**Issue by sergeLabo** [kivy/buildozer#785]
**With python 3.7**

I try to compile a simple Hello World with python 3.7 and wihout Crystax, 
the last error is:
- checking whether the C compiler works... no

Command failed: is with --ndk-api 9 **and** --ndk-api=21, but my buildozer is installed with master clone
with https://github.com/kivy/buildozer/commit/6b004f9778a312fed6908bceef605e4ef8c1efe9

STDOUT:
checking build system type... x86_64-pc-linux-gnu
checking host system type... arm-unknown-linux-androideabi
checking for python3.7... python3.7
checking for python interpreter for cross build... python3.7
checking for --enable-universalsdk... no
checking for --with-universal-archs... no
checking MACHDEP... checking for --without-gcc... no
checking for --with-icc... no
checking for arm-linux-androideabi-gcc... /media/sf_data/src_android/android-ndk-r15c/toolchains/llvm/prebuilt/linux-x86_64/bin/clang -target armv7a-none-linux-androideabi -gcc-toolchain /media/sf_data/src_android/android-ndk-r15c/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64
checking whether the C compiler works... no
configure: error: in `/home/serge/projets/hello-world/.buildozer/android/platform/build/build/other_builds/python3/armeabi-v7a__ndk_target_21/python3/android-build':
configure: error: C compiler cannot create executables

Command failed: /usr/bin/python3 -m pythonforandroid.toolchain create --dist_name=myapp --bootstrap=sdl2 --requirements=python3,kivy --ndk-api 9 --arch armeabi-v7a --copy-libs --color=always --storage-dir="/home/serge/projets/hello-world/.buildozer/android/platform/build" --ndk-api=21

**Part of buildozer.spec:**
requirements = python3,kivy
android.arch = armeabi-v7a
android.api = 24
android.sdk = 20
android.ndk = 15c
android.ndk_api = 21
android.ndk_path = /media/sf_data/src_android/android-ndk-r15c
android.sdk_path = /media/sf_data/src_android/android-sdk-20
p4a.branch = master

My project at [hello-world](https://github.com/sergeLabo/hello-world) with all files.

Any idea ?

**Comment by inclement** [comment]
I'm not sure what's wrong here, it may be something that has been fixed recently. If nothing else, it could be worth trying NDK 17c, which is the most well tested option right now.

I haven't seen any other issues like this recently so I'm closing as hopefully-fixed, but feel free to reopen if that isn't the case.

**Comment by dineshkidd** [comment]
How to solve this problem?

**Comment by tshirtman** [comment]
when you get the "C compiler cannot create executables" error, you should check the log file for that compilation, usually there are good hints of what caused the failure. Usually the path to this log file is displayed around the error in the buildozer log, or you can get it by running the command that buildozer says failed.

**Comment by dineshkidd** [comment]
> when you get the "C compiler cannot create executables" error, you should check the log file for that compilation, usually there are good hints of what caused the failure. Usually the path to this log file is displayed around the error in the buildozer log, or you can get it by running the command that buildozer says failed.

Checked log, can't figure out what it is. Here's the log.

This file contains any messages produced by compilers while
running configure, to aid debugging if configure makes a mistake.

It was created by libffi configure 3.3-rc0, which was
generated by GNU Autoconf 2.69.  Invocation command line was

  $ /home/dinesh/Desktop/sli/kivy/.buildozer/android/platform/build-armeabi-v7a/build/other_builds/libffi/armeabi-v7a__ndk_target_21/libffi/configure --host=arm-linux-androideabi --prefix=/home/dinesh/Desktop/sli/kivy/.buildozer/android/platform/build-armeabi-v7a/build/other_builds/libffi/armeabi-v7a__ndk_target_21/libffi --disable-builddir --enable-shared

## --------- ##
## Platform. ##
## --------- ##

hostname = pop-os
uname -m = x86_64
uname -r = 5.4.0-7634-generic
uname -s = Linux
uname -v = #38~1592497129~20.04~9a1ea2e-Ubuntu SMP Fri Jun 19 22:43:37 UTC 

/usr/bin/uname -p = x86_64
/bin/uname -X     = unknown

/bin/arch              = x86_64
/usr/bin/arch -k       = unknown
/usr/convex/getsysinfo = unknown
/usr/bin/hostinfo      = unknown
/bin/machine           = unknown
/usr/bin/oslevel       = unknown
/bin/universe          = unknown

PATH: /home/dinesh/.buildozer/android/platform/android-ndk-r19c/toolchains/llvm/prebuilt/linux-x86_64/bin
PATH: /home/dinesh/.buildozer/android/platform/android-ndk-r19c/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86/bin/
PATH: /home/dinesh/.buildozer/android/platform/android-ndk-r19c/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/bin/
PATH: /home/dinesh/.buildozer/android/platform/android-ndk-r19c
PATH: /home/dinesh/.buildozer/android/platform/android-sdk/tools
PATH: /home/dinesh/.buildozer/android/platform/apache-ant-1.9.4/bin
PATH: /home/dinesh/.local/bin
PATH: /usr/local/sbin
PATH: /usr/local/bin
PATH: /usr/sbin
PATH: /usr/bin
PATH: /sbin
PATH: /bin
PATH: /usr/games
PATH: /usr/local/games
PATH: /snap/bin


## ----------- ##
## Core tests. ##
## ----------- ##

configure:2700: checking build system type
configure:2714: result: x86_64-pc-linux-gnu
configure:2734: checking host system type
configure:2747: result: arm-unknown-linux-androideabi
configure:2767: checking target system type
configure:2780: result: arm-unknown-linux-androideabi
configure:2877: checking for gsed
configure:2908: result: sed
configure:2936: checking for a BSD-compatible install
configure:3004: result: /usr/bin/install -c
configure:3015: checking whether build environment is sane
configure:3070: result: yes
configure:3124: checking for arm-linux-androideabi-strip
configure:3151: result: arm-linux-androideabi-strip --strip-unneeded
configure:3216: checking for a thread-safe mkdir -p
configure:3255: result: /usr/bin/mkdir -p
configure:3262: checking for gawk
configure:3292: result: no
configure:3262: checking for mawk
configure:3278: found /usr/bin/mawk
configure:3289: result: mawk
configure:3300: checking whether make -j8 sets $(MAKE)
configure:3322: result: yes
configure:3351: checking whether make -j8 supports nested variables
configure:3368: result: yes
configure:3513: checking for arm-linux-androideabi-gcc
configure:3540: result: /home/dinesh/.buildozer/android/platform/android-ndk-r19c/toolchains/llvm/prebuilt/linux-x86_64/bin/clang -target armv7a-linux-androideabi21 -fomit-frame-pointer -march=armv7-a -mfloat-abi=softfp -mfpu=vfp -mthumb -fPIC
configure:3809: checking for C compiler version
configure:3818: /home/dinesh/.buildozer/android/platform/android-ndk-r19c/toolchains/llvm/prebuilt/linux-x86_64/bin/clang -target armv7a-linux-androideabi21 -fomit-frame-pointer -march=armv7-a -mfloat-abi=softfp -mfpu=vfp -mthumb -fPIC --version >&5
/home/dinesh/Desktop/sli/kivy/.buildozer/android/platform/build-armeabi-v7a/build/other_builds/libffi/armeabi-v7a__ndk_target_21/libffi/configure: line 3820: /home/dinesh/.buildozer/android/platform/android-ndk-r19c/toolchains/llvm/prebuilt/linux-x86_64/bin/clang: Permission denied
configure:3829: $? = 126
configure:3818: /home/dinesh/.buildozer/android/platform/android-ndk-r19c/toolchains/llvm/prebuilt/linux-x86_64/bin/clang -target armv7a-linux-androideabi21 -fomit-frame-pointer -march=armv7-a -mfloat-abi=softfp -mfpu=vfp -mthumb -fPIC -v >&5
/home/dinesh/Desktop/sli/kivy/.buildozer/android/platform/build-armeabi-v7a/build/other_builds/libffi/armeabi-v7a__ndk_target_21/libffi/configure: line 3820: /home/dinesh/.buildozer/android/platform/android-ndk-r19c/toolchains/llvm/prebuilt/linux-x86_64/bin/clang: Permission denied
configure:3829: $? = 126
configure:3818: /home/dinesh/.buildozer/android/platform/android-ndk-r19c/toolchains/llvm/prebuilt/linux-x86_64/bin/clang -target armv7a-linux-androideabi21 -fomit-frame-pointer -march=armv7-a -mfloat-abi=softfp -mfpu=vfp -mthumb -fPIC -V >&5
/home/dinesh/Desktop/sli/kivy/.buildozer/android/platform/build-armeabi-v7a/build/other_builds/libffi/armeabi-v7a__ndk_target_21/libffi/configure: line 3820: /home/dinesh/.buildozer/android/platform/android-ndk-r19c/toolchains/llvm/prebuilt/linux-x86_64/bin/clang: Permission denied
configure:3829: $? = 126
configure:3818: /home/dinesh/.buildozer/android/platform/android-ndk-r19c/toolchains/llvm/prebuilt/linux-x86_64/bin/clang -target armv7a-linux-androideabi21 -fomit-frame-pointer -march=armv7-a -mfloat-abi=softfp -mfpu=vfp -mthumb -fPIC -qversion >&5
/home/dinesh/Desktop/sli/kivy/.buildozer/android/platform/build-armeabi-v7a/build/other_builds/libffi/armeabi-v7a__ndk_target_21/libffi/configure: line 3820: /home/dinesh/.buildozer/android/platform/android-ndk-r19c/toolchains/llvm/prebuilt/linux-x86_64/bin/clang: Permission denied
configure:3829: $? = 126
configure:3849: checking whether the C compiler works
configure:3871: /home/dinesh/.buildozer/android/platform/android-ndk-r19c/toolchains/llvm/prebuilt/linux-x86_64/bin/clang -target armv7a-linux-androideabi21 -fomit-frame-pointer -march=armv7-a -mfloat-abi=softfp -mfpu=vfp -mthumb -fPIC -target armv7a-linux-androideabi21 -fomit-frame-pointer -march=armv7-a -mfloat-abi=softfp -mfpu=vfp -mthumb -fPIC -DANDROID -D__ANDROID_API__=21 -I/home/dinesh/.buildozer/android/platform/android-ndk-r19c/sysroot/usr/include/arm-linux-androideabi -I/home/dinesh/Desktop/sli/kivy/.buildozer/android/platform/build-armeabi-v7a/build/python-installs/myapp/include/python3.8   -L/home/dinesh/Desktop/sli/kivy/.buildozer/android/platform/build-armeabi-v7a/build/libs_collections/myapp/armeabi-v7a conftest.c  >&5
/home/dinesh/Desktop/sli/kivy/.buildozer/android/platform/build-armeabi-v7a/build/other_builds/libffi/armeabi-v7a__ndk_target_21/libffi/configure: line 3873: /home/dinesh/.buildozer/android/platform/android-ndk-r19c/toolchains/llvm/prebuilt/linux-x86_64/bin/clang: Permission denied
configure:3875: $? = 126
configure:3913: result: no
configure: failed program was:
| /* confdefs.h */
| #define PACKAGE_NAME "libffi"
| #define PACKAGE_TARNAME "libffi"
| #define PACKAGE_VERSION "3.3-rc0"
| #define PACKAGE_STRING "libffi 3.3-rc0"
| #define PACKAGE_BUGREPORT "http://github.com/libffi/libffi/issues"
| #define PACKAGE_URL ""
| #define PACKAGE "libffi"
| #define VERSION "3.3-rc0"
| /* end confdefs.h.  */
| 
| int
| main ()
| {
| 
|   ;
|   return 0;
| }
configure:3918: error: in `/home/dinesh/Desktop/sli/kivy/.buildozer/android/platform/build-armeabi-v7a/build/other_builds/libffi/armeabi-v7a__ndk_target_21/libffi':
configure:3920: error: C compiler cannot create executables
See `config.log' for more details

## ---------------- ##
## Cache variables. ##
## ---------------- ##

ac_cv_build=x86_64-pc-linux-gnu
ac_cv_env_CCASFLAGS_set=
ac_cv_env_CCASFLAGS_value=
ac_cv_env_CCAS_set=
ac_cv_env_CCAS_value=
ac_cv_env_CPPFLAGS_set=set
ac_cv_env_CPPFLAGS_value='-DANDROID -D__ANDROID_API__=21 -I/home/dinesh/.buildozer/android/platform/android-ndk-r19c/sysroot/usr/include/arm-linux-androideabi -I/home/dinesh/Desktop/sli/kivy/.buildozer/android/platform/build-armeabi-v7a/build/python-installs/myapp/include/python3.8'
ac_cv_env_CPP_set=
ac_cv_env_CPP_value=
ac_cv_env_CXXCPP_set=
ac_cv_env_CXXCPP_value=
ac_cv_env_LT_SYS_LIBRARY_PATH_set=
ac_cv_env_LT_SYS_LIBRARY_PATH_value=
ac_cv_env_build_alias_set=
ac_cv_env_build_alias_value=
ac_cv_env_host_alias_set=set
ac_cv_env_host_alias_value=arm-linux-androideabi
ac_cv_env_target_alias_set=
ac_cv_env_target_alias_value=
ac_cv_host=arm-unknown-linux-androideabi
ac_cv_path_ax_enable_builddir_sed=sed
ac_cv_path_install='/usr/bin/install -c'
ac_cv_path_mkdir=/usr/bin/mkdir
ac_cv_prog_AWK=mawk
ac_cv_prog_CC='/home/dinesh/.buildozer/android/platform/android-ndk-r19c/toolchains/llvm/prebuilt/linux-x86_64/bin/clang -target armv7a-linux-androideabi21 -fomit-frame-pointer -march=armv7-a -mfloat-abi=softfp -mfpu=vfp -mthumb -fPIC'
ac_cv_prog_STRIP='arm-linux-androideabi-strip --strip-unneeded'
ac_cv_prog_make_make_set=yes
ac_cv_target=arm-unknown-linux-androideabi
am_cv_make_support_nested_variables=yes

## ----------------- ##
## Output variables. ##
## ----------------- ##

ACLOCAL='${SHELL} /home/dinesh/Desktop/sli/kivy/.buildozer/android/platform/build-armeabi-v7a/build/other_builds/libffi/armeabi-v7a__ndk_target_21/libffi/missing aclocal-1.16'
ALLOCA=''
AMDEPBACKSLASH=''
AMDEP_FALSE=''
AMDEP_TRUE=''
AMTAR='$${TAR-tar}'
AM_BACKSLASH='\'
AM_DEFAULT_V='$(AM_DEFAULT_VERBOSITY)'
AM_DEFAULT_VERBOSITY='1'
AM_LTLDFLAGS=''
AM_RUNTESTFLAGS=''
AM_V='$(V)'
AR='arm-linux-androideabi-ar'
AUTOCONF='${SHELL} /home/dinesh/Desktop/sli/kivy/.buildozer/android/platform/build-armeabi-v7a/build/other_builds/libffi/armeabi-v7a__ndk_target_21/libffi/missing autoconf'
AUTOHEADER='${SHELL} /home/dinesh/Desktop/sli/kivy/.buildozer/android/platform/build-armeabi-v7a/build/other_builds/libffi/armeabi-v7a__ndk_target_21/libffi/missing autoheader'
AUTOMAKE='${SHELL} /home/dinesh/Desktop/sli/kivy/.buildozer/android/platform/build-armeabi-v7a/build/other_builds/libffi/armeabi-v7a__ndk_target_21/libffi/missing automake-1.16'
AWK='mawk'
BUILD_DOCS_FALSE=''
BUILD_DOCS_TRUE=''
CC='/home/dinesh/.buildozer/android/platform/android-ndk-r19c/toolchains/llvm/prebuilt/linux-x86_64/bin/clang -target armv7a-linux-androideabi21 -fomit-frame-pointer -march=armv7-a -mfloat-abi=softfp -mfpu=vfp -mthumb -fPIC'
CCAS=''
CCASDEPMODE=''
CCASFLAGS=''
CCDEPMODE=''
CFLAGS='-target armv7a-linux-androideabi21 -fomit-frame-pointer -march=armv7-a -mfloat-abi=softfp -mfpu=vfp -mthumb -fPIC'
CPP=''
CPPFLAGS='-DANDROID -D__ANDROID_API__=21 -I/home/dinesh/.buildozer/android/platform/android-ndk-r19c/sysroot/usr/include/arm-linux-androideabi -I/home/dinesh/Desktop/sli/kivy/.buildozer/android/platform/build-armeabi-v7a/build/python-installs/myapp/include/python3.8'
CXX='/home/dinesh/.buildozer/android/platform/android-ndk-r19c/toolchains/llvm/prebuilt/linux-x86_64/bin/clang++ -target armv7a-linux-androideabi21 -fomit-frame-pointer -march=armv7-a -mfloat-abi=softfp -mfpu=vfp -mthumb -fPIC'
CXXCPP=''
CXXDEPMODE=''
CXXFLAGS='-target armv7a-linux-androideabi21 -fomit-frame-pointer -march=armv7-a -mfloat-abi=softfp -mfpu=vfp -mthumb -fPIC'
CYGPATH_W='echo'
DEFS=''
DEPDIR=''
DLLTOOL=''
DSYMUTIL=''
DUMPBIN=''
ECHO_C=''
ECHO_N='-n'
ECHO_T=''
EGREP=''
EXEEXT=''
FFI_DEBUG_FALSE=''
FFI_DEBUG_TRUE=''
FFI_EXEC_TRAMPOLINE_TABLE=''
FFI_EXEC_TRAMPOLINE_TABLE_FALSE=''
FFI_EXEC_TRAMPOLINE_TABLE_TRUE=''
FGREP=''
GREP=''
HAVE_LONG_DOUBLE=''
HAVE_LONG_DOUBLE_VARIANT=''
INSTALL_DATA='${INSTALL} -m 644'
INSTALL_PROGRAM='${INSTALL}'
INSTALL_SCRIPT='${INSTALL}'
INSTALL_STRIP_PROGRAM='$(install_sh) -c -s'
LD='arm-linux-androideabi-ld'
LDFLAGS='  -L/home/dinesh/Desktop/sli/kivy/.buildozer/android/platform/build-armeabi-v7a/build/libs_collections/myapp/armeabi-v7a'
LIBFFI_BUILD_VERSIONED_SHLIB_FALSE=''
LIBFFI_BUILD_VERSIONED_SHLIB_GNU_FALSE=''
LIBFFI_BUILD_VERSIONED_SHLIB_GNU_TRUE=''
LIBFFI_BUILD_VERSIONED_SHLIB_SUN_FALSE=''
LIBFFI_BUILD_VERSIONED_SHLIB_SUN_TRUE=''
LIBFFI_BUILD_VERSIONED_SHLIB_TRUE=''
LIBOBJS=''
LIBS=''
LIBTOOL=''
LIPO=''
LN_S=''
LTLIBOBJS=''
LT_SYS_LIBRARY_PATH=''
MAINT=''
MAINTAINER_MODE_FALSE=''
MAINTAINER_MODE_TRUE=''
MAKEINFO='${SHELL} /home/dinesh/Desktop/sli/kivy/.buildozer/android/platform/build-armeabi-v7a/build/other_builds/libffi/armeabi-v7a__ndk_target_21/libffi/missing makeinfo'
MANIFEST_TOOL=''
MKDIR_P='/usr/bin/mkdir -p'
NM='arm-linux-androideabi-nm'
NMEDIT=''
OBJDUMP=''
OBJEXT=''
OPT_LDFLAGS=''
OTOOL64=''
OTOOL=''
PACKAGE='libffi'
PACKAGE_BUGREPORT='http://github.com/libffi/libffi/issues'
PACKAGE_NAME='libffi'
PACKAGE_STRING='libffi 3.3-rc0'
PACKAGE_TARNAME='libffi'
PACKAGE_URL=''
PACKAGE_VERSION='3.3-rc0'
PATH_SEPARATOR=':'
PRTDIAG=''
RANLIB='arm-linux-androideabi-ranlib'
SECTION_LDFLAGS=''
SED=''
SET_MAKE=''
SHELL='/bin/bash'
STRIP='arm-linux-androideabi-strip --strip-unneeded'
TARGET='arm-unknown-linux-androideabi'
TARGETDIR=''
TARGET_OBJ=''
TESTSUBDIR_FALSE=''
TESTSUBDIR_TRUE=''
VERSION='3.3-rc0'
ac_ct_AR=''
ac_ct_CC=''
ac_ct_CXX=''
ac_ct_DUMPBIN=''
am__EXEEXT_FALSE=''
am__EXEEXT_TRUE=''
am__fastdepCCAS_FALSE=''
am__fastdepCCAS_TRUE=''
am__fastdepCC_FALSE=''
am__fastdepCC_TRUE=''
am__fastdepCXX_FALSE=''
am__fastdepCXX_TRUE=''
am__include=''
am__isrc=''
am__leading_dot='.'
am__nodep=''
am__quote=''
am__tar='$${TAR-tar} chof - "$$tardir"'
am__untar='$${TAR-tar} xf -'
ax_enable_builddir_sed='sed'
bindir='${exec_prefix}/bin'
build='x86_64-pc-linux-gnu'
build_alias=''
build_cpu='x86_64'
build_os='linux-gnu'
build_vendor='pc'
datadir='${datarootdir}'
datarootdir='${prefix}/share'
docdir='${datarootdir}/doc/${PACKAGE_TARNAME}'
dvidir='${docdir}'
exec_prefix='NONE'
host='arm-unknown-linux-androideabi'
host_alias='arm-linux-androideabi'
host_cpu='arm'
host_os='linux-androideabi'
host_vendor='unknown'
htmldir='${docdir}'
includedir='${prefix}/include'
infodir='${datarootdir}/info'
install_sh='${SHELL} /home/dinesh/Desktop/sli/kivy/.buildozer/android/platform/build-armeabi-v7a/build/other_builds/libffi/armeabi-v7a__ndk_target_21/libffi/install-sh'
libdir='${exec_prefix}/lib'
libexecdir='${exec_prefix}/libexec'
localedir='${datarootdir}/locale'
localstatedir='${prefix}/var'
mandir='${datarootdir}/man'
mkdir_p='$(MKDIR_P)'
oldincludedir='/usr/include'
pdfdir='${docdir}'
prefix='/home/dinesh/Desktop/sli/kivy/.buildozer/android/platform/build-armeabi-v7a/build/other_builds/libffi/armeabi-v7a__ndk_target_21/libffi'
program_transform_name='s,x,x,'
psdir='${docdir}'
runstatedir='${localstatedir}/run'
sbindir='${exec_prefix}/sbin'
sharedstatedir='${prefix}/com'
sys_symbol_underscore=''
sysconfdir='${prefix}/etc'
target='arm-unknown-linux-androideabi'
target_alias='arm-linux-androideabi'
target_cpu='arm'
target_os='linux-androideabi'
target_vendor='unknown'
toolexecdir=''
toolexeclibdir=''

## ----------- ##
## confdefs.h. ##
## ----------- ##

/* confdefs.h */
#define PACKAGE_NAME "libffi"
#define PACKAGE_TARNAME "libffi"
#define PACKAGE_VERSION "3.3-rc0"
#define PACKAGE_STRING "libffi 3.3-rc0"
#define PACKAGE_BUGREPORT "http://github.com/libffi/libffi/issues"
#define PACKAGE_URL ""
#define PACKAGE "libffi"
#define VERSION "3.3-rc0"

configure: exit 77

**Comment by ntaraujo** [comment]
I'm having this issue right now with Python 3.8.6 in a WSL distro.
A simple hello world and default buildozer.spec.

```
STDOUT:
checking build system type... x86_64-pc-linux-gnu
checking host system type... arm-unknown-linux-androideabi
checking for python3.8... python3.8
checking for python interpreter for cross build... python3.8
checking for --enable-universalsdk... no
checking for --with-universal-archs... no
checking MACHDEP... "linux"
checking for arm-linux-androideabi-gcc... /home/ke/.buildozer/android/platform/android-ndk-r19c/toolchains/llvm/prebuilt/linux-x86_64/bin/armv7a-linux-androideabi21-clang
checking whether the C compiler works... no
configure: error: in `/mnt/c/Users/Nathan/Documents/GitHub/kivy-easier/dev/kivy-test/.buildozer/android/platform/build-armeabi-v7a/build/other_builds/python3/armeabi-v7a__ndk_target_21/python3/android-build':
configure: error: C compiler cannot create executables
See `config.log' for more details
```

I even don't know where `config.log` is. Where is it?

If it was solved, PLEASE how?

Thanks in advance
