### ISSUE TITLE
BUG,DOC: long_description fails to render with pypi

### ISSUE THREAD

**Issue by westurner** [kivy/buildozer#788]
https://pypi.org/project/buildozer/

https://github.com/pypa/readme_renderer/blob/master/README.rst#check-description-locally

You can check the long_description syntax w/:

```bash
twine check
```

**Comment by westurner** [comment]
https://cookiecutter.readthedocs.io/en/latest/readme.html#cookiecutter-specials

https://github.com/audreyr/cookiecutter-pypackage/blob/master/%7B%7Bcookiecutter.project_slug%7D%7D/setup.py

```python
with open('README.rst') as readme_file:
    readme = readme_file.read()

with open('HISTORY.rst') as history_file:
    history = history_file.read()

# ...
setup(
    long_description=readme + '\n\n' + history,
)
```

https://github.com/audreyr/cookiecutter-pypackage/blob/master/%7B%7Bcookiecutter.project_slug%7D%7D/docs/readme.rst

```rst
.. include:: ../README.rst
```

**Comment by AndreMiras** [comment]
I believe this is fixed https://github.com/kivy/buildozer/blob/1.1.0/.github/workflows/pypi-release.yml#L19
Feel free to reopen with info otherwise.
