### ISSUE TITLE
TypeError: read() takes exactly 2 arguments (3 given)

### ISSUE THREAD

**Issue by AndreMiras** [kivy/buildozer#792]
The regression was introduced on Python2 with https://github.com/kivy/buildozer/pull/789 also see https://github.com/kivy/buildozer/commit/c66af5dc0bf7420df6d71c26bee55f085b80c93b#commitcomment-31965387 and https://stackoverflow.com/questions/54208752/buildozer-problem-i-try-to-make-apk-file-for-android-but-i-cant

**Comment by JonasT** [comment]
I made an untested attempt of a fix here: https://github.com/kivy/buildozer/pull/791

**Comment by AndreMiras** [comment]
The original reporter made a more comprehensive bug report in #793 so I'm closing this one over the other
