### ISSUE TITLE
Target ndk-api is 19, but the **python3 recipe supports only 21**

### ISSUE THREAD

**Issue by 101iv** [kivy/buildozer#796]
### Versions

* Python: 2.7
* VM: 0.5

### Description

// I'm trying to build an apk in a virtual machine, but an error comes out
Build failed: Target ndk-api is 19, but the **python3 recipe supports only 21**+
How do I change the settings to remove the API restriction?

### buildozer.spec
Command:
```sh
[app]

title = FitRoom
package.name = fitroom
package.domain = org.test


source.dir = /media/sf_work/FitRoom-1.063-testcamera/
version = 0.1


requirements = python2, kivy==1.10.1, plyer

orientation = landscape

fullscreen = 1

android.permissions = CAMERA, WRITE_EXTERNAL_STORAGE, READ_EXTERNAL_STORAGE, INTERNET

android.api = 19
android.minapi = 9
android.sdk = 21
android.ndk = 9c

android.logcat_filters = *:W python:D
p4a.branch = master

[buildozer]

log_level = 2
warn_on_root = 1


```

### Logs

```
[ERROR]:   Build failed: Target ndk-api is 19, but the **python3 recipe supports only 21**+
# Command failed: /usr/bin/python -m pythonforandroid.toolchain create --dist_name=fitroom --bootstrap=sdl2 --requirements=python2,kivy==1.10.1,plyer --arch armeabi-v7a --copy-libs --color=always --storage-dir="/home/kivy/.buildozer/android/platform/build"```

**Comment by JonasT** [comment]
@101iv as far as I'm aware you need to use an older p4a version with e.g. python3crystax, or use python 2 with the `python2legacy` recipe. or drop support for devices with API level lower than 21. There is currently no support implemented on latest master for API lower than 21 I believe

**Comment by 101iv** [comment]
@JonasT , thank you for your time, 
the application was assembled with the following settings:
`
[app]

title = FitRoom
package.name = fitroom
package.domain = org.test
source.dir = /media/sf_work/FitRoom-1.062/
source.include_exts = py,png,jpg,kv,atlas
version = 0.1


requirements = python2, kivy==1.10.1, plyer, pyjnius, android

android.permissions = CAMERA, WRITE_EXTERNAL_STORAGE, READ_EXTERNAL_STORAGE, INTERNET

android.api = 27
android.minapi = 19
android.sdk = 23
android.ndk = r16b
android.ndk_api = 19

android.ndk_path = /home/kivy/Android/android-ndk-r16b/
android.sdk_path = /home/kivy/Android/android-sdk-23/

android.arch = armeabi-v7a
p4a.source_dir = /home/kivy/Repos/python-for-android/

[buildozer]
log_level = 2
warn_on_root = 1
`

Then, when there is time, I will test minapi < 19

**Comment by inclement** [comment]
This is expected behaviour, since we no longer really support minimum/ndk APIs less than 21. Supporting minapi 19 with python3 would be possible, there was a patch for it that we could add, but that's a separate issue.

**Comment by fs-melo** [comment]
Hi!
@inclement, we are starting a discussion about using the camera in API 21+ in [Kivy 6919 issue](https://github.com/kivy/kivy/issues/6919)
