### ISSUE TITLE
Do a new buildozer release

### ISSUE THREAD

**Issue by inclement** [kivy/buildozer#804]
After merging #803 to bring buildozer up to date, we need a new release. This may as well wait until at least tomorrow in case anything else comes up to add or test.

**Comment by inclement** [comment]
TODO: https://github.com/kivy/buildozer/pull/795 and https://github.com/kivy/buildozer/pull/787

**Comment by inclement** [comment]
Still waiting for me to finish some buildozer fixes/updates for the latest SDKs.

**Comment by KeyWeeUsr** [comment]
@inclement ping 😁

**Comment by AndreMiras** [comment]
Do we want to fix https://github.com/kivy/buildozer/issues/812 and https://github.com/kivy/buildozer/issues/813 first? Even though it's minor error, it doesn't look good and should be fairly easy to fix

**Comment by AndreMiras** [comment]
We got a few releases since then recently, last one was a month ago https://github.com/kivy/buildozer/releases/tag/1.1.0
Another one is to come soon
