### ISSUE TITLE
lol sorry

### ISSUE THREAD

**Issue by ulist** [kivy/buildozer#811]
https://github.com/palantir/bulldozer/issues/91

**Comment by AndreMiras** [comment]
I read the original bug report, but I have no clue what you're trying to do. If it's a bug report, I feel w definitely need more info and well proper title and description.
Closing for now, but feel free to re-open if you can edit title and desc with proper info and way for us to reproduce the bug. Remember we have an issue template to help you filling the important info

**Comment by ulist** [comment]
screw this kivy
