### ISSUE TITLE
Buildozer install doc is very out of date

### ISSUE THREAD

**Issue by inclement** [kivy/buildozer#819]
https://buildozer.readthedocs.io/en/latest/installation.html

**Comment by AndreMiras** [comment]
Just triggered a new build manually via https://readthedocs.org/projects/buildozer/builds/ and it's now up to date.
However I don't know if the build is supposed to run automatically. @inclement do you have an idea?

**Comment by inclement** [comment]
It used to run automatically, I believe we would like that to happen again if possible.

**Comment by misl6** [comment]
Closing this issue as the integration on readthedocs, (which is a webhook configured on GitHub side) now works just good and the docs are kept synced.
