### ISSUE TITLE
Application stuck in portrait mode

### ISSUE THREAD

**Issue by MDelaney7700** [kivy/buildozer#820]
### Versions

* Python: 3.7
* OS: Ubuntu 18.04
* Buildozer: 0.39

### Description

My android application appears stuck in portrait mode even when orientation is set to either "all" or "sensorLandscape". It actually goes to landscape when set to "landscape", but otherwise to goes to portrait and remains there. So far I've tried deleting my application and global .buildozer directories and rebuilding everything, but the issue persisted. Strangely, when the application is loading initially, the loading screen is able to change orientation, but when the app loads, it goes to portrait.

### buildozer.spec
Command:
```sh
buildozer android debug deploy run
```

Spec file:
```
title = Dss Time
package.name = dssapp
package.domain = com.delaneyware
source.dir = .
source.include_exts = py,png,jpg,kv,atlas
version = 0.1
requirements = python3,kivy,requests,android,dateutil,certifi
orientation = all
osx.python_version = 3
osx.kivy_version = 1.10.1
fullscreen = 0
android.permissions = INTERNET
android.arch = armeabi-v7a
ios.kivy_ios_url = https://github.com/kivy/kivy-ios
ios.kivy_ios_branch = master
ios.ios_deploy_url = https://github.com/phonegap/ios-deploy
ios.ios_deploy_branch = 1.7.0
log_level = 2
warn_on_root = 1
```

**Comment by inclement** [comment]
The `all` option isn't currently supported in buildozer/p4a master, because we updated to SDL2.0.9 but that doesn't have a setting for it. We'll probably fix this quite soon. Possibly you can set it from your apk by calling the Java API for it instead.

**Comment by inclement** [comment]
Fixed by @opacam in https://github.com/kivy/kivy/pull/6138, but we'll have to wait a short time to make p4a use this updated Kivy version as Kivy master needs an update to the sdl2_image used by p4a.

**Comment by AndreMiras** [comment]
Merged in p4a master https://github.com/kivy/python-for-android/pull/1692
thanks for the report
