### ISSUE TITLE
download() is not CI log friendly

### ISSUE THREAD

**Issue by AndreMiras** [kivy/buildozer#823]
The way we report download progress in [`buildozer/__init__.py` download()](https://github.com/kivy/buildozer/blob/91ba12d/buildozer/__init__.py#L672) is absolutely helpful in the terminal, but really messes up with Travis logger.

When downloading things as big as the Android NDK via buildozer, it produces a very large amount of progress lines, like in the extract below:
```
[0m[1;34m# Android NDK is missing, downloading[0m
- Download 0.00%
- Download 0.00%
- Download 0.00%
- Download 0.00%
- Download 0.00%
- Download 0.01%
- Download 0.01%
- Download 0.01%
- Download 0.01%
- Download 0.01%
- Download 0.01%
- Download 0.01%
- Download 0.01%
- Download 0.02%
- Download 0.02%
- Download 0.02%
```
In total this log file has over 100K lines of `- Download `! See attached screenshot and complete log for reference: https://api.travis-ci.org/v3/job/491113892/log.txt
![image](https://user-images.githubusercontent.com/24973/52528534-506b8c00-2ce1-11e9-97e1-fc5026a8354b.png)

To fix the issue, maybe we should make it possible to reduce the verbosity of this `download()` method. Other suggestions are very welcome.
Side note: same issue exists in p4a via `download_file()`, but the most annoying currently is `buildozer` as it generates lager downloads so far.

**Comment by mkg20001** [comment]
My fork, which includes [this commit](https://github.com/mkg20001/buildozer/commit/c4ae19f4b8bcd24db1dcd053bb175c0bdaa06d60) has an environment flag called `CI_MODE` which can be set to 1 to disable progress-printing

**Comment by AndreMiras** [comment]
Very nice, yes that's the idea :+1:

**Comment by mkg20001** [comment]
Created PRs #833 and kivy/python-for-android#1727 that implement this. Hope this gets merged soon, then I can finally drop my forks of this project
