### ISSUE TITLE
I found the origin of the problem mentioned in issue #694 (Aidl not found)

### ISSUE THREAD

**Issue by climb65** [kivy/buildozer#824]
Hi guys,
I found the origin of the problem mentioned in https://github.com/kivy/buildozer/issues/694

Note : it is about the aidl problem and the lack of the build-tools directory in ~/.buildozer/android/platform/android-sdk/

On a fresh Ubuntu 18 system, when running this command :

buildozer android debug deploy run

The process stopped with this :
Aidl not found, please install it.

Actually, we need to accept the sdk license. But, by running buildozer in log_level 1 we have no chance to see this license request.
We need to set log_level at 2, then run the command again. The script will pause with messages (thanks to log_level 2). We need to hit the 'y' key and 'Enter'. Then everything will go smoothly!

Richard

**Comment by darosior** [comment]
Thank you !

**Comment by fedus** [comment]
For me, even with loglevel 2 the script does not pause to wait for user input and everything is declined.

**Comment by rwinterberg** [comment]
I saw the y/n prompt come by, but I got confused and broke off the build. After that, I found this thread, but now I cannot get the y/n prompt to accept the license back again. 
No matter if I do a clean build, manually delete the SDK, I get the 'AIDL not found' message.

Any idea how to re-invoke the SDK license prompt?

**Comment by ADR-007-SoftServe** [comment]
I just typed `y` even ther no any message
```
buildozer android update -v2
# Check configuration tokens
# Ensure build layout
# Check configuration tokens
# Preparing build
# Check requirements for android
# Install platform
# Apache ANT found at /home/kivy/.buildozer/android/platform/apache-ant-1.9.4
# Android SDK found at /home/kivy/.buildozer/android/platform/android-sdk
# Android NDK found at /home/kivy/.buildozer/android/platform/android-ndk-r17c
# Installing/updating SDK platform tools if necessary
y
# Updating SDK build tools if necessary
y
# Downloading platform api target if necessary
# Android packages installation done.
# Check application requirements
# Check garden requirements
# Compile platform
```

**Comment by stmikeal** [comment]
Thanks a lot!

**Comment by venomega** [comment]
> I just typed `y` even ther no any message
> 
> ```
> buildozer android update -v2
> # Check configuration tokens
> # Ensure build layout
> # Check configuration tokens
> # Preparing build
> # Check requirements for android
> # Install platform
> # Apache ANT found at /home/kivy/.buildozer/android/platform/apache-ant-1.9.4
> # Android SDK found at /home/kivy/.buildozer/android/platform/android-sdk
> # Android NDK found at /home/kivy/.buildozer/android/platform/android-ndk-r17c
> # Installing/updating SDK platform tools if necessary
> y
> # Updating SDK build tools if necessary
> y
> # Downloading platform api target if necessary
> # Android packages installation done.
> # Check application requirements
> # Check garden requirements
> # Compile platform
> ```

this not work for me, any other ideas?

**Comment by theo2bel** [comment]
> 

did you finally succeed ? I still have the problem

**Comment by stmikeal** [comment]
check this link, mb it'll help you
https://github.com/kivy/buildozer/issues/1303
