### ISSUE TITLE
Errors packaging hello world app

### ISSUE THREAD

**Issue by brupelo** [kivy/buildozer#825]
I've posted this question also on [stackoverflow](https://stackoverflow.com/questions/54621830/errors-packaging-app-for-android-using-ubuntu-and-buildozer) so it can be reproduced easily (~15min)

**Comment by AndreMiras** [comment]
I believe this is using an old toolchain as it references `# Command failed: ./distribute.sh -l` feel free to re-open with up to date log/report as a lot has changed recently
