### ISSUE TITLE
App crashes on startup

### ISSUE THREAD

**Issue by PtmDex** [kivy/buildozer#826]
After installing modules, I followed instructions to build an apk file. 
My app uses gspread and oauth2client. Put all the requirements in the buildozer.spec file.
I run `buildozer android debug deploy run logcat` then the application crash after loading screen.
The first thing I think the problem is it can't find "libpython3.5m.so", "libpython3.6m.so", "libpython3.7m.
I inserted the log  below. Please help me thanks T_T.

[log file](http://www.mediafire.com/file/of2qg23a1jhnanm/log.txt/file)

[buildozer.spec](http://www.mediafire.com/file/129d59jdb5w4w38/buildozer.spec/file)

**Comment by AndreMiras** [comment]
I guess the relevant part of your log file is:
```
02-11 14:04:06.022 16530 16664 I python  :  Traceback (most recent call last):
02-11 14:04:06.022 16530 16664 I python  :    File "/home/kivy/Desktop/avac-app/.buildozer/android/app/main.py", line 11, in <module>
02-11 14:04:06.023 16530 16664 I python  :    File "/home/kivy/Desktop/avac-app/.buildozer/android/platform/build/build/python-installs/avacremote/oauth2client/service_account.py", line 26, in <module>
02-11 14:04:06.024 16530 16664 I python  :    File "/home/kivy/Desktop/avac-app/.buildozer/android/platform/build/build/python-installs/avacremote/oauth2client/crypt.py", line 23, in <module>
02-11 14:04:06.025 16530 16664 I python  :    File "/home/kivy/Desktop/avac-app/.buildozer/android/platform/build/build/python-installs/avacremote/oauth2client/_pure_python_crypt.py", line 22, in <module>
02-11 14:04:06.026 16530 16664 I python  :  ImportError: No module named pyasn1.codec.der
02-11 14:04:06.026 16530 16664 I python  : Python for android ended.
```
So you probably miss that `pyasn1` module in your requirements.
I guess this is not really a buildozer bug, so I'm closing. If you need some support try the support channel on discord :smiley:
