### ISSUE TITLE
Create tests for PR fix bug when logcat value which cannot be decode to utf-8

### ISSUE THREAD

**Issue by Draqun** [kivy/buildozer#857]
Create tests for fix from link below.

https://github.com/kivy/buildozer/pull/856

**Comment by Draqun** [comment]
Hi. Sadly I don't have enough skills to write tests. I don't know docker (ugly solution) and there is no requirements.txt file to build venv.
Sorry for that.

**Comment by AndreMiras** [comment]
No worries, this could be tricky.
I'm actually not sure how this error you fixed happens.
Anyway for testing it I would say it should involve mocking https://docs.python.org/3/library/unittest.mock.html
The way I would have imagined it is calling [Buildozer.cmd()](https://github.com/kivy/buildozer/blob/c803e68/buildozer/__init__.py#L271) within a mocked `Popen` to make sure it `.stdout.read()` returns a non `utf-8` decodable string.
So the patching could look like this (untested):
```python
command = 'mycommand'
kwargs = { 'show_output': True }
with mock.patch('buildozer.Popen') as m_popen:
    # the command output could be were we want to play with unicode decode errors
    m_popen().stdout.read.side_effect = [b'mycommand output']
    buildozer.cmd(command, **kwargs)
```
That just to give the idea

**Comment by AndreMiras** [comment]
I just gave it a try see https://github.com/kivy/buildozer/pull/905
So yes definitely not the best use case to start playing with mocks
