### ISSUE TITLE
The scipy package does not work

### ISSUE THREAD

**Issue by Moriand** [kivy/buildozer#869]
### Versions

* Python: 3.x
* OS: ubuntu x64
* Buildozer: 0.39 ultimate

### Description
I used buildozer in 2 ways.
the first is creating an apk without using scipy, that is, only the design, that includes buttons and the graphic part.
And the other one is, including the scipy package and it turns out the following:

  - ### **only design**

when using
`buildozer android debug run logcat> info.txt`
It has **not generated any errors** and works correctly on the android device.

  - ### **including scipy package**

When using
`buildozer android debug run logcat> info.txt`
it has generated the apk but, when opening the application on my android mobile phone it **closes after the splashscreen**

### buildozer.spec
Command:
```sh
buildozer android debug run
```

Spec file:
```
# (list) Source files to include (let empty to include all the files)
source.include_exts = py,png,jpg,kv
# (str) Application versioning (method 1)
version = 1.0
# (list) Application requirements
# comma separated e.g. requirements = sqlite3,kivy
requirements = python3,kivy,scipy
# change the major version of python used by the app
osx.python_version = 3
# Kivy version to use
osx.kivy_version = 1.10.0
# (int) Log level (0 = error only, 1 = info, 2 = debug (with command output))
log_level = 2
```

### Logs

```
```

**Comment by inclement** [comment]
I'm afraid scipy is not supported by python-for-android, although the fact that it builds the APK without failing is a bug.

**Comment by vizakshat** [comment]
>  the fact that it builds the APK without failing is a bug.
same with many packges.. I have tried to include other python packages and the build is successful.. the app only crashes at splashscreen when import the module.. if I comment the import the run is successful ..

**Comment by podraco** [comment]
try using:
`buildozer -v android debug deploy run && adb logcat | grep python`
to get the real Logcat, since it's a runtime bug,

**Comment by lakshit77** [comment]
#880 
did anyone got any solution for this issue.??

**Comment by Julian-O** [comment]
This is a python-for-android issue, not a Buildozer one.

Seems to have been addressed with https://github.com/kivy/python-for-android/pull/2370

Closing as out-of-scope here.
