### ISSUE TITLE
buildozer android debug deploy is stuck

### ISSUE THREAD

**Issue by Crimar1** [kivy/buildozer#870]
### Versions

* Python: 2.7.15 
* OS: Ubuntu 18.10
* Buildozer: 

### Description

I'm trying to create an apk file. I created a virtual box with ubuntu, Now the terminal of ubuntu is stuck after the
command: buildozer android debug

What can I do to make it work?

![buildozer stuck](https://user-images.githubusercontent.com/39221131/54960374-a37d6380-4f5c-11e9-9471-1146a6ac7414.png)

I run the command: buildozer android logcat

![error logcat](https://user-images.githubusercontent.com/39221131/54965197-c6654300-4f6f-11e9-978c-0f0eef92a403.jpg)

**Comment by Flajt** [comment]
It's just a guess. Try to install adb and/or install it in the missing folder (just create it and install it via Github if possible  )

**Comment by AndreMiras** [comment]
my guess is that you're not running buildozer master and your `log_level` is not `2`. It's probably hanging with the license. Please share your `buildozer.spec` and `buildozer --version`

**Comment by snorrwe** [comment]
I had the same issue and the reason was a licence I had to accept. Setting `log_level` to `2` helped, although I think an option that would automatically accept everything (like `--yes` on `apt-get`) would be helpful

**Comment by AndreMiras** [comment]
Thanks for the feedback.
Yes there's already an option to accept the license automatically.
[android.accept_sdk_license](https://github.com/kivy/buildozer/blob/0.39/buildozer/default.spec#L126)
