### ISSUE TITLE
What is the way to add folders and files?

### ISSUE THREAD

**Issue by spartero** [kivy/buildozer#875]
After trying a simple example, I have taken the step to something more complex. I want to package a flask application that I have running for android. has the following structure:
```
- main.py
   - templates
      - plantilla.html
      - index.html
   - static
      - img
         - img.jp
      - css
         - style.css
```
In the configuration file (I only put the parts corresponding to the configuration of folders and files, the rest is by default):
```
source.dir = .
source.include_exts = py,html,css,jpg
source.include_patterns = templates/*.html,static/img/*.jpg,static/css/*.css
```
the apk created does not work on the phone and if I open the apk, I do not see any html file, css, jpg

What is the way to add folders and files?

**Comment by spartero** [comment]
I have already solved it, but I just have to put the extensions of the files to be packaged and the apk in `source.include_exts = py, html, css, jpg`. And stop commenting `source.include_patterns`. After doing this, delete the hidden buildozer folder and repackage it.

**Comment by iruriksl** [comment]
> After trying a simple example, I have taken the step to something more complex. I want to package a flask application that I have running for android. has the following structure:
> 
> ```
> - main.py
>    - templates
>       - plantilla.html
>       - index.html
>    - static
>       - img
>          - img.jp
>       - css
>          - style.css
> ```
> 
> In the configuration file (I only put the parts corresponding to the configuration of folders and files, the rest is by default):
> 
> ```
> source.dir = .
> source.include_exts = py,html,css,jpg
> source.include_patterns = templates/*.html,static/img/*.jpg,static/css/*.css
> ```
> 
> the apk created does not work on the phone and if I open the apk, I do not see any html file, css, jpg
> 
> What is the way to add folders and files?

I am facing the same problem. The apk build is success, but the other files instead of main.py is not found in the apk.
If you got any solution share it as the current buildozer & pythonfor android version are not including the files, dirs as defined under source.include_exts & source.include_patterns

**Comment by iruriksl** [comment]
> I have already solved it, but I just have to put the extensions of the files to be packaged and the apk in `source.include_exts = py, html, css, jpg`. And stop commenting `source.include_patterns`. After doing this, delete the hidden buildozer folder and repackage it.

This doesn't worked
