### ISSUE TITLE
Buildozer "Command failed:" error

### ISSUE THREAD

**Issue by PATAPOsha** [kivy/buildozer#876]
### Versions

* Python: 3.6.7
* OS: Ubuntu 18
* Buildozer: 0.40.dev0
* Kivy: 1.11.0.dev0
* Java: openjdk version "10.0.2" 2018-07-17
* Cython: 0.29.6

### Description

Trying to run commands from buildozer's README:
```
buildozer init
buildozer android debug deploy run
```

I have main.py from https://kivy.org/doc/stable/guide/basic.html#quickstart in my project dir.

Getting:
```
Command failed: /home/pata/.buildozer/android/platform/android-sdk/tools/bin/sdkmanager tools platform-tools
```

### buildozer.spec
Command:
```sh
buildozer android debug
```

Spec file:
Generated .spec. Only log_level = 2 edited.

### Logs

```
(kivy_test) pata@pata_pc:~/PycharmProjects/kivy_test$ buildozer android debug
# Check configuration tokens
# Ensure build layout
# Check configuration tokens
# Read available permissions from api-versions.xml
# Preparing build
# Check requirements for android
# Run 'dpkg --version'
# Cwd None
Debian 'dpkg' package management program version 1.19.0.5 (amd64).
This is free software; see the GNU General Public License version 2 or
later for copying conditions. There is NO warranty.
# Search for Git (git)
#  -> found at /usr/bin/git
# Search for Cython (cython)
#  -> found at /home/pata/.local/bin/cython
# Search for Java compiler (javac)
#  -> found at /usr/lib/jvm/java-11-openjdk-amd64/bin/javac
# Search for Java keytool (keytool)
#  -> found at /usr/lib/jvm/java-11-openjdk-amd64/bin/keytool
# Install platform
# Run '/home/pata/venvs/kivy_test/bin/python -m pip install -q  \'appdirs\' \'colorama>=0.3.3\' \'jinja2\' \'six\' \'enum34; python_version<"3.4"\' \'sh>=1.10; sys_platform!="nt"\''
# Cwd None
# Apache ANT found at /home/pata/.buildozer/android/platform/apache-ant-1.9.4
# Android SDK found at /home/pata/.buildozer/android/platform/android-sdk
# Android NDK found at /home/pata/.buildozer/android/platform/android-ndk-r17c
# Installing/updating SDK platform tools if necessary
# Run '/home/pata/.buildozer/android/platform/android-sdk/tools/bin/sdkmanager tools platform-tools'
# Cwd /home/pata/.buildozer/android/platform/android-sdk
Exception in thread "main" java.lang.NoClassDefFoundError: javax/xml/bind/annotation/XmlSchema
        at com.android.repository.api.SchemaModule$SchemaModuleVersion.<init>(SchemaModule.java:156)
        at com.android.repository.api.SchemaModule.<init>(SchemaModule.java:75)
        at com.android.sdklib.repository.AndroidSdkHandler.<clinit>(AndroidSdkHandler.java:81)
        at com.android.sdklib.tool.sdkmanager.SdkManagerCli.main(SdkManagerCli.java:73)
        at com.android.sdklib.tool.sdkmanager.SdkManagerCli.main(SdkManagerCli.java:48)
Caused by: java.lang.ClassNotFoundException: javax.xml.bind.annotation.XmlSchema
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:583)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:190)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:499)
        ... 5 more
# Command failed: /home/pata/.buildozer/android/platform/android-sdk/tools/bin/sdkmanager tools platform-tools

```

**Comment by AndreMiras** [comment]
Yes you need openjdk-8:
```
sudo apt install openjdk-8-jdk
```
Closing as dup https://github.com/search?q=org%3Akivy+java.lang.NoClassDefFoundError%3A+javax%2Fxml%2Fbind%2Fannotation%2FXmlSchema&type=Issues

**Comment by Narinder99** [comment]
Hii i have same error 

sudo apt install openjdk-8-jdk not working

**Comment by 2001chase2001** [comment]
i have the same error and sudo apt install openjdk-8-jdk not working for me

**Comment by AndreMiras** [comment]
Please share complete debug output as well as the output of this command.
```
dpkg -l | grep openjdk
```

**Comment by supsub** [comment]
same error, output of `dpkg -l | grep openjdk`:
```
ii  openjdk-8-jdk:amd64                        8u222-b10-1ubuntu1~18.04.1                   amd64        OpenJDK Development Kit (JDK)  
ii  openjdk-8-jdk-headless:amd64               8u222-b10-1ubuntu1~18.04.1                   amd64        OpenJDK Development Kit (JDK) (headless) 
ii  openjdk-8-jre:amd64                        8u222-b10-1ubuntu1~18.04.1                   amd64        OpenJDK Java runtime, using Hotspot JIT
ii  openjdk-8-jre-headless:amd64               8u222-b10-1ubuntu1~18.04.1                   amd64        OpenJDK Java runtime, using Hotspot JIT (headless)
```

**Comment by michaelwongso** [comment]
@AndreMiras But i already installed openjdk-8-jdk
Welcome to the Buildozer Virtual Machine.
    Please see ~/Desktop/README.txt for more information
    kivy@kivy-VirtualBox:~$ sudo apt install openjdk-8-jdk
    [sudo] password for kivy: 
    Reading package lists... Done
    Building dependency tree       
    Reading state information... Done
    openjdk-8-jdk is already the newest version.
    0 upgraded, 0 newly installed, 0 to remove and 572 not upgraded.
    kivy@kivy-VirtualBox:~$

**Comment by AndreMiras** [comment]
That's pretty weird @supsub could you share your complete buildozer log then?

**Comment by supsub** [comment]
Hey @AndreMiras i solved this problem by uninstalling all java JDKs' from my machine ( i had 8 and 11) and then running 
`sudo apt install openjdk-8-jdk`
Just switching to jdk8 in jej config alternatives didn't work.

**Comment by AndreMiras** [comment]
I suspected this that's why I asked for the `dpkg -l` command. But then I'm surprised it didn't appear in the output.
Thanks for letting us know anyway

**Comment by Krozark** [comment]
> Hey @AndreMiras i solved this problem by uninstalling all java JDKs' from my machine ( i had 8 and 11) and then running

Exaclty the same for me. Removing java 11 fix this error.

**Comment by heikeling** [comment]
# Check configuration tokens
# Ensure build layout
# Check configuration tokens
# Read available permissions from api-versions.xml
# Preparing build
# Check requirements for android
# Search for Git (git)
#  -> found at /usr/bin/git
# Search for Cython (cython)
#  -> found at /usr/local/bin/cython
# Search for Java compiler (javac)
#  -> found at /usr/lib/jvm/java-8-openjdk-amd64/bin/javac
# Search for Java keytool (keytool)
#  -> found at /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/keytool
# Install platform
# Run ['git', 'config', '--get', 'remote.origin.url']
# Cwd /mnt/c/users/home/desktop/kivyCnlang/.buildozer/android/platform/python-for-android
https://github.com/kivy/python-for-android.git
# Run ['git', 'branch', '-vv']
# Cwd /mnt/c/users/home/desktop/kivyCnlang/.buildozer/android/platform/python-for-android
* master cc6481b0 [origin/master] Merge pull request #2718 from kivy/release-2022.12.20
# Run ['/usr/bin/python3', '-m', 'pip', 'install', '-q', '--user', 'appdirs', 'colorama>=0.3.3', 'jinja2', 'sh>=1.10; sys_platform!="nt"', 'pep517', 'toml', 'packaging']
# Cwd None
# Apache ANT found at /home/ubuntu/.buildozer/android/platform/apache-ant-1.9.4
# Android SDK found at /home/ubuntu/.buildozer/android/platform/android-sdk
# Recommended android's NDK version by p4a is: 25b
# Android NDK found at /home/ubuntu/.buildozer/android/platform/android-ndk-r25b
# Installing/updating SDK platform tools if necessary
# Run ['/home/ubuntu/.buildozer/android/platform/android-sdk/tools/bin/sdkmanager', '--sdk_root=/home/ubuntu/.buildozer/android/platform/android-sdk', 'platform-tools']
# Cwd /home/ubuntu/.buildozer/android/platform/android-sdk
Warning: IO exception while downloading manifest
Warning: IO exception while downloading manifest
Warning: IO exception while downloading manifest
Warning: IO exception while downloading manifestch remote repository...
Warning: IO exception while downloading manifest
Warning: IO exception while downloading manifest
Warning: IO exception while downloading manifest
Warning: IO exception while downloading manifest
Warning: IO exception while downloading manifest
Warning: IO exception while downloading manifest
Warning: IO exception while downloading manifest
Warning: IO exception while downloading manifest
Warning: IO exception while downloading manifest
Warning: IO exception while downloading manifest
Warning: IO exception while downloading manifest
Warning: Still waiting for package manifests to be fetched remotely.
Warning: Failed to find package platform-tools
# Command failed: ['/home/ubuntu/.buildozer/android/platform/android-sdk/tools/bin/sdkmanager', '--sdk_root=/home/ubuntu/.buildozer/android/platform/android-sdk', 'platform-tools']
# ENVIRONMENT:
#     SHELL = '/bin/bash'
#     WSL_DISTRO_NAME = 'Ubuntu'
#     NAME = 'DESKTOP-3FOMP22'
#     PWD = '/mnt/c/users/home/desktop/kivyCnlang'
#     LOGNAME = 'ubuntu'
#     HOME = '/home/ubuntu'
#     LANG = 'C.UTF-8'
#     LS_COLORS = 'rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=00:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.zst=01;31:*.tzst=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.wim=01;31:*.swm=01;31:*.dwm=01;31:*.esd=01;31:*.jpg=01;35:*.jpeg=01;35:*.mjpg=01;35:*.mjpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.webp=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=00;36:*.au=00;36:*.flac=00;36:*.m4a=00;36:*.mid=00;36:*.midi=00;36:*.mka=00;36:*.mp3=00;36:*.mpc=00;36:*.ogg=00;36:*.ra=00;36:*.wav=00;36:*.oga=00;36:*.opus=00;36:*.spx=00;36:*.xspf=00;36:'
#     LESSCLOSE = '/usr/bin/lesspipe %s %s'
#     TERM = 'xterm-256color'
#     LESSOPEN = '| /usr/bin/lesspipe %s'
#     USER = 'ubuntu'
#     SHLVL = '1'
#     WSLENV = ''
#     XDG_DATA_DIRS = '/usr/share/gnome:/usr/local/share:/usr/share:/var/lib/snapd/desktop'
#     PATH = ('/home/ubuntu/.buildozer/android/platform/apache-ant-1.9.4/bin:/home/ubuntu/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/mnt/c/Program '
 'Files/WindowsApps/CanonicalGroupLimited.Ubuntu_2204.1.8.0_x64__79rhkp1fndgsc:/mnt/c/Program '
 'Files/OpenJDK/jdk-11.0.16.8-hotspot/bin:/mnt/c/Program Files '
 '(x86)/VMware/VMware '
 'Workstation/bin/:/mnt/c/WINDOWS/system32:/mnt/c/WINDOWS:/mnt/c/WINDOWS/System32/Wbem:/mnt/c/WINDOWS/System32/WindowsPowerShell/v1.0/:/mnt/c/WINDOWS/System32/OpenSSH/:/mnt/c/Program '
 'Files/Microsoft SQL Server/130/Tools/Binn/:/mnt/c/Program '
 'Files/nodejs/:/mnt/c/Program Files (x86)/Git/cmd:/mnt/c/Program '
 'Files/dotnet/:/mnt/c/Strawberry/c/bin:/mnt/c/Strawberry/perl/site/bin:/mnt/c/Strawberry/perl/bin:/mnt/d/Program '
 'Files/Go/bin:/mnt/c/Users/home/AppData/Local/Programs/Python/Python310/Scripts/:/mnt/c/Users/home/AppData/Local/Programs/Python/Python310/:/mnt/c/Users/home/AppData/Local/Microsoft/WindowsApps:/mnt/c/Users/home/AppData/Roaming/npm:/mnt/d/Users/home/AppData/Local/Programs/APICloud '
 'Studio 3/bin:/mnt/d/Program Files/JetBrains/PyCharm Community Edition '
 '2022.2.1/bin:/mnt/d/Users/home/AppData/Local/Programs/Microsoft VS '
 'Code/bin:/mnt/c/Users/home/go/bin:/snap/bin')
#     HOSTTYPE = 'x86_64'
#     OLDPWD = '/home/ubuntu'
#     _ = '/usr/local/bin/buildozer'
#
# Buildozer failed to execute the last command
# The error might be hidden in the log above this error
# Please read the full log, and search for it before
# raising an issue with buildozer itself.
# In case of a bug report, please add a full log with log_level = 2

**Comment by heikeling** [comment]
why
