### ISSUE TITLE
How to pass "allow_backup" as parameter to python-for-android?

### ISSUE THREAD

**Issue by edsonitk** [kivy/buildozer#881]
Hi,

I need to avoid the automatic backup of android and I believe that if I change the allow_backup parameter in build.py it should work

Setup
Python: 2.7
Android
Buildozer:

**Comment by AndreMiras** [comment]
Linking the p4a PR for reference https://github.com/kivy/python-for-android/pull/1438

**Comment by AndreMiras** [comment]
Closed via #1206
