### ISSUE TITLE
Error when running: buildozer --verbose android debug deploy run

### ISSUE THREAD

**Issue by vitiral** [kivy/buildozer#89]
Edit: I am running 64 bit Ubuntu 12.04

I followed the guide from here: http://kivy.org/docs/guide/packaging-android.html

I am trying to compile the example pong app. Here is my buildozer.spec sheet
http://pastebin.com/R7uwpdtd

When I run `buildozer --verbose android debug deploy run` It gives the following errors:

```
Error: Target id 'android-14' is not valid. Use 'android list targets' to get the target ids.
```

```
BUILD FAILED
/home/user/.buildozer/android/platform/android-sdk-21/tools/ant/build.xml:399: SDK Platform Tools component is missing. Please install it with the SDK Manager (tools/android)
```

```
Total time: 0 seconds
Traceback (most recent call last):
  File "build.py", line 412, in <module>
    make_package(args)
  File "build.py", line 336, in make_package
    subprocess.check_call([ANT, arg])
  File "/usr/lib/python2.7/subprocess.py", line 511, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['ant', 'debug']' returned non-zero exit status 1
...


```

**Comment by fccoelho** [comment]
I am in the same situation as @foxbunny

**Comment by akshayaurora** [comment]
@fccoelho which version of bulldozer are you using? try updating the latest from pip

pip install --upgrade bulldozer

There was a new release just yesterday. Make sure you have the latest package and open a new issue if you still have a issue with it.

**Comment by erm3nda** [comment]
@akshayaurora It's buildozer, but as Kivy member i think you're sure about it's name :-)

**Comment by akshayaurora** [comment]
@erm3nda I am but autocorrect does not agree with me :/

**Comment by erm3nda** [comment]
I was thinking on the "98% of people copypasting w/o reading commands" :-) thank you.

**Comment by guysoft** [comment]
[Requested API target 19 is not available, install it with the SDK android tool.](url)
