### ISSUE TITLE
ValueError: Tried to access ndk_ver but it has not been set - this should not happen, something went wrong!

### ISSUE THREAD

**Issue by Petar-Luketina** [kivy/buildozer#893]
* Python: 2.7
* OS: Ubuntu 16
* Buildozer: tried dev (up-to-date) & stable

### Description

I'm trying to deploy my app with `buildozer android deploy` and `buildozer android debug` but I keep getting the same error no matter what settings I use. I tried:
```
p4a.source_dir = ~/p4a
p4a.bootstrap = sdl2

p4a.branch = master

android.api = 27
android.minapi = 21
android.sdk = 23
android.ndk = 17c
android.arch = armeabi-v7a
```
I also tried commenting out the the `android. ...` but neither solved my problem. Does anyone know what the error message means? Thank you in advance!

### Logs

```
[INFO]:    Requested API target 27 is available, continuing.
[INFO]:    Found NDK dir in $ANDROIDNDK: /home/pl/.buildozer/android/platform/android-ndk-r17c
[WARNING]: Android NDK version could not be found. This probablywon't cause any problems, but if necessary you canset it with `--ndk-version=...`.
[INFO]:    Getting NDK API version (i.e. minimum supported API) from user argument
Traceback (most recent call last):
  File "/home/pl/anaconda2/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/home/pl/anaconda2/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/pl/p4a/pythonforandroid/toolchain.py", line 1035, in <module>
    main()
  File "/home/pl/p4a/pythonforandroid/toolchain.py", line 1031, in main
    ToolchainCL()
  File "/home/pl/p4a/pythonforandroid/toolchain.py", line 551, in __init__
    getattr(self, args.subparser_name.replace('-', '_'))(args)
  File "/home/pl/p4a/pythonforandroid/toolchain.py", line 142, in wrapper_func
    user_ndk_api=self.ndk_api)
  File "pythonforandroid/build.py", line 376, in prepare_build_environment
    info('Using {} NDK {}'.format(self.ndk.capitalize(), self.ndk_ver))
  File "pythonforandroid/build.py", line 147, in ndk_ver
    raise ValueError('Tried to access ndk_ver but it has not '
ValueError: Tried to access ndk_ver but it has not been set - this should not happen, something went wrong!
```

**Comment by nitanmarcel** [comment]
Hi! I see you have there a `p4a.source_dir` set. If you use a custom dir for python for android make sure you have the latest master branch :)

**Comment by Petar-Luketina** [comment]
@nitanmarcel Thank you for reminding me! I just updated it, but I still get the same error.

**Comment by nitanmarcel** [comment]
@Petar-Luketina make sure is not the same error. The newer update brought me a new error as mentioned here https://github.com/kivy/python-for-android/issues/1808

**Comment by nitanmarcel** [comment]
Also you could try with python 3.x as until now I didn't had problems with

**Comment by nitanmarcel** [comment]
Some things you could try:

- Use the latest python version
or/and
- Make sure you're on the right branch on your cloned repository by doing a `git checkout master`

**Comment by Petar-Luketina** [comment]
> * git checkout master

I tried the last two suggestions but I haven't tried to build with Python 3x. You still have to use Crysyax, correct?

**Comment by nitanmarcel** [comment]
> > * git checkout master
> 
> I tried the last two suggestions but I haven't tried to build with Python 3x. You still have to use Crysyax, correct?

I don't really remember. When I installed buildozer I just installed the dependencies and install it with `sudo python3 setup.py install`

```shell

sudo apt install -y \
    build-essential \
    ccache \
    git \
    libncurses5:i386 \
    libstdc++6:i386 \
    libgtk2.0-0:i386 \
    libpangox-1.0-0:i386 \
    libpangoxft-1.0-0:i386 \
    libidn11:i386 \
    python2.7 \
    python2.7-dev \
    openjdk-8-jdk \
    unzip \
    zlib1g-dev \
    zlib1g:i386 \
    libltdl-dev \
    libffi-dev \
    libssl-dev \
    autoconf \
    autotools-dev
    cmake

# Install Buildozer
git clone https://github.com/kivy/buildozer.git
cd buildozer
sudo python3 setup.py install
```

**Comment by Petar-Luketina** [comment]
I did the above and got this error AttributeError: `'Namespace' object has no attribute 'ignore_setup_py'`

**Comment by nitanmarcel** [comment]
> I did the above and got this error AttributeError: `'Namespace' object has no attribute 'ignore_setup_py'`

Yes that means you're on the right version :laughing: 

The fix for that can be found here:

https://github.com/kivy/python-for-android/pull/1809

**Comment by Petar-Luketina** [comment]
Cool! That's good to know. What file do I add this code to:
```
    build_recipes(build_order, python_modules, ctx, args.private if hasattr(args, "private") else None,
                  ignore_project_setup_py=args.ignore_setup_py if hasattr(args, "ignore_setup_py") else False,
                 )
```

**Comment by nitanmarcel** [comment]
The toolchain.py file needs to be edited. That was just a lazy fix of mine and incomplete. Better wait for the devs to approve that PR by JonasT as it contains the full fix :)

**Comment by Petar-Luketina** [comment]
Okay. Thank you for the heads up!

**Comment by nitanmarcel** [comment]
@Petar-Luketina the dev has approved the PR. Is safe to build your app now

**Comment by Petar-Luketina** [comment]
@nitanmarcel I did this just now:
```
git clone https://github.com/kivy/buildozer.git
cd buildozer
sudo python3 setup.py install
```
I still got the same error. Did your deployment work?

**Comment by nitanmarcel** [comment]
- [ ] @Petar-Luketina The problem was with python-for-android so make sure you updated your repo, or comment out `p4a.source_dir = ~/p4a` and let buildozer download p4a for you.

Also make sure you deleted the . buildozer folder before building again :)

**Comment by Petar-Luketina** [comment]
@nitanmarcel I appreciate all your help! It worked flawlessly.
