### ISSUE TITLE
warnings while building apk using buildozer

### ISSUE THREAD

**Issue by sujeeth30** [kivy/buildozer#910]
[DEBUG]:   -> running cp /home/sujeeth/Desktop/myapp/.buildozer/android/platform/build/dists/myapp/build/outputs/apk/debug/myapp-debug.apk myapp-1.0-debug.apk
WARNING: Received a --sdk argument, but this argument is deprecated and does nothing.
No compiled python is present to zip, skipping.
No setup.py/pyproject.toml used, copying full private data into .apk.
Applying Java source code patches...
Applying patch: src/patches/SDLActivity.java.patch
Warning: failed to apply patch (exit code 1), assuming it is already applied: src/patches/SDLActivity.java.patch
# Android packaging done!
# APK myapp-1.0-debug.apk available in the bin directory

my app is also crashing it isn't opening.please help me solve this warnings

**Comment by AndreMiras** [comment]
Your app crashing probably has nothing to do with the warnings.
Take a look at the documentation to see how to use logcat to show the app logs.
Usually reading theses logs are enough to spot and fix the issue. If you still struggle, come to the support channel of Discord
