### ISSUE TITLE
app crash

### ISSUE THREAD

**Issue by sujeeth30** [kivy/buildozer#911]
below are the errors in logcat.

06-04 15:16:52.184 24840 24860 I python  :  Traceback (most recent call last):
06-04 15:16:52.185 24840 24860 I python  :    File "/home/sujeeth/Desktop/myapp/.buildozer/android/platform/build/build/python-installs/myapp/pymongo/uri_parser.py", line 254, in _get_dns_srv_hosts
06-04 15:16:52.187 24840 24860 I python  :    File "/home/sujeeth/Desktop/myapp/.buildozer/android/platform/build/build/python-installs/myapp/dns/resolver.py", line 1102, in query
06-04 15:16:52.190 24840 24860 I python  :    File "/home/sujeeth/Desktop/myapp/.buildozer/android/platform/build/build/python-installs/myapp/dns/resolver.py", line 992, in query
06-04 15:16:52.191 24840 24860 I python  :    File "/home/sujeeth/Desktop/myapp/.buildozer/android/platform/build/build/python-installs/myapp/dns/resolver.py", line 799, in _compute_timeout
06-04 15:16:52.193 24840 24860 I python  :  dns.exception.Timeout: The DNS operation timed out after 30.003905057907104 seconds
06-04 15:16:52.194 24840 24860 I python  :  
06-04 15:16:52.195 24840 24860 I python  :  During handling of the above exception, another exception occurred:
06-04 15:16:52.196 24840 24860 I python  :  
06-04 15:16:52.196 24840 24860 I python  :  Traceback (most recent call last):
06-04 15:16:52.197 24840 24860 I python  :    File "/home/sujeeth/Desktop/myapp/.buildozer/android/app/main.py", line 361, in <module>
06-04 15:16:52.199 24840 24860 I python  :    File "/home/sujeeth/Desktop/myapp/.buildozer/android/platform/build/build/python-installs/myapp/pymongo/mongo_client.py", line 524, in __init__
06-04 15:16:52.201 24840 24860 I python  :    File "/home/sujeeth/Desktop/myapp/.buildozer/android/platform/build/build/python-installs/myapp/pymongo/uri_parser.py", line 366, in parse_uri
06-04 15:16:52.203 24840 24860 I python  :    File "/home/sujeeth/Desktop/myapp/.buildozer/android/platform/build/build/python-installs/myapp/pymongo/uri_parser.py", line 256, in _get_dns_srv_hosts
06-04 15:16:52.205 24840 24860 I python  :  pymongo.errors.ConfigurationError: The DNS operation timed out after 30.003905057907104 seconds

**Comment by tshirtman** [comment]
that's an application issue, not a kivy issue, make sure your app can access your mongo host.
