### ISSUE TITLE
No matching distribution found for io

### ISSUE THREAD

**Issue by GUNASEKHAR333** [kivy/buildozer#915]
i need to  build an apk file for the a python program which uses the python module "io". so, i added "io" in the requirements section of buildozer.spec. while i ran the command "buildozer android debug deploy run", the errors raised are "could not find a version that satisfies the requirement io (from -r requirements.txt (line 5)) " and "No matching distribution found for io (from -r requirements.txt (line 5))".
please help me how to resolve this error.

**Comment by AndreMiras** [comment]
But `io` doesn't exist on pypi it's a core module. Buildozer requirements works the same way as pip one.
If it's a core module you don't need to pip install it.

**Comment by GUNASEKHAR333** [comment]
> But `io` doesn't exist on pypi it's a core module. Buildozer requirements works the same way as pip one.
> If it's a core module you don't need to pip install it.

io is installed in my system. nothing is wrong with it. while building apk , buildozer downloads the recipes of all the modules used in the program.The error i specified is the one raised while downloading the recipe of io.

**Comment by AndreMiras** [comment]
What I mean is we don't pip install `io` it's part of the standard Python distribution.
https://docs.python.org/3/library/io.html
So it means you don't need to put it in your requirements. It's currently failing at recipe time because you have it in your requirement which is a nonsense for a core module
