### ISSUE TITLE
sdkmanager is notinstalled

### ISSUE THREAD

**Issue by RianFC** [kivy/buildozer#927]
### Versions

* Python:Python 3.7.3
* OS:4.19.49-1-MANJARO
* Buildozer:0.40.dev0

### Description

sdkmanager path "/home/olixao/.buildozer/android/platform/android-sdk/tools/bin/sdkmanager" does not exist, sdkmanager is notinstalled

### buildozer.spec
Command:
```sh
buildozer android debug
```

Spec file:
```
[app]

# (str) Title of your application
title = My Application

# (str) Package name
package.name = myapp

# (str) Package domain (needed for android/ios packaging)
package.domain = org.test

# (str) Source code where the main.py live
source.dir = .

# (list) Source files to include (let empty to include all the files)
source.include_exts = py,png,jpg,kv,atlas

# (list) List of inclusions using pattern matching
#source.include_patterns = assets/*,images/*.png

# (list) Source files to exclude (let empty to not exclude anything)
#source.exclude_exts = spec

# (list) List of directory to exclude (let empty to not exclude anything)
#source.exclude_dirs = tests, bin

# (list) List of exclusions using pattern matching
#source.exclude_patterns = license,images/*/*.jpg

# (str) Application versioning (method 1)
version = 0.1

# (str) Application versioning (method 2)
# version.regex = __version__ = ['"](.*)['"]
# version.filename = %(source.dir)s/main.py

# (list) Application requirements
# comma separated e.g. requirements = sqlite3,kivy
requirements = python3crystax,kivy

# (str) Custom source folders for requirements
# Sets custom source for any requirements with recipes
# requirements.source.kivy = ../../kivy

# (list) Garden requirements
#garden_requirements =

# (str) Presplash of the application
#presplash.filename = %(source.dir)s/data/presplash.png

# (str) Icon of the application
#icon.filename = %(source.dir)s/data/icon.png

# (str) Supported orientation (one of landscape, sensorLandscape, portrait or all)
orientation = portrait

# (list) List of service to declare
#services = NAME:ENTRYPOINT_TO_PY,NAME2:ENTRYPOINT2_TO_PY

#
# OSX Specific
#

#
# author = © Copyright Info

# change the major version of python used by the app
osx.python_version = 3

# Kivy version to use
osx.kivy_version = 1.9.1

#
# Android specific
#

# (bool) Indicate if the application should be fullscreen or not
fullscreen = 0

# (string) Presplash background color (for new android toolchain)
# Supported formats are: #RRGGBB #AARRGGBB or one of the following names:
# red, blue, green, black, white, gray, cyan, magenta, yellow, lightgray,
# darkgray, grey, lightgrey, darkgrey, aqua, fuchsia, lime, maroon, navy,
# olive, purple, silver, teal.
#android.presplash_color = #FFFFFF

# (list) Permissions
#android.permissions = INTERNET

# (int) Target Android API, should be as high as possible.
#android.api = 27

# (int) Minimum API your APK will support.
#android.minapi = 21

# (int) Android SDK version to use
#android.sdk = 20

# (str) Android NDK version to use
#android.ndk = 17c

# (int) Android NDK API to use. This is the minimum API your app will support, it should usually match android.minapi.
#android.ndk_api = 21

# (bool) Use --private data storage (True) or --dir public storage (False)
#android.private_storage = True

# (str) Android NDK directory (if empty, it will be automatically downloaded.)
android.ndk_path = ~/.buildozer/crystax-ndk

# (str) Android SDK directory (if empty, it will be automatically downloaded.)
#android.sdk_path =

# (str) ANT directory (if empty, it will be automatically downloaded.)
#android.ant_path =

# (bool) If True, then skip trying to update the Android sdk
# This can be useful to avoid excess Internet downloads or save time
# when an update is due and you just want to test/build your package
# android.skip_update = False

# (bool) If True, then automatically accept SDK license
# agreements. This is intended for automation only. If set to False,
# the default, you will be shown the license when first running
# buildozer.
# android.accept_sdk_license = False

# (str) Android entry point, default is ok for Kivy-based app
#android.entrypoint = org.renpy.android.PythonActivity

# (list) Pattern to whitelist for the whole project
#android.whitelist =

# (str) Path to a custom whitelist file
#android.whitelist_src =

# (str) Path to a custom blacklist file
#android.blacklist_src =

# (list) List of Java .jar files to add to the libs so that pyjnius can access
# their classes. Don't add jars that you do not need, since extra jars can slow
# down the build process. Allows wildcards matching, for example:
# OUYA-ODK/libs/*.jar
#android.add_jars = foo.jar,bar.jar,path/to/more/*.jar

# (list) List of Java files to add to the android project (can be java or a
# directory containing the files)
#android.add_src =

# (list) Android AAR archives to add (currently works only with sdl2_gradle
# bootstrap)
#android.add_aars =

# (list) Gradle dependencies to add (currently works only with sdl2_gradle
# bootstrap)
#android.gradle_dependencies =

# (list) Java classes to add as activities to the manifest.
#android.add_activites = com.example.ExampleActivity

# (str) python-for-android branch to use, defaults to master
#p4a.branch = master

# (str) OUYA Console category. Should be one of GAME or APP
# If you leave this blank, OUYA support will not be enabled
#android.ouya.category = GAME

# (str) Filename of OUYA Console icon. It must be a 732x412 png image.
#android.ouya.icon.filename = %(source.dir)s/data/ouya_icon.png

# (str) XML file to include as an intent filters in <activity> tag
#android.manifest.intent_filters =

# (str) launchMode to set for the main activity
#android.manifest.launch_mode = standard

# (list) Android additional libraries to copy into libs/armeabi
#android.add_libs_armeabi = libs/android/*.so
#android.add_libs_armeabi_v7a = libs/android-v7/*.so
#android.add_libs_x86 = libs/android-x86/*.so
#android.add_libs_mips = libs/android-mips/*.so

# (bool) Indicate whether the screen should stay on
# Don't forget to add the WAKE_LOCK permission if you set this to True
#android.wakelock = False

# (list) Android application meta-data to set (key=value format)
#android.meta_data =

# (list) Android library project to add (will be added in the
# project.properties automatically.)
#android.library_references =

# (str) Android logcat filters to use
#android.logcat_filters = *:S python:D

# (bool) Copy library instead of making a libpymodules.so
#android.copy_libs = 1

# (str) The Android arch to build for, choices: armeabi-v7a, arm64-v8a, x86
android.arch = armeabi-v7a

#
# Python for android (p4a) specific
#

# (str) python-for-android git clone directory (if empty, it will be automatically cloned from github)
#p4a.source_dir =

# (str) The directory in which python-for-android should look for your own build recipes (if any)
#p4a.local_recipes =

# (str) Filename to the hook for p4a
#p4a.hook =

# (str) Bootstrap to use for android builds
# p4a.bootstrap = sdl2

# (int) port number to specify an explicit --port= p4a argument (eg for bootstrap flask)
#p4a.port =


#
# iOS specific
#

# (str) Path to a custom kivy-ios folder
#ios.kivy_ios_dir = ../kivy-ios
# Alternately, specify the URL and branch of a git checkout:
ios.kivy_ios_url = https://github.com/kivy/kivy-ios
ios.kivy_ios_branch = master

# Another platform dependency: ios-deploy
# Uncomment to use a custom checkout
#ios.ios_deploy_dir = ../ios_deploy
# Or specify URL and branch
ios.ios_deploy_url = https://github.com/phonegap/ios-deploy
ios.ios_deploy_branch = 1.7.0

# (str) Name of the certificate to use for signing the debug version
# Get a list of available identities: buildozer ios list_identities
#ios.codesign.debug = "iPhone Developer: <lastname> <firstname> (<hexstring>)"

# (str) Name of the certificate to use for signing the release version
#ios.codesign.release = %(ios.codesign.debug)s


[buildozer]

# (int) Log level (0 = error only, 1 = info, 2 = debug (with command output))
log_level = 2

# (int) Display warning if buildozer is run as root (0 = False, 1 = True)
warn_on_root = 1

# (str) Path to build artifact storage, absolute or relative to spec file
# build_dir = ./.buildozer

# (str) Path to build output (i.e. .apk, .ipa) storage
# bin_dir = ./bin

#    -----------------------------------------------------------------------------
#    List as sections
#
#    You can define all the "list" as [section:key].
#    Each line will be considered as a option to the list.
#    Let's take [app] / source.exclude_patterns.
#    Instead of doing:
#
#[app]
#source.exclude_patterns = license,data/audio/*.wav,data/images/original/*
#
#    This can be translated into:
#
#[app:source.exclude_patterns]
#license
#data/audio/*.wav
#data/images/original/*
#


#    -----------------------------------------------------------------------------
#    Profiles
#
#    You can extend section / key with a profile
#    For example, you want to deploy a demo version of your application without
#    HD content. You could first change the title to add "(demo)" in the name
#    and extend the excluded directories to remove the HD content.
#
#[app@demo]
#title = My Application (demo)
#
#[app:source.exclude_patterns@demo]
#images/hd/*
#
#    Then, invoke the command line with the "demo" profile:
#
#buildozer --profile demo android debug

```

### Logs

```
# Check configuration tokens
# Ensure build layout
# Check configuration tokens
# Read available permissions from api-versions.xml
# Preparing build
# Check requirements for android
# Run 'dpkg --version'
# Cwd None
Programa de gerenciamento de pacotes Debian 'dpkg' versão 1.18.25 (amd64).
Isto é software livre; veja a GNU General Public License versão 2 ou
posterior para condições de cópia. Não existe NENHUMA garantia.
# Search for Git (git)
#  -> found at /usr/bin/git
# Search for Cython (cython)
#  -> found at /usr/local/bin/cython
# Search for Java compiler (javac)
#  -> found at /usr/lib/jvm/java-8-openjdk/bin/javac
# Search for Java keytool (keytool)
#  -> found at /usr/lib/jvm/java-8-openjdk/jre/bin/keytool
# Install platform
# Run '/usr/local/bin/python3.8 -m pip install -q --user \'appdirs\' \'colorama>=0.3.3\' \'jinja2\' \'six\' \'enum34; python_version<"3.4"\' \'sh>=1.10; sys_platform!="nt"\' \'pep517\' \'pytoml\' \'virtualenv\''
# Cwd None
# Apache ANT found at /home/olixao/.buildozer/android/platform/apache-ant-1.9.4
# Android SDK found at /home/olixao/.buildozer/android/platform/android-sdk
# Android NDK found at /home/olixao/.buildozer/crystax-ndk
# Installing/updating SDK platform tools if necessary
# Check configuration tokens
# sdkmanager path "/home/olixao/.buildozer/android/platform/android-sdk/tools/bin/sdkmanager" does not exist, sdkmanager is notinstalled
```

**Comment by davidecavestro** [comment]
I got the same error message: turned out I had a partial/corrupted zip file at 
`~/.buildozer/android/platform/android-sdk/sdk-tools-linux-4333796.zip`

I made it work replacing the partial zip with a complete one and rhen reissuing the buildozer command.
i.e. on my Debian this completed the download of the zip
```
cd ~/.buildozer/android/platform/android-sdk && \
curl -L -O -C - https://dl.google.com/android/repository/sdk-tools-linux-4333796.zip
```

**Comment by AndreMiras** [comment]
Yes that could be it. Also before trying to reinstall I would advise you to remove crystax and use the Android ndk

**Comment by kagawad** [comment]
@AndreMiras  how to reinstall ? crystax

**Comment by kagawad** [comment]
i also have the same error
pewpew@pewpew:~/Desktop/myfirstapp$ buildozer android debug
# Check configuration tokens
# Ensure build layout
# Check configuration tokens
# Read available permissions from api-versions.xml
# Preparing build
# Check requirements for android
# Run 'dpkg --version'
# Cwd None
Debian 'dpkg' package management program version 1.19.0.5 (amd64).
This is free software; see the GNU General Public License version 2 or
later for copying conditions. There is NO warranty.
# Search for Git (git)
#  -> found at /usr/bin/git
# Search for Cython (cython)
#  -> found at /usr/local/bin/cython
# Search for Java compiler (javac)
#  -> found at /usr/lib/jvm/java-8-openjdk-amd64/bin/javac
# Search for Java keytool (keytool)
#  -> found at /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/keytool
# Install platform
# Run 'git config --get remote.origin.url'
# Cwd /home/pewpew/Desktop/myfirstapp/.buildozer/android/platform/python-for-android
https://github.com/kivy/python-for-android.git
# Run 'git branch -vv'
# Cwd /home/pewpew/Desktop/myfirstapp/.buildozer/android/platform/python-for-android
* master dd69749f [origin/master] Merge pull request #1955 from kivy/release-2019.08.09
# Run '/usr/bin/python -m pip install -q --user \'appdirs\' \'colorama>=0.3.3\' \'jinja2\' \'six\' \'enum34; python_version<"3.4"\' \'sh>=1.10; sys_platform!="nt"\' \'pep517\' \'pytoml\' \'virtualenv\''
# Cwd None
# Apache ANT found at /home/pewpew/.buildozer/android/platform/apache-ant-1.9.4
# Android SDK found at /home/pewpew/.buildozer/android/platform/android-sdk
# Recommended android's NDK version by p4a is: 17c
# Android NDK is missing, downloading
# Downloading https://dl.google.com/android/repository/android-ndk-r17c-linux-x86_64.zip
# Unpacking Android NDK
# Run 'unzip -q /home/pewpew/.buildozer/android/platform/android-ndk-r17c-linux-x86_64.zip'
# Cwd /home/pewpew/.buildozer/android/platform
# Rename /home/pewpew/.buildozer/android/platform/android-ndk-r17c to /home/pewpew/.buildozer/android/platform/android-ndk-r17c
# Android NDK installation done.
# Installing/updating SDK platform tools if necessary
# Check configuration tokens
# sdkmanager path "/home/pewpew/.buildozer/android/platform/android-sdk/tools/bin/sdkmanager" does not exist, sdkmanager is notinstalled

**Comment by kagawad** [comment]
i also have the same error
pewpew@pewpew:~/Desktop/myfirstapp$ buildozer android debug
# Check configuration tokens
# Ensure build layout
# Check configuration tokens
# Read available permissions from api-versions.xml
# Preparing build
# Check requirements for android
# Run 'dpkg --version'
# Cwd None
Debian 'dpkg' package management program version 1.19.0.5 (amd64).
This is free software; see the GNU General Public License version 2 or
later for copying conditions. There is NO warranty.
# Search for Git (git)
#  -> found at /usr/bin/git
# Search for Cython (cython)
#  -> found at /usr/local/bin/cython
# Search for Java compiler (javac)
#  -> found at /usr/lib/jvm/java-8-openjdk-amd64/bin/javac
# Search for Java keytool (keytool)
#  -> found at /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/keytool
# Install platform
# Run 'git config --get remote.origin.url'
# Cwd /home/pewpew/Desktop/myfirstapp/.buildozer/android/platform/python-for-android
https://github.com/kivy/python-for-android.git
# Run 'git branch -vv'
# Cwd /home/pewpew/Desktop/myfirstapp/.buildozer/android/platform/python-for-android
* master dd69749f [origin/master] Merge pull request #1955 from kivy/release-2019.08.09
# Run '/usr/bin/python -m pip install -q --user \'appdirs\' \'colorama>=0.3.3\' \'jinja2\' \'six\' \'enum34; python_version<"3.4"\' \'sh>=1.10; sys_platform!="nt"\' \'pep517\' \'pytoml\' \'virtualenv\''
# Cwd None
# Apache ANT found at /home/pewpew/.buildozer/android/platform/apache-ant-1.9.4
# Android SDK found at /home/pewpew/.buildozer/android/platform/android-sdk
# Recommended android's NDK version by p4a is: 17c
# Android NDK is missing, downloading
# Downloading https://dl.google.com/android/repository/android-ndk-r17c-linux-x86_64.zip
# Unpacking Android NDK
# Run 'unzip -q /home/pewpew/.buildozer/android/platform/android-ndk-r17c-linux-x86_64.zip'
# Cwd /home/pewpew/.buildozer/android/platform
# Rename /home/pewpew/.buildozer/android/platform/android-ndk-r17c to /home/pewpew/.buildozer/android/platform/android-ndk-r17c
# Android NDK installation done.
# Installing/updating SDK platform tools if necessary
# Check configuration tokens
# sdkmanager path "/home/pewpew/.buildozer/android/platform/android-sdk/tools/bin/sdkmanager" does not exist, sdkmanager is notinstalled
asd

**Comment by olixao** [comment]
ok

**Comment by AndreMiras** [comment]
Yes I would try all of the following:

1. running from scratch by deleting the `~/.buildozer` folder
2. make sure `buildozer` is up to date with latest master
3. change `android.accept_sdk_license` to `True` in your `buildozer.spec`
4. install buildozer from master `pip install --upgrade --user https://github.com/kivy/buildozer/archive/e58ad28.zip`

Last please when you share logs, use the triple backticks, pastebin or whatever you prefer to make it readable. Otherwise you see it's sometimes bold and miss some info. You can edit your answer when you see it looks like this mess.

**Comment by hamzashadeez** [comment]
**cd** to this directory /home/hamza/.buildozer/android/platform/android-sdk and '**ls**', you will see the zip file, you just need to unzip it with `unzip *zip`. this is how i really fixed the problem

**Comment by pavanbhat1999** [comment]
Sorry guys, But any of your suggested method is not working for me  So could anyone suggest better method.
![Screenshot from 2020-01-23 09-26-26](https://user-images.githubusercontent.com/47946571/72955644-c10c9b00-3dc2-11ea-88d5-19744ceddfd4.png)

**Comment by Erickfgfg** [comment]
O meu esta dando os mesmos problemas...

**Comment by francescopelizza-omega** [comment]
as solved here https://stackoverflow.com/questions/59330223/sdkmanager-not-installed (but not fully explained)

starting from the error:
# sdkmanager path "/home/phoenix/.buildozer/android/platform/android-sdk/tools/bin/sdkmanager" does not exist, sdkmanager is notinstalled

consider this piece of path: .buildozer/android/platform/android-sdk

sitting at your folder project (../your_app/buildozer.spec)

cd .buildozer/android/platform/android-sdk
remove any zip file you find (IF ANY) there about SDK.....
then download:
curl -L -O -C - https://dl.google.com/android/repository/sdk-tools-linux-4333796.zip

then unzip file:
unzip sdk-tools-linux-4333796.zip

pwd

copy and paste pwd output to buildozer.spec line (no quotes needed):
android.sdk_path = PWD_OUTPUT

save buildozer.spec and then run

buildozer android debug deploy run (or -v android release)

**Comment by francescopelizza-omega** [comment]
Well of course.....you anyway need android studio installed.....

the SDKMANAGER will look up for .android folder in home path...which comes with android studio

you may need to install the latest SDK command line tool and you're good to go....

if you still have problems.....install from android studio not just the latest SDK command line tool but also additional things such as NDK ans SDK build tools

to do so you open android studio

activity panel on android >Tools-> SDK MANAGER-> ANDROID SDK->(tab) SDK tools and you thick "show package details"

so you thick old versions of NDK, SDK (command line and buildtools)

you click apply, you accept and wait for finishing

then you're good to go

enjoy

**Comment by nlhnt** [comment]
Today I ran into this, I decided to manually unzip the downloaded sdk.

**Comment by tasen-sp** [comment]
> **cd** to this directory /home/hamza/.buildozer/android/platform/android-sdk and '**ls**', you will see the zip file, you just need to unzip it with `unzip *zip`. this is how i really fixed the problem

Thanks a lot. By there will be two zip files there first one is not unzipable .we should unzip the second one only.

**Comment by leycec** [comment]
@RianFC: Would it be possible to reopen this? [PEBKAC](https://www.computerhope.com/jargon/p/pebkac.htm) issues like this are *super* annoying. But... I just hit this, too. :sob: 

Ideally, Buildozer should either:

* Automate the extraction of the appropriate `~/.buildozer/android/platform/android-sdk/*.zip` file(s) on behalf of the user.
* Print [detailed instructions manually walking the user through this installation process](https://github.com/kivy/buildozer/issues/927#issuecomment-611621080) – probably by just printing the URL to a section of Buildozer's online documentation.

App development is hard enough as it is, right? We can make this a bit easier for everyone out there in the trenches.

**Comment by Ridola20** [comment]
can someone pls help me debug mine, having too many problems that are pissing me off right now

Pls
