### ISSUE TITLE
ERROR: can't install numpy as requirement. unknown url type

### ISSUE THREAD

**Issue by MounirHader** [kivy/buildozer#933]
Buildozer cannot get the numpy package from the corresponding page when installing as requirement (in the .spec file)

`buildozer android debug`

The error seems to be somewhere in:
```
Download error on https://pypi.org/simple/numpy/: unknown url type: https -- Some packages may not be found!
Couldn't find index page for 'numpy' (maybe misspelled?)
Download error on https://pypi.org/simple/: unknown url type: https -- Some packages may not be found!
```

The page https://pypi.org/simple/numpy/ does actually exist.

Final output error:
`distutils.errors.DistutilsError: Could not find suitable distribution for Requirement.parse('numpy==1.15.1')`

Is this a bug in the pypi URL that is set as standard?

### Versions
* Python: 3.7
* OS: Ubuntu 18.04

**Comment by MounirHader** [comment]
This is actually not a numpy problem but matplotlib, which is also listed as requirement in the .spec file. Without it no errors show up. 

```
BUILDING MATPLOTLIB
            matplotlib: yes [3.0.3]
                python: yes [3.7.1 (default, Jul 10 2019, 11:07:43)  [GCC
                        7.4.0]]
              platform: yes [linux]

REQUIRED DEPENDENCIES AND EXTENSIONS
                 numpy: yes [not found. pip may install it below.]
      install_requires: yes [handled by setuptools]
                libagg: yes [pkg-config information for 'libagg' could not
                        be found. Using local copy.]
              freetype: yes [version 2.8.1]
                   png: yes [version 1.6.34]
                 qhull: yes [pkg-config information for 'libqhull' could not
                        be found. Using local copy.]

OPTIONAL SUBPACKAGES
           sample_data: no  [skipping due to configuration]
              toolkits: yes [installing]
                 tests: no  [skipping due to configuration]
        toolkits_tests: no  [skipping due to configuration]

OPTIONAL BACKEND EXTENSIONS
                   agg: yes [installing]
                 tkagg: no  [Disabled by patching during Android build]
                macosx: no  [skipping due to configuration]
             windowing: no  [skipping due to configuration]

OPTIONAL PACKAGE DATA
                  dlls: no  [skipping due to configuration]

Download error on https://pypi.org/simple/numpy/: unknown url type: https -- Some packages may not be found!
Couldn't find index page for 'numpy' (maybe misspelled?)
Download error on https://pypi.org/simple/: unknown url type: https -- Some packages may not be found!
```

Is this a buildozer bug?

**Comment by kingking888** [comment]
Excuseme, how can i run in windows?

**Comment by podraco** [comment]
have you tried to use a local copy of the repo?
### spect file
```
requirements = sdl2, python3, bla bla bla, numpy
requirements.source.numpy = /path/to/your/git/clone
```

**Comment by advent-embedded** [comment]
im encountering this error too, i tried many ways to fix but couldn't  succeed. Having numpy as local copy didn't work. Despite having numpy as local copy, matplotlib recipe tries to download numpy from predefined URL for its own compilation. The URL where it seeks numpy definitely works as i tried in browser for confirmation. i even tried building through private network w/o firewall. None of the attempt worked.

**Comment by AndreMiras** [comment]
It usually happens if the Python host was compiled without SSL support and also sometimes on a messed up Python installation.
You could try the fix described in this comment:
https://github.com/kivy/python-for-android/issues/1859#issuecomment-550022312

**Comment by AndreMiras** [comment]
Also documented in https://github.com/kivy/python-for-android/blob/56a6cf1/doc/source/troubleshooting.rst#sslerrorcant-connect-to-https-url-because-the-ssl-module-is-not-available
