### ISSUE TITLE
app crash

### ISSUE THREAD

**Issue by alfie0** [kivy/buildozer#939]
Below are the errors in logcat, Please help me thanks 

[catlog5.log](https://github.com/kivy/buildozer/files/3420181/catlog5.log)

[buildozer.spec.txt](https://github.com/kivy/buildozer/files/3422289/buildozer.spec.txt)

**Comment by AndreMiras** [comment]
You're trying to import a module `comms` that's not found.
```
07-23 12:04:12.217 10589 10610 I python  :  Traceback (most recent call last):
07-23 12:04:12.217 10589 10610 I python  :    File "/home/alfie/smoopi/.buildozer/android/app/main.py", line 33, in <module>
07-23 12:04:12.218 10589 10610 I python  :  ModuleNotFoundError: No module named 'comms'
07-23 12:04:12.218 10589 10610 I python  : Python for android ended
```
