### ISSUE TITLE
Buildozer failed to execute the last command

### ISSUE THREAD

**Issue by malvernbright** [kivy/buildozer#958]
# Command failed: git clone -b master --single-branch https://github.com/kivy/python-for-android.git python-for-android
# 
# Buildozer failed to execute the last command
# If the error is not obvious, please raise the log_level to 2
# and retry the latest command.
# In case of a bug report, please add a full log with log_level = 2

**Comment by AndreMiras** [comment]
Missing a lot of debug info. Please follow the issue template
