### ISSUE TITLE
please add aidl into Dockerfile

### ISSUE THREAD

**Issue by sdayu** [kivy/buildozer#960]
I tried to build android apk from Dockerfile. In the process `buildozer android debug`, after the buildozer download essential packages, it shown aidl not found.

Please add **aidl** in to the Dockerfile under section
**# system requirements to build most of the recipes**
like
```
    zip \
    zlib1g-dev \
    aidl
```

thank.

**Comment by tshirtman** [comment]
it's not aidl that you need to install, this error actually means that android sdk is missing build tools
https://buildozer.readthedocs.io/en/latest/installation.html#aidl-not-found-please-install-it

```
    ~/.buildozer/android/platform/android-sdk/tools/bin/sdkmanager "build-tools;29.0.0"
```
