### ISSUE TITLE
Paused at  Installing/updating SDK platform tools if necessary

### ISSUE THREAD

**Issue by Shu-Ji** [kivy/buildozer#965]
### Versions

* Python: 3.7.2
* OS: Mac Darwin Kernel Version 18.7.0
* Buildozer: 0.39

### Description

Paused at command(I waited it for 5 hours for this command):
```
$ buildozer android debug deploy run
```

![image](https://user-images.githubusercontent.com/1127594/64470079-cf3d8000-d16f-11e9-8eb9-7686564900fb.png)

5 hours later, nothing happened, even no errors, just hangled.

### buildozer.spec
Command:
```sh
buildozer android debug deploy run
```

Spec file:
```
the default spec file generated by buildozer init
```

### Logs

```
# Check configuration tokens
# Ensure build layout
# Check configuration tokens
# Preparing build
# Check requirements for android
# Install platform
# Apache ANT found at /Users/finn/.buildozer/android/platform/apache-ant-1.9.4
# Android SDK found at /Users/finn/.buildozer/android/platform/android-sdk
# Android NDK found at /Users/finn/.buildozer/android/platform/android-ndk-r17c
# Installing/updating SDK platform tools if necessary
```

**Comment by AndreMiras** [comment]
Yes it's probably asking for the licence. Set log level to 2. An also I would recommend installing a more up to date buildozer version.
```
pip3 install --user https://github.com/kivy/buildozer/archive/182d13f.zip
```

**Comment by Shu-Ji** [comment]
Many Thinks!
It works now after set `log_level = 2` and accept the licence.

```
# (int) Log level (0 = error only, 1 = info, 2 = debug (with command output))
log_level = 2
```

**Comment by AndreMiras** [comment]
Thank you for confirming the fix 👍
