### ISSUE TITLE
buildozer fails with kivymd link

### ISSUE THREAD

**Issue by SidnetyAtheos** [kivy/buildozer#968]
Buildozer crashes when entering requirements = git https: //github.com/HeaTTheatR/KivyMD.git

When I withdraw, it generates the apk as usual, but the app doesn't open because it doesn't have the kivymd module
would be grateful if anyone can help

requirements=python3,kivy,android,jnius,pyjnius,plyer,requests,git+https://github.com/HeaTTheatR/KivyMD.git

error is bold
First error in terminal:

**ERROR: Command errored out with exit status 1: /home/sidney/PycharmProjects/AgendaFacil/.buildozer/android/platform/build-armeabi-v7a/build/venv/bin/python3 /home/sidney/PycharmProjects/AgendaFacil/.buildozer/android/platform/build-armeabi-v7a/build/venv/lib/python3.5/site-packages/pip/_vendor/pep517/_in_process.py get_requires_for_build_wheel /tmp/tmpsfsa8hnk Check the logs for full command output.**

the second:

  File "/home/sidney/PycharmProjects/AgendaFacil/.buildozer/android/platform/build-armeabi-v7a/build/venv/lib/python3.5/site-packages/pip/_internal/utils/misc.py", line 931, in call_subprocess
    raise InstallationError(exc_msg)
pip._internal.exceptions.InstallationError: Command errored out with exit status 1: /home/sidney/PycharmProjects/AgendaFacil/.buildozer/android/platform/build-armeabi-v7a/build/venv/bin/python3 /home/sidney/PycharmProjects/AgendaFacil/.buildozer/android/platform/build-armeabi-v7a/build/venv/lib/python3.5/site-packages/pip/_vendor/pep517/_in_process.py get_requires_for_build_wheel /tmp/tmpsfsa8hnk Check the logs for full command output.

  STDERR:

# Command failed: /usr/local/bin/python3.7 -m pythonforandroid.toolchain create --dist_name=myapp --bootstrap=sdl2 --requirements=python3,kivy,android,jnius,pyjnius,plyer,requests,git+https://github.com/HeaTTheatR/KivyMD.git --arch armeabi-v7a --copy-libs --color=always --storage-dir="/home/sidney/PycharmProjects/AgendaFacil/.buildozer/android/platform/build-armeabi-v7a" --ndk-api=21
# ENVIRONMENT:
#     LS_COLORS = 'rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=00:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.Z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.zst=01;31:*.tzst=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.jpg=01;35:*.jpeg=01;35:*.mjpg=01;35:*.mjpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=00;36:*.au=00;36:*.flac=00;36:*.m4a=00;36:*.mid=00;36:*.midi=00;36:*.mka=00;36:*.mp3=00;36:*.mpc=00;36:*.ogg=00;36:*.ra=00;36:*.wav=00;36:*.oga=00;36:*.opus=00;36:*.spx=00;36:*.xspf=00;36:'
#     INSIDE_NEMO_PYTHON = ''
#     LANG = 'pt_BR.UTF-8'
#     DISPLAY = ':0'
#     GTK_OVERLAY_SCROLLING = '1'
#     COLORTERM = 'truecolor'
#     XDG_VTNR = '7'
#     SSH_AUTH_SOCK = '/run/user/1000/keyring/ssh'
#     XDG_SESSION_ID = '1'
#     XDG_GREETER_DATA_DIR = '/var/lib/lightdm/data/sidney'
#     USER = 'sidney'
#     DESKTOP_SESSION = 'cinnamon'
#     QT_QPA_PLATFORMTHEME = 'gtk2'
#     PWD = '/home/sidney/PycharmProjects/AgendaFacil'
#     HOME = '/home/sidney'
#     SSH_AGENT_PID = '1018'
#     QT_ACCESSIBILITY = '1'
#     XDG_SESSION_TYPE = 'x11'
#     XDG_DATA_DIRS = '/usr/share/gnome:/home/sidney/.local/share/flatpak/exports/share:/var/lib/flatpak/exports/share:/usr/local/share:/usr/share'
#     XDG_SESSION_DESKTOP = 'cinnamon'
#     GJS_DEBUG_OUTPUT = 'stderr'
#     GTK_MODULES = 'gail:atk-bridge'
#     TERM = 'xterm-256color'
#     SHELL = '/bin/bash'
#     VTE_VERSION = '4601'
#     XDG_SEAT_PATH = '/org/freedesktop/DisplayManager/Seat0'
#     XDG_CURRENT_DESKTOP = 'X-Cinnamon'
#     GPG_AGENT_INFO = '/run/user/1000/gnupg/S.gpg-agent:0:1'
#     QT_LINUX_ACCESSIBILITY_ALWAYS_ON = '1'
#     SHLVL = '1'
#     XDG_SEAT = 'seat0'
#     WINDOWID = '92274694'
#     GDMSESSION = 'cinnamon'
#     GNOME_DESKTOP_SESSION_ID = 'this-is-deprecated'
#     LOGNAME = 'sidney'
#     DBUS_SESSION_BUS_ADDRESS = 'unix:path=/run/user/1000/bus'
#     XDG_RUNTIME_DIR = '/run/user/1000'
#     XAUTHORITY = '/home/sidney/.Xauthority'
#     XDG_SESSION_PATH = '/org/freedesktop/DisplayManager/Session0'
#     PATH = '/home/sidney/.buildozer/android/platform/apache-ant-1.9.4/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games:/usr/local/sbin:/usr/sbin:/sbin'
#     CINNAMON_VERSION = '4.2.4'
#     GJS_DEBUG_TOPICS = 'JS ERROR;JS LOG'
#     SESSION_MANAGER = 'local/mint:@/tmp/.ICE-unix/882,unix/mint:/tmp/.ICE-unix/882'
#     _ = '/usr/local/bin/buildozer'
#     PACKAGES_PATH = '/home/sidney/.buildozer/android/packages'
#     ANDROIDSDK = '/home/sidney/.buildozer/android/platform/android-sdk'
#     ANDROIDNDK = '/home/sidney/.buildozer/android/platform/android-ndk-r17c'
#     ANDROIDAPI = '27'
#     ANDROIDMINAPI = '21'
# 
# Buildozer failed to execute the last command
# The error might be hidden in the log above this error
# Please read the full log, and search for it before
# raising an issue with buildozer itself.
# In case of a bug report, please add a full log with log_level = 2

**Comment by andreisima** [comment]
This is support not issue.
requirements = python3, kivy, kivymd
