### ISSUE TITLE
How to specify my own versionCode

### ISSUE THREAD

**Issue by Denis-Memo** [kivy/buildozer#974]
I want to upload multiple apk to Play Store. One apk for _armeabi-v7a_ and other apk for _arm64-v8a_ because kivy don’t currently support multi-architecture builds in a single APK. To archive that i need to be very carefully with **versionCode** because of [this](https://proandroiddev.com/keep-salinity-with-your-versioncode-db2089b640b9) and [this](https://blog.danlew.net/2018/03/15/how-to-screw-over-your-beta-users-without-really-trying/) and [this](https://medium.com/@maxirosson/versioning-android-apps-d6ec171cfd82). Even worse there is no way to use same VERSION_CODE for multiple APKs in Google Play but **Buildozer** don't seems to give an option to change **versionCode**, the default Kivy **versionCode** is **721100** i don't even know why 721100. So i need to be able to specify my own version code based on Google instructions to include API level, screen sizes and application's version as explained [here](https://developer.android.com/google/play/publishing/multiple-apks.html#VersionCodes). In my case my minSdkVersion is 21, targetSdkVersion is 27 and my app version is 1.0.

**Comment by zebra-lucky** [comment]
as a possilbe solution is a proposed patch:

https://github.com/kivy/buildozer/pull/1079/commits/30e87ff066d1665a48a48149c5f394fc6e450503

#1079

**Comment by Denis-Memo** [comment]
Resolved

**Comment by GrandmasterSivaram** [comment]
Hi Dennis, could you please tell me, how u have done it. I have the same problem. Thanks!!

**Comment by kagune-code** [comment]
you don't need any such apps there is a way easier way
just uncomment and change this part of you code

```
# (int) overrides automatic versionCode computation (used in build.gradle)
# this is not the same as app version and should only be edited if you know what you're doing
# android.numeric_version = 1
```

if it is commented then it defaults to 7211 for armeabi-v7a and 8211 for arm64-v8a
just change it to something higher(like 8212) and re-run the buildozer android release,zipalign
 ,jarsign and reupload  

`

**Comment by kagune-code** [comment]
i meant to say buildozer spec file not code

**Comment by Jesscarlett** [comment]
Thank you. updating the buildozer spec file  - android.numeric_version = 1 worked! I used 7112 and 8212, I can upload my new apks to google store.
