### ISSUE TITLE
version `GLIBC_2.18' not found

### ISSUE THREAD

**Issue by ryuk0moon** [kivy/buildozer#992]
### Versions

* Python:
* OS:
* Buildozer:

### Description

// REPLACE ME: What are you trying to get done, what has happened, what went wrong, and what did you expect?

### buildozer.spec
Command:
```sh
// REPLACE ME: buildozer command ran? e.g. buildozer android debug
```

Spec file:
```
// REPLACE ME: Paste your buildozer.spec file here
```

### Logs

```
// REPLACE ME: Paste the build ouput containing the error
```
[INFO]:    -> running perl Configure shared no-dso no...(and 37 more)
[INFO]:    Applying patch disable-sover.patch                                  
[INFO]:    -> running patch -t -d /home/ryuk/workspa...(and 283 more)
[INFO]:    -> running make build_libs                                          
Exception in thread background thread for pid 116605:                          
Traceback (most recent call last):
  File "/opt/rh/rh-python36/root/usr/lib64/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/opt/rh/rh-python36/root/usr/lib64/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ryuk/.local/lib/python3.6/site-packages/sh.py", line 1540, in wrap
    fn(*args, **kwargs)
  File "/home/ryuk/.local/lib/python3.6/site-packages/sh.py", line 2459, in background_thread
    handle_exit_code(exit_code)
  File "/home/ryuk/.local/lib/python3.6/site-packages/sh.py", line 2157, in fn
    return self.command.handle_command_exit_code(exit_code)
  File "/home/ryuk/.local/lib/python3.6/site-packages/sh.py", line 815, in handle_command_exit_code
    raise exc
sh.ErrorReturnCode_2: 

  RAN: /usr/bin/make build_libs

  STDOUT:
/usr/bin/perl "-I." -Mconfigdata "util/dofile.pl" \
    "-oMakefile" crypto/include/internal/bn_conf.h.in > crypto/include/internal/bn_conf.h
/usr/bin/perl "-I." -Mconfigdata "util/dofile.pl" \
    "-oMakefile" crypto/include/internal/dso_conf.h.in > crypto/include/internal/dso_conf.h
/usr/bin/perl "-I." -Mconfigdata "util/dofile.pl" \
    "-oMakefile" include/openssl/opensslconf.h.in > include/openssl/opensslconf.h
make depend && make _build_libs
make[1]: Entering directory `/home/ryuk/workspace/test/testpython/kivy/.buildozer/android/platform/build-armeabi-v7a/build/other_builds/openssl/armeabi-v7a__ndk_target_21/openssl1.1'
make[1]: Leaving directory `/home/ryuk/workspace/test/testpython/kivy/.buildozer/android/platform/build-armeabi-v7a/build/other_builds/openssl/armeabi-v7a__ndk_target_21/openssl1.1'
make[1]: Entering directory `/home/ryuk/workspace/test/testpython/kivy/.buildozer/android/platform/build-armeabi-v7a/build/other_builds/openssl/armeabi-v7a__ndk_target_21/openssl1.1'
/home/ryuk/.buildozer/android/platform/android-ndk-r17c/toolchains/llvm/prebuilt/linux-x86_64/bin/clang -DANDROID -fomit-frame-pointer -D__ANDROID_API__=21 -target armv7a-none-linux-androideabi -gcc-toolchain /home/ryuk/.buildozer/android/platform/android-ndk-r17c/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64 -isystem /home/ryuk/.buildozer/android/platform/android-ndk-r17c/sysroot/usr/include/arm-linux-androideabi -I/home/ryuk/.buildozer/android/platform/android-ndk-r17c/sysroot/usr/include/arm-linux-androideabi -isysroot /home/ryuk/.buildozer/android/platform/android-ndk-r17c/sysroot -I/home/ryuk/workspace/test/testpython/kivy/.buildozer/android/platform/build-armeabi-v7a/build/python-installs/myapp/include/python3.7  -I. -Iinclude -fPIC -pthread  -target armv7a-linux-androideabi -gcc-toolchain /home/ryuk/.buildozer/android/platform/android-ndk-r17c/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64 --sysroot=/home/ryuk/.buildozer/android/platform/android-ndk-r17c/platforms/android-21/arch-arm -Wall -O3 -DOPENSSL_USE_NODELETE -DOPENSSL_PIC -DOPENSSLDIR="\"/usr/local/ssl\"" -DENGINESDIR="\"/usr/local/lib/engines-1.1\"" -D__ANDROID_API__=21 -isystem /home/ryuk/.buildozer/android/platform/android-ndk-r17c/sysroot/usr/include/arm-linux-androideabi -isystem /home/ryuk/.buildozer/android/platform/android-ndk-r17c/sysroot/usr/include -DNDEBUG -D__ANDROID_API__=21  -c -o apps/app_rand.o apps/app_rand.c
/home/ryuk/.buildozer/android/platform/android-ndk-r17c/toolchains/llvm/prebuilt/linux-x86_64/bin/clang: /lib64/libc.so.6: version `GLIBC_2.18' not found (required by /home/ryuk/.buildozer/android/platform/android-ndk-r17c/toolchains/llvm/prebuilt/linux-x86_64/bin/../lib64/libc++.so.1)
make[1]: *** [apps/app_rand.o] Error 1
make[1]: Leaving directory `/home/ryuk/workspace/test/testpython/kivy/.buildozer/android/platform/build-armeabi-v7a/build/other_builds/openssl/armeabi-v7a__ndk_target_21/openssl1.1'
make: *** [build_libs] Error 2

  STDERR:

Traceback (most recent call last):
  File "/opt/rh/rh-python36/root/usr/lib64/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/opt/rh/rh-python36/root/usr/lib64/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/ryuk/workspace/test/testpython/kivy/.buildozer/android/platform/python-for-android/pythonforandroid/toolchain.py", line 1192, in <module>
    main()
  File "/home/ryuk/workspace/test/testpython/kivy/.buildozer/android/platform/python-for-android/pythonforandroid/entrypoints.py", line 18, in main
    ToolchainCL()
  File "/home/ryuk/workspace/test/testpython/kivy/.buildozer/android/platform/python-for-android/pythonforandroid/toolchain.py", line 668, in __init__
    getattr(self, args.subparser_name.replace('-', '_'))(args)
  File "/home/ryuk/workspace/test/testpython/kivy/.buildozer/android/platform/python-for-android/pythonforandroid/toolchain.py", line 153, in wrapper_func
    build_dist_from_args(ctx, dist, args)
  File "/home/ryuk/workspace/test/testpython/kivy/.buildozer/android/platform/python-for-android/pythonforandroid/toolchain.py", line 206, in build_dist_from_args
    args, "ignore_setup_py", False
  File "/home/ryuk/workspace/test/testpython/kivy/.buildozer/android/platform/python-for-android/pythonforandroid/build.py", line 577, in build_recipes
    recipe.build_arch(arch)
  File "/home/ryuk/workspace/test/testpython/kivy/.buildozer/android/platform/python-for-android/pythonforandroid/recipes/openssl/__init__.py", line 130, in build_arch
    shprint(sh.make, 'build_libs', _env=env)
  File "/home/ryuk/workspace/test/testpython/kivy/.buildozer/android/platform/python-for-android/pythonforandroid/logger.py", line 180, in shprint
    for line in output:
  File "/home/ryuk/.local/lib/python3.6/site-packages/sh.py", line 863, in next
    self.wait()
  File "/home/ryuk/.local/lib/python3.6/site-packages/sh.py", line 792, in wait
    self.handle_command_exit_code(exit_code)
  File "/home/ryuk/.local/lib/python3.6/site-packages/sh.py", line 815, in handle_command_exit_code
    raise exc
sh.ErrorReturnCode_2: 

  RAN: /usr/bin/make build_libs

  STDOUT:
/usr/bin/perl "-I." -Mconfigdata "util/dofile.pl" \
    "-oMakefile" crypto/include/internal/bn_conf.h.in > crypto/include/internal/bn_conf.h
/usr/bin/perl "-I." -Mconfigdata "util/dofile.pl" \
    "-oMakefile" crypto/include/internal/dso_conf.h.in > crypto/include/internal/dso_conf.h
/usr/bin/perl "-I." -Mconfigdata "util/dofile.pl" \
    "-oMakefile" include/openssl/opensslconf.h.in > include/openssl/opensslconf.h
make depend && make _build_libs
make[1]: Entering directory `/home/ryuk/workspace/test/testpython/kivy/.buildozer/android/platform/build-armeabi-v7a/build/other_builds/openssl/armeabi-v7a__ndk_target_21/openssl1.1'
make[1]: Leaving directory `/home/ryuk/workspace/test/testpython/kivy/.buildozer/android/platform/build-armeabi-v7a/build/other_builds/openssl/armeabi-v7a__ndk_target_21/openssl1.1'
make[1]: Entering directory `/home/ryuk/workspace/test/testpython/kivy/.buildozer/android/platform/build-armeabi-v7a/build/other_builds/openssl/armeabi-v7a__ndk_target_21/openssl1.1'
/home/ryuk/.buildozer/android/platform/android-ndk-r17c/toolchains/llvm/prebuilt/linux-x86_64/bin/clang -DANDROID -fomit-frame-pointer -D__ANDROID_API__=21 -target armv7a-none-linux-androideabi -gcc-toolchain /home/ryuk/.buildozer/android/platform/android-ndk-r17c/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64 -isystem /home/ryuk/.buildozer/android/platform/android-ndk-r17c/sysroot/usr/include/arm-linux-androideabi -I/home/ryuk/.buildozer/android/platform/android-ndk-r17c/sysroot/usr/include/arm-linux-androideabi -isysroot /home/ryuk/.buildozer/android/platform/android-ndk-r17c/sysroot -I/home/ryuk/workspace/test/testpython/kivy/.buildozer/android/platform/build-armeabi-v7a/build/python-installs/myapp/include/python3.7  -I. -Iinclude -fPIC -pthread  -target armv7a-linux-androideabi -gcc-toolchain /home/ryuk/.buildozer/android/platform/android-ndk-r17c/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64 --sysroot=/home/ryuk/.buildozer/android/platform/android-ndk-r17c/platforms/android-21/arch-arm -Wall -O3 -DOPENSSL_USE_NODELETE -DOPENSSL_PIC -DOPENSSLDIR="\"/usr/local/ssl\"" -DENGINESDIR="\"/usr/local/lib/engines-1.1\"" -D__ANDROID_API__=21 -isystem /home/ryuk/.buildozer/android/platform/android-ndk-r17c/sysroot/usr/include/arm-linux-androideabi -isystem /home/ryuk/.buildozer/android/platform/android-ndk-r17c/sysroot/usr/include -DNDEBUG -D__ANDROID_API__=21  -c -o apps/app_rand.o apps/app_rand.c
/home/ryuk/.buildozer/android/platform/android-ndk-r17c/toolchains/llvm/prebuilt/linux-x86_64/bin/clang: /lib64/libc.so.6: version `GLIBC_2.18' not found (required by /home/ryuk/.buildozer/android/platform/android-ndk-r17c/toolchains/llvm/prebuilt/linux-x86_64/bin/../lib64/libc++.so.1)
make[1]: *** [apps/app_rand.o] Error 1
make[1]: Leaving directory `/home/ryuk/workspace/test/testpython/kivy/.buildozer/android/platform/build-armeabi-v7a/build/other_builds/openssl/armeabi-v7a__ndk_target_21/openssl1.1'
make: *** [build_libs] Error 2

**Comment by AndreMiras** [comment]
The build log is too short/truncated for us to know what exactly is happening.
Also it's missing some important info such as buildozer.spec and versions used.
Feel free to re-open providing all the required info
