### ISSUE TITLE
packaging error

### ISSUE THREAD

**Issue by onurkanbakirci** [kivy/buildozer#994]
When ı try to building .apk, ı got the following error:

# Command failed: /usr/bin/python3 -m pythonforandroid.toolchain create --dist_name=myapp --bootstrap=sdl2 --requirements=python2,hostpython2,hostpython3,python3crystax,kivy,plyer --arch armeabi-v7a --copy-libs --color=always --storage-dir="/home/onurkan/test/.buildozer/android/platform/build-armeabi-v7a" --ndk-api=21
# ENVIRONMENT:
#     LC_ADDRESS = 'tr_TR.UTF-8'
#     LC_NUMERIC = 'tr_TR.UTF-8'
#     LANG = 'en_US.UTF-8'
#     LC_NAME = 'tr_TR.UTF-8'
#     LC_TELEPHONE = 'tr_TR.UTF-8'
#     XDG_VTNR = '7'
#     XDG_GREETER_DATA_DIR = '/var/lib/lightdm-data/onurkan'
#     XDG_DATA_DIRS = '/usr/share/ubuntu:/usr/share/gnome:/usr/local/share:/usr/share:/var/lib/snapd/desktop'
#     TERM = 'xterm-256color'
#     LC_IDENTIFICATION = 'tr_TR.UTF-8'
#     ANDROIDSDK = '/home/onurkan/.buildozer/android/platform/android-sdk'
#     QT_IM_MODULE = 'ibus'
#     DBUS_SESSION_BUS_ADDRESS = 'unix:abstract=/tmp/dbus-RZ06hHDhbT'
#     QT4_IM_MODULE = 'xim'
#     DEFAULTS_PATH = '/usr/share/gconf/ubuntu.default.path'
#     JOB = 'unity-settings-daemon'
#     VTE_VERSION = '4205'
#     SESSIONTYPE = 'gnome-session'
#     PWD = '/home/onurkan/test'
#     SESSION = 'ubuntu'
#     GTK2_MODULES = 'overlay-scrollbar'
#     GNOME_KEYRING_CONTROL = ''
#     UPSTART_SESSION = 'unix:abstract=/com/ubuntu/upstart-session/1000/1583'
#     COMPIZ_CONFIG_PROFILE = 'ubuntu'
#     GPG_AGENT_INFO = '/home/onurkan/.gnupg/S.gpg-agent:0:1'
#     UPSTART_JOB = 'unity7'
#     GTK_MODULES = 'gail:atk-bridge:unity-gtk-module'
#     LANGUAGE = 'en_US'
#     XDG_SESSION_PATH = '/org/freedesktop/DisplayManager/Session0'
#     LESSCLOSE = '/usr/bin/lesspipe %s %s'
#     LC_MEASUREMENT = 'tr_TR.UTF-8'
#     WINDOWID = '69209135'
#     LS_COLORS = 'rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=00:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.Z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.jpg=01;35:*.jpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=00;36:*.au=00;36:*.flac=00;36:*.m4a=00;36:*.mid=00;36:*.midi=00;36:*.mka=00;36:*.mp3=00;36:*.mpc=00;36:*.ogg=00;36:*.ra=00;36:*.wav=00;36:*.oga=00;36:*.opus=00;36:*.spx=00;36:*.xspf=00;36:'
#     IM_CONFIG_PHASE = '1'
#     MANDATORY_PATH = '/usr/share/gconf/ubuntu.mandatory.path'
#     ANDROIDNDK = '/home/onurkan/.buildozer/crystax-ndk-10.3.2'
#     UPSTART_EVENTS = 'xsession started'
#     XDG_SESSION_ID = 'c2'
#     GTK_IM_MODULE = 'ibus'
#     USER = 'onurkan'
#     XDG_CONFIG_DIRS = '/etc/xdg/xdg-ubuntu:/usr/share/upstart/xdg:/etc/xdg'
#     GNOME_KEYRING_PID = ''
#     COMPIZ_BIN_PATH = '/usr/bin/'
#     XDG_SEAT_PATH = '/org/freedesktop/DisplayManager/Seat0'
#     LOGNAME = 'onurkan'
#     QT_QPA_PLATFORMTHEME = 'appmenu-qt5'
#     _ = '/usr/local/bin/buildozer'
#     LC_TIME = 'tr_TR.UTF-8'
#     XDG_SESSION_DESKTOP = 'ubuntu'
#     LC_PAPER = 'tr_TR.UTF-8'
#     GDM_LANG = 'en_US'
#     HOME = '/home/onurkan'
#     GNOME_DESKTOP_SESSION_ID = 'this-is-deprecated'
#     CLUTTER_IM_MODULE = 'xim'
#     XAUTHORITY = '/home/onurkan/.Xauthority'
#     XDG_RUNTIME_DIR = '/run/user/1000'
#     GDMSESSION = 'ubuntu'
#     OLDPWD = '/home/onurkan'
#     UNITY_HAS_3D_SUPPORT = 'true'
#     SHELL = '/bin/bash'
#     LC_MONETARY = 'tr_TR.UTF-8'
#     XDG_SESSION_TYPE = 'x11'
#     DISPLAY = ':0'
#     UNITY_DEFAULT_PROFILE = 'unity'
#     QT_LINUX_ACCESSIBILITY_ALWAYS_ON = '1'
#     XDG_CURRENT_DESKTOP = 'Unity'
#     XDG_SEAT = 'seat0'
#     SHLVL = '1'
#     XMODIFIERS = '@im=ibus'
#     QT_ACCESSIBILITY = '1'
#     PACKAGES_PATH = '/home/onurkan/.buildozer/android/packages'
#     DESKTOP_SESSION = 'ubuntu'
#     LESSOPEN = '| /usr/bin/lesspipe %s'
#     ANDROIDAPI = '27'
#     UPSTART_INSTANCE = ''
#     SSH_AUTH_SOCK = '/run/user/1000/keyring/ssh'
#     PATH = '/home/onurkan/.buildozer/android/platform/apache-ant-1.9.4/bin:/home/onurkan/bin:/home/onurkan/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/home/onurkan/.local/bin/'
#     INSTANCE = ''
#     ANDROIDMINAPI = '21'
# 
# Buildozer failed to execute the last command
# If the error is not obvious, please raise the log_level to 2
# and retry the latest command.
# In case of a bug report, please add a full log with log_level = 2

so, how can ı solve this problem?

**Comment by AndreMiras** [comment]
This bug report is not in the correct format, please follow the template as you create a new bug.
Also this is a bug tracker, for support requests use the forums or chat
