### ISSUE TITLE
Buildozer failed to execute the last command

### ISSUE THREAD

**Issue by ariaadhiguna99** [kivy/buildozer#999]
i got this error when i was trying to build android apk
>Traceback (most recent call last):
  File "/home/aa/anaconda3/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/aa/anaconda3/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/aa/kivytest/.buildozer/android/platform/python-for-android/pythonforandroid/toolchain.py", line 1192, in <module>
    main()
  File "/home/aa/kivytest/.buildozer/android/platform/python-for-android/pythonforandroid/entrypoints.py", line 18, in main
    ToolchainCL()
  File "/home/aa/kivytest/.buildozer/android/platform/python-for-android/pythonforandroid/toolchain.py", line 668, in __init__
    getattr(self, args.subparser_name.replace('-', '_'))(args)
  File "/home/aa/kivytest/.buildozer/android/platform/python-for-android/pythonforandroid/toolchain.py", line 146, in wrapper_func
    user_ndk_api=self.ndk_api)
  File "/home/aa/kivytest/.buildozer/android/platform/python-for-android/pythonforandroid/build.py", line 358, in prepare_build_environment
    raise IOError('Couldn\'t find a virtualenv executable, '
OSError: Couldn't find a virtualenv executable, you must install this to use p4a.
 Command failed: /home/aa/anaconda3/bin/python3 -m pythonforandroid.toolchain create --dist_name=myapp --bootstrap=sdl2 --requirements=python3,kivy --arch armeabi-v7a --copy-libs --color=always --storage-dir="/home/aa/kivytest/.buildozer/android/platform/build-armeabi-v7a" --ndk-api=21
 ENVIRONMENT:
     CLUTTER_IM_MODULE = 'xim'
     CONDA_SHLVL = '1'
     LS_COLORS = 'rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=00:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.Z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.zst=01;31:*.tzst=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.wim=01;31:*.swm=01;31:*.dwm=01;31:*.esd=01;31:*.jpg=01;35:*.jpeg=01;35:*.mjpg=01;35:*.mjpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=00;36:*.au=00;36:*.flac=00;36:*.m4a=00;36:*.mid=00;36:*.midi=00;36:*.mka=00;36:*.mp3=00;36:*.mpc=00;36:*.ogg=00;36:*.ra=00;36:*.wav=00;36:*.oga=00;36:*.opus=00;36:*.spx=00;36:*.xspf=00;36:'
     CONDA_EXE = '/home/aa/anaconda3/bin/conda'
     LC_MEASUREMENT = 'id_ID.UTF-8'
     LESSCLOSE = '/usr/bin/lesspipe %s %s'
     LC_PAPER = 'id_ID.UTF-8'
     LC_MONETARY = 'id_ID.UTF-8'
     XDG_MENU_PREFIX = 'gnome-'
     LANG = 'en_US.UTF-8'
     DISPLAY = ':0'
     GNOME_SHELL_SESSION_MODE = 'ubuntu'
     COLORTERM = 'truecolor'
     USERNAME = 'aa'
     CONDA_PREFIX = '/home/aa/anaconda3'
     XDG_VTNR = '2'
     SSH_AUTH_SOCK = '/run/user/1000/keyring/ssh'
     VIRTUAL_ENV = '/home/aa/kivy_venv'
     _CE_M = ''
     LC_NAME = 'id_ID.UTF-8'
     XDG_SESSION_ID = '2'
     USER = 'aa'
     DESKTOP_SESSION = 'ubuntu'
     QT4_IM_MODULE = 'xim'
     TEXTDOMAINDIR = '/usr/share/locale/'
     GNOME_TERMINAL_SCREEN = '/org/gnome/Terminal/screen/54844b73_1990_46d2_a97a_3aab772ea61d'
     PWD = '/home/aa/kivytest'
     HOME = '/home/aa'
     CONDA_PYTHON_EXE = '/home/aa/anaconda3/bin/python'
     TEXTDOMAIN = 'im-config'
     SSH_AGENT_PID = '1554'
     QT_ACCESSIBILITY = '1'
     XDG_SESSION_TYPE = 'x11'
     XDG_DATA_DIRS = '/usr/share/ubuntu:/usr/local/share/:/usr/share/:/var/lib/snapd/desktop'
     _CE_CONDA = ''
     XDG_SESSION_DESKTOP = 'ubuntu'
     LC_ADDRESS = 'id_ID.UTF-8'
     GJS_DEBUG_OUTPUT = 'stderr'
     LC_NUMERIC = 'id_ID.UTF-8'
     CONDA_PROMPT_MODIFIER = '(base) '
     GTK_MODULES = 'gail:atk-bridge'
     WINDOWPATH = '2'
     VTE_VERSION = '5202'
     TERM = 'xterm-256color'
     SHELL = '/bin/bash'
     QT_IM_MODULE = 'xim'
     XMODIFIERS = '@im=ibus'
     IM_CONFIG_PHASE = '2'
     XDG_CURRENT_DESKTOP = 'ubuntu:GNOME'
     GPG_AGENT_INFO = '/run/user/1000/gnupg/S.gpg-agent:0:1'
     GNOME_TERMINAL_SERVICE = ':1.60'
     XDG_SEAT = 'seat0'
     SHLVL = '1'
     LC_TELEPHONE = 'id_ID.UTF-8'
     GDMSESSION = 'ubuntu'
     GNOME_DESKTOP_SESSION_ID = 'this-is-deprecated'
     LOGNAME = 'aa'
     DBUS_SESSION_BUS_ADDRESS = 'unix:path=/run/user/1000/bus'
     XDG_RUNTIME_DIR = '/run/user/1000'
     XAUTHORITY = '/run/user/1000/gdm/Xauthority'
     XDG_CONFIG_DIRS = '/etc/xdg/xdg-ubuntu:/etc/xdg'
     PATH = '/home/aa/.buildozer/android/platform/apache-ant-1.9.4/bin:/home/aa/kivy_venv/bin:/home/aa/anaconda3/bin:/home/aa/anaconda3/condabin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin'
     LC_IDENTIFICATION = 'id_ID.UTF-8'
     PS1 = ('(kivy_venv) (base) \\[\\e]0;\\u@\\h: '
 '\\w\\a\\]${debian_chroot:+($debian_chroot)}\\[\\033[01;32m\\]\\u@\\h\\[\\033[00m\\]:\\[\\033[01;34m\\]\\w\\[\\033[00m\\]\\$ ')
     CONDA_DEFAULT_ENV = 'base'
     GJS_DEBUG_TOPICS = 'JS ERROR;JS LOG'
     SESSION_MANAGER = 'local/AA-UbuntuP:@/tmp/.ICE-unix/1459,unix/AA-UbuntuP:/tmp/.ICE-unix/1459'
     LESSOPEN = '| /usr/bin/lesspipe %s'
     GTK_IM_MODULE = 'ibus'
     LC_TIME = 'id_ID.UTF-8'
     _ = '/home/aa/anaconda3/bin/buildozer'
     OLDPWD = '/home/aa'
     PACKAGES_PATH = '/home/aa/.buildozer/android/packages'
     ANDROIDSDK = '/home/aa/.buildozer/android/platform/android-sdk'
     ANDROIDNDK = '/home/aa/.buildozer/android/platform/android-ndk-r17c'
     ANDROIDAPI = '27'
     ANDROIDMINAPI = '21'
     Buildozer failed to execute the last command
     The error might be hidden in the log above this error
     Please read the full log, and search for it before
     raising an issue with buildozer itself.
     In case of a bug report, please add a full log with log_level = 2

**Comment by tshirtman** [comment]
>  In case of a bug report, please add a full log with log_level = 2

please read the error messages before asking for help.

you would also have seen this

> raise IOError('Couldn't find a virtualenv executable, '
OSError: Couldn't find a virtualenv executable, you must install this to use p4a.

and that would have given you directions to solve it.

**Comment by Wisestjean** [comment]
**### Unable to create apk**
First time with buildozer , I am using KALI LINUX
/usr/bin/tar: SDL2_image-2.0.4/Xcode/Frameworks/webp.framework/Resources: Cannot create symlink to ‘Versions/Current/Resources’: Operation not permitted
/usr/bin/tar: SDL2_image-2.0.4/Xcode/Frameworks/webp.framework/webp: Cannot create symlink to ‘Versions/Current/webp’: Operation not permitted
/usr/bin/tar: SDL2_image-2.0.4/Xcode/Frameworks/webp.framework/Headers: Cannot create symlink to ‘Versions/Current/Headers’: Operation not permitted
/usr/bin/tar: SDL2_image-2.0.4/Xcode/Frameworks/webp.framework/Versions/Current: Cannot create symlink to ‘A’: Operation not permitted
/usr/bin/tar: Exiting with failure status due to previous errors


[errorHadling.txt](https://github.com/kivy/buildozer/files/8240859/errorHadling.txt)
[errorHadling.txt](https://github.com/kivy/buildozer/files/8240862/errorHadling.txt)

**Comment by IROPA-Zakarie** [comment]
i have the same error

**Comment by ZXTube** [comment]
Me too 😭😭😭
